apache/paimon

flink-table-store-core/pom.xml
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileFormat.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileFormatImpl.java
flink-table-store-core/src/test/java/file/FileFormatTest.java
pom.xml

Introduce file format class which creates reader and writer factories for specific file format.

[FLINK-25625] Introduce FileFormat

---

flink-table-store-core/pom.xml
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/KeyValue.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/KeyValueSerializer.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/ValueKind.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MemTable.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/SortBufferMemTable.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/Accumulator.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/DeduplicateAccumulator.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/ValueCountAccumulator.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/HeapMemorySegmentPool.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/ObjectSerializer.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/OffsetRowData.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/KeyValueSerializerTest.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestKeyValueGenerator.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/SortBufferMemTableTestBase.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/AccumulatorTestUtils.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/ObjectSerializerTestBase.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/OffsetRowDataTest.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/ReusingKeyValue.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/ReusingTestData.java

- Add OffsetRowData
- Add KeyValue and KeyValueSerializer
- Add MemTable and Accumulator

[FLINK-25627] Add basic structures of file store in table-store

---

flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/LevelSortedRun.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/Levels.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/SortedRun.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/CompactManager.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/CompactStrategy.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/CompactUnit.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/IntervalPartition.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/UniversalCompaction.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/CompactManagerTest.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/IntervalPartitionTest.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/UniversalCompactionTest.java

- Introduce IntervalPartition: Algorithm to partition several sst files into the minimum number of `SortedRun`.
- Introduce UniversalCompaction CompactStrategy: Universal Compaction Style is a compaction style, targeting the use cases requiring lower write amplification, trading off read amplification and space amplification.
- Introduce CompactManager: Manager to submit compaction task.

[FLINK-25629] Introduce CompactStrategy and CompactManager for table store

---

flink-table-store-connector/pom.xml
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/LocalCommittable.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/LocalCommittableSerializer.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/SinkRecord.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/SinkRecordConverter.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreGlobalCommitter.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreSink.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreSinkWriter.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/utils/ProjectionUtils.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/LocalCommittableSerializerTest.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/StoreSinkTest.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/TestFileStore.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestCommittableSerializer.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/Increment.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestCommittableSerializerTest.java
pom.xml

Introduce Table Store Sink with SinkWriter and GlobalCommitter.

[FLINK-25680] Introduce Table Store Flink Sink

---

flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreSinkWriter.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/log/LogInitContext.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/log/LogOptions.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/log/LogSinkProvider.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/log/LogSourceProvider.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/log/LogStoreTableFactory.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/sink/SinkRecord.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/sink/SinkRecordConverter.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/utils/OptionsUtils.java
flink-table-store-kafka/pom.xml
flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogKeyedDeserializationSchema.java
flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogOptions.java
flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogSerializationSchema.java
flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogSinkProvider.java
flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogSourceProvider.java
flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogStoreFactory.java
flink-table-store-kafka/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
flink-table-store-kafka/src/test/java/org/apache/flink/table/store/kafka/KafkaLogITCase.java
flink-table-store-kafka/src/test/java/org/apache/flink/table/store/kafka/KafkaLogSerializationTest.java
flink-table-store-kafka/src/test/java/org/apache/flink/table/store/kafka/KafkaLogTestUtils.java
flink-table-store-kafka/src/test/java/org/apache/flink/table/store/kafka/KafkaTableTestBase.java
flink-table-store-kafka/src/test/java/org/apache/flink/table/store/kafka/TestOffsetsLogSink.java
flink-table-store-kafka/src/test/resources/log4j2-test.properties
pom.xml

Introduce log store:
- Refactor SinkRecord
- Introduce log store interfaces
- Implement Kafka log store

[FLINK-26103] Introduce log store

---

README.md

* 1 Remove unnecessary html link tags
* 2 Fix typo

[hotfix][docs] Remove unnecessary html link tags and fix typo

---

flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStore.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreFactory.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreFactoryOptions.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/TableStoreSink.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/ContinuousFileSplitEnumerator.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSource.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/TableStoreSource.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ContinuousFileStoreITCase.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ContinuousITCase.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TableStoreFactoryTest.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TableStoreTestBase.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScan.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScanImpl.java

- Add FileStore Continuous Reading ITCases
- LOG_SYSTEM default is null, when null, use FileStore Continuous Reading
- FileStore Continuous Reading supports latest scan

[FLINK-26679] Add FileStore Continuous Reading ITCase

---

flink-table-store-core/src/main/java/org/apache/flink/table/store/file/format/FileFormat.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/format/FileFormatFactory.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/format/FileStatsExtractingAvroFormat.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/format/FlushingFileFormat.java
flink-table-store-dist/pom.xml
flink-table-store-format/pom.xml
flink-table-store-format/src/main/java/org/apache/flink/table/store/format/avro/AvroFileFormat.java
flink-table-store-format/src/main/java/org/apache/flink/table/store/format/avro/AvroFileFormatFactory.java
flink-table-store-format/src/main/java/org/apache/flink/table/store/format/orc/OrcFileFormat.java
flink-table-store-format/src/main/java/org/apache/flink/table/store/format/orc/OrcFileFormatFactory.java
flink-table-store-format/src/main/java/org/apache/flink/table/store/format/orc/OrcFileStatsExtractor.java
flink-table-store-format/src/main/resources/META-INF/services/org.apache.flink.table.store.file.format.FileFormatFactory
flink-table-store-format/src/test/java/org/apache/flink/table/store/format/orc/OrcFileStatsExtractorTest.java
pom.xml

We need a flink-table-store-dist module to produce a fat connector jar for table store.

[FLINK-26703] Introduce flink-table-store-dist module for packaging

---

flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStore.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSource.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSourceReader.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitReader.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/TableStoreSource.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreITCase.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/LogStoreSinkITCase.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/FileStoreSourceReaderTest.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/log/LogStoreTableFactory.java
flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogDeserializationSchema.java
flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogSourceProvider.java
flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogStoreFactory.java
flink-table-store-kafka/src/test/java/org/apache/flink/table/store/kafka/KafkaLogITCase.java
flink-table-store-kafka/src/test/java/org/apache/flink/table/store/kafka/KafkaLogSerializationTest.java

Finish two TODOs in table store:
- support projection push down for log store
- support projection push down for non-primary-key

[FLINK-26791] Finish projection push down for table store

---

flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreGlobalCommitter.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreSink.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/TestFileStore.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreOptions.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreExpire.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreExpireImpl.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/FileStorePathFactory.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/SnapshotFinder.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreExpireTest.java

Currently, find latest snapshot id and earliest snapshot id is very slow, we can optimize this by introducing snapshot hint files.

[FLINK-26778] Introduce snapshot latest and earliest hint files

---

flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/And.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/Equal.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/GreaterOrEqual.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/GreaterThan.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/IsNotNull.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/IsNull.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/LessOrEqual.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/LessThan.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/Literal.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/NotEqual.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/Or.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/PredicateConverter.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/predicate/PredicateConverterTest.java

[FLINK-26877] Introduce auto type inference for filter push down

---

flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStore.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreFactory.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreFactoryOptions.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/TableStoreSink.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/TableStoreSource.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreITCase.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ReadWriteTableITCase.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/LogStoreSinkITCase.java

Support:
- scan.parallelism
- sink.parallelism

[FLINK-26911] Introduce parallelism setter for table store

---

flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestEntrySerializer.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestFile.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestFileMetaSerializer.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestList.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/sst/SstFileMetaSerializer.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/VersionedObjectSerializer.java

Metadata related format should be added to the version field for better forward compatibility in the future.

[FLINK-27157] Add version field to manifest entries

---

flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ReadWriteTableTestBase.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/StreamingWarehouseITCase.java

Add it case to cover the user story

[FLINK-27264] Add IT case for concurrent batch overwrite and streaming insert into

---

.github/workflows/e2e-tests.yml
flink-table-store-e2e-tests/pom.xml
flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/E2eTestBase.java
flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/FileStoreBatchE2eTest.java
flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/FileStoreFlinkFormatE2eTest.java
flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/FileStoreStreamE2eTest.java
flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/LogStoreE2eTest.java
flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/utils/ParameterProperty.java
flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/utils/TestUtils.java
flink-table-store-e2e-tests/src/test/resources-filtered/project.properties
flink-table-store-e2e-tests/src/test/resources/log4j2-test.properties
pom.xml

End to end tests ensure that users can run table store as expected.

[FLINK-27283] Add end to end tests for table store

---

docs/content/docs/development/create-table.md
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStore.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ContinuousFileStoreITCase.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreTableITCase.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/PartialUpdateITCase.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreOptions.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/DeduplicateMergeFunction.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/PartialUpdateMergeFunction.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/ValueCountMergeFunction.java

PartialUpdateMergeFunction, It will merge two records, completing the not-null fields.
It is very useful for wide tables, where two source tables join together to form a wide table.

[FLINK-26457] Introduce PartialUpdateMergeFunction

---

flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/TypeE2eTest.java

#105 only tests for all supported key data types. This PR add another test for all supported value data types.

[FLINK-27439] Add an e2e test for all supported value data types

---

README.md

This PR aims to correct the `README.md` to correct the description of how to build and get the jar package of this project.

[hotfix][docs] Correct the description of how to build this project

---

flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreFactory.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreITCase.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/Schema.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/SchemaManager.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/SchemaSerializer.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/UpdateSchema.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/schema/SchemaManagerTest.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/schema/SchemaSerializationTest.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/schema/SchemaTest.java

We can add comment to schema for table.

[FLINK-27709] Add comment to schema

---

flink-table-store-hive/src/main/java/org/apache/flink/table/store/TableStoreJobConf.java
flink-table-store-hive/src/main/java/org/apache/flink/table/store/hive/HiveSchema.java
flink-table-store-hive/src/main/java/org/apache/flink/table/store/hive/HiveTypeUtils.java
flink-table-store-hive/src/main/java/org/apache/flink/table/store/hive/TableStoreHiveMetaHook.java
flink-table-store-hive/src/main/java/org/apache/flink/table/store/hive/TableStoreHiveStorageHandler.java
flink-table-store-hive/src/main/java/org/apache/flink/table/store/hive/TableStoreSerDe.java
flink-table-store-hive/src/main/java/org/apache/flink/table/store/hive/objectinspector/TableStoreCharObjectInspector.java
flink-table-store-hive/src/main/java/org/apache/flink/table/store/hive/objectinspector/TableStoreDecimalObjectInspector.java
flink-table-store-hive/src/main/java/org/apache/flink/table/store/hive/objectinspector/TableStoreListObjectInspector.java
flink-table-store-hive/src/main/java/org/apache/flink/table/store/hive/objectinspector/TableStoreMapObjectInspector.java
flink-table-store-hive/src/main/java/org/apache/flink/table/store/hive/objectinspector/TableStoreRowDataObjectInspector.java
flink-table-store-hive/src/main/java/org/apache/flink/table/store/hive/objectinspector/TableStoreVarcharObjectInspector.java
flink-table-store-hive/src/main/java/org/apache/flink/table/store/mapred/TableStoreInputFormat.java
flink-table-store-hive/src/test/java/org/apache/flink/table/store/hive/HiveSchemaTest.java
flink-table-store-hive/src/test/java/org/apache/flink/table/store/hive/RandomGenericRowDataGenerator.java
flink-table-store-hive/src/test/java/org/apache/flink/table/store/hive/TableStoreHiveStorageHandlerITCase.java
flink-table-store-hive/src/test/java/org/apache/flink/table/store/hive/TableStoreSerDeTest.java
flink-table-store-hive/src/test/java/org/apache/flink/table/store/hive/objectinspector/TableStoreCharObjectInspectorTest.java
flink-table-store-hive/src/test/java/org/apache/flink/table/store/hive/objectinspector/TableStoreDecimalObjectInspectorTest.java
flink-table-store-hive/src/test/java/org/apache/flink/table/store/hive/objectinspector/TableStoreListObjectInspectorTest.java
flink-table-store-hive/src/test/java/org/apache/flink/table/store/hive/objectinspector/TableStoreMapObjectInspectorTest.java
flink-table-store-hive/src/test/java/org/apache/flink/table/store/hive/objectinspector/TableStoreRowDataObjectInspectorTest.java
flink-table-store-hive/src/test/java/org/apache/flink/table/store/hive/objectinspector/TableStoreVarcharObjectInspectorTest.java

As table store schema is supported, we should use this schema as the ground truth. Hive DDL should only be used for checking.

[FLINK-28079] Check Hive DDL against table store schema when creating table

---

docs/content/docs/engines/spark.md
flink-table-store-spark/pom.xml
flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SparkReadITCase.java

- Include Hive metastore dependency in Spark bundled jar.
- Improve document of Spark.

[FLINK-28511] Improve Spark dependencies and document

---

docs/content/docs/engines/spark.md
flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SparkReadITCase.java

- Introduce Dataset API.
- Unify table_store and tablestore.

[FLINK-28689] Optimize Spark documentation to Catalog and Dataset

---

flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/CatalogFactory.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/catalog/CatalogFactoryTest.java

- Not exist, automatic creating the directory.
- Exist but it is not directory, throw exception.
- Exist and it is a directory, pass...

[FLINK-28692] Check warehouse path in CatalogFactory

---

docs/layouts/shortcodes/generated/core_configuration.html
flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java

Some configuration adjustments, a more reasonable allocation of memory, to avoid OOM.

[hotfix] Adjust the default value of WRITE_BUFFER_SIZE and NUM_SORTED_RUNS_STOP_TRIGGER

---

flink-table-store-dist/pom.xml
flink-table-store-e2e-tests/pom.xml
flink-table-store-e2e-tests/src/test/resources-filtered/docker-compose.yaml

java.lang.NoSuchFieldError: callback
at org.apache.flink.table.store.kafka.KafkaSinkFunction.open (KafkaSinkFunction.java:71)
Error when using table store with kafka sql-jar.
We should shade more for flink-connector-kafka.

[FLINK-28775] Unclean shade in flink-table-store-dist

---

.github/workflows/build-different-versions.yml
flink-table-store-shade/pom.xml
pom.xml

Fix syntax of `build-different-versions.yaml`.

[hotfix] Fix github workflow build-different-versions.yaml

---

tools/releasing/create_binary_release.sh

This PR fixes incorrect paths for Hive catalog in the releasing script.

[hotfix] Fix releasing script

---

flink-table-store-core/src/test/java/org/apache/flink/table/store/file/FileFormatTest.java

Fix FileFormatTest read the same value from file twice.

[FLINK-29063] fix FileFormatTest

---

docs/content/docs/engines/spark3.md

Fix correct spelling mistakes of CHANGE in ALTER TABLE syntax.

[HOTFIX] Fix the spelling mistakes of CHANGE in ALTER TABLE syntax

---

docs/content/docs/development/rescale-bucket.md

The current description for restoring a job from a savepoint only applies for jar jobs.

[hotfix] Fix the typo in DDL, and correct the SQL job restore description

---

docs/content/docs/development/configuration.md
docs/content/docs/development/lookup-join.md
docs/content/docs/development/rescale-bucket.md
docs/content/docs/development/roadmap.md
docs/layouts/shortcodes/generated/rocksdb_configuration.html
flink-table-store-common/src/main/java/org/apache/flink/table/store/file/predicate/PredicateBuilder.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/file/predicate/PredicateConverter.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/file/predicate/PredicateFilter.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/KeyProjectedRowData.java
flink-table-store-connector/pom.xml
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/RocksDBOptions.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/lookup/FileStoreLookupFunction.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/lookup/LookupTable.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/lookup/PrimaryKeyLookupTable.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/lookup/RocksDBSetState.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/lookup/RocksDBState.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/lookup/RocksDBStateFactory.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/lookup/RocksDBValueState.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/lookup/SecondaryIndexLookupTable.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/lookup/StreamingReader.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/ContinuousFileSplitEnumerator.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSource.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/SnapshotEnumerator.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/TableStoreSource.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/LookupJoinITCase.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/lookup/LookupTableTest.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/SnapshotEnumerator.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/TableStreamingReader.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/predicate/PredicateConverterTest.java

At present, the bottom layer of Table Store is LSM structure, and it has full and incremental reading, which can have certain lookup capability. We can unlock Table Store to implement LookupTableSource.

[FLINK-29154] Support LookupTableSource for table store

---

docs/content/docs/development/create-table.md
docs/layouts/shortcodes/generated/core_configuration.html
flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/RowDataUtils.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/utils/RowDataUtilsTest.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FlinkSourceBuilder.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/PreAggregationITCase.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/aggregate/AggregateMergeFunction.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/aggregate/FieldAggregator.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/aggregate/FieldBoolAndAgg.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/aggregate/FieldBoolOrAgg.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/aggregate/FieldLastNonNullValueAgg.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/aggregate/FieldLastValueAgg.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/aggregate/FieldListaggAgg.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/aggregate/FieldMaxAgg.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/aggregate/FieldMinAgg.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/aggregate/FieldSumAgg.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTable.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/aggregate/FieldAggregatorTest.java

We can introduce richer merge strategies, one of which is already introduced is PartialUpdateMergeFunction, which completes non-NULL fields when merging. This PR introduces support for pre-aggregated merges.

[FLINK-27626] Introduce pre-aggregated merge to table store

---

flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/SortBufferMemTable.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/FullChangelogMergeFunctionWrapper.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/MergeFunctionWrapper.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/ReducerMergeFunctionWrapper.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/SortMergeReader.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/FullChangelogMergeFunctionWrapperTestBase.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/MergeFunctionTestUtils.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/ReducerMergeFunctionWrapperTestBase.java

We need to introduce a special `MergeFunction` to produce changelogs.

[FLINK-29293] Introduce a MergeFunction for full compaction

---

flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/MergeTreeTest.java

Use independent reader/writer factory for compaction in `MergeTreeTest`, otherwise, there may be concurrency problems in the test case

[FLINK-29745] Use independent reader/writer factory for compaction in MergeTreeTest

---

docs/content/docs/development/query-table.md
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/AbstractTableStoreFactory.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/FlinkCatalog.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/MetadataCatalogTable.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/ContinuousFileSplitEnumerator.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSource.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplit.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitGenerator.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitSerializer.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FlinkSource.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FlinkTableSource.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/MetadataSource.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/MetadataTableSource.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/TableStoreSource.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/CatalogTableITCase.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TableStoreManagedFactoryTest.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitGeneratorTest.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/AbstractCatalog.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/Catalog.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/IteratorRecordReader.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/SnapshotManager.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/metadata/MetadataTableLoader.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/metadata/SnapshotsTable.java
flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SparkReadITCase.java

Introduce snapshots metadata table to show snapshot history.

[FLINK-29760] Introduce snapshots metadata table

---

flink-table-store-e2e-tests/src/test/resources/flink.env

Redirct gc log from stdout to file

[FLINK-29791] Redirect gc log from stdout to file

---

docs/layouts/shortcodes/generated/catalog_configuration.html
flink-table-store-core/src/main/java/org/apache/flink/table/store/CatalogOptions.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/TableType.java
flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/HiveCatalog.java
flink-table-store-hive/flink-table-store-hive-catalog/src/test/java/org/apache/flink/table/store/hive/HiveCatalogITCase.java

support hive catalog to create external table

[FLINK-29922] Support create external table for hive catalog

---

docs/layouts/shortcodes/generated/core_configuration.html
flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java

Another little fix with documents, this time I found that sentence get one more period.
Signed-off-by: houhang

[FLINK-30028]A little fix with document about periods in log.changelog-mode description.

---

docs/content/docs/development/rescale-bucket.md

1. fix the wrong column in "INSERT OVERWRITE" sqls;
2. append a ddl for "insert from" temporary table;
3. append some ";" in some sqls.

[FLINK-30043] Some example sqls in flink table store rescale-bucket doucument are incorrect.

---

docs/content/docs/development/lookup-join.md

I guess it's better add a left table DDL in doc to help new users learn how to use lookup join easily.

[FLINK-30094] Append a left table DDL in Lookup Join character.

---

flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/AbstractTableStoreFactory.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSource.java
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FlinkSourceBuilder.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ContinuousFileStoreITCase.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/SnapshotManager.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/AppendOnlyFileStoreTable.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogValueCountFileStoreTable.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTable.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/FileStoreTableFactory.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/DataTableScan.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/SnapshotEnumerator.java

The file store can find a suitable snapshot according to start timestamp and read incremental data from it.

[FLINK-29232] File store continuous reading support from_timestamp scan mode

---

flink-table-store-codegen-loader/pom.xml
flink-table-store-codegen-loader/src/main/java/org/apache/flink/table/store/codegen/CodeGenLoader.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/LocalFileUtils.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/utils/LocalFileUtilsTest.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/utils/TempDirUtils.java

[FLINK-30139] CodeGenLoader fails when temporary directory is a symlink

---

flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/SchemaManager.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/FileStoreTableFactory.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/schema/SchemaManagerTest.java

The full compaction producer is not supported in `ValueCountMergeFunction`, it should be checked in `SchemaManager`

[FLINK-30161] Add table schema validation for full compaction

---

flink-table-store-benchmark/flink-table-store-micro-benchmarks/src/main/java/org/apache/flink/table/store/benchmark/file/mergetree/MergeTreeBenchmark.java
flink-table-store-benchmark/flink-table-store-micro-benchmarks/src/main/java/org/apache/flink/table/store/benchmark/file/mergetree/MergeTreeReaderBenchmark.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/Projection.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/RowDataUtils.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/PartialUpdateITCase.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/PreAggregationITCase.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/TestChangelogDataReadWrite.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/KeyValueFileStore.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/DeduplicateMergeFunction.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/FullChangelogMergeTreeCompactRewriter.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/MergeFunction.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/MergeFunctionFactory.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/MergeTreeCompactRewriter.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/PartialUpdateMergeFunction.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/ValueCountMergeFunction.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/aggregate/AggregateMergeFunction.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreRead.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreWrite.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogValueCountFileStoreTable.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTable.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/MergeTreeTest.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/SortBufferWriteBufferTestBase.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreExpireTest.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreReadTest.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreScanTest.java

We did not properly process the project in MergeFunction, which resulted in subsequent reading position errors.

[FLINK-30125] Projection pushdown is not work for partial update

---

flink-table-store-common/src/main/java/org/apache/flink/table/store/file/predicate/CompoundPredicate.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/file/predicate/LeafPredicate.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/file/predicate/PredicateReplaceVisitor.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/file/predicate/PredicateVisitor.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/SchemaEvolutionUtil.java

At present, predicate is traversed in many places. We need a visitor mode, which can better traverse Predicate.

[FLINK-30272] Introduce a Predicate Visitor

---

docs/content/docs/filesystems/overview.md
docs/content/docs/filesystems/s3.md
flink-table-store-common/src/main/java/org/apache/flink/table/store/filesystem/FileSystems.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/plugin/ComponentClassLoader.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/plugin/FileSystemLoader.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/plugin/PluginLoader.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/codegen/CodeGenUtils.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/CatalogFactory.java
flink-table-store-filesystems/flink-table-store-oss/src/main/java/org/apache/flink/table/store/oss/OSSLoader.java
flink-table-store-filesystems/flink-table-store-oss/src/main/resources/META-INF/services/org.apache.flink.table.store.plugin.FileSystemLoader
flink-table-store-filesystems/flink-table-store-s3/pom.xml
flink-table-store-filesystems/flink-table-store-s3/src/main/java/org/apache/flink/table/store/s3/S3Loader.java
flink-table-store-filesystems/flink-table-store-s3/src/main/resources/META-INF/services/org.apache.flink.table.store.plugin.FileSystemLoader
flink-table-store-filesystems/pom.xml
flink-table-store-hive/flink-table-store-hive-connector/src/main/java/org/apache/flink/table/store/hive/HiveSchema.java
flink-table-store-spark/pom.xml
flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkCatalog.java
flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkSource.java
flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/MinioTestContainer.java
flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SparkS3ITCase.java
flink-table-store-spark2/src/main/java/org/apache/flink/table/store/spark/SparkSource.java

S3 contains a large number of dependencies, which can easily lead to class conflicts. We need a plugin mechanism to load the corresponding jars through the classloader.

[FLINK-30398] Introduce S3 support for table store

---

flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/FullChangelogStoreSinkWrite.java

Incorrect check between snapshot id and checkpoint id.

[hotfix] Remove incorrect check in FullChangelogStoreSinkWrite

---

flink-table-store-benchmark/flink-table-store-micro-benchmarks/src/main/java/org/apache/flink/table/store/benchmark/file/mergetree/MergeTreeBenchmark.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/TestChangelogDataReadWrite.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/AppendOnlyFileStore.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/KeyValueFileStore.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/io/DataFilePathFactory.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/io/KeyValueFileReaderFactory.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AppendOnlyFileStoreRead.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreRead.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreWrite.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/BulkFormatMapping.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/format/FileFormatDiscover.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/format/FormatKey.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/io/KeyValueFileReadWriteTest.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/MergeTreeTest.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/table/FileStoreTableTestBase.java

1. Set file format to orc
2. Write records.
3. Set file format to parquet.
4. Write records
5. Read -> throw exception...
We should support change file format.

[FLINK-30569] File Format can not change with data file exists

---

flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/schema/SchemaManagerTest.java

Cannot define any primary key in an append-only table

[FLINK-30587] Validate primary key in append-only table in ddl

---

docs/layouts/partials/docs/inject/menu-after.html
docs/layouts/shortcodes/beta.html
docs/layouts/shortcodes/img.html
docs/layouts/shortcodes/javadoc.html
docs/layouts/shortcodes/label.html
docs/layouts/shortcodes/scala_version.html
docs/layouts/shortcodes/stable.html
docs/layouts/shortcodes/top.html
docs/layouts/shortcodes/unstable.html
docs/layouts/shortcodes/version.html
docs/static/js/flink.js
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AbstractFileStoreScan.java

Change Logs
fix typo
Impact
fix typo

[hotfix] fix typo

---

flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/action/CompactActionITCase.java

In `CompactActionITCase#testStreamingCompact`, parallelism of compact job may be larger than 1, so there is a small possibility that different writers will perform full compaction in different checkpoints. We need to change the checking method of the test.

[FLINK-30603] Fix unstable test CompactActionITCase#testStreamingCompact

---

flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkTypeUtils.java
flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SparkReadITCase.java
flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SparkTypeTest.java

Fix invalid field id for nested type in spark ddl

[FLINK-30710] Fix invalid field id for nested type in spark catalog

---

flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkTypeUtils.java
flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SparkReadITCase.java

[FLINK-30820] Support varchar/char in spark

---

flink-table-store-common/src/main/java/org/apache/flink/table/store/memory/MemorySegment.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/memory/MemoryUtils.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/fs/HadoopLocalFileIOBehaviorTest.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/memory/MemorySegmentTestBase.java

Clean up some useless code and adjust the code call of legacy

[FLINK-30892] Clean codes for memory and tests

---

docs/content/docs/how-to/creating-tables.md
docs/content/docs/maintenance/configurations.md
docs/content/docs/maintenance/manage-partition.md
docs/layouts/shortcodes/generated/core_configuration.html
flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/AbstractFileStore.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStore.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/PartitionExpire.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/partition/PartitionTimeExtractor.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/AbstractFileStoreTable.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/TableCommit.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/PartitionExpireTest.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/partition/PartitionTimeExtractorTest.java

Same to snapshot expiration, we can also introduce partition expiration to automatically delete expired partitions in commit node.

[FLINK-30882] Introduce partition.expiration-time to automatically delete expired partitions

---

flink-table-store-common/pom.xml
flink-table-store-common/src/test/java/org/apache/flink/table/store/data/BinaryRowTest.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/data/BinaryStringTest.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/data/DecimalTest.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/data/NestedRowTest.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/data/RowDataTest.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/data/TimestampTest.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/data/serializer/SerializerTestBase.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/memory/MemorySegmentTestBase.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/memory/OffHeapDirectMemorySegmentTest.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/memory/OnHeapMemorySegmentTest.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/utils/CommonTestUtils.java
flink-table-store-test-utils/pom.xml
flink-table-store-test-utils/src/main/java/org/apache/flink/table/store/testutils/junit/TestLoggerExtension.java
flink-table-store-test-utils/src/main/java/org/apache/flink/table/store/testutils/junit/parameterized/Parameter.java
flink-table-store-test-utils/src/main/java/org/apache/flink/table/store/testutils/junit/parameterized/ParameterizedTestExtension.java
flink-table-store-test-utils/src/main/java/org/apache/flink/table/store/testutils/junit/parameterized/Parameters.java
pom.xml

Introduce flink-table-store-test-utils module for table store

[FLINK-30999] Introduce flink-table-store-test-utils for table store

---

flink-table-store-common/src/main/java/org/apache/flink/table/store/data/ArrayDataSerializer.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/data/BinaryRowSerializer.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/data/BinaryStringSerializer.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/data/MapDataSerializer.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/io/DataInputDeserializer.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/io/DataInputView.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/io/DataInputViewStream.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/io/DataInputViewStreamWrapper.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/io/DataOutputSerializer.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/io/DataOutputView.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/io/DataOutputViewStream.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/io/DataOutputViewStreamWrapper.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/memory/MemorySegmentUtils.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/memory/MemoryUtils.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestCommittableSerializer.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/ObjectSerializer.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/SerializationUtils.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/FileCommittableSerializer.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/SerializableCommittable.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/DataSplit.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/ObjectSerializerTestBase.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/table/source/SplitTest.java
flink-table-store-hive/flink-table-store-hive-connector/src/main/java/org/apache/flink/table/store/mapred/TableStoreInputSplit.java

Introduce input and output stream from `flink-core` for table store

[FLINK-31004] Introduce input and output stream for table store

---

flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/FlinkSink.java

[FLINK-31094] Add table name to Writer

---

flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/util/AbstractTestBase.java

[hotfix] Increase slots to 8 in AbstractTestBase

---

flink-table-store-common/src/main/java/org/apache/flink/table/store/data/BinaryArray.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/data/BinaryMap.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/data/BinaryRow.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/data/BinarySection.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/data/BinaryString.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/data/Decimal.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/data/GenericArray.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/data/GenericMap.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/data/GenericRow.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/data/NestedRow.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/data/Timestamp.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/data/columnar/ColumnarArray.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/data/columnar/ColumnarMap.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/data/columnar/ColumnarRow.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/memory/MemorySegment.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/memory/MemorySegmentSource.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/IOUtils.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/data/BinaryRowTest.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/data/serializer/InternalArraySerializerTest.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/data/serializer/InternalMapSerializerTest.java
flink-table-store-common/src/test/java/org/apache/flink/table/store/data/serializer/SerializerTestBase.java

This can make our internal data structures easy to use.

[FLINK-31179] Make data structures serializable

---

flink-table-store-connector/pom.xml
pom.xml

Unify the version of `kafka` in pom.

Unify the version of `kafka` in pom.

---

flink-table-store-flink/pom.xml

Add version reference of `kafka` dependent package

[hotfix] Adds the Kafka version reference in the dependencies

---

flink-table-store-common/src/main/java/org/apache/flink/table/store/data/LazyGenericRow.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/stats/FieldStatsConverters.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/system/FilesTable.java

At present, the reading performance of the Files table is very poor. Even every data read will read the schema file. We can optimize the reading performance.

[FLINK-31254] Improve the read performance for files table

---

docs/content/docs/how-to/creating-tables.md
docs/layouts/shortcodes/generated/core_configuration.html
flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/SchemaManager.java
flink-table-store-flink/flink-table-store-flink-common/pom.xml
flink-table-store-flink/flink-table-store-flink-common/src/test/java/org/apache/flink/table/store/connector/CatalogTableITCase.java
flink-table-store-hive/flink-table-store-hive-catalog/src/test/java/org/apache/flink/table/store/hive/HiveCatalogITCase.java
flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SparkReadITCase.java

Add Create Table As for flink table store

[FLINK-31128] Add Create Table As for flink table store

---

flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTableTest.java

Currently the result of `ChangelogWithKeyFileStoreTableTest#testAggMergeFunc` in branch release-0.3 is not correct. This PR fixes the testing method.

[hotfix] Fix ChangelogWithKeyFileStoreTableTest#testAggMergeFunc

---

docs/content/docs/how-to/altering-tables.md
flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/FlinkCatalog.java
flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileSystemCatalogITCase.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/Catalog.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/FileSystemCatalog.java
flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/HiveCatalog.java
flink-table-store-hive/flink-table-store-hive-catalog/src/test/java/org/apache/flink/table/store/hive/HiveCatalogITCase.java
flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkCatalog.java
flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SparkReadTestBase.java
flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SparkSchemaEvolutionITCase.java

This PR is cherry-picked from #471.

[FLINK-30608] support rename table

---

flink-table-store-flink/flink-table-store-flink-1.14/pom.xml
flink-table-store-flink/flink-table-store-flink-1.14/src/main/java/org/apache/flink/table/store/connector/lookup/LookupRuntimeProviderFactory.java
flink-table-store-flink/flink-table-store-flink-1.14/src/main/java/org/apache/flink/table/store/connector/lookup/OldLookupFunction.java
flink-table-store-flink/flink-table-store-flink-1.14/src/test/java/org/apache/flink/table/store/connector/CatalogITCaseBase.java
flink-table-store-flink/flink-table-store-flink-1.14/src/test/java/org/apache/flink/table/store/connector/LookupJoinITCase.java
flink-table-store-flink/flink-table-store-flink-1.14/src/test/resources/log4j2-test.properties
flink-table-store-flink/flink-table-store-flink-1.15/pom.xml
flink-table-store-flink/flink-table-store-flink-1.15/src/main/java/org/apache/flink/table/store/connector/lookup/LookupRuntimeProviderFactory.java
flink-table-store-flink/flink-table-store-flink-1.15/src/main/java/org/apache/flink/table/store/connector/lookup/OldLookupFunction.java
flink-table-store-flink/flink-table-store-flink-1.15/src/test/java/org/apache/flink/table/store/connector/CatalogITCaseBase.java
flink-table-store-flink/flink-table-store-flink-1.15/src/test/java/org/apache/flink/table/store/connector/LookupJoinITCase.java
flink-table-store-flink/flink-table-store-flink-1.15/src/test/resources/log4j2-test.properties
flink-table-store-flink/flink-table-store-flink-common/src/main/java/org/apache/flink/table/store/connector/lookup/FileStoreLookupFunction.java
flink-table-store-flink/flink-table-store-flink-common/src/main/java/org/apache/flink/table/store/connector/lookup/LookupRuntimeProviderFactory.java
flink-table-store-flink/flink-table-store-flink-common/src/main/java/org/apache/flink/table/store/connector/lookup/NewLookupFunction.java
flink-table-store-flink/flink-table-store-flink-common/src/main/java/org/apache/flink/table/store/connector/source/TableStoreSource.java
flink-table-store-flink/flink-table-store-flink-common/src/test/java/org/apache/flink/table/store/connector/LookupJoinITCase.java

Only implements new LookupFunction, retry lookup join can work.

[FLINK-31331] Flink 1.16 should implement new LookupFunction

---

flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/FileStoreBatchE2eTest.java
flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/FlinkActionsE2eTest.java
flink-table-store-flink/flink-table-store-flink-1.14/pom.xml
flink-table-store-flink/flink-table-store-flink-1.14/src/main/java/org/apache/flink/table/store/connector/utils/TableEnvironmentUtils.java
flink-table-store-flink/flink-table-store-flink-1.14/src/test/java/org/apache/flink/table/store/connector/FlinkActionITCase.java
flink-table-store-flink/flink-table-store-flink-1.15/pom.xml
flink-table-store-flink/flink-table-store-flink-1.15/src/test/java/org/apache/flink/table/store/connector/FlinkActionITCase.java
flink-table-store-flink/flink-table-store-flink-common/src/main/java/org/apache/flink/table/store/connector/action/ActionBase.java
flink-table-store-flink/flink-table-store-flink-common/src/main/java/org/apache/flink/table/store/connector/action/DeleteAction.java
flink-table-store-flink/flink-table-store-flink-common/src/main/java/org/apache/flink/table/store/connector/action/MergeIntoAction.java
flink-table-store-flink/flink-table-store-flink-common/src/main/java/org/apache/flink/table/store/connector/utils/TableEnvironmentUtils.java

Use Table API to do insert job to ensure the batch configuration takes effect.

[FLINK-31323] Fix unstable E2E test for flink actions

---

tools/releasing/create_binary_release.sh

Fix spark jar name in the create release script for table store

[FLINK-31394] Fix spark jar name in the create release script for table store

---

flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/Filter.java
flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/MurmurHashUtils.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeWriter.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/ChangelogMergeTreeRewriter.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/ChangelogResult.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/FullChangelogMergeFunctionWrapper.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/FullChangelogMergeTreeCompactRewriter.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/ReducerMergeFunctionWrapper.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AbstractFileStoreScan.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScan.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/TableWrite.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/AbstractDataTableScan.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/DataTableScan.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/snapshot/ContinuousDataFileSnapshotEnumerator.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/table/system/AuditLogTable.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/FullChangelogMergeFunctionWrapperTestBase.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/MergeFunctionTestUtils.java
flink-table-store-core/src/test/java/org/apache/flink/table/store/table/source/snapshot/CompactionChangelogFollowUpScannerTest.java
flink-table-store-flink/flink-table-store-flink-common/src/main/java/org/apache/flink/table/store/connector/sink/FullChangelogStoreSinkWrite.java

Refactor classes code of full-compaction, this is to prepare some shared codes for lookup changelog producer.

[FLINK-31392] Refactor classes code of full-compaction

---

docs/content/docs/how-to/creating-catalogs.md
tools/releasing/create_binary_release.sh

Fix hive catalog and connector jar name in the create release script for table store

[FLINK-31460] Fix hive catalog and connector jar name in the create release script for table store

---

flink-table-store-flink/flink-table-store-flink-1.14/src/test/java/org/apache/flink/table/store/connector/BatchFileStoreITCase.java
flink-table-store-flink/flink-table-store-flink-1.14/src/test/java/org/apache/flink/table/store/connector/ContinuousFileStoreITCase.java
flink-table-store-flink/flink-table-store-flink-1.15/src/test/java/org/apache/flink/table/store/connector/BatchFileStoreITCase.java
flink-table-store-flink/flink-table-store-flink-1.15/src/test/java/org/apache/flink/table/store/connector/ContinuousFileStoreITCase.java

[FLINK-31253](https://issues.apache.org/jira/browse/FLINK-31253)

[FLINK-31253] Port BatchFileStoreITCase and ContinuousFileStoreITCase to Flink 1.14 and 1.15

---

docs/content/docs/how-to/altering-tables.md
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/SchemaChange.java
flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/SchemaManager.java
flink-table-store-spark/flink-table-store-spark-common/src/main/java/org/apache/flink/table/store/spark/SparkCatalog.java
flink-table-store-spark/flink-table-store-spark-common/src/test/java/org/apache/flink/table/store/spark/SparkSchemaEvolutionITCase.java

add UPDATE COLUMN POSITION for flink table store

[FLINK-31459]add UPDATE COLUMN POSITION for flink table store

---

CODE_OF_CONDUCT.md

change name in CODE_OF_CONDUCT file

[hotfix] change name in CODE_OF_CONDUCT file

---

docs/content/engines/flink.md
docs/content/engines/spark2.md
docs/content/engines/spark3.md
paimon-benchmark/paimon-cluster-benchmark/README.md
paimon-benchmark/paimon-cluster-benchmark/src/main/java/org/apache/paimon/benchmark/Benchmark.java
paimon-benchmark/paimon-cluster-benchmark/src/main/resources/sinks/paimon.yaml
paimon-e2e-tests/src/test/java/org/apache/paimon/tests/HiveE2eTest.java
paimon-flink/paimon-flink-1.14/src/test/java/org/apache/paimon/flink/CatalogITCaseBase.java
paimon-flink/paimon-flink-1.15/src/test/java/org/apache/paimon/flink/CatalogITCaseBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FullChangelogStoreSinkWrite.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LogSystemITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/util/ReadWriteTableTestUtil.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/PaimonJobConf.java

This PR aims to replace keyword `table_store` with `paimon` in the project
NO
NO
NO

[core] Replace table_store with paimon in docs and classes

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/workflows/e2e-tests-1.14.yml
.github/workflows/e2e-tests-1.15.yml
.github/workflows/e2e-tests-1.16.yml
.github/workflows/utitcase-flink.yml
.github/workflows/utitcase.yml

[license] Add license header to ci file

---

README.md
paimon-benchmark/paimon-cluster-benchmark/src/main/java/org/apache/paimon/benchmark/Benchmark.java
paimon-benchmark/paimon-cluster-benchmark/src/main/java/org/apache/paimon/benchmark/metric/cpu/ProcfsBasedProcessTree.java
paimon-common/src/main/java/org/apache/paimon/utils/Preconditions.java
paimon-common/src/main/java/org/apache/paimon/utils/StringUtils.java

1. some code refactor
2. add JDK version info into README

[refactor] simplify String operations and add JDK version into README

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/format/FileFormat.java
paimon-common/src/main/java/org/apache/paimon/format/FileFormatFactory.java
paimon-common/src/test/java/org/apache/paimon/format/TestFileFormatFactory.java
paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/format/FileFormatDiscover.java
paimon-core/src/test/java/org/apache/paimon/FileFormatTest.java
paimon-core/src/test/java/org/apache/paimon/format/FileStatsExtractingAvroFormatFactory.java
paimon-format/src/main/java/org/apache/paimon/format/avro/AvroFileFormatFactory.java
paimon-format/src/main/java/org/apache/paimon/format/orc/OrcFileFormat.java
paimon-format/src/main/java/org/apache/paimon/format/orc/OrcFileFormatFactory.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetFileFormat.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetFileFormatFactory.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetReaderFactory.java
paimon-format/src/test/java/org/apache/paimon/format/orc/OrcFileFormatTest.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetFileFormatTest.java

related to https://github.com/apache/incubator-paimon/issues/641

[core] add read batch size option

---

docs/content/project/_index.md
docs/content/project/roadmap.md

[doc] Document roadmap

---

paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/format/FileFormatDiscover.java
paimon-core/src/test/java/org/apache/paimon/FileFormatTest.java
paimon-format/src/main/java/org/apache/paimon/format/orc/OrcFileFormat.java
paimon-format/src/test/java/org/apache/paimon/format/orc/OrcFileFormatTest.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetFileFormatTest.java

*add test case for CoreOptions.testCreateFileFormat method*
*org.apache.paimon.FileFormatTest#testCreateFileFormat*

[core] add test case for CoreOptions.testCreateFileFormat method

---

paimon-core/src/main/java/org/apache/paimon/cdc/EventParser.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CompactorSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcBucketStreamPartitioner.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcParsingProcessFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSinkBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/SchemaChangeProcessFunction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSinkITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestCdcEvent.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestCdcEventParser.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestCdcSourceFunction.java

To directly consume changes from Flink CDC connectors, we need a special CDC sink for Paimon.
* FlinkCdcSinkITCase
N/A
N/A

[FLINK-31434] Introduce CDC sink

---

docs/content/engines/flink.md
docs/content/engines/hive.md
docs/content/engines/spark2.md
docs/content/engines/spark3.md
docs/content/filesystems/oss.md
docs/content/filesystems/s3.md
docs/content/how-to/creating-catalogs.md

Recommend downloading snapshot jars instead of building from source.

[doc] Download snapshot jars

---

.github/workflows/e2e-tests-1.14.yml
.github/workflows/e2e-tests-1.15.yml
.github/workflows/e2e-tests-1.16.yml
.github/workflows/utitcase-flink.yml
.github/workflows/utitcase.yml

[ci] Skip code CI tests if the PR only contains docs change.

---

paimon-common/src/main/java/org/apache/paimon/utils/InternalRowUtils.java
paimon-common/src/main/java/org/apache/paimon/utils/RowDataToObjectArrayConverter.java
paimon-common/src/test/java/org/apache/paimon/utils/InternalRowUtilsTest.java
paimon-core/src/main/java/org/apache/paimon/KeyValue.java
paimon-core/src/main/java/org/apache/paimon/io/DataFileMetaSerializer.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/AggregateMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldMaxAgg.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldMinAgg.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaEvolutionUtil.java
paimon-core/src/main/java/org/apache/paimon/stats/FieldStatsArraySerializer.java
paimon-core/src/main/java/org/apache/paimon/table/sink/SequenceGenerator.java
paimon-core/src/main/java/org/apache/paimon/utils/RowDataPartitionComputer.java
paimon-core/src/test/java/org/apache/paimon/table/ColumnTypeFileDataTestBase.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/PaimonSerDe.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/objectinspector/PaimonInternalRowObjectInspector.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/PaimonSerDeTest.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/objectinspector/PaimonInternalRowObjectInspectorTest.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkArrayData.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkInternalRow.java

Rename  RowData to InternalRow.
No.
No.
No.

[typo][common] Rename paimon-common's 'RowDataUtils' to 'InternalRowUtils'

---

paimon-benchmark/paimon-cluster-benchmark/src/main/java/org/apache/paimon/benchmark/metric/BenchmarkMetric.java
paimon-core/src/main/java/org/apache/paimon/sort/HeapSort.java
paimon-core/src/test/java/org/apache/paimon/table/ColumnTypeFileMetaTestBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTestBase.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ParquetDataColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/RunLengthDecoder.java

Optimize some javadoc
No need
No
No

[javadoc] optimize javadoc

---

pom.xml

[Bug] Remove useless maven configurations #779

---

paimon-flink/paimon-flink-1.17/pom.xml
paimon-flink/pom.xml

Add paimon-flink-1.17 sub module. Sub task of #640 
No.
No.
No

[flink] Initialize flink-1.17 sub module

---

paimon-flink/paimon-flink-common/pom.xml
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java
pom.xml

[flink] Bump flink version of paimon-flink-common to 1.17.0

---

.github/workflows/e2e-tests-1.14-jdk11.yml
.github/workflows/e2e-tests-1.15-jdk11.yml
.github/workflows/e2e-tests-1.16-jdk11.yml
.github/workflows/unitcase-flink-jdk11.yml
.github/workflows/unitcase-jdk11.yml

hotfix for jdk11 daily github workflow
Because the workflow works only on default branch (master), I test manually in personal repo.

[hotfix] fix scheduled daily jdk11 workflow

---

.github/workflows/e2e-tests-1.17-jdk11.yml
.github/workflows/e2e-tests-1.17.yml
paimon-e2e-tests/pom.xml
paimon-hive/paimon-hive-connector-2.3/src/test/java/org/apache/paimon/hive/Hive23CatalogITCase.java
paimon-hive/paimon-hive-connector-3.1/src/test/java/org/apache/paimon/hive/Hive31CatalogITCase.java
pom.xml

[hotfix] Add flink1.17 e2e test ci check

---

paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/HiveSchema.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/PaimonJobConf.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/mapred/PaimonInputFormat.java

[hive] pass filesystem config to FileIO

---

DISCLAIMER

[hotfix] add DISCLAIMER file

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ReadWriteTableITCase.java

add test for NaN and Infinity type,
I test that ,and found it is fine  for issue https://github.com/apache/incubator-paimon/issues/736
*org.apache.paimon.flink.ReadWriteTableITCase#testNaNType*

[flink]add test for NaN and Infinity type

---

docs/content/concepts/external-log-systems.md
docs/content/engines/flink.md

Show list of flink jar downloads in external log system documentation

[hotfix] Show list of flink jar downloads in external log system documentation

---

docs/content/engines/overview.md

[Document] Adds the Trino feature that create/drop table, create/drop database in the overview document

---

docs/content/how-to/cdc-ingestion.md
docs/content/how-to/change-data-capture.md
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java

This PR adds document for `MySqlSyncTableAction`.
N/A
N/A
Yes. This is the PR for document.

[docs] Add document for MySqlSyncTableAction

---

docs/content/concepts/file-layouts.md

[doc] Document file format

---

pom.xml
tools/releasing/create_source_release.sh

Added incubating name in release file

[release] Added incubating name in release file

---

docs/content/engines/overview.md

[doc] add flink 1.17 version in Engines Overview

---

.github/workflows/code-analysys.yml
.gitignore
README.md
pom.xml
tools/ci/sonar_check.sh

close #837 
Add sonar check for paimon.
1. Analyze paimon https://sonarcloud.io/projects/create cc @JingsongLi 
2. Create a GitHub Secret
In paimon GitHub repository, go to [Settings > Secrets > Actions](https://github.com/apache/incubator-paimon/settings/secrets) and create a new secret with the following details:
2.1. In the Name field, enter `SONAR_TOKEN`.
2.2. In the Value field, enter token value.
2.3. In the Name field, enter `GITHUB_TOKEN`.(Needed to get PR information, if any) @JingsongLi 
2.4. In the Value field, enter token value.
https://docs.sonarcloud.io/advanced-setup/ci-based-analysis/github-actions-for-sonarcloud/
*(Does this change affect API or …

[Improve] [CI]Add Sonar Check

---

.github/workflows/check-licensing.yml
.github/workflows/code-analysys.yml
.github/workflows/e2e-tests-1.14.yml
.github/workflows/e2e-tests-1.15.yml
.github/workflows/e2e-tests-1.16.yml
.github/workflows/e2e-tests-1.17.yml
.github/workflows/publish_snapshot.yml
.github/workflows/utitcase-flink.yml
.github/workflows/utitcase.yml

Solve the problem of starting multiple actions at the same time.

[CI] Solve the problem of starting multiple actions at the same time

---

pom.xml

[Improve][Parent-Pom] add repositories

---

docs/content/api/_index.md
docs/content/api/java-api.md
docs/content/engines/flink.md
docs/content/engines/hive.md
docs/content/engines/overview.md
docs/content/engines/spark2.md
docs/content/engines/spark3.md
docs/content/filesystems/oss.md
docs/content/filesystems/overview.md
docs/content/filesystems/s3.md
docs/content/project/download.md

Update stable jar download link after release using mvn deploy jars

[release][doc] Update stable jar download link after release using mvn deploy jars

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalogBase.java

[Improve][catalog] Use `tableExists` for flink and spark catalog

---

.gitignore
pom.xml

[CI] Fix the sonar check  that parameters are overwritten

---

pom.xml
tools/ci/sonar_check.sh

[CI] Fix the problem that the code coverage metric is empty

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/kafka/KafkaLogSinkProvider.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/kafka/KafkaLogStoreFactory.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FileSystemCatalogITCase.java

This PR will close #740 .
FileSystemCatalogITCase.testLogWriteRead

[flink][bug] Support to automatically create a kafka topic when the topic not exists.

---

paimon-common/src/main/java/org/apache/paimon/utils/DateTimeUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/resources/mysql/setup.sql

Fix #860 
fix DATETIME type cast logic.
`MySqlSyncTableActionITCase#testAllTypes`
No
No

[flink][bug] Fix CDC Ingestion mysql DATETIME type cast error

---

docs/content/api/flink-api.md

[doc] Document Flink API

---

paimon-e2e-tests/README.md

[docs][e2e] Introduce README for e2e tests

---

paimon-common/src/main/java/org/apache/paimon/fs/Path.java

Modify useless comments in the Path class

[hotfix] Modify useless comments in the Path class

---

paimon-common/src/main/java/org/apache/paimon/fs/hadoop/HadoopViewFsFileIOLoader.java
paimon-common/src/main/resources/META-INF/services/org.apache.paimon.fs.FileIOLoader

Support viewfs FileIOLoader
this fix #946

[Feature] Support viewfs FileIOLoader

---

paimon-format/src/main/java/org/apache/paimon/format/orc/OrcWriterFactory.java

[format] Fix the issue of OrcWriterFactoryTest#testNotOverrideInMemoryManager NullPointerException in unit test.  #921 
No.
No.
No.

[format] Fix the issue of OrcWriterFactoryTest#testNotOverrideInMemoryManager NullPointerException in unit test.

---

docs/content/project/contributing.md

Refer to https://flink.apache.org/how-to-contribute/overview/

[doc] Document how to contribute

---

.github/workflows/check-licensing.yml
.github/workflows/code-analysys.yml
.github/workflows/e2e-tests-1.14.yml
.github/workflows/e2e-tests-1.15.yml
.github/workflows/e2e-tests-1.16.yml
.github/workflows/e2e-tests-1.17.yml
.github/workflows/publish_snapshot.yml
.github/workflows/utitcase-flink.yml
.github/workflows/utitcase.yml

[Feature] Improve ci trigger and cancel

---

paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

Fix tests failed in hive catalog #952 
Fix tests failed in hive catalog
*(Does this change affect API or storage format)* no
*(Does this change introduce a new feature)* no

[hive][tests] Fix tests in hive catalog

---

paimon-common/src/main/java/org/apache/paimon/plugin/PluginLoader.java

[Bug] PluginLoader localDirs cause PluginLoader error

---

docs/content/api/flink-api.md

fix flink api error. 'USE paimon'should be 'USE CATALOG paimon'
no
no
api#flink-api.md

[doc] fix flink api doc error

---

paimon-filesystems/paimon-s3-impl/src/main/resources/META-INF/NOTICE
paimon-format/src/main/resources/META-INF/NOTICE

rel #969 #968 #967 #965 
https://github.com/apache/incubator-paimon/actions/runs/4761095032/jobs/8462021431?pr=969#step:5:171

[hotfix] Found a total of 2 severe license issues

---

paimon-common/src/main/java/org/apache/paimon/types/DataTypes.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTypeUtils.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/resources/mysql/setup.sql

* issue  https://github.com/apache/incubator-paimon/issues/966*
*org.apache.paimon.flink.action.cdc.mysql.MySqlSyncTableActionITCase*

[flink] add more data type for mysql cdc action

---

docs/content/api/flink-api.md

Improve flink api doc
no
no
api#flink-api

[doc] Improve flink api doc

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogTest.java

Modify the  prompt when creating a flink table using FlinkCatalog.

[flink]Modify the prompt when creating a flink table using FlinkCatalog.

---

docs/content/api/java-api.md

Improve Java API documentation
no
no
api#java-api.md

[doc] Improve Java API documentation

---

docs/content/engines/overview.md
docs/content/engines/presto.md
docs/content/project/download.md

fix #667
add presto doc
no
no
engines#presto.md engines#overview.md project#download.md

[doc] add presto doc

---

docs/content/how-to/altering-tables.md

[docs] Guiding spark chaning column type

---

docs/content/how-to/cdc-ingestion.md
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSchema.java

[hotfix] Refactor column field name duplication check for MySqlSchema constructor

---

docs/content/api/java-api.md

[Improve][doc] Add supported data types for java api #997

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/resources/mysql/setup.sql

*issue https://github.com/apache/incubator-paimon/issues/966 *
*org.apache.paimon.flink.action.cdc.mysql.MySqlSyncTableActionITCase*

[flink] add time type for mysql cdc action

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/resources/mysql/setup.sql

Fix mysql timestamp cast error.
`MySqlSyncTableActionITCase#testAllTypes`
No
No

[flink][bug] Fix TIMESTAMP cast error in MySQL CDC

---

docs/content/engines/hive.md
paimon-hive/paimon-hive-common/src/main/java/org/apache/paimon/hive/HiveTypeUtils.java
paimon-hive/paimon-hive-common/src/test/java/org/apache/paimon/hive/HiveTypeUtilTest.java
paimon-hive/paimon-hive-common/src/test/java/org/apache/paimon/hive/HiveTypeUtilsTest.java

fix https://github.com/apache/incubator-paimon/issues/1009
Support row type for hive catalog.
HiveTypeUtilsTest
no
engines#hive.md

[hive] Support row type for hive catalog.

---

.gitignore

[improve] add  jacoco.exec to .gitignore

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/Action.java

[flink] printHelp

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecord.java

[flink]
parse mysql delete  correctly

[flink][bug] cdc sync action : mysql delete sync error

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/format/FormatWriterFactory.java
paimon-common/src/test/java/org/apache/paimon/format/FileStatsExtractorTestBase.java
paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java
paimon-core/src/main/java/org/apache/paimon/io/KeyValueFileWriterFactory.java
paimon-core/src/main/java/org/apache/paimon/io/RowDataFileWriter.java
paimon-core/src/main/java/org/apache/paimon/io/RowDataRollingFileWriter.java
paimon-core/src/main/java/org/apache/paimon/manifest/ManifestFile.java
paimon-core/src/main/java/org/apache/paimon/manifest/ManifestList.java
paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java
paimon-core/src/test/java/org/apache/paimon/FileFormatTest.java
paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java
paimon-core/src/test/java/org/apache/paimon/format/FileFormatSuffixTest.java
paimon-core/src/test/java/org/apache/paimon/format/FlushingFileFormat.java
paimon-core/src/test/java/org/apache/paimon/io/KeyValueFileReadWriteTest.java
paimon-core/src/test/java/org/apache/paimon/io/RollingFileWriterTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/LookupLevelsTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTest.java
paimon-format/src/test/java/org/apache/paimon/format/BulkFileFormatTest.java
paimon-format/src/test/java/org/apache/paimon/format/orc/OrcFileStatsExtractorTest.java
paimon-format/src/test/java/org/apache/paimon/format/orc/OrcWriterFactoryTest.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetFileStatsExtractorTest.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetReadWriteTest.java

fix #889 
Format
introduce a new feature

[core] Introduce file.compression

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java

[flink]validateMySqlConfig

---

docs/content/how-to/creating-catalogs.md
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/HiveCatalogTest.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

Hive catalog, name should be lower case

---

docs/content/concepts/append-only-table.md

[doc] Fix document mistake of append only table

---

docs/content/maintenance/write-performance.md

fix write-performance.md error

[doc] fix write-performance.md error

---

paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveWriteITCase.java

fix testInsertAllSupportedTypes

[hive]fix testInsertAllSupportedTypes(#752)

---

paimon-common/src/main/java/org/apache/paimon/data/JoinedRow.java

[Feature] Remove warning in mvn clean install #942
No
No
No

[minor] Reduce warning logs

---

paimon-flink/paimon-flink-common/pom.xml
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTypeUtils.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/resources/mysql/setup.sql

**issue https://github.com/apache/incubator-paimon/issues/966 **
add the follow data type:
GEOMETRY
POINT
LINESTRING
POLYGON
MULTIPOINT
MULTILINESTRING
MULTIPOLYGON
GEOMETRYCOLLECTION
*org.apache.paimon.flink.action.cdc.mysql.MySqlSyncTableActionITCase*

[flink]add spatial type for mysql cdc action

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/WriteMode.java
paimon-core/src/main/java/org/apache/paimon/table/FileStoreTableFactory.java
paimon-core/src/test/java/org/apache/paimon/schema/SchemaManagerTest.java
paimon-e2e-tests/src/test/java/org/apache/paimon/tests/FileStoreStreamE2eTest.java
paimon-flink/paimon-flink-1.14/src/test/java/org/apache/paimon/flink/FlinkActionITCase.java
paimon-flink/paimon-flink-1.15/src/test/java/org/apache/paimon/flink/FlinkActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FileStoreITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ForceCompactionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ReadWriteTableITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/DeleteActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/util/ReadWriteTableTestUtil.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/PaimonStorageHandlerITCase.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/mapred/PaimonRecordReaderTest.java
paimon-spark/paimon-spark-2/src/test/java/org/apache/paimon/spark/SimpleTableTestHelper.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadTestBase.java

[core] use append-only mode as the default write mode

---

docs/content/concepts/basic-concepts.md
docs/content/concepts/primary-key-table.md

Rephrase some content to improve the readability, since I had hard time to understand them. 
Fix some typos.

[hotfix][doc]improve readability and fix typos 

---

docs/content/project/contributing.md

[doc] remove redundant </ul> tag

---

pom.xml

[Improve] reduce warning logs when execute `mvn clean install`

---

paimon-common/src/main/java/org/apache/paimon/utils/ThreadUtils.java
paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeReadersConnectionsLeakTest.java
paimon-core/src/test/java/org/apache/paimon/utils/FailingConstructInputOutputIO.java

[core] [test] add test for bug mentioned in 1036

[test] add test for MergeTreeReaders connection leak for readers don't close correctly

---

paimon-core/src/main/java/org/apache/paimon/schema/Schema.java
paimon-core/src/test/java/org/apache/paimon/schema/SchemaBuilderTest.java

Currently, Schema#Builder.build hasn't check the arguments. This PR add validation to it.
No.
No.
No.

[core] Add validation in Schema#Builder

---

paimon-common/src/main/java/org/apache/paimon/utils/TypeUtils.java
paimon-common/src/test/java/org/apache/paimon/data/DataFormatTestUtil.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/resources/mysql/setup.sql

*related to https://github.com/apache/incubator-paimon/issues/966 *
* org.apache.paimon.flink.action.cdc.mysql.MySqlSyncTableActionITCase *

[flink] add set type for mysql cdc action

---

docs/content/engines/hive.md
docs/content/engines/overview.md
docs/content/how-to/creating-tables.md
paimon-core/src/main/java/org/apache/paimon/table/TableUtils.java
paimon-hive/paimon-hive-common/src/main/java/org/apache/paimon/hive/HiveTypeUtils.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/HiveSchema.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/PaimonMetaHook.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/PaimonStorageHandler.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/CreateTableITCase.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveTableSchemaTest.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveTestBase.java

[hive] Support Hive CREATE TABLE

---

README.md
docs/content/concepts/primary-key-table.md
docs/content/filesystems/hdfs.md
docs/content/how-to/altering-tables.md
docs/content/how-to/creating-catalogs.md
docs/content/project/contributing.md

[minor] fix typo in doc

---

docs/content/maintenance/write-performance.md
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/Action.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ActionBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java

[flink]
CompactAction support filesystem config
docs/content/maintenance/write-performance.md

[flink]CompactAction support catalog config

---

docs/content/how-to/altering-tables.md
paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-flink/paimon-flink-1.16/pom.xml
paimon-flink/paimon-flink-1.16/src/test/java/org/apache/paimon/flink/CatalogITCaseBase.java
paimon-flink/paimon-flink-1.16/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java
paimon-flink/paimon-flink-1.16/src/test/resources/log4j2-test.properties
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java

*Related to https://github.com/apache/incubator-paimon/issues/785*
*org.apache.paimon.flink.SchemaChangeITCase*

[flink] support alter table for flink

---

.github/PULL_REQUEST_TEMPLATE.md

Avoid showing explanatory notes
N/A

[community]: polish GitHub PR template.

---

.github/workflows/scope-label-conf.yml
.github/workflows/scope-label.yml

Add a GHA for adding labels based on modified files

[CI] Add a GHA for adding labels based on modified files

---

docs/content/engines/overview.md
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/CreateTableITCase.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveTestBase.java

Improve hive create table test case
CreateTableITCase

[hotfix][hive] Improve hive create table test case.

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkTableSink.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ReadWriteTableITCase.java

this close: https://github.com/apache/incubator-paimon/issues/786
To be added.

[flink] integrate DELETE for flink-1.17

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java

[flink][refactor] Remove duplicate code in MySqlSyncTableAction

---

docs/content/how-to/creating-catalogs.md
docs/content/how-to/creating-tables.md

Fix hdfs path in the document.

[hotfix][docs] Fix hdfs path in the document.

---

docs/content/api/java-api.md

Implove java api doc,add predicate.
no
no
api#java-api.md

[doc] Implove java api doc

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaChange.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java

fix https://github.com/apache/incubator-paimon/issues/980
Add addColumn refactoring method for SchemaChange class
CatalogTestBase
no
no

[core] Add addColumn refactoring method for SchemaChange class

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaChange.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java

fix https://github.com/apache/incubator-paimon/issues/985
Add updateColumnComment and updateColumnNullability overloaded methods to the SchemaChange class
CatalogTestBase
no
no

[core] Implove SchemaChange class

---

docs/content/how-to/writing-tables.md

add user documentation for `UPDATE`.  #787 
No.
No.
No.

[doc] add user documentation for UPDATE.

---

docs/content/engines/overview.md
docs/content/engines/presto.md
docs/content/how-to/altering-tables.md
docs/content/how-to/creating-tables.md

add create/alter table for presto doc
NO.
NO.
engines#presto.md , engines#overview.md, how-to#creating-tables.md, how-to#altering-tables.md

[doc] Update presto doc

---

paimon-common/src/main/java/org/apache/paimon/utils/InternalRowUtils.java

[improve] remove duplicate code

---

docs/content/engines/trino.md

Fix trino doc error
NO.
NO.
engines#trino.md

[doc] Fix trino doc error

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactManager.java

[hotfix][core] Fix the incorrect words in the log

---

docs/content/how-to/altering-tables.md
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java

[flink] Support modifying column comment by altering table on flink 1.17

---

docs/content/how-to/writing-tables.md

Add user documentation for DELETE.
No.
No.
No.

[doc] add user documentation for DELETE.

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSchema.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java

[flink][refactor] Extract caseSensitive related codes from MySqlSchema to util

---

docs/content/how-to/writing-tables.md

[hotfix][doc] fix user documentation for DELETE.

---

docs/content/project/download.md

Add paimon trino jar download address
NO.
NO.
project#download.md

[doc] Add paimon trino jar download address

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/CatalogUtils.java
paimon-core/src/main/java/org/apache/paimon/catalog/Identifier.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-core/src/test/java/org/apache/paimon/table/SchemaEvolutionTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunction.java

[hotfix] add column 'already exists' and 'does not exist' exception type

---

paimon-filesystems/paimon-hadoop-shaded/src/main/resources/META-INF/licenses/LICENSE.animal-sniffer
paimon-filesystems/paimon-s3-impl/src/main/resources/META-INF/licenses/LICENSE.animal-sniffer

Download from https://github.com/mojohaus/animal-sniffer/blob/master/LICENSE

[license] LICENSE.animal-sniffer should not be standard MIT

---

docs/content/maintenance/rescale-bucket.md

[core]
[Updated use case section of maintenance](https://paimon.apache.org/docs/master/maintenance/rescale-bucket/#use-case)
None
No
[maintenance](https://paimon.apache.org/docs/master/maintenance/rescale-bucket/#use-case)

[doc][maintenance] - Updated use case bullet point

---

docs/content/how-to/altering-tables.md
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java

fix #1075 
SchemaChangeITCase#testAddWatermark
SchemaChangeITCase#testDropWatermark
SchemaChangeITCase#testModifyWatermark

[flink] Support watermark change by altering table

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java

This PR resolves #1152 
SchemaChangeITCase under paimon-flink-1.17 
No
In a future issue.

[test] Add test for ADD/DROP/MODIFY columns for Flink 1.17

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkWrite.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkWriteITCase.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkWriteWIthKyroITCase.java

to fix https://github.com/apache/incubator-paimon/issues/635

[core] support kryo serialization

---

docs/content/how-to/cdc-ingestion.md

Follow-up for https://github.com/apache/incubator-paimon/pull/1148

[doc][Flink] add user doc for CDC computed column function `truncate`.

---

paimon-flink/paimon-flink-1.14/src/main/java/org/apache/paimon/flink/source/DataTableSource.java
paimon-flink/paimon-flink-1.15/src/main/java/org/apache/paimon/flink/source/DataTableSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/AbstractDataTableSource.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/statistics/AppendOnlyTableStatisticsTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/statistics/ChangelogValueCountTableStatisticsTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/statistics/ChangelogWithKeyTableStatisticsTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/statistics/FileStoreTableStatisticsTestBase.java

Support table statistics in table store related #758

[FLINK-30323] Support table statistics in table store

---

docs/content/engines/flink.md

Update some unclear phrases in the doc.

[hotfix][doc] update some unclear phrases

---

paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java

[core] Speed up SnapshotManager earlierOrEqualTimeMills

---

docs/content/concepts/file-operations.md
docs/content/maintenance/manage-snapshots.md
docs/content/maintenance/write-performance.md
paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/FileStore.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreExpireImpl.java
paimon-core/src/main/java/org/apache/paimon/operation/SnapshotDeletion.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/FileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/ReadonlyTable.java
paimon-core/src/main/java/org/apache/paimon/table/Table.java
paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
paimon-core/src/test/java/org/apache/paimon/operation/CleanedFileStoreExpireTest.java
paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/Action.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RollbackToAction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RollbackToActionITCase.java

Rollback table's state to a specific snapshot.
`FileStoreTableTestBase.testRollbackTo`
Yes Table.rollbackTo
Yes

[core] Introduce rollback to snapshot

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java

Using new APIs of `SchemaChange`, remove the redundant code.

[Fix][Flink] Using new api for schema change converter

---

docs/content/concepts/append-only-table.md

**Purpose** 
Fix [#1207](https://github.com/apache/incubator-paimon/issues/1207)

fix a sql syntax in doc

---

docs/content/concepts/file-operations.md

Fix typos and improve some description.

[hotfix][doc] fix typos and improve phrases of some content.

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalogFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ActionBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java

As tiltle.
This can fix problems like cannot access s3 in flink actions.
orignin.
no
no

[flink] Should pass FlinkFileIOLoader when creating catalog in flink actions

---

docs/content/filesystems/hdfs.md

[doc] Fix hdfs.md document configuration item input error

---

paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/PaimonStorageHandlerITCase.java

[hotfix][hive] Remove avro test in PaimonStorageHandlerITCase#testDateAndTimestamp

---

docs/content/engines/hive.md

Remind users that beeline does not support hive write
no
no
no

[doc] Remind users that beeline does not support hive write

---

docs/layouts/shortcodes/github_repo.html
docs/layouts/shortcodes/presto_github_repo.html
docs/layouts/shortcodes/trino_github_repo.html
docs/layouts/shortcodes/version.html

[hotfix] Fix typo in some shortcodes comment

---

paimon-core/src/main/java/org/apache/paimon/Snapshot.java

Fix  Snapshot file comment
NO.
NO.
NO.

[core] Fix  Snapshot file comment

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/AbstractDataTableSource.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ReadWriteTableITCase.java

Respect scan.parallelism, this is user-specified and should be the first priority

[flink] Respect scan.parallelism whatever the case

---

paimon-format/src/main/java/org/apache/paimon/format/avro/AvroSchemaConverter.java
paimon-format/src/main/java/org/apache/paimon/format/avro/AvroToRowDataConverters.java
paimon-format/src/main/java/org/apache/paimon/format/avro/RowDataToAvroConverters.java
paimon-format/src/test/java/org/apache/paimon/format/avro/AvroBulkFormatTest.java
paimon-format/src/test/java/org/apache/paimon/format/avro/AvroBulkFormatTestUtils.java
paimon-format/src/test/java/org/apache/paimon/format/avro/AvroFileFormatTest.java
paimon-format/src/test/java/org/apache/paimon/format/avro/AvroToRowDataConvertersTest.java
paimon-format/src/test/java/org/apache/paimon/format/avro/RowDataToAvroConvertersTest.java
paimon-hive/paimon-hive-common/src/main/java/org/apache/paimon/hive/HiveTypeUtils.java
paimon-hive/paimon-hive-common/src/test/java/org/apache/paimon/hive/HiveTypeUtilsTest.java

this close https://github.com/apache/incubator-paimon/issues/734

[core] paimon format avro support Timestamp LTZ

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ActionBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DeleteAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DropPartitionAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MergeIntoAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RollbackToAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/TableActionBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java

[flink] Introduce new ActionBase

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java

[flink] Add log in MySqlActionUtils#schemaCompatible for troubleshooting

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java

[flink] fix cdc issue

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ActionBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java

Action job should respect user define `pipeline.name`.

[flink] Use pipeline.name to action job name

---

docs/content/maintenance/manage-files.md
docs/content/maintenance/manage-partition.md
docs/content/maintenance/rescale-bucket.md

[doc] Introduce a page which documents small file number

---

paimon-e2e-tests/pom.xml
paimon-flink/paimon-flink-1.16/pom.xml
paimon-flink/paimon-flink-1.17/pom.xml
paimon-flink/paimon-flink-common/pom.xml
pom.xml

[flink] Bump flink version (1.16.1 to 1.16.2 and 1.17.0 to 1.17.1)

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/utils/RowDataToObjectArrayConverter.java
paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/manifest/ManifestFileMeta.java
paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileMetaTest.java
paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileMetaTestBase.java
paimon-core/src/test/java/org/apache/paimon/manifest/NoPartitionManifestFileMetaTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CompactorSinkITCase.java

add FullCompaction for Manifest File

[core] add FullCompaction for Manifest File

---

.github/PULL_REQUEST_TEMPLATE.md

You can link a pull request or branch to an issue to show that a fix is in progress and to automatically close the issue when the pull request or branch is merged.
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

[hotfix] Linking this pull request to the issue.

---

paimon-core/src/test/java/org/apache/paimon/operation/FileStoreExpireDeleteDirTest.java

[refactor][test] Extract duplicate code to util method in FileStoreExpireDeleteDirTest

---

paimon-common/src/main/java/org/apache/paimon/utils/InternalRowUtils.java
paimon-common/src/test/java/org/apache/paimon/utils/InternalRowUtilsTest.java

[common] Support TimeType comparing for aggregation merge engine

---

docs/content/engines/spark2.md

[docs] Fix typos in doc: spark2.md

---

docs/content/how-to/altering-tables.md

Fix the sql statement that changes the position of the column in Flink SQL.
see https://nightlies.apache.org/flink/flink-docs-release-1.17/docs/dev/table/sql/alter/#modify

[doc] Fix the sql statement that changes the position of the column in Flink SQL

---

docs/content/how-to/lookup-joins.md
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java

Linked issue: close #1303
testLookupPartitionedTable

[flink] Allow FileStoreLookupFunction to join partitioned table

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionITCaseBase.java

[hotfix] clean debug code

---

pom.xml

[pom] Update paimon shade to 0.4.0-incubating

---

docs/content/how-to/writing-tables.md
docs/content/maintenance/manage-snapshots.md
paimon-flink/paimon-flink-1.14/src/test/java/org/apache/paimon/flink/FlinkActionITCase.java
paimon-flink/paimon-flink-1.15/src/test/java/org/apache/paimon/flink/FlinkActionITCase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/Action.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ActionBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DeleteAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DropPartitionAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MergeIntoAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RollbackToAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/TableActionBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/DeleteActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/DropPartitionActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RollbackToActionITCase.java

Some flink actions hasn't parse catalog config, which cause S3 config cannot work. 
In addition, refactor some codes.
Add catalog-conf for the flink actions

[bug][refactor][flink] All flink actions should parse catalog config

---

docs/config.toml
docs/layouts/partials/docs/inject/content-before.html

Fix the link address of stable documentation.

[doc] Fix the link address of stable documentation.

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FileStoreSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkWriteSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSink.java

[refactor] Extract FlinkWriteSink class

---

paimon-core/src/main/java/org/apache/paimon/manifest/ManifestFile.java
paimon-core/src/main/java/org/apache/paimon/manifest/ManifestList.java
paimon-core/src/main/java/org/apache/paimon/utils/ObjectsFile.java

[core] Extract ObjectsFile.writeWithoutRolling

---

paimon-core/src/main/java/org/apache/paimon/table/sink/PartitionKeyExtractor.java
paimon-core/src/main/java/org/apache/paimon/table/sink/RowKeyExtractor.java
paimon-core/src/main/java/org/apache/paimon/table/sink/RowPartitionKeyExtractor.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowDataPartitionKeyExtractor.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowHashKeyChannelComputer.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowWithBucketChannelComputer.java

Introduce multiple flexible extractors.

[core] Introduce PartitionKeyExtractors

---

paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyTableCompactionCoordinator.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/sink/UnawareBucketRowKeyExtractor.java
paimon-core/src/main/java/org/apache/paimon/table/source/AbstractInnerTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/InnerStreamTableScanImpl.java
paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyTableCompactionITTest.java
paimon-core/src/test/java/org/apache/paimon/table/sink/UnawareBucketRowKeyExtractorTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/CompactorSourceBuilder.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/AppendOnlyTableITCase.java

1. Check schema when create non-bucket table.
2. Disable compaction when append-only table has unaware bucket
3. Add more tests for scan and schema check

[core] add unaware-bucket process for 'AppendOnlyFileStoreTable', add test for unaware-bucket table check and compaction.

---

docs/content/how-to/cdc-ingestion.md
paimon-e2e-tests/src/test/resources/log4j2-test.properties
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/resources/mysql/setup.sql

Scan newly added tables when recover from snapshot

---

paimon-core/src/main/java/org/apache/paimon/operation/SnapshotDeletion.java
paimon-core/src/main/java/org/apache/paimon/operation/TagFileKeeper.java

This PR cleans codes for #1278

[refactor] Remove useless class TagFileKeeper#DataFileInfo

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java

Fix EventParser initializes mysqlFiled every record.
MySqlSyncDatabaseActionITCase
MySqlSyncTableActionITCase
no
no

[flink] Improve EventParser initializes mysqlFiled every record

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/TableStreamingReader.java

A bug fix about bug fix: https://github.com/apache/incubator-paimon/pull/1361
Continuously refresh while look-up scan

[bug] bugfix: we should do continuously refresh while invoking look-up join

---

paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java

[core] Introduce tag prefix

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CompactorSinkBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/DynamicBucketSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkStreamPartitioner.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcSinkBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java

[flink] Use FlinkStreamPartitioner.partition

---

docs/content/how-to/writing-tables.md

[doc] Correct purging tables

---

paimon-common/src/main/java/org/apache/paimon/predicate/PredicateBuilder.java
paimon-common/src/test/java/org/apache/paimon/predicate/PredicateBuilderTest.java

[common] Support predicate on time type

---

paimon-hive/paimon-hive-connector-3.1/src/main/java/org/apache/paimon/hive/objectinspector/PaimonDateObjectInspector.java
paimon-hive/paimon-hive-connector-3.1/src/main/java/org/apache/paimon/hive/objectinspector/PaimonTimestampObjectInspector.java
paimon-hive/paimon-hive-connector-3.1/src/test/java/org/apache/paimon/hive/HiveWriteITCase.java

Support timestamp and date type in hive3 for hive writer
Linked issue: close #1368
HiveWriteITCase
no
no

[hive] Support timestamp and date type in hive3 for hive writer

---

paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/FileStore.java
paimon-core/src/main/java/org/apache/paimon/Snapshot.java
paimon-core/src/main/java/org/apache/paimon/operation/DeletionUtils.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreExpireImpl.java
paimon-core/src/main/java/org/apache/paimon/operation/SnapshotDeletion.java
paimon-core/src/main/java/org/apache/paimon/operation/TagDeletion.java
paimon-core/src/main/java/org/apache/paimon/operation/TagFileKeeper.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/ReadonlyTable.java
paimon-core/src/main/java/org/apache/paimon/table/Table.java
paimon-core/src/main/java/org/apache/paimon/utils/ParallellyExecuteUtils.java
paimon-core/src/test/java/org/apache/paimon/TestFileStore.java
paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java
paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java
paimon-core/src/test/java/org/apache/paimon/table/IndexFileExpireTableTest.java

Linked issue: close #1362
`FileStoreTableTestBase#testDeleteTag`
File deletion test:
`FileDeletionTest#testDeleteTagWithSnapshot`
`FileDeletionTest#testDeleteTagWithOtherTag`
`IndexFileExpireTableTest#testIndexFileExpirationWhenDeletingTag`

[core] Support deleting tag

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/Action.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DeleteAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DropPartitionAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MergeIntoAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RollbackToAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java

Extract some base codes;
Refactor exception logic;
Fix some errors.

[refactor] Refactor flink actions

---

paimon-core/src/main/java/org/apache/paimon/table/system/SystemTableLoader.java
paimon-core/src/main/java/org/apache/paimon/table/system/TagsTable.java
paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java

Add system table for tags.
new system table `<table>$tags`
TODO

[core] Introduce tags metadata table

---

docs/content/how-to/cdc-ingestion.md

[doc] Add solution for garbled chinese characters in CDC doc

---

.github/workflows/check-licensing.yml

[ci] Remove cache maven to fix out of range error

---

paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
paimon-e2e-tests/src/test/java/org/apache/paimon/tests/FlinkActionsE2eTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/Action.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CreateTagAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DeleteTagAction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/TagActionITCase.java

Allow user to create and delete tag by flink.
`TagActionITCase`
`FlinkActionsE2eTest#testCreateAndDeleteTag`
new flink actions:
create-tag
delete-tag
todo

[flink] Introduce create-tag and delete-tag actions

---

paimon-flink/paimon-flink-1.14/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java
paimon-flink/paimon-flink-1.15/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java

Run flink continuous file store IT Cases with parameterized changelog option, remove the double coded method with `changelog = true` and `changelog = false`

[flink] Run flink continuous file store IT Cases with parameterized changelog option

---

paimon-flink/paimon-flink-1.14/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
paimon-flink/paimon-flink-1.14/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java
paimon-flink/paimon-flink-1.15/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
paimon-flink/paimon-flink-1.15/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java

Complete the flink batch and streaming tests for `scan.mode`=`from-snapshot-full`

[flink] Add tests for scan.mode=from-snapshot-full

---

docs/content/concepts/file-operations.md

Add a description to explaining that DELETE needs to be run in the batch mode
no code change
no API/Format change
Change the documentation

[doc] Add a description explaining that DELETE needs to be run in the batch mode

---

docs/content/how-to/lookup-joins.md
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/ListDelimitedSerializer.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/NoPrimaryKeyLookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/RocksDBListState.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/RocksDBSetState.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/RocksDBStateFactory.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/LookupTableTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/RocksDBListStateTest.java

[flink] Add supports of lookup join on append-only table

---

docs/content/how-to/querying-tables.md
docs/content/how-to/system-tables.md
docs/content/maintenance/manage-tags.md

Linked issue: close #1406
no docs

[doc] Add doc for tag

---

paimon-core/src/main/java/org/apache/paimon/schema/TableSchema.java

Added validation of bucket keys when creating a table.

[core] Added validation of bucket keys when creating a table.

---

docs/content/api/flink-api.md

Dependency coordinate description error

[Hotfix][Doc]Dependency coordinate description error

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSchemaITCase.java

`KafkaSchemaTest` is a IT Test

[fix] rename it case tot ITCase

---

paimon-spark/paimon-spark-2/src/test/java/org/apache/paimon/spark/SparkTypeTest.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkTypeUtils.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadITCase.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadTestBase.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkSchemaEvolutionITCase.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkTypeTest.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkWriteITCase.java

[spark] convert non-null to nullable directly

---

docs/content/how-to/system-tables.md

Modify query system tag table name error

[doc] Modify query system tag table name error

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StaticFromTagStartingScanner.java

[core] fix typo in tag time travel related codes

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StateUtils.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java

fix the list state which lead that jm heap oom

[Flink]update union list state to avoid  inflation

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionUtils.java

Linked issue: close #1415 
Support properties.group.id in kafka cdc

[flink] Support properties.group.id in kafka cdc

---

docs/content/how-to/system-tables.md
paimon-core/src/main/java/org/apache/paimon/consumer/ConsumerManager.java
paimon-core/src/main/java/org/apache/paimon/table/system/ConsumersTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/SystemTableLoader.java
paimon-core/src/main/java/org/apache/paimon/utils/FileUtils.java
paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java

Linked issue: close #1475
Added system table consumers can be queried.
CatalogTableITCase

[core] Added system table consumers can be queried.

---

paimon-core/src/main/java/org/apache/paimon/table/system/ManifestsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/SystemTableLoader.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadITCase.java

Support for query manifests

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/WriteIntoPaimonTable.scala
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkWriteITCase.java

Disable shuffle for spark unaware-bucket table writes.

[spark] disable shuffle while writing unaware-bucket table

---

paimon-core/pom.xml
paimon-core/src/main/java/org/apache/paimon/metrics/Counter.java
paimon-core/src/main/java/org/apache/paimon/metrics/DescriptiveStatisticsHistogram.java
paimon-core/src/main/java/org/apache/paimon/metrics/DescriptiveStatisticsHistogramStatistics.java
paimon-core/src/main/java/org/apache/paimon/metrics/Gauge.java
paimon-core/src/main/java/org/apache/paimon/metrics/Histogram.java
paimon-core/src/main/java/org/apache/paimon/metrics/HistogramStatistics.java
paimon-core/src/main/java/org/apache/paimon/metrics/Metric.java
paimon-core/src/main/java/org/apache/paimon/metrics/MetricType.java
paimon-core/src/main/java/org/apache/paimon/metrics/SimpleCounter.java

[core] Introduce paimon metric interfaces

---

paimon-format/src/main/java/org/apache/paimon/format/parquet/writer/RowDataParquetBuilder.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetFileFormatTest.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetReadWriteTest.java

[Bug] Fix the parquet.compression do no work in parquet format

---

docs/content/engines/flink.md

Add doc about paimon action jars in engine/Flink

[doc] Document the Paimon action jars in Engine/Flink

---

docs/content/maintenance/manage-snapshots.md

Document the detail about snapshot expiration.
cc @JingsongLi

[doc] Document the detail about the snapshot expiration

---

docs/content/engines/spark3.md
docs/content/how-to/querying-tables.md
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkTimeTravelWithDataFrameITCase.java

add test and doc for spark time travel with data frame 
org.apache.paimon.spark.SparkTimeTravelWithDataFrameITCase
Add quering with data frame in spark3.md

[test][doc] Spark time travel with data frame test and doc

---

docs/content/concepts/overview.md

Update overview.md Clickhouse -> ClickHouse

---

paimon-common/src/main/java/org/apache/paimon/utils/IntHashSet.java
paimon-common/src/test/java/org/apache/paimon/utils/IntHashSetTest.java
paimon-core/src/main/java/org/apache/paimon/index/HashIndexMaintainer.java
paimon-core/src/test/java/org/apache/paimon/index/HashIndexMaintainerTest.java

We should check the hash index, not new hash, do not create new index file.

[core] Do not create new Index file if there is no change

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/table/system/ManifestsTable.java

Clean up redundant code in Manifests Table.

[hotfix] Clean up redundant code in Manifests Table.

---

docs/content/concepts/primary-key-table.md
docs/content/how-to/creating-tables.md
paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/casting/DefaultValueRow.java
paimon-core/src/main/java/org/apache/paimon/operation/DefaultValueAssiger.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/ChangelogValueCountFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/ChangelogWithKeyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/source/InnerStreamTableScanImpl.java
paimon-core/src/main/java/org/apache/paimon/table/source/InnerTableScanImpl.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
paimon-core/src/test/java/org/apache/paimon/operation/DefaultValueAssigerTest.java
paimon-core/src/test/java/org/apache/paimon/table/ChangelogWithKeyFileStoreTableTest.java
paimon-core/src/test/java/org/apache/paimon/table/SchemaEvolutionTest.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/DefaultValueScannerTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ReadWriteTableITCase.java

fix https://github.com/apache/incubator-paimon/issues/1322

[core] add default column value

---

paimon-spark/paimon-spark-2/pom.xml
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkRow.java

[spark] Fix the ClassCastException when creating timestamp data field in spark

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/table/ChangelogWithKeyFileStoreTable.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapperTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupChangelogWithAggITCase.java

[Bug] Fix the lookup changelog producer may produce wrong result

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumeratorTest.java

[flink] fix the issue that the historical snapshot may be lost when Enumerator performs snapshotState
Linked issue: close #1561 
Add `org.apache.paimon.flink.source.ContinuousFileSplitEnumeratorTest#testEnumeratorWithCheckpoint` to verify the correctness of checkpoint.
No.
No.

[flink] fix the issue that the historical snapshot may be lost when Enumerator performs snapshotState

---

paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/objectinspector/PaimonMapObjectInspector.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

Linked issue: related #1552 , but not solve it.

[hive] Added  the test case for Flink Write And Hive Read scenario.

---

paimon-hive/paimon-hive-common/src/main/java/org/apache/paimon/hive/HiveTypeUtils.java
paimon-hive/paimon-hive-common/src/test/java/org/apache/paimon/hive/HiveTypeUtilsTest.java

Linked issue: close #1565 
- Add test cases for the boundary conditions of maximum length for type conversion.

[hive]Fix the issue of type conversion error from Paimon to Hive type

---

paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/casting/DefaultValueRow.java
paimon-core/src/main/java/org/apache/paimon/io/KeyValueFileReaderFactory.java
paimon-core/src/main/java/org/apache/paimon/mergetree/MergeSorter.java
paimon-core/src/main/java/org/apache/paimon/operation/DefaultValueAssigner.java
paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreRead.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/source/InnerStreamTableScanImpl.java
paimon-core/src/main/java/org/apache/paimon/table/source/InnerTableScanImpl.java
paimon-core/src/main/java/org/apache/paimon/table/source/TableRead.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/BucketsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/ConsumersTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/FilesTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/ManifestsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/OptionsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/SchemasTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/SnapshotsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/TagsTable.java
paimon-core/src/test/java/org/apache/paimon/operation/DefaultValueAssignerTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java

[bug] Fix sort-spill-threshold with projection and refactor Default values

---

docs/content/how-to/writing-tables.md

[hotfix][doc] correct doc of purging partitions

---

docs/layouts/shortcodes/generated/mysql_sync_database.html
docs/layouts/shortcodes/generated/mysql_sync_table.html
paimon-e2e-tests/src/test/java/org/apache/paimon/tests/cdc/MySqlCdcE2eTestBase.java
paimon-e2e-tests/src/test/java/org/apache/paimon/tests/cdc/MySqlTinyIntConvertE2ETest.java
paimon-e2e-tests/src/test/resources/mysql/setup.sql
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSchema.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTableSchemaBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTypeUtils.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/resources/mysql/setup.sql

Linked issue: close https://github.com/)](https://github.com/apache/incubator-paimon/issues/1395

[flink][cdc] add option to decide convert mysql tinyint(1) to bool or not

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTableSchemaBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcMultiplexRecordEventParser.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/resources/mysql/setup.sql

[flink][mysql-cdc] MySQL CDC should ignore new tables that don't have primary keys or should be excluded

---

paimon-docs/pom.xml
pom.xml

unify maven dependency version

[maven] unify maven dependency version

---

docs/content/maintenance/write-performance.md
docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-format/src/main/java/org/apache/paimon/format/orc/OrcFileFormat.java
paimon-format/src/main/java/org/apache/paimon/format/orc/OrcWriterFactory.java
paimon-format/src/main/java/org/apache/paimon/format/orc/writer/OrcBulkWriter.java
paimon-format/src/test/java/org/apache/paimon/format/orc/writer/OrcBulkWriterTest.java

related #1375 
add write batch for orc format
org.apache.paimon.format.orc.writer.OrcBulkWriterTest.java
write-performance.md
core_configuration.html

[Format]add orc write batch size

---

paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/HiveSchema.java

When testing Paimon Hive connector with some Hive compatible system we meet the following problems:
1. Some system does not support `partition_columns` in properties. Instead they have a `TABLE_TOTAL_PARTITIONS` which records the number of partitions in that table. We should check both properties to determine if the table is a partitioned table.
2. Hive client and Hive workers may have different network environments. It is possible that Hive client cannot access the schema files. In this case we can create Hive table based on the Hive DDL given by user.
This PR solves the two problems above.
No.
No.

[hive] Refactor schema check between Paimon schema and Hive DDL

---

paimon-e2e-tests/src/test/java/org/apache/paimon/tests/cdc/MySqlCdcE2eTestBase.java
paimon-e2e-tests/src/test/java/org/apache/paimon/tests/cdc/MySqlComputedColumnE2ETest.java
paimon-e2e-tests/src/test/java/org/apache/paimon/tests/cdc/MySqlTinyIntConvertE2ETest.java

[flink][cdc] refactor mysql cdc e2e test

---

docs/content/engines/hive.md
docs/content/how-to/querying-tables.md
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/utils/HiveUtils.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/PaimonStorageHandlerITCase.java

[test][doc] Test and document Hive Time Travel

---

paimon-core/src/main/java/org/apache/paimon/Snapshot.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunctionTest.java
paimon-format/src/main/java/org/apache/paimon/format/orc/writer/OrcBulkWriter.java

Modify the wrong word from filed to field.

[hotfix] Modify the wrong word from filed to field.

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-core/src/test/java/org/apache/paimon/table/SchemaEvolutionTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java

Fix missing comment after updating column type.

[core] Fix missing comment after updating column type.

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java

Writer       ---->>>          Writer(write-only)    
(if the writer is write-only, table config with write-only=true)

[flink] flink web ui add write-only tag to writer(which is write only)

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperator.java

Limit memory pools in `CdcRecordStoreMultiWriteOperator` to avoid possible OOM.

[flink][cdc] Setting memory pool for multiple tables sink

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/LogicalTypeConversion.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogTest.java

Linked issue: close #1600 
Use Schema.Builder to build schema for flink schema when ddl
Added nest type in FlinkCatalogTest
no
no

[flink][schema] Use builder to build schema for flink ddl

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java

unify get catalog method for all test case  in flink action .

[flink] unify get catalog method for flink action

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcDynamicTableParsingProcessFunction.java

Linked issue: close https://github.com/apache/incubator-paimon/issues/1631

[flink] add error log for flink cdc database action

---

paimon-common/src/main/java/org/apache/paimon/types/ReassignFieldId.java
paimon-common/src/test/java/org/apache/paimon/types/ReassignFieldIdTest.java

Linked issue: close #1642 
Fix reassign field id for nested row type
Added test ReassignFieldIdTest for nested row type
no
no

[core][schema] Reassign field id for nested row type

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkGenericCatalogTest.java

fix spark generic catalog could not load existing paimon tables
spark_catalog will throw NoSuchDatabaseException in loadTable(ident)

[bug] [bugfix] fix spark generic catalog could not load existing paimon tables

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkTypeUtils.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkGenericCatalogTest.java

Linked issue: close #1602 
Use Schema.Builder to build schema for spark ddl
Added test SparkGenericCatalogTest.testStructTable to create table with struct type
no
no

[spark][schema] Use builder to build schema for spark ddl

---

paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkSchemaEvolutionITCase.java

[spark] fix SparkSchemaEvolutionITCase docs

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-common/src/main/java/org/apache/paimon/hive/HiveTypeUtils.java
paimon-hive/paimon-hive-common/src/test/java/org/apache/paimon/hive/HiveTypeUtilsTest.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/HiveSchema.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/PaimonMetaHook.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/objectinspector/PaimonInternalRowObjectInspector.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/objectinspector/PaimonObjectInspectorFactory.java

[hotfix] refactor HiveTypeUtils

---

paimon-core/src/test/java/org/apache/paimon/memory/MemoryPoolFactoryTest.java

fix MemoryPoolFactoryTest#testAddOwners

[fix] fix unstable test MemoryPoolFactoryTest#testAddOwners

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

Linked issue: close https://github.com/apache/incubator-paimon/issues/1661

[flink] clear schema after create/alter hive table error

---

paimon-common/src/main/java/org/apache/paimon/types/DataTypeChecks.java
paimon-common/src/main/java/org/apache/paimon/types/DataTypes.java

[core] Introduce getPrecision and getLength to DataTypes

---

docs/content/how-to/cdc-ingestion.md
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSchema.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseTableListITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/resources/mysql/sync_database_setup.sql
paimon-flink/paimon-flink-common/src/test/resources/mysql/tablelist_test_setup.sql

[flink][mysql-cdc] Support Synchronizing multiple shards into one database

---

paimon-core/src/main/java/org/apache/paimon/table/system/PartitionsTable.java

Fix the value of partitions table primary Keys.

[core] Fix the value of partitions table primary Keys.

---

docs/content/how-to/querying-tables.md

[doc]Supplement the tag function description of the hive engine

---

docs/content/how-to/cdc-ingestion.md
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/ComputedColumn.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/Expression.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/TruncateComputerTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/resources/mysql/sync_table_setup.sql

[flink][mysql-cdc] Add synchronizing shards test for MySqlSyncTableAction and do minor code refactor

---

docs/content/maintenance/manage-snapshots.md

[hotfix][doc] Fix a typo in manage-snapshots

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java

I think we should better use constant instead of string

[filnk] replace the string class name with constant

---

docs/content/how-to/cdc-ingestion.md
docs/layouts/shortcodes/generated/mysql_sync_database.html
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/TableNameConverter.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSchema.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionFactory.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlContainer.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseTableListITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/resources/mysql/sync_database_setup.sql
paimon-flink/paimon-flink-common/src/test/resources/mysql/tablelist_test_setup.sql

[flink][mysql-cdc] Support database synchronization without merging shards

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSchema.java

[flink][kafka-cdc] Fix that Kafka consumer mistakenly consumes records when getting KafkaSchema

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseTableListITCase.java

Linked issue: close #1750 
fix unstable test: MySqlSyncDatabaseTableListITCase#testActionRunResult
No
No

[flink] fix unstable test: MySqlSyncDatabaseTableListITCase#testActionRunResult

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/ComputedColumnUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSchema.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncDatabaseActionITCase.java

Linked issue: close #1746 
Fix Null point exception when kafka cdc operation does not configure group id

[kafka-cdc] Fix Null point exception when kafka cdc operation does not configure group id 

---

paimon-core/src/main/java/org/apache/paimon/table/system/FilesTable.java

Linked issue: close (https://github.com/apache/incubator-paimon/issues/1755)

[flink] validate dataFileMeta maxKey field

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java

Linked issue: close (https://github.com/apache/incubator-paimon/issues/1700)

[flink]do not throw exception when cdc table change is null

---

docs/content/how-to/cdc-ingestion.md
docs/layouts/shortcodes/generated/mysql_sync_database.html
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseTableListITCase.java

Linked issue: close  https://github.com/apache/incubator-paimon/issues/1742

[flink] sync the table with same name in different  db

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkTable.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonAnalysis.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/WriteIntoPaimonTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/paimon/commands/PaimonDynamicPartitionOverwriteCommand.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/InsertOverwriteTest.scala

[spark] supports dynamic insert overwrite

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/resources/mysql/sync_table_setup.sql

Linked issue: close  https://github.com/apache/incubator-paimon/issues/1711

[flink] Fix the table list of mysql cdc table synchronization action

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkSource.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/sources/PaimonSink.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/Utils.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSinkTest.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DataFrameWriteTest.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/InsertOverwriteTest.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/TableValuedFunctionsTest.scala

Linked issue: close [#xxx](https://github.com/apache/incubator-paimon/issues/1130)

[spark] Supports Spark Streaming Sink

---

docs/content/how-to/altering-tables.md

[doc] add doc for `drop column` ddl 

---

paimon-common/src/test/java/org/apache/paimon/format/FormatReadWriteTest.java
paimon-format/src/test/java/org/apache/paimon/format/orc/OrcFormatReadWriteTest.java

[test] Fix the OrcFormatReadWriteTest

---

docs/layouts/shortcodes/generated/flink_catalog_configuration.html
docs/layouts/shortcodes/generated/flink_connector_configuration.html
paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalogFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalogOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/kafka/KafkaLogStoreFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/kafka/KafkaLogStoreRegister.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LogSystemITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/kafka/KafkaLogStoreRegisterTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/kafka/KafkaTableTestBase.java

Linked issue: close https://github.com/apache/incubator-paimon/issues/1533
* KafkaLogStoreRegisterTest
* LogSystemITCase

[flink] supports kafka log system registration

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadITCase.java

[core] Validate changelog producer on table without primary keys

---

docs/content/how-to/altering-tables.md

[doc] fix spark changing column type

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/schema/AllMergedMySqlTableInfo.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/schema/MySqlSchema.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/schema/MySqlSchemasInfo.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/schema/MySqlTableInfo.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/schema/ShardsMergedMySqlTableInfo.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/schema/UnmergedMySqlTableInfo.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseTableListITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/resources/mysql/sync_database_setup.sql
paimon-flink/paimon-flink-common/src/test/resources/mysql/sync_table_setup.sql

1. Extract shards merging logic.
2. Refactor some tests to validate more case.

[flink][mysql-cdc] Refactor MySqlSchema related cods

---

docs/content/maintenance/manage-files.md
docs/content/maintenance/multiple-writers.md
docs/content/maintenance/read-performance.md
docs/content/maintenance/write-performance.md

Some suggestions for maintenance docs

[doc] rephrase some maintenance docs

---

docs/layouts/shortcodes/generated/compute_column.html
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/Expression.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java

Support dateFormat compute functions
Linked issue: close #1805

[flink] Support dateFormat compute functions

---

docs/content/how-to/creating-tables.md

fix doc default-value typo error.

fix doc default-value typo error.

---

paimon-common/src/main/java/org/apache/paimon/data/columnar/ColumnarArray.java

[hotfix] Fix ColumnarArray#getBinary

---

docs/content/how-to/system-tables.md

Added a link to the configurations documentation in the `Options Table` section of the system table documentation.
before change:
after change:

[doc] Added a link to the configurations documentation in the `Options Table` section of the system table documentation.

---

paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/PaimonMetaHook.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/CreateTableITCase.java

Hive create table should force table names to be lowercase,consistent with hive behavior.
#1760 
CreateTableITCase
no
no

[hive] Hive create table force db name and  table names to be lowercase

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/MultiTableUpdatedDataFieldsProcessFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunctionBase.java

[flink] refactor update data fields process function

---

paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/CreateTableITCase.java

Fix test error in the CreateTableITCase
error: https://github.com/apache/incubator-paimon/actions/runs/5875818036/job/15932765351#step:4:109157

[hotfix] Fix test error in the CreateTableITCase

---

docs/content/how-to/cdc-ingestion.md
paimon-flink/paimon-flink-common/pom.xml
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/JsonParserUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/ModeEnum.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBActionUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBRecordParser.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongodbSchema.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/strategy/Mongo4VersionStrategy.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/strategy/MongoVersionStrategy.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/JsonParserUtilsTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBContainer.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/resources/log4j2-test.properties
paimon-flink/paimon-flink-common/src/test/resources/mongodb/database/test-data-1.js
paimon-flink/paimon-flink-common/src/test/resources/mongodb/database/test-data-2.js
paimon-flink/paimon-flink-common/src/test/resources/mongodb/database/test-data-3.js
paimon-flink/paimon-flink-common/src/test/resources/mongodb/database/test-data-4.js
paimon-flink/paimon-flink-common/src/test/resources/mongodb/docker/random.key
paimon-flink/paimon-flink-common/src/test/resources/mongodb/docker/setup.js
paimon-flink/paimon-flink-common/src/test/resources/mongodb/table/inventory-1.js
paimon-flink/paimon-flink-common/src/test/resources/mongodb/table/inventory-2.js
paimon-flink/paimon-flink-common/src/test/resources/mongodb/table/inventory-3.js
paimon-flink/paimon-flink-common/src/test/resources/mongodb/table/inventory-4.js

Linked issue: close #1699 
UT:JsonParserUtilsTest
IT:MongoDBSyncTableActionITCase、MongoDBSyncDatabaseActionITCase

[flink]SyncAction based on MongoDB

---

.github/workflows/check-licensing.yml
.github/workflows/e2e-tests-1.14-jdk11.yml
.github/workflows/e2e-tests-1.14.yml
.github/workflows/e2e-tests-1.15-jdk11.yml
.github/workflows/e2e-tests-1.15.yml
.github/workflows/e2e-tests-1.16-jdk11.yml
.github/workflows/e2e-tests-1.16.yml
.github/workflows/e2e-tests-1.17-jdk11.yml
.github/workflows/e2e-tests-1.17.yml
.github/workflows/publish_snapshot.yml
.github/workflows/unitcase-flink-jdk11.yml
.github/workflows/unitcase-jdk11.yml
.github/workflows/utitcase-flink.yml
.github/workflows/utitcase.yml

-T 1C to speed up build efficiency
after change：

[core]CI execution optimization

---

paimon-core/src/main/java/org/apache/paimon/tag/TagAutoCreation.java
paimon-core/src/test/java/org/apache/paimon/tag/TagAutoCreationTest.java

[core] fix tagTotime parse error

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/DatabaseSyncMode.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/MultiTableUpdatedDataFieldsProcessFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunctionBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseTableListITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/resources/mysql/sync_database_setup.sql

[refactor] Refactor MySQL CDC actions to make it easier to introduce new features

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactActionITCase.java

[flink] minor update compaction test case

---

.github/workflows/utitcase-flink.yml

To solve the flink test timeout problem

[hotfix] Temporarily set flink test timeout to 80 minutes

---

paimon-core/src/main/java/org/apache/paimon/schema/Schema.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

hive create table should force primary key not null
HiveCatalogITCaseBase
no
no

[hive]hive create table should force primary key not null

---

docs/content/engines/hive.md

fix beeline instructions for use
no
no
no

[hotfix] [doc] fix beeline instructions for use

---

docs/content/concepts/primary-key-table.md
docs/layouts/shortcodes/generated/mysql_sync_database.html
docs/layouts/shortcodes/generated/mysql_sync_table.html

[doc]Minor document optimization

---

docs/content/api/flink-api.md
docs/content/concepts/append-only-table.md
docs/content/engines/flink.md
docs/content/filesystems/hdfs.md
docs/content/filesystems/oss.md
docs/content/filesystems/s3.md
docs/content/how-to/cdc-ingestion.md
docs/content/how-to/creating-catalogs.md
docs/content/how-to/lookup-joins.md
docs/content/how-to/writing-tables.md
docs/content/maintenance/manage-tags.md
docs/content/maintenance/rescale-bucket.md
docs/layouts/shortcodes/generated/kafka_sync_database.html
docs/layouts/shortcodes/generated/kafka_sync_table.html
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableActionFactory.java

….
Modify the flink documentation link to point to the flink stable version.
All modified links were manually click-tested.

[doc] Modify the flink documentation link to point to the flink stable version

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcMultiplexRecordEventParser.java

[flink][kafka-cdc] Kafka cdc doesn't need to check table's primary keys

---

docs/layouts/shortcodes/generated/flink_connector_configuration.html
paimon-core/src/main/java/org/apache/paimon/sort/zorder/ZIndexer.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/OrderRewriteActionITCase.java

some code style fix and small spelling error

[fix] fix some code style issues and minus spelling error

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/formats/canal/CanalRecordParser.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/formats/ogg/OggRecordParser.java

[flink][kafka-cdc] Minor refactor kafka cdc record parser

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkTable.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonPartitionManagement.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonPartitionManagementTest.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/WithTableOptions.scala

Linked feature: close #[1584](https://github.com/apache/incubator-paimon/issues/1584)
org.apache.paimon.spark.SparkReadITCase#testShowPartition
org.apache.paimon.spark.SparkReadITCase#testDropPartition

[Spark] Spark supports PARTITION MANAGEMENT

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaOggSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaOggSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java

Remove the duplicate parts of the test case

[flink] Remove the duplicate parts of the test case

---

docs/content/how-to/system-tables.md
paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/table/system/CatalogOptionsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/SystemTableLoader.java
paimon-core/src/test/java/org/apache/paimon/table/system/CatalogOptionsTableTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java

[core] Support catalog options table

---

docs/content/concepts/primary-key-table.md
docs/content/how-to/querying-tables.md
docs/layouts/shortcodes/generated/core_configuration.html
docs/layouts/shortcodes/generated/flink_connector_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/DataTableSource.java

[doc] Document Flink scan remove normalize

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ActionBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/DatabaseSyncMode.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/TypeMapping.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/CdcActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaOggSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaOggSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlCdcTypeMappingITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseTableListITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java

To make sure the action arguments are correctly parsed.

[flink][cdc] Build all the cdc test actions from arguments

---

docs/content/how-to/cdc-ingestion.md
docs/layouts/shortcodes/generated/kafka_sync_database.html
docs/layouts/shortcodes/generated/kafka_sync_table.html
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSchema.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/formats/DataFormat.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/formats/RecordParser.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/formats/RecordParserFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/formats/canal/CanalRecordParser.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/formats/ogg/OggRecordParser.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTypeUtils.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSchemaITCase.java
paimon-flink/paimon-flink-common/src/test/resources/kafka/canal/database/tostring/canal-data-1.txt
paimon-flink/paimon-flink-common/src/test/resources/kafka/canal/table/tostring/canal-data-1.txt

Additionally, refactor kafka cdc test.
KafkaCanalSyncDatabaseActionITCase#testTypeMappingToString
kafka cdc: --type-mapping
cdc ingestion

[flink][kafka-cdc] Kafka Canal CDC supports data type to string mapping

---

paimon-core/src/main/java/org/apache/paimon/table/system/BucketsTable.java

- To specify the database of the wrapped table of  `BucketsTable`;
- add two columns (databaseName and tableName) for `BucketsTable `;

[core] Add database name and table name in BucketsTable

---

docs/content/concepts/external-log-systems.md
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/kafka/KafkaLogSinkProvider.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/kafka/KafkaLogStoreFactory.java

[flink] Remove the code for topic creation in `KafkaLogSinkProvider`
Linked issue: close #1891 
No
No
No

[flink] Remove the code for topic creation in KafkaLogSinkProvider.

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/FileStoreLookupFunctionTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/AppendOnlyTableCompactionWorkerOperatorTest.java

fix test AppendOnlyTableCompaction stock in future get

[test] fix test AppendOnlyTableCompaction stock in future get

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/Action.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/SortCompactAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/CdcActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionITCaseBase.java

[flink] Remove Redundant Test Methods

---

docs/content/how-to/cdc-ingestion.md

Correct the errors in the document.

[doc] Correct the errors in the document

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/CdcActionCommonUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSchema.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/formats/RecordParser.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/formats/canal/CanalRecordParser.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/formats/ogg/OggRecordParser.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBActionUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongodbSchema.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/strategy/MongoVersionStrategy.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTableSchemaBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/schema/MySqlSchema.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaOggSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java

[flink][cdc] Extract common util methods

---

docs/content/maintenance/manage-tags.md

remove  duplicate tag to fix docs compile bug
Linked issue: close #1922

[bug][docs] Fix docs compile bug

---

docs/content/how-to/querying-tables.md
docs/content/how-to/writing-tables.md

[doc][spark] fix spark.sql.extensions fully qualified class name

---

paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkTimeTravelWithDataFrameITCase.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkWriteWithKyroITCase.java

[hotfix] Minor fix spark test error

---

.github/workflows/docs-tests.yml

Linked issue: close #1937 
When the document has syntax errors:
the related pr: #1923

[hotfix] add docs test ci

---

pom.xml

see https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/647

[hotfix] Skip compile failure on no git directory

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkRow.java

[Bug] Fix spark array and map type error when write

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/formats/canal/CanalRecordParser.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/strategy/MongoVersionStrategy.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcMultiplexRecordSchemaBuilder.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/TestCaseInsensitiveCatalogFactory.java

Fix the issue of throwing an exception related to field size after adding a new table.
MongoDBSyncDatabaseActionITCase#testDynamicTableCreationInMongoDB()

[flink] fix exception related to field size after adding a new table

---

docs/content/api/java-api.md
docs/content/concepts/file-operations.md
docs/content/concepts/primary-key-table.md
paimon-benchmark/paimon-cluster-benchmark/README.md
paimon-benchmark/paimon-cluster-benchmark/src/main/java/org/apache/paimon/benchmark/Benchmark.java
paimon-benchmark/paimon-cluster-benchmark/src/main/resources/bin/config.sh

[doc] Update docs in benchmark and java api

---

paimon-core/src/main/java/org/apache/paimon/table/source/AbstractInnerTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/InnerStreamTableScanImpl.java
paimon-core/src/main/java/org/apache/paimon/table/source/InnerTableScanImpl.java
paimon-core/src/main/java/org/apache/paimon/table/source/StreamTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/AbstractStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/CompactedStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousCompactorStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousFromSnapshotFullStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousFromSnapshotStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousFromTimestampStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousLatestStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/FullCompactedStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/FullStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalTagStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalTimeStampStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StartingContext.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StaticFromSnapshotStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StaticFromTagStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StaticFromTimestampStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/CompactedStartingScannerTest.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ContinuousCompactorStartingScannerTest.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ContinuousFromTimestampStartingScannerTest.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ContinuousLatestStartingScannerTest.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/FullCompactedStartingScannerTest.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/FullStartingScannerTest.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/StaticFromTagStartingScannerTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumeratorTest.java

Let StartingScanner return some information that will be used in Spark Streaming Source.

[core] Supports StartingContext and Mini-Refactor StartingScanner

---

paimon-common/src/main/java/org/apache/paimon/options/Options.java
paimon-core/src/main/java/org/apache/paimon/table/source/InnerStreamTableScanImpl.java
paimon-core/src/main/java/org/apache/paimon/table/source/StreamTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousFromTimestampStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousLatestStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StartingContext.java
paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumeratorTest.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkScan.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkScanBuilder.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkTable.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonPartitionManagement.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkSource.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/SchemaHelper.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/WithFileStoreTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/sources/PaimonMicroBatchStream.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/sources/PaimonSourceOffset.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/sources/StreamHelper.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/util/JsonUtils.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSourceTest.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala

[spark] Supports Spark Streaming Source

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/AppendOnlyTableCompactionWorkerOperatorTest.java

Add wait time for runnable in thread pool, the last runnable may not be stopped by shutdown.

[test] add wait time for runnable in thread pool

---

paimon-common/src/main/java/org/apache/paimon/plugin/PluginLoader.java

[core] Try to delete plugin jar

---

docs/content/concepts/basic-concepts.md

Consistency Guarantees description is faulty

[doc] Consistency Guarantees description is faulty

---

docs/content/concepts/file-layouts.md
docs/content/maintenance/dedicated-compaction.md
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactDatabaseActionFactory.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactDatabaseActionITCase.java

[flink] Refactor Flink Database compaction job

---

docs/layouts/shortcodes/generated/catalog_configuration.html
docs/layouts/shortcodes/generated/flink_catalog_configuration.html
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalogOptions.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogTest.java

Linked issue: close https://github.com/apache/incubator-paimon/issues/1729
FlinkCatalogTest

[flink] add option to support disable creating table in default database

---

docs/layouts/shortcodes/generated/catalog_configuration.html
docs/layouts/shortcodes/generated/spark_connector_configuration.html

There exists some unused config in doc.

[doc] Rebuild doc with mvn command

---

docs/content/concepts/append-only-table.md
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java
paimon-core/src/main/java/org/apache/paimon/disk/ExternalBuffer.java
paimon-core/src/main/java/org/apache/paimon/disk/InMemoryBuffer.java
paimon-core/src/main/java/org/apache/paimon/disk/RowBuffer.java
paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java
paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java
paimon-core/src/test/java/org/apache/paimon/disk/ExternalBufferTest.java
paimon-core/src/test/java/org/apache/paimon/disk/InMemoryBufferTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalIndexAssignerOperator.java

[core] Refactor Multiple Partitions Write for Append table

---

docs/layouts/shortcodes/generated/catalog_configuration.html
docs/layouts/shortcodes/generated/spark_connector_configuration.html
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/SortOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/SortUtils.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sorter/SortOperatorTest.java

[fix] clear sort buffer after zorder sort complete

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseAction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableAction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableActionFactory.java

Keep the mongodb action construction logic the same as mysql and kafka

[flink] Optimize mongodb action build

---

paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/extensions/CallStatementParserTest.java

[hotfix] fix failed test CallStatementParserTest

---

docs/content/maintenance/manage-snapshots.md

Linked issue: close #2031 
[core] add doc for asynchronous expiration.
No
No
No

[core] add doc for asynchronous expiration.

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionUtils.java

fix kafka CDC Ingestion multi-topic exception

[flink] Fix kafka CDC Ingestion multi-topic exception

---

docs/content/how-to/cdc-ingestion.md

specify the MongoDB CDC version

[flink] Specify the MongoDB CDC version

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongodbSchema.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBActionITCaseBase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBContainer.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongodbSchemaITCase.java

fix:Caused by: com.mongodb.MongoQueryException: Query failed with error code 13 and error message 'command find requires authentication' on server 127.0.0.1:27017.
MongodbSchemaITCase

[flink] Fix mongodb CDC Ingestion QueryException

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/formats/RecordParser.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/formats/canal/CanalRecordParser.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaOggSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/resources/kafka/canal/database/case-insensitive/canal-data-1.txt
paimon-flink/paimon-flink-cdc/src/test/resources/kafka/ogg/database/case-insensitive/ogg-data-1.txt
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcMultiplexRecordSchemaBuilder.java

[cdc] kafka cdc uses hive catalog to support field conversion to lowercase

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/sources/PaimonMicroBatchStream.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/sources/PaimonSourceOffset.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/sources/StreamHelper.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSourceTest.scala

[spark] Refactor needToScanCurrentSnapshot in PaimonSourceOffset

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/strategy/Mongo4VersionStrategy.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/resources/mongodb/table/event/event-delete.js
paimon-flink/paimon-flink-cdc/src/test/resources/mongodb/table/event/event-insert.js
paimon-flink/paimon-flink-cdc/src/test/resources/mongodb/table/event/event-replace.js
paimon-flink/paimon-flink-cdc/src/test/resources/mongodb/table/event/event-update.js

fix:java.lang.unsupportedoperationexception: Unknown record type: delete
MongoDBSyncTableActionITCase#testMongoDBCDCOperations()

[flink] Fix mongodb CDC Ingestion unknown delete

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MergeIntoActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/TableActionBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CompactDatabaseProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CompactProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CreateTagProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/DeleteTagProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/DropPartitionProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/MergeIntoProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ProcedureBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ProcedureUtil.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ResetConsumerProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RollbackToProcedure.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ConsumerActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/DropPartitionActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/MergeIntoActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RollbackToActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/TagActionITCase.java

DeleteAction is ignored because we can use flink `DELETE` statement.

[flink] Translate actions to procedures

---

docs/content/engines/overview.md

[doc] update the progress of Doris Paimon Catalog

---

paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlCdcTypeMappingITCase.java

[cdc] fix mysql cdc test char to string type mapping

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/CdcActionCommonUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/ComputedColumnUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/schema/AllMergedMySqlTableInfo.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/schema/MySqlSchemaUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/schema/MySqlSchemasInfo.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/schema/MySqlTableInfo.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/schema/ShardsMergedMySqlTableInfo.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/schema/UnmergedMySqlTableInfo.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java

1.Use public `Schema` to replace `MysqlSchema`
2.Add mysql table comments to paimon table schema

[cdc] Refactor mysql schema build in mysql cdc action

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/CdcActionCommonUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/ComputedColumnUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSchemaUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableAction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/formats/RecordParser.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBActionUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableAction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongodbSchemaUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/schema/MySqlSchemaUtils.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSchemaITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongodbSchemaITCase.java

[cdc] Refactor Kafka and MongoDB cdc schema build

---

paimon-core/src/main/java/org/apache/paimon/table/system/PartitionsTable.java
paimon-core/src/test/java/org/apache/paimon/table/TableTestBase.java
paimon-core/src/test/java/org/apache/paimon/table/system/PartitionsTableTest.java

[Bug] Fix the wrong record count for partitions table

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/CdcActionCommonUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTableSchemaBuilder.java

Optimize Duplicate Field Detection in MySQL CDC Schema Building.

[cdc] Optimize Duplicate Field Detection in MySQL CDC Schema Building.

---

paimon-core/src/main/java/org/apache/paimon/metrics/AbstractMetricGroup.java
paimon-core/src/main/java/org/apache/paimon/metrics/Metrics.java
paimon-core/src/test/java/org/apache/paimon/metrics/MetricGroupTest.java

[core] Support remove metric groups from metric instance

---

docs/content/engines/presto.md

[Doc] Update presto.md

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java

[flink] Fine-grained resource management parameter verification

---

paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java

[core] Fix the issue of table copy

---

docs/content/maintenance/dedicated-compaction.md

Adding instructions related to parameter settings in ON YARN scenarios
null
For paimon-action, if the user uses FLINK ON YARN, the current documentation does not describe how to set the parameters in this scenario. Given the large number of users using FLINK ON YARN, I think we need to add documentation.

[DOC] Adding instructions related to parameter settings in ON YARN scenarios

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CompactProcedure.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/SortCompactActionITCase.java

Simplify the usage of compact procedure in flink action.
Just change the way to pass the parameters, no other influence to user.
Wait for @yuzelin repair merge-into and add doc for procedure together

[flink] simplify the usage of flink compact procedure

---

docs/content/engines/overview.md
docs/content/engines/spark3.md

[spark] structured streaming docs

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBActionUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java

[CDC]Change the method of the CDC Util class to public

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java

In some cases, we may need to extend the flink catalog to inject customerized schema options. 
This PR extracts the code for constructing paimon schema from CatalogTable to make it easier to override the behavior.

[flink] Refactor FlinkCatalog to inject customerized schema options

---

docs/content/how-to/querying-tables.md
paimon-common/src/main/java/org/apache/paimon/utils/StringUtils.java
paimon-core/src/main/java/org/apache/paimon/consumer/ConsumerManager.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ResetConsumerAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ResetConsumerActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ResetConsumerProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RollbackToProcedure.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ConsumerActionITCase.java

…r ID.
reset consumer action supports delete a consumer with a given consumer ID
ConsumerActionITCase#testResetConsumer

[flink] Reset consumer action supports delete a consumer with a given consumer ID

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CompactDatabaseProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CompactProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CreateTagProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/DeleteTagProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/DropPartitionProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/MergeIntoProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ProcedureBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ProcedureUtil.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ResetConsumerProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RollbackToProcedure.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory

Procedure implementation class supports automatic discovery.

[hotfix] Procedure implementation class supports automatic discovery.

---

docs/content/engines/spark3.md
docs/layouts/shortcodes/generated/spark_connector_configuration.html
paimon-common/src/main/java/org/apache/paimon/utils/TypeUtils.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkConnectorOptions.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkScan.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkSource.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/sources/PaimonMicroBatchStream.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/sources/StreamHelper.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonCDCSourceTest.scala

[spark] Spark supports read changelog

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CompactDatabaseProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CompactProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CreateTagProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/DeleteTagProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/DropPartitionProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/MergeIntoProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ProcedureUtil.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ResetConsumerProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RollbackToProcedure.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ConsumerActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/DropPartitionActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/MergeIntoActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RollbackToActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/SortCompactActionForDynamicBucketITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/SortCompactActionForUnawareBucketITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/TagActionITCase.java

We follow the behavior of [iceberg procedures](https://iceberg.apache.org/docs/1.3.1/spark-procedures/)

[flink] Place all the built-in procedures into sys database

---

.github/workflows/e2e-tests-1.14-jdk11.yml
.github/workflows/e2e-tests-1.14.yml
.github/workflows/e2e-tests-1.15-jdk11.yml
.github/workflows/e2e-tests-1.15.yml
.github/workflows/e2e-tests-1.16-jdk11.yml
.github/workflows/e2e-tests-1.16.yml
.github/workflows/e2e-tests-1.17-jdk11.yml
.github/workflows/e2e-tests-1.17.yml
.github/workflows/flink-cdc-tests-jdk11.yml
.github/workflows/flink-cdc-tests.yml
.github/workflows/unitcase-flink-jdk11.yml
.github/workflows/unitcase-jdk11.yml
.github/workflows/utitcase-flink.yml
.github/workflows/utitcase.yml

Now, test outputs too more logs, it is difficult to find the root exception.

[ci] Separate Build and Test to reduce log output for test

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java

add `SHOW PARTITIONS` for paimon
org.apache.paimon.flink.CatalogTableITCase#testShowPartitions

[flink] add `SHOW PARTITIONS` for paimon

---

paimon-core/src/main/java/org/apache/paimon/operation/PartitionExpire.java
paimon-core/src/main/java/org/apache/paimon/partition/PartitionTimeExtractor.java
paimon-core/src/test/java/org/apache/paimon/operation/PartitionExpireTest.java

ignore illegal partition for expire parition action
PartitionExpireTest#testIllegalPartition

ignore parition expire exception

---

docs/content/engines/flink.md
docs/content/engines/overview.md
docs/content/project/download.md
paimon-flink/paimon-flink-1.18/pom.xml
paimon-flink/paimon-flink-common/pom.xml

[flink] Update Flink to 1.18.0

---

pom.xml

[hotfix] Fix conflict between scalatest-maven-plugin with maven 3.2.5

---

paimon-core/src/main/java/org/apache/paimon/mergetree/MergeSorter.java
paimon-core/src/main/java/org/apache/paimon/sort/BinaryExternalSortBuffer.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalIndexAssigner.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/SortOperator.java

[core] Refactor code to introduce BinaryExternalSortBuffer.create

---

paimon-common/src/main/java/org/apache/paimon/utils/KeyValueIterator.java
paimon-common/src/main/java/org/apache/paimon/utils/ListDelimitedSerializer.java
paimon-common/src/main/java/org/apache/paimon/utils/ProjectToRowFunction.java
paimon-core/pom.xml
paimon-core/src/main/java/org/apache/paimon/crosspartition/GlobalIndexAssigner.java
paimon-core/src/main/java/org/apache/paimon/crosspartition/IndexBootstrap.java
paimon-core/src/main/java/org/apache/paimon/crosspartition/KeyPartPartitionKeyExtractor.java
paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBListState.java
paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBOptions.java
paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBSetState.java
paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBState.java
paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBStateFactory.java
paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBValueState.java
paimon-core/src/test/java/org/apache/paimon/crosspartition/GlobalIndexAssignerTest.java
paimon-core/src/test/java/org/apache/paimon/crosspartition/IndexBootstrapTest.java
paimon-docs/src/main/java/org/apache/paimon/docs/configuration/ConfigOptionsDocGenerator.java
paimon-flink/paimon-flink-common/pom.xml
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/NoPrimaryKeyLookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PrimaryKeyLookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/SecondaryIndexLookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalDynamicBucketSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalIndexAssignerOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/IndexBootstrapOperator.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/FileStoreLookupFunctionTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/LookupTableTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/RocksDBListStateTest.java

These codes should be reused by paimon-spark.

[core] Move codes of cross partition to paimon-core

---

paimon-core/src/main/java/org/apache/paimon/manifest/WrappedManifestCommittable.java
paimon-core/src/main/java/org/apache/paimon/table/sink/TableCommitImpl.java
paimon-core/src/main/java/org/apache/paimon/tag/TagAutoCreation.java
paimon-core/src/main/java/org/apache/paimon/tag/TagTimeExtractor.java
paimon-core/src/test/java/org/apache/paimon/manifest/WrappedManifestCommittableTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/Committer.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCommitter.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreMultiCommitter.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/WrappedManifestCommittableSerializer.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTestBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/StoreMultiCommitterTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/WrappedManifestCommittableSerializerTest.java

[core] Force creating snapshot for tag with auto process time creation

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java

[core] Add validation for sequence group during create table

---

paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java

[core] Fix the conflict exception may exceed akka frame size

---

docs/content/how-to/querying-tables.md

supplement Hive query examples。

[doc]Supplement Hive query examples

---

paimon-core/src/test/java/org/apache/paimon/table/IncrementalTimeStampTableTest.java

[hotfix] Clean IncrementalTimeStampTableTest

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeFunction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java

[Bug] fix the sequence field missing when projection pushed down

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/kafka/KafkaLogStoreRegister.java

[flink] Add kafka options to register

---

paimon-common/src/main/java/org/apache/paimon/lineage/LineageMetaFactory.java
paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/table/system/SourceTableLineageTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/SystemTableLoader.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkLineageITCase.java
paimon-flink/paimon-flink-common/src/test/resources/META-INF/services/org.apache.paimon.factories.Factory

Linked issue: close #2197 
This pr aims to add system table `SourceTableLineageTable` and users can query for source table linage by sql, for example:
SELECT * FROM sys.source_table_lineage;
1. Added source table lineage in test `FlinkLineageITCase#testTableLineage`
no
no

[lineage] Add system source table lineage meta table

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/kafka/KafkaLogStoreRegister.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/kafka/KafkaLogStoreRegisterITCase.java

Linked issue: close #2225 2225
Add exception stack information for log store register to position issues.
Added test `KafkaLogStoreRegisterITCase#testRegisterTopicException`
no
no

[flink] Add exception stack for log store register

---

.github/workflows/e2e-tests-1.17-jdk11.yml
.github/workflows/e2e-tests-1.18-jdk11.yml
.github/workflows/e2e-tests-1.18.yml
paimon-e2e-tests/pom.xml
paimon-e2e-tests/src/test/java/org/apache/paimon/tests/E2eTestBase.java
paimon-e2e-tests/src/test/java/org/apache/paimon/tests/FlinkProceduresE2eTest.java
paimon-e2e-tests/src/test/resources-filtered/docker-compose.yaml
paimon-hive/paimon-hive-connector-2.3/src/test/java/org/apache/paimon/hive/Hive23CatalogITCase.java
paimon-hive/paimon-hive-connector-3.1/src/test/java/org/apache/paimon/hive/Hive31CatalogITCase.java
pom.xml

[e2e] Add e2e for flink 1.18

---

paimon-core/src/main/java/org/apache/paimon/table/system/SinkTableLineageTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/SystemTableLoader.java
paimon-core/src/main/java/org/apache/paimon/table/system/TableLineageTable.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkLineageITCase.java

Linked issue: close #2199 
Add system sink table lineage table
Added test in `FlinkLineageITCase#testTableLineage`
no
no

[lineage] Add system sink table lineage meta table

---

paimon-hive/paimon-hive-catalog/pom.xml
paimon-hive/paimon-hive-connector-2.3/pom.xml
paimon-hive/paimon-hive-connector-3.1/pom.xml
paimon-hive/paimon-hive-connector-common/pom.xml

Tests in IDEA cannot deal shade.

[hive] Exclude conflict jars

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunctionBase.java

Improve exception message showing

[cdc] Improve exception message

---

paimon-core/src/main/java/org/apache/paimon/tag/TagAutoCreation.java
paimon-core/src/main/java/org/apache/paimon/tag/TagPeriodHandler.java
paimon-core/src/test/java/org/apache/paimon/tag/TagAutoCreationTest.java

Fix modify tag period exception.

[core]Fix modify tag period exception

---

paimon-format/src/main/java/org/apache/paimon/format/orc/writer/OrcBulkWriter.java

Linked issue: close #2278 
[format] remove the code that uses reflection to obtain the estimated memory size of the orc writer.
The existing `org.apache.paimon.io.RollingFileWriterTest` can cover this change.
No
No

[format] remove the code that uses reflection to obtain the estimated memory size of the orc writer.

---

.asf.yaml

[hotfix] Added github label.

---

paimon-core/src/main/java/org/apache/paimon/schema/TableSchema.java
paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyTableUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/LocalMergeOperator.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FirstRowITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java

[Bug] fix first_row can not work with local merge operator

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/MessageQueueSyncTableActionBase.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseAction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseAction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableAction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ActionBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/SortCompactAction.java

Some action cannot use custom job name. This PR fix it.

[flink] Flink actions support custom job name

---

paimon-core/src/main/java/org/apache/paimon/AppendOnlyFileStore.java
paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java
paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyCompactManager.java
paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyCompactionTask.java
paimon-core/src/main/java/org/apache/paimon/compact/CompactTask.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactManager.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactTask.java
paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/operation/MemoryFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/operation/metrics/CompactionMetrics.java
paimon-core/src/main/java/org/apache/paimon/operation/metrics/CompactionStats.java
paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/sink/TableWrite.java
paimon-core/src/main/java/org/apache/paimon/table/sink/TableWriteImpl.java
paimon-core/src/test/java/org/apache/paimon/TestFileStore.java
paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyCompactManagerTest.java
paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java
paimon-core/src/test/java/org/apache/paimon/append/FullCompactTaskTest.java
paimon-core/src/test/java/org/apache/paimon/format/FileFormatSuffixTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTestBase.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/MergeTreeCompactManagerTest.java
paimon-core/src/test/java/org/apache/paimon/operation/metrics/CompactionMetricsTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/TestChangelogDataReadWrite.java

[core] Support compaction metrics

---

docs/content/how-to/writing-tables.md

[doc] Document flink TRUNCATE TABLE syntax

---

paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java

Close  rewriter anyway no mater what to avoid connection leak.

[bug] close write anyway to avoid connection leak

---

paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/DataTableSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/DynamicPartitionFilteringInfo.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkSourceBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkTableSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/StaticFileStoreSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/StaticFileStoreSplitEnumerator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/SystemTableSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/assigners/DynamicPartitionPruningAssigner.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/table/RichTableSource.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumeratorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FairAssignModeTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FileSplitEnumeratorTestBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/PreemptiveAssignModeTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/StaticFileStoreSplitEnumeratorTestBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/align/AlignedContinuousFileSplitEnumeratorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/statistics/FileStoreTableStatisticsTestBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/statistics/PrimaryKeyTableStatisticsTest.java

To support DPP of batch query.
`StaticFileStoreSplitEnumeratorTestBase`
`BatchFileStoreITCase`
`ContinuousFileStoreITCase`

[flink] Support flink dynamic partition pruning

---

paimon-e2e-tests/src/test/java/org/apache/paimon/tests/E2eTestBase.java

Try to fix the frequently occurred "container is not running" error.

[e2e] Fix unstable e2e tests with Kafka service

---

docs/layouts/shortcodes/generated/core_configuration.html
docs/layouts/shortcodes/generated/flink_catalog_configuration.html
docs/layouts/shortcodes/generated/flink_connector_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalogOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java

Log related options are very confused for users.
We can put them all in a separate page if we have a good page for log system.

[core] Remove log system options documentation

---

paimon-common/src/main/java/org/apache/paimon/reader/RecordReaderIterator.java

Linked issue: close #2231 
[common] fix the problem that RecordReader may not be closed in asynchronous compact thread. 
Since `RecordReader#readBatch` is affected by `interrupt`, `currentIterator#releaseBatch` may be executed twice, resulting in the `RecordReader` possibly not being closed. 
#2285 mainly fixes the problem that the `Writer` is not closed, and the `Reader` also needs to be closed.
No
No
No

 [common] fix the problem that RecordReader may not be closed in asynchronous compact thread.

---

paimon-common/src/main/java/org/apache/paimon/options/OptionsUtils.java
paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/kafka/KafkaLogStoreFactory.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/utils/HiveUtils.java

Linked issue: close #2229 
Add convert properties with prefix key in OptionsUtils
This feature is covered by existing tests
no
no

[core] Add convert properties with prefix key in OptionsUtils

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/FlinkCatalogPropertiesUtil.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java

[Bug] Fix alter table column do not work for the non-physical column

---

docs/content/how-to/altering-tables.md
paimon-common/src/main/java/org/apache/paimon/utils/TypeUtils.java
paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/table/source/InnerTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/InnerTableScanImpl.java
paimon-core/src/main/java/org/apache/paimon/table/source/ReadBuilder.java
paimon-core/src/main/java/org/apache/paimon/table/source/ReadBuilderImpl.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReader.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java

add `drop partition`  for flink sql 
org.apache.paimon.flink.CatalogTableITCase#testDropPartition

[flink] add `drop partition`  for flink sql

---

paimon-e2e-tests/src/test/java/org/apache/paimon/tests/E2eTestBase.java
paimon-e2e-tests/src/test/java/org/apache/paimon/tests/FlinkActionsE2eTest.java
paimon-e2e-tests/src/test/java/org/apache/paimon/tests/FlinkActionsE2eTestBase.java
paimon-e2e-tests/src/test/java/org/apache/paimon/tests/FlinkActionsWithKafkaE2eTest.java

Fix https://github.com/apache/incubator-paimon/actions/runs/6862065679/job/18659032196#step:5:183

[hotfix] Fix FlinkActionsE2eTest testDropPartition timeout

---

paimon-spark/paimon-spark-3.3/pom.xml
paimon-spark/paimon-spark-3.3/src/test/resources/log4j2-test.properties
paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala
paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/InsertOverwriteTest.scala
paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/ProcedureTest.scala
paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/WithTableOptions.scala
paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/spark/paimon/Utils.scala
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/analysis/NoSuchProcedureException.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/PaimonDynamicPartitionOverwriteCommand.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/ProcedureTest.scala

Fix compatibility with spark3.3
Copy InsertOverwriteTest and ProcedureTest to paimon-spark-3.3

[spark] Fix compatibility with spark3.3

---

docs/content/concepts/primary-key-table.md

[hotfix] Fix syntax error in primary-key-table doc

---

docs/content/how-to/querying-tables.md
docs/content/how-to/writing-tables.md
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/TableValuedFunctionsTest.scala

[doc] Remove unnecessary spark catalog configuration

---

docs/content/cdc-ingestion/overview.md

[doc] Document setting custom synchronization job name

---

paimon-flink/paimon-flink-cdc/pom.xml
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunctionBase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunctionBaseTest.java

Linked issue: (https://github.com/apache/incubator-paimon/issues/2128)

[Paimon-2128][CDC]Add more checker for the decimal type.

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/MessageQueueSchemaUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/MessageQueueSyncTableActionBase.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncTableActionBase.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableAction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableAction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarSyncTableAction.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java

Refactor CDC table synchronization action by extracting common parts.

[cdc] Refactor CDC table synchronization action by extracting common parts.

---

paimon-common/src/main/java/org/apache/paimon/utils/DateTimeUtils.java
paimon-common/src/test/java/org/apache/paimon/data/BinaryRowTest.java
paimon-common/src/test/java/org/apache/paimon/utils/DateTimeUtilsTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java
paimon-format/src/main/java/org/apache/paimon/format/orc/reader/OrcTimestampColumnVector.java

[orc] Optimize ORC timestamp type read

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/MergeIntoPaimonTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/extensions/PaimonSparkSessionExtensions.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/Utils.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/analysis/AnalysisHelper.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/analysis/PaimonAnalysis.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/analysis/PaimonMergeInto.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/analysis/PaimonMergeIntoResolver.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/analysis/expressions/ExpressionHelper.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTest.scala

Supports MERGE INTO syntax
Linked issue: https://github.com/apache/incubator-paimon/issues/1583

[spark] Support MERGE INTO command

---

docs/content/engines/spark3.md

[spark][docs] doc for spark schema evolution

---

paimon-format/pom.xml
paimon-format/src/main/resources/META-INF/NOTICE

Parquet-avro is never used in this repo.
Linked issue: close #2138

[Build] Remove unused dep Parquet-avro.

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java

[hotfix] Improve partial-update retract exception

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncTableActionBase.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableAction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableAction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarSyncTableAction.java

Linked issue: close https://github.com/apache/incubator-paimon/issues/2341

[flink]Change the return value of buildSource in SyncTableActionBase

---

paimon-format/pom.xml
paimon-format/src/main/resources/META-INF/NOTICE

[Build] Bump Parquet version to 1.13.1.

---

paimon-core/src/main/java/org/apache/paimon/table/source/AbstractInnerTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/InnerTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/metrics/FlinkMetricGroup.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileStoreSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/LogHybridSourceFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/StaticFileStoreSource.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FileStoreSourceMetricsTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/utils/MetricUtils.java

Linked issue: subtask of #2240 
Tests:
FileStoreSourceMetricsTest#staticFileStoreSourceScanMetricsTest
FileStoreSourceMetricsTest#continuousFileStoreSourceScanMetricsTest
FileStoreSourceMetricsTest#logHybridFileStoreSourceScanMetricsTest

[Flink] Register scan metrics to flink metric groups

---

docs/content/concepts/primary-key-table.md
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregator.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldFirstNotNullValueAgg.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregatorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java

[core] Add support of first_not_null value

---

paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBStateFactory.java

[core] Improve RocksDBStateFactory bulkLoad exception

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/UpdatePaimonTableCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/analysis/AssignmentAlignmentHelper.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/analysis/PaimonMergeInto.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/analysis/expressions/ExpressionHelper.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTest.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/UpdateTableTest.scala

Merge into support update nested column

[spark] Merge into support update nested column

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/analysis/PaimonAnalysis.scala
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkWriteITCase.java

[Spark] Truncate Partition

---

paimon-common/src/main/java/org/apache/paimon/fs/Path.java
paimon-common/src/main/java/org/apache/paimon/fs/local/LocalFileIO.java
paimon-core/src/main/java/org/apache/paimon/catalog/CatalogUtils.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/test/java/org/apache/paimon/format/FileFormatSuffixTest.java
paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java
paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
paimon-core/src/test/java/org/apache/paimon/table/SchemaEvolutionTest.java
paimon-core/src/test/java/org/apache/paimon/table/source/StartupModeTest.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/CdcMultiplexRecordChannelComputerTest.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperatorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/StoreMultiCommitterTest.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/mapred/PaimonOutputCommitter.java
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/PaimonSinkTest.scala
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/CreateAndDeleteTagProcedureTest.scala
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/RollbackProcedureTest.scala
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonCDCSourceTest.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSinkTest.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSourceTest.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CompactProcedureTest.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CreateAndDeleteTagProcedureTest.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/RollbackProcedureTest.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DataFrameWriteTest.scala

"oss://bucket/tmp/1" => Path.getPath => "/tmp/1".
It is dangerous to use this method, we should remove it for avoiding bugs.

[core] Remove Path.getPath

---

.github/workflows/check-licensing.yml
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/GlobalDynamicBucketTableITCase.java

[flink] [test] Fix unstable test of GlobalDynamicBucketTableITCase

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/WriteIntoPaimonTable.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DynamicBucketTableTest.scala

[spark] Fix dynamicBucketAssignerParallelism conf

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileStoreSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedContinuousFileSplitEnumerator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedContinuousFileStoreSource.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumeratorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/align/AlignedContinuousFileSplitEnumeratorTest.java

close: https://github.com/apache/incubator-paimon/issues/2370 
Added test.
No other influence to user

[flink] Limit max split while continuously scanning to avoid JobManager OOM

---

docs/content/maintenance/metrics.md

[doc] Paimon metrics doc

---

docs/content/engines/presto.md

Update presto connector docs

---

paimon-core/src/main/java/org/apache/paimon/migrate/FileMetaUtils.java

[core] Add log for migrate procedure

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkReaderFactory.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkScan.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBatch.scala

[spark] override equals as a preparative step for performance optimization

---

docs/content/concepts/primary-key-table.md
paimon-common/src/main/java/org/apache/paimon/utils/InternalRowUtils.java
paimon-common/src/test/java/org/apache/paimon/utils/InternalRowUtilsTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java

[core] support to compare varchar/char type

---

paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaDebeziumSyncTableActionITCase.java

Dbz format completes the test case

[flink] Fix dbz format  the test case

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java

[doc] Update file.compression description

---

paimon-e2e-tests/pom.xml
paimon-flink/paimon-flink-1.16/pom.xml
paimon-flink/paimon-flink-1.17/pom.xml
paimon-flink/paimon-flink-cdc/pom.xml

Flink 1.17.2 Release Notes: https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12315522&version=12353260
Flink 1.16.3 Release Notes: https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12315522&version=12353259

[flink] Bump flink 1.17.1 to 1.17.2 and flink 1.16.2 to 1.16.3

---

docs/content/maintenance/understand-files.md
paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/FileStore.java
paimon-core/src/main/java/org/apache/paimon/Snapshot.java
paimon-core/src/main/java/org/apache/paimon/index/IndexFileHandler.java
paimon-core/src/main/java/org/apache/paimon/io/DataFilePathFactory.java
paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java
paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
paimon-core/src/test/java/org/apache/paimon/operation/OrphanFilesCleanTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RemoveOrphanFilesAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RemoveOrphanFilesProcedure.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionITCase.java

Linked issue: close #1571 
Fix #2222
`OrphanFilesCleanTest`
`RemoveOrphanFilesActionITCase`
Understand Files - Remove Orphan Files

[core][flink] Introduce orphan files clean and corresponding flink action

---

docs/content/migration/migration-from-hive.md
paimon-spark/paimon-spark-common/pom.xml
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/catalog/SparkBaseCatalog.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/catalog/WithPaimonCatalog.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/BaseProcedure.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/MigrateFileProcedure.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/MigrateTableProcedure.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/utils/TableMigrationUtils.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonHiveTestBase.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/MigrateFileProcedureTest.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/MigrateTableProcedureTest.scala

[spark] Support call migrate procedure

---

docs/content/maintenance/understand-files.md
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedure.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedureTest.scala

[spark] Add remove orphan files procedure

---

docs/content/migration/migration-from-hive.md
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MigrateTableActionFactory.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/MigrateFileProcedure.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/MigrateTableProcedure.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/MigrateFileProcedureTest.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/MigrateTableProcedureTest.scala

Change the action and procedure name of migration

[fix] fix migration action and procedure name

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarSyncDatabaseActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarSyncTableActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactDatabaseActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CreateTagActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DeleteActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DeleteTagActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DropPartitionActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MergeIntoActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MigrateTableActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ResetConsumerActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RollbackToActionFactory.java

[flink] All argument keys in help messages of action factory use underline instead of hyphen

---

docs/content/cdc-ingestion/kafka-cdc.md
docs/content/cdc-ingestion/mongo-cdc.md
docs/content/cdc-ingestion/mysql-cdc.md
docs/content/cdc-ingestion/overview.md
docs/content/cdc-ingestion/pulsar-cdc.md
docs/content/how-to/altering-tables.md
docs/content/how-to/querying-tables.md
docs/content/how-to/writing-tables.md
docs/content/maintenance/dedicated-compaction.md
docs/content/maintenance/manage-snapshots.md
docs/content/maintenance/manage-tags.md
docs/content/maintenance/understand-files.md
docs/layouts/shortcodes/generated/kafka_sync_database.html
docs/layouts/shortcodes/generated/kafka_sync_table.html
docs/layouts/shortcodes/generated/mongodb_sync_database.html
docs/layouts/shortcodes/generated/mongodb_sync_table.html
docs/layouts/shortcodes/generated/mysql_sync_database.html
docs/layouts/shortcodes/generated/mysql_sync_table.html
docs/layouts/shortcodes/generated/pulsar_sync_database.html
docs/layouts/shortcodes/generated/pulsar_sync_table.html
docs/layouts/shortcodes/generated/sort-compact.html

Fix doc replace all --a-b-c to --a_b_c

[docs] Fix docs change "-" to "_"

---

docs/content/engines/flink.md
docs/content/maintenance/manage-snapshots.md
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/DropPartitionProcedure.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedure.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedureTest.scala

[doc] Document available flink procedures

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkTable.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadITCase.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadTestBase.java

[spark] Show create table display using paimon

---

docs/content/engines/trino.md
docs/content/how-to/querying-tables.md

Linked issue: https://github.com/apache/incubator-paimon-trino/pull/43

[doc]Add doc for Trino time travel query

---

docs/content/maintenance/dedicated-compaction.md
paimon-common/src/main/java/org/apache/paimon/predicate/PredicateBuilder.java
paimon-common/src/main/java/org/apache/paimon/utils/ParameterUtils.java
paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyTableCompactionCoordinator.java
paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyTableCompactionCoordinatorTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/UnawareBucketCompactionTopoBuilder.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/sort/TableSorter.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CompactProcedureTest.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonPushDownTest.scala

[spark] Optimize compact procedure in non-sort scenario

---

docs/content/maintenance/metrics.md

Document paimon write and write buffer metrics.

[doc] Add write and write buffer metrics

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonStatistics.scala

Linked issue: https://github.com/apache/incubator-paimon/issues/2404

[spark] define PaimonStatistics for the following CBO optimization

---

docs/content/api/flink-api.md
docs/layouts/shortcodes/generated/compute_column.html
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/MessageQueueSchemaUtils.java

[hotfix] Fix doc and improve error message

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/DeduplicateMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyTableUtils.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/FullChangelogMergeFunctionWrapperTestBase.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/ReducerMergeFunctionWrapperTestBase.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/SortMergeReaderTestBase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java

[cdc] Support ignore delete records

---

paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonIncompatiblePHRRules.scala
paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonIncompatibleResolutionRules.scala
paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/paimon/spark/catalyst/trees/PaimonLeafLike.scala
paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/paimon/spark/leafnode/package.scala
paimon-spark/paimon-spark-3.1/src/test/java/org/apache/paimon/spark/SparkGenericCatalogTest.java
paimon-spark/paimon-spark-3.2/src/test/java/org/apache/paimon/spark/SparkGenericCatalogTest.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonAnalysis.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonIncompatiblePHRRules.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonIncompatibleResolutionRules.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/plans/logical/PaimonCallCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/MergeIntoPaimonTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonTruncateTableCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/UpdatePaimonTableCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/execution/PaimonCallExec.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/extensions/PaimonSparkSessionExtensions.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/leafnode/package.scala

https://github.com/apache/incubator-paimon/issues/2490

[spark] solve the compatibility with spark 3.1

---

paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseTableListITCase.java
paimon-flink/paimon-flink-cdc/src/test/resources/mysql/tablelist_test_setup.sql

[cdc] Fix unstable MySqlSyncDatabaseTableListITCase

---

.github/workflows/unitcase-jdk11.yml
.github/workflows/utitcase.yml
paimon-flink/pom.xml

[ci] Fix that non-flink tests still run some flink related tests

---

paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/paimon/spark/PaimonScan.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScanBuilder.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScanBuilder.scala

[spark] optimize description of scan

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java

[spark] Fix autoFillConfigurations in SparkGenericCatalog

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java

[spark] Auto modify conf for Aliyun EMR DLF in SparkGenericCatalog

---

paimon-common/src/main/java/org/apache/paimon/security/SecurityContext.java

Trino uses SecurityContext, but due to the complexity of the environment, the loaded configuration files are often incorrect. Therefore, we should support using user-supplied configuration.

[core]Support create SecurityContext by CatalogContext

---

paimon-flink/paimon-flink-common/pom.xml
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/DataCatalogTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/FlinkCatalogPropertiesUtil.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ReadWriteTableITCase.java

[core] support to show comments for non-physical columns

---

paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkITCase.java

[test] add time for cdc tests

---

docs/content/cdc-ingestion/pulsar-cdc.md
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarActionUtils.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarSchemaITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarSyncDatabaseActionITCase.java

Remove unnecessary ConfigOption;
Improve doc

[cdc] Improve pulsar-cdc

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

Reduce the number of accesses to Hive and filesystem for showing tables  when using HiveCatalog

[Flink] remove schemaFileExists check for showing tables  when using HiveCatalog

---

docs/content/engines/trino.md

We need modify Trino doc regarding installation methods after this pr https://github.com/apache/incubator-paimon-trino/pull/50  merged.

[doc]Change to Trino documentation regarding installation

---

docs/content/cdc-ingestion/pulsar-cdc.md
docs/layouts/shortcodes/generated/kafka_sync_database.html
docs/layouts/shortcodes/generated/kafka_sync_table.html
docs/layouts/shortcodes/generated/pulsar_sync_database.html
docs/layouts/shortcodes/generated/pulsar_sync_table.html
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/CdcActionCommonUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncJobHandler.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarActionUtils.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaMaxwellSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaOggSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarSyncDatabaseActionITCase.java

[cdc] Support 'topic-pattern' for kafka and pulsar cdc

---

paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/AppendOnlyFileStore.java
paimon-core/src/main/java/org/apache/paimon/FileStore.java
paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/FileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/sink/CallbackUtils.java
paimon-core/src/main/java/org/apache/paimon/tag/TagAutoCreation.java
paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
paimon-core/src/test/java/org/apache/paimon/TestFileStore.java
paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java
paimon-core/src/test/java/org/apache/paimon/operation/UncleanedFileStoreExpireTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AutoTagForSavepointCommitterOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/BatchWriteGeneratorTagOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/AutoTagForSavepointCommitterOperatorTest.java

Let TagManager#createTag to handle callbacks.

[core] Fix that some tag creations haven't handle tag callbacks

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java

[Bug] Support modify non physical column comment

---

docs/content/engines/spark.md
paimon-spark/paimon-spark-common/pom.xml
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/sort/HilbertSorter.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/sort/SparkHilbertUDF.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/sort/TableSorter.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/utils/ConvertBinaryUtil.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/ConvertBinaryUtilTest.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CompactProcedureTest.scala

**Support hilbert curve sort action**
Relying on this repository：https://github.com/davidmoten/hilbert-curve. It is Apache-2.0 and is compatible with the incubator-paimon project licensing.
Linked issue: (https://github.com/apache/incubator-paimon/issues/1412)
no

[spark] Support hilbert curve sort action in spark

---

paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetSchemaConverter.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/objectinspector/PaimonObjectInspectorFactory.java

[BugFix]Fix timestamp type write parquet file not have logicaltype

---

docs/content/concepts/primary-key-table.md

Aggregation model function document optimization.

[doc] Aggregation model function document optimization

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregator.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldCountAgg.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregatorTest.java

The agg table model supports count types.

[core] The agg table model supports count types

---

docs/content/concepts/primary-key-table.md
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregator.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldProductAgg.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregatorTest.java

Support product function for agg table

[Core]Support product function for agg table

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarActionUtils.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarSyncTableActionITCase.java

[cdc] Support topic-pattern in kafka/pulsar table synchronization

---

docs/content/concepts/primary-key-table.md
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/AggregateMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregator.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldNestedUpdateAgg.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregatorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java

[core] Introduce nested-update agg to support aggregate nested table

---

docs/content/concepts/primary-key-table.md

Doc agg table function description unified format.

[doc] Doc agg table function description unified format

---

docs/content/concepts/primary-key-table.md
paimon-common/src/main/java/org/apache/paimon/options/ConfigOption.java
paimon-common/src/main/java/org/apache/paimon/options/ConfigOptions.java
paimon-common/src/main/java/org/apache/paimon/options/Options.java
paimon-common/src/main/java/org/apache/paimon/options/OptionsUtils.java
paimon-docs/src/main/java/org/apache/paimon/docs/configuration/ConfigOptionsDocGenerator.java
paimon-docs/src/test/java/org/apache/paimon/docs/configuration/ConfigOptionsDocGeneratorTest.java

Never used, and we use "," instead of ";"

[core] Remove ConfigOptions toList

---

paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java

[hotfix] Improve empty dirs clean test in FileDeletionTest

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregator.java

ignoreRetract has been handled twice.

[core] Minor improve FieldAggregator#createFieldNestedUpdateAgg

---

docs/content/concepts/primary-key-table.md
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregator.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldCollectAgg.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregatorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java

Collect agg collects elements into an Array.

[core] Introduce collect agg

---

docs/content/concepts/primary-key-table.md
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregator.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldMergeMapAgg.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregatorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java

[core] Introduce merge_map agg

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java

[core] Introduce product IT case

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/table/system/AllTableOptionsTable.java
paimon-core/src/test/java/org/apache/paimon/table/system/AllTableOptionsTableTest.java

Append all options system table ut.

[core]Append all options system table ut

---

paimon-core/src/test/java/org/apache/paimon/table/system/ConsumersTableTest.java

Append consumers system table ut.

[core]Append consumers system table ut

---

paimon-spark/paimon-spark-3.2/pom.xml

[hotfix] Fix paimon-spark-3.2 pom (duplicate dependency)

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/strategy/MongoVersionStrategy.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/resources/mongodb/table/defaultid/defaultId-2.js

Fix the problem of mongo primary key field.

[flink]Fix the problem of mongo primary key field

---

NOTICE

[Doc] Add 2024 on NOTICE

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java

Improve hive database is exists yet create/drop database.

[hive] Improve hive database is exists yet create/drop database

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CompactorSinkITCase.java

Fix unstable test of parallelism check. Parallelism should be greater than 1.

[test] Fix unstable test of parallelism set error.

---

paimon-core/src/test/java/org/apache/paimon/table/system/TagsTableTest.java

[core]Append tags system table ut

---

paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/mapred/PaimonRecordReader.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveReadITCase.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveWriteITCase.java

[hive] Compatible with upper and lower case when use hivesql queries paimon external table

---

paimon-core/src/test/java/org/apache/paimon/table/system/OptionsTableTest.java

Append options system table ut.

[core] Append options system table ut

---

paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaDebeziumSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaDebeziumWithSchemaSyncTableActionITCase.java

[flink-cdc]correct writing errors(change canal to debezium)

---

paimon-common/src/main/java/org/apache/paimon/types/RowType.java
paimon-common/src/main/java/org/apache/paimon/utils/FunctionWithIOException.java
paimon-core/src/main/java/org/apache/paimon/crosspartition/IndexBootstrap.java
paimon-core/src/main/java/org/apache/paimon/io/SplitsParallelReadUtil.java
paimon-core/src/main/java/org/apache/paimon/table/source/KeyValueTableRead.java
paimon-core/src/main/java/org/apache/paimon/utils/PartialRow.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/NoPrimaryKeyLookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PrimaryKeyLookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/SecondaryIndexLookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/TableStreamingReader.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/LookupTableTest.java

[flink] Fix inconsistency problem when lookup join table with sequence field

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/RecordParser.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/canal/CanalRecordParser.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaDebeziumWithSchemaSyncTableActionITCase.java

[cdc] Minor improve RecordParser

---

paimon-core/src/main/java/org/apache/paimon/table/system/PartitionsTable.java
paimon-core/src/test/java/org/apache/paimon/table/system/PartitionsTableTest.java

[core] Add partition modify timestamp to partition system table

---

paimon-core/src/main/java/org/apache/paimon/manifest/IndexManifestFile.java

Remove dead code, here should never come in.

[core] Don't delete file out of Snapshot expire

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreWriteOperator.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcSinkBuilder.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcUnawareBucketSink.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcUnawareBucketWriteOperator.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncTableSinkITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/TestTable.java

[cdc] Minor improve CdcUnawareBucketSink and fix unstable test

---

paimon-core/src/main/java/org/apache/paimon/utils/JsonSerdeUtil.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SynchronizationActionBase.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/watermark/CdcTimestampExtractorFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/watermark/CdcWatermarkStrategy.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaDebeziumSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaMaxwellSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaOggSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/resources/kafka/canal/table/watermark/canal-data-1.txt
paimon-flink/paimon-flink-cdc/src/test/resources/kafka/debezium/table/watermark/debezium-data-1.txt
paimon-flink/paimon-flink-cdc/src/test/resources/kafka/maxwell/table/watermark/maxwell-data-1.txt
paimon-flink/paimon-flink-cdc/src/test/resources/kafka/ogg/table/watermark/ogg-data-1.txt

Cdc ingestion support warkmark strategy.

[flink] Cdc ingestion support warkmark strategy

---

docs/content/engines/spark.md
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonCDCSourceTest.scala

Update spark streaming read change log doc

[doc] Update spark streaming read change log

---

docs/content/engines/hive.md

[hive] add docs for hive engine

---

paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/mapred/PaimonInputFormat.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/mapred/PaimonRecordReader.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/utils/HiveSplitGenerator.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/utils/HiveSplitUtils.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/utils/HiveUtils.java

Just refactoring code to make logic more clear and make `PaimonInputFormat` clean.

[hive] Refactor `PaimonInputFormat` to simplify and make logic more clear.
