paimon-core/src/main/java/org/apache/paimon/operation/FileStoreExpireImpl.java, paimon-core/src/test/java/org/apache/paimon/operation/FileStoreExpireTestBase.java
When there are very old consumers, we should quickly exit the loop of snapshot elimination. Otherwise, the performance is very poor.
=> [core] Optimize snapshot expire loop for consumers

paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeInto.scala, paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeIntoResolver.scala, paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeInto.scala, paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeIntoResolver.scala, paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeInto.scala, paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeIntoResolver.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeIntoBase.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeIntoResolverBase.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/MergeIntoPaimonTable.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTest.scala
=> [Spark] Merge Into: When Not Matched By Source

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
We should build the schema after we do the monitor table check
Otherwise, if there are thousands of tables but we only want to synchronize a few of them, it will build thousands of schemas, which is useless and affects performance, and may even throw exceptions during the process of building schemas
=> [flink] build schema after match in the sync action

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
Linked issue: close #2493 
Currently there will be `FileIO` when a catalog is created. We would like to support path for `database` and paimon need to get fileio for each database when it is created, dropped and tables are created, dropped for it. This PR aims to introduce `DatabaseFileIOProvider` in catalog to get fileio for given database name.
Exist tests can cover this feature.
no
no
=> [schema] Support database path for specified database in catalog

docs/content/maintenance/manage-tags.md, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CreateTagAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CreateTagActionFactory.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CreateTagProcedure.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/TagActionITCase.java, paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/CreateAndDeleteTagProcedureTest.scala, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CreateTagProcedure.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CreateAndDeleteTagProcedureTest.scala
Support the creation of tags based on the latest snapshot.
=> [flink] Support the creation of tags based on the latest snapshot

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java, paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java, paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
Set auto-create = false when using FilesystemCatalog to create table.
Error:
```
Caused by: com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName, com.amazonaws.auth.profile.ProfileCredentialsProvider@610ea73f: profile file cannot be null, com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@180077f2: Failed to connect to service …
```
=> [Catalog]Set auto-create = false when using FilesystemCatalog to create table

docs/layouts/shortcodes/generated/rocksdb_configuration.html, paimon-common/src/main/java/org/apache/paimon/utils/ListDelimitedSerializer.java, paimon-core/src/main/java/org/apache/paimon/crosspartition/GlobalIndexAssigner.java, paimon-core/src/main/java/org/apache/paimon/lookup/BulkLoader.java, paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBListState.java, paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBOptions.java, paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBSetState.java, paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBState.java, paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBStateFactory.java, paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBValueState.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/NoPrimaryKeyLookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PrimaryKeyLookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/SecondaryIndexLookupTable.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/FileStoreLookupFunctionTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/LookupTableTest.java
When initializing, it is necessary to scan the entire table and then write one by one to RocksDB. This process is too time-consuming because RocksDB writes slowly.
We can optimize it to bulkload mode, sort it first before writing it during full initialization.
=> [flink] Optimize Flink Lookup Join: Bulk load for initialization

docs/content/maintenance/metrics.md, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FileStoreSourceReader.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkRecordsWithSplitIds.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/metrics/FileStoreSourceReaderMetrics.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/ReadOperator.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FlinkRecordsWithSplitIdsTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/operator/OperatorSourceTest.java
This PR implemented a new Flink source metrics, which is `currentEmitEventTimeLag`.
* `OperatorSourceTest`.
Also end to end tested by hand.
No.
Yes. Document is also updated.
=> Implement currentEmitEventTimeLag for Flink source

docs/content/how-to/querying-tables.md, docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/consumer/Consumer.java, paimon-core/src/main/java/org/apache/paimon/table/source/AbstractInnerTableScan.java, paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java
Consumer-id:
When previous job is stopped, the newly started job can continue to consume from the previous progress without resuming from the state. The newly reading will start reading from next snapshot id found in consumer files. If you don’t want this behavior, you can set 'consumer.ignore-progress' to true.
=> [core] Introduce consumer.ignore-progress

paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java, paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/SnapshotReaderTest.java
1. Append only table always can convert to raw files
2. Primary key table only max level can convert to raw files, Because other level may contain data with RowKind not INSERT, other engines cannot natively read it.
The main change compared to before is that individual level 0 files can not be convert to raw files
=> [core] Primary key table only max level can convert to raw files

paimon-core/src/main/java/org/apache/paimon/table/TableUtils.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
Table a is a primary key table with lookup changelog-producer
Delete from table a where pk = xxx will cause an error
Fix this problem
=> [flink] Fix delete exception with lookup changelog-producer and pk as delete key(push down to client).

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PrimaryKeyFileStoreTableITCase.java
Flink's `SinkMaterializer` is an undesired feature for Paimon, because it will keep all the keys in operator's state and also filter out delete records, which may cause incorrect result.
This PR throws an exception if there is a `SinkMaterializer` before Paimon sink. Thus the user will not forget to remove `SinkMaterializer`.
* `PartialUpdateITCase#testNoSinkMaterializer`.
No.
No.
=> [flink] Throws exception if there is a SinkMaterializer before Paimon sink

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java
This is because if insert values have `CAST`, it will cause disorder (cannot be solved by setting parallelism to 1); And in this test, the old DECIMAL(4, 2) will truncate result, so the final result will be affected by the order of input.
=> [hotfix] Fix unstable test ProductAggregation#testMergeInMemory caused by disorder and scale

paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousLatestStartingScanner.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkRecordsWithSplitIds.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java
Linked issue: close https://github.com/apache/incubator-paimon/issues/2588
org.apache.paimon.flink.ContinuousFileStoreITCase
=> [core] fix streaming read empty table in latest mode

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
Linked issue: close #2616 
`org.apache.paimon.flink.CatalogTableITCase#testDropPartition`
=> [flink] fix IF EXISTS clause not works when drop table

docs/layouts/shortcodes/generated/flink_connector_configuration.html, paimon-common/src/main/java/org/apache/paimon/utils/ParallelExecution.java, paimon-core/src/main/java/org/apache/paimon/crosspartition/IndexBootstrap.java, paimon-core/src/main/java/org/apache/paimon/io/SplitsParallelReadUtil.java, paimon-core/src/test/java/org/apache/paimon/utils/ParallelExecutionTest.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/TableStreamingReader.java
The current lookup join initialization loading is too slow, so we introduce parallelism execution to accelerate it.
=> [flink] Introduce parallelism execution for lookup join

paimon-core/src/main/java/org/apache/paimon/index/BucketAssigner.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/WriteIntoPaimonTable.scala, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkWriteITCase.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DynamicBucketTableTest.scala
For write dynamic bucket with spark
- support set `dynamic-bucket.initial-buckets`
- only load indexes belonging to the certain bucket
=> [spark] Decoupling of initialBuckets and assignerParallelism for dynamic bucket write

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncJobHandler.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlRecordParser.java
1. port has default value.
2. null value in Json will be parsed into NullNode.
=> [hotfix][cdc] Uncheck 'port' of mysql-conf; Fix record null check

paimon-common/src/main/java/org/apache/paimon/data/serializer/BinaryStringSerializer.java, paimon-common/src/main/java/org/apache/paimon/data/serializer/BooleanSerializer.java, paimon-common/src/main/java/org/apache/paimon/data/serializer/ByteSerializer.java, paimon-common/src/main/java/org/apache/paimon/data/serializer/DecimalSerializer.java, paimon-common/src/main/java/org/apache/paimon/data/serializer/DoubleSerializer.java, paimon-common/src/main/java/org/apache/paimon/data/serializer/FloatSerializer.java, paimon-common/src/main/java/org/apache/paimon/data/serializer/IntSerializer.java, paimon-common/src/main/java/org/apache/paimon/data/serializer/LongSerializer.java, paimon-common/src/main/java/org/apache/paimon/data/serializer/Serializer.java, paimon-common/src/main/java/org/apache/paimon/data/serializer/ShortSerializer.java, paimon-common/src/main/java/org/apache/paimon/data/serializer/TimestampSerializer.java, paimon-common/src/test/java/org/apache/paimon/data/serializer/BinaryStringSerializerTest.java, paimon-common/src/test/java/org/apache/paimon/data/serializer/BooleanSerializerTest.java, paimon-common/src/test/java/org/apache/paimon/data/serializer/ByteSerializerTest.java, paimon-common/src/test/java/org/apache/paimon/data/serializer/DecimalSerializerTest.java, paimon-common/src/test/java/org/apache/paimon/data/serializer/DoubleSerializerTest.java, paimon-common/src/test/java/org/apache/paimon/data/serializer/FloatSerializerTest.java, paimon-common/src/test/java/org/apache/paimon/data/serializer/IntSerializerTest.java, paimon-common/src/test/java/org/apache/paimon/data/serializer/LongSerializerTest.java, paimon-common/src/test/java/org/apache/paimon/data/serializer/SerializerTestBase.java, paimon-common/src/test/java/org/apache/paimon/data/serializer/ShortSerializerTest.java, paimon-common/src/test/java/org/apache/paimon/data/serializer/TimestampSerializerTest.java
Introduce serializeToString and deserializeFromString for internal data structure, support data structures:
BinaryString, Boolean, Byte, Decimal, Double, Float, Int, Long, Shot, Timestamp
=> [core] Introduce serializeToString and deserializeFromString for internal data structure

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
Use sql for schema evolution on CatalogTableITCase.
`testFilesTable` and `testPartitionsTable`
=> [test] Use sql for schema evolution on CatalogTableITCase

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcFixedBucketSink.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcSinkBuilder.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FixedBucketSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowUnawareBucketSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/UnawareBucketSink.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FileStoreITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/FlinkSinkTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/SinkSavepointITCase.java
In addition, #2630 can extend cdc unaware-bucket sink more easy.
=> [flink] Refactor FlinkSink to clarify the relationships between different bucket-mode tables and sinks

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java, paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/operation/MemoryFileStoreWrite.java, paimon-core/src/test/java/org/apache/paimon/operation/AppendOnlyFileStoreWriteTest.java, paimon-core/src/test/java/org/apache/paimon/table/AppendOnlyFileStoreTableTest.java
In batch write to append-only table mode, if the partition-bucket writers number is greater than 5, we forcedly to enable write-buffer-for-append and write-buffer-spillable to avoid out of memory error.
=> [core] If writers size greater than 5, enable buffer and spill for append-only writers in batch mode

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/RecordParser.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaDebeziumWithSchemaSyncTableActionITCase.java, paimon-flink/paimon-flink-cdc/src/test/resources/kafka/debezium/table/schema/schemaevolution/debezium-data-4.txt
fix that kafka cdc action build schema fail from delete record
1.  Try to parse schema from delete record .
2.  Ignore exception to  triger retry if parse schema still failed from delete record .
KafkaDebeziumWithSchemaSyncTableActionITCase#testKafkaBuildSchemaWithDelete
=> [CDC]fix building schema from delete record

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcMultiplexRecordChannelComputer.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperator.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSink.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/CdcMultiplexRecordChannelComputerTest.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperatorTest.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSinkTest.java
1. In the table synchronization action, tableConfig has been copied
https://github.com/apache/incubator-paimon/blob/b84b22562797261e7f77d2268f9c031a66a6c8c9/paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncTableActionBase.java#L121-L154
2. In the database synchronization action, when adding a new table, tableConfig has been copied
https://github.com/apache/incubator-paimon/blob/b84b22562797261e7f77d2268f9c031a66a6c8c9/paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/NewTableSchemaBuilder.java#L44-L61
=> [hotfix] Clear redundant dynamic option copy code in cdc action

paimon-common/src/main/java/org/apache/paimon/options/Options.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionUtils.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
Use the tool class convertToPropertiesPrefixKey to optimize obtaining configuration by specified prefix.
=> [hotfix] Use the tool class convertToPropertiesPrefixKey to optimize obtaining configuration by specified prefix.

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldIgnoreRetractAgg.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java
Currently `FieldIgnoreRetractAgg` forgets to implement the reset method. When using `first_value` aggregate function with `ignore-retract = false`, the aggregated result will be incorrect.
* `PreAggregationITCase.FirstValueAggregation#testAggregatorResetWhenIgnoringRetract`.
No.
No.
=> [core] FieldIgnoreRetractAgg should implement the reset method by calling the wrapped aggregator

paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/SearchArgumentToPredicateConverter.java, paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/utils/HiveUtils.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveReadITCase.java
=> [hive] Fix hive to be compatible with uppercase fields when using predicates to query paimon external tables.

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/StaticFileStoreSplitEnumerator.java
=> [flink] StaticFileStoreSplitEnumerator should ignore ReaderConsumeProgressEvent

paimon-core/src/main/java/org/apache/paimon/table/sink/TableCommitImpl.java, paimon-core/src/test/java/org/apache/paimon/table/sink/TableCommitTest.java
The path of index file is wrong. Here will throw exception. 
This bug is quite serious. For the dynamic bucket mode, long term backpressure is severe, accumulating a lot of checkpoints. Once fails, it is easy to encounter this problem.
=> [core] Fix index file checkFilesExistence in TableCommitImpl

paimon-common/src/main/java/org/apache/paimon/io/cache/CacheManager.java, paimon-common/src/main/java/org/apache/paimon/io/cache/CachedRandomInputView.java, paimon-common/src/main/java/org/apache/paimon/lookup/hash/HashLookupStoreWriter.java
Remove `file.length()` for every cache page.
=> [core] Optimize CacheManager to reduce disk access

pom.xml, tools/releasing/deploy_staging_jars.sh
When I debug my code with the official paimon jar in my IDE , I want to download the paimon jar source , but I found it failed, so I think we should build the source jar and upload to maven repository.
We can add an optional parameter to the profile, and we will generate and upload the source jar in every released, user can skip the operation when compile the code in their computer.
=> [core] generate doc and source jar when compile 

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/kafka/KafkaLogSourceProvider.java
Linked issue: close #2688 
The user-configured `group-id` should be used with higher priority.
No
No
No
=> [cdc] KafkaLogSourceProvider preferentially uses the user-configured group-id.

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/SortOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/SortUtils.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sorter/SortOperatorTest.java
Add validation for parallelism of the SortOperator to avoid potential issues with skewed range partitioning.
=> [flink] Add validation for parallelism of the SortOperator.

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/shuffle/RangeShuffle.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/SortCompactActionForUnawareBucketITCase.java
Run sort compact action in flink job may cause a data skew with lots of hot data.
No influence to user.
=> [flink] Random choose task while sorting to avoid data skew

paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/sql/CompactProcedureTest.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/PaimonSqlExtensionsAstBuilder.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CompactProcedureTestBase.scala
=> [spark] Fix call procedure compatibility with spark3.2

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java, paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java, paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonHiveTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTest.scala
Linked issue: one step of #2619
support  create database with location, comment, props
```sql
CREATE DATABASE db LOCATION 'x' COMMENT 'x' WITH DBPROPERTIES ('k1' = 'v1', 'k2' = 'v2')
```
Note:
- for hive catalog: store all props(location, comment, other props) to hms
- for filesystem catalog: when props is not empty, do nothings but give a warn `Currently filesystem catalog can't store database properties, discard properties: {}`, because filesystem catalog can't store meta.  Besides, because db's location in filesystem catalog is stable, **when create db location 'xxx' with filesystem catalog, an exception is thrown**: `Cannot specify location for a database when using fileSystem catalog`
=> [core][spark] Support create database with location, comment, props using hive catalog

docs/content/maintenance/read-performance.md, docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/UniversalCompaction.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/UniversalCompactionTest.java
Introduce `compaction.optimization-interval`, it is async option for doing full-compaction. Combined with `read-optimized system table`, it can be better used to users.
=> [core] Introduce compaction.optimization-interval

paimon-common/src/main/java/org/apache/paimon/format/FileFormat.java
After this [fix](https://github.com/apache/incubator-paimon/commit/83049b7bd4dd772e8ecef974e42f7ad6f0ad0969), loading the FileFormatFactory class became duplicated in `FileFormat#fromIdentifier`.
=> [Minor] Remove duplicate code from FileFormat#fromIdentifier.

docs/content/concepts/primary-key-table/merge-engine.md, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregator.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldFirstNonNullValueAgg.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregatorTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java
Currently we have two aggregate functions for the `aggregation` merge engine: `last_non_null_value` and `first_not_null_value`. These two names should be unified to prevent users from typo.
This PR renames `first_not_null_value` to `first_non_null_value`. The legacy name is also kept for compatibility.
* `PreAggregationITCase#FirstValueAggregation`.
No.
Yes. Document is also changed.
=> [core] Rename first_not_null_value agg function to first_non_null_value

paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/procedure/CompactProcedureTest.scala, paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/procedure/ProcedureTest.scala, paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/procedure/ProcedureTest.scala, paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/PaimonOptimizationTest.scala, paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/PaimonOptimizationTest.scala, paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/procedure/CompactProcedureTest.scala, paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/procedure/ProcedureTest.scala, paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/sql/PaimonOptimizationTest.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonHiveTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CompactProcedureTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/ProcedureTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTest.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DeleteFromTableTest.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonOptimizationTestBase.scala
- https://github.com/apache/incubator-paimon/pull/2707 make `CompactProcedureTestBase` abstract, and only test at spark3.2, we need add it to spark3.5 too
- other typo (￣▽￣)...
=> [hotfix] Fix spark test typo and missing test

docs/content/how-to/querying-tables.md, docs/content/maintenance/manage-tags.md, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkTimeTravelITCase.java
After #2566, a tag name can be a number, so spark time travel to a number version string may be confused (the version string is a tag or a snapshot ?)
=> [core] Introduce 'scan.version' to refactor spark time travel

paimon-core/src/main/java/org/apache/paimon/sort/zorder/ZIndexer.java, paimon-core/src/test/java/org/apache/paimon/sort/zorder/ZIndexerTest.java
If a column is null, ZIndexer will throws an exception. It shouldn't get the null row:
```sql
-- it is not correct to get the string before check if it is null.
BinaryString binaryString = row.getString(fieldIndex);
return row.isNullAt(fieldIndex)
? NULL_BYTES
: ZOrderByteUtils.byteTruncateOrFill(
MemorySegmentUtils.getBytes(
binaryString.getSegments(),
binaryString.getOffset(),
Math.min(
varTypeSize,
binaryString.getSizeInBytes())),
varTypeSize,
reuse)
.array();
```
=> [core] Fix bug: zindexer should deal well with column `null` value.

docs/content/maintenance/manage-snapshots.md, docs/content/maintenance/manage-tags.md
[doc] Use underscore instead of hyphen for rollback_to in doc.
=> [doc] Use underscore instead of hyphen for rollback_to in doc.

paimon-common/src/main/java/org/apache/paimon/utils/OptionalUtils.java, paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java, paimon-core/src/main/java/org/apache/paimon/FileStore.java, paimon-core/src/main/java/org/apache/paimon/Snapshot.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommit.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java, paimon-core/src/main/java/org/apache/paimon/stats/ColStats.java, paimon-core/src/main/java/org/apache/paimon/stats/Stats.java, paimon-core/src/main/java/org/apache/paimon/stats/StatsFile.java, paimon-core/src/main/java/org/apache/paimon/stats/StatsFileHandler.java, paimon-core/src/main/java/org/apache/paimon/utils/FileStorePathFactory.java, paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java, paimon-core/src/test/java/org/apache/paimon/operation/FileStoreCommitTest.java, paimon-core/src/test/java/org/apache/paimon/stats/StatsFileTest.java, paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java
First step of [PIP-14: Paimon statistics](https://cwiki.apache.org/confluence/display/PAIMON/PIP-14%3A+Paimon+statistics)
snapshot-x
```json
{
"version" : 3,
"id" : 2,
"schemaId" : 3,
"baseManifestList" : "manifest-list-485c5847-cb20-4324-b2ea-fd73959c5857-0",
"deltaManifestList" : "manifest-list-485c5847-cb20-4324-b2ea-fd73959c5857-1",
"changelogManifestList" : null,
"commitUser" : "e30257ac-a617-4571-a57b-60c3dd608754",
"commitIdentifier" : 9223372036854775807,
"commitKind" : "ANALYZE",
"timeMillis" : 1704944283486,
"logOffsets" : { },
"totalRecordCount" : 6,
"deltaRecordCount" : 0,
"changelogRecordCount" : 0,
"watermark" : null,
"statistics" : "stats-87effd5d-48fd-4aab-81fe-4222b847d247-0"
}
```
statistics/stats-87effd5d-48fd-4aab-81fe-4222b847d247-0
```json
{
"snapshotId": 2, …
```
=> [core] Introduce stats in snapshot

docs/content/program-api/java-api.md, paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java, paimon-core/src/test/java/org/apache/paimon/table/SchemaEvolutionTest.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/CdcActionCommonUtils.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkSchemaEvolutionITCase.java
…
The new column exception shows the specific column name in the cdc database synchronization action.
=> [hotfix] The new column exception shows the specific column name in the cdc database synchronization action.

paimon-format/src/main/java/org/apache/paimon/format/orc/reader/OrcSplitReaderUtil.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetSchemaConverter.java
Now, paimon timestamp type lost some metadata
orc file Type meta not contains timestamp with local zone, just timestamp type
parquet file file schema meta not contains adjust to UTC   
=> [format]Fix orc and parquet writer about timestamp not contains [local timezone] and [is_adjust_to_utc]

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java, paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/HiveCatalogTest.java
Fix paimon table comment cannot be synchronized to hive metastore
HiveCatalogTest.testAddHiveTableParameters
assertThat(tableProperties).containsEntry("comment", "this is a hive table");
=> [hive] Fix paimon table comment cannot be synchronized to hive metastore

paimon-flink/paimon-flink-1.18/pom.xml
Apache Flink 1.18.1
https://flink.apache.org/2024/01/19/apache-flink-1.18.1-release-announcement/
=> [flink] Bump flink 1.18.0 to 1.18.1

paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java, paimon-core/src/main/java/org/apache/paimon/table/RollbackHelper.java, paimon-core/src/main/java/org/apache/paimon/table/system/TagsTable.java, paimon-core/src/main/java/org/apache/paimon/tag/TagAutoCreation.java, paimon-core/src/main/java/org/apache/paimon/tag/TagPeriodHandler.java, paimon-core/src/main/java/org/apache/paimon/tag/TagPreview.java, paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java, paimon-core/src/test/java/org/apache/paimon/table/system/TagsTableTest.java, paimon-core/src/test/java/org/apache/paimon/tag/TagAutoCreationTest.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/BatchWriteGeneratorTagOperator.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/AutoTagForSavepointCommitterOperatorTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/BatchWriteGeneratorTagOperatorTest.java
=> [core] Fix that TagManager doesn't handle case where more than 1 tags are created based on the same snapshot

paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommit.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java, paimon-core/src/main/java/org/apache/paimon/stats/ColStats.java, paimon-core/src/main/java/org/apache/paimon/stats/Statistics.java, paimon-core/src/main/java/org/apache/paimon/stats/StatsFile.java, paimon-core/src/main/java/org/apache/paimon/stats/StatsFileHandler.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/ReadonlyTable.java, paimon-core/src/main/java/org/apache/paimon/table/Table.java, paimon-core/src/test/java/org/apache/paimon/operation/FileStoreCommitTest.java, paimon-core/src/test/java/org/apache/paimon/stats/StatsFileTest.java, paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTest.scala, paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTest.scala, paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTest.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonAnalysis.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonAnalyzeTableColumnCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/Utils.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTest.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTestBase.scala
Support:
- ANALYZE TABLE T COMPUTE STATISTICS
- ANALYZE TABLE T COMPUTE STATISTICS FOR COLUMNS
=> [spark] Support ANALYZE table

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/shuffle/RangeShuffle.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/SortCompactActionForUnawareBucketITCase.java
Fix the NullPointException when performing the sort compaction on the empty input.
=> [Bug] fix sort compaction failed on empty input

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-common/src/main/java/org/apache/paimon/io/cache/CacheManager.java, paimon-common/src/main/java/org/apache/paimon/io/cache/CachedRandomInputView.java, paimon-common/src/main/java/org/apache/paimon/lookup/hash/HashLookupStoreFactory.java, paimon-common/src/main/java/org/apache/paimon/lookup/hash/HashLookupStoreReader.java, paimon-common/src/test/java/org/apache/paimon/io/cache/CachedRandomInputViewTest.java, paimon-common/src/test/java/org/apache/paimon/lookup/hash/HashLookupStoreFactoryTest.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/operation/MemoryFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/table/query/LocalTableQuery.java, paimon-core/src/test/java/org/apache/paimon/mergetree/ContainsLevelsTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/LookupLevelsTest.java
- The Cache system should be page independent and can use a custom pageSize.
- Introduce a new Page size for cache, can be smaller.
cache-page-size default 16 KB
=> [core] Let CacheManager page unaware

paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java, paimon-core/src/main/java/org/apache/paimon/operation/FileDeletionBase.java, paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java, paimon-core/src/main/java/org/apache/paimon/operation/SnapshotDeletion.java, paimon-core/src/main/java/org/apache/paimon/operation/TagDeletion.java, paimon-core/src/main/java/org/apache/paimon/stats/StatsFileHandler.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTestBase.scala
=> [core] Add statistics expire and clean

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java, paimon-core/src/main/java/org/apache/paimon/crosspartition/GlobalIndexAssigner.java, paimon-core/src/main/java/org/apache/paimon/migrate/FileMetaUtils.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/FileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/ReadOptimizedTable.java, paimon-core/src/test/java/org/apache/paimon/catalog/PrimaryKeyTableTestBase.java, paimon-core/src/test/java/org/apache/paimon/operation/PartitionExpireTest.java, paimon-core/src/test/java/org/apache/paimon/stats/StatsTableTest.java, paimon-core/src/test/java/org/apache/paimon/table/IndexFileExpireTableTest.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableActionITCase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarSyncTableActionITCase.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DropPartitionAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkTableSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/HashBucketAssignerOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/SupportsRowLevelOperationFlinkTableSink.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/DynamicBucketTableITCase.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/migrate/HiveMigrator.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonPartitionManagement.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CompactProcedureTestBase.scala
This PR makes `AbstractFileStoreTable` a package private class. Developers should use `FileStoreTable` interface instead.
This PR is a refactor without tests.
No.
No.
=> [core] Make AbstractFileStoreTable package private

paimon-core/src/main/java/org/apache/paimon/KeyValue.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ChangelogMergeTreeRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/CompactRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FirstRowMergeTreeCompactRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FullChangelogMergeFunctionWrapper.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FullChangelogMergeTreeCompactRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapper.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeTreeCompactRewriter.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/LookupCompactionTest.scala
Support skip rewrite when upgrade in ChangelogMergeTreeRewriter, e.g.
```sql
CREATE TABLE IF NOT EXISTS T ("a INT, b INT, c STRING, PRIMARY KEY (a) NOT ENFORCED)
WITH ('merge-engine'='deduplicate', 'file.format'='avro', 'changelog-producer' = 'lookup');
INSERT INTO T VALUES (1, 1, '1')
```
before: rewrite a new file, even we just insert one record
```
bucket-0
├── changelog-a17ac0b1-85b8-4086-a79d-bcfb674ef628-1.avro
├── data-a17ac0b1-85b8-4086-a79d-bcfb674ef628-0.avro
└── data-d12c0084-4da4-4f7c-b57b-abecd360a13b-0.avro
```
after: just upgrade, no new file
```
bucket-0
├── changelog-cf80d9df-ed66-464f-a37e-06e14e3811e4-0.avro
└── data-8b9c5336-f96f-4b10-bd55-d1f83c45f982-0.avro
```
=> [core] Support skip rewrite when upgrade in ChangelogMergeTreeRewriter

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ChangelogMergeTreeRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FirstRowMergeTreeCompactRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FullChangelogMergeTreeCompactRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeTreeCompactRewriter.java
Continue https://github.com/apache/incubator-paimon/pull/2751
=> [core] Introduce UpgradeStrategy to simplify logical

docs/layouts/shortcodes/generated/mysql_sync_table.html, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncTableActionFactoryBase.java
=> [cdc] Fix that MySqlSyncTableActionFactory handles METADATA_COLUMN in different way with MySqlSyncDatabaseActionFactory

docs/layouts/shortcodes/generated/postgres_sync_table.html, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncDatabaseActionBase.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/NewTableSchemaBuilder.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/postgres/PostgresSyncTableActionITCase.java
1.the newly added table cannot obtain the metadata column in the database cdc action.
2. resolve pg cdc ut exception.
https://github.com/zhuangchong/flink-table-store/blob/74f6c61bdc7f68a1460d031bbc83e71552b42dc2/paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java#L1318-L1329
```java
// test new added table
statement.execute("USE " + "metadata");
statement.executeUpdate("CREATE TABLE t3 (k INT, v1 VARCHAR(10), PRIMARY KEY (k))");
statement.executeUpdate("INSERT INTO t3 VALUES (1, 'Hi')");
waitingTables("t3");
table = getFileStoreTable("t3");
waitForResult(
Collections.singletonList("+I[1, Hi, t3, metadata]"),
table,
rowType,
Collections.singletonList("k"));
}
```
=> [cdc] the newly added table cannot obtain the metadata column in the database cdc action.

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncJobHandler.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/postgres/PostgresTypeUtils.java
Port is not a required parameter in sync pg table.
=> [CDC]Improve pg sync table cdc

paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/paimon/spark/PaimonScan.scala, paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/paimon/spark/statistics/StatisticsHelper.scala, paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/statistics/StatisticsHelper.scala, paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/paimon/spark/statistics/StatisticsHelper.scala, paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTest.scala, paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTest.scala, paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTest.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScanBuilder.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonStatistics.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/statistics/StatisticsHelper.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/statistics/StatisticsHelperBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTestBase.scala
Integrate statistics into spark scan
Test this on 1T tpc-ds, overall performance improved by 15%, some case:
q19 cost from 175s -> 11s
q64 cost from 84s -> 56s
q72 can't run  ->  32s
=> [spark] Integrate statistics into spark scan

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java, paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/HiveCatalogTest.java
Fix alter paimon table options cannot be synchronized to hive parameters.
org.apache.paimon.hive.HiveCatalogTest.testAlterHiveTableParameters()
=> [hive] alter paimon table options cannot be synchronized to hive par

paimon-core/src/main/java/org/apache/paimon/table/source/AbstractInnerTableScan.java, paimon-core/src/main/java/org/apache/paimon/table/source/InnerTableScan.java, paimon-core/src/main/java/org/apache/paimon/table/source/InnerTableScanImpl.java, paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/FilesTable.java, paimon-core/src/test/java/org/apache/paimon/table/system/FilesTableTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
For large tables, querying the files table is very slow, and we need to support some filter down acceleration queries.
This PR pushdown for three fields:
1. partition
2. bucket
3. level
These three fields related conditions are the most important query conditions.
=> [core] Support filter pushdown in FilesTable

paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/LookupBloomFilterBenchmark.java, paimon-common/src/main/java/org/apache/paimon/lookup/LookupStoreFactory.java, paimon-common/src/main/java/org/apache/paimon/lookup/LookupStoreWriter.java, paimon-common/src/main/java/org/apache/paimon/lookup/hash/HashContext.java, paimon-common/src/main/java/org/apache/paimon/lookup/hash/HashLookupStoreFactory.java, paimon-common/src/main/java/org/apache/paimon/lookup/hash/HashLookupStoreReader.java, paimon-common/src/main/java/org/apache/paimon/lookup/hash/HashLookupStoreWriter.java, paimon-common/src/main/java/org/apache/paimon/utils/BloomFilter.java, paimon-common/src/main/java/org/apache/paimon/utils/FileBasedBloomFilter.java, paimon-common/src/test/java/org/apache/paimon/lookup/hash/HashLookupStoreFactoryTest.java, paimon-core/src/main/java/org/apache/paimon/mergetree/ContainsLevels.java, paimon-core/src/main/java/org/apache/paimon/mergetree/LookupLevels.java
The previous approach made the file structure too complex, which is not conducive to adding file compression in the future.
We can interact solely through memory.
=> [core] Introduce Context for LookupStoreFactory to avoid writing metadata

paimon-benchmark/paimon-micro-benchmarks/pom.xml
Fix the exception when running test in IDE.
=> [Bug] Fix the protobuf conflict in paimon-micro-benchmarks

docs/content/concepts/primary-key-table/merge-engine.md, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldCollectAgg.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldMergeMapAgg.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregatorTest.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkTableSinkBase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java
The retract isn't correct when:
1. If the retract field arrives but accumulator doesn't, won't retract;
2. The retract field from one input stream will retract the result merged from multiple input streams.
for example, using merge_map, acc (1, A) + input (1, B) will get (1, B), and if retract (1, A) later, the result (1, B) will be deleted from result map.
=> [core] Agg 'collect' and 'merge_map' support retract

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactDatabaseAction.java
In divided mode, the dynamic conf isn't applied.
=> [flink] Fix that sink.parallelism doesn't work in compact_database action divided mode

paimon-common/src/main/java/org/apache/paimon/lookup/hash/HashLookupStoreWriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/LookupLevels.java, paimon-core/src/main/java/org/apache/paimon/mergetree/LookupUtils.java, paimon-core/src/main/java/org/apache/paimon/mergetree/SortedRun.java, paimon-core/src/test/java/org/apache/paimon/mergetree/LookupLevelsTest.java
When lookup, we use `DataOutputSerializer` to serialize sequenceNumber by `writeLong`,  which is BigEndian default, so when read, we need use `getLongBigEndian`
=> [core] Fix deserialization of sequenceNumber in lookup

paimon-flink/paimon-flink-cdc/pom.xml, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/debezium/DebeziumSchemaUtils.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlRecordParser.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/postgres/PostgresRecordParser.java
After the MySqlRecordParser.class in paimon-flink-1.18-0.6.0-incubating.jar is decompiled, the string `org.apache.kafka.connect.data.Decimal` is shaded to `org.apache.flink.kafka.shaded .org.apache.kafka.connect.data.Decimal`
After this PR:
MySqlRecordParser.class decompilation:
DebeziumSchemaUtils.class decompilation:
KafkaSinkFunction.class decompilation:
=> [cdc] Fixed constant value of org.apache.kafka prefix being shaded.

paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-common/src/main/java/org/apache/paimon/utils/MathUtils.java
Add a no overflow version of `Math.incrementExact` for int increment sately
Math.java (jdk)
```
public static int incrementExact(int a) {
if (a == Integer.MAX_VALUE) {
throw new ArithmeticException("integer overflow");
}
return a + 1;
}
```
MathUtils.java (paimon)
```
public static int incrementSafely(int a) {
if (a == Integer.MAX_VALUE) {
return a;
}
return a + 1;
}
```
=> [hotfix] Add incrementSafely in MathUtils

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java
The issue of duplicate schema IDs when multiple parallel updates are made to the same table has been resolved.
=> [cdc]Fix duplicate schema IDs when multiple parallel updates

paimon-format/src/main/java/org/apache/paimon/format/orc/writer/RowDataVectorizer.java
Currently `ColumnVector#ensureSize` will resize to the required size each time. The complexity of this implementation is $\mathcal{O}(n^2)$.
Instead, this PR multiplies the array size by $2$ each time. Thus optimizing the complexity to $\mathcal{O}(n\log n)$.
No.
No.
=> [orc] Optimize ensureSize for orc ColumnVector

paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/procedure/ProcedureTest.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/PaimonSparkSqlExtensionsParser.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/PaimonSqlExtensionsAstBuilder.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/ProcedureTestBase.scala
=> [spark] Fix PaimonParseException compatibility with spark3.3-

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedContinuousFileSplitEnumerator.java
Linked issue: close #2881
Also related to https://github.com/apache/incubator-paimon/pull/2762
=> [Bug] Throw exception when failed to enumerator the splits

docs/content/maintenance/manage-tags.md
Modify the wrong parameters of flink action in the document,create-tag should be changed to create_tag and delete-tag should be changed to delete_tag
=> [doc] Modify the wrong parameters of flink action in the document

paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
Currently, we use delete-and-write to overwrite the hint file, it's better to run with the atomic overwrite, so there is no intermediate state for the hint file.
=> [core] Use overwrite instead of delete-and-write when commit hint file

paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java, paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java
This PR optimizes `SnapshotManager#earlierThanTimeMills` with binary search.
No.
No.
=> [core] Use binary search to optimize SnapshotManager#earlierThanTimeMills

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/RetryingMetaStoreClientFactory.java
Some metastore client classes (for example, aliyun DLF) only provides constructor for Hive 2.x (with arguments `HiveConf, HiveMetaHookLoader, Boolean`). However metastore protocols are compatible between Hive 2.x and 3.x so these metastore client classes can also support Hive 3.x, just that Hive 3.x requires the constructor arguments to be `Configuration, HiveMetaHookLoader, Boolean` by default.
This PR explicitly specify constructor arguments in `RetryingMetaStoreClientFactory` to support such scenario.
This PR is tested by hand.
No.
No.
=> [hive] Support HiveCatalog for Hive 3.x and certain metastore client classes with constructors only for 2.x

paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/FileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java, paimon-flink/paimon-flink-common/pom.xml, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FullCacheLookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupStreamingReader.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java
If user passes scan options to dim table through dynamic option, it will cause exception.
This PR fix it by clear the scan options when loading data from dim table.
=> [flink] The dim table in lookup join should ignore scan options

paimon-core/src/main/java/org/apache/paimon/table/source/AbstractInnerTableScan.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java
The consumer id should work for stream mode only, otherwise the result of the batch scan is empty. close #2855
=> [Bug] Ignore the consumer-id in batch job

docs/content/concepts/primary-key-table/sequence-rowkind.md, paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeWriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/sink/SequenceGenerator.java, paimon-core/src/main/java/org/apache/paimon/table/sink/TableWriteImpl.java, paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTestBase.java, paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java, paimon-core/src/test/java/org/apache/paimon/table/sink/SequenceGeneratorTest.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/LocalMergeOperator.java
The system time is very inaccurate and basically useless. We should use self increasing IDs, which will at least have some effect.
=> [core] Sequence Auto padding should based on incremental id

paimon-core/src/main/java/org/apache/paimon/table/source/InnerStreamTableScanImpl.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/AllDeltaFollowUpScanner.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/CompactionChangelogFollowUpScanner.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousAppendAndCompactFollowUpScanner.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/DeltaFollowUpScanner.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/FollowUpScanner.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/InputChangelogFollowUpScanner.java, paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/CompactionChangelogFollowUpScannerTest.java, paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ContinuousAppendAndCompactFollowUpScannerTest.java, paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/DeltaFollowUpScannerTest.java, paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/InputChangelogFollowUpScannerTest.java
Directly pass the Snapshot to reader to avoid read the snapshot file twice
=> [core] Avoid read the snapshot file twice

docs/content/concepts/primary-key-table/merge-engine.md, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldLastNonNullValueAgg.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldLastValueAgg.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldNestedUpdateAgg.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregatorTest.java, paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
The `last_value` and `last_non_null_value` just set field to null when accept retract messages.
This is good to most cases.
=> [core] Last value and nested_update agg function support retract

paimon-core/src/main/java/org/apache/paimon/stats/FieldStatsArraySerializer.java, paimon-core/src/main/java/org/apache/paimon/stats/FieldStatsConverters.java, paimon-core/src/main/java/org/apache/paimon/table/system/FilesTable.java, paimon-core/src/test/java/org/apache/paimon/io/KeyValueFileReadWriteTest.java, paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileTest.java, paimon-core/src/test/java/org/apache/paimon/stats/FieldStatsArraySerializerTest.java, paimon-core/src/test/java/org/apache/paimon/stats/StatsTestUtils.java
We have introduced `FieldStatsArraySerializer.evolution`, we don't need keep another evolution method `fromBinary`. This PR aims to clean some usage in tests code.
=> [core] Remove legacy stats FieldStatsArraySerializer.fromBinary

paimon-core/src/main/java/org/apache/paimon/manifest/ManifestEntry.java
"Manifest might be corrupted" makes users panic...
=> [core] Remove useless exception message when commit conflicts

paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/operation/PartitionExpire.java
Currently, `PartitionExpire` will scan all manifest entries and merge them in memory before extracting the partitions. This is very inefficient any may cause OOM.
This PR optimizes `PartitionExpire` by filtering partitions while scanning, thus decreasing the number of manifest entries to be merged.
Existing tests should cover the change.
No.
No.
=> [core] Optimize partition expire by filtering partitions while scanning

docs/content/how-to/lookup-joins.md, docs/layouts/shortcodes/generated/flink_connector_configuration.html, paimon-common/src/main/java/org/apache/paimon/data/JoinedRow.java, paimon-common/src/main/java/org/apache/paimon/predicate/PredicateBuilder.java, paimon-common/src/main/java/org/apache/paimon/types/RowType.java, paimon-common/src/main/java/org/apache/paimon/utils/KeyProjectedRow.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/DynamicPartitionLoader.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FullCacheLookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/NoPrimaryKeyLookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PrimaryKeyLookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PrimaryKeyPartialLookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/SecondaryIndexLookupTable.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/FileStoreLookupFunctionTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/LookupTableTest.java
In many cases, data is stored in the payload by partition, and each partition contains the full amount of data, while the latest data is often stored in the latest partition.
We introduce a max_pt mechanism here to only look up the latest partition.
=> [flink] Introduce max_pt for Flink lookup join

paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/mapred/PaimonInputFormat.java, paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/mapred/PaimonInputSplit.java, paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/mapred/PaimonRecordReader.java, paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/utils/HiveSplitGenerator.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/mapred/PaimonInputSplitTest.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/mapred/PaimonRecordReaderTest.java
Pass Table to Split to Avoid Loading from File System when createRecordReader ,this can reduce the access of FileSystem.
=> [Hive]Pass Table into Split to Avoid Loading from FileSystem when createRecordReader

paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/source/InnerTableScanImpl.java, paimon-core/src/main/java/org/apache/paimon/table/system/ReadOptimizedTable.java, paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
The RO table no longer needs to be merged, so we should enable it to have the ability to non-primary key filtering pushdown.
=> [core] Read optimized table supports value filter pushdown

paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java, paimon-core/src/main/java/org/apache/paimon/disk/ExternalBuffer.java, paimon-core/src/main/java/org/apache/paimon/disk/InMemoryBuffer.java, paimon-core/src/main/java/org/apache/paimon/disk/RowBuffer.java, paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java
Fix bug when open spillable, still many small files generated.
=> [core][bug] Write Spillable with memory preemption has bug : preempt memory will cause writer flush memory to disk which should not happen

paimon-codegen/src/main/java/org/apache/paimon/codegen/CodeGeneratorImpl.java, paimon-common/src/main/java/org/apache/paimon/codegen/CodeGenerator.java, paimon-common/src/main/java/org/apache/paimon/utils/FieldsComparator.java, paimon-common/src/test/java/org/apache/paimon/data/BinaryStringTest.java, paimon-core/src/main/java/org/apache/paimon/codegen/CodeGenUtils.java, paimon-core/src/main/java/org/apache/paimon/crosspartition/GlobalIndexAssigner.java, paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBState.java, paimon-core/src/main/java/org/apache/paimon/mergetree/MergeSorter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeReaders.java, paimon-core/src/main/java/org/apache/paimon/mergetree/SortBufferWriteBuffer.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ChangelogMergeTreeRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/SortMergeReader.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/SortMergeReaderWithLoserTree.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/SortMergeReaderWithMinHeap.java, paimon-core/src/main/java/org/apache/paimon/operation/DiffReader.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreRead.java, paimon-core/src/main/java/org/apache/paimon/sort/BinaryExternalSortBuffer.java, paimon-core/src/main/java/org/apache/paimon/utils/KeyComparatorSupplier.java, paimon-core/src/test/java/org/apache/paimon/mergetree/MergeSorterTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/SortMergeReaderTestBase.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/SortOperator.java
We should separate user define sequence fields and incremental sequence id. This way, there will be no more accuracy issues. When comparing, we can first compare the user-defined sequenceField (We don't need to extract long now, just compare) and then compare our self increasing sequenceId.
There are still many codes that need to be modified as a whole, and this is just the first part.
First step of https://github.com/apache/incubator-paimon/pull/2811
=> [core] Introduce userDefineSeqComparator for MergeSorter

paimon-core/src/main/java/org/apache/paimon/manifest/FileEntry.java, paimon-core/src/main/java/org/apache/paimon/manifest/ManifestEntry.java, paimon-core/src/main/java/org/apache/paimon/manifest/ManifestFile.java, paimon-core/src/main/java/org/apache/paimon/manifest/ManifestFileMeta.java, paimon-core/src/main/java/org/apache/paimon/manifest/SimpleFileEntry.java, paimon-core/src/main/java/org/apache/paimon/manifest/SimpleFileEntrySerializer.java, paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/operation/FileDeletionBase.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/partition/PartitionPredicate.java, paimon-core/src/main/java/org/apache/paimon/utils/ObjectsFile.java, paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileMetaTestBase.java, paimon-core/src/test/java/org/apache/paimon/partition/PartitionPredicateTest.java
This is different from https://github.com/apache/incubator-paimon/pull/1114
This PR aims to reduce memory in FileStoreCommit to avoid OOM.
Often with dozens of fields, this PR can reduce memory usage by 10 times.
=> [core] Introduce SimpleFileEntry to reduce memory in FileStoreCommit

paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java
An small bug: Exception have been swallowed if finally throws an exception too.
=> [core] Exception should be thrown after 'catch' in `AppendOnlyWriter`.

paimon-core/src/main/java/org/apache/paimon/utils/SerializableRunnable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java
Currently we check for sink materializer and throws exception in SQL compile time. However, some cloud computing flatform (for example, aliyun VVP) allows user to change some Flink configurations after compiling SQL but before starting the job.
This PR postpone sink materializer check from compile time to runtime to work around such case.
No.
No,
=> [flink] Postpone sink materializer check from compile time to runtime

paimon-common/src/main/java/org/apache/paimon/data/columnar/ColumnarRowIterator.java, paimon-common/src/main/java/org/apache/paimon/reader/RecordReader.java, paimon-common/src/main/java/org/apache/paimon/reader/RecordWithPositionIterator.java, paimon-format/src/main/java/org/apache/paimon/format/orc/OrcReaderFactory.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetReaderFactory.java, paimon-format/src/test/java/org/apache/paimon/format/orc/OrcReaderFactoryTest.java
before: rowPosition(), next()
after: next(), rowPositon()
Only in this way can we correctly apply filter to it
=> [core] Redefine the usage of RecordWithPositionIterator

.github/workflows/utitcase-flink.yml, paimon-flink/paimon-flink-1.14/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java, paimon-flink/paimon-flink-1.15/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java, paimon-flink/paimon-flink-1.16/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java, paimon-flink/paimon-flink-common/pom.xml, paimon-flink/pom.xml
Fix that paimon-flink-1.1x tests cannot be touched now (some tests are error in 1.1x module but not be tested)
And replace hadoop-common dep to paimon-flink pom because the tests of paimon-flink-1.1x need it.
=> [ci] Fix paimon flink tests

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/sink/TableCommitImpl.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java
Linked issue: close #2957
`org.apache.paimon.flink.sink.CommitterOperatorTest#testForceCreateSnapshotCommit`
=> [core] New parameters `commit.force-create-snapshot` Used to force a snapshot to be generated when committing

paimon-core/src/main/java/org/apache/paimon/manifest/FileEntry.java, paimon-core/src/main/java/org/apache/paimon/manifest/ManifestFile.java, paimon-core/src/main/java/org/apache/paimon/manifest/ManifestFileMeta.java, paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileMetaTest.java, paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileMetaTestBase.java
Before optimization: Read all entries into memory, which is prone to OOM.
Optimized: Stream read entries into files, no longer reading all entries into memory.
=> [core] Optimize full compaction for manifest entries

docs/layouts/shortcodes/generated/spark_connector_configuration.html, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkConnectorOptions.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/catalog/SparkBaseCatalog.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/connector/catalog/CatalogUtils.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonHiveTestBase.scala
=> [spark] use the internal session catalog in spark generic catalog

paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/SearchArgumentToPredicateConverter.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveReadITCase.java
…whatever use uppercase or lowercase field name in sql.
Linked issue: close #2844
hivesql query paimon external table can work after schema evolution. whatever use uppercase or lowercase field name in sql.
=> [hive] hivesql query paimon external table can work after schema evolution. 

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ChangelogMergeTreeRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FullChangelogMergeTreeCompactRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeTreeCompactRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactRewriter.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java
`ChangelogMergeTreeRewriter` should get rid of lookup concept.
=> [core] Refactor ChangelogMergeTreeRewriter to lookup free

docs/layouts/shortcodes/generated/jdbc_catalog_configuration.html, paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalog.java, paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalogOptions.java, paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreRead.java, paimon-core/src/main/java/org/apache/paimon/utils/BulkFormatMapping.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
1.Drop a Hive external table only deletes metadata but not data files.
2.Remove uncalled methods: checkIdentifierUpperCase、schemaFileExists
3.Modify wrong words
=> [hive] Drop a Hive external table only deletes metadata but not data files.

paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java, paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java, paimon-core/src/main/java/org/apache/paimon/deletionvectors/ApplyDeletionVectorReader.java, paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVector.java, paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVectorsMaintainer.java, paimon-core/src/main/java/org/apache/paimon/index/HashIndexFile.java, paimon-core/src/main/java/org/apache/paimon/index/IndexFileHandler.java, paimon-core/src/main/java/org/apache/paimon/io/KeyValueFileReaderFactory.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreRead.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/query/LocalTableQuery.java, paimon-core/src/main/java/org/apache/paimon/table/source/DataSplit.java, paimon-core/src/main/java/org/apache/paimon/table/source/DeletionFile.java, paimon-core/src/main/java/org/apache/paimon/table/source/MergeTreeSplitGenerator.java, paimon-core/src/main/java/org/apache/paimon/table/source/Split.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalStartingScanner.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java, paimon-core/src/test/java/org/apache/paimon/io/KeyValueFileReadWriteTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/ContainsLevelsTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/LookupLevelsTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTestBase.java, paimon-core/src/test/java/org/apache/paimon/table/source/SplitGeneratorTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/TestChangelogDataReadWrite.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/ScanHelper.scala
Deletion file should be in Split, and the reader should respect deletion files in Split, instead of reading deletion manifest again which is very costly.
=> [core] Introduce deletion files to DataSplit

paimon-core/src/main/java/org/apache/paimon/migrate/Migrator.java, paimon-flink/paimon-flink-common/pom.xml, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/MigrateDatabaseProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/TableMigrationUtils.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/migrate/HiveMigrator.java
paimon-flink module should not depend on Hive directly.
=> [flink] Remove MigrateDatabaseProcedure's dependency on Hive

paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala, paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala, paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/sql/DeleteFromTableTest.scala, paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/DeleteFromTableTest.scala, paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/DeleteFromTableTest.scala, paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/sql/DeleteFromTableTest.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DeleteFromTableTest.scala
Linked issue: close https://github.com/apache/incubator-paimon/issues/2860
Spark3.2 DeleteFromTableTest
Spark3.1 cannot use DeleteFromTableTest because of conflict
=> Support DeleteFromPaimonTableCommand for Spark3.x ( x < 3)

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ConcatRecordReader.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreRead.java, paimon-core/src/main/java/org/apache/paimon/table/source/KeyValueTableRead.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupStreamingReader.java
In fact, `KeyValueTableRead` only reads the content of the value and does not read the columns of the key. We should default to opening the projection of the key.
=> [core] KeyValueTableRead should always project keys

paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeReaders.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ChangelogMergeTreeRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactRewriter.java, paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTestBase.java
(Just code refactor) Compaction should only invoke one `MergeTreeReaders.readerForMergeTree`.
=> [core] Refactor MergeTreeReaders.readerForMergeTree to unify invoking

paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java, paimon-core/src/main/java/org/apache/paimon/table/source/InnerStreamTableScanImpl.java, paimon-core/src/main/java/org/apache/paimon/table/source/InnerTableScanImpl.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/DeletionVectorITCase.java
=> [core] Fix streaming & batch read dv table

paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreRead.java, paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java, paimon-core/src/main/java/org/apache/paimon/table/query/LocalTableQuery.java, paimon-core/src/main/java/org/apache/paimon/utils/UserDefinedSeqComparator.java, paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FullCacheLookupTable.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/TestChangelogDataReadWrite.java
In the reading merging process, if there is a projection inside, we did not consider the existence of the sequence field and its index position.
=> [core] Fix merge index out of range for sequence field

paimon-core/src/main/java/org/apache/paimon/table/source/PlanImpl.java, paimon-core/src/test/java/org/apache/paimon/mergetree/MergeSorterTest.java, paimon-core/src/test/java/org/apache/paimon/utils/AsyncRecordReaderTest.java, paimon-core/src/test/java/org/apache/paimon/utils/ParallelExecutionTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumeratorTest.java, tools/maven/checkstyle.xml
Use javax.annotation.Nullable instead of org.jetbrains.annotations.Nullable.
=> [checkstyle] forbid use of org.jetbrains.annotations.Nullable

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/assigners/AlignedSplitAssigner.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/assigners/DynamicPartitionPruningAssigner.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/assigners/FIFOSplitAssigner.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/assigners/PreAssignSplitAssigner.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/assigners/SplitAssigner.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumeratorTest.java
Linked issue: close #3010 
[flink] splitAssigner adds a thread-safe interface for obtaining the number of remaining splits.
- org.apache.paimon.flink.source.ContinuousFileSplitEnumeratorTest#testEnumeratorSplitMax
No
No
=> [flink] splitAssigner adds a thread-safe interface for obtaining the number of remaining splits.

paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkITCase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncTableSinkITCase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/TestTable.java
The TestCdcSourceFunction is bounded source, which will cause the downstream to produce committable with ID Long.MAX_VALUE. But the compaction of unaware bucket is unbounded, so it won't call the `endInput()`, thus the final committable may not be handled.
Additionally, revert some test codes, so others tests may be more stable.
=> [hotfix] Fix unstable testRandomCdcEventsUnawareBucket

paimon-format/src/main/java/org/apache/paimon/format/avro/AvroBulkFormat.java
=> [core] `AvroReader` should not get file-size by file-io repeatly.

paimon-core/src/main/java/org/apache/paimon/utils/JsonSerdeUtil.java, paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/HiveSchema.java, paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/PaimonSerDe.java, paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/PaimonStorageHandler.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveTableSchemaTest.java
The Map Task will fetch  the tableschema  of paimon. we cache the schema json to configuration to reduce the access of FileSystem
=> [Hive] Cache TableSchema into Configuration to avoid loading read scheme file in PaimonSerDe

docs/layouts/shortcodes/generated/catalog_configuration.html, paimon-common/src/main/java/org/apache/paimon/options/CatalogOptions.java, paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java, paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java, paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalog.java, paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalogFactory.java, paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalogLock.java, paimon-core/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory, paimon-core/src/test/java/org/apache/paimon/jdbc/JdbcCatalogTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FileSystemCatalogITCase.java, paimon-flink/paimon-flink-common/src/test/resources/META-INF/services/org.apache.paimon.factories.Factory, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalogLock.java, paimon-hive/paimon-hive-catalog/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
Linked issue: close #2826 
This PR aims to add lock in file system catalog
Added test `FileSystemCatalogITCase#testCatalogWithLockForSchema`
no
no
=> [core] Support configuring lock in paimon catalog

paimon-codegen/src/main/scala/org/apache/paimon/codegen/EqualiserCodeGenerator.scala, paimon-codegen/src/main/scala/org/apache/paimon/codegen/ScalarOperatorGens.scala, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FullCompactionFileStoreITCase.java
See the test case:
If we didn't handle ARRAY<ROW>, the `valueEqualiser` in `FullChangelogMergeFunctionWrapper` and `LookupChangelogMergeFunctionWrapper` might throw exception when call `equals`.
=> [codegen] EqualiserCodeGenerator supports ARRAY<ROW>

paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreScan.java, paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
subTask of #2898, The dv table no longer needs to be merged, so we should enable it to have the ability to non-primary key filtering pushdown.
=> [core] Dv table supports value filter pushdown

paimon-hive/paimon-hive-connector-3.1/src/test/java/org/apache/paimon/hive/HiveWriteITCase.java, paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/mapred/PaimonOutputCommitter.java, paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/mapred/PaimonOutputFormat.java, paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/mapred/TezUtil.java
Linked issue: close #2804 
in some hadoop hive3 mr engine it will use tez(org.apache.tez.mapreduce.output.MROutput) to commit job,use org.apache.hadoop.mapred.TaskAttemptID as the key may cause that writer cannot be found,so we rewrite the equlas and hashcode
HiveWriteITCase
no
=> [hive]fix hive writer in tez-mr

paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java, paimon-core/src/main/java/org/apache/paimon/AppendOnlyFileStore.java, paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java, paimon-core/src/main/java/org/apache/paimon/io/KeyValueFileReaderFactory.java, paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreRead.java, paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreRead.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java, paimon-core/src/test/java/org/apache/paimon/TestFileStore.java, paimon-core/src/test/java/org/apache/paimon/io/KeyValueFileReadWriteTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/ContainsLevelsTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/LookupLevelsTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTestBase.java, paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java, paimon-core/src/test/java/org/apache/paimon/operation/FileStoreCommitTest.java, paimon-core/src/test/java/org/apache/paimon/operation/FileStoreExpireTestBase.java, paimon-core/src/test/java/org/apache/paimon/operation/KeyValueFileStoreReadTest.java, paimon-core/src/test/java/org/apache/paimon/operation/KeyValueFileStoreScanTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/TestChangelogDataReadWrite.java
We already store TableSchema in `AbstractFileStoreTable`, but we don't use it.
We can use it to avoid read schema from filesystem.
=> [core] Reduce schema read for readers

paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java, paimon-core/src/test/java/org/apache/paimon/schema/SchemaManagerTest.java, paimon-core/src/test/java/org/apache/paimon/schema/SchemaUtils.java, paimon-core/src/test/java/org/apache/paimon/schema/TableSchemaTest.java
1, add more validation for sequence field.
2, remove sequence padding from CoreOptions.
=> [core] Add more validation for sequence field during create table.

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-common/src/main/java/org/apache/paimon/types/InternalRowToSizeVisitor.java, paimon-common/src/test/java/org/apache/paimon/types/InternalRowToSizeVisitorTest.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/shuffle/RangeShuffle.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/SortUtils.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/SortCompactActionForUnawareBucketITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/shuffle/RangeShuffleTest.java
Improve the processing efficiency of sort compaction operations when there is data size skewness on range phase.
1. add  the  size based rangestrategy config.
2. add sample ratio config for per task and range num config.
SortCompactActionForUnawareBucketITCase
RangeShuffleTest
InternalRowToSizeVisitorTest
add config  
``` --table_conf sort-compaction.range-strategy= SIZE ```
=> [Flink]add range strategy for sort compaction

paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/DeletionVectorITCase.java
Fix dv table with partial-update and aggregate when changelog-producer = none
=> [core] Fix dv table with partial-update and aggregate

paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/TableWriterBenchmark.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommit.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java, paimon-core/src/main/java/org/apache/paimon/table/sink/BatchTableCommit.java, paimon-core/src/main/java/org/apache/paimon/table/sink/TableCommitImpl.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkTableSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/SupportsRowLevelOperationFlinkTableSink.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonTruncateTableCommand.scala
1. Introduce BatchTableCommit.truncateTable
2. Fix `TableWriterBenchmark`, it should not flush per 10000 rows.
=> [core] Introduce BatchTableCommit.truncateTable

paimon-common/src/main/java/org/apache/paimon/utils/Int2ShortHashMap.java, paimon-core/src/main/java/org/apache/paimon/index/PartitionIndex.java
Linked issue: close #3038
When using dynamic bucket, i find out that when restart the job, it will cost long time to load index, and after observing the flame graph, i find out the thread was stuck at :
and by watching the code line 249 in Int2ShortOpenHashMap was quoted by 'There's always an unused entry.' 
So i add initial Int2ShortOpenHashMap size to avoid the thread stuck to accelerate the load process.
=> [core] add initial map size to solve load index slowly.

paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreRead.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/source/InnerTableScanImpl.java, paimon-core/src/main/java/org/apache/paimon/table/source/MergeTreeSplitGenerator.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java, paimon-core/src/main/java/org/apache/paimon/table/system/ReadOptimizedTable.java, paimon-core/src/test/java/org/apache/paimon/table/source/SplitGeneratorTest.java
First row merge engine does not need to be merged in batch read, in this PR, we deal with FIRST ROW just like deletion vectors:
1. Scan only read level bigger that 0.
2. Split splits for first_row.
3. Make Raw Files for first_row.
4. Read no merge when raw file exists.
=> [core] Optimize first_row batch read

.github/workflows/e2e-tests-1.18-jdk11.yml, .github/workflows/e2e-tests-1.18.yml, .github/workflows/e2e-tests-1.19-jdk11.yml, .github/workflows/e2e-tests-1.19.yml, .github/workflows/utitcase-flink.yml, paimon-e2e-tests/pom.xml, paimon-flink/paimon-flink-1.15/src/main/java/org/apache/paimon/flink/utils/ManagedMemoryUtils.java, paimon-flink/paimon-flink-1.15/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java, paimon-flink/paimon-flink-1.16/pom.xml, paimon-flink/paimon-flink-1.16/src/main/java/org/apache/paimon/flink/utils/ManagedMemoryUtils.java, paimon-flink/paimon-flink-1.16/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java, paimon-flink/paimon-flink-1.17/src/main/java/org/apache/paimon/flink/utils/ManagedMemoryUtils.java, paimon-flink/paimon-flink-1.17/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java, paimon-flink/paimon-flink-1.18/pom.xml, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/utils/ManagedMemoryUtils.java, paimon-flink/paimon-flink-1.18/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java, paimon-flink/paimon-flink-1.19/pom.xml, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSink.java, paimon-flink/paimon-flink-common/pom.xml, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowDataStoreWriteOperator.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/RescaleBucketITCase.java, paimon-flink/pom.xml, paimon-hive/paimon-hive-catalog/pom.xml, paimon-hive/paimon-hive-connector-2.3/pom.xml, paimon-hive/paimon-hive-connector-3.1/pom.xml, paimon-hive/paimon-hive-connector-common/pom.xml, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java, paimon-hive/pom.xml, pom.xml
Modification :
1. ENABLE_FINE_GRAINED_RESOURCE_MANAGEMENT was removed and the default setting is true.
2. RowDataStoreWriteOperator:  FunctionUtils#openFunction (method signature changed)
3. ManagedMemoryUtils: StreamConfig#getManagedMemoryFractionOperatorUseCaseOfSlot (method signature changed)
Fixed test :
RescaleBucketITCase#testSuspendAndRecoverAfterRescaleOverwrite
and some conflict jar in pom
Added tests : 
flink-1.19 tests
flink-1.19 e2e tests
=> [flink] Bump flink version to 1.19

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ChangelogMergeTreeRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FullChangelogMergeTreeCompactRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeTreeCompactRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactRewriter.java
When upgrade is possible and delete row count is 0, we can avoid rewrite
=> [core] Skip rewrite when delete row count is 0 with dv

.mvn/readme.txt, pom.xml
Someone may want to compile a child module in the child directory instead of using `-pl`, but after #2883 using this way to compile will raise an error.
Even though I don't agree with compiling like this (doge.jpg), still find a way to fix it
=> [hotfix] Add project root path to files to facilitate compiling modules in child dirs

paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/FileStoreTable.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/BucketProcessor.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/SchemaHelper.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/WriteIntoPaimonTable.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DynamicBucketTableTest.scala
=> [spark] minor refactor SparkWriter

README.md
#3063 used the Maven variable ${maven.multiModuleProjectDirectory}, which was added in versions after Maven 3.3.1. Therefore, it's necessary to declare the minimum required version of Maven.
=> [doc]introduce the minimum version of Maven.

docs/content/engines/flink.md, paimon-e2e-tests/src/test/java/org/apache/paimon/tests/FlinkProceduresE2eTest.java, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/CompactProcedure.java, paimon-flink/paimon-flink-1.18/src/test/java/org/apache/paimon/flink/procedure/ProcedurePositionalArgumentsITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogITCaseBase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/SortCompactActionForDynamicBucketITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/SortCompactActionForUnawareBucketITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/CompactProcedureITCase.java
Migrate procedure tests from action tests.
Add test in flink-1.18 to ensure compatiblity.
Compact procedure supports named arguments. The names are:
table, partitions, order_strategy, order_by, options
flink -> procedures
=> [flink] Compact procedure supports named arguments

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncTableActionBase.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SynchronizationActionBase.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/CdcActionITCaseBase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSchemaITCase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableActionITCase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/postgres/PostgresSyncTableActionITCase.java
When using cdc action to synchronize the existing paimon table, the latest dynamic options are not updated to the table schema file.
You can first create a paimon table, start a cdc action and configure several new options. After the action is started, check the latest schema of the table. The latest schema of the table does not have the latest options.
=> [cdc] Update the latest dynamic options to the table schema file when synchronizing an existing paimon table using the cdc action.

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/debezium/DebeziumRecordParser.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/debezium/DebeziumSchemaUtils.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlRecordParser.java
=> [CDC] extract common code

paimon-core/src/main/java/org/apache/paimon/io/DataFileMeta.java, paimon-core/src/main/java/org/apache/paimon/table/source/AppendOnlySplitGenerator.java, paimon-core/src/main/java/org/apache/paimon/table/source/MergeTreeSplitGenerator.java, paimon-core/src/main/java/org/apache/paimon/table/source/SplitGenerator.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalStartingScanner.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java, paimon-core/src/test/java/org/apache/paimon/io/DataFileTestUtils.java, paimon-core/src/test/java/org/apache/paimon/table/source/SplitGeneratorTest.java, paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/SnapshotReaderTest.java
- make SplitGenerator return files + rawConvertible
- optimizer split generate
=> [core] Introduce SplitGroup for SplitGenerator

paimon-common/pom.xml, paimon-common/src/main/java/org/apache/paimon/utils/RoaringBitmap32.java, paimon-common/src/main/resources/META-INF/NOTICE, paimon-core/pom.xml, paimon-core/src/main/java/org/apache/paimon/deletionvectors/BitmapDeletionVector.java
subtask of #2898
- wapper RoaringBitma in paimon-common
- Shade roaringbitmap dependency into paimon-common, paimon-common.jar, before 3.3M -> after 3.6M
=> [core] Shade roaringbitmap dependency into paimon-common

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SynchronizationActionBase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java, paimon-flink/paimon-flink-cdc/src/test/resources/mysql/sync_table_setup.sql
Fix cdc existing table options unavailable to change.
=> [cdc] Fix cdc existing table options unavailable to change.

paimon-core/src/test/java/org/apache/paimon/operation/KeyValueFileStoreScanTest.java
```
Error:  org.apache.paimon.operation.KeyValueFileStoreScanTest.testWithValueFilter  Time elapsed: 0.154 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
expected: 1
but was: 3
```
=> [test] Fix flaky testWithValueFilter

paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java, paimon-core/src/main/java/org/apache/paimon/io/NewFilesIncrement.java, paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeWriter.java, paimon-core/src/main/java/org/apache/paimon/migrate/FileMetaUtils.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java, paimon-core/src/main/java/org/apache/paimon/table/sink/CommitMessageSerializer.java, paimon-core/src/test/java/org/apache/paimon/index/HashBucketAssignerTest.java, paimon-core/src/test/java/org/apache/paimon/manifest/ManifestCommittableSerializerTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java
=> [core] add deletedFiles in NewFilesIncrement

paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyCompactionTask.java, paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java, paimon-core/src/main/java/org/apache/paimon/io/DataFileMeta.java, paimon-core/src/main/java/org/apache/paimon/io/DataIncrement.java, paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeWriter.java, paimon-core/src/main/java/org/apache/paimon/migrate/FileMetaUtils.java, paimon-core/src/main/java/org/apache/paimon/table/sink/CommitMessageImpl.java, paimon-core/src/main/java/org/apache/paimon/table/sink/CommitMessageSerializer.java, paimon-core/src/main/java/org/apache/paimon/utils/CommitIncrement.java, paimon-core/src/test/java/org/apache/paimon/index/HashBucketAssignerTest.java, paimon-core/src/test/java/org/apache/paimon/manifest/ManifestCommittableSerializerTest.java, paimon-core/src/test/java/org/apache/paimon/table/sink/CommitMessageSerializerTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommittableSerializerTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/MultiTableCommittableSerializerTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/WrappedManifestCommittableSerializerTest.java
=> [core] rename NewFilesIncrement to DataIncrement

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/SinkSavepointITCase.java
Flink 1.19 uses exponential delay as the default restart strategy. It will make `SinkSavepointITCase` prone to timeout.
This PR specifies restart strategy for `SinkSavepointITCase` to fix this issue.
No test is needed.
No changes.
Not needed.
=> [flink] Specify restart strategy for SinkSavepointITCase

paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionITCaseBase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableActionITCase.java
The `send` is asynchronously, so if we want test `latest` or `current_timestamp`, we need to ensure the previouse data are sent.
=> [hotfix] Fix unstable Kafka CDC starup mode tests

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/Changelog.java, paimon-core/src/main/java/org/apache/paimon/Snapshot.java, paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/operation/FileDeletionBase.java, paimon-core/src/main/java/org/apache/paimon/operation/SnapshotDeletion.java, paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/ExpireChangelogImpl.java, paimon-core/src/main/java/org/apache/paimon/table/ExpireSnapshotsImpl.java, paimon-core/src/main/java/org/apache/paimon/table/ReadonlyTable.java, paimon-core/src/main/java/org/apache/paimon/table/RollbackHelper.java, paimon-core/src/main/java/org/apache/paimon/table/Table.java, paimon-core/src/main/java/org/apache/paimon/table/source/AbstractInnerTableScan.java, paimon-core/src/main/java/org/apache/paimon/table/source/InnerStreamTableScanImpl.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousFromSnapshotStartingScanner.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousFromTimestampStartingScanner.java, paimon-core/src/main/java/org/apache/paimon/utils/NextSnapshotFetcher.java, paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java, paimon-core/src/test/java/org/apache/paimon/TestFileStore.java, paimon-core/src/test/java/org/apache/paimon/operation/ExpireSnapshotsTest.java, paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java, paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java, paimon-core/src/test/java/org/apache/paimon/table/source/StartupModeTest.java, paimon-core/src/test/java/org/apache/paimon/table/source/TableScanTest.java, paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ContinuousFromTimestampStartingScannerTest.java, paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ScannerTestBase.java, paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java
This PR is the first step for #2899. It's mainly do the following things.
- Add `changelog` related option to define the changlog lifecycle.
- Introduce `ExpireChangelogImpl` to handle the changelog expire
=> [core] Introduce ExpireChangelogImpl to decouple the changelog lifecycle

paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommit.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java, paimon-core/src/main/java/org/apache/paimon/table/sink/StreamTableCommit.java, paimon-core/src/main/java/org/apache/paimon/table/sink/TableCommitImpl.java, paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java, paimon-core/src/test/java/org/apache/paimon/operation/FileStoreCommitTest.java, paimon-core/src/test/java/org/apache/paimon/operation/PartitionExpireTest.java, paimon-core/src/test/java/org/apache/paimon/operation/TestCommitThread.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCommitter.java
https://github.com/apache/paimon/pull/301 FileStoreCommitImpl also checks for conflicts when committing append changes.
But it only for "When the job runs to checkpoint N, if the user recovers from an old checkpoint (such as checkpoint N-5), the sink of the current FTS will cause a manifest corruption because duplicate files may be committed.".
We should optimize this, normal commit will cause too much check burden.
=> [core] FileStoreCommit should check append files only in recovering

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/shuffle/RangeShuffle.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/SortUtils.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/SortCompactActionForUnawareBucketITCase.java
Add local sample config for sort compaction . It' helpful for the sort compaction task with large parallelism,which sampling may lead to a performance bottleneck.
=> [compaction]Add local sample config for sort compaction

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/DynamicPartitionLoader.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/FileStoreLookupFunctionTest.java
=> [lookup] Fix NPE when FileStoreLookupFunction init empty table with dynamic partition

paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java, paimon-core/src/test/java/org/apache/paimon/operation/FileStoreCommitTest.java
This PR fixes `FileStoreCommitTest#testCommitOldSnapshotAgain`.
=> [core] Fix failed tests in FileStoreCommitTest

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FirstRowMergeFunctionWrapper.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeTreeCompactRewriter.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapperTest.java
=> [typo] Fix typo of FirstRowMergeFunctionWrapper

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FullCacheLookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/NoPrimaryKeyLookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PrimaryKeyLookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/SecondaryIndexLookupTable.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/LookupTableTest.java
Open `RocksDBStateFactory` should in `FullCacheLookupTable.open`, otherwise there will be NPE.
=> [flink] Fix re-open for FullCacheLookupTable implementations

paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/paimon/spark/catalyst/optimizer/MergePaimonScalarSubqueriers.scala, paimon-spark/paimon-spark-3.4/src/main/scala/org/apache/paimon/spark/catalyst/optimizer/MergePaimonScalarSubqueriers.scala, paimon-spark/paimon-spark-3.5/src/main/scala/org/apache/paimon/spark/catalyst/optimizer/MergePaimonScalarSubqueriers.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/optimizer/MergePaimonScalarSubqueriersBase.scala
use cachedRelation.output to build OutputMap in MergePaimonScalarSubqueriers
before
```
=== Applying Rule org.apache.paimon.spark.catalyst.optimizer.MergePaimonScalarSubqueriers ===
!Project [CASE WHEN (scalar-subquery#0 [] > 74129) THEN scalar-subquery#1 [] ELSE scalar-subquery#2 [] END AS bucket1#3, CASE WHEN (scalar-subquery#4 [] > 122840) THEN scalar-subquery#5 [] ELSE scalar-subquery#6 [] END AS bucket2#7, CASE WHEN (scalar-subquery#8 [] > 56580) THEN scalar-subquery#9 [] ELSE scalar-subquery#10 [] END AS bucket3#11, CASE WHEN (scalar-subquery#12 [] > 10097) THEN scalar-subquery#13 [] ELSE scalar-subquery#14 [] END AS bucket4#15, CASE WHEN (scalar-subquery#16 [] > 165306) THEN scalar-subquery#17 [] ELSE scalar-subquery#18 [] END AS bucket5#19]   WithCTE
!:  :- Aggregate [count(1) AS …
```
=> [spark] use cachedRelation.output to build OutputMap in MergePaimonScalarSubqueriers

paimon-core/src/main/java/org/apache/paimon/io/KeyValueDataFileRecordReader.java, paimon-core/src/main/java/org/apache/paimon/io/KeyValueFileReaderFactory.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/FileStoreTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MergeIntoAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/LocalMergeOperator.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/MergeIntoActionITCase.java
Before #3128 , the delete records can be write into data file even when `ignore-delete=true`. So if using jar built after 3128 to read old data, the merge engine might throw exception. This PR fix it by adding filter in reader.
Besides, records passed by `LocalMergeOperator` also should be filtered.
Also remove `changeIgnoreMergeEngine` in merge_into action. Because I think merge_into should also obey the constrains of merge engine.
=> [core] Fix that ignore-delete option is not compatible with old delete records and LocalMergeOperator

paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/catalyst/Compatibility.scala, paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonDeleteTable.scala, paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/paimon/spark/catalyst/Compatibility.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/Compatibility.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/RowLevelOp.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/expressions/ExpressionHelper.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/MergeIntoPaimonTable.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonTruncateTableCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/UpdatePaimonTableCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/sources/PaimonSink.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DeleteFromTableTest.scala
=> [spark] delete for append table

paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
Linked issue: #3157
Because the same builder is used in the for loop of generateSplits in SnapshotReaderImpl, if rawConvertible is true the last time, it will affect the value of the next Datasplit rawFiles. The ultimate result is the need for MergeRedier's Datasplit, as rawFiles were mistakenly set and NoMergeReader was created, resulting in duplicate data during reading
=> [core] Fix duplicate primary keys in query results

paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java, paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java, paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java, paimon-core/src/test/java/org/apache/paimon/format/FileFormatSuffixTest.java, paimon-core/src/test/java/org/apache/paimon/operation/AppendOnlyFileStoreWriteTest.java
Reduce small files generation in many partitions write job of append only table.
=> [core] Reduce small files while batch write append only table with a lot of partitions.

paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java
The `parallelStream` will run in multi thread, it will lead to unstable results of assert delete files number.
This should can resolve the unstable `OrphanFilesCleanTest.testCleanOrphanFilesWithChangelogDecoupled` such as https://github.com/apache/paimon/actions/runs/8587139001/job/23530395569
=> [Bug] Fix the race condition in OrphanFilesClean

paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
if the commit times is 5, the changelog-1 is not expired may lead to unexpected file left.
such as
https://github.com/Aitozi/incubator-paimon/actions/runs/8590046982/job/23537660465
=> [Bug] Fix the unstable testRollbackToTagWithChangelogDecoupled

paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/CreateTableITCase.java
=> [hive] Support recreate the hive table

paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/spark/sql/PaimonStatsUtils.scala, paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/spark/sql/PaimonStatsUtils.scala, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonMetrics.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonRecordReaderIterator.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonStatistics.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/expressions/ExpressionHelper.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/MergeIntoPaimonTable.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonAnalyzeTableColumnCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonDynamicPartitionOverwriteCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/UpdatePaimonTableCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/sources/PaimonSink.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/statistics/StatisticsHelperBase.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/PaimonStatsUtils.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/PaimonUtils.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/connector/catalog/PaimonCatalogUtils.scala
Avoid conflicts with original spark objects
=> [spark] Add paimon prefix to objects under spark sql package

paimon-common/src/main/java/org/apache/paimon/data/columnar/ColumnarRow.java, paimon-common/src/main/java/org/apache/paimon/data/columnar/ColumnarRowIterator.java, paimon-common/src/main/java/org/apache/paimon/data/columnar/VectorizedColumnBatch.java, paimon-common/src/main/java/org/apache/paimon/reader/VectorizedRecordIterator.java, paimon-format/src/main/java/org/apache/paimon/format/orc/OrcReaderFactory.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetReaderFactory.java
For the integration of computing engines, if the computing engine can perceive that the returned iterator is a columnar batch, then the computing engine has more opportunities to accelerate computation.
=> [core] Expose VectorizedRecordIterator to accelerate append table read

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/MonitorFunction.java
Balance MonitorFunction data shuffle for partitioned table, because partitioned table with one bucket only shuffle to one subtask
=> [flink] Balance MonitorFunction data shuffle for partitioned table

paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/paimon/spark/PaimonScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/optimizer/MergePaimonScalarSubqueriersBase.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/statistics/StatisticsHelperBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonOptimizationTestBase.scala
=> [spark] Use Seq in the PaimonScan's constructor to ensure equals

docs/layouts/shortcodes/generated/other_functions.html, paimon-common/src/main/java/org/apache/paimon/types/DataTypeJsonParser.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/ComputedColumn.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/ComputedColumnUtils.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/Expression.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
=> [cdc] Calculated columns support constant value.

paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/CdcActionITCaseBase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/kafka/KafkaTableTestBase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkITCase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncTableSinkITCase.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/AsyncLookupFunctionWrapper.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogITCaseBase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FileStoreITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FileSystemCatalogITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkTestBase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/MappingTableITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PrimaryKeyFileStoreTableITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ActionITCaseBase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactDatabaseActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CompactorSinkITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/SinkSavepointITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/CompactorSourceITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/MultiTablesCompactorSourceBuilderITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/util/AbstractTestBase.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/procedure/MigrateDatabaseProcedureITCase.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/procedure/MigrateFileProcedureITCase.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/procedure/MigrateTableProcedureITCase.java
As mentioned in #3121 , Flink 1.19 uses exponential delay as the default restart strategy. It will make failure tests prone to timeout.
This PR specifies the default restart strategy for `TableEnvironment` and `StreamExecutionEnvironment` in tests.
This is a refactor for tests. Existing tests should cover the change.
No changes.
Not needed.
=> [flink] Set default recover strategy for TableEnvironment and StreamExecutionEnvironment in tests

paimon-core/src/main/java/org/apache/paimon/operation/FileDeletionBase.java
=> [core] fix when cleaning up a manifest, the name of the manifest is null

docs/content/maintenance/configurations.md, docs/layouts/shortcodes/generated/spark_catalog_configuration.html, docs/layouts/shortcodes/generated/spark_connector_configuration.html, paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/paimon/spark/utils/SQLConfUtils.java, paimon-spark/paimon-spark-3.2/pom.xml, paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/utils/SQLConfUtils.java, paimon-spark/paimon-spark-3.2/src/test/resources/hive-site.xml, paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTest.scala, paimon-spark/paimon-spark-3.3/pom.xml, paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/paimon/spark/utils/SQLConfUtils.java, paimon-spark/paimon-spark-3.3/src/test/resources/hive-site.xml, paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTest.scala, paimon-spark/paimon-spark-3.4/pom.xml, paimon-spark/paimon-spark-3.4/src/test/resources/hive-site.xml, paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTest.scala, paimon-spark/paimon-spark-3.5/pom.xml, paimon-spark/paimon-spark-3.5/src/test/resources/hive-site.xml, paimon-spark/paimon-spark-3.5/src/test/resources/log4j2-test.properties, paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTest.scala, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalogOptions.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkConnectorOptions.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/utils/SQLConfUtils.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonHiveTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTestBase.scala
Snice spark3.4, spark supports config default database for session catalog: `spark.sql.catalog.spark_catalog.defaultDatabase`
In this PR:
- Support config `defaultDatabase` for SparkCatalog: `spark.sql.catalog.$catalogName.defaultDatabase`
- For SparkGenericCatalog, before spark3.4, because we cannot modify the defaultDatabase of session catalog, just ingore it, after spark3.4 support it.
When  the default database does not exist, just create it  (follow the current implementation of paimon)
- Add tests for different spark version
- Since different modules will be executed in parallel during compilation, give different modules  a unique hive port in hive-site.xml
=> [spark] Support config defaultDatabase for spark catalog

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/AbstractFlinkTableFactory.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/DataTableSource.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkTableSource.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/SystemTableSource.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/DataTableSourceTest.java
Currently, the `scan.parallelism` and `scan.infer-parallelism` is not work for system table.  We should implement this because we have `ro` / `audit_log` table
=> [flink] support to infer parallelism for system table

docs/content/primary-key-table/merge-engine.md, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DeleteAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MergeIntoAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MergeIntoActionFactory.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/MergeIntoProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/SupportsRowLevelOperationFlinkTableSink.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ReadWriteTableITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/MergeIntoActionITCase.java
1. partial-update and aggregate should not accept batch update because there is no UB and the aggregate result will be wrong.
2. It's not very clear about how to handle row level batch delete with partial update currently. Doris just delete the record. But it's not easy to delete the record because #3128   and  #3139 .
Support batch update merge engines: `deduplicate` and `first-row`.
Support batch delete merge engines: `deduplicate`.
=> [flink] Add merge-engine check when executing row level batch update and delete

paimon-common/src/main/java/org/apache/paimon/utils/LazyField.java, paimon-core/src/main/java/org/apache/paimon/AppendOnlyFileStore.java, paimon-core/src/main/java/org/apache/paimon/FileStore.java, paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java, paimon-core/src/main/java/org/apache/paimon/deletionvectors/ApplyDeletionVectorReader.java, paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/operation/MergeFileSplitRead.java, paimon-core/src/main/java/org/apache/paimon/operation/RawFileSplitRead.java, paimon-core/src/main/java/org/apache/paimon/operation/SplitRead.java, paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/source/AbstractDataTableRead.java, paimon-core/src/main/java/org/apache/paimon/table/source/KeyValueTableRead.java, paimon-core/src/main/java/org/apache/paimon/table/source/TableRead.java, paimon-core/src/test/java/org/apache/paimon/TestFileStore.java, paimon-core/src/test/java/org/apache/paimon/operation/MergeFileSplitReadTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/MergeIntoActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/TestChangelogDataReadWrite.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/util/ReadWriteTableTestUtil.java
`KeyValueFileStoreRead` is an implementation for `KeyValueFileStore`, this class handle LSM merging and changelog row kind things, it will force reading fields such as sequence and row_kind. For `COUNT(*)` querying, it is slow.
If in batch mode and reading raw files, it is recommended to use `RawFileSplitRead`.
=> [core] Introduce RawFileSplitRead to accelerate batch read for primary key table

pom.xml
When executing a parallel build with a directory-maven-plugin execution, Maven 3.5.0 will output a warning
```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] ***************************************************************** …
```
=> [doc] Update directory-maven-plugin to 1.0 version

docs/content/primary-key-table/merge-engine.md, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DeleteAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MergeIntoAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/SupportsRowLevelOperationFlinkTableSink.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ReadWriteTableITCase.java
correct https://github.com/apache/paimon/pull/3181
=> [core] Unify delete&update&mergeinto for merge engines

paimon-common/src/main/java/org/apache/paimon/data/columnar/ArrayColumnVector.java, paimon-common/src/main/java/org/apache/paimon/data/columnar/ColumnarArray.java, paimon-common/src/main/java/org/apache/paimon/data/columnar/MapColumnVector.java, paimon-common/src/main/java/org/apache/paimon/data/columnar/RowColumnVector.java, paimon-common/src/main/java/org/apache/paimon/data/columnar/heap/HeapArrayVector.java, paimon-common/src/main/java/org/apache/paimon/data/columnar/heap/HeapMapVector.java, paimon-common/src/main/java/org/apache/paimon/data/columnar/heap/HeapRowVector.java, paimon-common/src/main/java/org/apache/paimon/utils/VectorMappingUtils.java, paimon-format/src/main/java/org/apache/paimon/format/orc/reader/OrcArrayColumnVector.java, paimon-format/src/main/java/org/apache/paimon/format/orc/reader/OrcMapColumnVector.java, paimon-format/src/main/java/org/apache/paimon/format/orc/reader/OrcRowColumnVector.java
=> [common] Expose columnar data in RowColumnVector/ArrayColumnVector/MapColumnVector

.github/workflows/docs-tests.yml, docs/content/flink/action-jars.md
Hugo removes google analytics support in the latest version. To avoid breaking the CI, we should specify an older version of hugo.
=> [ci] Use hugo v0.124.1 to build documents

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonStatistics.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/statistics/StatisticsHelperBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTestBase.scala
This PR fixes the following scenario: select without the pushed filter fields like partition when CBO is need like join
```sql
select ... from tbl1
join
select id from tbl2 where partition_col > '1' ...
```
exception
```
partition_col does not exist. Available: id
java.lang.IllegalArgumentException: partition_col does not exist. Available: id
at org.apache.spark.sql.types.StructType.$anonfun$fieldIndex$1(StructType.scala:306)
at scala.collection.immutable.Map$Map1.getOrElse(Map.scala:168)
at org.apache.spark.sql.types.StructType.fieldIndex(StructType.scala:305)
at org.apache.paimon.spark.statistics.StatisticsHelperBase.toRef(StatisticsHelperBase.scala:66)
at org.apache.paimon.spark.statistics.StatisticsHelperBase.$anonfun$filterToCondition$1(StatisticsHelperBase.scala:56)
at …
```
=> [spark] Add the fields in reservedFilters into the estimation of stats

paimon-core/src/main/java/org/apache/paimon/io/DataFileMeta.java
Now if call DataFileMeta's to_string() will report : 
so fix it
=> fix bug of DataFileMeta's to_string()

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FirstRowMergeFunction.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FirstRowMergeFunctionWrapper.java
If we meet high level key during the compact, we could avoid lookup the key in high level in this turn.
=> [core] optimize the first row merge engine

paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexCommon.java, paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexFormat.java, paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexOptions.java, paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexPredicate.java, paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexReader.java, paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexWriter.java, paimon-common/src/main/java/org/apache/paimon/fileindex/bloomfilter/BloomFilterFileIndex.java, paimon-common/src/main/java/org/apache/paimon/fileindex/empty/EmptyFileIndexReader.java, paimon-common/src/main/java/org/apache/paimon/options/Options.java, paimon-common/src/test/java/org/apache/paimon/fileindex/FileIndexFormatFormatTest.java, paimon-core/src/main/java/org/apache/paimon/io/FileIndexWriter.java, paimon-core/src/test/java/org/apache/paimon/table/AppendOnlyFileStoreTableTest.java
* API
If you want to create a file index with map-keys, you need to specify.
```sql
CREATE TABLE <PAIMON_TABLE> (<COLUMN> <COLUMN_TYPE> , ...) WITH
(
"file-index.bloom-filter.columns" = "map_data[key1], map_data[key2], map_data[key3], map_data[key4]", --must
"file-index.bloom-filter.map_data.items" = "200", --optional default 1000000
"file-index.bloom-filter.map_data.fpp" = "0.1",  --optional default 0.1
"file-index.bloom-filter.map_data[key1].items" = "10000", --optional
"file-index.in-manifest-threshold" = "500 B" --optional
)
```
If you want to specify the options for specific map key, you can add an external options like:
`file-index.bloom-filter.<map_column>##<map_key>.<op_key>='<op_value>'`
clickhouse: https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#ta …
=> [core] Enable file index for map type with map-keys.

paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/table/source/DataSplit.java, paimon-core/src/main/java/org/apache/paimon/table/source/IndexFile.java, paimon-core/src/main/java/org/apache/paimon/table/source/RawFile.java, paimon-core/src/main/java/org/apache/paimon/table/source/Split.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalStartingScanner.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java, paimon-core/src/test/java/org/apache/paimon/TestFileStore.java, paimon-core/src/test/java/org/apache/paimon/crosspartition/IndexBootstrapTest.java, paimon-core/src/test/java/org/apache/paimon/operation/MergeFileSplitReadTest.java, paimon-core/src/test/java/org/apache/paimon/table/source/SplitTest.java, paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/SnapshotReaderTest.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/PlaceholderSplit.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/SortCompactActionForUnawareBucketITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumeratorTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FileSplitEnumeratorTestBase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FileStoreSourceSplitGeneratorTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FileStoreSourceSplitSerializerTest.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/mapred/PaimonInputSplitTest.java, paimon-spark/paimon-spark-common/pom.xml, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/ScanHelper.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/SparkDataFileMeta.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/UpdatePaimonTableCommand.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/ScanHelperTest.scala
* REASON
After bloom-filter added to paimon, we should find extra files in `RawFile`.
=> [core] Expose `IndexFile` in `Split`.

paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVector.java, paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVectorsIndexFile.java, paimon-core/src/main/java/org/apache/paimon/index/IndexFileHandler.java, paimon-core/src/main/java/org/apache/paimon/index/IndexFileMeta.java, paimon-core/src/main/java/org/apache/paimon/index/IndexFileMetaSerializer.java, paimon-core/src/test/java/org/apache/paimon/deletionvectors/DeletionVectorsIndexFileTest.java, paimon-core/src/test/java/org/apache/paimon/index/IndexFileMetaSerializerTest.java
1. Use `readFully` to read bytes in DeletionVectorsIndexFile,  fix #3277 
2. Explicitly specify dvRanges' type as LinkedHashMap, not bux fix, just code enhance
3. Add more exception info
=> [core] Use readFully in DeletionVectorsIndexFile and explicitly specify dvRanges' type as LinkedHashMap

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
When we perform alter table operation, `updateHmsTable` method called will lose some StorageDescriptor infos like `bucketCols` variable. It's value changes from empty to null. This will cause an npe exception if we depend on this variable. Actually, there is no need to recreate new StorageDescriptor and SerDeInfo objects when we alter table. Just reuse previous objects and modify them as needed.
call `updateHmsTable` before:
call `updateHmsTable` after:
=> [hive] Reuse table StorageDescriptor info

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapper.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeTreeCompactRewriter.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapperTest.java
```java
mergeFunction2.reset();
if (highLevel != null) {
mergeFunction2.add(highLevel);
}
candidates.forEach(mergeFunction2::add);
KeyValue result = mergeFunction2.getResult();
```
When we find a high-level record, we now add it to the merge function first. We previously assumed that the high-level record had a smaller sequence number, which is incorrect. To obtain accurate results, we should add the high-level record and candidates in order.
=> [core] Fix the merge order in lookup compaction

paimon-core/src/main/java/org/apache/paimon/table/system/TagsTable.java, paimon-core/src/test/java/org/apache/paimon/table/system/TagsTableTest.java
=> [core]tag create time nullable

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/SupportsRowLevelOperationFlinkTableSink.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DeleteFromTableTest.scala
Delete one partition in flink will not produce changelog. But anyway, it should. The pr has done two things:
1、Before delete push down, check the row count, if row number is bigger than 100_0000, we generate a job to finish delete. (Do not apply push down)\
2、Delete the partition by per-record set (set the record kind to RowKing.DELETE, then write it back) in Delete push down action.
fix #1508
=> [flink] Delete in flink should produce changelog no matter what

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcMultiplexRecordChannelComputer.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperator.java
=> [cdc] Combine mode should throw better exception to dynamic bucket table

docs/content/flink/sql-query.md, docs/content/spark/sql-query.md, docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/table/source/AbstractInnerTableScan.java, paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/IncrementalStartingScannerTest.java
=> [core] incremental-between-scan-mode should respect changelog-producer

paimon-core/src/main/java/org/apache/paimon/lookup/BulkLoader.java, paimon-core/src/test/java/org/apache/paimon/crosspartition/GlobalIndexAssignerTest.java
=> [core] Fix SST files written using SstFileWriter don't work with TtlDB

docs/content/primary-key-table/overview.md, docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/io/FileReaderFactory.java, paimon-core/src/main/java/org/apache/paimon/io/KeyValueFileReaderFactory.java, paimon-core/src/main/java/org/apache/paimon/io/RecordLevelExpire.java, paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeReaders.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ChangelogMergeTreeRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FullChangelogMergeTreeCompactRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeTreeCompactRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactRewriter.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java, paimon-core/src/test/java/org/apache/paimon/catalog/PrimaryKeyTableTestBase.java, paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireTest.java
In compaction, you can configure record-Level expire time to expire records, you should configure:
1. `'record-level.expire-time'`: time retain for records.
2. `'record-level.time-field'`: time field for record level expire, it should be a seconds INT.
Expiration happens in compaction, and there is no strong guarantee to expire records in time.
=> [core] Introduce record-level expire time

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/RowLevelOp.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DeleteFromTableTest.scala
Just like DELETE append table, we can DELETE compacted partial-update & agg & first-row table using COPY ON WRITE mode too.
=> [spark] Delete supports all merge engines

docs/layouts/shortcodes/generated/flink_connector_configuration.html, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTablesCompactorSink.java
Introduce new parameters to control whether the committer operator and writer operator are chained together
Linked issue: close #3232
=> [Flink] Introduce new parameters to control whether the committer operator and writer operator are chained together

docs/content/concepts/basic-concepts.md
Add some descriptions about data writing.
=> Update basic-concepts.md to add some descriptions about data writing

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/RichEventParser.java
… a schema change.
When the order of the same field varies, it is regarded as a schema change. Consequently, the Schema Evolution node receives a large volume of records, impacting performance.
So when comparing, it's necessary to ignore the ID of the field.
=> [cdc]Fixed When the order of the same field differs, it is considered a schema change.

docs/config.toml
After:
Only show first 5 versions in `front page`, for the current config`range $docs := first 5 .Site.Params.PreviousDocs`
In `all versions` page we can see all version's docs:
=> [doc] Add more previous version docs

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonHiveTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/SparkVersionSupport.scala
Fix: drop database cascase when database is not empy with SparkGenericCatalog
We need to use SparkCatalog to drop tables instead of letting NamespaceCatalog(SessionCatalog) handle it, otherwrise will throw this exception:
```
Caused by: MetaException(message:Failed to load storage handler:  Error in loading storage handler.org.apache.paimon.hive.PaimonStorageHandler)
at org.apache.hadoop.hive.ql.metadata.Hive$7.getHook(Hive.java:3599)
at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getHook(HiveMetaStoreClient.java:1786)
at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.dropTable(HiveMetaStoreClient.java:1087)
at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.dropTable(HiveMetaStoreClient.java:1008)
at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.dropDatabase(Hiv …
```
=> [spark] Fix drop database cascade when database is not empy with SparkGenericCatalog

paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeWriter.java, paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/utils/RecordWriter.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java, paimon-flink/paimon-flink-cdc/src/test/resources/mysql/sync_table_setup.sql
Currently, `AbstractFileStoreWrite#createWriterContainer` get max sequence number from restored data files. But if write-only is true, the restored data files are empty, which leads to a wrong sequence number.
=> [core] FileStoreWrite.State should get max sequence number from RecordWriter instead of from data files

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunctionBase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunctionBaseTest.java
schemaCompatible checks support timestamp types
=> [cdc]Add more checker for the timestamp type.

docs/content/spark/procedures.md, paimon-core/src/main/java/org/apache/paimon/migrate/Migrator.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/migrate/HiveMigrator.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/MigrateTableProcedure.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/MigrateTableProcedureTest.scala
Currently MigrateTableProcedure  only support migrate table with origin name，but some conditions user not want to drop origin table in hms or want to rename a new target table name，this pr is aim to support it.
=> [spark] MigrateTableProcedure support keep origin table and rename target paimon table

docs/content/flink/sql-write.md, docs/layouts/shortcodes/generated/flink_connector_configuration.html, paimon-common/src/main/java/org/apache/paimon/utils/IOUtils.java, paimon-core/src/main/java/org/apache/paimon/partition/PartitionTimeExtractor.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/Committer.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CompactorSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkWriteSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTablesCompactorSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCommitter.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreMultiCommitter.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/UnawareBucketCompactionSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/AddDonePartitionAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionMarkDone.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionMarkDoneAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionMarkDoneTrigger.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/SuccessFile.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/SuccessFileMarkDoneAction.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/StoreMultiCommitterTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/AddDonePartitionActionTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/PartitionMarkDoneTriggerTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/SuccessFileMarkDoneActionTest.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
This PR is intended to support a mechanism for marking a partition as finished and subsequently pulling up offline scheduling jobs.
Unlike Flink's Filesystem (which came from my younger self), this uses a "mark partition as finished if there is no new data for a certain amount of time" approach, which is currently only supported for system time, but can be extended to include a watermark approach.
Another question is how to mark the end of the partition, there are several options:
1. create a xx.done partition
2. create a _SUCCESS file
3. or other
For partitioned tables, each partition may need to be scheduled to trigger downstream batch computation. Therefore,
it is necessary to choose this timing to indicate that it is ready for scheduling and to minimize the amount of data
drift during …
=> [flink] Introduce partition mark done

docs/content/flink/procedures.md, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/ExpireSnapshotsProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ExpireSnapshotsProcedure.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/ExpireSnapshotsProcedureITCase.java
Linked issue: close #3330
Support specifying `retain_min`, `older_than` and `max_deletes` for Flink's `expire_snapshots procedure`.
Add `ExpireSnapshotsProcedureITCase`
Signature of the `expire_snapshots` procedure for Flink 1.19 and later is changed. `expire_snapshot(table, retain_max)` with positioned arguments is no longer supported. User needs to either use named arguments, or use the full signature `expire_snapshot(table, retain_max, retain_min, older_than, max_deletes)` and pass null for arguments not needed. Flink 1.18 and earlier versions are not affected.
The Flink Procedure page is been updated.
=> [Flink] `expire_snapshots` procedure supports `retain_min`, `older_than` and `max_deletes`

paimon-common/src/main/java/org/apache/paimon/predicate/LeafPredicateExtractor.java, paimon-core/src/main/java/org/apache/paimon/table/system/FilesTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/SnapshotsTable.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
1. Extract a class: LeafPredicateExtractor
2. Handle push down for snapshots table.
=> [core] Optimize snapshots table when specific snapshot id

paimon-core/src/main/java/org/apache/paimon/mergetree/MergeSorter.java, paimon-core/src/main/java/org/apache/paimon/operation/MergeFileSplitRead.java, paimon-core/src/main/java/org/apache/paimon/operation/RawFileSplitRead.java, paimon-core/src/main/java/org/apache/paimon/operation/SplitRead.java, paimon-core/src/main/java/org/apache/paimon/table/source/KeyValueTableRead.java, paimon-core/src/main/java/org/apache/paimon/table/source/splitread/IncrementalChangelogReadProvider.java, paimon-core/src/main/java/org/apache/paimon/table/source/splitread/IncrementalDiffReadProvider.java, paimon-core/src/main/java/org/apache/paimon/table/source/splitread/IncrementalDiffSplitRead.java, paimon-core/src/main/java/org/apache/paimon/table/source/splitread/MergeFileSplitReadProvider.java, paimon-core/src/main/java/org/apache/paimon/table/source/splitread/RawFileSplitReadProvider.java, paimon-core/src/main/java/org/apache/paimon/table/source/splitread/SplitReadProvider.java, paimon-core/src/test/java/org/apache/paimon/operation/MergeFileSplitReadTest.java, paimon-core/src/test/java/org/apache/paimon/table/IncrementalTableTest.java
=> [core] Incremental-between tags should deduplicate records

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTestBase.scala
Becase `SparkGenericCatalog` doest not implement `ViewCatalog` currently, `listTables` will return views too, so dropTable(view) will raise exception, we need to fallback to use `sessionCatalog` to drop
=> [spark] Fix drop database cascade when database with view with SparkGenericCatalog

paimon-core/src/main/java/org/apache/paimon/table/system/TagsTable.java, paimon-core/src/test/java/org/apache/paimon/table/system/TagsTableTest.java
Revert #2754
`TagsTableTest.testTagBranchesTable` is an unstable case where the order of branches is uncertain.
The underlying reason is that we already have branches table, which should not be recalculated in the Tags table, forming redundant information.
=> [core] Revert branchs in TagsTable

paimon-core/src/main/java/org/apache/paimon/index/BucketAssigner.java, paimon-core/src/main/java/org/apache/paimon/index/HashBucketAssigner.java, paimon-core/src/main/java/org/apache/paimon/index/SimpleHashBucketAssigner.java, paimon-core/src/test/java/org/apache/paimon/index/SimpleHashBucketAssignerTest.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkRow.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkTableWrite.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/BucketProcessor.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala
There are currently two shuffles, which can be optimized into one.
=> [spark] Optimize Spark write newly dynamic bucket table

docs/content/spark/quick-start.md, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkInternalRow.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkTypeUtils.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonPartitionManagement.scala, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkInternalRowTest.java, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadITCase.java, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkTypeTest.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonPartitionManagementTest.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/SparkVersionSupport.scala
In the current version, if user specify the col type to `char` or `varchar` with spark, the type is just `string`, and the query results do not conform to `char`. This PR will fix it. 
e.g.  
define char(4)
`select("a")` should return `"a   "`
=> [spark] Support varchar/char type

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/migrate/HiveMigrator.java
Linked issue: https://github.com/apache/paimon/issues/3380
Fix HiveMigrator hive api version compatible issue
=> [spark] Fix HiveMigrator hive api version compatible issue

docs/layouts/shortcodes/generated/flink_connector_configuration.html, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FullCacheLookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupStreamingReader.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/NoPrimaryKeyLookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PrimaryKeyLookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/SecondaryIndexLookupTable.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/FileStoreLookupFunctionTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/LookupTableTest.java
Linked issue: close #3295 
This PR aims to add async refresh of lookup table to avoid lag in job when the lookup operator is blocked by refresh data from table store
1. Updated existing test for refresh async in FileStoreLookupFunctionTest
2. Added LookupTableTest#testPKLookupTableRefreshAsync for refresh async
no
no
=> [flink][lookup] Support async refresh of lookup table

docs/content/primary-key-table/merge-engine.md, docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/AggregateMergeFunction.java, paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunctionTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/AggregateMergeFunctionTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java
Fix update null value for partial update with sequence-group
Linked issue: close #3373
1. Added test unit PartialUpdateMergeFunctionTest#testSequenceGroupDefaultAggFunc
2. Added test unit PartialUpdateITCase#testSequenceGroupWithDefaultAggFunc and PartialUpdateITCase#testPartialUpdateWithDefaultAndFieldAggregation
no
no
=> [core] Support default aggregate function for partial update and aggregate merge function

paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-common/src/main/java/org/apache/paimon/options/ExpireConfig.java, paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java, paimon-core/src/main/java/org/apache/paimon/FileStore.java, paimon-core/src/main/java/org/apache/paimon/operation/ChangelogDeletion.java, paimon-core/src/main/java/org/apache/paimon/operation/FileDeletionBase.java, paimon-core/src/main/java/org/apache/paimon/operation/SnapshotDeletion.java, paimon-core/src/main/java/org/apache/paimon/operation/TagDeletion.java, paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedFileStore.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/ExpireChangelogImpl.java, paimon-core/src/main/java/org/apache/paimon/table/ExpireSnapshots.java, paimon-core/src/main/java/org/apache/paimon/table/ExpireSnapshotsImpl.java, paimon-core/src/test/java/org/apache/paimon/TestFileStore.java, paimon-core/src/test/java/org/apache/paimon/operation/ExpireSnapshotsTest.java, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/ExpireSnapshotsProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ExpireSnapshotsProcedure.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ExpireSnapshotsProcedure.java
This PR is the second step of https://github.com/apache/paimon/pull/3178 to simply the clean up logic of snapshot and changelog
=> [core] Introduce ChangelogDeletion to Expiration

paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/ReadonlyTable.java, paimon-core/src/main/java/org/apache/paimon/table/Table.java, paimon-core/src/main/java/org/apache/paimon/utils/BranchManager.java, paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java, paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ReplaceBranchProcedure.java, paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/BranchActionITCase.java
Linked issue: close https://github.com/apache/incubator-paimon/issues/2153
BranchActionITCase.testReplaceBranchToTargetBranch
=> [Feature]Implement replace branch in BranchManager

paimon-common/src/main/java/org/apache/paimon/sort/hilbert/HilbertIndexer.java, paimon-spark/paimon-spark-common/pom.xml, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/sort/SparkHilbertUDF.java
SparkHilbertUDF hilbertCurvePosBytes classnotfound fix，due to this changes https://github.com/apache/paimon/pull/3251 
Linked issue: https://github.com/apache/paimon/issues/3416
before fix
after fix
=> [spark] SparkHilbertUDF hilbertCurvePosBytes classnotfound fix

paimon-common/src/main/java/org/apache/paimon/predicate/NullFalseLeafBinaryFunction.java, paimon-common/src/main/java/org/apache/paimon/predicate/PredicateBuilder.java, paimon-common/src/main/java/org/apache/paimon/utils/RowDataToObjectArrayConverter.java, paimon-core/src/main/java/org/apache/paimon/partition/PartitionPredicate.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java, paimon-core/src/test/java/org/apache/paimon/operation/AppendOnlyFileStoreWriteTest.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
=> [core] [bug] Partition should not be filtered when manifest file predicate and file itself all min/max is null

paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/utils/HiveUtils.java
=> [hive]fix load default hadoop config

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ChangelogMergeTreeRewriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactRewriter.java, paimon-core/src/test/java/org/apache/paimon/mergetree/ChangelogMergeTreeRewriterTest.java
[core] close files in `CompactRewriter` to avoid file leaks.
Linked issue: close #3408 
- org.apache.paimon.mergetree.ChangelogMergeTreeRewriterTest#testRewriteFailAndCleanupFiles
- org.apache.paimon.mergetree.ChangelogMergeTreeRewriterTest#testRewriteSuccess
No
No
=> [core] close files in CompactRewriter to avoid file leaks.

paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/TableReadBenchmark.java, paimon-common/src/main/java/org/apache/paimon/fs/VectoredReadUtils.java, paimon-common/src/main/java/org/apache/paimon/fs/VectoredReadable.java, paimon-common/src/test/java/org/apache/paimon/fs/VectoredReadUtilsTest.java
For continuous disk data, if multiple threads are started to read, the performance will be worse than sequential reading.
So the strategy has been adjusted here to ensure that continuous data is read by a single thread as much as possible.
=> [core] Adjust VectoredReadable to better read performance

paimon-common/src/main/java/org/apache/paimon/fs/VectoredReadUtils.java
Fix the flaky test `VectoredReadUtilsTest.testRandom()`
=> [core] FallbackToReadSequence when readable instanceof SeekableInputStream

paimon-format/pom.xml, paimon-format/src/main/resources/META-INF/NOTICE
| LIBRARY                            | VULNERABILITY ID | SEVERITY | INSTALLED VERSION | FIXED VERSION               | TITLE                                                                 |
|------------------------------------|------------------|----------|-------------------|-----------------------------|-----------------------------------------------------------------------|
| com.google.protobuf:protobuf-java  | CVE-2022-3171    | HIGH     | 3.17.3            | 3.16.3, 3.19.6, 3.20.3, 3.21.7 | protobuf-java: timeout in parser leads to DoS <br> -->[avd.aquasec.com/nvd/cve-2022-3171](https://avd.aquasec.com/nvd/cve-2022-3171) |
|                                    | CVE-2022-3509    | HIGH     |                   | 3.21.7, 3.20.3, 3.19.6, 3.16.3 | Protobuf Java …
=> [SECURITY] Upgrade protobuf-java and commons-compress version to fix CVE

paimon-common/src/main/java/org/apache/paimon/data/BinaryWriter.java, paimon-core/src/main/java/org/apache/paimon/migrate/FileMetaUtils.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/migrate/HiveMigrator.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/MigrateTableProcedure.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/MigrateTableProcedureTest.scala
Fix migrate hive partitioned table with null partition
=> [core] Fix migrate hive partitioned table with null partition

paimon-core/src/test/java/org/apache/paimon/utils/TraceableFileIO.java
Fix flaky test testLookupDynamicPartition, https://github.com/apache/paimon/actions/runs/9305326341/job/25611978740
=> [test] Fix flaky test testLookupDynamicPartition

docs/content/flink/sql-write.md, docs/layouts/shortcodes/generated/flink_connector_configuration.html, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/SortCompactAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/shuffle/RangeShuffle.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkTableSinkBase.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/HilbertSorter.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/OrderSorter.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/SortUtils.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/TableSortInfo.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/TableSorter.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/ZorderSorter.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/RangePartitionAndSortForUnawareBucketTableITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sorter/TableSortInfoTest.java
Linked issue: close https://github.com/apache/paimon/issues/3385
Introduce Range Partition And Sort in Append Scalable Table Batch Writing for Flink.
1. Add `TableSortInfoTest` for the `TableSortInfo`.
2. Add `RangePartitionAndSortForUnawareBucketTableITCase`.
no
Yes. The doc of FlinkConnectorOptions has been updated.
=> [flink] Introduce Range Partition And Sort in Append Scalable Table Batch Writing for Flink

paimon-core/src/main/java/org/apache/paimon/table/source/ReadBuilder.java, paimon-core/src/main/java/org/apache/paimon/table/source/ReadBuilderImpl.java, paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FullCacheLookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupStreamingReader.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PrimaryKeyPartialLookupTable.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/LookupTableTest.java
Modifies Paimon's FileStoreLookupFunction to cache only the required buckets during lookup joins.
no
=> [flink] Support FileStoreLookupFunction to only cache required buckets

docs/content/primary-key-table/merge-engine.md, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-common/src/main/java/org/apache/paimon/lookup/LookupStrategy.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java, paimon-core/src/main/java/org/apache/paimon/table/source/DataTableStreamScan.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapperTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FirstRowITCase.java
We should support this. Just like deletion vectors mode, no need to bind lookup changelog producer.
=> [core] Fisrt row merge engine supports none changelog producer

LICENSE, paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/TableReadBenchmark.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetInputFile.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetInputStream.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetUtil.java, paimon-format/src/main/java/org/apache/parquet/hadoop/ParquetFileReader.java, paimon-format/src/main/java/org/apache/parquet/hadoop/ParquetWriter.java
Next step of https://github.com/apache/incubator-paimon/pull/3369
=> [parquet] Parquet use vector IO

paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/BytesColumnReader.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/FixedLenBytesColumnReader.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ParquetDictionary.java
Avoid copying byte arrays every time.
=> [parquet] Optimize parquet to use getBytesUnsafe for dictionary

paimon-core/src/main/java/org/apache/paimon/io/KeyValueDataFileRecordReader.java, paimon-core/src/main/java/org/apache/paimon/io/KeyValueFileReaderFactory.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/DeduplicateMergeFunction.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FirstRowMergeFunction.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java, paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyTableUtils.java, paimon-core/src/test/java/org/apache/paimon/mergetree/SortBufferWriteBufferTestBase.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapperTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/SortMergeReaderTestBase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java
To maintain compatibility with 0.7, #3139 put `ignoreDelete` in reader, causing that UPDATE_BEFORE cannot be read in streaming reading. So the `ignore-delete` have to be put into merge engines.
=> [core] Fix that cannot read UPDATE_BEFORE of ignore-delete table

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/TableSortInfo.java, tools/maven/checkstyle.xml
Fix the illegal usage of flink.shaded.guava31 dependency in TableSortInfo
no
no
no
=> [flink] Fix the illegal usage of flink.shaded.guava31 dependency in TableSortInfo

paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/source/AppendOnlySplitGenerator.java, paimon-core/src/main/java/org/apache/paimon/table/source/DataTableBatchScan.java, paimon-core/src/main/java/org/apache/paimon/table/source/DataTableStreamScan.java, paimon-core/src/main/java/org/apache/paimon/table/source/MergeTreeSplitGenerator.java, paimon-core/src/main/java/org/apache/paimon/table/source/SplitGenerator.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReader.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java, paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/ReadOptimizedTable.java, paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java, paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
dv mode or first row mode, we should shuffle files because we don't need to merge files.
=> [core] ReadBuilder.withShard should shuffle files for dv mode and first row

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java, paimon-core/src/main/java/org/apache/paimon/table/sink/BatchWriteBuilderImpl.java, paimon-core/src/main/java/org/apache/paimon/table/sink/StreamWriteBuilderImpl.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSink.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSinkTest.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DropPartitionAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/DropPartitionProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CombinedTableCompactorSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/DynamicBucketCompactSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/DynamicBucketSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/SupportsRowLevelOperationFlinkTableSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalDynamicBucketSink.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FileStoreITCase.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java
In our business scenario, the full data are written to the paimon table through bound stream job. Using of bound stream job instead of batch job is to enable downstream build index faster and further reduce the inc data of catchup. When bound stream job failover, the random commitUser will recover from Flink state, this is no problem. 
But In our business scenario, we use Apache Airflow schedule Flink jobs. A Airflow node will fail due to lots of reasons. Then user clear the airflow node, a new Flink bound stream job will start with no state, so a new CommitUser will be generated. This will affect downstream judgment on whether to use a new build index processor.
So I submit this pr, we can assign a fixed commitUser to an Airflow node.
Add ut
=> [core] support custom commitUser

paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java, paimon-core/src/test/java/org/apache/paimon/table/sink/TableWriteTest.java
Currently in `AbstractFileStoreWrite`, we use `writerContainer.lastModifiedCommitIdentifier <= latestCommittedIdentifier` to check that there is no more record waiting to be committed for this writer.
However, each commit identifier may have multiple snapshots (for example, one APPEND snapshot and one COMPACT snapshot). If the commit is slow, writer might be closed and re-opened between the APPEND snapshot and the COMPACT snapshot, thus causing commit conflicts in the future.
To ensure that all snapshots of this identifier are committed, the correct condition should be `writerContainer.lastModifiedCommitIdentifier < latestCommittedIdentifier`.
* `TableWriteTest#testWaitAllSnapshotsOfSpecificIdentifier`
Not affected.
=> [core] Close writer after commit identifier of snapshot is strictly larger than last modified identifier

paimon-core/src/main/java/org/apache/paimon/table/source/DataTableBatchScan.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/ScanHelper.scala
#3226 Add `rawConvertible` in `DataSplit`, and remove the lazy loading mechanism.
We should use `rawConvertible` to determine whether needs to convertToRawFiles to preventing double convert
=> [core] Use rawConvertible to determine whether needs to convertToRawFiles

paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java, paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java, paimon-core/src/main/java/org/apache/paimon/utils/UserDefinedSeqComparator.java, paimon-core/src/test/java/org/apache/paimon/mergetree/SortBufferWriteBufferTestBase.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunctionTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java
Linked issue: close #3372 
Use `UserDefinedSeqComparator` to support multiple fields in sequence-group
Added UT:
- PartialUpdateMergeFunctionTest.testMultiSequenceFields
- PartialUpdateMergeFunctionTest.testMultiSequenceFieldsDefaultAggFunc
- PartialUpdateMergeFunctionTest.testMultiSequenceFieldsDefinedNoField
- PartialUpdateMergeFunctionTest.testMultiSequenceFieldsRepeatDefine
- PartialUpdateMergeFunctionTest.testMultiSequenceFieldsAdjustProjectionRepeatProject
- PartialUpdateMergeFunctionTest.testMultiSequenceFieldsAdjustProjectionProject
- PartialUpdateMergeFunctionTest.testMultiSequenceFieldsAdjustProjectionAllFieldsProject
- PartialUpdateMergeFunctionTest.testMultiSequenceFieldsFirstValue
- PartialUpdateMergeFunctionTest.testMultiSequenceFieldsPartialUpdateWithAggregation
- …
=> [Feature] Support multiple fields in sequence-group

paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/FixedLenBytesColumnReader.java
Optimize parquet to use getBytesUnsafe in FixedLenBytesColumnReader
=> [parquet] Optimize parquet to use getBytesUnsafe in FixedLenBytesColumnReader

paimon-spark/paimon-spark-3.1/pom.xml, paimon-spark/paimon-spark-3.3/pom.xml, paimon-spark/paimon-spark-3.4/pom.xml, paimon-spark/paimon-spark-3.5/pom.xml, paimon-spark/paimon-spark-common/pom.xml
For test failure in IDEA
```
An exception or error caused a run to abort: COMPRESSION_ZSTD_LEVEL 
java.lang.NoSuchFieldError: COMPRESSION_ZSTD_LEVEL
at org.apache.paimon.format.orc.OrcFileFormat.getOrcProperties(OrcFileFormat.java:153)
at org.apache.paimon.format.orc.OrcFileFormat.<init>(OrcFileFormat.java:74)
at org.apache.paimon.format.orc.OrcFileFormatFactory.create(OrcFileFormatFactory.java:35)
at org.apache.paimon.format.orc.OrcFileFormatFactory.create(OrcFileFormatFactory.java:24)
at org.apache.paimon.format.FileFormat.fromIdentifier(FileFormat.java:99)
at org.apache.paimon.format.FileFormat.fromIdentifier(FileFormat.java:84)
at org.apache.paimon.format.FileFormat.fromIdentifier(FileFormat.java:79)
at org.apache.paimon.schema.SchemaValidation.validateTableSchema(SchemaValidation.java …
```
=> [spark] Exclude orc-core from spark-core_2.12 dependency

docs/content/primary-key-table/deletion-vectors.md, docs/layouts/shortcodes/generated/core_configuration.html, docs/layouts/shortcodes/generated/flink_connector_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java, paimon-core/src/main/java/org/apache/paimon/compact/CompactDeletionFile.java, paimon-core/src/main/java/org/apache/paimon/compact/CompactResult.java, paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVectorsMaintainer.java, paimon-core/src/main/java/org/apache/paimon/index/IndexFileHandler.java, paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeWriter.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactManager.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactTask.java, paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/utils/CommitIncrement.java, paimon-core/src/main/java/org/apache/paimon/utils/ObjectsFile.java, paimon-core/src/test/java/org/apache/paimon/TestAppendFileStore.java, paimon-core/src/test/java/org/apache/paimon/deletionvectors/DeletionVectorsMaintainerTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTestBase.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/MergeTreeCompactManagerTest.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTablesStoreCompactOperator.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala
In the previous implementation, due to concurrent thread safety issues, asynchronous execution could not be enabled for the deletion vectors mode, as there were also an asynchronous compaction thread to write deletion vectors when the main thread materialize them.
We can avoid this situation by handing over the materialization of the deletion vectors to the asynchronous compaction thread. After each compaction is completed, we actively materialize the deletion vectors as a deletion file.
`PrimaryKeyFileStoreTableITCase` already coverred this.
`/primary-key-table/deletion-vectors` modified.
=> [core] Deletion Vectors mode supports lookup async

paimon-common/src/main/resources/META-INF/NOTICE, pom.xml
Upgrade ANTLR from 4.8 to 4.9.3 for the reasons:
1. IDEA spark test warning for spark upgrade antlr from 4.8 to 4.9.3 since spark3.4
```
ANTLR Tool version 4.9.3 used for code generation does not match the current runtime version 4.8ANTLR Tool version 4.9.3 used for code generation does not match the current runtime version 4.8
```
Note: this warning will exist in paimon-spark3.3- after this PR, because I think just follow the newest version is ok, don't want to add mutl versions for this
2. github CI warning for antlr4-maven-plugin:4.8 not thread-safe
```
Warning:  *****************************************************************
Warning:  * Your build is requesting parallel execution, but this         *
Warning:  * project contains the following plugin(s) that have goals not  *
Warning: …
```
=> [pom] Bump ANTLR from 4.8 to 4.9.3

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala
To remove redundant projects requires the project and its child have the same output with order.
So we adjust here.
=> [spark] adjust the field order of readSchema

paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexPredicate.java, paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexReader.java, paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexResult.java, paimon-common/src/main/java/org/apache/paimon/fileindex/bloomfilter/BloomFilterFileIndex.java, paimon-common/src/main/java/org/apache/paimon/fileindex/empty/EmptyFileIndexReader.java, paimon-common/src/test/java/org/apache/paimon/fileindex/bloomfilter/BloomFilterFileIndexTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/UnawareBucketAppendOnlyTableITCase.java
`FileIndexPredicate` return `FileIndexResult`, not `Boolean` any more.
For example, bit map index:
SQL:
```
SELECT * FROM <TABLE> WHERE a1 = 1 and a2 = 2
```
Bitmap index for a1 returns rows 1,2,3
Bitmap index for a2 returns rows 4,5,6.
Then this file could be skipped.
SQL
```
SELECT * FROM <TABLE> WHERE a1=1 or a1=2 or a1=3
```
Bitmap index for a1=1 returns rows null
Bitmap index for a1=2 return rows 1,2,3
Bitmap index for a1=3 return rows 3,4,5
Then this file should be found, and rows should be 1,2,3,4,5 (push down not implement yet)
Generally, file index implement should handle method 'or', whatever the IndexResult is produced by the file index type itself, or other kind of file index.
=> [core] File index result should be able to process and/or.

paimon-common/src/main/java/org/apache/paimon/types/RowType.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FullCacheLookupTable.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/LookupTableTest.java
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
at org.apache.paimon.utils.ProjectedRow.isNullAt(ProjectedRow.java:80)
at RecordComparator$52.compare(Unknown Source)
at org.apache.paimon.utils.UserDefinedSeqComparator.compare(UserDefinedSeqComparator.java:49)
at org.apache.paimon.utils.UserDefinedSeqComparator.compare(UserDefinedSeqComparator.java:32)
at org.apache.paimon.flink.lookup.SecondaryIndexLookupTable.refresh(SecondaryIndexLookupTable.java:88)
at org.apache.paimon.flink.lookup.FullCacheLookupTable.refresh(FullCacheLookupTable.java:154)
at org.apache.paimon.flink.lookup.FileStoreLookupFunction.refresh(FileStoreLookupFunction.java:299)
at org.apache.paimon.flink.lookup.FileStoreLookupFunction.checkRefresh(FileStoreLookupFunction.java:288)
at …
```
=> [flink] Fix lookup IndexOutOfBounds for sequence defined with projection

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/BatchWriteGeneratorTagOperatorTest.java
=> [test] fix flaky test for testBatchWriteGeneratorTag.

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldCountAgg.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregatorTest.java
FieldCountAgg support FieldType with numberic field type， follow up https://github.com/apache/paimon/pull/3536
=> [core] Support Numberic type to FieldCountAgg

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/CdcActionCommonUtils.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/MessageQueueSchemaUtils.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncDatabaseActionBase.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncJobHandler.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncTableActionBase.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/DataFormat.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/RecordParser.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/RecordParserFactory.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/canal/CanalRecordParser.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/debezium/DebeziumRecordParser.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/json/JsonRecordParser.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/maxwell/MaxwellRecordParser.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/ogg/OggRecordParser.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBRecordParser.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/strategy/Mongo4VersionStrategy.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlRecordParser.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/postgres/PostgresRecordParser.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CaseSensitiveUtils.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcMultiplexRecord.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecord.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcSinkBuilder.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/NewTableSchemaBuilder.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunctionBase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncDatabaseActionITCase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java, paimon-flink/paimon-flink-cdc/src/test/resources/kafka/canal/database/case-insensitive/canal-data-1.txt, paimon-flink/paimon-flink-cdc/src/test/resources/mysql/sync_database_setup.sql
Currently, all record parsers have to handle `case-insensitive`. This PR want to move it to a separate operator.
Note that #2485 has already considered handle `case-insensitive` with computed columns, so this PR won't cause problems to computed columns.
1. there are already some test cases for table sync with `case-insensitive`.
2. add `MySqlSyncDatabaseActionITCase#testIgnoreCaseCombined`
3. enhance `KafkaCanalSyncDatabaseActionITCase#testCaseInsensitive`
=> [cdc] Handle case-insensitive in separate operator instead of record parsers

docs/content/concepts/specification.md, docs/content/flink/procedures.md, paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexFormat.java, paimon-core/src/main/java/org/apache/paimon/io/DataFileMeta.java, paimon-core/src/main/java/org/apache/paimon/io/DataFilePathFactory.java, paimon-core/src/main/java/org/apache/paimon/io/FileIndexWriter.java, paimon-core/src/main/java/org/apache/paimon/manifest/ManifestEntrySerializer.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/FileIndexProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommittableTypeInfo.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CompactionTaskTypeInfo.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FileIndexSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTableCommittableTypeInfo.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/NoneCopyVersionedSerializerTypeSerializerProxy.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FileIndexScanSource.java, paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/FileIndexProcedureITCase.java
Add / Drop / Modify file index for existing tables. 
This action is strictly idempotent.
Trigger this procedure will:
1. If `ManifestFile` does not contain the target file index column and type, add it
2. If `ManifestFile` contains the index column and type, but table options don't, drop it
3. If `ManifestFile` contains the index column and type, and table options also contain, leave it
Three options:
1. Table name
2. Partition filter
sql
```
CALL sys.file_index_rewrite('default.T'); -- just rewrite all the table
CALL sys.file_index_rewrite('default.T', 'pt=a'); --add partition filter
```
=> [flink] Introduce file index rewriter procedure

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FileStoreSourceReader.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkRecordsWithSplitIds.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/ReadOperator.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FlinkRecordsWithSplitIdsTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/SourceMetricsITCase.java
FLIP-27 source has a default implementation of `numRecordsIn` metrics. However this metrics only count the number of batches Paimon source produces, not the number of records.
This PR fixes the metrics by increasing the counter before emitting data to source output.
* `SourceMetricsITCase#testNumRecordsIn`
No API changes.
=> [flink] Fix source numRecordsIn metrics

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FullCacheLookupTable.java
Close refresh executor before lookup table is closed to avoid writing data into invalid directory
no
no
=> [flink] Close refresh executor before lookup table is closed

docs/content/flink/cdc-ingestion/kafka-cdc.md, docs/content/flink/cdc-ingestion/mongo-cdc.md, docs/content/flink/cdc-ingestion/mysql-cdc.md, docs/content/flink/cdc-ingestion/pulsar-cdc.md, docs/layouts/shortcodes/generated/kafka_sync_database.html, docs/layouts/shortcodes/generated/mongodb_sync_database.html, docs/layouts/shortcodes/generated/mysql_sync_database.html, docs/layouts/shortcodes/generated/pulsar_sync_database.html, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/CdcActionCommonUtils.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/MessageQueueSyncTableActionBase.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncDatabaseActionBase.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncDatabaseActionFactoryBase.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncTableActionBase.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/NewTableSchemaBuilder.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/CdcActionITCaseBase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncDatabaseActionITCase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/postgres/PostgresSyncTableActionITCase.java, paimon-flink/paimon-flink-cdc/src/test/resources/kafka/canal/database/specify-keys/canal-data-1.txt, paimon-flink/paimon-flink-cdc/src/test/resources/mysql/sync_database_setup.sql
Specified keys if not exist in source table, we will try to set keys from source table or doesn't set keys.
`MySqlSyncDatabaseActionITCase#testSpecifyKeys`
`KafkaCanalSyncDatabaseActionITCase#testSpecifyKeys`
database sync supports:
--primary-keys
--partition-keys
=> [cdc] Database sync supports specify partition keys and primary keys

docs/layouts/shortcodes/generated/flink_connector_configuration.html, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/Committer.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCommitter.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreMultiCommitter.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionMarkDone.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionMarkDoneTrigger.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkBatchJobPartitionMarkdoneITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/PartitionMarkDoneTriggerTest.java
Base on https://github.com/apache/paimon/pull/3317
This PR is intended to support a mechanism for marking a partition as finished and subsequently pulling up offline scheduling jobs with flink batch job.
=> [flink] Introduce partition mark done with batch

paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTest.scala, paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTest.scala, paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTest.scala, paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTest.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTestBase.scala
SparkSql uts use version check instead of interfaces avoid multiple methods to control test logic
=> [spark] SparkSql UT use version check instead of interfaces

paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java, paimon-core/src/main/java/org/apache/paimon/operation/PartitionExpire.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ExpirePartitionsProcedure.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ExpirePartitionsProcedure.java
Linked issue: close [When metastore.partitioned-table is enabled, the partition information in hms will not be deleted after the expired partition is automatically deleted.](https://github.com/apache/paimon/issues/3514)
=> [core] Fix the expired partition sync to metastore

paimon-format/pom.xml
As far as I know, `FileStoreLookupFunctionTest` will throws `NoSuchMethodError` in IDEA currently.
=> [test] Exclude orc dependency to avoid test fails in IDEA

paimon-core/src/main/java/org/apache/paimon/manifest/FileEntry.java, paimon-core/src/main/java/org/apache/paimon/manifest/ManifestFileMeta.java
Linked issue: close https://github.com/apache/paimon/issues/3590
When submitting a snapshot triggers a full compaction of the manifest file, we hope to reduce the usage of the taskManager heap memory.
Before the comparison test, fine-grained-resource-management has been enabled，The committer operator runs in a separate task manager.
Heap memory usage before optimization：
Heap memory usage after optimization：
=> [core]Committer operator memory optimization

paimon-core/src/main/java/org/apache/paimon/operation/PartitionExpire.java
PartitionExpire drop partition atomicity when sync to hms.
CREATE TABLE bdsp_test.paimon_mi_24(
user_id STRING COMMENT '任务用到的库',
used_table STRING COMMENT '任务用到的表',
day STRING COMMENT '按天进行分区'
)USING paimon
PARTITIONED BY (day);
insert into bdsp_test.paimon_mi_24
select 'a', 'a_table', '2024-04-22';
insert into bdsp_test.paimon_mi_24
select 'b', 'a_table', '2024-09-22';
select * from bdsp_test.paimon_mi_24 limit 10;
CALL sys.expire_partitions(table => 'bdsp_test.paimon_mi_24', expiration_time => '1 d', timestamp_formatter => 'yyyy-MM-dd');
If hive version is low which cannot compatible with paimon（such as follow），hms sync would error but paimon drop partition is ok
Linked issue: https://github.com/apache/paimon/issues/3593
=> [core] PartitionExpire drop partitions consisitent with hms drop

paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CreateAndDeleteTagProcedureTest.scala
When call create_tag twice for the same snapshot of the same tag, the tag medata should update.
```sql
CALL sys.create_tag(table => 'default.T', tag => 'my_tag', snapshot => 10)
CALL sys.delete_tag(table => 'default.T', tag => 'my_tag', snapshot => 10, time_retained => '1d')
```
=> [core] update tag metadata for the same snapshot of the same tag

paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java, paimon-core/src/main/java/org/apache/paimon/manifest/FileEntry.java, paimon-core/src/main/java/org/apache/paimon/manifest/ManifestFileMeta.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java, paimon-core/src/main/java/org/apache/paimon/utils/ScanParallelExecutor.java, paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileMetaTest.java, paimon-core/src/test/java/org/apache/paimon/manifest/NoPartitionManifestFileMetaTest.java
This closes #3590
The `ScanParallelExecutor.parallelismBatchIterable` is designed to do parallelly execution with memory control, and the parallelism is controlled by `scan.manifest.parallelism`.
=> [core] Use parallelismBatchIterable to reduce memory cost

paimon-common/src/main/java/org/apache/paimon/predicate/PredicateBuilder.java, paimon-core/src/main/java/org/apache/paimon/io/KeyValueFileReaderFactory.java, paimon-core/src/main/java/org/apache/paimon/operation/RawFileSplitRead.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/MigrateTableProcedureTest.scala
Skip pushing down partition filter to file reader,  for the reasons:
- The partition filters have been applied to the splits generation, so pushing them to file has little effect.
- In some scenarios, the data file may not contain partition fields (such as migrate table, or our internal implementation that does not write partition fields). Then, if we push down the partition filter to the parquet reader, we will obtain no data. (The reason behind this is that parquet reader will treat all non-existent fields ​​as null, and if we push down `is not null`, reader will reject everything).
e.g. `SELECT * FROM migrate_tbl WHERE pt = 1` always return nothing
=> [core] Skip pushing down partition filter to file reader

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordUtils.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordKeyAndBucketExtractorTest.java
Linked issue: close #3570 
Why causes conflict :
`CdcRecordKeyAndBucketExtractor` use `CdcRecordUtils#projectAsInsert ` to project partition and keys genericRow , the `projectAsInsert` will ignore the empty value and eventually write null into GenericRow, but `RowDataKeyAndBucketExtractor` would be not ignore empty value and write empty value into GenericRow.
=> [cdc] Fix keyAndPartitions extractor result conflict if partitions or keys value is empty.

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcMultiplexRecord.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordSerializeITCase.java
=> [cdc] Fix richCdcMultiplexRecord cant be deserialized by kryoSerializer.

paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetReaderFactory.java, paimon-format/src/main/java/org/apache/parquet/hadoop/ParquetFileReader.java, paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetReadWriteTest.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DeletionVectorTest.scala
Parquet write & expose row index in block metadata since 1.12.3 (paimon use 1.13.1) see https://github.com/apache/parquet-java/pull/945, we can use it to computer row position when blocks are filtered.  When row index was not found in block metadata, skip applying filter in order to get the correct row position
- testReadRowPositionWithRandomFilter()
- test("Paimon deletionVector: select with format filter push down")
=> [core] Fix read row position with parquet when filter push down 

paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java, paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java
Optimize watermark check in SnapshotManager which can earlier quit reduce FileIO with Filesystem:
we can find many watermark in snapshot could be Long.MIN firstly which should not be compute.
Linked issue: close https://github.com/apache/paimon/issues/3637
=> [snapshot] Optimize watermark check in SnapshotManager which can reduce FileIO with Filesystem

docs/content/spark/procedures.md, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/BaseProcedure.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonSplitScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CompactProcedureTestBase.scala
Currently, spark sort compact will sort all the filtered data globally, and then write them by dynamic partition overwrite, which will lead to the following problems:
1. If the partition is not specified, data will be sorted globally, which is an unnecessary overhead
2. because it is a full range shuffle, small files are uncontrollable, for all reducers may contain all partitions
Therefore, this PR make a single partition as a sort compact group and then submit it to spark, a new conf ~`max_order_threads`~ `max_concurrent_jobs ` is introduced in sort compact procedure, the maximum number of concurrent job submissions, default is 15.
Test on 1T tpc-ds, sort compact web_sales on ws_bill_customer_sk, before 233s -> after 108s, and the target file size can be controled by …
=> [spark] Optimize sort compact procedure by submitting job by partition

paimon-core/src/main/java/org/apache/paimon/operation/metrics/ScanMetrics.java, paimon-core/src/main/java/org/apache/paimon/operation/metrics/ScanStats.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonMetrics.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/metric/SparkMetricRegistry.scala
Integrate paimon scan metrics into spark scan, so that we can get more information on the UI. Note: these new metrics are only available from Spark 3.4, because `reportDriverMetrics` was added in 3.4.
e.g.
```sql
select count(*) from inventory where inv_date_sk = 2450822
```
=> [spark] Integrate paimon scan metrics into spark scan

docs/content/flink/procedures.md, docs/content/maintenance/manage-snapshots.md, docs/content/spark/procedures.md, paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java, paimon-core/src/test/java/org/apache/paimon/operation/OrphanFilesCleanTest.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RemoveOrphanFilesAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionFactory.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RemoveOrphanFilesProcedure.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ActionITCaseBase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionITCase.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedure.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedureTest.scala
1. remove_orphan_files  support dry run，similar to the iceberg
2. The current remove_orphan_files (flink/spark) only outputs the number of deleted files after execution. I think it should output the orphan file path to be more transparent to users. as follows
remove_orphan_files procedures output in spark/flink procedures
remove_orphan_files  action output in flink action jar
=> [core]remove_orphan_files support dry run and optimize output

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonInputPartition.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonStatistics.scala
Avoid unnecessary get splits in spark scan
=> [spark] Avoid unnecessary get splits in spark scan

paimon-common/src/main/java/org/apache/paimon/fs/FileIO.java, paimon-common/src/test/java/org/apache/paimon/fs/FileIOTest.java, paimon-common/src/test/java/org/apache/paimon/fs/local/LocalFleIOTest.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java, paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java, paimon-core/src/main/java/org/apache/paimon/stats/StatsFile.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java, paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java, paimon-core/src/test/java/org/apache/paimon/catalog/CatalogFactoryTest.java, paimon-core/src/test/java/org/apache/paimon/operation/ExpireSnapshotsTest.java, paimon-core/src/test/java/org/apache/paimon/operation/OrphanFilesCleanTest.java, paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedureTest.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTestBase.scala
Old writeFileUtf8 should only be used by commit, others should throw exception when file existing. So this PR introduces a new writeFile.
=> [core] Should not ignore return value of FileIO.writeFileUtf8

paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVectorIndexFileMaintainer.java, paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVectorsMaintainer.java, paimon-core/src/main/java/org/apache/paimon/index/IndexFileHandler.java, paimon-core/src/main/java/org/apache/paimon/index/PartitionIndex.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java, paimon-core/src/test/java/org/apache/paimon/operation/FileStoreCommitTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/DynamicBucketTableITCase.java
Read deletion indexes at once to reduce file IO in splits generation
Test on tpcds q23a
before
```shell
grep FsStats spark-thrift-server.log | grep web_sales | wc
7437   81807 1770826
```
after
```shell
grep FsStats spark-thrift-server.log | grep web_sales | wc
67     737   16257
```
=> [core] Read deletion indexes at once to reduce file IO in splits generation

paimon-core/src/main/java/org/apache/paimon/table/system/BranchesTable.java
When we create a empty branch，created_from_tag and created_from_snapshot should be null.If isnullable is false and use sql 'select * form xxx$branches' query,it will throw a exception:
Caused by: org.apache.flink.table.api.TableException: Column 'created_from_tag' is NOT NULL, however, a null value is being written into it. You can set job configuration 'table.exec.sink.not-null-enforcer'='DROP' to suppress this exception and drop such records silently.
at org.apache.flink.table.runtime.operators.sink.ConstraintEnforcer.processNotNullConstraint(ConstraintEnforcer.java:261)
at org.apache.flink.table.runtime.operators.sink.ConstraintEnforcer.processElement(ConstraintEnforcer.java:241)
at org.apache.flink.streaming.runtime.tasks.ChainingOutput.pushToOperator(ChainingOutput.java:108)
at …
=> [flink] fix BranchesTable column created_from_tag and created_from_snapshot should be nullable.

paimon-core/src/main/java/org/apache/paimon/table/source/KeyValueTableRead.java, paimon-core/src/main/java/org/apache/paimon/table/source/splitread/RawFileSplitReadProvider.java
Old version: Previous versions of Paimon may retain -D records at the highest level for tables with changelog producer=lookup, while Paimon's old reader will filter -D once no matter what.
New version: Paimon will not retain -D data in the top-level files in the new version, and also optimizes the Reader to enter optimization logic when reading top-level data, no longer filtering -D data.
Paimon should filter out - D for old files in the case of changelog-producer=lookup, without going through optimization logic.
=> [core] Legacy files should always drop delete rows

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/RowLevelHelper.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTestBase.scala
Before on `target.a = source.a` is OK, this patch fix merge into on `source.a = target.a`, e,g
```sql
MERGE INTO target
USING source
ON source.a = target.a
WHEN MATCHED THEN
UPDATE SET a = source.a, b = source.b, c = source.c
```
=> [spark] Fix merge into update on source eq target condition

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-common/src/main/java/org/apache/paimon/sort/hilbert/HilbertIndexer.java, paimon-common/src/test/java/org/apache/paimon/format/FormatReadWriteTest.java, paimon-core/src/main/java/org/apache/paimon/schema/SchemaSerializer.java, paimon-core/src/main/java/org/apache/paimon/schema/TableSchema.java, paimon-core/src/test/java/org/apache/paimon/schema/TableSchemaSerializationTest.java, paimon-core/src/test/java/org/apache/paimon/table/ColumnTypeFileMetaTestBase.java, paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileDataTableTest.java, paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyTableColumnTypeFileMetaTest.java, paimon-core/src/test/java/org/apache/paimon/table/system/FilesTableTest.java, paimon-e2e-tests/src/test/java/org/apache/paimon/tests/TypeE2eTest.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/CdcActionITCaseBase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/postgres/PostgresSyncTableActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/SortCompactActionForUnawareBucketITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java, paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetFormatReadWriteTest.java
At present, Parquet is relatively excellent in terms of compression rate and analytical performance. It is time to use parquet by default.
All tests cover default format.
Old tables use orc too, old new table use parquet.
=> [core] Parquet becomes default file format

paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonMetricTest.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonOptimizationTestBase.scala
startDataFiles should be `numAddedFiles() - f.numDeletedFiles` instead of `numAddedFiles() + f.numDeletedFiles`
=> [core] Fix skippedTableFiles in scan metrics

docs/content/spark/procedures.md, docs/content/spark/sql-query.md, docs/content/spark/sql-write.md
- Fix sheet misalignment in `procedure` doc
- Make dynamic overwrite description clearer
- Remove `spark.sql.extensions` in other pages, because this is already a necessary configuration in `quick-start` doc
=> [doc] Update spark procedure and dynamic overwrite docs

paimon-spark/paimon-spark-3.1/pom.xml, paimon-spark/paimon-spark-3.2/pom.xml, paimon-spark/paimon-spark-3.3/pom.xml, paimon-spark/paimon-spark-3.4/pom.xml, paimon-spark/paimon-spark-3.5/pom.xml, paimon-spark/paimon-spark-common/pom.xml
For test failure in IDEA.
parquet-column conflict.
```
java.lang.IllegalAccessError: tried to access method org.apache.parquet.io.ColumnIO.getRepetitionLevel()I from class org.apache.paimon.format.parquet.reader.ParquetSplitReaderUtil
at org.apache.paimon.format.parquet.reader.ParquetSplitReaderUtil.constructField(ParquetSplitReaderUtil.java:382)
at org.apache.paimon.format.parquet.reader.ParquetSplitReaderUtil.buildFieldsList(ParquetSplitReaderUtil.java:374)
at org.apache.paimon.format.parquet.ParquetReaderFactory.createReader(ParquetReaderFactory.java:118)
```
and
parquet-hadoop conflict.
```
java.lang.NoSuchFieldError: LZ4_RAW
at org.apache.parquet.hadoop.metadata.CompressionCodecName.<clinit>(CompressionCodecName.java:34)
at org.apache.parquet.hadoop.ParquetWriter.<clinit>(ParquetWrite …
```
=> [spark] exclude parquet-column and parquet-hadoop dependency

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncDatabaseActionBase.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcMultiplexRecordEventParser.java
One of #2706 
The scenario is user might create tables before submitting cdc job, so if we doesn't collect them, the job may fail when processing records of the existed tables.
=> [cdc] Database sync initializes the set of existed tables

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java
The SparkSession.active().sharedState().externalCatalog().unwrapped() method will create a new hive metastore connection
=> [hotfix] fix the spark generic catalog to execute externalCatalog() creates a new hive metastore connection instance.

docs/content/primary-key-table/merge-engine.md, docs/content/primary-key-table/sequence-rowkind.md
Document sequence.field supports fields of all data types
=> [doc] Document sequence.field supports fields of all data types

paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpirePartitionsAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RemoveOrphanFilesAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionFactory.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RemoveOrphanFilesProcedure.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionITCase.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedure.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedureTest.scala
Some users want to clear the orphaned files of the entire database with just one click, rather than running an action on each table.
So this pr is support remove db orphan files.
=> [core] support remove db orphan files

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java, paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/CatalogEnvironment.java, paimon-core/src/main/java/org/apache/paimon/table/FileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/FileStoreTableFactory.java, paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java, paimon-core/src/test/java/org/apache/paimon/TestAppendFileStore.java, paimon-core/src/test/java/org/apache/paimon/TestFileStore.java, paimon-core/src/test/java/org/apache/paimon/table/sink/TableCommitTest.java, paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ContinuousAppendAndCompactFollowUpScannerTest.java, paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ScannerTestBase.java, paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/SnapshotReaderTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/FlinkSinkTest.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTestBase.scala
User may customize the location of database, so we tend to get the database name from identity return by catalog.
Similarly, get tablename from identity too, to adapt when we can customize the table location in the future (or now?)
=> [core] Get table name and full table name from identifier

docs/content/flink/procedures.md, docs/content/spark/procedures.md, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DeleteBranchAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DeleteTagAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/DeleteBranchProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/DeleteTagProcedure.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/BranchActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/TagActionITCase.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/DeleteBranchProcedure.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CreateAndDeleteBranchProcedureTest.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CreateAndDeleteTagProcedureTest.scala
Support multiple tags and branches delete，when user create many tags or branches such as auto-create tag/branch，then need delete them in a quick way，so support multiple mode.
Linked issue: close [#xxx](https://github.com/apache/paimon/issues/3685)
=> [procedure] Support multiple tags and branches delete

paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetSchemaConverter.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/writer/ParquetRowDataWriter.java, paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetReadWriteTest.java
Cherry-pick https://github.com/apache/flink/pull/24956
=> [parquet] ParquetSchemaConverter supports required fields

paimon-core/src/main/java/org/apache/paimon/operation/FileDeletionBase.java, paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java
Scenario: If a stream writing job is running and expiring snapshots, and then deleting tags around the expiring snapshots, might lead to the skipping set is wrong and the reading job will throw FileNotFoundException.
The problem is，the `taggedSnapshots` may be changed. 
TODO: maybe should check delete tags.
=> [core] Fix that FileDeletionBase#dataFileSkipper might skip tag when deleting tag

paimon-flink/paimon-flink-1.16/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/kafka/LogSystemITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/RescaleBucketITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadITCase.java
Fix deprecated method getRootCause() in assertj
Linked issue: close #https://github.com/apache/paimon/issues/3695
=> [hotfix] Fix deprecated method getRootCause() in assertj

paimon-common/src/main/java/org/apache/paimon/utils/HadoopUtils.java, paimon-common/src/test/java/org/apache/paimon/utils/HadoopUtilsITCase.java, paimon-common/src/test/resources/META-INF/services/org.apache.paimon.fs.FileIOLoader
Currently `hadoop-conf-dir` only supports local path. This PR uses Paimon's FileIO to access `hadoop-conf-dir` with scheme.
* Unit test.
No changes.
=> [common] Use Paimon's FileIO to access hadoop-conf-dir with scheme

paimon-common/src/main/java/org/apache/paimon/data/BinaryArrayWriter.java, paimon-common/src/main/java/org/apache/paimon/data/BinaryWriter.java, paimon-common/src/main/java/org/apache/paimon/data/InternalArray.java, paimon-common/src/main/java/org/apache/paimon/data/InternalRow.java, paimon-common/src/main/java/org/apache/paimon/data/serializer/RowCompactedSerializer.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldBoolAndAgg.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldBoolOrAgg.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldCountAgg.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldListaggAgg.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldProductAgg.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldSumAgg.java
Type handle check need more details about type and classname for user dig
Currently when type not matched only throw out IllegalArgumentException without any details which is litter hard for user to dig their job，so add more detail in IllegalArgumentException maybe better.
Linked issue: close https://github.com/apache/paimon/issues/3697
=> [core] Add type and classname in TypeHandle condition when throw IllegalArgumentException

pom.xml
Add a `<arg>-Xlint:deprecation</arg>` arg for `maven-compiler-plugin` to optimizing deprecation related messages in build logs.
Linked issue: close #3702
This helps us to discover which deprecation APIs are still being called by `Paimon`.
=> [pom] Add maven compiler args to optimize deprecation related logs

paimon-core/src/main/java/org/apache/paimon/table/sink/TableCommitImpl.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/Committer.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCommitter.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreMultiCommitter.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PrimaryKeyFileStoreTableITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/util/AbstractTestBase.java
In new versions of Flink, if a batch job fails, it might restart from some operator in the middle.
If the job is restarted from the commit operator, endInput will be called again, and the same commit messages will be committed again.
So when `endInput` is called, we must check if these commit messages are already committed.
* IT case.
No changes.
=> [flink] Fix multi-add conflict when two batch jobs are writing into the same partition at the same time

docs/content/program-api/java-api.md, paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/InnerTable.java, paimon-core/src/main/java/org/apache/paimon/table/ReadonlyTable.java, paimon-core/src/main/java/org/apache/paimon/table/sink/BatchWriteBuilderImpl.java, paimon-core/src/main/java/org/apache/paimon/table/sink/FixedBucketWriteSelector.java, paimon-core/src/main/java/org/apache/paimon/table/sink/StreamWriteBuilderImpl.java, paimon-core/src/main/java/org/apache/paimon/table/sink/WriteBuilder.java, paimon-core/src/main/java/org/apache/paimon/table/sink/WriteSelector.java, paimon-core/src/test/java/org/apache/paimon/table/AppendOnlyFileStoreTableTest.java, paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
Compute engines require the ability to write when integrating Paimon, and currently we only have one example of single point writing. We need to add an example of distributed writing.
new Experimental API: `WriteBuilder.newWriteSelector`:
```
/**
* Create a {@link WriteSelector} to partition records before writers.
*
* @return empty if no data distribution is required.
* @throws UnsupportedOperationException if this table mode does not support building writes
*     through upper level APIs.
*/
@Experimental
Optional<WriteSelector> newWriteSelector();
```
WriteSelector:
```
/**
* The {@link WriteSelector} determines to which logical downstream writers a record should be
* written to.
*/
public interface WriteSelector extends Serializable {
/** Returns the logical writer index, to which the …
```
=> [core] Introduce newWriteSelector to WriteBuilder

paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java, paimon-core/src/main/java/org/apache/paimon/disk/RowBuffer.java, paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java, paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java, paimon-core/src/test/java/org/apache/paimon/operation/AppendOnlyFileStoreWriteTest.java
io-manager is null, should not invoke spill.
=> [core] Disable forceBufferSpill when io-manager is null.

paimon-core/src/main/java/org/apache/paimon/schema/SchemaChange.java, paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java, paimon-core/src/test/java/org/apache/paimon/schema/SchemaManagerTest.java
Purpose
[core] AddColumn move support before and last.
Linked issue: close https://github.com/apache/paimon/issues/3316
Tests
Add test case: org.apache.paimon.schema.SchemaManagerTest#testApplyMove
API and Format
Documentation
=> [core] AddColumn move support before and last.

paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSourceTest.scala
Remove unreachable code in `PaimonSourceTest` class, cause that `hasPk` is scala's `Boolean` type, the value can only be `true` or `false`, so code `case _ =>` will never be accessed.
Linked issue: close #3710
Passed test cases in `PaimonSourceTest`.
=> [test] Remove unreachable code in `PaimonSourceTest` class

paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetSchemaConverter.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ParquetSplitReaderUtil.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/writer/PositionOutputStreamAdapter.java
Fix deprecated apis `OriginalType` class and `checkNotNull` method in `paimon-format` realted to parquet:
- Class `org.apache.parquet.schema.OriginalType` is instead by `org.apache.parquet.schema.LogicalTypeAnnotation`, and I noticed that other open source projects closely related to parquet, such as `Spark` and `Iceberg`, have already switched.
- Method `org.apache.parquet.Preconditions.checkNotNull()`
Linked issue: close #3708
Passed all parquet realated test cases in `paimon-format`submodule.
=> [hotfix] Fix deprecated apis OriginalType class and checkNotNull method in paimon-format realted to parquet

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/pom.xml, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-common/src/main/java/org/apache/paimon/compression/BlockCompressionFactory.java, paimon-common/src/main/java/org/apache/paimon/compression/ZstdBlockCompressionFactory.java, paimon-common/src/main/java/org/apache/paimon/compression/ZstdBlockCompressor.java, paimon-common/src/main/java/org/apache/paimon/compression/ZstdBlockDecompressor.java, paimon-format/pom.xml, pom.xml
=> [core] Local disk spill compression uses zstd

paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexReader.java, paimon-common/src/main/java/org/apache/paimon/fileindex/empty/EmptyFileIndexReader.java, paimon-common/src/main/java/org/apache/paimon/predicate/EndsWith.java, paimon-common/src/main/java/org/apache/paimon/predicate/FunctionVisitor.java, paimon-common/src/main/java/org/apache/paimon/predicate/OnlyPartitionKeyEqualVisitor.java, paimon-common/src/main/java/org/apache/paimon/predicate/PredicateBuilder.java, paimon-common/src/test/java/org/apache/paimon/predicate/PredicateTest.java, paimon-format/src/main/java/org/apache/paimon/format/orc/filter/OrcPredicateFunctionVisitor.java, paimon-format/src/main/java/org/apache/parquet/filter2/predicate/ParquetFilters.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkFilterConverter.java, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkFilterConverterTest.java
Linked issue: close https://github.com/apache/paimon/issues/3715
=> [spark] Support StringEndsWith filter in SparkFilterConverter

docs/content/primary-key-table/merge-engine.md, paimon-common/src/main/java/org/apache/paimon/utils/RoaringBitmap32.java, paimon-common/src/main/java/org/apache/paimon/utils/RoaringBitmap64.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregator.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldRoaringBitmap32Agg.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldRoaringBitmap64Agg.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregatorTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java
subtask of #3717 
- org.apache.paimon.mergetree.compact.aggregate.FieldAggregatorTest#testFieldRoaringBitmap64Agg
- org.apache.paimon.flink.PreAggregationITCase.RoaringBitmapAggAggregationITCase#testRoaring32BitmapAgg
- org.apache.paimon.flink.PreAggregationITCase.RoaringBitmapAggAggregationITCase#testRoaring64BitmapAgg
=> [core] introduce rbm32/rbm64 aggregate function.

paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/TableReadBenchmark.java
Fix the problem that parquet-related benchmark test cases call the wrong method in `TableReadBenchmark` class.
Linked issue: close #3727
=> [benchmark] Fix the problem that parquet-related benchmark test cases call the wrong method in `TableReadBenchmark` class

paimon-common/src/main/java/org/apache/paimon/predicate/PredicateBuilder.java, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkFilterConverterTest.java
Fix spark query with filter timestamp
before fix:
spark-sql> select * from bdsp_prd.z_paimon_pk_table where dt='2024-04-11 11:01:00' limit 10;
OK
pk	v1	v2	dt
Time taken: 1.198 seconds
spark-sql> 24/07/11 16:44:13 WARN SparkContext: Successfully stopped SparkContext
after fix，user can query by filter timestamp type：
Spark master: yarn, Application Id: application_1719458929416_3440055
spark-sql> select * from bdsp_prd.z_paimon_pk_table where dt='2024-07-09 12:22:21' limit 10;
24/07/11 16:34:03 WARN TaskSetManager: Finished tasks (1/1) in stage 0.0
OK
pk	v1	v2	dt
2	12.3	21	2024-07-09 12:22:21
Time taken: 18.313 seconds, Fetched 1 row(s)
=> [spark] Fix spark query with filter timestamp

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/pom.xml, paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergCommitCallback.java, paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergPathFactory.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergConversions.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergDataFileMeta.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergDataFileMetaSerializer.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestEntry.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestEntrySerializer.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestFile.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestFileMeta.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestFileMetaSerializer.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestList.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergPartitionSummary.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergPartitionSummarySerializer.java, paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergDataField.java, paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergMetadata.java, paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergPartitionField.java, paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergPartitionSpec.java, paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergSchema.java, paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergSnapshot.java, paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergSnapshotSummary.java, paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergSortOrder.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/test/java/org/apache/paimon/iceberg/IcebergCompatibilityTest.java, paimon-format/src/main/java/org/apache/paimon/format/avro/AvroFileFormat.java, paimon-format/src/main/java/org/apache/paimon/format/avro/AvroSchemaConverter.java, paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/SearchArgumentToPredicateConverter.java
Iceberg is a popular data lake format. In order to have more users try out Paimon while keeping their existing Iceberg workflow, we introduce `IcebergCommitCallback` in this PR to create Iceberg metadata after commit.
With this feature, Iceberg readers can read Paimon's `RawFile`s.
* Unit tests
No changes in Paimon format.
Yes. Document will be added later.
=> [core] Introduce IcebergCommitCallback to create Iceberg metadata after commit

paimon-filesystems/paimon-oss-impl/pom.xml, paimon-filesystems/paimon-s3-impl/pom.xml, pom.xml
rework on #2519, in 2 steps: upgrade jar plugin first, then we'll see on removing the Git branch name configuration later
=> upgrade maven-jar-plugin: fixes Reproducible Builds issue

paimon-core/src/main/java/org/apache/paimon/table/RollbackHelper.java, paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java
Linked issue: close #3732 
Skip non-existent snapshots in rollback operation
Added FileStoreTableTestBase#testRollbackToSnapshotSkipNonExistentSnapshot
no
no
=> [core][rollback] Skip non-existent snapshots in rollback

docs/content/flink/sql-alter.md, docs/content/spark/sql-alter.md, paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java, paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/PaimonMetaHook.java
Linked issue: close #3742 
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase#testAlterTableComment
docs/content/flink/sql-alter.md
docs/content/spark/sql-alter.md
=> [flink] support flink sql alter table comment

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java, paimon-core/src/main/java/org/apache/paimon/operation/ChangelogDeletion.java, paimon-core/src/main/java/org/apache/paimon/operation/FileDeletionBase.java, paimon-core/src/main/java/org/apache/paimon/operation/SnapshotDeletion.java, paimon-core/src/main/java/org/apache/paimon/operation/TagDeletion.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/ExpireChangelogImpl.java, paimon-core/src/main/java/org/apache/paimon/table/ExpireSnapshotsImpl.java, paimon-core/src/main/java/org/apache/paimon/table/RollbackHelper.java, paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java, paimon-core/src/test/java/org/apache/paimon/TestFileStore.java, paimon-core/src/test/java/org/apache/paimon/operation/ExpireSnapshotsTest.java, paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java, paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java, paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
Object store delete directory will list files for directory, it is very costly. We can not delete directory for every snapshot.
=> [core] Disable snapshot.clean-empty-directories by default

paimon-common/src/main/java/org/apache/paimon/predicate/PredicateBuilder.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/SearchArgumentToPredicateConverterTest.java
Timestamp with local zone should only use Timestamp.fromInstant.
=> [core] Fix PredicateBuilder.convertJavaObject with timestamp with local zone

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/ScanHelper.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/ScanHelperTest.scala
=> [spark] Fix the generation of PaimonInputPartition 

docs/content/maintenance/manage-branches.md, paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java, paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java, paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java, paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalog.java, paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BranchSqlITCase.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
Schema of branches are stored in separated directories. However currently Paimon does not support different schemas for different branches.
This PR supports this feature, and also support using table branches with `<table_name>$branch_<branch_name>`. This usage is similar to Iceberg's branches.
We recommend this usage instead of `/*+ OPTIONS('branch' = '<branch_name>) */` in Flink. Because if we use dynamic option and the target branch has different schema from the main branch, then Flink sink and catalog will have different schemas and it cannot pass Flink SQL's validation.
IT cases.
No changes.
Yes.
=> [core] Support using table branches with $branch_ and support different schemas for different branches

docs/content/flink/procedures.md, docs/content/spark/procedures.md
=> [doc] Complement expire_strategy possible values for procedures expire_partitions.

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-common/src/main/java/org/apache/paimon/utils/FileDeletionThreadPool.java, paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java, paimon-core/src/main/java/org/apache/paimon/operation/ChangelogDeletion.java, paimon-core/src/main/java/org/apache/paimon/operation/FileDeletionBase.java, paimon-core/src/main/java/org/apache/paimon/operation/SnapshotDeletion.java, paimon-core/src/main/java/org/apache/paimon/operation/TagDeletion.java
For object storage, the larger the concurrency to delete files, the better the overall deletion throughput.
=> [core] Introduce delete-file.thread-num

docs/content/spark/quick-start.md, paimon-common/src/main/java/org/apache/paimon/utils/DateTimeUtils.java, paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/paimon/spark/util/shim/TypeUtils.scala, paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/util/shim/TypeUtils.scala, paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/paimon/spark/util/shim/TypeUtils.scala, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkInternalRow.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkRow.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkTypeUtils.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/util/shim/TypeUtils.scala, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkInternalRowTest.java, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkTypeTest.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLTestBase.scala
Spark support timestamp_ntz since spark3.4, paimon can support it. And there were problems with timestamp between paimon and spark types before, the following is the correct result after modification
| Spark Data Type | Paimon Data Type | Atomic Type |
|----------|----------|----------|
| TimestampType    | LocalZonedTimestamp   | true   |
| TimestampNTZType (spark3.4+)   | TimestampType   | true   |
For spark3.3 and below, we still treat paimon TimestampType as spark TimestampType
For spark3.4+, everything goes well
=> [spark] Support timestamp_ntz

paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/procedure/RepairActionITCase.java
Fix unstable Hive connector ut
hms port is 9083 in RepairActionITCase not stable because other test also use it，so change it to 9082.
=> [hotfix] Fix unstable Hive connector ut

docs/content/primary-key-table/merge-engine/partial-update.md, docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java, paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
Linked issue: close #3048
This pull request supports dealing with deletion records in partial update merge engine.
Unit tests are added in PrimaryKeyFileStoreTableTest to verify the changes in this PR
This pull request affects the default behavior of partial-update merge engine in cases where deletion records exist. Given that the existing behavior is to throw exception in this case, the changes in this PR are backward compatible.
This PR requires to update the document about merge engine, which has been included in the commit.
=> [core] Support delete by default in partial updates

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregator.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldCollectAgg.java
Improve performance by not distinct accumulator all the time.
=> [core] Improve performance of dinstinct collect agg.

paimon-service/paimon-service-runtime/src/test/java/org/apache/paimon/service/KvQueryTableTest.java
Fix port occupied in KvQueryTableTest
Fix port occupied in KvQueryTableTest
=> [hotfix] Fix port occupied in KvQueryTableTest

paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/ReadonlyTable.java, paimon-core/src/main/java/org/apache/paimon/table/Table.java, paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/BucketsTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/FileMonitorTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/ReadOptimizedTable.java
API users have requirement to take a look to latest snapshot id. And maybe use scan.snapshot-id to read data with idempotent.
Add Table.latestSnapshotId public interface.
=> [core] Add latestSnapshotId to Table

docs/content/primary-key-table/compaction.md, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/test/java/org/apache/paimon/CoreOptionsTest.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTablesStoreCompactOperator.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PrimaryKeyFileStoreTableITCase.java
1. Rename `changelog-producer.lookup-wait` to `lookup-wait`.
2. Lookup wait should affect deletion vectors mode and first row engine.
3. `AsyncLookupSinkWrite` should be used to deletion vectors mode and first row engine.
=> [core] Lookup wait should affect deletion vectors mode and first row engine

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java
when sink.committer-operator-chaining'='false',  an extra node appeared in our flink job.
This is a bug, fix it.
=> [core] fix CommitterOperator chain value when sink.committer-operator-chaining is false

paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/paimon/spark/catalyst/optimizer/MergePaimonScalarSubqueries.scala, paimon-spark/paimon-spark-3.4/src/main/scala/org/apache/paimon/spark/catalyst/optimizer/MergePaimonScalarSubqueries.scala, paimon-spark/paimon-spark-3.5/src/main/scala/org/apache/paimon/spark/catalyst/optimizer/MergePaimonScalarSubqueries.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/optimizer/EvalSubqueriesForDeleteTable.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/optimizer/MergePaimonScalarSubqueriersBase.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/optimizer/MergePaimonScalarSubqueries.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/optimizer/MergePaimonScalarSubqueriesBase.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/extensions/PaimonSparkSessionExtensions.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonOptimizationTestBase.scala
- Apply MergePaimonScalarSubqueries only when paimon scan exists
- fix typo
=> [spark] Apply MergePaimonScalarSubqueries only when paimon scan exists

docs/content/spark/procedures.md, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/MigrateFileProcedure.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/procedure/MigrateFileProcedureITCase.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/procedure/RepairActionITCase.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/MigrateFileProcedure.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/MigrateFileProcedureTest.scala
Currently migrate_file would delete source table after migrate，but some condition user hope save origin table.The pr is aim to support it.
Linked issue: close https://github.com/apache/paimon/issues/3781
=> [hive] migrate_file support save source table

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MigrateFileAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MigrateFileActionFactory.java, paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/procedure/MigrateFileProcedureITCase.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/procedure/MigrateTableProcedureITCase.java
Follow up https://github.com/apache/paimon/pull/3780
add action to support migrate_file which not support now.
Linked issue: close https://github.com/apache/paimon/issues/3795
MigrateFileProcedureITCase
=> [flink] Support migrate file action

paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-common/src/main/java/org/apache/paimon/options/ConfigOption.java, paimon-common/src/main/java/org/apache/paimon/security/SecurityConfiguration.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
In ConfigOption, withDeprecatedKeys is very similar with withFallbackKeys. We can just keep only one.
=> [core] Remove duplicate ConfigOption.withDeprecatedKeys

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BranchSqlITCase.java
=> [test] Complement the ITCase for flink branchSQL.

paimon-core/src/main/java/org/apache/paimon/partition/PartitionTimeExtractor.java, paimon-core/src/main/java/org/apache/paimon/partition/PartitionValuesTimeExpireStrategy.java, paimon-core/src/test/java/org/apache/paimon/partition/PartitionTimeExtractorTest.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionMarkDoneTrigger.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/PartitionMarkDoneTriggerTest.java
When using `partition markdone`, if some partitions are non-date formatted, currently `PartitionTimeExtractor` will returns `null` and omits the exception. This PR refactor it for better trouble shooting.
=> [core] Refactor exception handling of PartitionTimeExtractor

paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVectorIndexFileMaintainer.java, paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVectorsIndexFile.java, paimon-core/src/main/java/org/apache/paimon/index/IndexFileHandler.java, paimon-core/src/test/java/org/apache/paimon/TestAppendFileStore.java, paimon-core/src/test/java/org/apache/paimon/deletionvectors/DeletionVectorIndexFileMaintainerTest.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/SparkDataFileMeta.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/UpdatePaimonTableCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/util/SQLHelper.scala
=>  [spark] refactor delete with deletion vector

paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/lookup/AbstractLookupBenchmark.java, paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/lookup/LookupBloomFilterBenchmark.java, paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/lookup/LookupWriterBenchmark.java
Linked issue: close #3773 
Add write benchmark for sort file
Added `LookupWriterBenchmark` for different value size and record count for sort file
no
no
=> [core][lookup] Add writer benchmark for sort and hash file store

paimon-core/src/main/java/org/apache/paimon/utils/ObjectsCache.java, paimon-core/src/test/java/org/apache/paimon/utils/ObjectsCacheTest.java
=> [core] Make ObjectsCache thread safe

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonStatistics.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/statistics/StatisticsHelperBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTestBase.scala
Fix query with char&varchar after analyze when partition filter push down hit
```
VarcharType(10) (of class org.apache.spark.sql.types.VarcharType)
scala.MatchError: VarcharType(10) (of class org.apache.spark.sql.types.VarcharType)
at org.apache.spark.sql.catalyst.plans.logical.statsEstimation.FilterEstimation.evaluateBinary(FilterEstimation.scala:281)
at org.apache.spark.sql.catalyst.plans.logical.statsEstimation.FilterEstimation.calculateSingleCondition(FilterEstimation.scala:148)
at org.apache.spark.sql.catalyst.plans.logical.statsEstimation.FilterEstimation.calculateFilterSelectivity(FilterEstimation.scala:118)
at org.apache.spark.sql.catalyst.plans.logical.statsEstimation.FilterEstimation.estimate(FilterEstimation.scala:50)
at …
```
=> [spark] Fix stats estimation with char and varchar

paimon-core/src/main/java/org/apache/paimon/FileStore.java, paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala
For example, `SegmentsCache` in `AbstractFileStore` is not serializable.
=> [core] FileStore should not be serializable

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java, paimon-core/src/main/java/org/apache/paimon/table/system/AggregationFieldsTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/BranchesTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/ConsumersTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/OptionsTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/SchemasTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/SnapshotsTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/StatisticTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/SystemTableLoader.java, paimon-core/src/main/java/org/apache/paimon/table/system/TagsTable.java
Introduce a map to `SystemTableLoader`, so outside can get all system tables from it.
=> [core] Introduce SYSTEM_TABLE_LOADERS to SystemTableLoader

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonOptionHelper.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkSource.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/util/OptionUtils.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonOptionTest.scala
Users can configure paimon option globally via `spark.paimon.x`, e.g.
`set spark.paimon.file.block-size=512M` to control the file block size globally
=> [spark] Support global options via SQL conf

paimon-core/src/main/java/org/apache/paimon/schema/Schema.java, paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java, paimon-core/src/test/java/org/apache/paimon/schema/SchemaManagerTest.java, paimon-flink/paimon-flink-1.16/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java
Currently we have some immutable table options (for example, merge-engine and primary-key). Once the table is created, they cannot be changed.
However for an empty table, changing these options does not affect any data. Also ,we've supported different schemas for different branches in #3757. Users can set primary keys to a newly created branch with this feature.
* Unit tests.
No API / format changes.
=> [core] Immutable table options can now be changed on an empty table

paimon-core/src/main/java/org/apache/paimon/casting/CastExecutors.java, paimon-core/src/main/java/org/apache/paimon/casting/NumericPrimitiveToTimestamp.java, paimon-core/src/test/java/org/apache/paimon/casting/CastExecutorTest.java
Currently paimon casting not support numeric to timestamp cast，the pr is aimed to support it.
Linked issue: https://github.com/apache/paimon/issues/3833
=> [core] Support NumericPrimitiveToTimestamp in casting

paimon-core/src/main/java/org/apache/paimon/mergetree/LookupLevels.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeTreeCompactRewriter.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/table/query/LocalTableQuery.java, paimon-core/src/test/java/org/apache/paimon/mergetree/ContainsLevelsTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/LookupLevelsTest.java
=> [core] Manage the lookup file disk cache in task granularity

paimon-common/src/main/java/org/apache/paimon/utils/InternalRowPartitionComputer.java, paimon-common/src/test/java/org/apache/paimon/utils/InternalRowPartitionComputerTest.java, paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java, paimon-core/src/main/java/org/apache/paimon/disk/FileChannelManager.java, paimon-core/src/main/java/org/apache/paimon/disk/FileChannelManagerImpl.java, paimon-core/src/main/java/org/apache/paimon/disk/FileIOChannel.java, paimon-core/src/main/java/org/apache/paimon/disk/IOManager.java, paimon-core/src/main/java/org/apache/paimon/disk/IOManagerImpl.java, paimon-core/src/main/java/org/apache/paimon/mergetree/LookupFile.java, paimon-core/src/main/java/org/apache/paimon/mergetree/LookupLevels.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/table/query/LocalTableQuery.java, paimon-core/src/test/java/org/apache/paimon/mergetree/ContainsLevelsTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/LookupFileTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/LookupLevelsTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/TestChangelogDataReadWrite.java
Add the hint in local file name to track the remote the file for debugging purpose.
=> [core] Add hint in local lookup file tracking with remote file

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/SystemCatalogTable.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/WatermarkITCase.java
Support the watermark function of auditlog table
- WatermarkITCase
No changes.
=> [flink] Support the watermark function of auditlog table

paimon-core/src/main/java/org/apache/paimon/manifest/ManifestFileMeta.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java, paimon-core/src/main/java/org/apache/paimon/partition/PartitionPredicate.java, paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java
The case is the upstream data changes too many partitions, make the Predicate too deep, then error is:
```
Caused by: java.lang.RuntimeException: java.lang.StackOverflowError
at org.apache.paimon.manifest.ManifestFileMeta.merge(ManifestFileMeta.java:178)
at org.apache.paimon.operation.FileStoreCommitImpl.tryCommitOnce(FileStoreCommitImpl.java:808)
... 27 more
Caused by: java.lang.StackOverflowError
at org.apache.paimon.predicate.CompoundPredicate.test(CompoundPredicate.java:59)
at org.apache.paimon.predicate.Or.test(Or.java:55)
at org.apache.paimon.predicate.CompoundPredicate.test(CompoundPredicate.java:59)
...
```
=> [core] Optimize manifest-full-compact and parts overwrite by PartitionPredicate

paimon-common/src/main/java/org/apache/paimon/data/LocalZoneTimestamp.java, paimon-common/src/test/java/org/apache/paimon/data/LocalZoneTimestampTest.java
Due to the fact that both types share the same Timestamp, and the default toString for Timestamp is implemented for TimestampWithoutZone, the usage is very disjointed and difficult for users to understand.
We can specifically introduce a separate data structure for TimestampLocalZone, and this PR introduces this data structure without modifying its usage in the code.
=> [core] Introduce data structure for timestamp with local zone

paimon-common/src/main/java/org/apache/paimon/utils/StringUtils.java, paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java, paimon-core/src/main/java/org/apache/paimon/catalog/CachingCatalog.java, paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java, paimon-core/src/main/java/org/apache/paimon/catalog/CatalogUtils.java, paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java, paimon-core/src/main/java/org/apache/paimon/catalog/Identifier.java, paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalog.java, paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java, paimon-core/src/test/java/org/apache/paimon/table/SchemaEvolutionTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BranchSqlITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
In # we allow visit table branches by `$branch_`. Now an identifier may represent a data table, or a system table, or a table branch.
In this PR, we add some methods in `Identifier` so that it can recognize branches and system tables. Catalogs will need these methods to get schemas, communicate with metastores, etc.
This is a refactor. Existing tests should cover the changes.
`Identifier` is a public API. This PR adds some methods to the class.
=> [core] Identifier can now recognize branch and system tables

paimon-core/src/main/java/org/apache/paimon/table/FallbackReadFileStoreTable.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java, paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/HiveSchema.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
Support creating hive catalog table branch and reading branch data
- HiveCatalogITCaseBase
No changes.
=> [hive] Support creating hive catalog table branch and reading branch data

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/DynamicPartitionLoader.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java
=> [flink] Fix lookup join with lookup.dynamic-partition and cross-partition table throws ArrayIndexOutOfBoundsException

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonAnalysis.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DataFrameWriteTest.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/InsertOverwriteTableTest.scala
=> [spark] dataframe.write and insert sql syntax in byName mode

docs/layouts/shortcodes/generated/catalog_configuration.html, paimon-common/src/main/java/org/apache/paimon/codegen/CompileUtils.java, paimon-common/src/main/java/org/apache/paimon/io/cache/CacheManager.java, paimon-common/src/main/java/org/apache/paimon/options/CatalogOptions.java, paimon-common/src/main/java/org/apache/paimon/reader/RecordReaderIterator.java, paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java, paimon-core/src/main/java/org/apache/paimon/FileStore.java, paimon-core/src/main/java/org/apache/paimon/catalog/CachingCatalog.java, paimon-core/src/main/java/org/apache/paimon/catalog/CatalogFactory.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestFile.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestList.java, paimon-core/src/main/java/org/apache/paimon/index/IndexFileHandler.java, paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBState.java, paimon-core/src/main/java/org/apache/paimon/manifest/IndexManifestFile.java, paimon-core/src/main/java/org/apache/paimon/manifest/ManifestFile.java, paimon-core/src/main/java/org/apache/paimon/manifest/ManifestList.java, paimon-core/src/main/java/org/apache/paimon/manifest/SimpleFileEntrySerializer.java, paimon-core/src/main/java/org/apache/paimon/mergetree/LookupFile.java, paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedCatalog.java, paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedFileStore.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/DelegatedFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/FileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/utils/ObjectsCache.java, paimon-core/src/main/java/org/apache/paimon/utils/ObjectsFile.java, paimon-core/src/main/java/org/apache/paimon/utils/SegmentsCache.java, paimon-core/src/test/java/org/apache/paimon/catalog/CachingCatalogTest.java, paimon-core/src/test/java/org/apache/paimon/catalog/TestableCachingCatalog.java, paimon-core/src/test/java/org/apache/paimon/manifest/IndexManifestFileHandlerTest.java, paimon-core/src/test/java/org/apache/paimon/utils/ObjectsCacheTest.java
Next part for https://github.com/apache/paimon/pull/3829
Avoid costly manifest reading for table in CachingCatalog. Reusing `writeManifestCache` mechanism in `AbstractFileStore`.
=> [core] Introduce cache.manifest-max-memory to CachingCatalog

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLTestBase.scala
For DDL like
```
CREATE TABLE T (id STRING, name STRING, pt STRING)
PARTITIONED BY (substr(pt, 1, 2))
```
should throw an exception since we do not support hidden partitions
=> [spark] Fix partition transform converter

paimon-hive/paimon-hive-catalog/pom.xml
[hive] exclude parquet-hadoop-bundle from paimon-hive-catalog.
Linked issue: close #3881 
No.
No.
No.
=> [hive] exclude parquet-hadoop-bundle from paimon-hive-catalog.

paimon-format/src/main/java/org/apache/paimon/format/avro/AvroFileFormat.java
Improve performance:
No need to flush every block for avro writer.
=> [avro] Do not flush on every block for DataFileWriter

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkGenericCatalogFactory.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkGenericCatalogFactoryTest.java
Linked issue: close #3738
Support options filter in FlinkGenericCatalog when creating HiveCatalogs. Some times, the catalog factory loaded by SPI may validate the input options.
FlinkGenericCatalogFactoryTest.testHiveCatalogFilter
=> [flink] Support options filter in FlinkGenericCatalogFactory

paimon-e2e-tests/src/test/java/org/apache/paimon/tests/E2eTestBase.java, paimon-e2e-tests/src/test/java/org/apache/paimon/tests/SparkE2eTest.java
According to https://github.com/actions/runner-images/issues/9692 , docker compose v1 is removed from github action images. So we ned to update docker compose in e2e tests to v2.
Existing tests should cover the change.
No changes in format.
=> [e2e] Update docker compose to v2

paimon-core/src/main/java/org/apache/paimon/operation/PartitionExpire.java
Make expire partition log more readable
LOG changed before: ```Expire Partition: org.apache.paimon.data.BinaryRow@b2d8cadd``` 
LOG changed after: ```Expire Partition: {dt=20240710, hour=4}```
=> [core] Change expire parition log

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java, paimon-core/src/test/java/org/apache/paimon/operation/AppendOnlyFileStoreWriteTest.java
`write-max-writers-to-spill` default value is 5, which is too small. Generally, at least 10 are acceptable.
=> [core] Increase write-max-writers-to-spill and logging

paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java, paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/CopyFileOperator.java
Now CloneActionITCase is unstabitily, because we use Catalog#getTable which means the schema file must be copied completely, but in a distributed environment, this cannot be guaranteed.
So we add interface in Catalog for CloneAction adapter CachingCatalog.
=> [core] add interface in Catalog for CloneAction adapter CachingCatalog

docs/content/spark/procedures.md, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ExpirePartitionsProcedure.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/ExpirePartitionsProcedureTest.scala
Support time-pattern options in spark expire partition procedure
=> [spark] Support specifying time-pattern in ExpairePartition procedure

paimon-core/src/main/java/org/apache/paimon/crosspartition/IndexBootstrap.java, paimon-core/src/test/java/org/apache/paimon/crosspartition/IndexBootstrapTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/GlobalDynamicBucketTableITCase.java
In the case of partitioned tables,  call  IndexBootstrap.bootstrapType function  throw exception:  "Field names must be unique. Found duplicates: [dt]"    
Linked issue: close #3886
=> [core][bug]Fix partition table get index RowType error

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-common/src/main/java/org/apache/paimon/fs/AsyncPositionOutputStream.java, paimon-common/src/main/java/org/apache/paimon/utils/FixLenByteArrayOutputStream.java, paimon-common/src/main/java/org/apache/paimon/utils/ReuseByteArrayOutputStream.java, paimon-common/src/test/java/org/apache/paimon/fs/AsyncPositionOutputStreamTest.java, paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestFile.java, paimon-core/src/main/java/org/apache/paimon/io/KeyValueDataFileWriter.java, paimon-core/src/main/java/org/apache/paimon/io/RowDataFileWriter.java, paimon-core/src/main/java/org/apache/paimon/io/RowDataRollingFileWriter.java, paimon-core/src/main/java/org/apache/paimon/io/SingleFileWriter.java, paimon-core/src/main/java/org/apache/paimon/io/StatsCollectingSingleFileWriter.java, paimon-core/src/main/java/org/apache/paimon/manifest/ManifestFile.java, paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/operation/MemoryFileStoreWrite.java, paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java, paimon-core/src/test/java/org/apache/paimon/format/FileFormatSuffixTest.java, paimon-core/src/test/java/org/apache/paimon/io/RollingFileWriterTest.java
This PR introduces asynchronous file writing to increase data throughput.
In order to avoid the problem of byte array reuse, all written arrays are copied once, which is the overhead brought by this PR. However, compared to writing files, copying a byte array seems to be less expensive.
`AsyncPositionOutputStreamTest`
=> [core] Introduce AsyncPositionOutputStream

paimon-common/src/main/java/org/apache/paimon/fileindex/bitmap/BitmapFileIndex.java, paimon-common/src/test/java/org/apache/paimon/fileindex/bitmapindex/TestBitmapFileIndex.java
I found a bug in the process of serializing the bitmap index
=> [core] Fix offset bug of bitmap index

docs/content/flink/procedures.md, paimon-flink/paimon-flink-1.18/src/test/java/org/apache/paimon/flink/procedure/ProcedurePositionalArgumentsITCase.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ActionFactory.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpirePartitionsAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpirePartitionsActionFactory.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ExpirePartitionsProcedure.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ExpirePartitionsActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/ExpirePartitionsProcedureITCase.java
Support time-pattern options in flink expire partition
=> [flink]Support specifying time-pattern in ExpairePartition

paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonCommitTest.scala
Linked issue: https://github.com/apache/paimon/issues/3840
=> [spark] Inconsistent parameter key if use dataframe write 

docs/content/append-table/streaming.md, docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyTableCompactionCoordinator.java, paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/StoreMultiCommitterTest.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DeletionVectorTest.scala
Currently, the default value is 50, which means 50 small files in a bucket, it will be large number of small files...
Adjust this to 5.
=> [core] Adjust compaction.max.file-num of bucketed append table to 5

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-common/src/main/java/org/apache/paimon/lookup/LookupStrategy.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapperTest.java, paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AsyncLookupSinkWrite.java
Linked issue: subtask of #3868 
[common] supports configuring force-lookup
- `org.apache.paimon.table.PrimaryKeyFileStoreTableTest#testForceLookupCompaction`
=> [common] supports configuring force-lookup.

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonPartitionManagement.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonPartitionManagementTest.scala
Spark support drop multi-partitions in one command atomically:
```sql
ALTER TABLE table DROP [IF EXISTS] PARTITION spec1[, PARTITION spec2, ...];
```
This pr changes `PaimonPartitionManagement` to extends `SupportsAtomicPartitionManagement` instead of `SupportsPartitionManagement`.
add test
no
=> [spark] Support alter table drop multi partitions

paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexReader.java, paimon-common/src/main/java/org/apache/paimon/fileindex/empty/EmptyFileIndexReader.java, paimon-common/src/main/java/org/apache/paimon/predicate/Contains.java, paimon-common/src/main/java/org/apache/paimon/predicate/FunctionVisitor.java, paimon-common/src/main/java/org/apache/paimon/predicate/OnlyPartitionKeyEqualVisitor.java, paimon-common/src/main/java/org/apache/paimon/predicate/PredicateBuilder.java, paimon-format/src/main/java/org/apache/paimon/format/orc/filter/OrcPredicateFunctionVisitor.java, paimon-format/src/main/java/org/apache/parquet/filter2/predicate/ParquetFilters.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkFilterConverter.java, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkFilterConverterTest.java
This pr makes Spark engine supports push down `StringContains`, e.g., `col like '%xx%'`, and create a new predicate function `Contains` in Paimon to represent it.
add test
no
=> [spark] Support push down StringContains

paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/NestedColumnReader.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/NestedPositionUtil.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/NestedPrimitiveColumnReader.java, paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetColumnVectorTest.java, paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetReadWriteTest.java
For orc, if we have 4 rows of `ARRAY<ARRAY<STRING>: [[0, null], [1], [], null], [2], [], null]`. The data layout is:
Currently, the parquet format layout is not same. For example, the inner `IntVector` will have more than one null value (that is ,the empty and null array will be set as null value in inner vector). This PR make parquet to be consistent with orc.
=> [parquet] Child vector of complex type should arrange elements compactly (like orc)

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java
=> [spark] fix bug that use the wrong version of commit message serializer

paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTest.scala, paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTest.scala, paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTest.scala, paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTest.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonTableTest.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/MergeIntoNotMatchedBySourceTest.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTestBase.scala
=> [spark] refine MergeInto UT

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldCountAgg.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregatorTest.java
```
CREATE  TABLE testAggregation ( 
id STRING  
,name STRING 
,dt STRING 
,PRIMARY KEY(id, dt) NOT ENFORCED 
,agg_count bigint 
) PARTITIONED BY (dt) WITH ( 
'bucket' = '1' 
,'auto-create' = 'false' 
,'fields.agg_count.aggregate-function' = 'count' 
,'connector' = 'paimon' 
,'merge-engine' = 'aggregation' 
);
insert datas to trigger compaction.
```
throw ClassCastException ：
FieldType is Bigint type, but return Integer type.
Eventually, an error occurs when executing method `getLong` :
=> [core] Fix FieldCountAgg should return the same data type as fieldType.

paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTest.scala, paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTest.scala, paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTest.scala, paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTest.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeIntoBase.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/RowLevelOp.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/MergeIntoPaimonTable.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/UpdatePaimonTableCommand.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonTableTest.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTestBase.scala
Support merge into for append table
=> [spark] Support merge into for append table

docs/content/primary-key-table/merge-engine/aggregation.md, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregator.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldListaggAgg.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/IntervalPartitionTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/AggregateMergeFunctionTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregatorTest.java
1、In my company, user want set field delimiter when use list agg.
2、Eliminate todo left over from two years ago.
=> [core] support user define delimiter with list agg

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/UnawareBucketCompactionTopoBuilder.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/BucketUnawareCompactSource.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/UnawareBucketAppendOnlyTableITCase.java
When write data to append only table, the watermark will be override by the CompactionCoordinator with Long.MIN_VALUE. This is a bug, now fix it.
=> [core] fix bug of watermark override with append only table

paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalTimeStampStartingScanner.java, paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/TimeTravelITCase.java, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkTimeTravelWithDataFrameITCase.java
…liestSnapshot time , no data return (#3904)
=> [core] when use from-timestamp read data from snapshot, if time < earliestSnapshot time , no data return (#3904)

paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java, paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java
Linked issue: close #3902
org.apache.paimon.utils.SnapshotManagerTest#testLatestSnapshotOfUser
=> Avoid FileNotFoundException when looking for the latest snapshot of user #3902

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java, paimon-core/src/main/java/org/apache/paimon/operation/PartitionExpire.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkEndInputPartitionExpireITCase.java
In my company, some paimon user have reported the following issue :
Everyday the batch jobs have a running time lower than config partition.expiration-check-interval, so many partitions that should have expired have not been expired.
Now add a conf, support check partition expire used in case of batch mode or bounded stream.
=> [core] support check partition expire when batch mode or bounded stream

paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVectorIndexFileWriter.java, paimon-core/src/test/java/org/apache/paimon/deletionvectors/DeletionVectorsIndexFileTest.java
Linked issue: close #3891
See issue, there will be FileNotFound when using s3
The bug is only in S3, cannot re-produce in unit tests.
=> [core] Get size should after close output in emptyIndexFile

paimon-core/src/main/java/org/apache/paimon/casting/CastExecutors.java, paimon-core/src/main/java/org/apache/paimon/casting/TimestampToNumericPrimitiveCastRule.java, paimon-core/src/test/java/org/apache/paimon/casting/CastExecutorTest.java
Follow up https://github.com/apache/paimon/pull/3832 had support NumericPrimitive  to Timestamp  casting，this pr support Timestamp to NumericPrimitive  casting.
CastExecutorTest##testTimestampToNumeric
=> [core] Support TimestampToNumericPrimitiveCastRule in casting

paimon-core/src/main/java/org/apache/paimon/casting/BinaryToStringCastRule.java, paimon-core/src/main/java/org/apache/paimon/casting/CastExecutors.java, paimon-core/src/test/java/org/apache/paimon/casting/CastExecutorTest.java
Currently only support string to binary casting，this pr is aimed to support BinaryToStringCastRule in casting
CastExecutorTest##testBinaryToString
=> [core] Support BinaryToStringCastRule in casting

paimon-flink/paimon-flink-1.18/src/test/java/org/apache/paimon/flink/UnawareBucketAppendOnlyTableITCase.java, paimon-flink/paimon-flink-1.18/src/test/resources/log4j2-test.properties, paimon-flink/paimon-flink-1.19/pom.xml, paimon-flink/paimon-flink-1.19/src/test/java/org/apache/paimon/flink/UnawareBucketAppendOnlyTableITCase.java, paimon-flink/paimon-flink-1.19/src/test/resources/log4j2-test.properties, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/UnawareBucketCompactionTopoBuilder.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendBypassCompactWorkerOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendCompactWorkerOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendOnlySingleTableCompactionWorkerOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CompactWorkerOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/UnawareBucketSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/AppendBypassCoordinateOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/BucketUnawareCompactSource.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/UnawareBucketAppendOnlyTableITCase.java
Inline compaction of append table (bucket = -1) has a special independent topology. It has caused many problems:
1. Causing the bounded streaming to not end.
2. There is an issue with sending the watermark (which has been fixed by send max watermark).
3. Causing great confusion to users
Overall, it is quite risky, and we can actually hang the compact after the writer, making its lifecycle very easy to control.
=> [flink] Introduce bypass append compact coordinator and worker

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CombinedTableCompactorSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
Only write manifest cache is conflict with Flink adaptive parallelism, we can only assert it when enabling write manifest cache.
=> [flink] Support Flink adaptive parallelism by default

paimon-common/src/main/java/org/apache/paimon/utils/InternalRowPartitionComputer.java, paimon-common/src/test/java/org/apache/paimon/utils/InternalRowPartitionComputerTest.java, paimon-core/src/main/java/org/apache/paimon/manifest/FileEntry.java, paimon-core/src/main/java/org/apache/paimon/mergetree/LookupFile.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommit.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java, paimon-core/src/main/java/org/apache/paimon/operation/PartitionExpire.java, paimon-core/src/main/java/org/apache/paimon/partition/PartitionUpdateTimeExpireStrategy.java, paimon-core/src/main/java/org/apache/paimon/partition/PartitionValuesTimeExpireStrategy.java, paimon-core/src/main/java/org/apache/paimon/table/sink/TableCommitImpl.java, paimon-core/src/test/java/org/apache/paimon/operation/PartitionExpireTest.java
We recently found that, if data is written into expired partitions, commit conflicts may occur.
This PR avoid 'trying to delete file' commit exception for expired partitions in `FileStoreCommit`, just ignore expired deleted files.
Close #3340
Cover #3518
`PartitionExpireTest.testDeleteExpiredPartition`
=> [core] Avoid 'trying to delete file' commit exception for expired partitions

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcUnawareBucketSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkTableSinkBase.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowUnawareBucketSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/UnawareBucketSink.java
#3936 hang the compact after the writer, making its lifecycle very easy to control.
So in the bounded streaming mode, we can have a compact topology.
=> [core] Remove bounded check for append compact topology

paimon-core/src/main/java/org/apache/paimon/table/source/DataSplit.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FileStoreSourceSplitReader.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/ReadOperator.java
Currently when reading `DataSplit`, we calculate `currentFetchEventTimeLag` with the latest file creation time in this split. This is incorrect because fetch event time lag should be defined by the oldest data in this split.
This PR changes this behavior by using the earliest file creation time to calculate fetch event time lag.
Tested by hand.
=> [flink] When reading DataSplit, calculate fetch event time lag with earliest file creation time instead of latest

docs/layouts/shortcodes/generated/flink_connector_configuration.html, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileStoreSource.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkSourceBuilder.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedContinuousFileSplitEnumerator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedContinuousFileStoreSource.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/MonitorFunction.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/AppendOnlyTableITCase.java
Now when stream read a unware bucket table with comsume_id and consumer.mode = exactly-once. SKEW will happy, this is a bug, now fix it.
=> [core] fix skew bug of stream read unware bucket table

paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/utils/SnapshotNotExistException.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/CreateTagsProcedureITCase.java
Creating failed : 
Creating successful :
=> [core] Throw SnapshotNotExistException when the snapshot for creating tag does not exist.

paimon-core/src/main/java/org/apache/paimon/manifest/IndexManifestEntry.java, paimon-core/src/main/java/org/apache/paimon/manifest/ManifestEntry.java, paimon-core/src/main/java/org/apache/paimon/manifest/ManifestFileMeta.java, paimon-core/src/main/java/org/apache/paimon/utils/VersionedObjectSerializer.java
The manifest schema should not be nullable, otherwise it will be wrapped with union null in avro which can not be read from Spark.
```sql
select * from
`avro`.`/Users/cathy/Desktop/tmp/spark-3.5.1-bin-hadoop3/warehouse/default.db/t/manifest/manifest-list-f1f00e99-398c-43e4-846f-6d88dad0aeb7-1`;
```
before
```
Caused by: org.apache.spark.sql.avro.IncompatibleSchemaException: Cannot convert Avro type ["null",{"type":"record","name":"record","namespace":"org.apache.paimon.avro.generated","fields":[{"name":"_VERSION","type":"int"},{"name":"_KIND","type":"int"},{"name":"_PARTITION","type":"bytes"},{"name":"_BUCKET","type":"int"},{"name":"_TOTAL_BUCKETS","type":"int"},{"name":"_FILE","type":["null",{"type":"record","name":"record__FILE","fields":[{"name":"_FILE_NAME","type":"string"},{"name":"_F …
```
=> [core] The manifest schema should not be nullable

pom.xml
We have used paimon embedded in our spark/flink jobs, and we want to make these jobs run on the aarch64 machines, this PR is to make this  feasible
aarch64 cpu arch compatibility: the compiled jar has been passed the alibaba's yoda tool check
=> chore: Update snappy version to 1.1.8.4 for aarch64 compatibility

paimon-core/src/main/java/org/apache/paimon/schema/SchemaChange.java, paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadTestBase.java, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkSchemaEvolutionITCase.java
Spark catalog `TableChange.UpdateColumnType` should only change the data type, but paimon always changes the nullable to true. This pr keeps the original field nullability.
To fix the issue:
```sql
CREATE TABLE t (a INT, b BIGINT NOT NULL) USING paimon;
ALTER TABLE t CHANGE COLUMN b TYPE string;
SHOW CREATE TABLE t; => b STRING NOT NULL
```
add test
no
=> [spark] Fix alter table column type change nullability

docs/layouts/shortcodes/generated/catalog_configuration.html, paimon-common/src/main/java/org/apache/paimon/options/CatalogOptions.java, paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveLocationTest.java
object store commit has no guarantee.
For safety, enable catalog lock when the file io is object store.
=> [core] Enable catalog lock when the file io is object store

paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/PaimonUtils.scala
Fix Comaptibility in getting NamedReference from spark32 to spark35 with a common api to get NamedReference
spark3.3+ ：
spark3.2：
then sql would error out as ：
=> [spark] Fix Comaptibility in getting NamedReference from spark32 to spark35

paimon-core/src/main/java/org/apache/paimon/sort/AbstractBinaryExternalMerger.java
Linked issue: close #3974 
[core] fix the issue that BinaryExternalMerger spill files may be leaked.
=>  [core] fix the issue that BinaryExternalMerger spill files may be leaked.

docs/layouts/shortcodes/generated/catalog_configuration.html, paimon-common/src/main/java/org/apache/paimon/options/CatalogOptions.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
Add a option for HiveCatalog to decide sync all properties to hms.
Currently HiveCatalog had not sync all tblproperties to hms，this not fitable for platform dev which need collect these metadata，so add option to control it default is false.
before fix:
```
CREATE TABLE paimon_q_02 (
`user_id` STRING COMMENT '任务用到的库',
`used_table` STRING COMMENT '任务用到的表',
`day` STRING COMMENT '按天进行分区')
USING paimon
PARTITIONED BY (day)
TBLPROPERTIES(
'file.format' = 'parquet',
'file.compression' = 'ZSTD')
```
then TABLE_PARAMS not contains 'file.format' = 'parquet', 'file.compression' = 'ZSTD':
```
"tableParams":{"owner":"yuydws","totalSize":"623","numRows":"-1","rawDataSize":"-1","provider":"paimon","COLUMN_STATS_ACCURATE":"false","numFiles":"1","transient_lastDdlTime":"1723718372" …
```
=> [hive] Add a option for HiveCatalog to decide sync all properties to hms

paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java, paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/DataTable.java, paimon-core/src/main/java/org/apache/paimon/table/FallbackReadFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/FileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/FileStoreTableFactory.java, paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/BucketsTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/FileMonitorTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/ReadOptimizedTable.java, paimon-core/src/main/java/org/apache/paimon/utils/BranchManager.java, paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java, paimon-core/src/test/java/org/apache/paimon/operation/OrphanFilesCleanTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionITCase.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
Currently `OrphanFilesClean` cannot handle data files created from branches and will mistakenly delete them. This PR modifies `OrphanFilesClean` so that it can support data from branches.
IT cases.
=> [core] OrphanFilesClean now support branches

paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/paimon/spark/PaimonScan.scala, paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/PaimonScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonInputPartition.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/execution/adaptive/DisableUnnecessaryPaimonBucketedScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/extensions/PaimonSparkSessionExtensions.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DisableUnnecessaryPaimonBucketedScanSuite.scala, pom.xml
This pr adds a new rule `DisableUnnecessaryPaimonBucketedScan` to support auto disable bucketed scan if the bucket scan is not actually effective i.e., there is no shuffle exchange been removed. This change is to avoid performance regression since the bucketed scan may have smaller parallelism than normal scan.
For example: a table with bucket key x but user join/group-by/partition-by on column y.
Note, this rule is inspired from Spark `DisableUnnecessaryBucketedScan` but work for v2 scan. 
Add test.
no
=> [spark] Support auto disable bucketed scan

paimon-core/src/main/java/org/apache/paimon/table/FallbackReadFileStoreTable.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BranchSqlITCase.java
Currently schema of main branch and fallback branch are validated in the constructor of `FallbackReadFileStoreTable`. However if the user mistakenly changed the schema of one branch, he won't be able to drop or alter this table, because the object cannot be created.
This PR fixes this issue by moving the validation before creating `TableScan`.
Existing tests should cover the change.
=> [core] Move schema validation of FallbackReadFileStoreTable from constructor to scanner

docs/content/maintenance/metrics.md, paimon-core/src/main/java/org/apache/paimon/operation/MemoryFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/operation/metrics/WriterBufferMetric.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/WriterOperatorTest.java
This PR adds a `numWriters` metrics to monitor the number of active writers in each parallelism. This metric can help us determine if the memory shortage is caused by too many writers.
* `PrimaryKeyWriterOperatorTest#testNumWritersMetric`
No changes in API or format.
Yes. Document is updated.
=> [core] Add numWriters metrics

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
alter table option support sync all properties to hms
testCreateCatalogWithSyncTblProperties
=> [hive] alter table option support sync all properties to hms

docs/content/flink/procedures.md, docs/content/maintenance/dedicated-compaction.md, docs/content/spark/procedures.md, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/CompactProcedure.java, paimon-flink/paimon-flink-1.18/src/test/java/org/apache/paimon/flink/procedure/ProcedurePositionalArgumentsITCase.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactActionFactory.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactDatabaseAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactDatabaseActionFactory.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/UnawareBucketCompactionTopoBuilder.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CompactDatabaseProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/CombinedTableCompactorSourceBuilder.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/CompactorSourceBuilder.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedAwareBatchSourceFunction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedUnawareBatchSourceFunction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/MultiTablesReadOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/MultiUnawareTablesReadOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/MultiTablesCompactorUtil.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactDatabaseActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/CompactorSourceITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/MultiTablesCompactorSourceBuilderITCase.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CompactProcedureTestBase.scala
If a partition has not received any new data writes for an extended period, we consider it to be a history partition. To further reduce the number of small files, it is necessary to perform a full compaction on history partitions.
This pr is to support doing a full compaction for history partition with a dedicated compaction job. Compared to dedicated compaction before:
you can set `history_time`, if a partition don't receive any new data for `history_time`, it will be full compacted.
**note: this feature is only supported in batch mode.**
`CompactDatabaseActionITCase#testHistoryPartitionCompact`
=> [flink] support history partition compaction in dedicated compaction job.

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/postgres/PostgresActionUtils.java
Mysql-CDC supports configuring parameter scan.incremental.snapshot.backfill.skip,Postgres-CDC supports  scan.incremental.snapshot.backfill.skip and scan.incremental.close-idle-reader.enabled  parameters
=> 【CDC】CDC supports more configuration parameters

paimon-core/src/main/java/org/apache/paimon/iceberg/AbstractIcebergCommitCallback.java, paimon-core/src/main/java/org/apache/paimon/iceberg/AppendOnlyIcebergCommitCallback.java, paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergCommitCallback.java, paimon-core/src/main/java/org/apache/paimon/iceberg/PrimaryKeyIcebergCommitCallback.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergConversions.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestEntry.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestFileMeta.java, paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergSnapshotSummary.java, paimon-core/src/main/java/org/apache/paimon/metastore/AddPartitionCommitCallback.java, paimon-core/src/main/java/org/apache/paimon/metastore/TagPreviewCommitCallback.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/sink/CommitCallback.java, paimon-core/src/test/java/org/apache/paimon/iceberg/IcebergCompatibilityTest.java, paimon-core/src/test/java/org/apache/paimon/table/sink/TableCommitTest.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonCommitTest.scala
In #3731 we introduce `IcebergCommitCallback` to create Iceberg metadata. In this PR we improve this class so that it can reuse Iceberg manifest files created before to create new Iceberg metadata.
Unit tests.
No changes in Paimon format.
=> [core] Support creating Iceberg metadata based on old ones

docs/content/spark/procedures.md, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CompactProcedureTestBase.scala
This pr uses Union(datasets) to replace submit each dataset by self to reudce driver limiation and overhead, and also remove the option `max_concurrent_jobs`, it is unncessary since we do not have such config for hash_fixed or hash_dynamic.
Pass CI
no
=> [spark] CompactUnAwareBucketTable uses union to replace submit job by self

docs/content/primary-key-table/compaction.md, docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/io/RecordLevelExpire.java, paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireWithMillisecondTest.java
Change-Id: Iced3e7a7e6facb3cd37c87a2ee87723c9ba6d5ab
Linked issue: close #3989 
Support setting the time field type for record level expire, it can be second or millisecond.
Add a UT int RecordLevelExpireWithMillisecondTest.java
=> [core] Support setting the time field type for record level expire

paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java, paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreScan.java, paimon-core/src/test/java/org/apache/paimon/table/source/StreamTableScanTest.java
Currently, there are issues with value filtering pushed down to the primary key table: 
1. We shouldn't apply full bucket filtering to incremental data, as it is meaningless and can lead to erroneous data.
2. Our determination of whether to push down value filtering varies between full and incremental data.
=> [core] Fix value filter pushdown in KeyValueFileStoreScan

paimon-core/src/main/java/org/apache/paimon/iceberg/AbstractIcebergCommitCallback.java, paimon-core/src/test/java/org/apache/paimon/iceberg/IcebergCompatibilityTest.java
Currently, new Iceberg compatible metadata are just appended to the metadata list. Without compaction, this list will become longer and longer, and the query speed will become slower.
This PR introduces compaction when creating Iceberg compatible metadata.
Modify existing random tests to fit in this change.
=> [core] Add compaction when creating Iceberg compatible metadata

paimon-arrow/src/main/java/org/apache/paimon/arrow/writer/ArrowFieldWriter.java, paimon-arrow/src/main/java/org/apache/paimon/arrow/writer/ArrowFieldWriters.java
FieldVecotor.setValueCount() takes much time
=> [arrow] Remove field vector set row count to avoid performance issue

paimon-arrow/src/main/java/org/apache/paimon/arrow/converter/Arrow2PaimonVectorConverter.java
Read timestamp vector and process by paimon self
=> [arrow] Read timestamp vector and process by paimon self

paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeWriter.java, paimon-core/src/main/java/org/apache/paimon/sort/BinaryExternalSortBuffer.java
`writeBuffer.clear()` should be put at finally block in case failure.
Pass CI
no
=> [core] MergeTreeWriter clear writer buffer at finally

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
Dynamic bucket mode should know the distribution strategy to filter own data of a task.
If AQE enabled, there is no fixed distribution strategy, task cannot know the its own bucket index.
=> [core] Dynamic bucket mode cannot work with AQE

paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/AbstractFlinkTableFactory.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java
=> [core] Throw more clear exception for rescale bucket -1

paimon-common/src/main/java/org/apache/paimon/utils/HllSketchUtil.java, paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldHllSketchAgg.java
Move hll util to paimon-commom from paimon-core, datasketches was shaded. To avoid class not found exception in runtime.
=> [core] fix hll class not found

paimon-core/src/main/java/org/apache/paimon/manifest/PartitionEntry.java, paimon-core/src/main/java/org/apache/paimon/table/FallbackReadFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/source/AbstractDataTableScan.java, paimon-core/src/main/java/org/apache/paimon/table/source/ReadOnceTableScan.java, paimon-core/src/main/java/org/apache/paimon/table/source/TableScan.java, paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java, paimon-core/src/test/java/org/apache/paimon/table/FallbackReadFileStoreTableTest.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumeratorTest.java
Expose method to get PartitionEntries from TableScan
No need, we just expose a forwarding method.
Add new method to `TableScan` interface.
No need.
=> [core] Expose method to get PartitionEntries from TableScan

docs/content/flink/sql-ddl.md, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogTest.java
Otherwise, it would be strange to create a table with a different path while the data is in another path.
=> [flink] FlinkCatalog should assert different path for creating table

paimon-core/src/main/java/org/apache/paimon/manifest/ManifestCommittable.java, paimon-core/src/main/java/org/apache/paimon/partition/actions/SuccessFileMarkDoneAction.java, paimon-core/src/main/java/org/apache/paimon/partition/file/SuccessFile.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionMarkDone.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionMarkDoneTrigger.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/PartitionMarkDoneTest.java
As long as the data is complete, there is no need to wait for the compaction to finish.
However, there are except cases, in deletion vectors mode, the zero level is ignored during batch reads. In this case, we should only wait for the compaction to complete.
Add `PartitionMarkDoneTest`.
=> [flink] Partition Mark done should not be affected by compaction

paimon-common/src/main/java/org/apache/paimon/format/FormatWriter.java, paimon-common/src/main/java/org/apache/paimon/io/BatchRecords.java, paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java, paimon-core/src/main/java/org/apache/paimon/io/RollingFileWriter.java, paimon-core/src/main/java/org/apache/paimon/io/SingleFileWriter.java, paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/table/sink/BatchTableWrite.java, paimon-core/src/main/java/org/apache/paimon/table/sink/TableWriteImpl.java, paimon-core/src/main/java/org/apache/paimon/utils/RecordWriter.java
Other compute engine (which process batch mainly) may need to add a batch record in one time. Not per row processing
Situation like schema evolution should be considered.
=> [core] Add batch record write interface for table.

paimon-core/src/main/java/org/apache/paimon/io/KeyValueFileReaderFactory.java
Async record reader should only work with .orc exactly
Only orc reader batch could be put in queue.
Others like parquet or other kind of orc, reuse the batch
=> [core] Async record reader should only work with .orc exactly

paimon-common/src/main/java/org/apache/paimon/format/FormatWriter.java, paimon-common/src/test/java/org/apache/paimon/format/FormatReadWriteTest.java, paimon-common/src/test/java/org/apache/paimon/format/SimpleColStatsExtractorTest.java, paimon-core/src/main/java/org/apache/paimon/io/SingleFileWriter.java, paimon-core/src/main/java/org/apache/paimon/utils/ObjectsFile.java, paimon-core/src/test/java/org/apache/paimon/FileFormatTest.java, paimon-core/src/test/java/org/apache/paimon/format/FlushingFileFormat.java, paimon-core/src/test/java/org/apache/paimon/mergetree/ChangelogMergeTreeRewriterTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/ContainsLevelsTest.java, paimon-format/src/main/java/org/apache/paimon/format/avro/AvroBulkWriter.java, paimon-format/src/main/java/org/apache/paimon/format/avro/AvroFileFormat.java, paimon-format/src/main/java/org/apache/paimon/format/orc/writer/OrcBulkWriter.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/writer/ParquetBulkWriter.java, paimon-format/src/test/java/org/apache/paimon/format/BulkFileFormatTest.java, paimon-format/src/test/java/org/apache/paimon/format/avro/AvroFileFormatTest.java, paimon-format/src/test/java/org/apache/paimon/format/orc/writer/OrcZstdTest.java, paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetColumnVectorTest.java, paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetReadWriteTest.java
1. Remove `FormatWriter.flush`, it is useless.
2. Rename `finish` to `close`.
=> [core] Refactor FormatWriter interface to remove flush

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLTestBase.scala
The `provider` prop is the identifier of datasource type, we should always set it
=> [spark] Auto fill provider prop when using paimon is not explicitly specified

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
Follow up https://github.com/apache/paimon/pull/3973
currently primary-key partition-key bucket-id not sync to hms, add these info to properties when sync hms.
user condition is to show metadata in platform.
=> [hive] Sync primary-key/partition-key/bucket-id when sync to hms

paimon-arrow/src/main/java/org/apache/paimon/arrow/converter/Arrow2PaimonVectorConverter.java, paimon-arrow/src/main/java/org/apache/paimon/arrow/reader/ArrowBatchReader.java, paimon-arrow/src/main/java/org/apache/paimon/arrow/vector/ArrowFormatCWriter.java, paimon-arrow/src/main/java/org/apache/paimon/arrow/vector/ArrowFormatWriter.java, paimon-arrow/src/test/java/org/apache/paimon/arrow/vector/ArrowFormatWriterTest.java
When merge, the last value will be referenced by maxKey. If reader close, the maxKey will be useless. We must avoid this situation
=> [arrow] Pass arrow reader last value by serializer to binary row

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/UnawareBucketSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/AppendBypassCoordinateOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/AppendBypassCoordinateOperatorFactory.java
The previous `AppendBypassCoordinateOperator` spent a lot of time generating compact tasks when there were many files, leading to significant blocking of normal threads and even resulting in checkpoint delays.
Modify it:
1. Scanning in a separate thread.
2. Make sure there is no message in mail box, and send compact tasks to downstream.
=> [flink] Bypass operator should never block checkpoint

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
=> [hive] repair table support sync all properties to hms 

paimon-core/src/main/java/org/apache/paimon/iceberg/AbstractIcebergCommitCallback.java, paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergPathFactory.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestFile.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestList.java, paimon-core/src/test/java/org/apache/paimon/iceberg/IcebergCompatibilityTest.java
Currently all previously generated Iceberg metadata are not deleted, so the number of metadata files will become larger.
This PR implements expiration of Iceberg metadata. When the number of Iceberg snapshots exceeds limit, related files will be removed.
Unit tests.
=> [core] Expire Iceberg metadata when number of snapshots exceeds limit

paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/pool/CachedClientPool.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/pool/HiveClientPool.java, paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/pool/TestCachedClientPool.java
1. Fix the bug linking Paimon to Hive's Catalog:
- The key of the cached item has not overridden the HashCode and Equals methods.
- The value of the cached item, that is, when creating the Hive client, the UGI information was not passed.
2. Add Paimon's options as the cache key to simplify user usage。
```
DROP CATALOG paimon_thrift;
CREATE EXTERNAL CATALOG `paimon_thrift`
PROPERTIES (
"type"  =  "paimon",
"paimon.catalog.type"  =  "hive",
"paimon.catalog.warehouse"  =  "hdfs://localhost:9000/user/hive/warehouse/"
"hive.metastore.uris"  =  "thrift://localhost:9083",
'paimon.option.client-pool-cache.keys'='ugi,conf:*'
);
set catalog paimon_thrift;
show databases;
```
1. Fix before
2. Fix after
=> [hive] bugfix jdbc paimon hive client pool (#3004)

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactDatabaseAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CombinedTableCompactorSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTablesStoreCompactOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/MultiTablesCompactorUtil.java
make compaction completely asynchronous in dedicated compaction job
add dynamic options for tables in dedicated compaction job:
`num-sorted-run.stop-trigger = 2147483647`
`sort-spill-threshold = 10`
`lookup-wait = false`
=> [flink][spark] make compaction completely asynchronous in dedicated compaction job

paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreScan.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java
[core] fix the issue of incorrect filtering in filterWholeBucketAllFiles.
Linked issue: close #4065
=> [core] fix the issue of incorrect filtering in filterWholeBucketAllFiles.

docs/content/flink/procedures.md, docs/content/spark/procedures.md, paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java, paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CreateTagFromTimestampProcedure.java, paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/CreateTagFromTimestampProcedureITCase.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CreateTagFromTimestampProcedure.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CreateTagFromTimestampProcedureTest.scala
Now, Supports creating tags from snapshots commit-time.
The procedure will find the first snapshot that commit-time is greater than the specified timestamp.
```CALL sys.create_tag_from_timestamp(`table` => 'default.T', `tag` => 'my_tag', `timestamp` => 1724404318750,  time_retained => '1 d')```
=> [core] Supports creating tags from snapshots commit-time.

paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java, paimon-core/src/main/java/org/apache/paimon/FileStore.java, paimon-core/src/main/java/org/apache/paimon/index/IndexFileMeta.java, paimon-core/src/main/java/org/apache/paimon/manifest/IndexManifestEntry.java, paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedFileStore.java, paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/FallbackReadFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/FormatTable.java, paimon-core/src/main/java/org/apache/paimon/table/ReadonlyTable.java, paimon-core/src/main/java/org/apache/paimon/table/Table.java, paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/BucketsTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/FileMonitorTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/ReadOptimizedTable.java
Same to manifestListReader and manifestFileReader. We can also make indexManifestFileReader public.
=> [core] Add Table.indexManifestFileReader

paimon-arrow/src/main/java/org/apache/paimon/arrow/ArrowBundleRecords.java, paimon-arrow/src/test/java/org/apache/paimon/arrow/vector/ArrowFormatWriterTest.java
Wrap VectorSchemaRoot as a BundleRecords.
=> [arrow] Add ArrowBundleRecords for a VectorSchemaRoot records.

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/table/source/DataTableStreamScan.java, paimon-core/src/test/java/org/apache/paimon/table/source/StartupModeTest.java
Support stream read with delay duration.
real user scenario is algorithm partital update, user use lake table join hbase/redis dim table, but dim table update is delay, so need delay read for stream lake table. this pr is aim to support it with add an option to control the delay time.
=> [core] Support stream read with delay duration

docs/content/flink/procedures.md, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CreateTagFromWatermarkProcedure.java, paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/CreateTagFromWatermarkProcedureITCase.java
Linked pr:  #4051 
Add procedure to support creating tag from snapshots watermark.
```CALL [catalog.]sys.create_tag_from_watermark('identifier', 'tagName', watermark, time_retained)```
=> [flink] Supports creating tags from snapshots watermark.

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RewriteFileIndexProcedure.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/RewriteFileIndexProcedureITCase.java
Linked issue: close https://github.com/apache/paimon/issues/4004
=> [flink] Fix partition filter mismatch the column index

paimon-spark/paimon-spark-3.3/src/main/java/org/apache/spark/sql/connector/read/SupportsReportOrdering.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/execution/adaptive/DisableUnnecessaryPaimonBucketedScan.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/BucketedTableQueryTest.scala
This pr makes `PaimonScan` support `SupportsReportOrdering`. For primary key table, we will do a sorted run during write so the primary keys in one file are always ordered, and skip optimization if the contains a rawConvertible split since we will not do merge sort read.
This can help eliminate local sort for smj/sorted agg etc..
add tests
no
=> [spark] Support report scan ordering

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendBypassCompactWorkerOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/AppendBypassCoordinateOperator.java
It should be a separate node, and no chain is good to rescale parallelism.
=> [flink] Do not chain for AppendBypassCompactWorkerOperator

paimon-spark/paimon-spark-3.1/pom.xml, paimon-spark/paimon-spark-3.2/pom.xml, paimon-spark/paimon-spark-3.3/pom.xml, paimon-spark/paimon-spark-3.4/pom.xml, paimon-spark/paimon-spark-3.5/pom.xml, paimon-spark/paimon-spark-common/pom.xml
Different Spark branch uses different zstd-jni version, so it's better to use Spark's zstd-jni to avoid conflict. The reason why Paimon includes zstd-jni is: Flink uses airlift to support zstd so Flink distribution does not include zstd-jni.
manually test, after this pr did not include `com/github/luben/zstd`
no
=> [spark] Spark package should exclude zstd-jni

paimon-arrow/src/main/java/org/apache/paimon/arrow/vector/ArrowFormatCWriter.java, paimon-arrow/src/main/java/org/apache/paimon/arrow/vector/ArrowFormatWriter.java, paimon-arrow/src/test/java/org/apache/paimon/arrow/vector/ArrowFormatWriterTest.java
=> [arrow] ArrowFormatWriter shouldn't set allowUpperCase=false by default

paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/spark/sql/PaimonStatsUtils.scala, paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/spark/sql/PaimonStatsUtils.scala, paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/spark/sql/PaimonStatsUtils.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonAnalyzeTableColumnCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/PaimonStatsUtils.scala
Add the catalog and database info to the `TableIdentifier`, so that Spark can obtain more info when calling `calculateSingleLocationSize`.
N/A
No.
No.
=> [spark] Add catalog and database info for spark analyze

paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java, paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BranchSqlITCase.java
If set non-existed fallback branch, user cannot access the table.
=> [flink] Check that cannot set non-existed fallback branch

paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-common/src/main/java/org/apache/paimon/utils/StringUtils.java, paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java
Currently paimon not restrict consumer-id cannot be a blank string which may not fitable, this pr is aim to fix it.
=> [core] Check consumer-id cannot be blank string

paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
Now when clean tag file, skip datafile if exception happen.
Also skip clean manifest if exception happen.
=> [core] skip clean tag manifest file if exception

docs/config.toml, docs/content/program-api/flink-api.md
Documentation 
The doc page about programmatic Flink API doesn't refer to the latest paimon-flink-_flink_version_ package. This PR factors out the version and bumps it to 1.20.0
built the site and tested the page locally
NA
NA
=> [doc] Factor out most recent Flink version to docs config, and bump it

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonAnalysis.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLTestBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/InsertOverwriteTableTestBase.scala
for char we should auto pad to respect conf.charVarcharAsString when writing
=> [spark] Add string length check for char while writing

paimon-core/src/main/java/org/apache/paimon/io/StatsCollectingSingleFileWriter.java
Add limit for writeBundle interface
=> [core] Interface writeBundle should be with existing statExtractor

paimon-common/src/main/java/org/apache/paimon/utils/FileBasedBloomFilter.java
Cache manager cause out of memory while lookup merge
=> [core] FileBasedBloomFilter should not be pass private member to cache manager.

docs/content/flink/sql-write.md
According to the code display that clustering is only supported the bucket unaware append table.
=> [doc] Fix clustering is only supported the bucket unaware append table.

paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java, paimon-core/src/main/java/org/apache/paimon/table/system/SchemasTable.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
Before getting schema from SchemaManager , we should determine if a schema exists.
=> [core] fix query schema throw exception when specifying schema_id does not exist

paimon-common/src/main/java/org/apache/paimon/utils/ThreadPoolUtils.java
This fixes:
https://github.com/apache/paimon/actions/runs/10645769652/job/29511901738
```
Caused by: java.lang.IllegalStateException: Trying to access closed classloader. Please check if you store classloaders directly or indirectly in static fields. If the stacktrace suggests that the leak occurs in a third party library and cannot be fixed immediately, you can disable this check with the configuration 'classloader.check-leaked-classloader'.
```
Flink will close previous classloader, so in the async thread pool, we should set thread classloader.
=> [core] Fix 'Trying to access closed classloader' in Flink

paimon-core/src/main/java/org/apache/paimon/index/IndexFileHandler.java, paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java, paimon-core/src/test/java/org/apache/paimon/operation/KeyValueFileStoreScanTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/DeletionVectorITCase.java
Fix #4120
In `SnapshotReaderImpl`, we should use `Snapshot` to read index instead of snapshot id, because for tag, there is no snapshot file, but only tag file.
=> [core] Fix tag read for deletion vectors table

paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexOptions.java, paimon-common/src/main/java/org/apache/paimon/security/SecurityConfiguration.java, paimon-common/src/main/java/org/apache/paimon/utils/ParameterUtils.java, paimon-common/src/main/java/org/apache/paimon/utils/StringUtils.java, paimon-core/src/main/java/org/apache/paimon/consumer/ConsumerManager.java, paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java, paimon-core/src/main/java/org/apache/paimon/utils/BranchManager.java, paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java, paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java, paimon-e2e-tests/src/test/java/org/apache/paimon/tests/cdc/MySqlCdcE2eTestBase.java, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/CompactDatabaseProcedure.java, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/CompactProcedure.java, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/RemoveOrphanFilesProcedure.java, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/RewriteFileIndexProcedure.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/postgres/PostgresRecordParser.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CloneAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/CloneSourceBuilder.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CompactDatabaseProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CompactProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ProcedureBase.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RemoveOrphanFilesProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RepairProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RewriteFileIndexProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RollbackToProcedure.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedure.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RepairProcedure.java
StringUtils#isBlank is redundant, and it's not as clear as isNullOrWhitespaceOnly.
=> Remove StringUtils#isBlank which is same with #isNullOrWhitespaceOnly

docs/layouts/shortcodes/generated/core_configuration.html, docs/layouts/shortcodes/generated/orc_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-common/src/main/java/org/apache/paimon/format/FileFormat.java, paimon-common/src/main/java/org/apache/paimon/format/FileFormatFactory.java, paimon-format/src/main/java/org/apache/paimon/format/OrcOptions.java, paimon-format/src/main/java/org/apache/paimon/format/orc/OrcFileFormat.java, paimon-format/src/main/java/org/apache/paimon/format/orc/OrcWriterFactory.java, paimon-format/src/test/java/org/apache/paimon/format/avro/AvroFileFormatTest.java, paimon-format/src/test/java/org/apache/paimon/format/avro/AvroFormatReadWriteTest.java, paimon-format/src/test/java/org/apache/paimon/format/orc/OrcFileFormatTest.java, paimon-format/src/test/java/org/apache/paimon/format/orc/OrcFormatReadWriteTest.java, paimon-format/src/test/java/org/apache/paimon/format/orc/writer/OrcBulkWriterTest.java, paimon-format/src/test/java/org/apache/paimon/format/orc/writer/OrcZstdTest.java, paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetFileFormatTest.java, paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetFormatReadWriteTest.java
write.batch-size should be in CoreOptions rather than OrcOptions.
=> [orc] Move config write.batch-size to CoreOptions

paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/BucketedTableQueryTest.scala
This pr adds test for buceted scan with partitioned table. Although we do not support bucketed scan with multi-bucket columns, there is a chance to support multi primary keys if  primary keys contains partition column.
add test
no
=> [spark] Add tests for buceted scan with partitioned table

docs/content/primary-key-table/compaction.md, docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/io/RecordLevelExpire.java
Change-Id: I26ed6b5ab4a4c9e93bda22dfcc6f1b703bb664ce
Support seconds-long in record level time field type
=> [core]Support seconds-long in record level time field type

paimon-common/src/main/java/org/apache/paimon/lookup/hash/HashLookupStoreWriter.java
file.deleteOnExit method will stat in memory forever
=> [core] Remove deleteOnExit method to avoid out of memory

paimon-core/src/main/java/org/apache/paimon/table/system/ManifestsTable.java, paimon-core/src/test/java/org/apache/paimon/table/system/ManifestsTableTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
… 
Currently user can only query table manifest info of snapshot from scan.snapshot-id, due to snapshot manager of table, some early snapshot would clean. So maybe need offer user about snapshot range when user query a snapshot id which not exist.
=> [core] Manifest table query throw exception with range of snapshot when snapshot id not exist

paimon-core/src/main/java/org/apache/paimon/codegen/CodeGenUtils.java
The cache in CodeGenUtils is already soft values, we don't need to have TTL. After removing TTL, we can create less classes.
=> [core] Remove cache timeout in CodeGenUtils

paimon-core/src/main/java/org/apache/paimon/manifest/FileEntry.java, paimon-core/src/main/java/org/apache/paimon/manifest/ManifestEntry.java, paimon-core/src/main/java/org/apache/paimon/manifest/ManifestEntrySerializer.java, paimon-core/src/main/java/org/apache/paimon/manifest/SimpleFileEntry.java, paimon-core/src/main/java/org/apache/paimon/manifest/SimpleFileEntrySerializer.java, paimon-core/src/main/java/org/apache/paimon/operation/ManifestFileMerger.java, paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileMetaTest.java
In Manifest Full Merge, we can just keep deleted Identifiers in memory to reduce OOM.
To do this, we must to add extraFiles to Identifier, because it is a kind of changing.
=> [core] Only keep deleted Identifiers in memory for Manifest full merge

paimon-core/src/main/java/org/apache/paimon/schema/SchemaMergingUtils.java, paimon-core/src/test/java/org/apache/paimon/schema/SchemaMergingUtilsTest.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DataFrameWriteTest.scala
This pr revist the merge schema behavior:
- respect the original data type nullability
- skip commit schema if only target type nullability changed before merging
- support merge decimal type if both of them have same scale
add test
no
=> [core] Revisit merge schema to fix issues

paimon-codegen/src/main/java/org/apache/paimon/codegen/CodeGeneratorImpl.java, paimon-codegen/src/main/scala/org/apache/paimon/codegen/EqualiserCodeGenerator.scala, paimon-codegen/src/test/java/org/apache/paimon/codegen/EqualiserCodeGeneratorTest.java, paimon-common/src/main/java/org/apache/paimon/codegen/CodeGenerator.java, paimon-core/src/main/java/org/apache/paimon/codegen/CodeGenUtils.java
=> [core] Introduce projection fields to EqualiserCodeGenerator

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldNestedUpdateAgg.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java
=> [core] Fix ArrayIndexOutOfBoundsException when updating nested fields with null values.

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBActionUtils.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/postgres/PostgresActionUtils.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
Currently paimon cdc does not support scan.startup.mode=snapshot, but flink-cdc 3.x(mysql、pg、mongdb cdc) already supports shapshot mode
=> [cdc] paimon cdc support snapshot mode

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
We write data with flink stream and run a dedicated compaction with flink. If the compaction commit message is too large and commit time is too long followed, commit will fail and enter an infinite loop.
=> [core] Add commit max retries if commit failed

docs/layouts/shortcodes/generated/core_configuration.html, paimon-codegen/src/main/scala/org/apache/paimon/codegen/EqualiserCodeGenerator.scala, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java, paimon-core/src/main/java/org/apache/paimon/utils/ChangelogDeduplicateEqualiserSupplier.java, paimon-core/src/main/java/org/apache/paimon/utils/ValueEqualiserSupplier.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/FullChangelogMergeFunctionWrapperTestBase.java, paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapperTest.java
Change-Id: Ida465e4902f13592df552be731da1530fdeaaeb0
Linked issue: close #4095
Support  specifying fields that are ignored for comparison while generating -U, +U changelog for the same record. I will use the changelog-producer.row-deduplicate-ignore-fields to decide which fields are ignored.This configuration is only valid for the changelog-producer.row-deduplicate is true.
Add UT in LookupChangelogMergeFunctionWrapperTest.java
=> [core]Support ignoring specified fields while generating -U, +U changelog for the same record

docs/content/maintenance/system-tables.md, paimon-core/src/main/java/org/apache/paimon/manifest/BucketEntry.java, paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReader.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java, paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/BucketsTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/CompactBucketsTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/SystemTableLoader.java, paimon-core/src/test/java/org/apache/paimon/table/system/BucketsTableTest.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/MultiAwareBucketTableScan.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/BucketsRowChannelComputer.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/CombinedTableCompactorSourceBuilder.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/CompactorSourceBuilder.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/MultiTablesReadOperator.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java
Now Spark Bucketed table Compact will plan all files to know the buckets. We can introduce `BucketEntry` just like `PartitionEntry` to reduce memory usage.
This PR:
1. Introduce bucket entries to optimize Spark compact
2. Add BucketsTable system table to show bucket information.
1. Existed tests.
2. `BucketsTableTest`.
=> [core] Introduce bucket entries to optimize Spark compact

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java, paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java, paimon-core/src/main/java/org/apache/paimon/io/DataFilePathFactory.java, paimon-core/src/main/java/org/apache/paimon/operation/MergeFileSplitRead.java, paimon-core/src/main/java/org/apache/paimon/utils/FileStorePathFactory.java, paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java, paimon-core/src/test/java/org/apache/paimon/format/FileFormatSuffixTest.java, paimon-core/src/test/java/org/apache/paimon/io/DataFilePathFactoryTest.java, paimon-core/src/test/java/org/apache/paimon/io/KeyValueFileReadWriteTest.java, paimon-core/src/test/java/org/apache/paimon/io/RollingFileWriterTest.java, paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileMetaTestBase.java, paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileTest.java, paimon-core/src/test/java/org/apache/paimon/manifest/ManifestListTest.java, paimon-core/src/test/java/org/apache/paimon/mergetree/ChangelogMergeTreeRewriterTest.java, paimon-core/src/test/java/org/apache/paimon/operation/OrphanFilesCleanTest.java, paimon-core/src/test/java/org/apache/paimon/utils/FileStorePathFactoryTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/TestChangelogDataReadWrite.java, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkFileIndexITCase.java, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkWriteITCase.java, paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkWriteWithKyroITCase.java
Add conf `file.prefix` to control the file name prefix of data files.
=> [core] Support custom data file name prefix

docs/content/flink/procedures.md, docs/content/maintenance/manage-snapshots.md, docs/content/spark/procedures.md, paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/RemoveOrphanFilesProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RemoveOrphanFilesAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionFactory.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RemoveOrphanFilesProcedure.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionITCase.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedure.java
Allow users to freely adjust the number of thread for removing orphan files.
=> [core] add parallelism argument for remove orphan files

paimon-common/src/main/java/org/apache/paimon/utils/IteratorResultIterator.java, paimon-common/src/main/java/org/apache/paimon/utils/IteratorWithException.java, paimon-format/src/main/java/org/apache/paimon/format/avro/AvroBulkFormat.java, paimon-format/src/test/java/org/apache/paimon/format/avro/AvroFileFormatTest.java
Many features, such as `OrphanFilesClean`, in Paimon checks for specific `IOException`s (for example, `FileNotFoundException` or `EOFException`) and deal with them properly. However avro readers currently wraps all `IOException`s into `AvroRuntimeException`, thus we cannot know what the real exception is.
This PR unwraps `AvroRuntimeException` and throws the real `IOException` in avro readers.
Unit tests.
=> [avro] Unwrap AvroRuntimeException and throw the real IOException

paimon-common/src/main/java/org/apache/paimon/types/ArrayType.java, paimon-common/src/main/java/org/apache/paimon/types/BigIntType.java, paimon-common/src/main/java/org/apache/paimon/types/BinaryType.java, paimon-common/src/main/java/org/apache/paimon/types/BooleanType.java, paimon-common/src/main/java/org/apache/paimon/types/CharType.java, paimon-common/src/main/java/org/apache/paimon/types/DataType.java, paimon-common/src/main/java/org/apache/paimon/types/DateType.java, paimon-common/src/main/java/org/apache/paimon/types/DecimalType.java, paimon-common/src/main/java/org/apache/paimon/types/DoubleType.java, paimon-common/src/main/java/org/apache/paimon/types/FloatType.java, paimon-common/src/main/java/org/apache/paimon/types/IntType.java, paimon-common/src/main/java/org/apache/paimon/types/LocalZonedTimestampType.java, paimon-common/src/main/java/org/apache/paimon/types/MapType.java, paimon-common/src/main/java/org/apache/paimon/types/MultisetType.java, paimon-common/src/main/java/org/apache/paimon/types/RowType.java, paimon-common/src/main/java/org/apache/paimon/types/SmallIntType.java, paimon-common/src/main/java/org/apache/paimon/types/TimeType.java, paimon-common/src/main/java/org/apache/paimon/types/TimestampType.java, paimon-common/src/main/java/org/apache/paimon/types/TinyIntType.java, paimon-common/src/main/java/org/apache/paimon/types/VarBinaryType.java, paimon-common/src/main/java/org/apache/paimon/types/VarCharType.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonStatistics.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTestBase.scala
`SupportsReportStatistics#estimateStatistics` should report the statistics after do column pruning, filter push down. This pr fixes it does not do column pruning. In addition, we should consider the metadata column size.
Introduce `defaultSize` method for `DataType`, so that we can get the size in bytes without column statistics.
add test
no
=> [spark] Fix reported statistics does not do column pruning

docs/content/spark/procedures.md, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/MigrateDatabaseProcedure.java, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/MigrateFileProcedure.java, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/MigrateTableProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MigrateDatabaseAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MigrateDatabaseActionFactory.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MigrateFileAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MigrateFileActionFactory.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MigrateTableAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MigrateTableActionFactory.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/MigrateDatabaseProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/MigrateFileProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/MigrateTableProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/TableMigrationUtils.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/migrate/HiveMigrator.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/procedure/MigrateDatabaseProcedureITCase.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/procedure/MigrateFileProcedureITCase.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/procedure/MigrateTableProcedureITCase.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/MigrateFileProcedure.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/MigrateTableProcedure.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/utils/TableMigrationUtils.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/MigrateFileProcedureTest.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/MigrateTableProcedureTest.scala
Currently migrate table/file/database cannot set thread parallelism, user can not overclock cpu to improve migrate speed or reduce cpu cost for avoid impacting other process in machine , this pr is support parallelism change.
=> [hive] HiveMigrator support set parallelism for procedures

paimon-core/src/main/java/org/apache/paimon/consumer/Consumer.java, paimon-core/src/main/java/org/apache/paimon/operation/ChangelogDeletion.java, paimon-core/src/test/java/org/apache/paimon/table/ChangelogExpireTest.java, paimon-core/src/test/java/org/apache/paimon/table/IndexFileExpireTableTest.java
Just two small bugs:
1 Check index file exists before read
2 Try more times for table consumer read (Rename may not be atomic)
=> [core] Changelog expire should check index file existence

paimon-common/src/main/java/org/apache/paimon/options/Options.java, paimon-common/src/main/java/org/apache/paimon/utils/SerializableConsumer.java, paimon-common/src/main/java/org/apache/paimon/utils/SerializablePredicate.java, paimon-core/src/main/java/org/apache/paimon/operation/LocalOrphanFilesClean.java, paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java, paimon-core/src/main/java/org/apache/paimon/table/FallbackReadFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/FileStoreTableFactory.java, paimon-core/src/test/java/org/apache/paimon/operation/LocalOrphanFilesCleanTest.java, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/RemoveOrphanFilesProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RemoveOrphanFilesAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionFactory.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/orphan/FlinkOrphanFilesClean.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RemoveOrphanFilesProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/BoundedOneInputOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/BoundedTwoInputOperator.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ActionITCaseBase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/BranchActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CloneActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactDatabaseActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ConsumerActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/DropPartitionActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/MarkPartitionDoneActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/MergeIntoActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RewriteFileIndexActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RollbackToActionITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/TagActionITCase.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedure.java
For large tables, there are a lot of files, and the current single-machine program may lead to OOM (Out of Memory) issues. We should introduce distributed execution to avoid OOM and performance problems.
=> [flink] Introduce dedecate job for orphan files clean

paimon-common/src/main/java/org/apache/paimon/compression/ZstdBlockCompressor.java
=> [core] Avoid loading zstd-jni collisions

paimon-core/src/main/java/org/apache/paimon/table/system/ReadOptimizedTable.java, paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
Linked issue: close #4191
[core] disable streaming read of ReadOptimizedTable which has primary-key.
1. org.apache.paimon.table.PrimaryKeyFileStoreTableTest#testStreamingReadOptimizedTable
No
No
=> [core] disable streaming read of ReadOptimizedTable which has primary-key.

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncDatabaseActionBase.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseAction.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseAction.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarSyncDatabaseAction.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/NewTableSchemaBuilder.java
=> [cdc] Kafka database sync new table shouldn't require primary keys

paimon-common/src/test/java/org/apache/paimon/format/FormatReadWriteTest.java
Add test case for format read nested type with purning
=> [test] Add test case for format read nested type with purning

paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java, paimon-core/src/main/java/org/apache/paimon/utils/BranchManager.java, paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java, paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java, paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java
hotfix branch manager gets schema, tag and snapshot paths method to reduce constant string usage.
=> [hotfix] hotfix branch manager gets schema, tag and snapshot paths method to reduce constant string usage.

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcSinkBuilder.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcUnawareBucketSink.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java
rebalance it to make sure schema change work to avoid infinite loop.
No test, it is hard to reproduce in the unit test.
=> [cdc] Unaware bucket cdc sink should not chain

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonStatistics.scala
fix unspecified value parameter when using PaimonMetadataColumn.get method
https://github.com/apache/paimon/actions/runs/10933145723/job/30351130554#step:4:4636
=> [hotfix] fix unspecified value parameter when using PaimonMetadataColumn.get method

paimon-spark/paimon-spark-3.5/pom.xml, paimon-spark/paimon-spark-common/pom.xml
Bump Spark version from 3.5.2 to 3.5.3. Including some bug fix which may affect Paimon, e.g., [bucketed join](https://github.com/apache/spark/pull/47735)
Pass CI
No
=> [spark] Bump Spark 3.5.3

paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalStartingScanner.java, paimon-core/src/main/java/org/apache/paimon/utils/ManifestReadThreadPool.java
Sequence batch should not be used; it only optimizes memory, and we only need to return the results in order.
Randomly execution can improve performance.
=> [core] Optimize IncrementalStartingScanner to randomlyExecute

paimon-core/src/main/java/org/apache/paimon/operation/LocalOrphanFilesClean.java
Read manifest to find used files will cost time, if the candidates is empty, we don't need to do that
=> [core] Reduce unnecessary manifest reading during orphan clean

paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeIntoResolver.scala, paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeIntoResolver.scala, paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeIntoResolver.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeIntoResolver.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeIntoResolverBase.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/MergeIntoNotMatchedBySourceTest.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTestBase.scala
Fix resolve merge into with alias
```sql
MERGE INTO target t
USING source s
ON t.a = s.a
WHEN MATCHED AND t.a = 5 THEN
UPDATE SET t.b = s.b + t.b
```
```text
cannot resolve t.a from SubqueryAlias t
+- SubqueryAlias spark_catalog.default.target
+- RelationV2[a#0, b#1, c#2] spark_catalog.default.target default.target
java.lang.RuntimeException: cannot resolve t.a from SubqueryAlias t
+- SubqueryAlias spark_catalog.default.target
+- RelationV2[a#0, b#1, c#2] spark_catalog.default.target default.target
at org.apache.paimon.spark.catalyst.analysis.expressions.ExpressionHelper.$anonfun$resolveExpression$1(ExpressionHelper.scala:50)
at org.apache.paimon.spark.catalyst.analysis.expressions.ExpressionHelper.$anonfun$resolveExpression$1$adapted(ExpressionHelper.scala:48)
at …
```
=> [spark] Fix resolve merge into with alias

docs/content/spark/procedures.md, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/MigrateDatabaseProcedure.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/MigrateDatabaseProcedure.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/MigrateDatabaseProcedure.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/utils/TableMigrationUtils.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/MigrateDatabaseProcedureTest.scala
Currently spark side not support migrate_database procedure which can improve user to migrate their tables, this pr is aimed to support it.
=> [spark] Support migrate database procedure for spark

paimon-core/src/main/java/org/apache/paimon/Snapshot.java, paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java
This PR adds a more detailed error message to the snapshot expiration process, showing users a possible cause of the FileNotFoundException they may face and the recommended solution to it.
A UT has been added to verify the error message in case of concurrent snapshot expiration.
This PR does not affect API or format.
This change does not need documentation
=> [core] Improve error message for concurrent snapshot expiration

paimon-core/src/main/java/org/apache/paimon/table/ExpireSnapshotsImpl.java, paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
If there is two writing job directly aiming to two different partitions, then there'll come up a conflict while expiring snapshot. This should be avoided.
=> [core] Check snapshot existence before expire

paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/utils/BranchManager.java, paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java, paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
We can just return current table if the target branch of `switchToBranch` is same with current. For example, `RemoveOrphanFiles` will always do `switchToBranch` for main branch.
Pass CI
no
=> [core] Fast return current table if target branch is same with current

paimon-core/src/main/java/org/apache/paimon/AppendOnlyFileStore.java, paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFixedBucketFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyUnawareBucketFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java, paimon-core/src/main/java/org/apache/paimon/operation/MemoryFileStoreWrite.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTablesStoreCompactOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/NoopStoreSinkWriteState.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowUnawareBucketSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCompactOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWrite.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWriteState.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWriteStateImpl.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/TableWriteOperator.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/UnawareBucketAppendOnlyTableITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/FlinkSinkTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/StoreCompactOperatorTest.java
Currently Paimon writer operators in Flink have states, which record the `commitUser` (for all writers) and the list of active buckets (for lookup or full-compaction changelog producer). These states prevent a writer object to be closed too early and cause conflicts.
However for append only unaware bucket writers, because they only create new files, there is no conflict. So for these writers we can remove Flink state. This optimization is also useful for bounded stream jobs, because when chaining source and write operator together, if some source parallelism have finished, checkpoint cannot be performed if there are union list states in the operators which are still running.
IT case.
=> [flink] Remove state from append only unaware bucket writer

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ExpireSnapshotsProcedure.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/ExpireSnapshotsProcedureTest.scala
- change param `older_than` type from TimeStampType to StringType, TimeStampType is not easy to understand and use.
- add new param `time_retained`, which can call `expire_snapshots` periodically. `older_than` is suitable for one-time call.
=> [spark] Adjust ExpireSnapshotsProcedure param type

paimon-core/src/main/java/org/apache/paimon/table/source/DataTableStreamScan.java, paimon-core/src/test/java/org/apache/paimon/table/TableTestBase.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/CompactionDiffFollowUpScanner.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FullCacheLookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/IncrementalCompactDiffSplitRead.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupCompactDiffRead.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupDataTableScan.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupFileStoreTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupStreamingReader.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PrimaryKeyPartialLookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/TableScanUtils.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/LookupTableTest.java
Linked issue: close #3868 
[flink] refactor the code of the lookup and support computing the changelog generated by compact during read time.
This is used when changelog producer is none, but CoreOptions#needLookup is true and the table is used as a dim table.
- org.apache.paimon.flink.lookup.LookupTableTest#testFullCacheLookupTableWithForceLookup
- org.apache.paimon.flink.lookup.LookupTableTest#testPartialLookupTableWithForceLookup
No
=> [flink] refactor the code of the lookup and support computing the changelog generated by compact during read time.

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
This PR provides default parallelism configuration for sink operators, in cases where undefined/adaptive parallelism has not been supported.
Existing UTs are modified to verify that the cases mentioned above can function correctly now.
No API or format is changed
No documentation needed. The existing unsupported cases had not been documented, so no modification needed for documents.
=> [flink] Set default parallelism for sink in cases where AQE not supported

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-common/src/main/java/org/apache/paimon/TableType.java, paimon-common/src/main/java/org/apache/paimon/options/CatalogOptions.java, paimon-common/src/main/java/org/apache/paimon/table/CatalogTableType.java, paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalogFactory.java, paimon-core/src/test/java/org/apache/paimon/catalog/CatalogFactoryTest.java, paimon-core/src/test/java/org/apache/paimon/table/system/CatalogOptionsTableTest.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
No we have multiple tables:
1. normal paimon table
2. format table
3. Flink materialized table
We can have a type option to describe this.
=> [core] Introduce type option

paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-common/src/main/java/org/apache/paimon/format/FileFormat.java, paimon-common/src/main/java/org/apache/paimon/format/FileFormatFactory.java, paimon-common/src/main/java/org/apache/paimon/options/Options.java, paimon-core/src/main/java/org/apache/paimon/format/FileFormatDiscover.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestFile.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestList.java, paimon-core/src/main/java/org/apache/paimon/io/KeyValueFileWriterFactory.java, paimon-core/src/main/java/org/apache/paimon/migrate/FileMetaUtils.java, paimon-core/src/test/java/org/apache/paimon/FileFormatTest.java, paimon-format/src/main/java/org/apache/paimon/format/avro/AvroFileFormat.java, paimon-format/src/main/java/org/apache/paimon/format/orc/OrcFileFormat.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetFileFormat.java, paimon-format/src/test/java/org/apache/paimon/format/orc/OrcFileFormatTest.java, paimon-format/src/test/java/org/apache/paimon/format/orc/writer/OrcBulkWriterTest.java, paimon-format/src/test/java/org/apache/paimon/format/orc/writer/OrcZstdTest.java, paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetFileFormatTest.java
Currently, format prefix in option keys are removed before sending into the constructor of each format. However, most formats (orc, parquet) still recover these prefixes in their code, so it would be better to let the format itself deal with these prefixes.
Also, we're going to introduce a special `compacted changelog` format, which wraps other file formats. However with the current code, each format can only see the options related to itself. If option keys are processed in each format, we can see options for other formats and keep what we need.
This PR process option keys in each format.
=> [format] Format prefix in option keys are processed in each format

paimon-core/src/main/java/org/apache/paimon/table/KnownSplitsTable.java, paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/paimon/spark/PaimonScan.scala, paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/PaimonScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/ColumnPruningAndPushDown.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonSplitScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkTable.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/MergeIntoPaimonTable.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/UpdatePaimonTableCommand.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DeletionVectorTest.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/spark/paimon/Utils.scala
`PaimonSplitScan` is built for internal scan with update/delete/mergeinto. It is used to generate deletion vector, collect touched files, etc. The main usage is to select some metadata columns based on target table, e.g., row index, file path. That says, it does not need to load data columns.
This pr makes `PaimonSplitScan` support column pruning and filter push down to improve performance:
1. introduce `KnownSplitsTable`, it is a `ReadonlyTable` and hold some known data splits
2. introduce `PaimonSplitScanBuilder`, it is used when the table is the `KnownSplitsTable` and build `PaimonSplitScan`
For example:
```
update test set c1 = 9 where c2 = 'a';
```
before:
```
(1) BatchScan default.test
Output [5]: [c1#197, c2#198, c3#199, c4#200, __paimon_file_path#205]
class …
```
=> [spark] PaimonSplitScan supports column pruning and filter push down

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/MultiUnawareTablesReadOperator.java
=> [flink] Make MultiUnawaureTablesReader use its own logger

paimon-core/src/main/java/org/apache/paimon/index/IndexFileMeta.java, paimon-core/src/main/java/org/apache/paimon/manifest/IndexManifestEntry.java
As described in issue #4182, keeping the name `_DELETIONS_VECTORS_RANGES` in Class `IndexManifestEntry`
Linked issue: close #4182
No
No
No
=> [core] Fix serialize name _DELETION_VECTORS_RANGES conflict

paimon-core/src/main/java/org/apache/paimon/append/UnawareAppendTableCompactionCoordinator.java, paimon-core/src/main/java/org/apache/paimon/manifest/FileEntry.java, paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/operation/FileStoreScan.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReader.java, paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java, paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java, paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyTableCompactionTest.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java
If the table is very large and has many partitions, it can lead to putting too many ManifestEntries directly into memory, causing JVM OOM, and this situation is difficult to recover, with almost no means available at present.
So in this PR, the process of Plan is changed to Iterator mode, so that Compact can be safely performed regardless of the size of the table.
=> [core] Optimize UnawareAppendTableCompactionCoordinator to avoid OOM

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java, paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
Linked issue: close #4247
org.apache.paimon.table.PrimaryKeyFileStoreTableTest#testPartialUpdateRemoveRecordOnDelete
=> [flink] fix same primary key cannot be inserted again after deletion in Partial Update merge engine.

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScanBuilder.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonLocalScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScanBuilder.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonSplitScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/aggregate/LocalAggregator.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PushDownAggregatesTest.scala
Make `PaimonScanBuilder` support `SupportsPushDownAggregates`. This pr implements a local aggregator framework to eval aggregate function. For now, only `CountStar` is supported.
If the aggregation can be pushed down, build a `PaimonLocalScan` to avoid execute with RDD.
There are some limitations:
- only support append table
- only support without deletion vector
- only support with no filter or partition filter
- only support without group by
add test
no
=> [spark] Support push down aggregate

paimon-arrow/src/main/java/org/apache/paimon/arrow/ArrowBundleRecords.java, paimon-arrow/src/main/java/org/apache/paimon/arrow/converter/Arrow2PaimonVectorConverter.java, paimon-arrow/src/main/java/org/apache/paimon/arrow/reader/ArrowBatchReader.java, paimon-arrow/src/main/java/org/apache/paimon/arrow/vector/ArrowFormatWriter.java, paimon-arrow/src/test/java/org/apache/paimon/arrow/vector/ArrowFormatWriterTest.java, paimon-arrow/src/test/java/org/apache/paimon/arrow/vector/OneElementFieldVectorGeneratorTest.java
* [arrow] Enable upper case in arrow format writer
* [arrow] Fix bug for timestamp type converter
* [arrow] Add log
=> [arrow] Enable upper-case field name in arrow format writer

paimon-e2e-tests/src/test/java/org/apache/paimon/tests/E2eTestBase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionITCaseBase.java
Fix concurrent exception while building E2E Flink Test / Flink CDC
> Error: Exception in thread "Debug Logging Timer" java.lang.RuntimeException: Failed to execute logging action
at org.apache.paimon.flink.action.cdc.kafka.KafkaActionITCaseBase$2.run(KafkaActionITCaseBase.java:206)
at java.util.TimerThread.mainLoop(Timer.java:555)
at java.util.TimerThread.run(Timer.java:505)
Caused by: java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2490)
at org.apache.kafka.clients.consumer.KafkaConsumer.acquireAndEnsureOpen(KafkaConsumer.java:2474)
at org.apache.kafka.clients.consumer.KafkaConsumer.beginningOffsets(KafkaConsumer.java:2175)
at …
=> [e2e] Fix kafka consumer concurrent exception

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/ReadOperator.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/operator/OperatorSourceTest.java
Currently for source with consumers, `currentEmitEventTimeLag` will continue to increase even if no new records are read. According to the definition of this metrics, this time lag is the different between the event time and the emit time of the last record.
This PR fixes the issue by sticking to the definition of the metrics.
Unit tests.
=> [flink] Emit event time lag should not increase when no new records are read

paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/SupportsRowLevelOperationFlinkTableSink.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java
partial-update merge engine support batch deletion using flink sql
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase#testRemoveRecordOnDelete
=> [flink] partial-update merge engine support batch deletion using flink sql

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkInternalRow.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkTypeUtils.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/aggregate/LocalAggregator.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PushDownAggregatesTest.scala
If the aggregate all group by keys are from partition columns, we can support push down it. It makes user to get every partition (or with partition filter) row count fast. 
add test
no
=> [spark] Support push down aggregate with group by partition column

docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-common/src/main/java/org/apache/paimon/TableType.java, paimon-flink/paimon-flink-1.15/src/main/java/org/apache/flink/table/catalog/CatalogMaterializedTable.java, paimon-flink/paimon-flink-1.16/src/main/java/org/apache/flink/table/catalog/CatalogMaterializedTable.java, paimon-flink/paimon-flink-1.17/src/main/java/org/apache/flink/table/catalog/CatalogMaterializedTable.java, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/flink/table/catalog/CatalogMaterializedTable.java, paimon-flink/paimon-flink-1.19/src/main/java/org/apache/flink/table/catalog/CatalogMaterializedTable.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/flink/table/catalog/CatalogMaterializedTable.java, paimon-flink/paimon-flink-common/pom.xml, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogTest.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/MaterializedTableITCase.java
Linked issue: close #4045
Flink has introduced [Materialized Table](https://nightlies.apache.org/flink/flink-docs-release-1.20/docs/dev/table/materialized-table/overview/) in 1.20 release, we can support it in Paimon connector.
No
=> [flink] Support Flink Materialized Table

docs/content/flink/procedures.md, docs/content/spark/procedures.md, paimon-core/src/main/java/org/apache/paimon/operation/LocalOrphanFilesClean.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RemoveOrphanFilesProcedure.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionITCase.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedure.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedureTest.scala
For some small tables, using distributed mode directly will waste a lot of resources. Users should be allowed to choose the remove orphan clean mode (local or distributed).
Add UT in RemoveOrphanFilesProcedureTest: Paimon procedure: remove orphan files with mode
Added usage methods：
```
CALL sys.remove_orphan_files(table => 'default.T', older_than => '2023-10-31 12:00:00', dry_run => true, parallelism => '5', mode => 'local')
```
=> [spark][flink] Introduce orphan file cleaning local and distributed mode

paimon-core/src/main/java/org/apache/paimon/operation/PartitionExpire.java, paimon-core/src/main/java/org/apache/paimon/partition/PartitionExpireStrategy.java, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/ExpirePartitionsProcedure.java, paimon-flink/paimon-flink-1.18/src/test/java/org/apache/paimon/flink/procedure/ProcedurePositionalArgumentsITCase.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ExpirePartitionsProcedure.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/ExpirePartitionsProcedureITCase.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ExpirePartitionsProcedure.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/ExpirePartitionsProcedureTest.scala
- The result of expire_partitions is out of order, sort it.
- Add max_expires param to limit the expired partitions number at one time.
before:
after:
=> [core] Sort the expired partitions and add max_expires param

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FirstRowMergeFunctionWrapper.java
When I study the logic of produce changelog, I find a redundant if statement affects my understanding of the code logic.
In order not to affect more people, so now delete it.
=> [core] Delete redundant if statement when produce changelog by lookup for first row.

paimon-flink/paimon-flink-1.15/src/main/java/org/apache/flink/streaming/runtime/streamrecord/RecordAttributes.java, paimon-flink/paimon-flink-1.15/src/main/java/org/apache/paimon/flink/ProcessRecordAttributesUtil.java, paimon-flink/paimon-flink-1.16/src/main/java/org/apache/flink/streaming/runtime/streamrecord/RecordAttributes.java, paimon-flink/paimon-flink-1.16/src/main/java/org/apache/paimon/flink/ProcessRecordAttributesUtil.java, paimon-flink/paimon-flink-1.17/src/main/java/org/apache/flink/streaming/runtime/streamrecord/RecordAttributes.java, paimon-flink/paimon-flink-1.17/src/main/java/org/apache/paimon/flink/ProcessRecordAttributesUtil.java, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/flink/streaming/runtime/streamrecord/RecordAttributes.java, paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/ProcessRecordAttributesUtil.java, paimon-flink/paimon-flink-1.19/pom.xml, paimon-flink/paimon-flink-cdc/pom.xml, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/flink/streaming/runtime/streamrecord/RecordAttributes.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/ProcessRecordAttributesUtil.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/ProcessRecordAttributesUtil.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/HashBucketAssignerOperator.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StreamMapWithForwardingRecordAttributes.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/TableWriteOperator.java
This PR introduces RecordAttributesProcessor for write operators, providing the ability to handle record attributes during constructing sink operators.
WriteOperatorTest.testProcessRecordAttributes is introduced to verify the correctness of this PR.
This change does not introduce changes that require a document.
=> [feature][flink] introduce RecordAttributesProcessor for write operators

docs/content/maintenance/system-tables.md, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/ManifestsTable.java, paimon-core/src/test/java/org/apache/paimon/table/system/ManifestsTableTest.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTestBase.scala
Follow up https://github.com/apache/paimon/pull/1667 and https://github.com/apache/paimon/pull/4251 
which can only support query by snapshot id, this pr is aimed to support tag name query.
=> [core] Manifest and Statistic support query by tag name

paimon-common/src/main/java/org/apache/paimon/types/ArrayType.java, paimon-common/src/main/java/org/apache/paimon/types/MapType.java, paimon-common/src/main/java/org/apache/paimon/types/RowType.java, paimon-core/src/main/java/org/apache/paimon/utils/BulkFormatMapping.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetReaderFactory.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetSchemaConverter.java, paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ParquetSplitReaderUtil.java, paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkTypeUtils.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/ColumnPruningAndPushDown.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonStatistics.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonQueryTest.scala
to #4209, Support nested col pruning,  e.g.
```sql
CREATE TABLE students (
name STRING,
age INT,
course STRUCT<course_name: STRING, grade: DOUBLE>
) USING paimon;
```
```sql
SELECT course.grade FROM students;
```
will only obtain `course.grade` from colume-storage-format (parquet, orc)
=> [spark] Support nested col pruning

paimon-common/src/main/java/org/apache/paimon/types/DataField.java, paimon-common/src/main/java/org/apache/paimon/types/RowType.java, paimon-common/src/main/java/org/apache/paimon/utils/BinaryStringUtils.java, paimon-common/src/main/java/org/apache/paimon/utils/TypeUtils.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/debezium/DebeziumSchemaUtils.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/RichEventParser.java
@umeshdangat has an outstanding PR which was updated after PR by @zhuangchong was merged. That PR: https://github.com/apache/paimon/pull/3323
The above patch allows consuming data from avro data from kafka into paimon but it doesnt support complex avro types. This PR achieves that. The original PR https://github.com/zhuangchong/flink-table-store/pull/1 was pointing to @zhuangchong branch to clearly show the changes only relavant to supporting complex avro types.
This PR fixes the failing E2E tests for PR: https://github.com/apache/paimon/pull/3931
Copying the note from PR: https://github.com/apache/paimon/pull/3931
> One issue is CdcSourceRecord contains Map<String, String> thus the current somewhat tedious approach is to deserialize avro complex types into json strings and then read them …
=> [common][flink] Add support for complex types in kafka debezium avro cdc action

paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java, paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CreateAndDeleteTagProcedureTest.scala
when re-create a tag with the same name, we should delete it first and dont want to the job failed if tag not exists, like this:
```
CALL sys.delete_tag(table => 'default.T', tag => 'my_tag');
CALL sys.create_tag(table => 'default.T', tag => 'my_tag');
```
This is like `drop table [if exists] tb` usage.
=> [core] Delete tag not failed if tag not exists

paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java, paimon-core/src/main/java/org/apache/paimon/utils/ObjectsFile.java, paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java, paimon-core/src/test/java/org/apache/paimon/operation/FileStoreCommitTest.java
At present, if the number of files is very large and the commit interval is relatively small, and multiple jobs are written simultaneously, there will be serious competition, and even retry failures (more than ten times will fail).
This is because the data files conflicts checking may be triggered at present, which requires a relatively long time to read data files from old snapshot. If other jobs commit at this time, and repeated commit may still fail because of repeated conflicts checking.
This is very wasteful. We can actually reuse the base files, we can just read incremental files and merge it to last time base files.
=> [core] Optimize multiple commit to reduce conflicts

paimon-core/src/main/java/org/apache/paimon/table/source/DataTableBatchScan.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonPushDownTest.scala
If we enable the deletion vector, the raw files row count may not equal to the actual row count. We can not push down limit if there are some deletion files. 
add test
no
=> [spark] Fix push down limit data correctness issue with deletion vector

paimon-core/src/main/java/org/apache/paimon/operation/LocalOrphanFilesClean.java
Local Remove Orphan Files OOM always occurred when collecting data file meta. Because  data files in tables may be large (could reach tens of millions or more). 
Relatively speaking, the number of candidate files is not large (ten thousand or hundreds of thousands).
So we can just collect data file meta in candidate files to reduce the probability of OOM occurrence.
=> [core] Filter data file while executing local orphan clean

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/TableStatsUtil.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkAnalyzeTableITCase.java
=> [Flink] Support analysis statistics in flink

paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeWriter.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWriteImpl.java
This PR fixes InsertOnly related behavior in CDC and deduplication scenarios.
Related PR: #3791 
This change does not introduce changes that require a document.
=> Fix InsertOnly behavior for CDC and deduplication scenarios

docs/content/migration/iceberg-compatibility.md, docs/layouts/shortcodes/generated/core_configuration.html, paimon-common/src/main/java/org/apache/paimon/CoreOptions.java, paimon-core/pom.xml, paimon-core/src/main/java/org/apache/paimon/iceberg/AbstractIcebergCommitCallback.java, paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergOptions.java, paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergPathFactory.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergDataFileMeta.java, paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergDataField.java, paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergPartitionField.java, paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergSchema.java, paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java, paimon-core/src/test/java/org/apache/paimon/iceberg/IcebergCompatibilityTest.java, paimon-flink/paimon-flink-1.16/pom.xml, paimon-flink/paimon-flink-1.16/src/test/java/org/apache/paimon/flink/iceberg/Flink116IcebergITCase.java, paimon-flink/paimon-flink-1.17/pom.xml, paimon-flink/paimon-flink-1.17/src/test/java/org/apache/paimon/flink/iceberg/Flink117IcebergITCase.java, paimon-flink/paimon-flink-1.18/pom.xml, paimon-flink/paimon-flink-1.18/src/test/java/org/apache/paimon/flink/iceberg/Flink118IcebergITCase.java, paimon-flink/paimon-flink-1.19/pom.xml, paimon-flink/paimon-flink-1.19/src/test/java/org/apache/paimon/flink/iceberg/Flink119IcebergITCase.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/iceberg/FlinkIcebergITCaseBase.java
Currently there is not IT cases for Paimon Iceberg compatibility in Flink. This PR adds IT cases and fixes some issues with parquet format.
IT cases.
Document for the whole Iceberg compatibility feature is also added.
=> [fix][flink] Fix Iceberg compatible metadata cannot be read when data file format is parquet

paimon-core/src/main/java/org/apache/paimon/table/source/DataTableBatchScan.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScanBuilder.scala, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonPushDownTest.scala
For the primary key table, we still have a chance to push down limit if the split is raw convertible. This pr relaxes the push down limit condition to support primary key table.
add test
no
=> [core][spark] Support push down limit for primary key table

.gitignore
[Jenv](https://github.com/jenv/jenv) is a popular tool for managing multiple Java versions.
=> [hotfix] Add `.java-version` to to `.gitignore`

paimon-core/src/main/java/org/apache/paimon/table/query/LocalTableQuery.java, paimon-core/src/test/java/org/apache/paimon/table/TableTestBase.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FullCacheLookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupStreamingReader.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupTable.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PrimaryKeyPartialLookupTable.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/LookupTableTest.java
Flink LookupTable support cache row filter to filter out rows to be stored in cache.
- UT added in `LookupTableTest` and `KeyValueFileReadWriteTest`.
No
No
=> [flink] Flink LookupTable support cache row filter

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactDatabaseAction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkStreamPartitioner.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedUnawareBatchSourceFunction.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedUnawareStreamingSourceFunction.java
fix compact unaware bucket table in combine mode the writer parallelism is always 1
=> [flink] fix compact unaware bucket table in combine mode the writer parallelism is always 1

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkGenericCatalog.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/FlinkGenericCatalogITCase.java
Fix the exception as below when use `FlinkGenericCatalog`
=> [flink] Fix FlinkGenericCatalog can not get procedure

paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/lookup/AbstractLookupBenchmark.java, paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/lookup/LookupReaderBenchmark.java, paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/lookup/LookupWriterBenchmark.java
Linked issue: close #4139 
Add benchmark for reader and writer with bloom filter in sort file store
no
no
no
=> [core] Add benchmark for reader and writer with bloom filter in sort file store

docs/content/migration/iceberg-compatibility.md, paimon-core/pom.xml, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergConversions.java, paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergDataField.java, paimon-core/src/test/java/org/apache/paimon/iceberg/IcebergCompatibilityTest.java, paimon-flink/paimon-flink-1.17/pom.xml, paimon-flink/paimon-flink-1.18/pom.xml, paimon-flink/paimon-flink-1.19/pom.xml, paimon-flink/paimon-flink-common/pom.xml, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/iceberg/FlinkIcebergITCaseBase.java, pom.xml
`TIMESTAMP` is a widely used data type. This PR supports `TIMESTAMP` and `TIMESTAMP_LTZ` type in Iceberg compatibility.
=> [core] Support timestamp type in Iceberg compatibility

docs/content/maintenance/system-tables.md, paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/ManifestsTable.java, paimon-core/src/main/java/org/apache/paimon/table/system/StatisticTable.java, paimon-core/src/test/java/org/apache/paimon/table/system/ManifestsTableTest.java, paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTestBase.scala
=> [core] Manifest and Statistic support query by timestamp

paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileMetaTest.java
add random test case for ManifestFileMerger#tryFullCompaction
=> [test] add random test case for manifest file full compaction

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java, paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java, paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonPartitionManagement.scala
Adjust https://github.com/apache/paimon/pull/4323
=> [core] Adjust create partition interface

paimon-common/src/main/java/org/apache/paimon/statistics/TruncateSimpleColStatsCollector.java
This pr improves TruncateSimpleColStatsCollector performance:
1. avoid doing tuncate if previous row failed to truncate max
2. avoid unnecessary copy if we succeeded to tuncate max
3. avoid truncate max twice
the test has been convered by `SimpleColStatsCollectorTest`
no
=> [core] Improve TruncateSimpleColStatsCollector performance

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SaveMode.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkTable.scala, paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkWrite.scala
For example: `explain insert into table ...`
before:
```
== Physical Plan ==
AppendDataExecV1 SparkTable(org.apache.paimon.table.PrimaryKeyFileStoreTable@55b12c21), Project [id#287L AS id#290L, (id % 3)#289L AS c1#291L, id#288 AS c2#292], org.apache.spark.sql.execution.datasources.v2.DataSourceV2Strategy$$Lambda$4534/0x000000080270fa08@5762dc14, org.apache.paimon.spark.SparkWrite@30ba29cf
```
after:
```
== Physical Plan ==
AppendDataExecV1 PrimaryKeyFileStoreTable[default.bucket_t1], Project [id#3L AS id#6L, (id % 3)#5L AS c1#7L, id#4 AS c2#8], org.apache.spark.sql.execution.datasources.v2.DataSourceV2Strategy$$Lambda$2239/0x0000000801fb0d88@13448d2d, table: default.bucket_t1, saveMode: InsertInto, options: {}
```
manually test
no
=> [spark] Improve write table plan explain string

paimon-core/src/main/java/org/apache/paimon/operation/LocalOrphanFilesClean.java, paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java, paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
Increase parallel reading of snapshot, manifest, and data file meta to improve execution efficiency
Test in table with 7TB size with local mode:
Before this patch: local orphan clean will cost **20 min**
After this patcgh, use the same sql in **parallelism 16**, the procedure only cost **5 min**
=> [core] Support parallel reading of local orphan clean

paimon-core/src/main/java/org/apache/paimon/table/RollbackHelper.java
If we start a job when Rollback is running, it may read latest snapshot id from hint file and get wrong snapshot id.
=> [core] Rollback action write hint first 

paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/lookup/AbstractLookupBenchmark.java, paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/lookup/LookupReaderBenchmark.java
We use expected rows(5000000) and fpp(0.01) in bloom filter, the writer results are as follows:
Records | Value Data Size | Without Bloom Filter(MS) | With Bloom Filter(MS) | Relative
-- | -- | -- | -- | --
100000 | 0B | 6 | 9 | 1.5
100000 | 64B | 11 | 13 | 1.181818182
100000 | 500B | 37 | 34 | 0.918918919
100000 | 1000B | 57 | 58 | 1.01754386
100000 | 2000B | 88 | 95 | 1.079545455
1000000 | 0B | 32 | 64 | 2
1000000 | 64B | 74 | 114 | 1.540540541
1000000 | 500B | 253 | 310 | 1.225296443
1000000 | 1000B | 384 | 440 | 1.145833333
1000000 | 2000B | 534 | 625 | 1.170411985
5000000 | 0B | 164 | 327 | 1.993902439
5000000 | 64B | 356 | 511 | 1.435393258
5000000 | 500B | 1072 | 1197 | 1.116604478
5000000 | 1000B | 1921 | 2338 | 1.21707444
5000000 | 2000B | 3163 | 3480 | …
=> [core] Update writer/reader benchmark for bloom filter

paimon-arrow/src/main/java/org/apache/paimon/arrow/writer/ArrowFieldWriterFactoryVisitor.java
Init MapVector before write. If not, export VectorSchemaRoot to c-struct when meet a empty Map will cause an error while deserializing in c++: arrow/cpp/src/arrow/result.cc:28: ValueOrDie called on an error: Invalid: ArrowArrayStruct contains null data pointer for a buffer with non-zero computed size
=> [arrow] Allocate buffer for MapVector in init

docs/content/migration/iceberg-compatibility.md, paimon-core/src/main/java/org/apache/paimon/iceberg/AbstractIcebergCommitCallback.java, paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergMetadataCommitter.java, paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergMetadataCommitterFactory.java, paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergOptions.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergDataFileMeta.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestEntry.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestFileMeta.java, paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergPartitionSummary.java, paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergMetadata.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/iceberg/FlinkIcebergITCaseBase.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/iceberg/IcebergHiveMetadataCommitter.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/iceberg/IcebergHiveMetadataCommitterFactory.java, paimon-hive/paimon-hive-catalog/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory, paimon-hive/paimon-hive-connector-2.3/pom.xml, paimon-hive/paimon-hive-connector-2.3/src/test/java/org/apache/paimon/iceberg/IcebergHive23MetadataCommitterITCase.java, paimon-hive/paimon-hive-connector-3.1/pom.xml, paimon-hive/paimon-hive-connector-3.1/src/test/java/org/apache/paimon/iceberg/IcebergHive31MetadataCommitterITCase.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/iceberg/IcebergHiveMetadataCommitterITCaseBase.java, paimon-hive/pom.xml
Iceberg Hive catalog is the most widely used Iceberg catalog. This PR supports syncing Iceberg compatible metadata to Hive, so Paimon table can be accessed from Iceberg Hive catalog.
IT cases.
=> [hive] Support syncing Iceberg compatible metadata to Hive, so Paimon table can be accessed from Iceberg Hive catalog

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCommitter.java
During closing, we should also close partition mark done to release the resource such as metastore client in MarkDoneAction.
=> [Bug] Close PartitionMarkDone to prevent potential resource leakage

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PredicateITCase.java, paimon-format/src/main/java/org/apache/parquet/filter2/predicate/ParquetFilters.java
=> [format] Fix ParquetFilters cannot handle tinyint and smallint correctly

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveFormatTableUtils.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogFormatTableITCaseBase.java
I found that when using flink to create a format table, flink will throw an exception when reading the format table. This is due to the fact that the field-delimiter of the hive table is not specified. This pr is to support setting csv.field-delimiter.
=> [hive] Support create formatTable set csv.field-delimiter

paimon-format/pom.xml, paimon-spark/paimon-spark-3.2/pom.xml, paimon-spark/paimon-spark-3.3/pom.xml, paimon-spark/paimon-spark-3.4/pom.xml, paimon-spark/paimon-spark-3.5/pom.xml, paimon-spark/paimon-spark-common/pom.xml, paimon-spark/pom.xml, pom.xml
Linked issue: close #4351
Remove the dependency of `paimon-bundle` in all submodules of `paimon-spark` to fix the problem that the paimon class cannot be found in idea.
=> [spark]  remove the dependency of paimon-bundle in all submodules of paimon-spark.

paimon-core/src/main/java/org/apache/paimon/privilege/NoPrivilegeException.java, paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegeChecker.java, paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedFileStore.java, paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedFileStoreTable.java, paimon-core/src/test/java/org/apache/paimon/catalog/FileSystemCatalogTest.java, paimon-core/src/test/java/org/apache/paimon/privilege/PrivilegedCatalogTest.java
Fix snapshot privilege check logic
Introduced `org.apache.paimon.privilege.PrivilegedCatalogTest` to verify the changes.
This change does not affect API or storage format
This change does not introduce a new feature
=> [core] Fix snapshot privilege check logic

docs/content/migration/iceberg-compatibility.md
Currently Iceberg compatibility document only has examples with Flink and Spark. This PR adds example on querying Paimon table with Trino Iceberg connector.
No tests.
=> [docs] Add example on querying Paimon table with Trino Iceberg connector

paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java, paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java, paimon-core/src/main/java/org/apache/paimon/view/View.java, paimon-core/src/main/java/org/apache/paimon/view/ViewImpl.java, paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java, paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveTableUtils.java, paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/HiveCatalogTest.java, paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
This PR aims to support View in Catalog, our metastore behind us, such as Hive metastore, supports views, but our catalog has not done this conversion well. This PR aims to support the definition of views and bridge with HiveCatalog.
```
/** Interface for view definition. */
public interface View {
/** A name to identify this view. */
String name();
/** Full name (including database) to identify this view. */
String fullName();
/** Returns the row type of this view. */
RowType rowType();
/** Returns the view representation. */
String query();
/** Optional comment of this view. */
Optional<String> comment();
/** Options of this view. */
Map<String, String> options();
/** Copy this view with adding dynamic options. */
View copy(Map<String, String> dynamicOptions);
}
```
```
/**
* Return a …
```
=> [core] Introduce View Support to HiveCatalog

paimon-spark/paimon-spark-3.2/pom.xml, paimon-spark/paimon-spark-3.3/pom.xml, paimon-spark/paimon-spark-3.4/pom.xml, paimon-spark/paimon-spark-3.5/pom.xml
we already excluded zstd-jni jar from spark runtime jar(#4085), however, the zstd-jni jar contains not only Java files but also references to some native libraries. These files should also be excluded.
=> [spark]: clean up zstd-jni lib files

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/BaseDataTableSource.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java
`lookup.dynamic-partition` will create `DynamicPartitionLoader`, it will use scan options to load data. But dim table should ignore scan options.
=> [flink] Lookup source should ignore scan options

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/RetryingMetaStoreClientFactory.java, paimon-hive/paimon-hive-connector-3.1/src/test/java/org/apache/paimon/hive/CustomConstructorMetastoreClient.java, paimon-hive/paimon-hive-connector-3.1/src/test/java/org/apache/paimon/hive/Hive31CatalogITCase.java
An enhancement introduced by #4283 lead to the following problem for dlf catalog:
```
Failed to create the desired metastore client (class name: com.aliyun.datalake.metastore.hive3.ProxyMetaStoreClient)
```
Because dlf hive3 ProxyMetaStoreClient still uses hive2 construct method.
=> [hive] Fix wrong construct for dlf metastore

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SynchronizationActionBase.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java, paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/CdcActionITCaseBase.java, paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java, paimon-flink/paimon-flink-cdc/src/test/resources/mysql/sync_table_setup.sql
Flink-cdc do not support batch mode, including flink cdc `snapshot` scan mode . Although it is a bounded source.
https://issues.apache.org/jira/browse/FLINK-36280
https://github.com/apache/flink-cdc/pull/2901
if use set RuntimeExecutionMode = Batch. job will be never finish and never fail.
so , we need to check the flink execution mode.
=> [cdc] Add flink execution mode check for cdc table sync action.

docs/content/flink/sql-alter.md, docs/content/spark/sql-alter.md
=> [doc] Add doc for adding partitions

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java, paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java
…
Linked issue: close #4344 
PartialUpdateITCase#testRemoveRecordOnDelete()
=> [flink] fix delete record exception after partial-update merge engine configuration to lookup changelog producer

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AdaptiveParallelism.java, paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java
In #4221, a default parallelism was added to Paimon Sink in AQE cases. It is discovered that the value of Flink's `parallelism.default` configuration could actually be -1, which means Paimon sink might be unintentionally working under adaptive parallelism mode.
BatchFileStoreITCase#testAQEWithXXX can be used to verify the changes in this PR and #4221.
No API or Format is changed.
No documentation needed. The existing unsupported cases had not been documented, so no modification needed for documents.
=> [flink] fix sink parallelism in case of AQE

paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java
Linked issue: close #4396 
According the API of mkdirs in `FileIO`, it may return false to represent mkdir failed,  we should handle the false condition when creating database.
```java
boolean mkdirs(Path path) throws IOException;
```
=> [core]  add check for make directory for db location when creating database
