apache/paimon

paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarSyncTableActionITCase.java

[hotfix] Fix PulsarSyncTableActionITCase#testWaterMarkSyncTable

---

paimon-hive/paimon-hive-connector-3.1/src/main/java/org/apache/paimon/hive/objectinspector/PaimonTimestampObjectInspector.java
paimon-hive/paimon-hive-connector-3.1/src/test/java/org/apache/paimon/hive/HiveWriteITCase.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/objectinspector/PaimonTimestampObjectInspector.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/PaimonStorageHandlerITCase.java

[hive] Fix Hive 3 timestamp precision conversion error

---

docs/content/maintenance/metrics.md
paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeWriter.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactManager.java
paimon-core/src/main/java/org/apache/paimon/operation/metrics/CompactionMetrics.java
paimon-core/src/main/java/org/apache/paimon/operation/metrics/WriterMetrics.java
paimon-core/src/test/java/org/apache/paimon/operation/metrics/CompactionMetricsTest.java

To show the compaction condition.

[core] Add level0 file count metric

---

paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/kafka/LogSystemITCase.java

[flink] remove redundant code for `LogSystemITCase`

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java

This reverts commit b3fd931e0c24202e605489cfcd085314a0b0c470, see https://github.com/apache/incubator-paimon/pull/2595#discussion_r1451752055

Revert "[hive] Improve hive database is exists yet create/drop database (#2595)"

---

paimon-common/src/test/java/org/apache/paimon/format/FormatReadWriteTest.java
paimon-format/src/main/java/org/apache/paimon/format/avro/AvroSchemaVisitor.java
paimon-hive/paimon-hive-common/src/main/java/org/apache/paimon/hive/HiveTypeUtils.java
paimon-hive/paimon-hive-common/src/main/java/org/apache/paimon/hive/LocalZonedTimestampTypeUtils.java
paimon-hive/paimon-hive-connector-3.1/src/main/java/org/apache/paimon/hive/LocalZonedTimestampTypeUtils.java
paimon-hive/paimon-hive-connector-3.1/src/main/java/org/apache/paimon/hive/objectinspector/PaimonTimestampLocalTZObjectInspector.java
paimon-hive/paimon-hive-connector-3.1/src/test/java/org/apache/paimon/hive/HiveWriteITCase.java
paimon-hive/paimon-hive-connector-3.1/src/test/java/org/apache/paimon/hive/objectinspector/PaimonTimestampLocalTZObjectInspectorTest.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/objectinspector/PaimonObjectInspectorFactory.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/objectinspector/PaimonTimestampLocalTZObjectInspector.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/RandomGenericRowDataGenerator.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/objectinspector/PaimonInternalRowObjectInspectorTest.java

[hive] Support 'timestamp with local time zone' for Hive

---

paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/FileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/query/LocalTableQuery.java
paimon-core/src/main/java/org/apache/paimon/table/query/TableQuery.java
paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
paimon-flink/paimon-flink-common/pom.xml
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PrimaryKeyPartialLookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/query/RemoteTableQuery.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/RemoteLookupJoinITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/FileStoreLookupFunctionTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/LookupTableTest.java
paimon-flink/pom.xml
paimon-service/paimon-service-runtime/src/test/java/org/apache/paimon/service/KvQueryTableTest.java

Introduce a new mode Remote Lookup to query service.

[flink] Introduce RemoteTableQuery for Flink Lookup join

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregator.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldCollectAgg.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregatorTest.java

[core] 'collect' aggregator supports constructed element types

---

paimon-common/src/main/java/org/apache/paimon/fs/FileIO.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/DataTable.java
paimon-core/src/main/java/org/apache/paimon/table/ReadonlyTable.java
paimon-core/src/main/java/org/apache/paimon/table/Table.java
paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/BucketsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/FileMonitorTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/ReadOptimizedTable.java
paimon-core/src/main/java/org/apache/paimon/utils/BranchManager.java
paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java

Introduce branch for paimon
Linked issue: https://github.com/apache/incubator-paimon/issues/2148
deisgn：https://cwiki.apache.org/confluence/display/PAIMON/PIP-9%3A+Support+Branch
task：https://github.com/apache/incubator-paimon/issues/1795

[Core] Support create and delete branch

---

docs/content/how-to/lookup-joins.md
docs/content/how-to/writing-tables.md
docs/content/maintenance/configurations.md
paimon-core/src/main/java/org/apache/paimon/table/query/LocalTableQuery.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/QueryServiceActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ProcedureBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/QueryServiceProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/query/RemoteTableQuery.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/service/QueryAddressRegister.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/service/QueryExecutorOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/service/QueryFileMonitor.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/service/QueryService.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/RemoteLookupJoinITCase.java
paimon-service/paimon-service-client/src/main/java/org/apache/paimon/service/network/NetworkUtils.java

Final step for: https://cwiki.apache.org/confluence/display/PAIMON/PIP-10%3A+Introduce+Paimon+QueryService
Build DataStream topology for query service.

[flink] Introduce Query Service

---

paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java
paimon-core/src/main/java/org/apache/paimon/utils/FileUtils.java
paimon-core/src/main/java/org/apache/paimon/utils/ScanParallelExecutor.java
paimon-core/src/test/java/org/apache/paimon/utils/ScanParallelExecutorTest.java

[core] Ensure enough tasks for scan.manifest.parallelism

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/watermark/CdcTimestampExtractorFactory.java

[hotfix] Timestamp extractor error

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CreateBranchProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/DeleteBranchProcedure.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/BranchActionITCase.java

Add procedure in flink for create/delete branch
Linked issue: close #2723 
1. Added test case BranchActionITCase
no
no

[core][branch] Add procedure in flink for create/delete branch

---

docs/content/engines/flink.md
docs/content/engines/spark.md
paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/FileStore.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/ExpireSnapshots.java
paimon-core/src/main/java/org/apache/paimon/table/ExpireSnapshotsImpl.java
paimon-core/src/main/java/org/apache/paimon/table/ReadonlyTable.java
paimon-core/src/main/java/org/apache/paimon/table/Table.java
paimon-core/src/main/java/org/apache/paimon/table/sink/TableCommitImpl.java
paimon-core/src/test/java/org/apache/paimon/TestFileStore.java
paimon-core/src/test/java/org/apache/paimon/operation/CleanedFileStoreExpireTest.java
paimon-core/src/test/java/org/apache/paimon/operation/OrphanFilesCleanTest.java
paimon-core/src/test/java/org/apache/paimon/operation/UncleanedFileStoreExpireTest.java
paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java
paimon-core/src/test/java/org/apache/paimon/table/IndexFileExpireTableTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ExpireSnapshotsProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ProcedureBase.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ExpireSnapshotsProcedure.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkTimeTravelITCase.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/ExpireSnapshotsProcedureTest.scala

[core] Introduce expire_snapshots procedure

---

paimon-core/src/main/java/org/apache/paimon/utils/JsonSerdeUtil.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/RecordParser.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/canal/CanalRecordParser.java

[flink] Unified use of JsonSerdeUtil

---

paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

[hotfix] Clean todo in HiveCatalogITCaseBase

---

paimon-flink/paimon-flink-common/pom.xml
pom.xml

[hotfix] Bump all flink-1.18.0 to 1.18.1

---

paimon-common/src/main/java/org/apache/paimon/io/cache/CacheManager.java
paimon-common/src/main/java/org/apache/paimon/io/cache/FileBasedRandomInputView.java
paimon-common/src/main/java/org/apache/paimon/lookup/hash/HashLookupStoreReader.java
paimon-common/src/main/java/org/apache/paimon/utils/FileBasedBloomFilter.java
paimon-common/src/test/java/org/apache/paimon/io/cache/FileBasedRandomInputViewTest.java

[core] FileBasedRandomInputView should respect LRU Cache

---

docs/content/concepts/append-table/append-scalable-table.md
docs/content/concepts/primary-key-table/merge-engine.md

I found a very small documentation error. I wonder if I can directly submit a PR without raising an issue.

[doc] Update append-scalable-table.md and merge-engine.md

---

paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/Benchmark.java
paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/TableBenchmark.java
paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/TableReadBenchmark.java
paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/TableWriterBenchmark.java

Add a benchmark to measure the table read performance

[Benchmark] Add table read benchmark

---

docs/content/engines/spark.md

[doc] Fix argument for spark expire_snapshots

---

paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/spark/sql/StatsUtils.scala
paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/spark/sql/StatsUtils.scala
paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTest.scala
paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTest.scala
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTest.scala
paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTest.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonAnalyzeTableColumnCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/StatsUtils.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/Utils.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTestBase.scala

[spark] Fix analyze compatibility with spark3.3-

---

paimon-core/src/main/java/org/apache/paimon/branch/TableBranch.java
paimon-core/src/main/java/org/apache/paimon/table/system/BranchesTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/SystemTableLoader.java
paimon-core/src/main/java/org/apache/paimon/table/system/TagsTable.java
paimon-core/src/main/java/org/apache/paimon/utils/BranchManager.java
paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
paimon-core/src/test/java/org/apache/paimon/table/system/BranchesTableTest.java
paimon-core/src/test/java/org/apache/paimon/table/system/TagsTableTest.java

Linked issue: close #2758 
Add system table for branches
Added BranchesTableTest
no
no

[core][branch] Add branches system table

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkFilterConverter.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkFilterConverterTest.java

[spark] SparkFilterConverter supports convert EqualNullSafe

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/CatalogLock.java
paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java
paimon-core/src/main/java/org/apache/paimon/operation/Lock.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalogLock.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

Linked issue: close #2870 2870
Refactor catalog lock factory to extend paimon Factory
Existing test HiveCatalogITCaseBase
no
no

[core] Refactor catalog lock factory for paimon Factory

---

docs/content/concepts/append-table/append-queue-table.md
docs/content/concepts/append-table/append-scalable-table.md
docs/content/concepts/primary-key-table/merge-engine.md
docs/content/concepts/primary-key-table/sequence-rowkind.md
docs/content/how-to/altering-tables.md
docs/content/how-to/creating-tables.md
docs/content/how-to/lookup-joins.md
docs/content/how-to/system-tables.md
docs/content/how-to/writing-tables.md
docs/content/maintenance/manage-partition.md
docs/content/maintenance/manage-tags.md
docs/content/migration/upsert-to-partitioned.md

Change the table name from uppercase to lowercase.

[doc] Change the table name from uppercase to lowercase

---

paimon-core/src/main/java/org/apache/paimon/mergetree/DropDeleteReader.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ChangelogMergeTreeRewriter.java
paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/LookupCompactionTest.scala

Support drop delete in rewriteChangelogCompaction

[core] Support drop delete in rewriteChangelogCompaction

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/RecordParser.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaMaxwellSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/resources/kafka/maxwell/table/schemaevolution/maxwell-data-4.txt

fix:
java.lang.NullPointerException
at java.util.HashMap.merge(HashMap.java:1226)
at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
at java.util.Iterator.forEachRemaining(Iterator.java:116)
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
at …

[flink] Fix maxwell extractRecords nullPointerException

---

paimon-core/src/main/java/org/apache/paimon/mergetree/LookupUtils.java
paimon-core/src/test/java/org/apache/paimon/mergetree/LookupLevelsTest.java

[Bug] Fix the incorrect lookup join result when lookup from level0

---

paimon-spark/paimon-spark-3.5/pom.xml

[spark] Bump Spark version 3.5.1

---

docs/content/how-to/creating-tables.md

Linked issue: close #2920 
Fix the document of Create Table AS example
No need tests
No
No

[Bug] Fix the document of Create Table AS example

---

paimon-common/src/main/java/org/apache/paimon/data/columnar/ColumnarRowIterator.java
paimon-common/src/main/java/org/apache/paimon/reader/RecordReader.java
paimon-common/src/main/java/org/apache/paimon/reader/RecordWithPositionIterator.java
paimon-format/src/main/java/org/apache/paimon/format/orc/OrcReaderFactory.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetReaderFactory.java
paimon-format/src/test/java/org/apache/paimon/format/orc/OrcReaderFactoryTest.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetReadWriteTest.java

This is the first step of https://github.com/apache/incubator-paimon/issues/2898, in this PR:
- introduce RecordWithPositionIterator
- implement it with orc and parquet format

[core] Introduce RecordWithPositionIterator interface

---

paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncTableActionBase.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SynchronizationActionBase.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/resources/mysql/sync_table_setup.sql

[core] Forbid to change bucket number through dynamic options

---

paimon-flink/paimon-flink-1.14/pom.xml
paimon-flink/paimon-flink-1.15/pom.xml
paimon-flink/paimon-flink-cdc/pom.xml
paimon-flink/pom.xml

[flink] Clean kafka dependencies for paimon-flink

---

docs/content/engines/spark.md

Add procedure documents for spark create_tag ,delete_tag,rollback and remove_orphan_files.

[DOC]add spark procedure  doc

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java

[spark] bugfix: set underlyingSessionCatalogEnabled correctly

---

docs/content/engines/flink.md
docs/content/engines/spark.md
docs/content/maintenance/manage-tags.md

[doc] Polish doc of create_tag by latest snapshot

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/AppendOnlyTableITCase.java
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/PaimonSinkTest.scala
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/CreateAndDeleteTagProcedureTest.scala
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/RollbackProcedureTest.scala

[hotfix] Remove useless 'write-mode' option in tests

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala

[spark] Make compact procedure compatible with the Kryo serializer

---

paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalogLock.java

Rename catalogName to catalogKey

[core]Unified Naming of JdbcCatalog Fields

---

paimon-filesystems/paimon-s3-impl/src/main/resources/META-INF/NOTICE
paimon-flink/paimon-flink-cdc/pom.xml
paimon-format/src/main/resources/META-INF/NOTICE
pom.xml

Linked issue: 
close #2966 
close #2965

[hotfix] upgrade json-path and avro version

---

docs/content/engines/spark.md

[doc] Updated Spark quickstart documentation for using `--packages`

---

paimon-common/src/main/java/org/apache/paimon/data/serializer/RowCompactedSerializer.java
paimon-common/src/main/java/org/apache/paimon/utils/VarLengthIntUtils.java
paimon-core/src/main/java/org/apache/paimon/mergetree/LookupLevels.java

[core] Use var length encoding for row position

---

docs/content/engines/overview.md
docs/content/engines/trino.md
docs/content/filesystems/oss.md
docs/content/filesystems/s3.md
docs/content/how-to/altering-tables.md
docs/content/how-to/querying-tables.md
docs/content/project/download.md

Repaire trino docs for latest paimo-trino version.

[docs] Trino docs update for sharing file system.

---

paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/TableWriterBenchmark.java
paimon-common/src/main/java/org/apache/paimon/data/AbstractBinaryWriter.java
paimon-common/src/main/java/org/apache/paimon/data/serializer/InternalRowSerializer.java
paimon-common/src/test/java/org/apache/paimon/data/serializer/InternalRowSerializerTest.java
paimon-format/src/main/java/org/apache/paimon/format/orc/writer/FieldWriter.java
paimon-format/src/main/java/org/apache/paimon/format/orc/writer/FieldWriterFactory.java
paimon-format/src/main/java/org/apache/paimon/format/orc/writer/RowDataVectorizer.java

- Improve performance for `InternalRowSerializer`.
- Improve performance for `RowDataVectorizer`.

[core] Optimize write performance

---

paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java

[core] support create tag based on tag

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
paimon-core/src/test/java/org/apache/paimon/schema/TableSchemaTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java

Add validation for fields prefix to check field exist

[core] Add validation for fields prefix

---

paimon-core/src/main/java/org/apache/paimon/metastore/AddPartitionTagCallback.java
paimon-core/src/main/java/org/apache/paimon/metastore/MetastoreClient.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/sink/TagCallback.java
paimon-core/src/main/java/org/apache/paimon/tag/TagAutoCreation.java
paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java
paimon-core/src/test/java/org/apache/paimon/operation/UncleanedFileStoreExpireTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AutoTagForSavepointCommitterOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/BatchWriteGeneratorTagOperator.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/BatchWriteGeneratorTagOperatorTest.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveMetastoreClient.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

[core] support to drop partition when delete tag

---

docs/content/maintenance/configurations.md
docs/layouts/shortcodes/generated/core_configuration.html
docs/layouts/shortcodes/generated/orc_configuration.html
docs/layouts/shortcodes/generated/spark_connector_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-docs/src/main/java/org/apache/paimon/docs/configuration/ConfigOptionsDocGenerator.java
paimon-format/src/main/java/org/apache/paimon/format/OrcOptions.java
paimon-format/src/main/java/org/apache/paimon/format/orc/OrcWriterFactory.java
paimon-format/src/test/java/org/apache/paimon/format/orc/writer/OrcBulkWriterTest.java

[doc] Introduce orc options documentation page

---

docs/content/engines/flink.md
docs/content/engines/overview.md
docs/content/project/download.md

Add flink 1.19 to the documentation.

[doc] Add flink 1.19 to the documentation.

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/RemoteLookupJoinITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/FlinkSinkTest.java

[hotfix] Remove redundant and unused test code

---

docs/content/engines/trino.md

[doc] Fix version in trino documentation

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CompactProcedure.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/SortCompactActionForDynamicBucketITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/SortCompactActionForUnawareBucketITCase.java

[flink] Compact procedure does not process 'ALL' word

---

paimon-core/src/test/java/org/apache/paimon/tag/TagAutoCreationTest.java

[fix] Fix unstable test TagAutoCreationTest#testModifyTagPeriod

---

docs/content/how-to/creating-catalogs.md
docs/layouts/shortcodes/generated/jdbc_catalog_configuration.html
paimon-core/src/main/java/org/apache/paimon/jdbc/AbstractDistributedLockDialect.java
paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalog.java
paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalogFactory.java
paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalogLock.java
paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalogOptions.java
paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcDistributedLockDialect.java
paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcUtils.java
paimon-core/src/main/java/org/apache/paimon/jdbc/MysqlDistributedLockDialect.java
paimon-core/src/main/java/org/apache/paimon/jdbc/SqlLiteDistributedLockDialect.java
paimon-core/src/test/java/org/apache/paimon/jdbc/JdbcCatalogTest.java

Linked issue: close (https://github.com/apache/incubator-paimon/issues/3046)

[Core]JdbcCatalog supports custom configuration for the length of lock table

---

.asf.yaml
.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/workflows/publish_snapshot.yml
DISCLAIMER
NOTICE
README.md
docs/config.toml
docs/content/_index.md
docs/content/concepts/overview.md
docs/content/project/contributing.md
docs/layouts/partials/docs/inject/footer.html
pom.xml
tools/ci/sonar_check.sh

[docs] Apache Paimon became top level project.

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java

[flink] Fix performance issue in ContinuousFileSplitEnumerator

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncTableActionBase.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SynchronizationActionBase.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/CdcActionITCaseBase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSchemaITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/postgres/PostgresSyncTableActionITCase.java

[Refactor] Minor refactor #3062

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java

[bug] fix Mysql Sync Table Unable to synchronize newly added tables

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java

Fix checkstyle violation for #2851

[hotfix] Apply spotless to fix checkstyle violation in flink-cdc module

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/UnawareBucketAppendOnlyTableITCase.java

[test] Append only table can't test failing IO re-insert yet

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java

[hotfix] Fix unstable test MySqlSyncTableActionITCase#testSyncShards

---

paimon-common/src/main/java/org/apache/paimon/data/BinaryRow.java
paimon-core/src/main/java/org/apache/paimon/io/DataFilePathFactory.java
paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java
paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java
paimon-core/src/main/java/org/apache/paimon/table/system/ManifestsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/SystemTableLoader.java
paimon-core/src/main/java/org/apache/paimon/utils/FileStorePathFactory.java
paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java
paimon-core/src/test/java/org/apache/paimon/format/FileFormatSuffixTest.java
paimon-core/src/test/java/org/apache/paimon/io/DataFilePathFactoryTest.java
paimon-core/src/test/java/org/apache/paimon/io/KeyValueFileReadWriteTest.java
paimon-core/src/test/java/org/apache/paimon/io/RollingFileWriterTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/ContainsLevelsTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/LookupLevelsTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTestBase.java
paimon-core/src/test/java/org/apache/paimon/operation/OrphanFilesCleanTest.java
paimon-core/src/test/java/org/apache/paimon/table/sink/TableCommitTest.java
paimon-core/src/test/java/org/apache/paimon/table/system/ManifestsTableTest.java
paimon-core/src/test/java/org/apache/paimon/utils/FileStorePathFactoryTest.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonPartitionManagement.scala

[core] Refactor FileStorePathFactory to clean test methods

---

docs/content/how-to/creating-catalogs.md
paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/LockContextUtils.java
paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalogLock.java
paimon-core/src/test/java/org/apache/paimon/catalog/FileSystemCatalogTest.java

Linked issue: close (https://github.com/apache/incubator-paimon/issues/3032)

[core]Support common jdbc catalog lock for filesystem catalog.

---

paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java

[Core] Fix OrphanFilesClean has a chance to delete normal file

---

paimon-common/src/main/java/org/apache/paimon/reader/FileRecordIterator.java
paimon-common/src/main/java/org/apache/paimon/utils/IteratorResultIterator.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
paimon-format/src/main/java/org/apache/paimon/format/avro/AvroBulkFormat.java
paimon-format/src/test/java/org/apache/paimon/format/avro/AvroFileFormatTest.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DeletionVectorTest.scala

Subtask of #2898,  support dv with avro format

[core] Support dv with avro format

---

paimon-core/src/test/java/org/apache/paimon/operation/KeyValueFileStoreScanTest.java

[test] Fix test in KeyValueFileStoreScanTest, make it more accurate.

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaValueOnlyDeserializationSchemaWrapper.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaDebeziumSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/resources/kafka/debezium/table/nullvalue/debezium-data-1.txt
paimon-flink/paimon-flink-cdc/src/test/resources/kafka/debezium/table/nullvalue/debezium-data-2.txt

Null value is produced by tombstone-events
https://debezium.io/documentation/reference/2.5/connectors/mysql.html#mysql-tombstone-events

[cdc] Fix that kafka message value might be null which causes NPE

---

paimon-common/src/test/java/org/apache/paimon/fs/ByteArraySeekableStreamTest.java

Random test index out of bounds.

[test] Fix random test in ByteArraySeekableStreamTest.

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java
paimon-core/src/main/java/org/apache/paimon/crosspartition/GlobalIndexAssigner.java
paimon-core/src/main/java/org/apache/paimon/disk/ChannelWithMeta.java
paimon-core/src/main/java/org/apache/paimon/disk/ChannelWriterOutputView.java
paimon-core/src/main/java/org/apache/paimon/disk/ExternalBuffer.java
paimon-core/src/main/java/org/apache/paimon/disk/RowBuffer.java
paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBState.java
paimon-core/src/main/java/org/apache/paimon/mergetree/MergeSorter.java
paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeWriter.java
paimon-core/src/main/java/org/apache/paimon/mergetree/SortBufferWriteBuffer.java
paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/sort/AbstractBinaryExternalMerger.java
paimon-core/src/main/java/org/apache/paimon/sort/BinaryExternalSortBuffer.java
paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java
paimon-core/src/test/java/org/apache/paimon/disk/ExternalBufferTest.java
paimon-core/src/test/java/org/apache/paimon/format/FileFormatSuffixTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTestBase.java
paimon-core/src/test/java/org/apache/paimon/mergetree/SortBufferWriteBufferTestBase.java
paimon-core/src/test/java/org/apache/paimon/sort/BinaryExternalSortBufferTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/LocalMergeOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/SortOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/SortUtils.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sorter/SortOperatorTest.java

[core] Add limitation to the buffer spill disk usage

---

docs/content/cdc-ingestion/overview.md
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncTableActionBase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSchemaITCase.java

[cdc] Fix table synchronization hasn't copied dynamic options

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/Changelog.java
paimon-core/src/main/java/org/apache/paimon/table/ExpireSnapshotsImpl.java
paimon-core/src/main/java/org/apache/paimon/table/RollbackHelper.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ContinuousFromTimestampStartingScannerTest.java
paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java

[core] Refactor changelog to snapshot reference

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/DeduplicateMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FirstRowMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FistRowMergeFunctionWrapper.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FullChangelogMergeFunctionWrapper.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/AggregateMergeFunction.java
paimon-core/src/test/java/org/apache/paimon/operation/KeyValueFileStoreReadTest.java

[core] MergeFunction.getResult return not null

---

paimon-core/src/main/java/org/apache/paimon/utils/FileStorePathFactory.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonSplitScan.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonDeleteTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeIntoBase.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonUpdateTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/RowLevelHelper.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/RowLevelOp.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/expressions/ExpressionHelper.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/expressions/ExpressionUtils.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/SparkDataFileMeta.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/UpdatePaimonTableCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/WriteIntoPaimonTable.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTestBase.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/UpdateTableTest.scala

https://github.com/apache/paimon/issues/3057

[spark] update for append table

---

paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionITCaseBase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaDebeziumSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSchemaITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableActionITCase.java

A step of #3123
Reduce codes for records writing;
Reuse Kafka objects.

[cdc][refactor] Refactor records writing in Kafka CDC tests

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactDatabaseActionITCase.java

Asynchronous snapshot expiration cause the snapshot manager to read a snapshot which is exipiring.
[Failed test case](https://github.com/apache/paimon/actions/runs/8520283994/job/23336095324)

[hotfix] Fix unstable test CompactDatabaseActionITCase#testCombinedModeWithDynamicOptions

---

paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java

[hotfix] Fix failed test KafkaCanalSyncTableActionITCase#testStarUpOptionLatest

---

paimon-common/src/main/antlr4/JavaParser.g4

Standardize g4 file with lexer code string.

[common] Change Parser string with lexer

---

paimon-common/src/main/java/org/apache/paimon/options/MemorySize.java
paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
paimon-core/src/test/java/org/apache/paimon/table/source/SplitGeneratorTest.java

[test] Add test case for read with raw convertible splits

---

paimon-core/src/main/java/org/apache/paimon/utils/BranchManager.java
paimon-core/src/test/java/org/apache/paimon/table/system/TagsTableTest.java

1. TagManager also return tags in order (of snapshot id)
2. Make test stable

[core] BranchManager lists branches in the order of create time

---

paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonDeleteTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonDeleteTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonUpdateTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DeleteFromTableTest.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/UpdateTableTest.scala

https://github.com/apache/paimon/issues/3057

[spark] support subquery for spark update/delete

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ActionBase.java

ActionBase initializes the catalog and env, and the API calls the Action class, which can be customized for initialization

Support custom initial flink catalog & env

---

paimon-common/src/test/java/org/apache/paimon/utils/BloomFilter64Test.java

see
```
2024-04-08T10:31:53.5273247Z [INFO] Tests run: 10000, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1,413.912 s - in org.apache.paimon.utils.BloomFilter64Test
```

[test] Reduce the number of tests  for BloomFilter64Test.testFunction

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java
pom.xml

[test] Replace Awaitility with CommonTestUtils to reduce dependency

---

paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexFormat.java
paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexPredicate.java
paimon-common/src/test/java/org/apache/paimon/fileindex/FileIndexFormatFormatTest.java

Related pr: https://github.com/apache/paimon/pull/3068
New file index format:
* REASON
It's better to put all type of index into one file, we don't want many small files.

[core] File index format should include all type index and columns.

---

paimon-core/src/main/java/org/apache/paimon/table/ExpireChangelogImpl.java
paimon-core/src/main/java/org/apache/paimon/table/ExpireSnapshotsImpl.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/ExpireSnapshotsProcedureTest.scala

Retain number in Snapshot expire need guard check max retina num need greater than min retina num

[Snapshot] Retain number in Snapshot expire need guard check

---

paimon-core/src/main/java/org/apache/paimon/Snapshot.java
paimon-core/src/test/java/org/apache/paimon/SnapshotTest.java

In order to make the old reader compatible with the new format

[core] Add ignoreUnknown to Snapshot

---

paimon-common/src/main/java/org/apache/paimon/fs/FileIO.java
paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java
paimon-core/src/main/java/org/apache/paimon/utils/BranchManager.java
paimon-core/src/main/java/org/apache/paimon/utils/FileUtils.java

To fix https://github.com/apache/paimon-trino/issues/61

[core] Add listDirectories to FileIO

---

paimon-core/src/test/java/org/apache/paimon/mergetree/SortBufferWriteBufferTestBase.java
pom.xml

[test] By removing all default exclusions the nested classes get executed

---

docs/content/program-api/flink-api.md
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcSinkBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/SortCompactAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/TableActionBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkTableSinkBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/LogFlinkSinkBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/SortCompactSinkBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/DataTableSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkSourceBuilder.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FileStoreITCase.java

[api] Publish DataStream Sink & Source API

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-common/src/main/java/org/apache/paimon/fs/FileIO.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
paimon-core/src/test/java/org/apache/paimon/schema/TableSchemaTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkTableSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/SupportsRowLevelOperationFlinkTableSink.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/DynamicBucketTableITCase.java

Linked issue: close #2956 
and
1, add validation for bucket configuration.
2, fix typo.

[flink] Fixed the issue where deletes could not be performed when the table is in dynamic bucket mode.

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala

[Spark] Default parallelism also considers numShufflePartitions

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java

This PR fixes the unstable test case `CatalogITCaseBase#testTagsTable`.

[test] Fix unstable test case CatalogITCaseBase#testTagsTable

---

paimon-core/src/main/java/org/apache/paimon/lookup/BulkLoader.java

fix memory leak bug of bulkLoader

---

docs/content/maintenance/write-performance.md
docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-common/src/main/java/org/apache/paimon/utils/MathUtils.java
paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeWriter.java
paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTestBase.java

[core] Increase default sorted run stop trigger

---

paimon-common/src/main/java/org/apache/paimon/reader/EmptyRecordReader.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/ApplyDeletionVectorReader.java
paimon-core/src/main/java/org/apache/paimon/io/FileIndexSkipper.java
paimon-core/src/main/java/org/apache/paimon/operation/RawFileSplitRead.java

[core] Expose reader and dv from ApplyDeletionVectorReader

---

paimon-spark/paimon-spark-3.4/pom.xml

Apr 18, 2024
https://spark.apache.org/news/spark-3-4-3-released.html
GA

[spark] Bump Spark version 3.4.3

---

paimon-bundle/pom.xml
paimon-flink/paimon-flink-common/pom.xml

[dep] Move netty dep from bundle to flink

---

paimon-core/src/main/java/org/apache/paimon/deletionvectors/ApplyDeletionFileRecordIterator.java

Engine can know better about paimon underly deletion vectors, and do some optimization.

[core] Introduce ApplyDeletionFileRecordIterator to know underly iterator and dv

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java

Linked issue: close https://github.com/apache/paimon/issues/3260
Skip FlinkCatalog#listPartitions scan for FlinkRecomputeStatisticsProgram.

[flink] Skip FlinkCatalog#listPartitions scan for FlinkRecomputeStatisticsProgram

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala

[spark] drop partition when all the conditions is partition-related

---

docs/content/engines/trino.md
docs/content/project/download.md

[docs] Update lowest trino version to 420.

---

paimon-core/src/main/java/org/apache/paimon/operation/FileStoreScan.java
paimon-core/src/main/java/org/apache/paimon/operation/PartitionExpire.java
paimon-core/src/main/java/org/apache/paimon/table/source/TableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReader.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala

1. Improve PartitionExpire.
2. Improve `DeleteFromPaimonTableCommand`.

[core][spark] Use list partitions with predicate

---

paimon-core/src/main/java/org/apache/paimon/table/source/IndexFile.java

[core] Expose path from IndexFile

---

paimon-format/src/main/java/org/apache/paimon/format/OrcOptions.java

Fix test or dev with NoSuchMethodException in IDE in OrcConf
When use or test would occur NoSuchMethodException ，so change it to lit for avoid the exception

[core] Fix test or dev with NoSuchMethodException in IDE with OrcConf

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DeleteFromTableTest.scala

[spark] fix when the delete condition does not match any partitions

---

paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/CreateAndDeleteTagProcedureTest.scala
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/DeleteTagProcedure.java

Support delete tags in batch mode

[procedure] Support delete tags in batch mode

---

docs/content/maintenance/manage-tags.md

[spark]fix call procedure miss sys database name

---

paimon-common/src/main/java/org/apache/paimon/utils/BinaryStringUtils.java
paimon-common/src/main/java/org/apache/paimon/utils/StringUtils.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/InsertOverwriteTest.scala

[core] Fix partition type batch write with DATE and TIME

---

paimon-common/src/main/java/org/apache/paimon/utils/IteratorResultIterator.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/ApplyDeletionFileRecordIterator.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/ApplyDeletionVectorReader.java
paimon-core/src/main/java/org/apache/paimon/io/KeyValueFileReaderFactory.java
paimon-core/src/main/java/org/apache/paimon/operation/RawFileSplitRead.java
paimon-format/src/main/java/org/apache/paimon/format/avro/AvroBulkFormat.java

[core] declare InternalRow type definitely instead of Pattern <T> in classes related to DV

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkTable.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBatch.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonPartitionReader.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonPartitionReaderFactory.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonRecordReaderIterator.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonStatistics.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/schema/PaimonMetadataColumn.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/sources/PaimonMicroBatchStream.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonQueryTest.scala

[spark] supports metadata columns

---

paimon-common/src/main/java/org/apache/paimon/utils/RoaringBitmap32.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/BitmapDeletionVector.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVector.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVectorsMaintainer.java

This pr is pre-work for supporting upsert operations for append mor table.

[core] merge and getCardinality api in DeletionVector

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/TBPropertiesLocationHelper.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

[Hive] fix db-location conflict with location-in-properties

---

docs/content/engines/overview.md

The Apache Doris link was updated and the Trino part was modified.

Modification of Doris and Trino parts

---

paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVector.java
paimon-core/src/main/java/org/apache/paimon/table/source/DeletionFile.java

[core] introduce DeletionFile.Factory

---

paimon-bundle/pom.xml
paimon-bundle/src/assembly/src-assembly.xml

[pom]add source code to the  source jar of paimon bundle

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSink.java

[flink] [bug] Deletion table should set waitCompaction to true.

---

paimon-core/src/main/java/org/apache/paimon/table/system/StatisticTable.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonAnalyzeTableColumnCommand.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTestBase.scala

[spark][core] fix when a table have no snapshot or no statistics

---

paimon-core/src/test/java/org/apache/paimon/operation/FileStoreCommitTest.java

[core] fix testIndexFiles flaky ut

---

paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/sink/RowKindGenerator.java
paimon-core/src/main/java/org/apache/paimon/table/sink/TableWriteImpl.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/LocalMergeOperator.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java

[core] Fix that ignore-delete hasn't handle rowkind.field

---

docs/content/engines/starrocks.md
docs/content/maintenance/system-tables.md

Add a document for using Paimon in StarRocks.
No need.
No.
engines#starrocks.md

[doc] Add doc for StarRocks

---

docs/content/flink/cdc-ingestion/kafka-cdc.md
docs/content/flink/cdc-ingestion/pulsar-cdc.md
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/DataFormat.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/json/JsonRecordParser.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaJsonSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/resources/kafka/json/table/computedcolumn/json-data-1.txt
paimon-flink/paimon-flink-cdc/src/test/resources/kafka/json/table/schemaevolution/json-data-1.txt
paimon-flink/paimon-flink-cdc/src/test/resources/kafka/json/table/schemaevolution/json-data-2.txt

[Flink]paimon-action support normal json format

---

paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/utils/HiveUtils.java

[hive] JobConf should be passed to create paimon table

---

paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyTableUtils.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

Fix flink not synchronizing to hive metastore when deleting table partitions using hive catalog.

[Hive] Fix flink not synchronizing to hive metastore when deleting table partitions using hive catalog.

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaEvolutionUtil.java

fix method annotation in SchemaEvolutionUtil

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala

[spark] use metadata column to replace inpute_file_name udf

---

paimon-common/src/main/java/org/apache/paimon/predicate/PredicateBuilder.java
paimon-common/src/main/java/org/apache/paimon/utils/InternalRowPartitionComputer.java
paimon-common/src/main/java/org/apache/paimon/utils/RowDataToObjectArrayConverter.java
paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/manifest/ManifestFileMeta.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
paimon-core/src/main/java/org/apache/paimon/partition/PartitionPredicate.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
paimon-core/src/main/java/org/apache/paimon/utils/FileStorePathFactory.java
paimon-core/src/test/java/org/apache/paimon/operation/FileStoreCommitTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/SortCompactAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/TableActionBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/UnawareBucketCompactionTopoBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionMarkDone.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/CompactorSourceBuilder.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveMetastoreClient.java
paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/utils/HiveSplitGenerator.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonPartitionManagement.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/sources/StreamHelper.scala

[core] Unify Partition Predicate generation in PartitionPredicate

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonSplitScan.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/ScanHelper.scala

PaimonSplitScan can use `reshuffleSplits` just like PaimonScan

[spark] Reshuffle splits in PaimonSplitScan

---

paimon-core/src/main/java/org/apache/paimon/partition/PartitionPredicate.java
paimon-core/src/test/java/org/apache/paimon/operation/AppendOnlyFileStoreWriteTest.java

Related to https://github.com/apache/paimon/pull/3421

[core] [bug] Fix Partition Predicate null values process.

---

paimon-format/src/main/java/org/apache/paimon/format/parquet/writer/RowDataParquetBuilder.java

[parquet] Pass conf to parquet writer

---

paimon-core/src/main/java/org/apache/paimon/table/source/MergeTreeSplitGenerator.java
paimon-core/src/test/java/org/apache/paimon/io/DataFileTestUtils.java
paimon-core/src/test/java/org/apache/paimon/table/source/SplitGeneratorTest.java

[core] Fix raw convert fail for old storage ro table

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/kafka/KafkaLogSourceProvider.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/log/LogSourceProvider.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkSourceBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/LogHybridSourceFactory.java

[flink] Support pre create log source

---

paimon-core/src/main/java/org/apache/paimon/partition/PartitionTimeExtractor.java

fix LoggerFactor in PartitionTimeExtractor

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala

[spak] unify the writer logic of deletion vector

---

docs/content/maintenance/dedicated-compaction.md

hotfix.
Delete redundant symbols in compaction doc.

[hotfix] Delete redundant symbols in compaction doc

---

paimon-core/src/main/java/org/apache/paimon/table/source/SingletonSplit.java
paimon-core/src/main/java/org/apache/paimon/table/system/AggregationFieldsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/AllTableOptionsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/BranchesTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/CatalogOptionsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/ConsumersTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/FilesTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/ManifestsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/OptionsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/PartitionsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/SchemasTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/SnapshotsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/StatisticTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/TagsTable.java

[bug] [core] FilesTable splits too big to distribute.

---

docs/layouts/shortcodes/generated/flink_connector_configuration.html
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CombinedTableCompactorSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkEndInputWatermarkITCase.java

Linked issue: [3425](https://github.com/apache/paimon/issues/3425)

support watermark in batch mode

---

paimon-core/src/main/java/org/apache/paimon/table/ExpireSnapshotsImpl.java

Linked issue: https://github.com/apache/paimon/issues/3397

[Core] Fix snapshot EARLIEST first write value

---

docs/content/primary-key-table/changelog-producer.md

fix_Changelog_Producer_doc

---

docs/README.md

[doc]specify hugo version

---

paimon-core/src/main/java/org/apache/paimon/metastore/AddPartitionCommitCallback.java

[core] Add cache in AddPartitionCommitCallback

---

docs/content/engines/doris.md

add Apache Doris document in 'engines' category

[doc] add Apache Doris document in 'engines' category

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogTest.java

Linked issue: close #3489 
Support creating database with properties in flink which is supported in spark
Added test case FlinkCatalogTest#testCreateDb_DatabaseWithProperties
no
no

[flink] Support creating database with properties in flink

---

paimon-core/src/main/java/org/apache/paimon/tag/TagTimeExtractor.java

Linked issue: https://github.com/apache/paimon/issues/3488

[minor] Just ignore the Long.MIN_VALUE watermark when creating the tag.

---

paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/operation/FileDeletionBase.java
paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java
paimon-core/src/main/java/org/apache/paimon/operation/SnapshotDeletion.java
paimon-core/src/main/java/org/apache/paimon/operation/TagDeletion.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/RollbackHelper.java
paimon-core/src/main/java/org/apache/paimon/table/source/AbstractDataTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousFromSnapshotStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousFromTimestampStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/utils/NextSnapshotFetcher.java
paimon-core/src/test/java/org/apache/paimon/TestFileStore.java
paimon-core/src/test/java/org/apache/paimon/operation/ExpireSnapshotsTest.java
paimon-core/src/test/java/org/apache/paimon/operation/OrphanFilesCleanTest.java
paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ContinuousFromTimestampStartingScannerTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java

The third PR for https://github.com/apache/paimon/pull/3178 to support delta files decouple

[core] Changelog decouple supports delta files

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTypeUtils.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java

[cdc]add integer type for mysql cdc

---

paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/AbstractColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ParquetDecimalVector.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ParquetSplitReaderUtil.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ParquetTimestampVector.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/RunLengthDecoder.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/TimestampColumnReader.java
paimon-format/src/main/java/org/apache/parquet/hadoop/ParquetFileReader.java

[core] use paimon checkArgument instead of parquet's

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala

when there is a big subquery that need to involve shuffle to compute in delete condition, the metadata columns should be the output of `DatasourceV2Relation`, not just in the output of `DataSourceV2ScanRelation`, that can be computed correctly.

[spark] make metadata columns passed across shuffles

---

paimon-core/src/test/java/org/apache/paimon/utils/TraceableFileIO.java

see https://github.com/apache/paimon/actions/runs/9525273231/job/26259178799
Sorry for https://github.com/apache/paimon/pull/3447 is invalid, because `new ArrayList<>(OPEN_INPUT_STREAMS)` still has thread problems...

[test] Fix flaky test for ConcurrentModificationException with TraceableFileIO

---

docs/content/concepts/specification.md

change `t` to `my_table`
[https://github.com/apache/paimon/issues/3528](url)

closes #3528

---

paimon-common/src/main/java/org/apache/paimon/format/FormatReaderFactory.java
paimon-format/src/main/java/org/apache/paimon/format/avro/AvroBulkFormat.java
paimon-format/src/main/java/org/apache/paimon/format/orc/OrcReaderFactory.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetFileFormat.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetReaderFactory.java
paimon-format/src/main/java/org/apache/parquet/filter2/predicate/ParquetFilters.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetFiltersTest.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetReadWriteTest.java

There are multiple groups within a Parquet, and implementing filter pushdown can have a certain degree of data skipping effect.

[parquet] Introduce filter push down for parquet

---

paimon-core/src/main/java/org/apache/paimon/table/system/FilesTable.java
paimon-core/src/test/java/org/apache/paimon/table/system/FilesTableTest.java

Linked issue: close #3483.
New test case introduced to `FilesTableTest`

[core] Check if partition filter contains all partition keys for FilesTable

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java

_Change the access modifier of FileStoreLookupFunction#getRequireCachedBucketIds_
no
no
no

[flink] Change the access modifier of FileStoreLookupFunction#getRequireCachedBucketIds

---

paimon-flink/paimon-flink-1.19/pom.xml
paimon-flink/paimon-flink-common/pom.xml
pom.xml

[flink] Bump flink version to 1.19.1

---

docs/content/flink/procedures.md
paimon-core/src/main/java/org/apache/paimon/operation/PartitionExpire.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ExpirePartitionsProcedure.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/ExpirePartitionsProcedureITCase.java

Linked issue: https://github.com/apache/paimon/issues/3434

[flink] Add expire partitions procedure for flink.

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/CdcActionCommonUtils.java

[flink] Fix performance issue in CdcActionCommonUtils

---

paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalog.java
paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalogLockContext.java
paimon-core/src/test/java/org/apache/paimon/jdbc/JdbcCatalogTest.java

… in flink.
To fix serialize problem when using jdbc catalog with lock enbale lock in flink.
Linked issue: close #3541 
cover by exist test.
no
no

[core] fix serialize problem when using jdbc catalog with lock enbale lock in flink.

---

docs/content/spark/procedures.md
paimon-core/src/main/java/org/apache/paimon/operation/PartitionExpire.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ExpirePartitionsProcedure.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/ExpirePartitionsProcedureTest.scala

[spark] spark support expire partitions procedure.

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java

[common] Explain tag.num-retained-max

---

paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/sql/UpdateTableTest.scala
paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/UpdateTableTest.scala
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/UpdateTableTest.scala
paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/sql/UpdateTableTest.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/UpdatePaimonTableCommand.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/UpdateTableTestBase.scala

Fix update table with append table with spark 3.3-
Add a todo: support update appedn table with Exists/In subqueries with spark3.3-

[spark] Fix update append table with spark3.3-

---

paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StaticFromSnapshotStartingScanner.java
paimon-core/src/test/java/org/apache/paimon/table/source/StartupModeTest.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/IncrementalStartingScannerTest.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/StaticFromStartingScannerTest.java
paimon-core/src/test/java/org/apache/paimon/table/system/FilesTableTest.java
paimon-flink/paimon-flink-1.15/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkTimeTravelWithDataFrameITCase.java

[core] Check the validity of scan staring snapshotId

---

docs/content/flink/procedures.md
docs/content/spark/procedures.md

[doc] update docs for spark/flink create_tag

---

docs/content/spark/procedures.md
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/MergeBranchProcedure.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/MergeBranchProcedureTest.scala

Introduce MergeBranchProcedure for spark
Linked issue: https://github.com/apache/paimon/issues/3577

[spark] Introduce MergeBranchProcedure for spark

---

docs/content/spark/procedures.md
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ReplaceBranchProcedure.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/ReplaceBranchProcedureTest.scala

Introduce ReplaceBranchProcedure for spark
Linked issue: https://github.com/apache/paimon/issues/3575

[spark] Introduce ReplaceBranchProcedure for spark

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpirePartitionsAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpirePartitionsActionFactory.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ExpirePartitionsActionITCase.java

Introduce ExpirePartitionsAction for flink action jar call.
Linked issue: https://github.com/apache/paimon/issues/3587

[flink] Introduce ExpirePartitionsAction in flink

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ChangelogMergeTreeRewriter.java

[core] Avoid NPE covers real exceptions

---

docs/content/flink/cdc-ingestion/kafka-cdc.md
docs/content/flink/cdc-ingestion/mysql-cdc.md
docs/content/flink/cdc-ingestion/postgres-cdc.md
docs/content/flink/cdc-ingestion/pulsar-cdc.md

[doc] Fix flink cdc connectors document url link.

---

paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java

[common] Make 'ignore-delete' immutable

---

docs/content/flink/procedures.md
docs/content/maintenance/manage-branches.md

Document data branch and flink procudures.

[docs][branch] Document branch

---

paimon-core/src/main/java/org/apache/paimon/table/source/DataSplit.java
paimon-core/src/main/java/org/apache/paimon/table/source/RawFile.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/SnapshotReaderTest.java

Add more information in RawFile class.

[core] Add file size to RawFile

---

paimon-core/src/main/java/org/apache/paimon/operation/PartitionExpire.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ExpirePartitionsProcedure.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/ExpirePartitionsProcedureITCase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ExpirePartitionsProcedure.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/ExpirePartitionsProcedureTest.scala

Show the expired partition result list.

[core] Show the expired partition result list.

---

paimon-core/src/main/java/org/apache/paimon/utils/PartitionPathUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/PartitionMarkDoneAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/PartitionMarkDoneActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/PartitionMarkDoneProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionMarkDone.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkBatchJobPartitionMarkdoneITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/PartitionMarkDoneActionITCase.java

This pr is introduce PartitionMarkDone action and procedure for user can PartitionMarkDone at any time.

[flink] Introduce PartitionMarkDone action and procedure

---

docs/content/spark/procedures.md
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ResetConsumerProcedure.java

Introduce reset_consumer procedure in spark
Linked issue: https://github.com/apache/paimon/issues/3615

[spark] Introduce reset_consumer procedure

---

docs/content/flink/cdc-ingestion/mysql-cdc.md

[doc] Complement the version limit of mysql-cdc Bundled jar.

---

docs/content/maintenance/manage-branches.md
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CreateBranchAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CreateBranchActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DeleteBranchAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DeleteBranchActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MergeBranchAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MergeBranchActionFactory.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/BranchActionITCase.java

subtask of https://github.com/apache/paimon/issues/1795
org.apache.paimon.flink.action.BranchActionITCase
merge-branchs

[Flink]Add flink action for branch

---

docs/content/spark/procedures.md
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CreateBranchProcedure.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CreateAndDeleteBranchProcedureTest.scala

org.apache.paimon.spark.procedure.CreateAndDeleteBranchProcedureTest
spark procedures.md

[spark] Create empty_branch and create branch base on snapshot

---

paimon-core/src/main/java/org/apache/paimon/metastore/MetastoreClient.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/MarkPartitionDoneEventAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionMarkDoneAction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/AddDonePartitionActionTest.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveMetastoreClient.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

Add MarkPartitionDoneEventAction which calls `markPartitionForEvent ` method.

[flink]add MarkPartitionDoneEventAction.

---

docs/content/flink/procedures.md
docs/content/maintenance/manage-branches.md
docs/content/spark/procedures.md
paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/ReadonlyTable.java
paimon-core/src/main/java/org/apache/paimon/table/Table.java
paimon-core/src/main/java/org/apache/paimon/utils/BranchManager.java
paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/FastForwardAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/FastForwardActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/FastForwardProcedure.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/BranchActionITCase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/FastForwardProcedure.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/MergeBranchProcedureTest.scala

Rename merge_branch to fast_forward
Detail is here: https://lists.apache.org/thread/q46clxx38fz7n1xw0sgscmcslo3qrp5c

[Branch]Rename merge_branch to fast_forward

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/query/RemoteTableQuery.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/RemoteLookupJoinITCase.java
paimon-service/paimon-service-client/src/main/java/org/apache/paimon/service/client/KvQueryClient.java

[Flink] Fix unstable RemoteLookupJoinITCase.testServiceFileCleaned test method.

---

paimon-common/src/main/java/org/apache/paimon/data/columnar/heap/HeapRowVector.java
paimon-common/src/main/java/org/apache/paimon/utils/BooleanArrayList.java
paimon-common/src/main/java/org/apache/paimon/utils/IntArrayList.java
paimon-common/src/main/java/org/apache/paimon/utils/LongArrayList.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetReaderFactory.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/position/CollectionPosition.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/position/LevelDelegation.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/position/RowPosition.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/NestedColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/NestedPositionUtil.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/NestedPrimitiveColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ParquetDecimalVector.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ParquetSplitReaderUtil.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/type/ParquetField.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/type/ParquetGroupField.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/type/ParquetPrimitiveField.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetReadWriteTest.java

Linked issue: close #3642 
- support paimon read nested data.
- org.apache.paimon.format.parquet.ParquetReadWriteTest.testNestedRead
- yes, affect parquet.

[parquet] support read parquet nested columns.

---

paimon-common/src/main/java/org/apache/paimon/fs/FileIO.java

[core] Add log in the process of getting FileIO for better troubleshooting

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcDynamicTableParsingProcessFunction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcMultiplexRecordChannelComputer.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperator.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/CdcMultiplexRecordChannelComputerTest.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperatorTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/MultiTableScanBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/MultiUnawareBucketTableScan.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendOnlyMultiTableCompactionWorkerOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTablesStoreCompactOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreMultiCommitter.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedAwareBatchSourceFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedAwareStreamingSourceFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedUnawareBatchSourceFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedUnawareStreamingSourceFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/MultiTablesReadOperator.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/StoreMultiCommitterTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/MultiTablesCompactorSourceBuilderITCase.java

Fix unclosed catalog connection.

[hotfix] fix unclosed catalog connection.

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CompactProcedureTestBase.scala

`call sys.compact` can add some custom configs.

[spark] CompactProcedure add options parameter

---

paimon-core/src/main/java/org/apache/paimon/table/FileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/Table.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkTable.scala

[spark] SparkTable.name() returning a table name WITH database

---

paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVectorIndexFileMaintainer.java
paimon-core/src/test/java/org/apache/paimon/deletionvectors/DeletionVectorIndexFileMaintainerTest.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/SparkDeletionVectors.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/UpdatePaimonTableCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/WithFileStoreTable.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DeletionVectorTest.scala

[spark] spark update with deletion vector

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/tag/TagAutoCreation.java
paimon-core/src/test/java/org/apache/paimon/tag/TagAutoManagerTest.java

[core] Auto complete missing tags

---

paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexPredicate.java
paimon-core/src/main/java/org/apache/paimon/table/source/AbstractDataTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/DataTableStreamScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousFromSnapshotFullStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/utils/NextSnapshotFetcher.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/MonitorFunction.java

[core] check null scanSnapshotId to avoid npe

---

docs/content/filesystems/oss.md
docs/content/flink/procedures.md
docs/content/program-api/java-api.md
docs/content/spark/procedures.md

[docs] Fix some typos in docs

---

docs/content/spark/procedures.md
paimon-core/src/main/java/org/apache/paimon/stats/Statistics.java
paimon-core/src/main/java/org/apache/paimon/stats/StatsFileHandler.java
paimon-core/src/main/java/org/apache/paimon/utils/FileStorePathFactory.java
paimon-core/src/main/java/org/apache/paimon/utils/ScanParallelExecutor.java

Improve spark procedures document format and duplicate code calls
current:

[hotfix] Improve spark procedures document format and duplicate code calls

---

docs/content/primary-key-table/merge-engine.md
paimon-common/pom.xml
paimon-common/src/main/java/org/apache/paimon/utils/ThetaSketch.java
paimon-common/src/main/resources/META-INF/NOTICE
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregator.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldThetaSketchAgg.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregatorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java

subtask of #3717 
- org.apache.paimon.mergetree.compact.aggregate.FieldAggregatorTest#testFieldThetaSketchAgg
- org.apache.paimon.flink.PreAggregationITCase.ThetaSketchAggAggregationITCase#testThetaSketchAgg

[core] introduce theta_sketch aggregate function.

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AsyncLookupSinkWrite.java

[Flink] Fix class annotation of AsyncLookupSinkWrite

---

paimon-service/paimon-service-runtime/src/test/java/org/apache/paimon/service/KvQueryTableTest.java

[flink] Fix unstable KvQueryTableTest.testServerRestartSamePorts test method.

---

paimon-core/src/test/java/org/apache/paimon/iceberg/IcebergCompatibilityTest.java

[test] Fix spelling error in IcebergCompatibilityTest

---

docs/content/primary-key-table/merge-engine/partial-update.md

Linked issue: close #3741
Add doc for multi-sorted fields sequence-group example in Partial Update.

[doc] Add doc for sequence-group using multiple sorting fields

---

paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexResult.java

add default implementation to FileIndexResult and/or operation.

[core] add default implementation to FileIndexResult and/or operation.

---

paimon-core/src/main/java/org/apache/paimon/utils/JsonSerdeUtil.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/watermark/CdcTimestampExtractorFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/watermark/CdcWatermarkStrategy.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/CdcDebeziumTimestampExtractorITCase.java

[cdc] Fix flink cdc source record watermark timestamp extractor.

---

paimon-common/src/test/java/org/apache/paimon/fs/local/LocalFileIOTest.java

[test] Fix spelling error in LocalFileIOTest

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java

`assertMainBranch` can be a common method.

[rename] Extract assertMainBranch to AbstractCatalog

---

paimon-common/src/main/java/org/apache/paimon/utils/RoaringBitmap32.java

Add and/or operation to RoaringBitmap32.

[common] Add some methods to RoaringBitmap32

---

paimon-common/src/main/java/org/apache/paimon/utils/FileDeletionThreadPool.java

[core] Fix cache thread pool in FileDeletionThreadPool

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java

Partial-update with nested-update agg has thread safety bug.
The nested-update agg has internal state in Projection class, but it is shared by multiple Partial-update function.
TODO

[WIP][core] Fix thread safety bug in Partial-update with agg

---

docs/content/maintenance/system-tables.md

[doc] Document branches system table.

---

paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexWriter.java
paimon-common/src/main/java/org/apache/paimon/fileindex/bloomfilter/BloomFilterFileIndex.java
paimon-core/src/main/java/org/apache/paimon/io/DataFileIndexWriter.java

[core] Pass null value to file index

---

docs/content/maintenance/manage-branches.md
paimon-core/src/main/java/org/apache/paimon/consumer/ConsumerManager.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/ExpireChangelogImpl.java
paimon-core/src/main/java/org/apache/paimon/table/ExpireSnapshotsImpl.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
paimon-core/src/test/java/org/apache/paimon/consumer/ConsumerManagerTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ResetConsumerAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ResetConsumerProcedure.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ConsumerActionITCase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ResetConsumerProcedure.java

org.apache.paimon.flink.action.ConsumerActionITCase
org.apache.paimon.consumer.ConsumerManagerTest

[core] Consumer support branch

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CombinedTableCompactorSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTableCommittableChannelComputer.java

…perators
Linked issue: close #3231

[flink] Improve the parallelism of Flink database compression commit operator

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java

[doc] Fix duplicate possible values description in the configuration doc.

---

docs/content/maintenance/dedicated-compaction.md

Dedicated-compaction doc tabs set error value.

[doc]fix dedicated-compaction doc

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java
paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalog.java
paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java

- Extract `DelegateCatalog` to more catalog implementations, for example, `CachedCatalog`.

[core] Introduce DelegateCatalog

---

docs/content/program-api/flink-api.md

Missing an import in flink-api.md,  fix it.
flink-api.md

[doc] Missing an import in flink-api.md

---

paimon-common/src/main/java/org/apache/paimon/fs/AsyncPositionOutputStream.java
paimon-core/src/main/java/org/apache/paimon/io/SingleFileWriter.java

TODO
Please DO NOT merge this, this is a work in-progress PR.

[WIP][core] Introduce AsyncPositionOutputStream

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveMetastoreClient.java

[hotfix] HiveMetastoreClient should ignore branch

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonAnalysis.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DataFrameWriteTest.scala

[spark] support complex data type in byName mode

---

paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/lookup/LookupWriterBenchmark.java

Linked issue: close #3861 
no
no
no

[core] Add writing different data for keys in lookup file store benchmark

---

paimon-common/src/main/java/org/apache/paimon/data/serializer/RowCompactedSerializer.java
paimon-common/src/test/java/org/apache/paimon/lookup/sort/SortLookupStoreFactoryTest.java

Linked issue: close #3879 
Calculate header size from field count for slice comparator
Added test SortLookupStoreFactoryTest#testIntKey
no
no

[core] Calculate header size from field count for slice comparator

---

docs/content/spark/auxiliary.md

Add Spark Auxiliary Statements page for paimon, refer to https://spark.apache.org/docs/latest/sql-ref-syntax.html#auxiliary-statements

[doc] Add Auxiliary Statements for spark

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlRecordParser.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/resources/mysql/sync_table_setup.sql

cdc schema change shoud add column comment
Linked issue: close #3666 
testSchemaEvolutionWithComment

[cdc] mysql cdc schema change shoud add column comment

---

paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java

…te might be swallowed.
Linked issue: close #3938 
[core] fix the issue where exceptions in RowDataRollingFileWriter#write might be swallowed.
No
No
No

[core] fix the issue where exceptions in RowDataRollingFileWriter#write might be swallowed.

---

paimon-spark/paimon-spark-3.5/pom.xml
paimon-spark/paimon-spark-common/pom.xml

Bump Spark branch-3.5 version to 3.5.2
Pass CI
no

[spark] Bump Spark 3.5.2

---

docs/content/flink/expire-partition.md

Add "end-input.check-partition-expire" doc for partition expire.

[doc] Doc for 'end-input.check-partition-expire'

---

paimon-hive/paimon-hive-common/src/test/java/org/apache/paimon/hive/TestHiveMetastore.java

[test] fix flaky test TestHiveMetastore.

---

paimon-core/src/main/java/org/apache/paimon/crosspartition/GlobalIndexAssigner.java

Extract a lazy method for #3976

[core] Refactor GlobalIndexAssigner to introduce endBoostrapWithoutEmit

---

paimon-core/src/main/java/org/apache/paimon/Snapshot.java
paimon-core/src/main/java/org/apache/paimon/manifest/ManifestEntry.java
paimon-core/src/main/java/org/apache/paimon/manifest/ManifestList.java
paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java
paimon-core/src/main/java/org/apache/paimon/operation/FileDeletionBase.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreScan.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/DelegatedFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/ReadonlyTable.java
paimon-core/src/main/java/org/apache/paimon/table/Table.java
paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/BucketsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/FileMonitorTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/ManifestsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/ReadOptimizedTable.java
paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
paimon-core/src/test/java/org/apache/paimon/TestFileStore.java
paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java
paimon-core/src/test/java/org/apache/paimon/operation/KeyValueFileStoreScanTest.java
paimon-core/src/test/java/org/apache/paimon/operation/OrphanFilesCleanTest.java
paimon-core/src/test/java/org/apache/paimon/table/system/ManifestsTableTest.java

We should expose more interfaces to compute engines, there may be various needs, and these data structures inherently need to consider compatibility; We can make them public.
1. Make Snapshot public.
2. Introduce Table snapshot(long snapshotId)

[core] Introduce Table.snapshot(long snapshotId)

---

paimon-core/src/main/java/org/apache/paimon/crosspartition/KeyPartOrRow.java
paimon-core/src/main/java/org/apache/paimon/crosspartition/KeyPartPartitionKeyExtractor.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalDynamicBucketSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalIndexAssignerOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/IndexBootstrapOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/KeyPartRowChannelComputer.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/KeyWithRowSerializer.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/BucketProcessor.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DynamicBucketTableTest.scala

Support cross partition write for spark

[spark] Support cross partition write

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/partition/actions/PartitionMarkDoneAction.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

Improve partition mark done action type documentation

[doc] Improve partition mark done action type documentation

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/MergeIntoPaimonTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/schema/PaimonMetadataColumn.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DeletionVectorTest.scala

to support Spark MergeInto DML with DeletionVector

[spark] Support Spark MergeInto with DeletionVector

---

paimon-arrow/src/main/java/org/apache/paimon/arrow/reader/ArrowBatchReader.java
paimon-arrow/src/test/java/org/apache/paimon/arrow/vector/ArrowFormatWriterTest.java

Maybe `VectorSchemaRoot` schema does not match projectRowType for now, we should make a fit

[arrow] Arrow reader should check schema match every time

---

paimon-core/src/main/java/org/apache/paimon/AppendOnlyFileStore.java
paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java
paimon-core/src/main/java/org/apache/paimon/append/BucketedAppendCompactManager.java
paimon-core/src/main/java/org/apache/paimon/append/UnawareAppendCompactionTask.java
paimon-core/src/main/java/org/apache/paimon/append/UnawareAppendTableCompactionCoordinator.java
paimon-core/src/main/java/org/apache/paimon/compact/CompactResult.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVectorsMaintainer.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/append/AppendDeletionFileMaintainer.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/append/BucketedAppendDeletionFileMaintainer.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/append/UnawareAppendDeletionFileMaintainer.java
paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeWriter.java
paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/operation/MemoryFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/utils/CommitIncrement.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java

[core] Refactor codes for compact with deletion vector

---

paimon-core/src/main/java/org/apache/paimon/iceberg/AbstractIcebergCommitCallback.java

`AbstractIcebergCommitCallback#compactMetadataIfNeeded` mistakenly uses `manifestFile` concurrently, but `IcebergManifestFile` is not thread safe. This bug will cause unstable tests in `IcebergCompatibilityTest#testPartitionedPrimaryKeyTable`.
This PR fixes this issue.
`IcebergCompatibilityTest#testPartitionedPrimaryKeyTable`

[core] Fix thread safety issue about IcebergManifestFile in Iceberg commit callback

---

paimon-arrow/src/main/java/org/apache/paimon/arrow/ArrowUtils.java

This method is useful. For example, this need it:
https://github.com/apache/paimon-python/pull/8/

[refactor] Make ArrowUtils#toArrowField public

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala

Fix bootstrap record reader not close
N/A
no

[spark] Fix bootstrap record reader not close

---

paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/lookup/AbstractLookupBenchmark.java
paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/lookup/LookupBloomFilterBenchmark.java
paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/lookup/LookupReaderBenchmark.java

Linked issue: close #4017 
Add benchmark for reader
None
No
No

[core] Add reader benchmark for sorted file store

---

docs/content/maintenance/metrics.md
paimon-core/src/main/java/org/apache/paimon/compact/CompactTask.java
paimon-core/src/main/java/org/apache/paimon/operation/metrics/CompactionMetrics.java
paimon-core/src/test/java/org/apache/paimon/operation/metrics/CompactionMetricsTest.java

[core] Introduce avgCompactionTime metrics

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CompactProcedure.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/CompactProcedureITCase.java

Support using procedure to compact historical partition in flink. 
`CompactProcedureITCase`#`testHistoryPartitionCompact`

[flink] add history partition compact procedure in flink

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CreateTagFromTimestampAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CreateTagFromTimestampActionFactory.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CreateTagFromTimestampActionITTest.java

Linked issue: close #
Follow up https://github.com/apache/paimon/pull/4051
introduce action for create_tag_from_timestamp.

[flink] Introduce CreateTagFromTimestampAction for flink

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java

Implements `FlinkCatalog#getPartition`.
IT
No.
No.

[flink] Implements FlinkCatalog#getPartition

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpireSnapshotsAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpireSnapshotsActionFactory.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/ExpireSnapshotsProcedureITCase.java

Add expire snapshots action for old version flink

[flink] Add expire snapshots action.

---

paimon-core/src/main/java/org/apache/paimon/table/system/SchemasTable.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java

Support schema_id push down for $schemas to improve performance.
CatalogTableITCase#testSchemasTable

[core] Optimize `schemas` system table when specifying schema id

---

paimon-common/src/main/java/org/apache/paimon/utils/Pool.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FileStoreSourceSplitReader.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FileStoreSourceSplitReaderTest.java

[flink] fix the source data fetcher thread leak

---

docs/content/flink/procedures.md

[doc] Complement the usage section of procedure compact.

---

paimon-core/src/main/java/org/apache/paimon/table/system/TagsTable.java
paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java

[core] Optimize tags system table when specifying tag_name

---

docs/content/primary-key-table/merge-engine/aggregation.md

[doc] fix doc aggregation.md tabs name error.

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CreateTagFromWatermarkAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CreateTagFromWatermarkActionFactory.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CreateTagFromWatermarkActionITTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/CreateTagFromWatermarkProcedureITCase.java

add CreateTagFromWatermarkAction for old flink version

[flink] add CreateTagFromWatermarkAction

---

paimon-common/src/main/java/org/apache/paimon/lookup/sort/SortLookupStoreReader.java
paimon-common/src/main/java/org/apache/paimon/lookup/sort/SortLookupStoreUtils.java
paimon-common/src/main/java/org/apache/paimon/lookup/sort/SortLookupStoreWriter.java

Linked issue: close #4128 
Existing test SortLookupStoreFactoryTest
no
no

[core] Check reader checksum for sort file store

---

docs/content/append-table/query.md

[doc] Fix the duplicate descriptions about data file index.

---

paimon-common/src/main/java/org/apache/paimon/lookup/sort/SortLookupStoreReader.java
paimon-common/src/test/java/org/apache/paimon/lookup/sort/SortLookupStoreFactoryTest.java

Linked issue: close #4131 
Support bloom filter in sort file store reader
Added test SortLookupStoreFactoryTest
no
no

[core] Support bloom filter in sort file store reader

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java

[spark] Add error message when sessionCatalog is null

---

docs/content/maintenance/dedicated-compaction.md
docs/content/maintenance/write-performance.md

[doc] fix the invalid link for async compaction

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala

AQE won't break the required distribution and ordering, so it is unnecessary to disable aqe manually.
Pass CI
no

[spark] Delete with deletion vectors should enable AQE

---

paimon-common/src/main/java/org/apache/paimon/compression/ZstdBlockCompressor.java

Add exception handing when source array is null and add exception info 
Existed tests
No
No

[common] Add exception handing in zstd compressor

---

docs/content/maintenance/manage-branches.md
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/BranchProcedureTest.scala

[spark] update branch UT and doc

---

docs/content/flink/procedures.md
docs/content/flink/sql-query.md
docs/content/learn-paimon/understand-files.md
docs/content/maintenance/dedicated-compaction.md
docs/content/maintenance/manage-branches.md
docs/content/maintenance/manage-snapshots.md
docs/content/maintenance/manage-tags.md
docs/content/migration/clone-tables.md
docs/content/migration/migration-from-hive.md

This pull request adds Procedure with named argument to documents
A local Hugo service had been started to verify the document display results manually
This PR does not affect API or Format.
This pull request adds Procedure with named argument to documents

[flink][docs] Add Procedure with named argument to documents

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/UnawareBucketCompactor.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendCompactWorkerOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendOnlyMultiTableCompactionWorkerOperator.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/compact/UnawareBucketCompactorTest.java

Add metrics for UnawareBucketCompactor.

[flink] Add metrics for unaware append table compaction thread

---

pom.xml

continuation after #3719
improve Reproducible Builds: see https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/paimon/README.md

drop non-reproducible Git-Branch

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java

follow up https://github.com/apache/paimon/pull/4158

[spark] Fix compact unreasonable log info

---

docs/content/spark/sql-write.md

[doc] fix the configuration error of primary key in table building

---

paimon-core/src/main/java/org/apache/paimon/schema/TableSchema.java

[core] fix typo in TableSchema.java

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/TableMigrationUtils.java

[doc] Fix spelling error of parameter name

---

docs/layouts/shortcodes/generated/mongodb_sync_database.html
docs/layouts/shortcodes/generated/mysql_sync_table.html
docs/layouts/shortcodes/generated/postgres_sync_table.html

[doc] fix cdc doc url 404

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactAction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactActionITCase.java

[doc] Fix CompactionAction doc misspelling

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregator.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldBoolAndAgg.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldBoolOrAgg.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldCollectAgg.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldIgnoreRetractAgg.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldLastNonNullValueAgg.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldLastValueAgg.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldListaggAgg.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldMaxAgg.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldMergeMapAgg.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldMinAgg.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldNestedUpdateAgg.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldPrimaryKeyAgg.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldProductAgg.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldSumAgg.java

Add serial version ID for aggr functions which implement serial interface
No
No
No

[core] Add serial version ID for aggr functions

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/shuffle/RangeShuffle.java

[doc] Fix comment syntax errors

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PrimaryKeyFileStoreTableITCase.java

This PR fixes unstable tests in `PrimaryKeyFileStoreTableITCase` by:
1. Increase write buffer size so not too many files are created during testing.
2. Set `continuous.discovery-interval` to a very small value. Because during testing, Paimon table will produce snapshots very quickly, so consumers of these snapshots should also discover new snapshots very quickly.
Existing test should cover this change.

[test] Fix unstable tests in PrimaryKeyFileStoreTableITCase

---

paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseTableListITCase.java

This PR fixes unstable tests in `MySqlSyncDatabaseTableListITCase` by ensuring the job steps into incremental phase when trying to capture new tables. Previous code does not ensure this.

[test] Fix unstable tests in MySqlSyncDatabaseTableListITCase

---

paimon-arrow/src/main/java/org/apache/paimon/arrow/ArrowBundleRecords.java
paimon-arrow/src/main/java/org/apache/paimon/arrow/reader/ArrowBatchReader.java
paimon-arrow/src/test/java/org/apache/paimon/arrow/vector/ArrowFormatWriterTest.java

Catalog API is allowUpperCase, keep consistent.

[hotfix] Change 'toLowerCase' to 'allowUpperCase'

---

paimon-core/src/main/java/org/apache/paimon/table/ExpireSnapshotsImpl.java
paimon-core/src/test/java/org/apache/paimon/operation/ExpireSnapshotsTest.java

[core] Check existence before expire: more check.

---

paimon-core/src/main/java/org/apache/paimon/table/FallbackReadFileStoreTable.java

[hotfix] Fix that cannot add new entry to partitionEntries

---

paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileMetaTest.java
paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileMetaTestBase.java

add more test cases for `ManifestFileMerger#tryFullCompaction`
org.apache.paimon.manifest.ManifestFileMetaTest

[test] add test cases for manifest file full compaction

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkRow.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonQueryTest.scala

- `WrappedArray` was removed in Scala 2.13, replaced it by `scala.collection.Seq`
- Optimize seq to list
- Add test case for https://github.com/apache/paimon/pull/1932

[spark] Add test case for writing nested array

---

docs/content/program-api/python-api.md

[doc] Add doc for creating table

---

paimon-core/src/main/java/org/apache/paimon/table/system/BucketsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/PartitionsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/TagsTable.java
paimon-core/src/test/java/org/apache/paimon/table/system/TagsTableTest.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonSystemTableTest.scala

Sort some system table query result, including tags/partitions/buckets tables.

[core] Sort some system table query result

---

docs/content/spark/sql-ddl.md
paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/sql/ShowTagsTest.scala
paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/ShowTagsTest.scala
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/ShowTagsTest.scala
paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/sql/ShowTagsTest.scala
paimon-spark/paimon-spark-common/src/main/antlr4/org.apache.spark.sql.catalyst.parser.extensions/PaimonSqlExtensions.g4
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/plans/logical/ShowTagsCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/execution/PaimonStrategy.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/execution/ShowTagsExec.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/PaimonSparkSqlExtensionsParser.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/PaimonSqlExtensionsAstBuilder.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonShowTagsTestBase.scala

Add show tags sql syntax like show partitions. 
```
show tags table_identifier
```

[spark] Add show tags sql syntax

---

paimon-service/paimon-service-client/src/main/java/org/apache/paimon/service/network/NetworkClient.java

Before, it use the pattern as bellow, which will lead the ConcurrentHashMap stuck in loop 
```
Map<String, String> test = new ConcurrentHashMap<>();
test.computeIfAbsent(
"a",
new Function<String, String>() {
@Override
public String apply(String s) {
return test.remove("a");
}
});
System.out.println(test);
```
The `KvQueryTableTest` will stuck in the thread as below

[core] Fix the KvQueryTableTest may stuck in loop

---

paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileMetaTest.java

fix unstable random test `ManifestMetaTest#testRandomFullCompaction`

[fix][test] fix unstable random test for manifest full compaction

---

paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkCatalogWithHiveTest.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkGenericCatalogWithHiveTest.java

[test] Add test for hive-conf-dir in Spark catalog.

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/DataTableSource.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/statistics/FileStoreTableStatisticsTestBase.java

Currently only rowCount statistics are provided. Providing more complete column statistics will help Flink generate a better plan.

[flink] Support Column Statistics for Flink

---

paimon-common/src/main/java/org/apache/paimon/io/cache/CacheManager.java
paimon-common/src/test/java/org/apache/paimon/io/cache/CacheManagerTest.java

Linked issue: close #4400 
Added test case CacheManagerTest
no
no

[core] Fix the dead loop issue in CacheManager

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/AbstractFlinkTableFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkTableFactory.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ReadWriteTableITCase.java

Linked issue: close #4372 
The change is verified by FlinkCatalogTest.
This change does not affect API or Format.
This change does not introduce a new feature.

[flink] fix false assumption on catalog table passing logic

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PrimaryKeyFileStoreTableITCase.java

[fix] fix error in FlinkSink for changelog files merge

[fix] fix error in FlinkSink for changelog files merge

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java

[hive] Pass 'partition.expiration-time' prop to hms.

---

paimon-common/src/main/java/org/apache/paimon/io/CompressedPageFileInput.java
paimon-common/src/main/java/org/apache/paimon/io/cache/CacheManager.java
paimon-common/src/main/java/org/apache/paimon/io/cache/FileBasedRandomInputView.java
paimon-common/src/main/java/org/apache/paimon/lookup/sort/BlockCache.java
paimon-common/src/main/java/org/apache/paimon/lookup/sort/SortLookupStoreReader.java
paimon-common/src/test/java/org/apache/paimon/lookup/sort/SortLookupStoreFactoryTest.java

[core] Introduce BlockCache for SortLookupStoreReader

---

paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

[core] Support rename view

---

docs/content/flink/clone-tables.md

fix doc style

---

docs/content/concepts/spec/snapshot.md

Update `logOffsets` in snapshot.md 
Linked issue: **no**
**no**
**no**
Don't add any new feature, update `docs/content/concepts/spec/snapshot.md`.

[doc] Update logOffsets in snapshot.md

---

docs/content/program-api/python-api.md

doc for https://github.com/apache/paimon-python/pull/22

[doc] Add python sdk predicate doc

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java

[core] Refactor AbstractCatalog to make metastoreClientFactory public

---

paimon-core/src/main/java/org/apache/paimon/operation/MergeFileSplitRead.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadITCase.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonQueryTest.scala

Fix read nested column with pk table

[core][spark] Fix read nested column with pk table

---

paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalog.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java

[Core] remove duplicated schema names in list schema in JDBC catalog

---

docs/content/program-api/python-api.md

[doc] fix typo error in python-api.md

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaMergingUtils.java
paimon-core/src/test/java/org/apache/paimon/schema/SchemaMergingUtilsTest.java

[core] Fix merge schemas equal method issue

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveTableUtils.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

HiveCatalog.listViews method reduces the number of queries for hms metadata.

[hive] HiveCatalog.listViews method reduces the number of queries for hms metadata.

---

docs/content/flink/procedures.md
docs/content/maintenance/manage-snapshots.md

fix flink procedure sql syntax error.

[doc] fix flink procedure document sql syntax error.

---

docs/content/primary-key-table/merge-engine/aggregation.md

Update hll_sketch and theta_sketch example in aggregation.md
Don't add any new feature

[doc] Update hll_sketch and theta_sketch example in aggregation.md

---

paimon-core/src/main/java/org/apache/paimon/table/system/PartitionsTable.java
paimon-core/src/test/java/org/apache/paimon/table/system/PartitionsTableTest.java

partition system table support time travel

[core]partition system table support time travel

---

docs/content/primary-key-table/merge-engine/partial-update.md
docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunctionTest.java
paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java

Support deleting rows in partial update of specific sequence group
PartialUpdateMergeFunctionTest#testSequenceGroupPartialDelete
PrimaryKeyFileStoreTableTest#testPartialUpdateRemoveRecordOnSequenceGroup

[Feature] Support deleting rows in partial update of specific sequence group

---

docs/content/maintenance/system-tables.md

[doc] Add the query binlog example in doc

---

paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTestBase.scala

Sync db owner prop to hms when creating the db

[hive] Sync db owner prop to hms when creating the db

---

paimon-core/src/test/java/org/apache/paimon/catalog/FileSystemCatalogTest.java

fix error comments in FileSystemCatalogTest

[comments] fix error comments in FileSystemCatalogTest

---

paimon-core/src/main/java/org/apache/paimon/table/source/DataTableStreamScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/DimScanOverwriteException.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupDataTableScan.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/ReopenException.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java

[flink] Fix that dim table cannot refresh overwrite changes

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CompactorSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CompactorSinkBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCompactOperator.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CompactorSinkITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/StoreCompactOperatorTest.java

Linked issue:  https://github.com/apache/paimon/issues/4566

[flink] Refactor compactorSink to support extended compact type.

---

pom.xml

to solve problem that fail to publish snapshot.

[spark] define spark properties globally

---

docs/content/concepts/table-types.md
docs/content/engines/doris.md
docs/content/engines/starrocks.md
docs/content/primary-key-table/overview.md

Fix the link url in the documentation.
**docs/content/concepts/table-types.md
docs/content/engines/doris.md
docs/content/engines/starrocks.md
docs/content/primary-key-table/overview.md**

[doc] fix url links in documentation

---

paimon-flink/paimon-flink-1.15/src/main/java/org/apache/flink/api/connector/sink2/WriterInitContext.java
paimon-flink/paimon-flink-1.15/src/main/java/org/apache/flink/streaming/api/functions/sink/v2/DiscardingSink.java
paimon-flink/paimon-flink-1.16/src/main/java/org/apache/flink/api/connector/sink2/WriterInitContext.java
paimon-flink/paimon-flink-1.16/src/main/java/org/apache/flink/streaming/api/functions/sink/v2/DiscardingSink.java
paimon-flink/paimon-flink-1.17/src/main/java/org/apache/flink/api/connector/sink2/WriterInitContext.java
paimon-flink/paimon-flink-1.17/src/main/java/org/apache/flink/streaming/api/functions/sink/v2/DiscardingSink.java
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/flink/api/connector/sink2/WriterInitContext.java
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/flink/streaming/api/functions/sink/v2/DiscardingSink.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSink.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSinkTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CloneAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/service/QueryAddressRegister.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/service/QueryService.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CombinedTableCompactorSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/WriterChainingStrategyTest.java

Linked issue: #4442
This PR replaces deprecated SinkFunction with v2 Sink

[flink] Replace legacy SinkFunction with v2 Sink

---

docs/content/flink/sql-alter.md
docs/content/spark/sql-alter.md

This PR adds document for nested column evolution in Flink and Spark.

[docs] Add document for nested column evolution

---

docs/content/program-api/python-api.md

[doc] Update Python API for pypaimon 0.2

---

docs/content/migration/iceberg-compatibility.md
paimon-core/src/main/java/org/apache/paimon/iceberg/AbstractIcebergCommitCallback.java
paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergOptions.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/iceberg/IcebergHiveMetadataCommitter.java
paimon-hive/paimon-hive-connector-2.3/src/test/java/org/apache/paimon/iceberg/IcebergHive23MetadataCommitterITCase.java
paimon-hive/paimon-hive-connector-3.1/src/test/java/org/apache/paimon/iceberg/IcebergHive31MetadataCommitterITCase.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/iceberg/IcebergHiveMetadataCommitterITCaseBase.java

1. Introduce `metadata.iceberg.hive-client-class` to configure Glue Hive client.
2. New Database should have correct location.

[iceberg] Introduce integration for AWS Glue

---

docs/content/flink/sql-ddl.md
docs/content/flink/sql-write.md
docs/content/spark/sql-ddl.md

Fixed url positioning in documents.

[doc] fix url positioning in documents

---

docs/content/program-api/python-api.md

[doc] Minor refactor Python API doc

---

docs/content/spark/sql-write.md
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/InsertOverwriteTableTestBase.scala

Add insert with column list test case

[test][spark] Add insert with column list test case

---

paimon-common/src/main/java/org/apache/paimon/utils/InternalRowPartitionComputer.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
paimon-core/src/main/java/org/apache/paimon/partition/PartitionPredicate.java

If we expire too many partitions, there may be a stack overflow exception in `FileStoreCommitImpl.dropPartitions`. This is because there are so many partitions in the construction for predicate.
We can optimize it by using `PartitionPredicate.fromMultiple`, if all inputs are full partition fields.

[core] Optimize drop partitions to avoid stack overflow

---

docs/content/migration/iceberg-compatibility.md

[docs] add glue metastore repo

---

paimon-core/src/main/java/org/apache/paimon/disk/FileChannelManagerImpl.java

Paimon may spill data to the local temporary directory, but the disk where the temporary directory is located may become damaged during running (marked as read-only or otherwise), which can cause tasks to fail due to unsuccessful spills, when restarting, failure may still occur due to the bad disk.
In actual production, jobs are often configured with multiple temporary directories, so as long as the number of available cache directories for Paimon is greater than 0, it is acceptable even if the disks of some directories are unavailable.
This PR changes the behavior of `FileChannelManagerImpl` to log a warning instead of throwing an exception directly when encountering a bad disk, which improves the fault tolerance of the job.
@JingsongLi Could you please take a look? Thanks.
No
No

[core]: Improve fault tolerance for data spill to disk

---

docs/content/flink/sql-write.md

I fixed the links in flink **sql-write** document.
**docs/content/flink/sql-write.md**

[doc] updated url links in documentation

---

docs/content/flink/procedures.md
docs/content/spark/procedures.md
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/PurgeFilesProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/PurgeFilesProcedure.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/PurgeFilesProcedureITCase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/PurgeFilesProcedure.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/PurgeFilesProcedureTest.scala

follow up: https://github.com/apache/paimon/pull/4706  
after discussion, change sql method to procedure to implement purge files for table.

[core] Introduce PurgeFilesProcedure to purge table

---

pom.xml

[dependency] Upgrade paimon shade version

---

tools/releasing/deploy_staging_jars.sh

[hotfix] Add spark3 profile in deploy_staging_jars

---

docs/content/primary-key-table/merge-engine/partial-update.md

[hotfix] Fix invalid link in Partial Update doc

---

paimon-spark/paimon-spark-3.5/pom.xml
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonFunctionTest.scala
pom.xml

https://spark.apache.org/news/spark-3-5-4-released.html
(Dec 20, 2024)

[spark] Bump Spark 3.5.4

---

paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedureTest.scala

[spark] Remove unreasonable test output

---

NOTICE

Happy New Year 2025!
I changed the contents of the **NOTICE** file.

[doc] Add 2025 on NOTICE

---

paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalTagStartingScanner.java
paimon-core/src/test/java/org/apache/paimon/table/IncrementalTableTest.java

[core] Fix that incremental-to-auto-tag return wrong result if snapshots are expired

---

paimon-e2e-tests/pom.xml
pom.xml

Upgrade the  test-flink-sql-connector-kafka version.

[e2e] upgrade the test-flink-sql-connector-kafka version

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CombinedTableCompactorSink.java

Fix  some typos of method names in code.

[hotfix] fix some typos

---

paimon-core/src/test/java/org/apache/paimon/io/DataFilePathFactoryTest.java

Nit clean up the test code
No
No

[core] Remove unnecessary toString call

---

docs/content/program-api/python-api.md

[doc] Pypaimon api table_scan plan splits.

---

paimon-core/src/main/java/org/apache/paimon/table/source/AbstractDataTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalTagStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalTimeStampStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/TimeTravelUtil.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java

[core] Throw exception if increment query with rescale bucket

---

paimon-arrow/src/main/java/org/apache/paimon/arrow/converter/ArrowVectorizedBatchConverter.java
paimon-common/src/main/java/org/apache/paimon/data/columnar/ColumnarRowIterator.java
paimon-common/src/main/java/org/apache/paimon/data/columnar/VectorizedRowIterator.java
paimon-common/src/test/java/org/apache/paimon/data/columnar/ColumnarRowIteratorTest.java
paimon-common/src/test/java/org/apache/paimon/data/columnar/heap/RowColumnVectorTest.java

Using LongIterator instead of long[].

[core] Refactory ColumnarRowIterator using LongIterator.

---

docs/layouts/shortcodes/generated/mongodb_sync_database.html
docs/layouts/shortcodes/generated/mongodb_sync_table.html
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableActionFactory.java

Update url for postgres cdc and mongodb cdc.

[doc] Update url for postgres cdc and mongodb cdc

---

paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeInto.scala
paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeInto.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeInto.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeIntoBase.scala

[minor] remove the unused buildMergeIntoPaimonTable

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/aliyun/AliyunRecordParser.java

Just the same as the title suggestd literally.

[flink-action] Correct the isDdl field for aliyun-json cdc format.

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CloneActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactDatabaseActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CreateBranchActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CreateTagActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CreateTagFromTimestampActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CreateTagFromWatermarkActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DeleteActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DeleteBranchActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DeleteTagActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DropPartitionActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpirePartitionsActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpireSnapshotsActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpireTagsActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/FastForwardActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MarkPartitionDoneActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MergeIntoActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MigrateDatabaseActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MigrateFileActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MigrateTableActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/QueryServiceActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RemoveUnexistingFilesActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RenameTagActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RepairActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ReplaceTagActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ResetConsumerActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RewriteFileIndexActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RollbackToActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RollbackToTimestampActionFactory.java

[feature] [action] Adding line breaks to action prompts

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/postgres/PostgresSyncTableActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarSyncDatabaseActionFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarSyncTableActionFactory.java

[feature] [cdc] Add line breaks to improve readability

---

docs/content/concepts/data-types.md

Linked issue: close #5052 
fix docs

[docs] change TIMESTAMP(p) WITH TIME ZONE to TIMESTAMP(p) WITH LOCAL TIME ZONE in data-types

---

paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

Improve the HiveCatalogITCaseBase class to reduce the number of hive queries.

[hotfix] Improve the HiveCatalogITCaseBase class to reduce the number of hive queries

---

docs/content/maintenance/dedicated-compaction.md
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedureTest.scala

Fix some typos for document and test case.

[hotfix] [doc] Fix some typos

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FormatCatalogTable.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveTableUtils.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogFormatTableITCaseBase.java

hive create format table support query field comments.
HiveCatalogFormatTableITCaseBase

[hive] hive create format table support query field comments.

---

docs/content/maintenance/manage-branches.md

Paimon can not create a branch from a specific snapshot in fact.

[doc] fix doc error which saying create branch from a specific snapshot

---

docs/content/flink/consumer-id.md

Add missing document for Clearing Consumers in consumer-id.md

[doc]Add missing document for Clearing Consumers in consumer-id.md

---

docs/content/flink/procedures.md
docs/content/spark/procedures.md
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/MigrateDatabaseProcedure.java

[docs] Add missing document for `migrate` related procedures

[docs] Add missing document for `migrate` related procedures

---

paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/TableWriterBenchmark.java

[hotfix] remove the unrelated change in benchmark

---

docs/content/spark/sql-query.md
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonQueryTest.scala

Add `__paimon_row_index` metadata column

[doc][spark] Add `__paimon_row_index` metadata column

---

docs/content/primary-key-table/query-performance.md

[doc] Fix typo of deletion vectors

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveTableUtils.java

```
Caused by: java.lang.NullPointerException
at org.apache.paimon.hive.HiveTableUtils.tryToFormatSchema(HiveTableUtils.java:66)
at org.apache.paimon.hive.HiveCatalog.isFormatTable(HiveCatalog.java:1299)
at org.apache.paimon.hive.HiveCatalog.listTablesImpl(HiveCatalog.java:684)
at org.apache.paimon.catalog.AbstractCatalog.listTables(AbstractCatalog.java:240)
at org.apache.paimon.catalog.CatalogUtils.createGlobalSystemTable(CatalogUtils.java:216)
at org.apache.paimon.catalog.CatalogUtils.loadTable(CatalogUtils.java:181)
```

[core] Fix the potential NPE in HiveTableUtils

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/CompactorSourceBuilder.java

In my company, user run a dedicated compactor job, but JobManager's memory is heavy.
Now add dropStats in dedicated compactor jobs.

[Flink] dropStats in dedicated compactor jobs

---

paimon-common/src/main/java/org/apache/paimon/CoreOptions.java

NestedupdateAgg key fieldName maybe shuld be trimed
Linked issue: close #5141

[core] NestedupdateAgg key fieldName maybe shuld be trimed

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunctionTest.java
paimon-core/src/test/java/org/apache/paimon/table/PartialUpdateTableTest.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/writer/ParquetRowDataWriter.java

[core] [fix] Partial update should not return empty row with non-null column type exist

---

paimon-common/src/main/java/org/apache/paimon/utils/ReflectionUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedSourceReader.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/align/AlignedSourceReaderTest.java

[flink] fix the issue where AlignedSourceReader might hang, and add detailed comments.
- `org.apache.paimon.flink.source.align.AlignedSourceReaderTest#testCheckpointTrigger`
No.
No.

 [flink] fix the issue where AlignedSourceReader might hang, and add detailed comments.

---

docs/content/cdc-ingestion/mysql-cdc.md
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/resources/mysql/sync_table_setup.sql

Add mysql cdc synchronization table comment document.
MySqlSyncTableActionITCase#testSchemaEvolutionWithComment

[doc] Add mysql cdc synchronization table comment document.

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/align/AlignedSourceReaderTest.java

Linked issue: close #5155
[hotfix] fix the unreliability test of AlignedSourceReaderTest#testCheckpointTrigger.

[hotfix] fix the unreliability test of AlignedSourceReaderTest#testCheckpointTrigger.

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-common/src/main/java/org/apache/paimon/utils/MathUtils.java
paimon-core/src/main/java/org/apache/paimon/compact/CompactManager.java
paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeWriter.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ForceUpLevel0Compaction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactManager.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/UniversalCompaction.java
paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/utils/RecordWriter.java
paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTestBase.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/MergeTreeCompactManagerTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/UniversalCompactionTest.java
paimon-core/src/test/java/org/apache/paimon/operation/KeyValueFileStoreWriteTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/WriterOperatorTest.java

Linked issue: close #4917 
MergeTreeCompactManagerTest.testIsCompacting
KeyValueFileStoreWriteTest.testRadicalLookupCompactStrategy
KeyValueFileStoreWriteTest.testGentleLookupCompactStrategy
WriterOperatorTest.testGentleLookupWithFailure

[core] Introduce gentle lookup compaction mode to reduce overall compaction frequency

---

.gitignore

[hotfix] ignore .vscode folder in .gitignore

[hotfix] ignore .vscode folder in .gitignore

---

docs/content/primary-key-table/compaction.md

Add lookup compaction description in primary key compaction page

[doc] Add lookup compaction description in primary key compaction page

---

docs/content/migration/upgrade-compatibility.md

Introduce Paimon upgrade compatibility description page

[doc] Introduce Paimon upgrade compatibility description page

---

docs/content/engines/starrocks.md
docs/layouts/shortcodes/center.html
docs/layouts/shortcodes/gh_link.html
docs/layouts/shortcodes/github_repo.html
docs/layouts/shortcodes/presto_github_repo.html
docs/layouts/shortcodes/trino_github_repo.html
paimon-core/src/main/java/org/apache/paimon/migrate/FileMetaUtils.java

[hotfix] Fix some typos in documents and code

---

paimon-core/src/main/java/org/apache/paimon/table/source/splitread/IncrementalDiffSplitRead.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/TableValuedFunctionsTest.scala

[core] Fix incremental query audit log table with delete

---

docs/content/concepts/spec/schema.md
docs/content/engines/trino.md
docs/content/flink/action-jars.md
docs/content/flink/sql-alter.md
docs/content/maintenance/filesystems.md
docs/content/maintenance/write-performance.md
docs/content/spark/quick-start.md
docs/content/spark/sql-functions.md
paimon-e2e-tests/README.md

[doc] Fix documents format

---

paimon-core/src/main/java/org/apache/paimon/catalog/SupportsSnapshots.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/GetTableSnapshotResponse.java
paimon-core/src/main/java/org/apache/paimon/table/TableSnapshot.java
paimon-core/src/main/java/org/apache/paimon/tag/SnapshotLoaderImpl.java
paimon-core/src/test/java/org/apache/paimon/rest/MockRESTCatalogTest.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTestBase.java
paimon-open-api/rest-catalog-open-api.yaml

Commit Snapshot with statistics, get snapshot should also contain basic statistics too.

[rest] Add TableSnapshot including basic statistics to SupportsSnapshots

---

paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/ResourcePaths.java
paimon-core/src/main/java/org/apache/paimon/rest/requests/CommitTableRequest.java
paimon-core/src/main/java/org/apache/paimon/rest/requests/ForwardBranchRequest.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-open-api/rest-catalog-open-api.yaml
paimon-open-api/src/main/java/org/apache/paimon/open/api/RESTCatalogController.java

[rest] Make paths in REST less conflicts

---

docs/content/flink/procedures.md
docs/content/spark/procedures.md

Fix the name of parameter for procedures documents.

[docs] [procedures] Fix the name of parameter for procedures

---

docs/content/program-api/flink-api.md

Refine imports in example code.
NA
NA
NA

[docs] refine flink-api doc example code

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/ListDatabasesResponse.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTestBase.java
paimon-open-api/rest-catalog-open-api.yaml
paimon-open-api/src/main/java/org/apache/paimon/open/api/RESTCatalogController.java

[core] RestCatalog: support ListDatabasesPaged and optimize mock server
RESTCatalogTestBase.testListDatabases
RESTCatalogTestBase.testListDatabasesPaged and other original cases

[core] RestCatalog: support ListDatabasesPaged

---

paimon-core/src/main/java/org/apache/paimon/table/source/splitread/IncrementalDiffSplitRead.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/TableValuedFunctionsTest.scala

[core][followup] Fix incremental query audit log table with delete

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/aliyun/AliyunRecordParser.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTypeUtils.java

[cdc] AliyunRecordParser supports to extract types

---

.github/workflows/utitcase-spark-4.x.yml
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/PaimonHiveTestBase.scala

[test] Temporarily set client-pool-size to 1 in Spark PaimonHiveTestBase

---

paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/HiveCatalogTest.java

Fix unstable test HiveCatalogTest#testAlterPartitions.
https://github.com/apache/paimon/actions/runs/13920930734/job/38953805599#step:4:10381

[hotfix] Fix unstable test HiveCatalogTest#testAlterPartitions.

---

paimon-open-api/rest-catalog-open-api.yaml

add catalog api into rest catalog open api yaml 
CreateCatalog
ListCatalogs
AlterCatalog
DropCatalog
rest-catalog-open-api.yaml

[core] RestCatalog: add catalog api into rest open api yaml

---

paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/test/java/org/apache/paimon/rest/MockRESTMessage.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTObjectMapperTest.java
paimon-open-api/rest-catalog-open-api.yaml
paimon-open-api/src/main/java/org/apache/paimon/open/api/RESTCatalogController.java

[rest] Remove useless CreateDatabaseResponse

---

paimon-core/src/main/java/org/apache/paimon/stats/SimpleStatsEvolution.java
paimon-core/src/main/java/org/apache/paimon/table/source/DataSplit.java
paimon-core/src/test/java/org/apache/paimon/table/source/SplitTest.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScanBuilder.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/aggregate/AggFuncEvaluator.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/aggregate/AggregatePushDownUtils.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/aggregate/LocalAggregator.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PushDownAggregatesTest.scala

[spark] support to push down min/max aggregation

---

paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/AuditRESTResponse.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/BaseResourceAuditResponse.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/GetDatabaseResponse.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/GetTableResponse.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/GetViewResponse.java
paimon-core/src/test/java/org/apache/paimon/rest/MockRESTMessage.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTObjectMapperTest.java
paimon-open-api/rest-catalog-open-api.yaml
paimon-open-api/src/main/java/org/apache/paimon/open/api/RESTCatalogController.java

Expose more information to REST client:
1. path information.
2. owner, updateBy, createBy...

[rest] Add path and other options to Table Options

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/CatalogSnapshotCommit.java
paimon-core/src/main/java/org/apache/paimon/catalog/CatalogUtils.java
paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/CatalogEnvironment.java
paimon-core/src/main/java/org/apache/paimon/utils/CatalogBranchManager.java
paimon-core/src/test/java/org/apache/paimon/operation/PartitionExpireTest.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java

Avoid using catching UnsupportedException in codes.

[core] Add supportsVersionManagement to Catalog

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/WriteIntoPaimonTable.scala

[spark] Deduplicate partitions for markDone

---

paimon-open-api/rest-management-api.yaml

add getCatalogById in rest open api yaml 
rest-management-api.yaml

[core] RestCatalog: add getCatalogById in rest yaml

---

paimon-core/src/main/java/org/apache/paimon/migrate/FileMetaUtils.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/migrate/HiveMigrator.java

Reduce get partition requests in migrating hive table

[core] Reduce get partition requests in migrating hive table

---

paimon-open-api/rest-management-api.yaml

add catalog status in getCatalogResponse
rest-management-api.yaml

[core] RestCatalog: add status in GetCatalogResponse

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpireChangelogsAction.java

rename some arguments for avoiding ambiguity.

[flink][action] rename some arguments for avoiding ambiguity

---

docs/layouts/_default/baseof.html

[doc] fix rest api page js conflict

---

paimon-common/src/main/java/org/apache/paimon/utils/TypeUtils.java
paimon-common/src/test/java/org/apache/paimon/utils/TypeUtilsTest.java

[Bug] Improve float precision handling in TypeUtils.

---

paimon-core/src/main/java/org/apache/paimon/table/FileStoreTableFactory.java

There is no need to force an exception if call back branch is not exist.

Do not throw exception of fall back branch is not exist.

---

docs/layouts/_default/baseof.html

fix rest api doc charset and tab's icon and title

[core] fix rest api doc charset and tab's icon and title

---

docs/content/flink/procedures.md
docs/content/spark/procedures.md
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BranchSqlITCase.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/BranchProcedureTest.scala

[test] Add test and doc for create_branch from another branch.

---

paimon-flink/paimon-flink-1.15/pom.xml
paimon-flink/paimon-flink-1.19/pom.xml
paimon-flink/paimon-flink-1.20/pom.xml

Flink 1.15.4 Release Notes: https://flink.apache.org/2023/03/15/apache-flink-1.15.4-release-announcement/
Flink 1.19.2 Release Notes: https://flink.apache.org/2025/02/12/apache-flink-1.19.2-release-announcement/
Flink 1.20.1 Release Notes: https://flink.apache.org/2025/02/12/apache-flink-1.20.1-release-announcement/

[flink] Bump flink 1.15.3->1.15.4 & 1.19.1->1.19.2 & 1.20.0->1.20.1

---

paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVector.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVectorsIndexFile.java

[core] Fix typos in DeletionVector

---

paimon-core/src/main/java/org/apache/paimon/rest/auth/DLFAuthProviderFactory.java
paimon-core/src/test/java/org/apache/paimon/rest/auth/DLFAuthProviderFactoryTest.java

update parse region from dlf endpoint
org.apache.paimon.rest.auth.DLFAuthProviderFactoryTest#getRegion

[core] RESTCatalog: update parse region from dlf endpoint

---

paimon-flink/paimon-flink-cdc/pom.xml
paimon-flink/paimon-flink-common/pom.xml
pom.xml

[flink] Bump flink version to 1.20.1

---

paimon-core/src/main/java/org/apache/paimon/mergetree/SortedRun.java
paimon-core/src/main/java/org/apache/paimon/table/source/DataTableStreamScan.java
paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeySimpleTableTest.java

close https://github.com/apache/paimon/issues/4265
Fix https://github.com/apache/paimon/pull/4301

[core] Fix FileMonitorTable with Deletion Vectors Enabled

---

docs/content/primary-key-table/compaction.md

[docs] add some explanations about record-level expire

---

paimon-common/src/main/java/org/apache/paimon/types/FieldIdentifier.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/MultiTableUpdatedDataFieldsProcessFunction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunctionBase.java

[cdc] Fix database sync performance issue of schema evolution

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/SupportsRowLevelOperationFlinkTableSink.java

[flink] Flink batch delete supports aggregation.remove-record-on-delete option

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/MergeFunctionTestUtils.java

[hotfix] Fix test WithPartialUpdateMergeFunctionTest

---

paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

`sync-all-properties` is true instead of false, tests should be also changed.

[hive] Fix `sync-all-properties` related tests

---

docs/content/primary-key-table/data-distribution.md
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveWriteITCase.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/SparkWriteITCase.scala

[spark][hive] Spark & Hive support writing to postpone bucket

---

paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java

fix reduandant assert in CatalogTestBase

[test] remove root cause message check in CatalogTestBase.testCreateTable

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/io/FileWriterContext.java
paimon-core/src/main/java/org/apache/paimon/io/KeyValueDataFileWriter.java
paimon-core/src/main/java/org/apache/paimon/io/KeyValueDataFileWriterImpl.java
paimon-core/src/main/java/org/apache/paimon/io/KeyValueFileWriterFactory.java
paimon-core/src/main/java/org/apache/paimon/io/KeyValueThinDataFileWriterImpl.java
paimon-core/src/main/java/org/apache/paimon/io/RowDataFileWriter.java
paimon-core/src/main/java/org/apache/paimon/io/RowDataRollingFileWriter.java
paimon-core/src/main/java/org/apache/paimon/io/StatsCollectingSingleFileWriter.java
paimon-core/src/main/java/org/apache/paimon/utils/FileStorePathFactory.java
paimon-core/src/test/java/org/apache/paimon/io/KeyValueFileReadWriteTest.java
paimon-core/src/test/java/org/apache/paimon/io/RollingFileWriterTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/ChangelogMergeTreeRewriterTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/ContainsLevelsTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/LookupLevelsTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTestBase.java
paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeySimpleTableTest.java

Introduce `changelog-file.format` and `changelog-file.compression` and `changelog-file.stats-mode`.

[core] Introduce specific options for changelog files

---

docs/content/cdc-ingestion/overview.md

[doc] Refactor CDC type mapping doc and add missing options

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java

This PR extracts the schema generation logic from the `commitChanges` function into a reusable `generateTableSchema` function. This improves code modularity, reusability, and testability while decoupling schema construction from the `commitChanges` workflow.

[core] extract generateTableSchema method to decouple schema generation logic

---

docs/content/flink/sql-alter.md
docs/content/spark/sql-alter.md

remove adding partitions in flink/sql-alter and spark/sql-alter doc

[doc] remove adding partitions in sql-alter doc

---

docs/content/maintenance/filesystems.md

fix docs in filesystem.md
1.add azure to Supported FileSystems table
2.delete duplicate conetent of Microsoft Azure Storage

[docs]fix docs in filesystem.md

---

docs/content/migration/clone-from-hive.md

Fix clone hive database doc in clone-from-hive.md

[doc] fix clone hive database doc

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/hive/ListHiveFilesFunction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/clone/hive/ListHiveFilesFunctionTest.java

[hotfix] Rename CloneHiveUtilsTest to ListHiveFilesFunctionTest

---

paimon-core/src/test/java/org/apache/paimon/schema/SchemaManagerTest.java

Refactor SchemaManagerTest to use parameterized tests for move operations

[test] Refactor SchemaManagerTest to use parameterized tests for move operations

---

paimon-core/src/main/java/org/apache/paimon/migrate/FileMetaUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/hive/CopyHiveFilesFunction.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/migrate/HiveCloneUtils.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/migrate/HiveMigrator.java

[refactor] Extract some common codes of clone hive and migrate hive

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CloneHiveAction.java

[hive][clone] check whether source catalog is HiveCatalog

---

docs/content/spark/sql-write.md

alter grammar of streaming write to paimon table in spark sql-write doc

[doc] alter streaming write to paimon table grammar

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/hive/CopyProcessFunction.java

[hive][clone] implement two open function for flink 1.18- and 2.0+

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-connector-2.3/src/test/java/org/apache/paimon/hive/Hive23CatalogFormatTableITCase.java
paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/sql/FormatTableTest.scala
paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/FormatTableTest.scala
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/FormatTableTest.scala
paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/sql/FormatTableTest.scala
paimon-spark/paimon-spark-4.0/src/test/scala/org/apache/paimon/spark/sql/FormatTableTest.scala
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/execution/PaimonFormatTable.scala
paimon-spark/paimon-spark-ut/src/test/java/org/apache/paimon/spark/SparkCatalogWithHiveTest.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/FormatTableTestBase.scala

[spark] Support partitioned format table

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactDatabaseActionITCase.java

CompactDatabaseActionITCase#testCombinedModeWithDynamicOptions fails frequently

[test] Fix unstable CompactDatabaseActionITCase#testCombinedModeWithDynamicOptions

---

paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/orphan/FlinkOrphanFilesClean.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionITCaseBase.java

We should also clean empty directories in OrphanFilesClean, it already list directories.

[flink] Clean empty directory in FlinkOrphanFilesClean

---

paimon-core/src/main/java/org/apache/paimon/rest/RESTUtil.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTUtilTest.java

[core] RESTCatalog: fix npe when merge conf
- RESTUtilTest.testMerge
NO

[core] RESTCatalog: fix npe when merge conf

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RollbackToProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RollbackToTimestampProcedure.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/RollbackProcedureITCase.java
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/RollbackProcedureTest.scala
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RollbackProcedure.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RollbackToTimestampProcedure.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RollbackToWatermarkProcedure.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/RollbackProcedureTest.scala

Linked issue:  https://github.com/apache/paimon/issues/5511. 
Enhance rollback procedure result.
```text
+--------------------+-------------------+
|previous_snapshot_id|current_snapshot_id|
+--------------------+-------------------+
|3                   |2                  |
+--------------------+-------------------+
```

[procedure] Enhance return result for rollback procedure

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/ListCloneFilesFunction.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/migrate/HiveCloneUtils.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/procedure/CloneActionITCase.java

clone hive : support create database if not exists
org.apache.paimon.hive.procedure.CloneActionITCase#testCloneWithNotExistedDatabase

[hive][clone] support create database if not exists

---

paimon-core/src/main/java/org/apache/paimon/utils/CompressUtils.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogFormatTableITCaseBase.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/FormatTableTestBase.scala

[test] Add compress files tests for format table

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/SystemCatalogTable.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java

[flink] audit_log table supports computed column

---

paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java

Linked issue: close #5485
Identify the "Permission.NotAllow" error returned by HMS
N/A
N/A
N/A

[core] Resolve hms Permission.NotAllow error

---

paimon-core/src/main/java/org/apache/paimon/disk/IOManagerImpl.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonPartitionReader.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonPartitionReaderFactory.scala

[spark] Close ioManager in PaimonPartitionReader

---

docs/layouts/shortcodes/generated/core_configuration.html
docs/static/rest-catalog-open-api.yaml
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/Bitmap64DeletionVector.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/BitmapDeletionVector.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVector.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVectorIndexFileWriter.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVectorsIndexFile.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVectorsMaintainer.java
paimon-core/src/main/java/org/apache/paimon/index/DeletionVectorMeta.java
paimon-core/src/test/java/org/apache/paimon/deletionvectors/DeletionVectorTest.java
paimon-core/src/test/java/org/apache/paimon/deletionvectors/DeletionVectorsIndexFileTest.java
paimon-core/src/test/java/org/apache/paimon/deletionvectors/DeletionVectorsMaintainerTest.java
paimon-core/src/test/java/org/apache/paimon/deletionvectors/append/AppendDeletionFileMaintainerTest.java
paimon-core/src/test/java/org/apache/paimon/operation/FileStoreCommitTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/DeletionVectorITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PrimaryKeyFileStoreTableITCase.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/SparkDeletionVector.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/UpdatePaimonTableCommand.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DeletionVectorTest.scala

[core] Rename 'deletion-vectors.version' to 'deletion-vectors.bitmap64'

---

docs/layouts/shortcodes/generated/spark_connector_configuration.html
paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/catalyst/analysis/expressions/ExpressionHelper.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/expressions/ExpressionHelper.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/write/PaimonV2Write.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/write/PaimonV2WriteBuilder.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/write/PaimonWrite.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/write/PaimonWriteBuilder.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/write/PaimonWriteRequirement.scala

[spark] Minor refactor for spark v2 writer

---

paimon-core/src/test/java/org/apache/paimon/deletionvectors/DeletionVectorsIndexFileTest.java
paimon-core/src/test/java/org/apache/paimon/deletionvectors/DeletionVectorsMaintainerTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/DeletionVectorITCase.java

add some tests for mixed usage of two kinds of dv

[test] add tests for mixed usage of dv

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/RefreshBlacklist.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java

[flink] Fix that NewLookupFunction is not serializable because of RefreshBlacklist

---

docs/layouts/partials/docs/inject/footer.html
paimon-codegen/src/main/resources/META-INF/NOTICE
paimon-common/src/main/resources/META-INF/NOTICE
paimon-core/src/main/resources/META-INF/NOTICE
paimon-filesystems/paimon-azure-impl/src/main/resources/META-INF/NOTICE
paimon-filesystems/paimon-cosn-impl/src/main/resources/META-INF/NOTICE
paimon-filesystems/paimon-hadoop-shaded/src/main/resources/META-INF/NOTICE
paimon-filesystems/paimon-obs-impl/src/main/resources/META-INF/NOTICE
paimon-filesystems/paimon-oss-impl/src/main/resources/META-INF/NOTICE
paimon-filesystems/paimon-s3-impl/src/main/resources/META-INF/NOTICE
paimon-format/src/main/resources/META-INF/NOTICE

Update copyright to 2025, currently still is 2024

[notice] Update copyright to 2025

---

paimon-core/src/main/java/org/apache/paimon/table/system/FilesTable.java
paimon-core/src/test/java/org/apache/paimon/table/system/FilesTableTest.java

[core] Add deleteRowCount to FilesTable

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java

Add test for to table fallback when: main branch is append table and fallback branch is pk table
- CatalogTableITCase.testReadOptimizedTableFallBack

[hotfix] add test for ro fallback

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeTreeCompactRewriter.java
paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeySimpleTableTest.java

If level 0 is configured as avro, upgrading to higher levels will still be avro, which has an impact on query performance. We should force rewriting in this scenario.

[core] Forcing rewrite when upgrading level0 in different formats for lookup

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/MonitorSource.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/AppendOnlyTableITCase.java

Fixed error words from unware to unaware.

[hotfix] Fixed error words from unware to unaware.

---

paimon-api/src/main/java/org/apache/paimon/PagedList.java
paimon-api/src/main/java/org/apache/paimon/rest/RESTApi.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java

[core] Add documention in RESTApi class

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/PaimonHiveTestBase.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTestBase.scala

[hive] Sync unset table props with hms

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-api/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/source/DataTableStreamScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/FollowUpScanner.java
paimon-core/src/main/java/org/apache/paimon/table/system/ReadOptimizedTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupDataTableScan.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupFileStoreTable.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/AppendOnlyTableITCase.java

[flink] Support to stream read overwrite commit for append table

---

docs/content/flink/quick-start.md

Update the doc/content/flink/quick-start.md

---

docs/layouts/shortcodes/generated/other_functions.html
paimon-api/src/main/java/org/apache/paimon/utils/StringUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/Expression.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/resources/mysql/sync_table_setup.sql

[cdc] support several basic computed-column expressions in cdc ingestion.

---

docs/static/rest-catalog-open-api.yaml

fix listViewsPagedGlobally doc

fix listViewsPagedGlobally doc

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-api/src/main/java/org/apache/paimon/CoreOptions.java
paimon-api/src/main/java/org/apache/paimon/factories/FactoryUtil.java
paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/partition/PartitionExpireStrategy.java
paimon-core/src/main/java/org/apache/paimon/partition/PartitionExpireStrategyFactory.java
paimon-core/src/test/java/org/apache/paimon/partition/CustomPartitionExpirationFactory.java
paimon-core/src/test/java/org/apache/paimon/partition/PartitionExpireTableTest.java
paimon-core/src/test/resources/META-INF/services/org.apache.paimon.partition.PartitionExpireStrategyFactory
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpirePartitionsAction.java

This strategy use custom class to expire partitions.

[core] Introduce custom PartitionExpireStrategy

---

paimon-api/src/main/java/org/apache/paimon/rest/RESTApi.java

fix: 404 exception comment for snapshot api

[api] fix: 404 exception comment for snapshot api

---

.github/workflows/utitcase.yml

In order to make the test logs smaller when failure

[ci] Build first for 'UTCase and ITCase Others'

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpirePartitionsAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpirePartitionsActionFactory.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ExpirePartitionsActionITCase.java

[core] enable users to set table config for ExpirePartitionsAction

---

paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTest.java

1. Add list partitions tests for non-metastore part table
2. List partitions should return list desc to show latest partition

[rest] Add list partitions tests for non-metastore part table

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapper.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeFunction.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapperTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LookupMergeFunctionTest.java

Refactor after https://github.com/apache/incubator-paimon/pull/5632

[core] Refactor LookupChangelogMergeFunctionWrapper to better readability

---

paimon-core/src/main/java/org/apache/paimon/append/BucketedAppendCompactManager.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCompactOperator.java

This PR adds more logs to `BucketedAppendCompactManager` and `StoreCompactOperator` for easier debugging.

[core] Add more logs to BucketedAppendCompactManager for easier debugging

---

docs/layouts/shortcodes/generated/flink_connector_configuration.html
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileStoreSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedContinuousFileSplitEnumerator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedContinuousFileStoreSource.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumeratorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/align/AlignedContinuousFileSplitEnumeratorTest.java

[flink] Support limit the max snapshot count per checkpoint

---

paimon-core/src/main/java/org/apache/paimon/io/RecordLevelExpire.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireTest.java

fix: record expire get second bug,   int is used as the unit of expire second type, which will overflow in 2038.
RecordLevelExpireTest.testConvertFieldToSecond

[hotfix]fix: record expire get second bug

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

Old snapshots dependent on files.

[hive] HiveCatalog should not delete dir for drop partition

---

paimon-spark/paimon-spark-3.5/pom.xml
pom.xml

[spark] Bump Spark 3.5.6

---

docs/content/primary-key-table/merge-engine/partial-update.md

[doc] enhancing documentation for partial updates during multi-stream updates

---

paimon-core/src/main/java/org/apache/paimon/table/CatalogEnvironment.java
paimon-core/src/main/java/org/apache/paimon/table/FileStoreTableFactory.java

Purpose
Fix the bug that we query data nothing after we insert data into fallback branch using rest catalog. 
Tests
CatalogTableITCase.testReadOptimizedTableFallBack using rest catalog.

[hotfix] Fix fallback branch cannot query data in rest catalog

---

paimon-core/pom.xml
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java

[rest] Fix hadoop conf passing in RESTCatalog

---

paimon-core/src/main/java/org/apache/paimon/postpone/PostponeBucketFileStoreWrite.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PostponeBucketTableITCase.java

Currently files in `bucket = -2` use avro format by default. However, some types (like `TIMESTAMP(9)`) are not supported by avro.
This PR adds a check for avro supported types, so that if the schema contains unsupported types, postpone bucket tables will not use avro by default.
* `PostponeBucketTableITCase#testAvroUnsupportedTypes`.

[core] Don't use avro in postpone bucket tables when schema contains unsupported types

---

docs/content/maintenance/dedicated-compaction.md

Add execution mode specifications for SortCompact.

[doc] Add execution mode specifications for SortCompact.

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-api/src/main/java/org/apache/paimon/CoreOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowDataHashPartitionChannelComputer.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PostponeBucketTableITCase.java

[flink] Postpone mode should support 'partition.sink-strategy'

---

paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireTest.java

As mentioned in https://github.com/apache/paimon/pull/5751, if only pick some small files in top level and rewriting them to a big file when full compaction, it might lead to the generated big file overlapped with other big files. https://github.com/apache/paimon/pull/5751 fixed this bug, and this pr added a test for this case.

[core][test] add test case for picking some small files in top level when full compaction

---

paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/test/java/org/apache/paimon/table/SimpleTableTestBase.java

When the snapshotid still exists in the tag, it means we can rollback to the tag. We can support this.

[core] Support rollback to tag from snapshot id

---

paimon-common/src/main/java/org/apache/paimon/fs/AsyncPositionOutputStream.java

[core] clear bufferQueue when AsyncPositionOutputStream closing.

---

docs/layouts/shortcodes/generated/flink_connector_configuration.html
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/MarkPartitionDoneProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MarkPartitionDoneAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/MarkPartitionDoneProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCommitter.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/listener/CommitListener.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/listener/CommitListenerFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/listener/CommitListeners.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/listener/PartitionMarkDoneListener.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/listener/PartitionMarkDoneTrigger.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/listener/ReportPartStatsListener.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/MarkPartitionDoneActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/listener/AddDonePartitionActionTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/listener/CustomCommitListenerTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/listener/CustomPartitionMarkDoneActionTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/listener/HttpReportMarkDoneActionTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/listener/ListenerTestUtils.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/listener/MockCustomPartitionMarkDoneAction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/listener/PartitionMarkDoneTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/listener/PartitionMarkDoneTriggerTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/listener/SuccessFileMarkDoneActionTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/listener/WatermarkPartitionMarkDoneTest.java
paimon-flink/paimon-flink-common/src/test/resources/META-INF/services/org.apache.paimon.factories.Factory

[flink] Support loading custom CommitListener at runtime

---

paimon-core/src/main/java/org/apache/paimon/table/query/LocalTableQuery.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PrimaryKeyPartialLookupTable.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java

[flink] fall back to full cache mode when partial-lookup is unavailable.

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-api/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/AppendOnlyFileStore.java
paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java
paimon-core/src/main/java/org/apache/paimon/bucket/BucketFunction.java
paimon-core/src/main/java/org/apache/paimon/bucket/PaimonBucketFunction.java
paimon-core/src/main/java/org/apache/paimon/operation/BucketSelectConverter.java
paimon-core/src/main/java/org/apache/paimon/table/sink/FixedBucketRowKeyExtractor.java
paimon-core/src/test/java/org/apache/paimon/operation/BucketSelectConverterTest.java
paimon-core/src/test/java/org/apache/paimon/table/AppendOnlySimpleTableTest.java
paimon-core/src/test/java/org/apache/paimon/table/sink/FixedBucketRowKeyExtractorTest.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordKeyAndBucketExtractor.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PrimaryKeyPartialLookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/partitioner/BucketIdExtractor.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BucketFunctionTypeITCase.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalog/functions/PaimonFunctions.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/BucketExpression.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala
paimon-spark/paimon-spark-ut/pom.xml
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/SparkWriteITCase.scala

[core] Introduce the BucketFunction interface

---

paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergCommitCallback.java
paimon-core/src/test/java/org/apache/paimon/iceberg/IcebergCompatibilityTest.java

1. fix FileNotFoundException when deleting old metadata files.
2. remove unused code in IcebergCompatibilityTest.

[core][iceberg] fix FileNotFoundException when deleting old metadatas

---

paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java

[core] add checker for rename table operation and drop table operation.

---

docs/content/primary-key-table/merge-engine/aggregation.md

Update the aggregate document for rbm32 and rbm64 data type.
No
No

[doc] update agg doc for rmb32 and rbm64

---

paimon-spark/paimon-spark-3.5/pom.xml
paimon-spark/paimon-spark-ut/pom.xml

Like : https://github.com/apache/paimon/pull/5191

[spark][test] Fix the conflict of parquet dependency in spark test

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTest.java

Update test as rest catalog support alter format table

[core] update test as rest catalog support alter format table

---

docs/content/maintenance/manage-snapshots.md

add manually expire snapshot in Manage Snapshots

[doc] add manually expire snapshot in Manage Snapshots

---

paimon-filesystems/paimon-obs-impl/pom.xml

[hotfix] Fix typo in obs filesystem

---

paimon-core/src/main/java/org/apache/paimon/table/system/TagsTable.java
paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java

[refactor] Minor refactor TagManager for validating auto-tag

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-api/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/bucket/BucketFunction.java
paimon-core/src/main/java/org/apache/paimon/bucket/DefaultBucketFunction.java
paimon-core/src/main/java/org/apache/paimon/bucket/ModBucketFunction.java
paimon-core/src/test/java/org/apache/paimon/bucket/ModBucketFunctionTest.java
paimon-core/src/test/java/org/apache/paimon/table/AppendOnlySimpleTableTest.java
paimon-core/src/test/java/org/apache/paimon/table/sink/FixedBucketRowKeyExtractorTest.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalog/functions/PaimonFunctions.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/BucketExpression.scala

Linked issue: close #3538 
Add the support for `mod` bucket function
Introduce a new `ModBucketFunction`
`ModBucketFunctionTest`

[core] Support mod bucket function

---

paimon-core/src/main/java/org/apache/paimon/tag/TagPeriodHandler.java
paimon-core/src/test/java/org/apache/paimon/tag/TagAutoManagerTest.java
paimon-core/src/test/java/org/apache/paimon/tag/TagPeriodHandlerTest.java

[core] fix that auto-created tags without dashes cannot be expired.

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FullCacheLookupTable.java

[flink] fix that lookup table loading is not timely.

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/AppendBypassCoordinateOperator.java

[flink] fix that AppendBypassCoordinateOperator does not generate compaction tasks.

---

paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/utils/HiveSplitGenerator.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveLocationTest.java

[hive] skip the hive location if it does not belong to table

---

paimon-python/pypaimon/api/__init__.py
paimon-python/pypaimon/api/auth.py
paimon-python/pypaimon/api/client.py
paimon-python/pypaimon/api/token_loader.py
paimon-python/pypaimon/api/typedef.py
paimon-python/pypaimon/tests/api_test.py

python api: support ecs role auth
test_ecs_loader_token

[python] api:  support ecs role auth

---

paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTest.java

[rest] Create external table path if not exist

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/RewriteUpsertTableTestBase.scala

[core] Add validation to upsert key

---

paimon-api/src/main/java/org/apache/paimon/rest/RESTCatalogOptions.java
paimon-vfs/paimon-vfs-hadoop/src/main/java/org/apache/paimon/vfs/hadoop/PaimonVirtualFileSystem.java

Set user agent for pvfs hadoop filesystem.

[vfs] Add user agent for pvfs

---

.github/workflows/e2e-tests-flink-1.x.yml
.github/workflows/e2e-tests-flink-2.x-jdk11.yml
.github/workflows/paimon-python-checks.yml
.github/workflows/utitcase-flink-1.x.yml
.github/workflows/utitcase-flink-2.x-jdk11.yml
.github/workflows/utitcase-jdk11.yml
.github/workflows/utitcase-spark-3.x.yml
.github/workflows/utitcase-spark-4.x.yml
.github/workflows/utitcase.yml
paimon-python/setup.py

[python]Independent triggering of Python workflows

---

paimon-common/src/main/java/org/apache/paimon/fs/local/LocalFileIO.java
paimon-vfs/paimon-vfs-common/src/main/java/org/apache/paimon/vfs/VFSOperations.java
paimon-vfs/paimon-vfs-hadoop/src/main/java/org/apache/paimon/vfs/hadoop/PaimonVirtualFileSystem.java
paimon-vfs/paimon-vfs-hadoop/src/test/java/org/apache/paimon/vfs/hadoop/MockRestNoCacheVirtualFileSystemTest.java
paimon-vfs/paimon-vfs-hadoop/src/test/java/org/apache/paimon/vfs/hadoop/MockRestVirtualFileSystemTest.java
paimon-vfs/paimon-vfs-hadoop/src/test/java/org/apache/paimon/vfs/hadoop/VirtualFileSystemTest.java
paimon-vfs/pom.xml

Enable table cache in virtual filesystem to reduce rest requests to rest server.
Linked issue: https://github.com/apache/paimon/issues/5851

[VFS] Enable table cache in PVFS

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/predicate/SimpleSqlPredicateConvertor.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/FlinkCalciteClasses.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/predicate/SimpleSqlPredicateConvertorTest.java

sql to predicate add not in support
add not in  unit test

[Flink] SqlPredicate add not in support

---

paimon-core/src/main/java/org/apache/paimon/tag/TagBatchCreation.java

Follow https://github.com/apache/paimon/pull/5927

[core] Batch auto tag supports custom time zone

---

docs/content/ecosystem/doris.md
docs/content/ecosystem/overview.md

Correct the doris url link in the _docs/content/ecosystem/overview.md_ document.

[doc][hotfix] Correct Doris's URL link

---

paimon-core/src/main/java/org/apache/paimon/operation/FileDeletionBase.java

[core] Optimize FileDeletionBase.cleanUnusedIndexManifests to less file io

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-api/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/test/java/org/apache/paimon/CoreOptionsTest.java

[core] Add compaction.force-wait to support force waiting compaction finish when preparing commit

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/PredicateConverter.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PredicateConverterTest.java

flink PredicateConverter  add is true and is false

[FLINK] Predicate add is true and is false

---

paimon-python/pypaimon/api/api_response.py
paimon-python/pypaimon/catalog/rest/rest_catalog.py
paimon-python/pypaimon/schema/table_schema.py
paimon-python/pypaimon/tests/rest_server.py
paimon-python/setup.py

Fix the bug about param schem of GetTableResponse class

[bug] Fix schema api bug

---

docs/content/iceberg/rest-catalog.md
paimon-iceberg/src/test/java/org/apache/paimon/iceberg/IcebergRestMetadataCommitterTest.java

add a test case for iceberg rest-catalog compability and make some minor documentation fixes.

[iceberg] add a test case and make minor documentation fixes

---

paimon-core/pom.xml
paimon-core/src/main/java/org/apache/paimon/utils/NextSnapshotFetcher.java
paimon-core/src/test/java/org/apache/paimon/table/SimpleTableTestBase.java
paimon-core/src/test/java/org/apache/paimon/table/source/StreamTableScanTest.java
paimon-core/src/test/java/org/apache/paimon/utils/NextSnapshotFetcherTest.java
pom.xml

Avoid frequent access to files.

[core] Add range check counter in NextSnapshotFetcher

---

paimon-flink/paimon-flink1-common/src/main/java/org/apache/paimon/flink/action/MultipleParameterToolAdapter.java
paimon-flink/paimon-flink2-common/src/main/java/org/apache/paimon/flink/action/MultipleParameterToolAdapter.java

[flink][util] MultipleParameterToolAdapter supports merging other parameters

---

paimon-common/src/main/java/org/apache/paimon/casting/FallbackMappingRow.java
paimon-common/src/test/java/org/apache/paimon/casting/FallbackMappingRowTest.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java

Both:
* Fix null check in FallbackMappingRow
* Fix minus row id assign issue (This is too small to come up a new pull request, just one line)

[common] Fix small of FallbackMappingRow null check, fix assign row id issue.

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-api/src/main/java/org/apache/paimon/TableType.java
paimon-core/src/main/java/org/apache/paimon/catalog/CatalogUtils.java
paimon-core/src/main/java/org/apache/paimon/table/iceberg/IcebergTable.java
paimon-core/src/main/java/org/apache/paimon/table/iceberg/IcebergTableImpl.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTest.java

Just like Lance table (https://github.com/apache/incubator-paimon/pull/5977), we can also manage Iceberg Table in Catalog.

[iceberg] Introduce Iceberg Table in Catalog

---

paimon-api/src/main/java/org/apache/paimon/schema/TableSchema.java
paimon-api/src/main/java/org/apache/paimon/table/SpecialFields.java
paimon-core/src/main/java/org/apache/paimon/operation/BaseAppendFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/table/sink/TableWrite.java
paimon-core/src/main/java/org/apache/paimon/table/sink/TableWriteImpl.java
paimon-core/src/main/java/org/apache/paimon/utils/FormatReaderMapping.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/AppendPreCommitCompactWorkerOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/AppendTableCompactor.java
paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/sql/RowLineageTest.scala
paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/RowLineageTest.scala
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/RowLineageTest.scala
paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/sql/RowLineageTest.scala
paimon-spark/paimon-spark-4.0/src/test/scala/org/apache/paimon/spark/sql/RowLineageTest.scala
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkInternalRowWrapper.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkTableWrite.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/UpdatePaimonTableCommand.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/RowLineageTestBase.scala

In thir pr:
- Add `withWriteType` in  interface `TableWrite`
- Support spark update with row lineage table
e.g.
```sql
CREATE TABLE t (id INT, data INT) TBLPROPERTIES ('row-tracking.enabled' = 'true');
INSERT INTO t SELECT /*+ REPARTITION(1) */ id, id AS data FROM range(1, 4);
SELECT *, _ROW_ID, _SEQUENCE_NUMBER FROM t ORDER BY id;
+---+----+-------+----------------+
| id|data|_ROW_ID|_SEQUENCE_NUMBER|
+---+----+-------+----------------+
|  1|   1|      0|               1|
|  2|   2|      1|               1|
|  3|   3|      2|               1|
+---+----+-------+----------------+
in parquet file:
D select * from 'data-c7882bf0-110f-4e30-a054-03171c53cbe3-0.parquet';
┌───────┬───────┐
│  id   │ data  │
│ int32 │ int32 │
├───────┼───────┤
│     1 │     1 │
│     2 │     2 │
│     3 │     3 │ …
```

[core][spark] Support UPDATE for row lineage

---

paimon-core/src/main/java/org/apache/paimon/table/iceberg/IcebergTableImpl.java

fix exception message in IcebergTableImpl.

[iceberg] fix exception message

---

docs/content/maintenance/manage-branches.md

Change the branch name in the document.

[doc] Fix branch name

---

docs/content/append-table/row-tracking.md
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/MergeIntoPaimonTable.scala
paimon-spark/paimon-spark-ut/pom.xml
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/RowLineageTestBase.scala

Subtask of #6022, support spark MERGE  INTO for row lineage

[spark] Support MERGE for row lineage

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-api/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/OffPeakHours.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/UniversalCompaction.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/FullCompactTriggerTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/OffPeakHoursTest.java

[core] Introduce Tests for OffPeakHours and FullCompactTrigger

---

docs/content/append-table/row-tracking.md
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/UpdatePaimonTableCommand.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/RowLineageTestBase.scala

Add more row lineage test cases

[test][spark] Add more row lineage test cases

---

paimon-format/src/main/java/org/apache/paimon/format/orc/filter/OrcFilters.java
paimon-format/src/main/java/org/apache/paimon/format/orc/filter/OrcPredicateFunctionVisitor.java
paimon-format/src/test/java/org/apache/paimon/format/orc/filter/OrcFilterConverterTest.java
paimon-iceberg/src/test/java/org/apache/paimon/flink/CloneActionForIcebergITCase.java

Add support for IN predicate pushdown in ORC format
Add new tests.

[core] Add support for IN predicate pushdown in ORC format

---

paimon-format/src/main/java/org/apache/parquet/filter2/predicate/ParquetFilters.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetFiltersTest.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonPushDownTestBase.scala

[core] Support pushing down IN filter in parquet format

---

paimon-api/src/main/java/org/apache/paimon/CoreOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/AppendTableCompactor.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCompactOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/TableWriteOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/WriterRefresher.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/WriterRefresherTest.java

After https://github.com/apache/paimon/pull/6024

[flink] Refactor WriterRefresher to better abstraction

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java

Log the more information for debugging purpose when creating Flink catalog, such as metastore.

[flink] Log info when creating Flink catalog

---

paimon-core/src/main/java/org/apache/paimon/operation/DataEvolutionSplitRead.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendTableSink.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/RowLineageTestBase.scala

Fix minus:
Disable compaction for data evolution table
Fix count(*) error for data evolution table

[core] Disable compaction  for data evolution table

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendTableSink.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/AppendTableITCase.java

[flink] set managed memory for compact worker.

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java

[flink] Enhance FlinkSink building by expose more interfaces

---

docs/content/append-table/data-evolution.md

[docs] Fix docs about data evolution.

---

paimon-flink/paimon-flink-2.0/src/main/java/org/apache/flink/table/types/logical/VariantType.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/DataTypeToLogicalType.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkRowWrapper.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/LogicalTypeToDataType.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/util/AbstractTestBase.java
paimon-flink/paimon-flink1-common/src/main/java/org/apache/flink/table/data/ArrayData.java
paimon-flink/paimon-flink1-common/src/main/java/org/apache/flink/table/types/logical/VariantType.java
paimon-flink/paimon-flink1-common/src/main/java/org/apache/flink/types/variant/BinaryVariant.java
paimon-flink/paimon-flink1-common/src/main/java/org/apache/flink/types/variant/Variant.java
paimon-flink/paimon-flink1-common/src/main/java/org/apache/flink/types/variant/VariantBuilder.java

Support read and write variant with Flink

[flink] Support read and write variant with Flink

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/listener/PartitionMarkDoneTrigger.java

Asking why my partition does not expire among too many users. So add these logs for debug

[flink] Add log for partition mark done trigger

---

paimon-core/src/test/java/org/apache/paimon/mergetree/LevelsOrderingFixTest.java

[hotfix] Fix compile due to DataFileMeta changes

---

paimon-common/src/main/java/org/apache/paimon/casting/DefaultValueRow.java
paimon-common/src/main/java/org/apache/paimon/utils/DefaultValueUtils.java
paimon-core/src/main/java/org/apache/paimon/catalog/CatalogUtils.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BranchSqlITCase.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DefaultValueTest.scala
paimon-spark/pom.xml

- ~Add current_timestamp and current_date default value~
- Add default value validate

[core] Add validation for default value

---

paimon-python/pypaimon/api/api_response.py
paimon-python/pypaimon/api/client.py
paimon-python/pypaimon/api/resource_paths.py
paimon-python/pypaimon/api/rest_api.py
paimon-python/pypaimon/api/token_loader.py
paimon-python/pypaimon/catalog/catalog_factory.py
paimon-python/pypaimon/catalog/database.py
paimon-python/pypaimon/common/identifier.py
paimon-python/pypaimon/common/predicate.py
paimon-python/pypaimon/filesystem/pvfs.py
paimon-python/pypaimon/manifest/schema/data_file_meta.py
paimon-python/pypaimon/manifest/schema/simple_stats.py
paimon-python/pypaimon/read/split_read.py
paimon-python/pypaimon/schema/data_types.py
paimon-python/pypaimon/schema/schema_manager.py

[python] update to support Python 3.6

---

.github/workflows/file-size-check.yml

https://github.com/apache/paimon/actions/runs/17317278516/job/49162486144?pr=6175

[Test] No large binary files in PR

---

paimon-python/pypaimon/read/table_scan.py
paimon-python/pypaimon/tests/rest_table_read_write_test.py

feat: add large data write test and fix bin packing bug
- Add comprehensive test for writing 500K rows to 200-column wide table
- Fix bin packing logic to prevent shared reference issues
This fixes #6182
- RESTTableReadWriteTest.testWriteWideTableLargeData()

[bug] Fix bin packing bug when writing large data

---

paimon-core/src/main/java/org/apache/paimon/operation/LocalOrphanFilesClean.java
paimon-core/src/test/java/org/apache/paimon/operation/LocalOrphanFilesCleanTest.java

[core] clean up remaining empty directories.

---

.github/workflows/paimon-python-checks.yml
paimon-python/pypaimon/catalog/rest/rest_catalog.py
paimon-python/pypaimon/common/file_io.py
paimon-python/pypaimon/common/predicate.py
paimon-python/pypaimon/read/table_scan.py
paimon-python/pypaimon/table/file_store_table.py
paimon-python/pypaimon/tests/py36/ao_read_write_test.py
paimon-python/pypaimon/write/row_key_extractor.py
paimon-python/setup.py

- DLF access demo runs successfully.
- Add some tests
- Specify package versions in setup.py under python 3.6
pypaimon.tests.py36.ao_read_write_test

[python] Fix failing to access DLF under python 3.6

---

.gitignore
paimon-python/pypaimon/manifest/manifest_file_manager.py
paimon-python/pypaimon/read/reader/sort_merge_reader.py
paimon-python/pypaimon/schema/table_schema.py
paimon-python/pypaimon/table/row/binary_row.py

[Python] Miscellaneous fixes for hybrid write/read

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/AggregateMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/factory/FieldNestedUpdateAggFactory.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/factory/FieldPrimaryKeyAggFactory.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregatorRetractNullTest.java

Use with #6213 for finding which agg cuases NPE.

[core] Refactor AggregateMergeFunction and PartialUpdateMergeFunction for better maintenance and add test for retracting

---

docs/content/program-api/python-api.md

[Python] Update Doc for Read Splits and Data Types

---

paimon-python/pypaimon/common/config.py
paimon-python/pypaimon/common/file_io.py

[Python] fix oss file_io client_kwargs for pyarrow 16.0

---

paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java

Fix CatalogTestBase#testFormatTableRead visibility

[test] Fix method visibility in CatalogTestBase

---

paimon-common/src/main/java/org/apache/paimon/data/AbstractBinaryWriter.java

hotfix: compile error in AbstractBinaryWriter

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonAnalysis.scala

[spark] Avoid unnecessary repeated resolve MergeIntoTable

---

paimon-common/src/main/java/org/apache/paimon/format/EmptyStatsExtractor.java
paimon-common/src/main/java/org/apache/paimon/fs/OffsetSeekableInputStream.java
paimon-common/src/main/java/org/apache/paimon/utils/StreamUtils.java
paimon-common/src/test/java/org/apache/paimon/fs/OffsetSeekableInputStreamTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/changelog/format/CompactedChangelogFormatReaderFactory.java
paimon-format/src/main/java/org/apache/paimon/format/blob/BlobFileFormat.java
paimon-format/src/main/java/org/apache/paimon/format/blob/BlobFileFormatFactory.java
paimon-format/src/main/java/org/apache/paimon/format/blob/BlobFileRef.java
paimon-format/src/main/java/org/apache/paimon/format/blob/BlobFormatReader.java
paimon-format/src/main/java/org/apache/paimon/format/blob/BlobFormatWriter.java
paimon-format/src/test/java/org/apache/paimon/format/blob/BlobFileFormatTest.java

See https://cwiki.apache.org/confluence/display/PAIMON/PIP-35%3A+Introduce+Blob+to+store+multimodal+data

[format] Introduce BlobFileFormat to blob storage

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/RewritePaimonFunctionCommands.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonV1FunctionTestBase.scala

Improve error msg for creating a function on an existing tmp function

[spark] Improve error msg for creating a function on an existing tmp function
