apache/paimon

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/ConcatRecordReader.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/SortMergeReader.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/sst/SstFile.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/sst/SstFileMeta.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/sst/SstFileMetaSerializer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/sst/SstPathFactory.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/stats/FieldStats.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/stats/FieldStatsArraySerializer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/stats/FieldStatsCollector.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/FileUtils.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/RecordReader.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/RecordReaderIterator.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/CombiningRecordReaderTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/ConcatRecordReaderTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/SortMergeReaderTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/sst/SstFileMetaSerializerTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/sst/SstFileTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/sst/SstPathFactoryTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/sst/SstTestDataGenerator.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/stats/FieldStatsArraySerializerTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/stats/FieldStatsCollectorTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/FailingAtomicRenameFileSystem.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/FileStorePathFactory.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/TestAtomicRenameFileSystem.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/TestReusingRecordReader.java
- flink-table-store-core/src/test/resources/META-INF/services/org.apache.flink.core.fs.FileSystemFactory
- Introduce RecordReader interface: The reader that reads the batches of records. 
- Introduce SortMergeReader: This reader is to read a list of `RecordReader`, which is already sorted by key and sequence number, and perform a sort merge algorithm. `KeyValue` with the same key will also be combined during sort merging.
- Introduce ConcatRecordReader: This reader is to concatenate a list of `RecordReader` and read them sequentially. The input list is already sorted by key and sequence number, and the key intervals do not overlap each other.
- Introduce FieldStats: Statistics for each field.
- Introduce SstPathFactory: Factory which produces new Path for sst files.
- Introduce SstFile and SstFileMeta: This SstFile includes several `KeyValue`, representing the changes inserted into the file …
> [FLINK-25628] Introduce RecordReader and related classes for table store

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/Increment.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTree.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeReader.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/RecordWriter.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/LevelsTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/MergeTreeTest.java
- Add  test for Levels
- Introduce RecordWriter: The `RecordWriter` is responsible for writing data and handling in-progress files used to write yet un-staged data. The incremental files ready to commit is returned to the system by the`#prepareCommit()`
- Introduce MergeTreeOptions: Options for merge tree.
- Introduce MergeTree writer and reader: A merge tree, provides writer and reader, the granularity of the change is the file.
> [FLINK-25630] Introduce MergeTree writer and reader for table store

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/And.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/Equal.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/ExpressionConverter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/GreaterOrEqual.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/GreaterThan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/IsNotNull.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/IsNull.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/LessOrEqual.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/LessThan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/Literal.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/NotEqual.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/Or.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/Predicate.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/PredicateConverter.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/predicate/PredicateTest.java
Flink Expression is not serializable. Although it has asSerializableString, the method is not implemented by all Expressions, and the deserialization requires many parameters.
So table store introduces Predicate to be a serializable class to do filter and partition push down.
> [FLINK-25643] Introduce Predicate to table store

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStore.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestCommittable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestCommittableSerializer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommit.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreExpire.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/Lock.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestCommittableSerializerTest.java
We should introduce a FileStore interface to provide operations:
- provides FileStoreWrite: Write operation which provides RecordWriter creation.
- provides FileStoreCommit: Commit operation which provides commit and overwrite.
- provides FileStoreExpire: Expire operation which provides snapshots expire.
> [FLINK-25644] Introduce interfaces between file-table-store and flink connector sink

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/CompactManager.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/CompactStrategy.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/CompactManagerTest.java
When output level is zero, there may be have other files in level 0, we can not drop delete.
> [FLINK-25687] DropDelete is incorrect in CompactManager when outputLevel is zero

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/KeyValue.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/Snapshot.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestCommittable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestEntry.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestFile.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestFileMeta.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestList.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/sst/SstFile.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScanImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/FileStorePathFactory.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/FileUtils.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestKeyValueGenerator.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestFileMetaTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestFileTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestListTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/sst/SstTestDataGenerator.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/TestCommitThread.java
This PR introduces an atomic commit transaction for file store.
1. Before calling `FileStoreCommitImpl#commit`, user should first call `FileStoreCommitImpl#filterCommitted` to make sure this commit is not done before.
2. Before committing, it will first check for conflicts by checking if all files to be removed currently exists.
3. After that it use the external `FileStoreCommitImpl#lock` (if provided) or the atomic rename of the file system to ensure atomicity.
4. If commit fails due to conflicts or exception it tries its best to clean up and aborts.
5. If atomic rename fails it tries again after reading the latest snapshot from step 2.
> [FLINK-25689] Introduce atomic commit

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeWriter.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/MergeTreeTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/TestCommitThread.java
The deletion in MergeTreeWriter.updateCompactResult dose not consider upgrade case, the upgrade file is required by previous snapshot and following snapshot, we should ensure:
1. This file is not the output of upgraded.
2. This file is not the input of upgraded.
Otherwise, the file will be deleted incorrectly.
> [FLINK-25770] Delete file is not correct in MergeTreeWriter

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestFile.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestList.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeFactory.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/sst/SstFile.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/sst/SstPathFactory.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScanImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreWriteImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/stats/FieldStatsArraySerializer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/stats/FieldStatsCollector.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/FileStorePathFactory.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/FileUtils.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/RowDataToObjectArrayConverter.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestFileMetaTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestFileTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestListTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/MergeTreeTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/sst/SstFileTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreScanTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/OperationTestUtils.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/TestCommitThread.java
This PR implements partition and bucket filter in `FileStoreScanImpl`. It also perform some small optimizations such as concurrent reads in `FileStoreScanImpl`.
> [FLINK-25803] Implement partition and bucket filter in FileStoreScanImpl

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestFileMeta.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestFileMetaTest.java
Currently commit operation will create specific manifest files for new changes. We should not add more complexity by adding special cases to the commit protocol so we should merge new changes with the older changes.
> [hotfix] Commit operation should not create specific manifest file for new changes

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/Snapshot.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreExpireImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/FileStorePathFactory.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreExpireTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreScanTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/OperationTestUtils.java
Currently FileStoreExpire does not have an implementation. We need an implementation to clean up old snapshots and related files.
> [FLINK-25994] Implement FileStoreExpire

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/Snapshot.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestCommittable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestCommittableSerializer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestFileMeta.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestList.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommit.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/TypeUtils.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestKeyValueGenerator.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreExpireTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreScanTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/OperationTestUtils.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/TestCommitThread.java
- flink-table-store-core/src/test/resources/log4j2-test.xml
Overwrite is a useful transaction for batch jobs to completely update a partition for data correction. Currently FileStoreScanImpl doesn't implement this transaction so we need to implement that.
> [FLINK-25876] Implement overwrite in FlinkStoreCommitImpl

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestFileMeta.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestFileMetaTest.java
Changes in this PR:
- Introduce `manifest.merge-min-count` option in `FileStoreOptions.java`
- Update `merge` function in `ManifestFileMata.java` to take that option
> [FLINK-26217] Introduce manifest.merge-min-count in commit

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreITCase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestFileMetaTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestFileTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestListTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/sst/SstFileTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreExpireTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreScanTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/OperationTestUtils.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/TestCommitThread.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/FailingAtomicRenameFileSystem.java
Currently `FailingAtomicRenameFileSystem` uses a static method to reset the failing counter and set failing possibility. This may cause conflicts when there are multiple testing threads running different test cases. This PR fixes the issue.
> [hotfix] Set authority as thread name for FailingAtomicRenameFileSystem to support multi-thread testing

- flink-table-store-connector/pom.xml
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreFactory.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreFactoryOptions.java
- flink-table-store-connector/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TableStoreFactoryTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TableStoreITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/log/LogOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/log/LogStoreTableFactory.java
- flink-table-store-kafka/pom.xml
- flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogStoreFactory.java
- flink-table-store-kafka/src/test/java/org/apache/flink/table/store/kafka/KafkaLogITCase.java
- flink-table-store-kafka/src/test/java/org/apache/flink/table/store/kafka/KafkaTableTestBase.java
This PR aims to introduce the implementation of `ManagedTableFactory`, which supports using SQL to interact with table-store, the more details can be found at [FLIP-188](https://cwiki.apache.org/confluence/display/FLINK/FLIP-188%3A+Introduce+Built-in+Dynamic+Table+Storage).
This PR contains one commit
- 9781e97 Implement `#enrichOptions`, `#onCreateTable`, `#onDropTable` to support `CREATE/DROP TABLE` statements.
- Unit test by `FileStoreTableFactoryTest` 
- End-to-end test by `FileStoreITCase`
> [FLINK-26208] Introduce TableStoreFactory to support create/drop managed table via SQL

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestCommittable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreExpireTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreScanTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/TestCommitThread.java
This PR refactor `OperationTestUtils` into `TestFileStore` to clean up operation test cases.
> [hotfix] Refactor OperationTestUtils into TestFileStore and remove unnecessary repeated tests

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileFormat.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileFormatImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/KeyValue.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/sst/SstFileReader.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreRead.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreReadImpl.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/sst/SstFileTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreReadTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/FlushingAvroFormat.java
Projection pushdown is an optimization for sources. With this optimization, we can avoid reading useless columns and thus improve performance.
> [[FLINK-26031] Support projection pushdown on keys and values

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestFile.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestFileMeta.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/sst/SstFileWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/RollingFile.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestFileMetaTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestFileTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/sst/SstFileTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/stats/StatsTestUtils.java
Currently `ManifestFile#write` will only produce a single file no matter how large the given `ManifestFileMeta` list is. However batch jobs are likely to produce a lot of changes hence the list might be very long. We need to allow `ManifestFile#write` to produce multiple files for effective merging and filtering.
> [FLINK-26442] Allow ManifestFile to write a list of ManifestFileMeta into multiple files if too many

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/Snapshot.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestFile.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreExpireImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScanImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/FileUtils.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreExpireTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreScanTest.java
Current implementation of `FileStoreExpire` will read the whole snapshot for each snapshot to be expired. This is unnecessary because later snapshots also contain changes from previous snapshots.
This PR optimizes this by only reading new changes in a snapshot.
> [FLINK-26247] Optimize expire by only reading new changes in a snapshot

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreSinkWriter.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/StoreSinkTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/TestFileStore.java
This PR tries to fix the `ClassCastException` thrown when  `StoreSinkWriter#writeToFileStore` encountered non-pk value. When a record has no pk, the value should be a count with `long` type, while the initial value assigns `int` and will cause a `ClassCastException` at runtime (thrown by `SortBufferMemTable#put` caused by `buffer.write`).
`StoreSinkTest` is modified slightly to check the value type. Rollback the src code change will reproduce the issue.
> [hotfix] Fix ClassCastException when StoreSinkWriter#writeToFileStore encountered non-pk record

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/Snapshot.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
Overwriting a snapshot is different from the normal commit. It firstly clears up the whole partition then append new entries. So we need a new snapshot commit kind to describe it.
> [FLINK-26441] Add a new OVERWRITE snapshot commit kind

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreOptions.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
Currently, the `FileStoreOptions` only has the `FILE_PATH` option as the table store root dir, we should have another `TABLE_PATH` for generated SST/Manifest/Snapshot file per table.
> [FLINK-26562] Introduce table.path option for FileStoreOptions

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSource.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSourceReader.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitReader.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitReaderTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/TestDataReadWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreRead.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreReadImpl.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreReadTest.java
There is a keyAsRecord in `FileStoreSourceSplitReader`, but this should only be keyAsRecord. When keyAsRecord, it should emit the same number of records as value count.
And, `FileStoreSourceSplitReader` should have the ability to output delete records.
> [FLINK-26567] FileStoreSourceSplitReader should deal with value count

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/Snapshot.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
Now `ManifestCommittable` has the `logOffsets` inside, but it is not saved when generating snapshot in `FileStoreCommitImpl`.`logOffsets` needs to be saved in the snapshot. When `logOffsets` doesn't contain all buckets, it means that the current generated snapshot does not write data to all buckets, and it should be read from the last snapshot to complete the bucket's offsets. 
- `Snapshot` introduces the `logOffsets` inside.
- `FileStoreCommitImpl` saves the `logOffsets` in the `Snapshot`.
> [FLINK-26293] Store log offsets in snapshot

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStore.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/BucketStreamPartitioner.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSource.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitGenerator.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/LogHybridSourceFactory.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/PendingSplitsCheckpoint.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/PendingSplitsCheckpointSerializer.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/StaticFileStoreSplitEnumerator.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/LogStoreSinkITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/PendingSplitsCheckpointSerializerTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/StaticFileStoreSplitEnumeratorTest.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScanImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/sink/SinkRecordConverter.java
Introduce TableStore API to provide a clear and simple API for the upper level:
- Create a TableStore source.
- Create a TableStore sink.
The TableStore API automatically handles:
- handles key-related things
- handles mixing / hybrid with log store
- before sink, and it also handles partitioner to avoid message disorder
> [FLINK-26530] Introduce TableStore API and refactor ITCases

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScanImpl.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreScanTest.java
Now that we've implemented sst file statistics in [FLINK-26346](https://issues.apache.org/jira/browse/FLINK-26346), we can apply key & value filter in `FileStoreScanImpl`.
> [FLINK-26544] Apply key & value filter in FileStoreScanImpl

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStore.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/ContinuousFileSplitEnumerator.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSource.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/StaticFileStoreSplitEnumerator.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FiniteTestSource.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ReadWriteTableITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScanImpl.java
Now FileStoreScan only supports snapshot scan. It can support incremental scan too.
> [FLINK-26475] FileStoreScan supports incremental consuming

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStore.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSourceReader.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitReader.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/LogHybridSourceFactory.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitReaderTest.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/FileUtils.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/log/LogSourceProvider.java
- flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogSinkProvider.java
as https://issues.apache.org/jira/browse/FLINK-25927 has been merged into flink master branch and 1.15 branch, the flink-connector-base modules has been shaded into many connectors modules.
now the building of table-store project has been failed caused by above.
> [FLINK-26677] Make flink-connector-base dependency consistent

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/BucketStreamPartitioner.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreSinkWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/sink/SinkRecord.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/sink/SinkRecordConverter.java
- flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogSerializationSchema.java
- flink-table-store-kafka/src/test/java/org/apache/flink/table/store/kafka/KafkaLogTestUtils.java
`record.key().getArity() == 0` is ambiguous, it should be `record.primaryKey().getArity() == 0`
> [hotfix] Rename ambiguous key to primary key

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreFactory.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreFactoryOptions.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/TableStoreSink.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/ContinuousFileSplitEnumerator.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ContinuousFileStoreITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/CreateTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/DropTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ReadWriteTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TableStoreFactoryTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TableStoreTestBase.java
Remove CHANGE_TRACKING, the default overwrite does not generate changes to the log system.
Add hint CHANGE_TRACKING=false is an unfriendly way to  to support overwrite, and by default overwrite does not generate changes, so users have to turn it off.
Later we have the ability to generate changes for overwrite, and then add an overwrite.change-tracking.mode to configure it.
> [FLINK-26711] Remove change tracking in TableStore

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStore.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreFactory.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/CreateTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/DropTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ReadWriteTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TableStoreFactoryTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TableStoreTestBase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/LogStoreSinkITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreOptions.java
* Add check on pk and partition key, and filter partition keys when computing pk index
* Redefine table path as '${file.path}/${cat}.catalog/${db}.db/${table}'
> [FLINK-26753] PK constraint should include partition keys if table is partitioned

- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreReadTest.java
`FileStoreReadTest#testKeyProjection` is unstable because even after key projection, the merge tree may merge and discard key values with 0 occurrences. This PR fixes this issue.
> [hotfix] Fix unstable test FileStoreReadTest#testKeyProjection

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ContinuousFileStoreITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/LogStoreSinkITCase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/BlockingIterator.java
- flink-table-store-kafka/src/test/java/org/apache/flink/table/store/kafka/KafkaLogITCase.java
BlockingIterator provides the ability to bring timeout to blocking iterators.
It use a static cached {@link ExecutorService}. We don't limit the number of threads since the work inside is I/O type.
> [FLINK-26834] Introduce BlockingIterator to help testing

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitReader.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ReadWriteTableITCase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/BlockingIterator.java
Bug in FileStoreSourceSplitReader, the row is reused, we can not just modify the row kind. We should set back to insert kind before next keyvalue.
> [FLINK-26860] FileStore continuous bug for delete row kind records

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/global/AbstractCommitterOperator.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/LogHybridSourceFactory.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ReadWriteTableITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/log/LogWriteCallback.java
In AbstractCommitterOperator.endInput:
Suppose the last checkpoint before endInput is 5. Flink Streaming Job calling order:
1. Accept elements from upstream prepareSnapshotPreBarrier(5)
2. this.snapshotState(5)
3. Accept elements from upstream endInput
4. this.endInput
5. this.notifyCheckpointComplete(5)
So we should submit all the data in the endInput in order to avoid disordered commits.
> [FLINK-26867] Hybrid reading wrong because of disordered commits

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/UniversalCompaction.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/UniversalCompactionTest.java
This way we can avoid the problem of oversized first files
> [FLINK-26971] UniversalCompaction should pick by size ratio after picking by file num

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/format/FileFormat.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/FileFormatTest.java
Currently if we want to set compression method of file store we need to use 'file.orc.compress'. It would be better to use 'orc.compress' directly, just like what we do for filesystem connectors.
> [FLINK-27004] Use '<format>.<option>' instead of 'file.<format>.<option>' in table properties of managed table

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/format/FileFormat.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/format/FileFormatImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestFile.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestList.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/sst/SstFileReader.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/sst/SstFileWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreWriteImpl.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/avro/AvroFileFormat.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/orc/OrcFileFormat.java
When testing table store I'm faced with the following warning messages:
```
org.apache.org.impl.MemoryManagerImpl [] - Owner thread expected Thread[Writer -> Local Committer (1/16)#0,5,Flink Task Threads], got Thread[pool-8-thread-1,5,Flink Task Threads]
```
This is because `OrcBulkWriterFactory` is not thread safe (it keeps `WriterOptions` as a class member and creates writers from the same `WriterOptions` object, which is not thread safe).
What we should do is to reuse `FileFormat` instead of `DecodingFormat`/`EncodingFormat` to ensure thread safety.
> [FLINK-27070] Reuse FileFormat instead of DecodingFormat/EncodingFormat to ensure thread safety

- docs/content/docs/development/write-table.md
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreExpireImpl.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreExpireTest.java
Currently we retain at least 1 snapshot when expiring. However consider the following scenario:
A user writes a snapshot one day ago. Today he is reading this snapshot and meanwhile writing more records. If a new snapshot is created and the reading is not finished, the old snapshot created one day ago will be removed as it exceeds maximum retaining time. This will cause the reading to fail.
We should introduce `snapshot.num-retained.min` to at least retain a minimum number of snapshots to avoid this problem.
> [FLINK-27085] Introduce snapshot.num-retained.min option

- flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogSourceProvider.java
flink kafka relies on groupId in some unnecessary code paths, we can configure a random uuid
> [hotfix] Add random group id to kafka consumer

- pom.xml
`junit.version` in pom.xml is not defined. Use `junit4.version` instead.
> [hotfix] Fix junit4 dependency version

- flink-table-store-dist/pom.xml
`flink-sql-connector-kafka` contains shaded kafka classes. As we rely directly on kafka classes we need to use these shaded classes, so we also need to shade kafka dependencies.
> [hotfix] Shade kafka dependencies

- docs/content/docs/development/create-table.md
- docs/content/docs/try-table-store/quick-start.md
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ContinuousFileStoreITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ReadWriteTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ReadWriteTableTestBase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TableStoreFactoryTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TableStoreTestBase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreOptions.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
The original `file.path` indicates the root path of table store. However other options starting with `file.` (for example `file.format`) only affects sst files and have nothing to do with manifests or snapshots. We should change `file.path` to `path` to indicate that this config option affects the whole table store, not only the sst files.
> [FLINK-27135] Rename 'file.path' table option in table store to 'path'

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/sst/SstFileWriter.java
Each level 0 sst file is a sorted run. If we write rolling files then we cannot decrease number of sorted runs.
> [FLINK-27136] Disable rolling file when writing level 0 sst files

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/format/FileFormat.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/format/FileFormatFactory.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeOptions.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/format/FileStatsExtractingAvroFormatFactory.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/avro/AvroFileFormatFactory.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/orc/OrcFileFormat.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/orc/OrcFileFormatFactory.java
- flink-table-store-format/src/test/java/org/apache/flink/table/store/format/orc/OrcFileFormatTest.java
- By default, numLevels = numSortedRunMax + 1, this ensures that the compaction does not fall to level 0, but at least to level 1
- orc default compress is lz4, zlib is too slow
> [FLINK-27158] Adjust default value of compaction and compress

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
Currently it is possible for `FileStoreCommitImpl#filterCommitted` to check an expired snapshot, which throws `FileNotExists` exception. When faced with an expired file `FileStoreCommitImpl#filterCommitted` should exit.
> [FLINK-27139] FileStoreCommitImpl#filterCommitted should exit when faced with expired files

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/CompactManager.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/UniversalCompaction.java
Currently there is not enough log in `CompactManager`, for example what files are being compacted, what are their sizes, etc. This PR adds logs to file store compact for better tunning.
> [hotfix] Add logs to file store compact for better tunning

- flink-table-store-dist/pom.xml
- flink-table-store-format/pom.xml
- flink-table-store-format/src/test/java/org/apache/flink/table/store/format/BulkFileFormatTest.java
the following format should be supported in flink-table-store:
1. built in flink-table-store, such as avro/orc, supported already
2. provided by Flink, such as parquet/csv, has not been supported yet
> [FLINK-27172] Support bulk based format provided by Flink

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeOptions.java
Default 128 MB has better performance.
> [hotfix] Adjust the default value of write-buffer-size to 128 MB

- flink-table-store-codegen-loader/pom.xml
- flink-table-store-codegen-loader/src/main/java/org/apache/flink/table/store/codegen/CodeGenLoader.java
- flink-table-store-codegen/pom.xml
- flink-table-store-codegen/src/main/java/org/apache/flink/table/store/codegen/CodeGeneratorImpl.java
- flink-table-store-core/pom.xml
- flink-table-store-dist/pom.xml
- flink-table-store-format/pom.xml
Currently all Flink dependencies needed at runtime (for example, flink-sql-avro) by table store are packaged in flink-table-store-dist module. If we would like to enable other systems to read from table store in the future all these dependencies need to be copied to the distribution module of that system.
So instead we should move these dependencies to the associated table store module so that the number of dependencies in flink-table-store-dist can be decreased.
> [FLINK-27408] Package Flink runtime dependencies into associated table store modules instead of flink-table-store-dist

- docs/content/docs/development/write-table.md
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/TestDataReadWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/Levels.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/CompactManager.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/UniversalCompaction.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreWriteImpl.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/MergeTreeTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/CompactManagerTest.java
Currently Full Compaction may cause the writer to be blocked, which has an impact on LogStore latency.
We need to decouple compact and write, compact completely asynchronous.
But too many files will lead to unstable reads, when too many files, Compaction processing speed can not keep up with Writer, need to back press Writer.
Stop parameter: num-sorted-run.stop-trigger, default 10
> [FLINK-27335] Optimize async compaction in MergeTreeWriter

- flink-table-store-codegen/pom.xml
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/TypeE2eTest.java
- flink-table-store-format/pom.xml
When using array data type with table store a ClassNotFound exception will be thrown. This is because FLINK-27408 packaged codegen related classes into table store itself but missed out some classes.
To make sure that such bug will not happen again we also need an e2e test to check all supported data types.
> [FLINK-27439] Fix ClassNotFoundException when using array type in table store

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreFactoryOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeOptions.java
This config key controls the behavior for `ALTER TABLE ... COMPACT`.
When `compact.rescale-bucket` is false, it indicates the compaction will rewrite data according to the bucket number, which is read from manifest meta, and the commit will only add/delete files; o.w. it suggests the compaction will read bucket number from catalog meta, and the commit will overwrite the whole partition directory.
> [FLINK-27528] Introduce a new configuration option 'compact.rescale-bucket' for FileStore

- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/E2eTestBase.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/LogStoreE2eTest.java
- flink-table-store-e2e-tests/src/test/resources-filtered/docker-compose.yaml
- flink-table-store-e2e-tests/src/test/resources/flink.env
- pom.xml
Currently we build test dockers with testcontainers API. However testcontainers API are only a subset of docker APIs and is not suitable for managing a large group of services (In the future we'll add end to end tests for Hive which consists of numerous services such as Hadoop namenodes, datanodes, Hive metastore, etc.). So we refactor E2eTestBase with docker compose.
> [FLINK-27542] Refactor E2eTestBase with docker compose

- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/E2eTestBase.java
- flink-table-store-e2e-tests/src/test/resources-filtered/docker-compose.yaml
Currently e2e tests are not stable and may fail with `Container did not start correctly`. This is because docker images are occupying host machine ports now. As tests may run in parallel, docker images will fail to start if their corresponding ports are already occupied.
> [FLINK-27542] E2e docker image should not occupy host machine ports as tests may run in parallel

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/data/DataFileMeta.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/Increment.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/writer/AppendOnlyWriter.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/writer/AppendOnlyWriterTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/writer/TestAppendOnlyWriter.java
It's a sub PR for https://github.com/apache/flink-table-store/pull/99, which is trying to add an AppendOnlyWriter and unit test to accept records without any key or sort order.
> [FLINK-27546] Add append only writer which implements the RecordWriter interface

- flink-table-store-hive/src/main/java/org/apache/flink/table/store/hive/objectinspector/TableStoreDateObjectInspector.java
- flink-table-store-hive/src/test/java/org/apache/flink/table/store/hive/objectinspector/TableStoreDateObjectInspectorTest.java
Flink store date as an integer internally, where this integer represents epoch day. However `TableStoreDateObjectInspector` currently see this integer as epoch millisecond.
> [FLINK-27589] Fix incorrect implementation of TableStoreDateObjectInspector

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreFactoryOptions.java
When `TableStoreFactory.onCompactTable`gets called, the planned manifest entries need to be injected back into the enriched options, and we need a new key to represent it.
> [FLINK-27558] Introduce a new optional option for TableStoreFactory to represent planned manifest entries

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/NotEqual.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/predicate/PredicateTest.java
`NotEqual` predicate will throw `NullPointerException` for a column consisting only of nulls.
> [FLINK-27629] Fix NullPointerException in NotEqual predicate

- .github/workflows/e2e-tests.yml
- .github/workflows/java8-build.yml
- .github/workflows/utils.sh
- flink-table-store-hive/src/main/java/org/apache/flink/table/store/hive/objectinspector/TableStoreDateObjectInspector.java
- flink-table-store-hive/src/test/java/org/apache/flink/table/store/hive/objectinspector/TableStoreDateObjectInspectorTest.java
- flink-table-store-hive/src/test/java/org/apache/flink/table/store/hive/objectinspector/TableStoreTimestampObjectInspectorTest.java
Current implementation of `TableStoreDateObjectInspector` is still incorrect. The resulting `Date` is actually the previous day in timezones with negative offsets.
> [FLINK-27589] Fix incorrect implementation of TableStoreDateObjectInspector yet again

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/TableStoreSource.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScanImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/And.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/Equal.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/GreaterOrEqual.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/GreaterThan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/IsNotNull.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/IsNull.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/LessOrEqual.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/LessThan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/NotEqual.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/Or.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/Predicate.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/PredicateBuilder.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/StartsWith.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/predicate/PredicateTest.java
- flink-table-store-hive/src/main/java/org/apache/flink/table/store/SearchArgumentToPredicateConverter.java
- flink-table-store-hive/src/main/java/org/apache/flink/table/store/hive/TableStoreHiveStorageHandler.java
- flink-table-store-hive/src/main/java/org/apache/flink/table/store/mapred/TableStoreInputFormat.java
- flink-table-store-hive/src/test/java/org/apache/flink/table/store/FileStoreTestHelper.java
- flink-table-store-hive/src/test/java/org/apache/flink/table/store/SearchArgumentToPredicateConverterTest.java
- flink-table-store-hive/src/test/java/org/apache/flink/table/store/hive/TableStoreHiveStorageHandlerITCase.java
- flink-table-store-hive/src/test/java/org/apache/flink/table/store/mapred/TableStoreRecordReaderTest.java
Filter pushdown is a critical optimization for sources as it can decrease number of records to read. Hive provides a `HiveStoragePredicateHandler` interface for this purpose. We need to implement this interface in `TableStoreHiveStorageHandler`.
> [FLINK-27580] Implement filter pushdown for TableStoreHiveStorageHandler

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ContinuousFileStoreITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ForceCompactionITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/PartialUpdateITCase.java
A minor factor for the unit tests to reuse the `batchSql`.
> [FLINK-27706] Refactor all subclasses of FileStoreTableITCase to use the batchSql

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ForceCompactionITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/Levels.java
This PR specifies the number of levels as `max(restoredFiles.maxLevel() + 1, mergeTreeOptions.numOfLevels)`, to avoid the possible out-of-bounds exception.
> [FLINK-27705] Prevent num-sorted-run.compaction-trigger from interfering num-levels

- docs/content/docs/development/create-table.md
- docs/content/docs/try-table-store/quick-start.md
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/AbstractTableStoreFactory.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStore.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreFactoryOptions.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreManagedFactory.java
- flink-table-store-connector/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ReadWriteTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ReadWriteTableTestBase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TableStoreManagedFactoryTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TableStoreTestBase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/log/LogStoreTableFactory.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/FileStoreBatchE2eTest.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/FileStoreFlinkFormatE2eTest.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/FileStoreStreamE2eTest.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/LogStoreE2eTest.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/TypeE2eTest.java
- flink-table-store-e2e-tests/src/test/resources/log4j2-test.properties
- flink-table-store-hive/src/test/java/org/apache/flink/table/store/FileStoreTestHelper.java
- flink-table-store-hive/src/test/java/org/apache/flink/table/store/hive/TableStoreHiveStorageHandlerITCase.java
- flink-table-store-hive/src/test/java/org/apache/flink/table/store/mapred/TableStoreRecordReaderTest.java
- flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogOptions.java
- flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogStoreFactory.java
- flink-table-store-kafka/src/test/java/org/apache/flink/table/store/kafka/KafkaLogTestUtils.java
The path is easy to bother the user, he/she will misinterpret it as path of table.
Let's change it to root-path, and it will be clearer.
1. Rename `path` to `root-path`.
2. Extract a `AbstractTableStoreFactory`.
3. Use `path` as table path. Table Path will be generated in `enrichOptions`.
4. Topic will be generated in `LogStoreTableFactory.enrichOptions`.
It is equivalent to solidifying the `path` and `topic` when `enrichOptions`, so that subsequent queries and writes can use them directly.
This allows us to have a richer strategy for `path` / `topic` generation, rather than being tied to generating paths based on `tableIdentifier`.
> [FLINK-27752] Change 'path' to 'root-path' in table store

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScanImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/And.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/CompoundPredicate.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/Equal.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/GreaterOrEqual.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/GreaterThan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/IsNotNull.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/IsNull.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/LeafPredicate.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/LessOrEqual.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/LessThan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/NotEqual.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/Or.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/PredicateBuilder.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/PredicateConverter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/StartsWith.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreScanTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/predicate/PredicateConverterTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/predicate/PredicateTest.java
- flink-table-store-hive/src/main/java/org/apache/flink/table/store/SearchArgumentToPredicateConverter.java
- flink-table-store-hive/src/test/java/org/apache/flink/table/store/SearchArgumentToPredicateConverterTest.java
We'd like to expose a more simple interface in the row data abstraction layer. Instead of the `withPartitionFilter`, `withKeyFIlter` and `withValueFilter` methods in `FileStoreScan`, we'd like to introduce `RowDataScan` containing only one `withFilter` method. We'll enclose the logic to extract partition predicate or key predicate in this method.
To extract partition predicate from a big predicate object we'll need to look into this predicate tree. That's why we'll need `children` method and `LeafPredicate` interface to help us represent this tree structure.
> [FLINK-27835] Introduce LeafPredicate interface and children method in Predicate

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/TestDataReadWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStoreImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/data/DataFilePathFactory.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/format/FileFormat.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/format/FileFormatImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/FileStorePathFactory.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/data/DataFilePathFactoryTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/data/DataFileTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/format/FlushingFileFormat.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestFileMetaTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestFileTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestListTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/FileStorePathFactoryTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/writer/AppendOnlyWriterTest.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/avro/AvroFileFormat.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/orc/OrcFileFormat.java
- flink-table-store-format/src/test/java/org/apache/flink/table/store/format/FileFormatSuffixTest.java
Add file Suffix to data files, close [FLINK-27502](https://issues.apache.org/jira/browse/FLINK-27502)
org.apache.flink.table.store.format.FileFormatSuffixTest
> [FLINK-27502] Add file Suffix to data files

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreConnectorFactory.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileSystemCatalogITCase.java
- flink-table-store-core/pom.xml
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/FileSystemCatalog.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/TableStoreCatalog.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/TableStoreCatalogFactory.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/Schema.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/UpdateSchema.java
- flink-table-store-core/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/catalog/FileSystemCatalogTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/catalog/TableStoreCatalogTest.java
The Table Store has store the schema and other information on the file system so that it can actually provide a FileSystemCatalog for users to use.
This catalog is provided in JIRA:
- It supports database related management
- It supports the creation and deletion of tables
- It supports table changes, but currently can only modify the options and other information, the underlying does not yet support the schema column information modification
The use case for filesystem catalog:
```
CREATE CATALOG table_store WITH (
'type' = 'table-store',
'root-path' = '/root-path/'
);
USE CATALOG table_store;
```
```
— create table dir: path '${db_name}.db/${table_name}'
— create schema file in table dir
CREATE TABLE T1 (
a INT,
b INT
);
— delete table dir
DROP TABLE T1;
```
```
— create table dir and …
```
> [FLINK-27755] Introduce a filesystem catalog for table store

- flink-table-store-e2e-tests/pom.xml
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/E2eTestBase.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/FileStoreBatchE2eTest.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/FileStoreStreamE2eTest.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/HiveE2eTest.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/LogStoreE2eTest.java
- flink-table-store-e2e-tests/src/test/resources-filtered/docker-compose.yaml
- flink-table-store-e2e-tests/src/test/resources/flink.env
- flink-table-store-e2e-tests/src/test/resources/hadoop-hive.env
- flink-table-store-e2e-tests/src/test/resources/log4j2-test.properties
To ensure that jar produced by flink-table-store-hive module can actually work in real Hive system we need to add end to end tests.
> [FLINK-27542] Add end to end tests for Hive to read external table store files

- flink-table-store-e2e-tests/pom.xml
- flink-table-store-hive/pom.xml
- flink-table-store-shade/pom.xml
- flink-table-store-spark/pom.xml
- pom.xml
For Hive and other readers, they currently need to shade a bunch of dependencies, which is not very friendly, we can have a common module, and connector depends on this one module.
> [FLINK-28106] Introduce flink-table-store-shade for the dependencies of connectors

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/AlterTableCompactITCase.java
It case is unstable, see https://github.com/apache/flink-table-store/runs/6985604079?check_suite_focus=true
The exception is caused by the empty list returned by `generateData`
> [hotfix] Fix SqlParserEOFException in AlterTableCompactITCase

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/SchemaManager.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/AtomicFileWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/AtomicFsDataOutputStream.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/FileStorePathFactory.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/FileUtils.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/MetaFileWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/RecoverableAtomicFileWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/RenamingAtomicFsDataOutputStream.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/SnapshotManager.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/AtomicFileWriterTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/MetaFileWriterTest.java
In FileStoreCommitImpl, currently, it uses `rename` to support atomic commit.
But this is not work for object store like S3. We can use RecoverableWriter to support atomic commit for object store.
We can introduce `AtomicFileWriter`:
- Use rename if createRecoverableWriter is not supported or the filesystem is FILE_SYSTEM
- Use RecoverableWriter if FileSystem supports createRecoverableWriter
> [FLINK-28066] Use FileSystem.createRecoverableWriter in FileStoreCommit

- flink-table-store-hive/src/main/java/org/apache/flink/table/store/SearchArgumentToPredicateConverter.java
- flink-table-store-hive/src/test/java/org/apache/flink/table/store/SearchArgumentToPredicateConverterTest.java
For example: `SLECT * FROM T WHERE a = 1 and ${unsupported_filters};`
According to the reasonable path, the condition `a=1` should be able to be pushed down to the table store, but currently the whole will throw `UnsupportedOperationException`, resulting in `a=1` not being pushed down.
> [FLINK-27897] SearchArgumentToPredicateConverter can now keep partial results and throw away unsupported filters

- flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/RowDataUtils.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/data/DataFileMeta.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/data/DataFileMetaSerializer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestFile.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreExpireImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/FileStorePathFactory.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/SerializationUtils.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/data/DataFileMetaSerializerTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreExpireTest.java
See [FLINK-28244](https://issues.apache.org/jira/browse/FLINK-28244)
```
class DataFileMeta {
String fileName;
.....
// store the name of extra files, extra files including changelog_file,
// primary_key_index_file,secondary_index_file, and etc...
List<String> extraFiles;
}
```
Extra files can help us for many uses, including index files, changelog files and etc...
> [FLINK-28255] Add extraFiles to DataFileMeta

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/AlterTableCompactITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/StoreSinkTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/TestFileStoreTable.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitGeneratorTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitReaderTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/TestChangelogDataReadWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/KeyValue.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/KeyValueSerializer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/FileKind.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestEntry.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestEntrySerializer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MemTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeReader.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/SortBufferMemTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogValueCountFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/ValueContentRowDataRecordIterator.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestKeyValueGenerator.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestFileMetaTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestTestDataGenerator.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/MergeTreeTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/MergeFunctionTestUtils.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreReadTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/ReusingTestData.java
In [FLINK-28244](https://issues.apache.org/jira/browse/FLINK-28244)
We need store changelog of a table, the row kind should contains UPDATE_BEFORE and UPDATE_AFTER, but if we use ValueKind, it dose not contain UPDATE kinds.
We can just use RowKind.
> [FLINK-28257] Replace ValueKind to RowKind in table store

- .scalafmt.conf
- flink-table-store-codegen/pom.xml
- flink-table-store-codegen/src/main/java/org/apache/flink/table/store/codegen/CodeGeneratorImpl.java
- flink-table-store-codegen/src/main/java/org/apache/flink/table/store/codegen/SortSpec.java
- flink-table-store-codegen/src/main/scala/org.apache.flink.table.store.codegen/CodeGenException.scala
- flink-table-store-codegen/src/main/scala/org.apache.flink.table.store.codegen/CodeGeneratorContext.scala
- flink-table-store-codegen/src/main/scala/org.apache.flink.table.store.codegen/ComparatorCodeGenerator.scala
- flink-table-store-codegen/src/main/scala/org.apache.flink.table.store.codegen/ExprCodeGenerator.scala
- flink-table-store-codegen/src/main/scala/org.apache.flink.table.store.codegen/GenerateUtils.scala
- flink-table-store-codegen/src/main/scala/org.apache.flink.table.store.codegen/GeneratedExpression.scala
- flink-table-store-codegen/src/main/scala/org.apache.flink.table.store.codegen/ProjectionCodeGenerator.scala
- flink-table-store-codegen/src/main/scala/org.apache.flink.table.store.codegen/SortCodeGenerator.scala
- flink-table-store-common/src/main/java/org/apache/flink/table/store/codegen/CodeGenerator.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/codegen/CodeGenUtils.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/SortBufferMemTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/KeyComparatorSupplier.java
- pom.xml
We currently have the table-planner bundled into flink-table-store-codegen, which causes:
- bundle jar is too big, 20+MB
- Dependence on planner code will make it difficult to be compatible with multiple versions of Flink
> [FLINK-28282] Planner free in flink-table-store-codegen

- flink-table-store-codegen/pom.xml
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/Equal.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/GreaterOrEqual.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/GreaterThan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/IsNotNull.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/IsNull.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/LessOrEqual.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/LessThan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/NotEqual.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/NullFalseLeafBinaryFunction.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/PredicateBuilder.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/PredicateConverter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/StartsWith.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/predicate/PredicateBuilderTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/predicate/PredicateConverterTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/predicate/PredicateTest.java
- flink-table-store-hive/flink-table-store-hive-connector/pom.xml
- flink-table-store-hive/flink-table-store-hive-connector/src/test/java/org/apache/flink/table/store/SearchArgumentToPredicateConverterTest.java
- flink-table-store-hive/flink-table-store-hive-connector/src/test/java/org/apache/flink/table/store/hive/TableStoreHiveStorageHandlerITCase.java
- flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SparkFilterConverterTest.java
- pom.xml
Previously predicate functions does not accept null literals. This limits the range of supported predicates.
This PR adds support for null literals in predicates. We can now support predicates containing null literals, including `in` predicate with nulls.
> [FLINK-28064] Predicate now accepts null literals

- flink-table-store-kafka/src/test/java/org/apache/flink/table/store/kafka/KafkaTableTestBase.java
Currently the tests don't not delete the topics, which causes that Kafka local cluster may reuse the data inside the topic that results in a test error.
- `KafkaTableTestBase#after()` adds the deletion of the topics for Kafka cluster.
> [FLINK-28335] Delete topic after tests

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/SortBufferMemTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/MergeFunctionHelper.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/SortMergeReader.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/ValueCountMergeFunction.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/MergeFunctionHelperTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/ReusingTestData.java
If there is just one record, still use `MergeFunction` to merge. This is not necessary, just output directly.
- Updates the merge in the `SortBufferMemTable` and `SortMergeReader` to output directly if there is only one record, and use `MergeFunction` to merge in the case of multiple records.
> [FLINK-27336] Avoid merging when there is only one record

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/BucketStreamPartitioner.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/TableSchema.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/SinkRecordConverter.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/sink/SinkRecordConverterTest.java
Specifies the table store distribution policy. Data is assigned to each bucket according to the hash value of bucket-key.
- It is primary key when table has primary key. The user can specify a bucket key, it should be part of primary keys.
- It is all fields when table has no primary key.
If there are filter conditions for specific fields, reasonable settings can give a big performance boost to the table, but care needs to be taken to avoid data skewing.
> [FLINK-28017] Introduce bucket-key to table store

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FlinkSourceBuilder.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/TableStoreSource.java
`TableStoreSource` could support to push down watermark, which should implement the interface `SupportsWatermarkPushDown`.
- `TableStoreSource` implements the `SupportsWatermarkPushDown` interface to apply the `WatermarkStrategy`.
> [FLINK-26936] Pushdown watermark to table store source

- docs/layouts/shortcodes/generated/catalog_configuration.html
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/FlinkCatalog.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/FlinkCatalogFactory.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreConnectorFactory.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/FlinkSinkBuilder.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreCommitter.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreSink.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/TableStoreSink.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/CatalogOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/Catalog.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/CatalogFactory.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/CatalogLock.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/FileSystemCatalog.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/FileSystemCatalogFactory.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/HiveCatalog.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/HiveCatalogFactory.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/HiveCatalogLock.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/SerializableHiveConf.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/test/java/org/apache/flink/table/store/hive/HiveCatalogITCase.java
In HiveCatalog, we can set CatalogLock.Factory to TableStoreSink to support multiple concurrency writers for object storage.
> [FLINK-28384][hive] Add CatalogLock support for HiveCatalog in table store

- flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/ProjectedRowData.java
- flink-table-store-hive/flink-table-store-hive-connector/src/main/java/org/apache/flink/table/store/mapred/TableStoreInputFormat.java
- flink-table-store-hive/flink-table-store-hive-connector/src/main/java/org/apache/flink/table/store/mapred/TableStoreInputSplit.java
- flink-table-store-hive/flink-table-store-hive-connector/src/main/java/org/apache/flink/table/store/mapred/TableStoreRecordReader.java
- flink-table-store-hive/flink-table-store-hive-connector/src/test/java/org/apache/flink/table/store/hive/TableStoreHiveStorageHandlerITCase.java
- flink-table-store-hive/flink-table-store-hive-connector/src/test/java/org/apache/flink/table/store/mapred/TableStoreRecordReaderTest.java
As Hive 2 only provides selected column names and requires the source not to change the schema, we implement projection pushdown by only reading selected columns from files and set the other columns to null.
> [FLINK-28110] Support projection pushdown for Hive readers

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/AbstractTableStoreFactory.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/PrepareCommitOperator.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreCompactOperator.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreWriteOperator.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/AlterTableCompactITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/AppendOnlyTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ForceCompactionITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitReaderTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/TestChangelogDataReadWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/data/AppendOnlyWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/writer/RecordWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/AbstractTableWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/TableWrite.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/data/AppendOnlyWriterTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/MergeTreeTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/TestCommitThread.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/AppendOnlyFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogValueCountFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/FileStoreTableTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/WritePreemptMemoryTest.java
- flink-table-store-hive/flink-table-store-hive-connector/src/test/java/org/apache/flink/table/store/hive/TableStoreHiveStorageHandlerITCase.java
- flink-table-store-hive/flink-table-store-hive-connector/src/test/java/org/apache/flink/table/store/mapred/TableStoreRecordReaderTest.java
- flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SimpleTableTestHelper.java
Under batch mode, the framework should always synchronize the compaction result before committing, and it is annoying to let users set this value to true.
> [FLINK-28465] Wait compaction finished in endInput

- docs/content/docs/engines/build.md
- docs/content/docs/engines/spark2.md
- docs/content/docs/engines/trino.md
- flink-table-store-spark2/pom.xml
- flink-table-store-spark2/src/main/java/org/apache/flink/table/store/spark/SparkArrayData.java
- flink-table-store-spark2/src/main/java/org/apache/flink/table/store/spark/SparkDataSourceReader.java
- flink-table-store-spark2/src/main/java/org/apache/flink/table/store/spark/SparkFilterConverter.java
- flink-table-store-spark2/src/main/java/org/apache/flink/table/store/spark/SparkInputPartition.java
- flink-table-store-spark2/src/main/java/org/apache/flink/table/store/spark/SparkInternalRow.java
- flink-table-store-spark2/src/main/java/org/apache/flink/table/store/spark/SparkSource.java
- flink-table-store-spark2/src/main/java/org/apache/flink/table/store/spark/SparkTypeUtils.java
- flink-table-store-spark2/src/main/java/org/apache/flink/table/store/spark/SpecializedGettersReader.java
- flink-table-store-spark2/src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister
- flink-table-store-spark2/src/test/java/org/apache/flink/table/store/spark/SimpleTableTestHelper.java
- flink-table-store-spark2/src/test/java/org/apache/flink/table/store/spark/SparkFilterConverterTest.java
- flink-table-store-spark2/src/test/java/org/apache/flink/table/store/spark/SparkInternalRowTest.java
- flink-table-store-spark2/src/test/java/org/apache/flink/table/store/spark/SparkReadITCase.java
- flink-table-store-spark2/src/test/java/org/apache/flink/table/store/spark/SparkTypeTest.java
- flink-table-store-spark2/src/test/resources/log4j2-test.properties
- pom.xml
Flink Table Store supports Spark3 reader at present. Spark2 reader is introduced to support for Spark 2.X version to read storage of FileStore.
Supports Spark 2+:
- Introduces `SparkTypeUtils`.
- Introduces `SparkInternalRow`.
- Introduces `SparkSource`.
> [FLINK-28289] Introduce Spark2 Reader for table store

- flink-table-store-connector/src/main/1.15.0/org/apache/flink/table/store/connector/TableStoreManagedFactory.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/AlterTableCompactITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TableStoreManagedFactoryTest.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/data/AppendOnlyCompactManager.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AppendOnlyFileStoreWrite.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/data/AppendOnlyCompactManagerTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/data/IterativeCompactTaskTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/data/RollingCompactTaskTest.java
Compact tasks differ between auto-compact and "ALTER TABLE ... COMPACT"
- auto-compact task will pick the first qualified candidates to rewrite, and the AppendOnlyWriter must invoke the next compaction.
- "ALTER TABLE ... COMPACT" will perform a whole scan of the input, and within one task, there might be multiple times of rewrite happens.
> [FLINK-28108] Support "ALTER TABLE ... COMPACT" for append-only table

- docs/content/docs/engines/overview.md
- flink-table-store-spark/pom.xml
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkCatalog.java
- flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SparkTypeTest.java
flink-table-store-spark module support Spark 3.0~3.2 profile, which has published the Spark 3.3.0 version. Spark 3.3 profile can be introduced for SparkSource to follow the release version of Spark 3.
- Introduces the `dropNamespace(namespace, cascade)` implementation for Spark 3.3+ version from [47cf](https://github.com/apache/spark/commit/ec5d2a76a55a4094d7bb48788a917145d81d47cf).
Verified the spark-3.3 profile with `mvn clean install -Pspark-3.3`. The result of the tests is as follows:
> [FLINK-28560] Support Spark 3.3 profile for SparkSource

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/ArrayDataType.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/DataFieldSerializer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/MapDataType.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/MultisetDataType.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/RowDataType.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/TableSchema.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/schema/TableSchemaSerializationTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/schema/TableSchemaTest.java
Fix the nullability loss for `ArrayDataType`, `MultisetDataType`, `MapDataType` and `RowDataType`
> [FLINK-28573] Nested type will lose nullability when converting from TableSchema

- flink-table-store-spark/pom.xml
CVE-2022-33891: Apache Spark shell command injection vulnerability via Spark UI. Upgrade to supported Apache Spark maintenance release 3.1.3, 3.2.2 or 3.3.0 or later.
- Upgrade Spark version of flink-table-store-spark from 3.2.1 to 3.2.2.
> [FLINK-28578] Upgrade Spark version of flink-table-store-spark to 3.2.2

- docs/content/docs/engines/spark.md
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AppendOnlyFileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/SchemaChange.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/stats/BinaryTableStats.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/stats/FieldStatsArraySerializer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/RecordReaderUtils.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/SchemaEvolutionTest.java
The currently added column, if there is a filter on it, will cause an error in the RowDataToObjectArrayConverter because the number of columns is not correct
We can make BinaryTableStats supports evolution from shorter rowData.
> [FLINK-28579] Supports predicate testing for new columns

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreSink.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/AbstractFileStore.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/AppendOnlyFileStore.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/KeyValueFileStore.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/data/DataFileWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestEntry.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AbstractFileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommit.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreExpireImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/SnapshotManager.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/TableCommit.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/TestCommitThread.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/TestAtomicRenameFileSystem.java
Currently `FileStoreCommitImpl` only checks for conflicts by checking the files we're going to delete (due to compaction) are still there.
However, consider two jobs committing into the same LSM tree at the same time. For their first compaction no conflict is detected because they'll only delete their own level 0 files. But they will both produce level 1 files and the key ranges of these files may overlap. This is not correct for our LSM tree structure.
This PR fixes this issue.
> [FLINK-28582] Check LSM tree structure when multiple jobs are committing into the same bucket

- flink-table-store-common/src/main/java/org/apache/flink/table/store/file/predicate/LeafPredicate.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/predicate/PredicateTest.java
Now there will be a NPE if minValue or maxValue of FieldStats is null.
We can know the stats is unknown in LeafPredicate.test(long rowCount, FieldStats[] fieldStats), and return true directly.
> [FLINK-28580] Predicate supports unknown stats

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/CommitterOperator.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/CommitterOperatorTest.java
Currently snapshots are committed in `notifyCheckpointComplete`. If the job fails between a successful checkpoint and the call of `notifyCheckpointComplete`, these snapshots will be committed after job restarts.
However when the writer starts they also need to read from the latest snapshot (to build the latest structure of LSM tree). These two steps may happen concurrently and what the writers see may not be the latest snapshot.
To fix this problem, we can throw exception intentionally after new snapshots are committed during restore. In this way the job will be forcefully restarted and it is very likely that the writers can see the latest snapshot.
> [FLINK-28605] Throw exception intentionally when new snapshots are committed during restore

- flink-table-store-hive/flink-table-store-hive-catalog/src/main/resources/META-INF/NOTICE
`NOTICE` file is need to be created for `flink-table-store-hive-catalog`.
- Introduces the `NOTICE` file in `flink-table-store-hive-catalog`.
> [FLINK-28565] Create `NOTICE` file for `flink-table-store-hive-catalog`

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/AbstractTableStoreFactory.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreConnectorFactory.java
Using Flink 1.14. Temporary table in table store catalog will use the Factory provided by catalog.
We need to do some delegate work like HiveDynamicTableFactory.
> [FLINK-28642] Cannot create sink for Temporary table in table store catalog

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/compact/CompactManager.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/data/AppendOnlyWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeWriter.java
Currently when cancelling a job, we have to wait for current compaction thread to finish. If the compaction takes too long, the task manager may fail due to job cancelling takes more than 180 seconds.
> [FLINK-28662] Compaction should not block job cancelling

- docs/content/docs/engines/spark2.md
DDL is not supported. Spark2 just support:
```
spark.read().format("tablestore").load("file:/tmp/warehouse/default.db/myTable")
```
> [FLINK-28670] Documentation of spark2 is wrong

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/PredicateITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/BucketSelector.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/SinkRecordConverter.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/predicate/BucketSelectorTest.java
The calculation of bucket should be `Math.abs(hashcode % numBucket)` instead of `hashcode % numBucket`.
> [FLINK-28687] BucketSelector is wrong when hashcode is negative

- docs/content/docs/development/streaming-query.md
- docs/layouts/shortcodes/generated/core_configuration.html
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ContinuousFileStoreITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreWrite.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/MergeTreeTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTableTest.java
The changelog-file is limited, not just from input, we can have more changelog producer types.
> [FLINK-28683] Modify changelog-file to changelog-producer

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/AbstractTableStoreFactory.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/AbstractTableStoreFactoryTest.java
Skip comments comparison when building FileStoreTable
> [FLINK-28686] Spark table with column comment cannot be read/write by Flink

- NOTICE
- flink-table-store-hive/flink-table-store-hive-catalog/src/main/resources/META-INF/NOTICE
Copyright year of the NOTICE files in Flink Table Store need to be updated to `2014-2022`.
- Updates copyright year of the NOTICE files to `2014-2022`.
> [FLINK-28705] Update copyright year to 2014-2022 in NOTICE files

- flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/RowDataToObjectArrayConverter.java
- flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/RowDataUtils.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/KeyValue.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/stats/FieldStatsArraySerializer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/RowDataPartitionComputer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTable.java
- flink-table-store-hive/flink-table-store-hive-connector/src/main/java/org/apache/flink/table/store/hive/objectinspector/TableStoreRowDataObjectInspector.java
- flink-table-store-hive/flink-table-store-hive-connector/src/test/java/org/apache/flink/table/store/hive/TableStoreHiveStorageHandlerITCase.java
- flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogDeserializationSchema.java
Table Store Hive connector implement projection pushdown by reading desired fields and setting other unread fields to null. However the nullability of primary key fields are not null, so `RowData.FieldGetter` will not check for null values for these types. This may cause exception when primary key fields are not selected and are set to null.
> [FLINK-28717] Add null checking for all field getters

- flink-table-store-connector/src/main/1.14.5/org/apache/flink/table/store/connector/utils/StreamExecutionEnvironmentUtils.java
- flink-table-store-connector/src/main/1.15.0/org/apache/flink/table/store/connector/utils/StreamExecutionEnvironmentUtils.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreSink.java
We can't get configurations from `DummyStreamExecutionEnvironment` in Flink 1.14 (this is fixed by FLINK-26709 in Flink 1.15) so we have to use Java reflection to check if this execution environment is for batch job or for streaming job.
> [FLINK-28700] Table store sink fails to commit for Flink 1.14 batch job

- docs/content/docs/engines/hive.md
- flink-table-store-hive/flink-table-store-hive-connector/pom.xml
- flink-table-store-hive/flink-table-store-hive-connector/src/main/java/org/apache/flink/table/store/mapred/TableStoreInputFormat.java
- flink-table-store-hive/flink-table-store-hive-connector/src/test/java/org/apache/flink/table/store/hive/TableStoreHiveStorageHandlerITCase.java
Table Store Hive connector is supposed to support both MR and Tez engine. However current tests only runs on MR. We need to add Tez tests.
> [FLINK-28730] Add Tez execution engine test for Table Store Hive connector

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/data/AppendOnlyReader.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/data/DataFileReader.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/FileUtils.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/data/DataFileTest.java
When reading a file, if it is found that the file does not exist, it directly throws a file not found exception, which is often difficult for users to understand.
We can make it more clear in the exception message, e.g.
The file cannot be found, this may be because the read is too slow and the previous snapshot expired, you can configure a larger snapshot.time-retained or speed up your read.
```
Caused by: java.io.FileNotFoundException: File does not exist:
at org.apache.flink.table.store.file.utils.FileUtils.getFileSize(FileUtils.java:94) ~[flink-table-store-dist-0.2.jar:0.2-SNAPSHOT]
at org.apache.flink.table.store.file.data.DataFileReader$DataFileRecordReader.<init>(DataFileReader.java:86) ~[flink-table-store-dist-0.2.jar:0.2-SNAPSHOT]
```
> [FLINK-28715] Throw better exception when file not found in reading

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSource.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSourceReader.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitReader.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FlinkSourceBuilder.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/TableStoreSource.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/FileStoreSourceReaderTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitReaderTest.java
`FileStoreSource` could support for the `SupportsLimitPushDown` interface.
- `FileStoreSource` implements the `SupportsLimitPushDown` interface.
> [FLINK-28727] Flink Source supports `SupportsLimitPushDown`

- flink-table-store-benchmark/pom.xml
Currently the benchmark module does not have a correct NOTICE file. However this module does not need to be released, so we can just skip its deployment.
> [FLINK-28665] Disable deployment of table store benchmark module

- docs/content/docs/engines/hive.md
- flink-table-store-e2e-tests/pom.xml
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/E2eTestBase.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/HiveE2eTest.java
- flink-table-store-e2e-tests/src/test/resources-filtered/docker-compose.yaml
Current table store Hive document states that, to enable support in Hive, we should use ADD JAR statement to add hive connector jar.
However some types of queries, for example join statements in MR engine, may still throw ClassNotFound exception. The correct way to enable table store support is to create an auxlib directory under the root directory of Hive and copy jar into that directory.
> [FLINK-28760] Enable table store support in Hive by creating auxlib directory

- docs/content/docs/engines/build.md
Flink Table Store can not be built with Java 11, but the "[build from source](https://nightlies.apache.org/flink/flink-table-store-docs-master/docs/engines/build)" instructions don't mention this restriction.
- Add the instructions of built with Java 11 in `build.md`.
> [FLINK-28754] Document that Java 8 is required to build table store

- .github/workflows/publish_snapshot.yml
It is better to publish the Maven artifacts, so that downstream Java projects can use this.
> [FLINK-28794] Publish flink-table-store snapshot artifacts

- docs/content/docs/development/roadmap.md
The Flink Table Store subproject needs its own roadmap document to present an overview of the general direction.
- Introduces roadmap document `roadmap.md` of Flink Table Store.
> [FLINK-28840] Introduce roadmap document of Flink Table Store

- flink-table-store-dist/pom.xml
- flink-table-store-hive/flink-table-store-hive-catalog/pom.xml
flink-table-store-hive-catalog could not shade hive-shims-0.23 because `artifactSet` doesn't include `hive-shims-0.23` and the `hive-shims-0.23` isn't specifically included with filters
- The `filters` and `artifactSet` of flink-table-store-hive-catalog module includes the `hive-shims-0.23`.
> [FLINK-28903] flink-table-store-hive-catalog could not shade hive-shims-0.23

- docs/content/docs/engines/spark3.md
- Modify _Spark_ in "engine" documentation to _Spark3_.
- Optimizing Spark documentation about engines.
- This change is a trivial rework / code cleanup without any test coverage.
> [hotfix][docs] Optimizing Spark documentation about engines.

- docs/layouts/shortcodes/generated/core_configuration.html
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/TableStoreSource.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
There are many jobs that do not require a downstream normalize node, and the key is that the node has a very large cost.
Introduce a option:
Whether to force the removal of the normalize node when streaming read. Note: This is dangerous and is likely to cause data errors if downstream is used to calculate aggregation.
> [FLINK-29070] Provide a option to force the removal of the normalize node when streaming read

- .github/workflows/build-different-versions.yml
- docs/content/docs/engines/build.md
- docs/content/docs/engines/hive.md
- docs/content/docs/engines/overview.md
- flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/SerializableHiveConf.java
- flink-table-store-hive/pom.xml
Currently Table Store Hive catalog and connectors cannot run against Hive 2.1 CDH 6.3. We should fix this support.
> [FLINK-29071] Fix Table Store Hive CDH support

- docs/content/docs/development/create-table.md
Without the explicit cast, the SQL will throw the exception like 
```
[ERROR] Could not execute SQL statement. Reason:
org.apache.calcite.sql.validate.SqlValidatorException: Illegal use of 'NULL'
```
> [hotfix] Fix the partial update SQL example

- docs/layouts/shortcodes/generated/flink_connector_configuration.html
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/AbstractTableStoreFactory.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/FlinkConnectorOptions.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TableStoreTestBase.java
Now log.system default value is null, it can not be configured by dynamic option.
We can let default value is 'none'.
> [FLINK-29181] log.system can be congiured by dynamic options

- flink-table-store-common/src/main/java/org/apache/flink/table/store/format/FileFormat.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/FileStoreSourceReaderTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitReaderTest.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/data/DataFileReader.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeReader.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AppendOnlyFileStoreRead.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreRead.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/SchemaManager.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTable.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/data/DataFileTestUtils.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/format/FileStatsExtractingAvroFormat.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/format/FlushingFileFormat.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreExpireTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreReadTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreScanTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/AppendOnlyFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTableTest.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/avro/AvroFileFormat.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/orc/OrcFileFormat.java
As an improvement, value filters can be pushed down when generated splits do not have key range overlap.
> [FLINK-29129] Try best to push down value filters

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/SortBufferMemTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/DeduplicateMergeFunction.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/MergeFunction.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/MergeFunctionHelper.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/PartialUpdateMergeFunction.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/SortMergeReader.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/ValueCountMergeFunction.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/MergeFunctionHelperTestBase.java
We should pass KeyValue to MergeFunction, give MergeFunction more capabilities, such as throwing an exception when it sees an unreasonable RowKind.
> [FLINK-29189] Pass KeyValue to MergeFunction

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/BatchFileStoreITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/TableCommit.java
There is currently no data, which will not trigger an overwrite, which causes the semantics of the sql to not be correct
> [FLINK-29241] Can not overwrite from empty input

- docs/content/docs/development/write-table.md
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/memory/MemoryPoolFactory.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/memory/MemoryPoolFactoryTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/WritePreemptMemoryTest.java
When there are many partitions, the partition writer will seize memory and may have the memory not enough exceptions.
We need to make sure that the writer has enough memory before it can start.
Actually, there is enough memory, because it can preempt from other writers. The problem is in `OwnerMemoryPool.freePages`, it should contain preemptable memory.
> [FLINK-29273] Page not enough Exception in SortBufferMemTable

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/Increment.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/AbstractTableWrite.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/FileStoreTableTestBase.java
In AbstractTableWrite, the Writer is cleaned up as soon as no new files are generated, which may lead to the changes generated after the compaction have not been committed, but the new data from the next checkpoint comes to create a new writer, which conflicts with the changes generated in the next round of checkpoint and the previous round, resulting in an exception:
```
Caused by: java.lang.IllegalStateException: Trying to delete file {org.apache.flink.table.data.binary.BinaryRowData@5759f99e, 0, 0, data-7bf2498e-d0a1-42a5-97b7-b3860f10b076-0.orc} which is not previously added. Manifest might be corrupted.
```
> [FLINK-29295] Clear RecordWriter slower to avoid causing frequent compaction conflicts

- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/orc/OrcBulkWriterFactory.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/orc/OrcFileFormat.java
- flink-table-store-format/src/test/java/org/apache/flink/table/store/format/orc/OrcBulkWriterFactoryTest.java
- flink-table-store-format/src/test/java/org/apache/flink/table/store/format/orc/OrcFileFormatTest.java
Currently `OrcFileFormat` will create new `org.apache.hadoop.conf.Configuration` instance in methods `createReaderFactory` and `createWriterFactory`. The initialization of `org.apache.hadoop.conf.Configuration` tries to load local file `core-site.xml`. 
This PR will initialize the `writerConf` and `readerConf` of `org.apache.hadoop.conf.Configuration` and reuse them in `createReaderFactory` and `createWriterFactory`.
> [FLINK-29345] Create reusing reader/writer config in orc format

- flink-table-store-common/src/test/java/org/apache/flink/table/store/format/FileStatsExtractorTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/AppendOnlyFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogValueCountFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/FileStoreTableTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/WritePreemptMemoryTest.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/orc/OrcFileFormat.java
- flink-table-store-format/src/test/java/org/apache/flink/table/store/format/orc/OrcFileStatsExtractorTest.java
`BINARY` type is not supported in table store for `OrcFileFormat`.
- Adds the `BINARY` type support for `OrcFileFormat`.
> [FLINK-29278] BINARY type is not supported in table store

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/SchemaManager.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/SchemaEvolutionTest.java
When we execute AddColumn ddl, we should check whether the column name is exist. Otherwise, the ddl will be successful and the job reads this table will create source of flink store table failed.
> [FLINK-29385] Verify duplicate column names for AddColumn

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
When the job runs to checkpoint N, if the user recovers from an old checkpoint (such as checkpoint N-5), the sink of the current FTS will cause a manifest corruption because duplicate files may be committed.
We should avoid such corruption, and the storage should be robust enough.
> [FLINK-29367] FileStoreCommitImpl also checks for conflicts when committing append changes

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/memory/MemoryPoolFactory.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/memory/sort/BinaryInMemorySortBuffer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/SortBufferMemTable.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/SortBufferMemTableTestBase.java
Currently when we flush all memory in `SortBufferMemTable` and call the `clear` method to release memory, `BinaryInMemorySortBuffer` in `SortBufferMemTable` will keep one page. 
We should release all memory in `BinaryInMemorySortBuffer` and initialize it before we write data to or read data from it. The main changes are as follows
1. Add `clear` method to release all the memory segments
2. Add `tryInitialize` method to initialize the `BinaryInMemorySortBuffer` if it is used after `clear`
3. Add `tryInitialize` in `write` and `getIterator` to ensure that the `BinaryInMemorySortBuffer` is initialized
The `BinaryInMemorySortBuffer` class will be tested by exist test case `SortBufferMemTableTestBase`
> [FLINK-29276] BinaryInMemorySortBuffer supports to clear all memory segments

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/Committable.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/CommittableSerializer.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/CommitterOperator.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/PrepareCommitOperator.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreCompactOperator.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreWriteOperator.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/CommittableSerializerTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/CommitterOperatorTest.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/Increment.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/FileCommittable.java
- flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SparkReadITCase.java
After checkpoint abort, the files in cp5 may fall into cp6, because the compaction commit is deleted first and then added, which may lead to:
- Delete a file
- Add the same file again
This causes the deleted file not to be found.
We should reasonably distinguish files of different checkpoints in the committer.
> [FLINK-29369] Commit delete file failure due to Checkpoint aborted

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/io/RollingFileWriter.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/data/AppendOnlyWriterTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/io/RollingFileWriterTest.java
It is expensive for LocalFileSystem to do so, so it is changed to check the length per 1000 records to decide whether to roll the file.
> [FLINK-29342] Do not query writer.length() per record in RollingFileWriter

- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/ConnectionsFileSystem.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/TestAtomicRenameFileSystem.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/TraceableFileSystem.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/FileStoreTableTestBase.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/fs/HadoopReadOnlyFileSystem.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/orc/OrcFileStatsExtractor.java
1. OrcFileStatsExtractor forget closing reader.
2. HadoopReadOnlyFileSystem forget closing fsDataInputStream.
We need a pocket test to assert all connections are closed.
> [FLINK-29412] Connection leak in orc reader

- flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/ReflectionUtils.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/parquet/ParquetInputFormatFactory.java
ParquetInputFormatFactory should check the method's parameter count to decide which version to invoke.
> [FLINK-29506] ParquetInputFormatFactory fails to create format on Flink 1.14

- .github/workflows/e2e-tests.yml
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/E2eTestBase.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/FileStoreBatchE2eTest.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/FileStoreBuiltInFormatE2eTest.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/FileStoreStreamE2eTest.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/HiveE2eTest.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/LogStoreE2eTest.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/TypeE2eTest.java
- flink-table-store-e2e-tests/src/test/resources/flink.env
- pom.xml
- Get rid of `ManagedTableFactory`
- Use Kafka connector to replace filesystem connector, since for Flink 1.14, [File system sources for streaming is still under development. In the future, the community will add support for common streaming use cases, i.e., partition and directory monitoring](https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/connectors/table/filesystem/)
> [FLINK-29149] Migrate E2E tests to catalog-based and enable E2E tests for Flink 1.14

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/KeyValue.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/KeyValueFileStore.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MemTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeReader.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/SortBufferMemTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/DeduplicateMergeFunction.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/MergeFunction.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/MergeFunctionHelper.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/PartialUpdateMergeFunction.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/SortMergeReader.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/ValueCountMergeFunction.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/aggregate/AggregateMergeFunction.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreRead.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogValueCountFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTable.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/SortBufferMemTableTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/MergeFunctionHelperTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/SortMergeReaderTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreReadTest.java
`MergeFunction` of full compaction need to produce changelogs instead of single `KeyValue`. We need to modify MergeFunction into a generic class.
> [FLINK-29292] Make result of MergeFunction generic

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/LogSystemITCase.java
- flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogSinkProvider.java
- flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogSourceProvider.java
- flink-table-store-kafka/src/test/java/org/apache/flink/table/store/kafka/KafkaLogITCase.java
```
"CREATE TABLE T (i INT, j INT) WITH ("
+ "'log.system'='kafka', "
+ "'write-mode'='append-only', "
+ "'log.consistency'='eventual', "
+ "'kafka.bootstrap.servers'='%s', "
+ "'kafka.topic'='T')",
```
Above DDL table should work.
> [FLINK-29621] Append-only with eventual log.consistency can not work

- docs/layouts/shortcodes/generated/core_configuration.html
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/PartialUpdateITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/PartialUpdateMergeFunction.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTable.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTableTest.java
When the partial update input is a normal database cdc input, it can work normally as long as there is no delete data.
However, if a join is performed previously, the join node in flink job will generate delete messages, which will cause the partial update insertion to throw an exception.
We can add an option to decide whether to ignore the delete message in this case.
> [FLINK-29554] Add partial-update.ignore-delete option to avoid exception after join

- flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/HiveCatalog.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/test/java/org/apache/flink/table/store/hive/HiveCatalogITCase.java
`listTables` in `HiveCatalog` should only return table store tables, which should filter the Hive tables with input and output format.
- `HiveCatalog#listTables` filters the Hive tables to check whether the input format is `org.apache.flink.table.store.mapred.TableStoreInputFormat` and the output format is `org.apache.flink.table.store.mapred.TableStoreOutputFormat`.
> [FLINK-29690] listTables in HiveCatalog should only return table store tables

- docs/layouts/shortcodes/generated/core_configuration.html
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreWriteOperator.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/LargeDataITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/io/KeyValueDataFileWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/io/KeyValueFileWriterFactory.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/SortBufferWriteBuffer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/WriteBuffer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/UniversalCompaction.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AbstractFileStoreWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/sort/BinaryExternalSortBuffer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/sort/BinaryInMemorySortBuffer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/sort/SortBuffer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/AbstractTableWrite.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/io/KeyValueFileReadWriteTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/MergeTreeTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/SortBufferWriteBufferTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/UniversalCompactionTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/sort/BinaryExternalSortBufferTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/sort/IntNormalizedKeyComputer.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/sort/IntRecordComparator.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTableTest.java
Column format and remote DFS may greatly affect the performance of compaction. We can change the writeBuffer to spillable to improve the performance. In this way, at least one checkpoint will not result in a remote column file based compression.
This PR:
- `MergeTreeWriter` can output rolling level0 files, because after the writeBuffer can spill, we should avoid too big file in level0. 
- Let `UniversalCompaction` not output level 0 result, because after the writeBuffer can spill, multiple level0 files will be generated, which may lead to useless work done by the compaction. We adjust the outputLevel to at least level1, which can ensure that the compaction must be effective.
- Rename MemTable to WriteBuffer, it can spill now.
- Introduce `BinaryExternalSortBuffer`.
- Adjust …
> [FLINK-29586] Let write buffer spillable

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/memory/sort/BinaryInMemorySortBuffer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/SortBufferMemTable.java
In SortBufferMemTable, it will use `BinaryInMemorySortBuffer.createBuffer(BinaryRowDataSerializer serializer)`, the serializer is for full row, not just sort key fields.
Problems may occur when there are many fields.
The test does not reproduce the problem because special conditions are required to trigger the problem.
This problem is completely avoided at the code parameter level.
> [FLINK-29700] Serializer to BinaryInMemorySortBuffer is wrong

- docs/content/docs/development/create-table.md
- docs/layouts/shortcodes/generated/core_configuration.html
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/TableStoreConnectorFactory.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/MappingTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TemporaryTableITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
Add a `createTableIfNeeded` in `TableStoreConnectorFactory`.
When use:
```
CREATE TEMPORARY TABLE T (
i INT,
j INT
) WITH (
'connector'='table-store', 
'path'='...'
)
```
Create underly table schema in FileSystem if needed.
> [FLINK-29252] Support create table-store table with 'connector'='table-store'

- .github/workflows/build-different-versions.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/publish_snapshot.yml
- .github/workflows/utcase-itcase.yml
- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
Maven Wrapper is to solve the problem that the project is built with different versions of Maven. Through the maven wrapper, the maven environment used by the current project construction can be stored.
Advantages: 
1. The maven version used by the unified project 
2. The local machine does not need to install the maven environment
> Add maven wrapper

- flink-table-store-benchmark/flink-table-store-cluster-benchmark/pom.xml
- flink-table-store-benchmark/flink-table-store-micro-benchmarks/README.md
- flink-table-store-benchmark/flink-table-store-micro-benchmarks/pom.xml
- flink-table-store-benchmark/flink-table-store-micro-benchmarks/src/main/java/org/apache/flink/table/store/benchmark/config/ConfigUtil.java
- flink-table-store-benchmark/flink-table-store-micro-benchmarks/src/main/java/org/apache/flink/table/store/benchmark/config/FileBenchmarkOptions.java
- flink-table-store-benchmark/flink-table-store-micro-benchmarks/src/main/java/org/apache/flink/table/store/benchmark/file/mergetree/MergeTreeBenchmark.java
- flink-table-store-benchmark/flink-table-store-micro-benchmarks/src/main/java/org/apache/flink/table/store/benchmark/file/mergetree/MergeTreeReaderBenchmark.java
- flink-table-store-benchmark/flink-table-store-micro-benchmarks/src/main/java/org/apache/flink/table/store/benchmark/file/mergetree/MergeTreeWriterBenchmark.java
- flink-table-store-benchmark/flink-table-store-micro-benchmarks/src/main/resources/benchmark-conf.yaml
- flink-table-store-benchmark/flink-table-store-micro-benchmarks/src/main/resources/log4j.properties
- flink-table-store-benchmark/pom.xml
In this PR we create `flink-table-store-micro-benchmarks` module in `flink-table-store-benchmark`, and add merge tree reader/writer benchmarks:
1.  In `MergeTreeReaderBenchmark` we first create a writer to write about 50*50000 records to the store, and performance the latency of scan in reader. 
2. In `MergeTreeWriterBenchmark` we performance the throughput of write in merge tree with compaction
> [FLINK-29702] Add micro benchmarks module and merge tree reader/writer benchmarks

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/RescaleBucketITCase.java
`RescaleBucketITCase#testSuspendAndRecoverAfterRescaleOverwrite` fails due to some expected records in table `T4` does not appear in table `T3`. This is because `stopJobSafely` method does not wait for job to fully shut down.
> [FLINK-29075] Fix table store unstable test RescaleBucketITCase#testSuspendAndRecoverAfterRescaleOverwrite

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/PreAggregationITCase.java
`PreAggregationITCase.LastValueAggregation` and `PreAggregationITCase.LastNonNullValueAggregation` need to make sure that the order of input data is determined. However the default parallelism of `FileStoreTableITCase` is 2, so the order of input data might change across tests.
> [FLINK-29773] Fix table store unstable tests PreAggregationITCase

- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/TestCommitThread.java
`FileStoreCommitTest` may stuck because the `FileStoreCommit` in `TestCommitThread` does not commit APPEND snapshot when no new files are produced. In this case, if the following COMPACT snapshot conflicts with the current merge tree, the test will stuck.
> [FLINK-29792] Fix unstable test FileStoreCommitTest which may stuck

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreCommitter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/Snapshot.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestCommittable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestCommittableSerializer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/metadata/SnapshotsTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/TableCommit.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestCommittableSerializerTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/TestCommitThread.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/AppendOnlyFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogValueCountFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/FileStoreTableTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/SchemaEvolutionTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/WritePreemptMemoryTest.java
- flink-table-store-hive/flink-table-store-hive-connector/src/test/java/org/apache/flink/table/store/hive/TableStoreHiveStorageHandlerITCase.java
- flink-table-store-hive/flink-table-store-hive-connector/src/test/java/org/apache/flink/table/store/mapred/TableStoreRecordReaderTest.java
- flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SimpleTableTestHelper.java
- flink-table-store-spark2/src/test/java/org/apache/flink/table/store/spark/SimpleTableTestHelper.java
Currently `commitIdentifier` in `Snapshot` is a `String` value. However there are many scenarios where we need to compare two identifiers to find out which one is newer. For example
* In FLINK-29840, we need to store the latest modified commit for each writer. Only when the latest snapshot is newer than this commit can we safely close the writer.
* In FLINK-29805, we can read the commit identifier of the latest snapshot. All identifiers older than that should be filtered out.
* In FLINK-29752, we need to trigger full compaction once in a few commits. We can read the latest commit identifier and compare it with the full compaction identifier to check if full compaction is successfully committed.
 
> [FLINK-29842] Change commitIdentifier in Table Store snapshot to long value

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreExpireImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/SnapshotManager.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreExpireTest.java
Table Store sink continuously fails with "Trying to add file which is already added" when snapshot committing is slow.
This is due to a bug in `FileStoreCommitImpl#filterCommitted`. When this method finds an identifier, it removes the identifier from a map. However different snapshots may have the same identifier (for example an APPEND commit and the following COMPACT commit will have the same identifier), so we need to use another set to check for identifiers.
When snapshot committing is fast there is at most 1 identifier to check after the job restarts, so nothing happens. However when snapshot committing is slow, there will be multiple identifiers to check and some identifiers will be mistakenly kept.
> [FLINK-29805] Fix incorrect snapshot filter when snapshots are committing too slow

- docs/content/docs/development/write-table.md
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreSink.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/CatalogITCaseBase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/CompositePkAndMultiPartitionedTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/LookupJoinITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/MappingTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ReadWriteTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ReadWriteTableTestBase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/StreamingWarehouseITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TableEnvironmentTestUtils.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/TableStoreTestBase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/SinkSavepointITCase.java
- flink-table-store-kafka/src/test/java/org/apache/flink/table/store/kafka/KafkaTableTestBase.java
Currently table store sink does not support unaligned checkpoint or at least once checkpoint mode, but no exception is explicitly thrown. We should throw exception so that users can change their configurations.
> [FLINK-29876] Explicitly throw exception from Table Store sink when unaligned checkpoint is enabled or at least once checkpoint mode is used

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/Levels.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/LevelsTest.java
Current constructor of `Levels` class contains the following code:
```java
this.level0 = new TreeSet<>(Comparator.comparing(DataFileMeta::maxSequenceNumber).reversed());
```
However when two or more jobs writing the same bucket, they may produce files containing the same sequence number. If two files have the same `maxSequenceNumber`, one of them will be mistakenly ignored by `TreeSet`.
> [FLINK-29916] Fix bug that Levels in Table Store may mistakenly ignore level 0 files when two files have the same sequence number

- docs/layouts/shortcodes/generated/kafka_log_configuration.html
- flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogOptions.java
Just add a missing period about description of "kafka.bootstrap.servers".
> [FLINK-29924] Fix missing a period in the description of kafka.bootstrap.servers.

- flink-table-store-common/src/test/java/org/apache/flink/table/store/format/FileStatsExtractorTestBase.java
Fix `FileStatsExtractorTestBase` when the `numRows` is zero
> [FLINK-29930] Fix FileStatsExtractorTestBase test case

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/CommitterOperator.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StateUtils.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreSink.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreWriteOperator.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ChangelogWithKeyFileStoreTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/CommitterOperatorTest.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/AbstractFileStore.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/FileStore.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/AbstractFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/AppendOnlyFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogValueCountFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/FileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/AbstractTableWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/MemoryTableWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/TableWrite.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/utils/FailingAtomicRenameFileSystem.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/AppendOnlyFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogValueCountFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/FileStoreTableTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/SchemaEvolutionTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/WritePreemptMemoryTest.java
- flink-table-store-hive/flink-table-store-hive-connector/src/test/java/org/apache/flink/table/store/hive/TableStoreHiveStorageHandlerITCase.java
- flink-table-store-hive/flink-table-store-hive-connector/src/test/java/org/apache/flink/table/store/mapred/TableStoreRecordReaderTest.java
- flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SimpleTableTestHelper.java
- flink-table-store-spark2/src/test/java/org/apache/flink/table/store/spark/SimpleTableTestHelper.java
(Cherry-picked from #354)
Consider the following scenario when snapshot committing is slow:
* A writer produces some records at checkpoint T.
* It produces no record at checkpoint T+1 and is closed.
* It produces some records at checkpoint T+2. It will be reopened and read the latest sequence number from disk. However snapshot at checkpoint T may not be committed so the sequence number it reads might be too small.
In this scenario, records from checkpoint T may overwrite records from checkpoint T+2 because they have larger sequence numbers.
This PR fixes this bug by comparing last modified commit identifier and the latest committed identifier before closing a writer. If by comparing we found that the last modification is already committed, we can safely close the writer.
> [FLINK-29840] Fix bug that old record may overwrite new record in Table Store when snapshot committing is slow

- flink-table-store-hive/pom.xml
We can use hive 2.3.9 for all flink versions.
> [hotfix] Remove profile flink-1.14 and flink-1.15 in hive

- docs/layouts/shortcodes/generated/core_configuration.html
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/FullChangelogStoreWriteOperator.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/PrepareCommitOperator.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreCompactOperator.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreSink.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreWriteOperator.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSource.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ChangelogWithKeyFileStoreTableITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/append/AppendOnlyWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/MergeTreeCompactManager.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AbstractFileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AbstractFileStoreWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/RecordWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/TableWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/TableWriteImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/DataTableScan.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/UniversalCompactionTest.java
The last step to produce full compaction changelog is to modify Flink Table Store connector, so that full compaction will be triggered once in a while. If not, changelog files are not guaranteed to be produced, and the last few records for a partition may not appear in changelog.
> [FLINK-29752] Modify Flink Table Store connector to trigger full compaction constantly when full changelog is needed

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/FlinkSinkBuilder.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreSink.java
Change `sinkTo` to `sinkFrom`.
> [hotfix] Fix method name typo in StoreSink class

- docs/layouts/shortcodes/generated/rocksdb_configuration.html
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/RocksDBOptions.java
Need to add a period to the description of "lookup.cache-rows".
> [FLINK-29994][Table Store]Fix missing a period in description of Lookup Join.

- flink-table-store-hive/flink-table-store-hive-catalog/pom.xml
- flink-table-store-hive/flink-table-store-hive-connector/pom.xml
Flink Table Store has the [same issue](https://issues.apache.org/jira/browse/FLINK-29962) as the main repo - hive dependencies depend on `jamon-runtime-2.3.1` that has malformed [pom](https://repo1.maven.org/maven2/org/jamon/jamon-runtime/2.3.1/jamon-runtime-2.3.1.pom) (nested project tag). My maven mirror complains about this and does not accept the dependency. Here is an error message:
```
Could not resolve dependencies for project org.apache.flink:flink-table-store-hive-catalog:jar:0.3-SNAPSHOT: Failed to collect dependencies at org.apache.hive.hcatalog:hive-webhcat-java-client:jar:2.3.9 -> org.apache.hive.hcatalog:hive-hcatalog-core:jar:2.3.9 -> org.apache.hive:hive-cli:jar:2.3.9 -> org.apache.hive:hive-service:jar:2.3.9 -> org.apache.hive:hive-llap-server:jar:2.3.9 -> …
```
> [FLINK-29962] Exclude jamon 2.3.1 from dependencies

- docs/content/docs/development/rescale-bucket.md
The word "exiting " in "Reorganize exiting data must be achieved by INSERT OVERWRITE." doesn't make sense, I realized that mostly like a typo.
> [FLINK-30012]Fix a typo in official Table Store document.

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/SchemaManager.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/SchemaEvolutionTest.java
Check the source and target column types in `SchemaManager` to avoid data type conversion failures when reading data
> [FLINK-30013] Add check update column type

- flink-table-store-codegen/src/main/scala/org.apache.flink.table.store.codegen/GenerateUtils.scala
- flink-table-store-common/src/test/java/org/apache/flink/table/store/format/FileStatsExtractorTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/AppendOnlyFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogValueCountFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/FileStoreTableTestBase.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/orc/OrcFileFormat.java
- flink-table-store-format/src/test/java/org/apache/flink/table/store/format/orc/OrcFileStatsExtractorTest.java
Currently, changelog mode cannot support map and multiset as the field type. More specifically,
- `MULTISET` is not supported at all, including append-only mode. (
```
Caused by: java.lang.UnsupportedOperationException: Unsupported type: MULTISET<TINYINT>
at org.apache.flink.table.store.shaded.org.apache.flink.orc.OrcSplitReaderUtil.logicalTypeToOrcType(OrcSplitReaderUtil.java:214)
at org.apache.flink.table.store.shaded.org.apache.flink.orc.OrcSplitReaderUtil.logicalTypeToOrcType(OrcSplitReaderUtil.java:210)
at org.apache.flink.table.store.format.orc.OrcFileFormat.createWriterFactory(OrcFileFormat.java:94)
at org.apache.flink.table.store.file.data.AppendOnlyWriter$RowRollingWriter.lambda$createRollingRowWriter$0(AppendOnlyWriter.java:229)
at …
```
> [FLINK-28552] GenerateUtils#generateCompare supports MULTISET and MAP

- docs/content/docs/engines/overview.md
Update Spark3 to create/drop table in Compatibility Matrix, features have been verified in spark 3.3.1/3.2.2/3.1.3/3.0.3 versions
> [FLINK-28671] Update Spark3 to create/drop table in Compatibility Matrix

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/stats/BinaryTableStats.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/stats/BinaryTableStatsTest.java
`Predicate` get min and max from `BinaryRowData`, lazily deserialization.
> [FLINK-30027] Fields min and max in BinaryTableStats support lazy deserialization

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/AppendOnlyFileStore.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/KeyValueFileStore.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AbstractFileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AppendOnlyFileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/KeyFieldsExtractor.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/RowDataType.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/SchemaEvolutionUtil.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/SchemaFieldTypeExtractor.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/TableSchema.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/stats/FieldStatsArraySerializer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogValueCountFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTable.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestKeyValueGenerator.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/io/DataFileTestUtils.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreExpireTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreReadTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreScanTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/schema/SchemaEvolutionUtilTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/stats/FieldStatsArraySerializerTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/AppendOnlyTableFileMetaFilterTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogValueCountFileMetaFilterTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogWithKeyFileMetaFilterTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/FileMetaFilterTestBase.java
Currently, the table store uses the latest schema id to read the data file meta. When the schema evolves, it will cause errors, for example:
1. the schema of underlying data is [1->a, 2->b, 3->c, 4->d] and schema id is 0, where 1/2/3/4 is field id and a/b/c/d is field name
2. After schema evolution, schema id is 1, and the new schema is [1->a, 3->c, 5->f, 6->b, 7->g]
When table store reads the field stats from data file meta, it should mapping schema 1 to 0 according to their field ids.
This PR will read and parse the data according to the schema id in the meta file when reading the data file meta, and create index mapping from the table schema and the meta schema, so that the table store can read the correct file meta data through its latest schema.
The main codes are as follows:
1. …
> [FLINK-27843] Schema evolution for data file meta

- pom.xml
Without this patch `mvn package verify` fails with
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.1.1:shade (shade-flink) on project flink-table-store-dist: Error creating shaded jar: duplicate entry: META-INF/services/org.apache.flink.table.store.shaded.org.apache.kafka.common.config.provider.ConfigProvider -> [Help 1]
```
This patch fixes the issue by upgrading the version of `maven-shade-plugin` to 3.4.1.
> [FLINK-30091] Update maven-shade-plugin version to 3.4.1

- docs/layouts/shortcodes/generated/core_configuration.html
- flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreWrite.java
After a lot of tests, it is found that the participation of spillable does not improve HDFS greatly, but will bring some jitters.
In this jira, spillable is enabled only when the object is stored by default, so that the performance can be improved without affecting hdfs.
> [FLINK-30082] Enable write-buffer-spillable by default only for object storage

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSource.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/AppendOnlyFileStore.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/KeyValueFileStore.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AbstractFileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AppendOnlyFileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/DataTableScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/SnapshotEnumerator.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/FileStoreTableTestBase.java
At present, `read-compacted` does not affect the work of scan in various situations. We can read it directly from options.
> [FLINK-28812] Read read-compacted from options

- flink-table-store-common/src/main/java/org/apache/flink/table/store/file/predicate/PredicateFilter.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/BucketStreamPartitioner.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/FlinkSinkBuilder.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreWriteOperator.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/AppendOnlyTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/PredicateITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/predicate/BucketSelector.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/AppendOnlyFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogValueCountFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/FileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/SupportsWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/BucketComputer.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/SinkRecordConverter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/TableWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/TableWriteImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/TableRead.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/AppendOnlyFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/sink/SinkRecordConverterTest.java
When other engines dock with Sink, they need to know the corresponding bucket rules before they can be correctly distributed to each bucket.
This is first refactor PR for https://github.com/apache/flink-table-store/pull/394
> [FLINK-30164] Expose BucketComputer from SupportsWrite

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/FullChangelogStoreWriteOperator.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreCompactOperator.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/append/AppendOnlyWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AbstractFileStoreWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/RecordWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/TableWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/TableWriteImpl.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/TestCommitThread.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTableTest.java
Currently the compact interface in `TableWrite` and `FileStoreWrite` can only trigger full compaction. However a separated compact job should not only perform full compaction, but also perform normal compaction once in a while, just like what the current Table Store sinks do.
We need to modify compact interface for `TableWrite` and `FileStoreWrite` to support normal compaction.
> [FLINK-30205] Modify compact interface for TableWrite and FileStoreWrite to support normal compaction in Table Store

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/PartialUpdateITCase.java
- pom.xml
This patch stabilizes `PartialUpdateITCase#testForeignKeyJoin` and introduces a new test dependency - [Awaitility](https://github.com/awaitility/awaitility) that can be conveniently used to prevent similar issues in the future.
> [FLINK-29987] Use Awaitility in PartialUpdateITCase#testForeignKeyJoin

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/FlinkSinkBuilder.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreSink.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/TableStoreSink.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/Lock.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/HiveCatalog.java
For the core, it should not see too many Flink Table concepts, such as database and tableName. It only needs to create a Lock.
> [FLINK-30223] Refactor Lock to provide Lock.Factory

- docs/content/docs/engines/hive.md
- flink-table-store-hive/flink-table-store-hive-catalog/pom.xml
- flink-table-store-hive/pom.xml
- tools/releasing/create_binary_release.sh
For Hive3,  `org.apache.hadoop.hive.metastore.api` is moved to `org.apache.hive:hive-standalone-metastore`. We should shade this package as well to avoid `ClassNotFoundException`
> [FLINK-29983] Fix Table Store with Hive3 lacking hive-standalone-metastore dependency

- docs/content/docs/filesystem/_index.md
- docs/content/docs/filesystem/overview.md
- flink-table-store-filesystem/flink-table-store-fs-oss-hadoop/pom.xml
- flink-table-store-filesystem/pom.xml
- flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/HiveCatalog.java
- flink-table-store-hive/flink-table-store-hive-connector/src/main/java/org/apache/flink/table/store/hive/HiveSchema.java
- flink-table-store-hive/flink-table-store-hive-connector/src/main/java/org/apache/flink/table/store/hive/TableStoreSerDe.java
- flink-table-store-hive/flink-table-store-hive-connector/src/test/java/org/apache/flink/table/store/hive/HiveTableSchemaTest.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkCaseSensitiveConverter.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkCatalog.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkSource.java
- flink-table-store-spark2/src/main/java/org/apache/flink/table/store/spark/SparkCaseSensitiveConverter.java
- flink-table-store-spark2/src/main/java/org/apache/flink/table/store/spark/SparkSource.java
- pom.xml
Currently, we rely on Flink's plugin mechanism to initialize Filesystem, which does not apply to other engines like Spark/Hive. This PR resolves
- Invoke `Filesystem#initialize` to configure the target filesystem (including jar dependency and conf parameters)
- For Spark, convert case insensitive conf to case sensitive conf (special handling for oss)
- For Hive, let AK/endpoint can be configured via the `SET` command
- Tested upon Spark3.3 & Hive3.1, found sorts of class conflicts then decided to shade oss to ease use. So introduce a submodule `flink-table-store-filesystem` to shade fs-oss/fs-s3(in the next pr)
- Add readme
Towards the E2E test, I'm unsure whether we can put AK info directly since the oss server is hard to mock. (maybe GitHub CI can support passing some secret values as …
> [FLINK-29964] Support Spark/Hive with OSS

- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreExpireTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreReadTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreScanTest.java
Currently, without copy, merge function may produce wrong results in `TestFileStore`.
> [hotfix] Fix test unstable: use MergeFunctionFactory in TestFileStore

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AbstractFileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AppendOnlyFileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreScan.java
We already have tests in `FileStoreScanTest`, but it looks like JDK 8 can not reproduce failure.
> [hotfix] Methods in AbstractFileStoreScan should be thread safe

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitGeneratorTest.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestEntry.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestFileMeta.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AbstractFileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/DataTableScan.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTableTest.java
Currently `AbstractFileStoreScan` can only read incremental changes from APPEND snapshots. However in OVERWRITE snapshots, users will also append new records to table. These changes must be discovered by compact job source so that the overwritten partition can be compacted.
> [FLINK-30206] Allow FileStoreScan to read incremental changes from OVERWRITE snapshot in Table Store

- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/SupportsWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/SerializableCommittable.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkCatalog.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkFilterConverter.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkRowData.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkSource.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkTable.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkWrite.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkWriteBuilder.java
- flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SparkInternalRowTest.java
- flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SparkWriteITCase.java
- Supports spark batch write by v1 write. (The Spark SourceV2 interface currently does not support custom distribution, and the Table Store must have consistent distribution.)
- Supports spark delete.
> [FLINK-29614] Introduce Spark writer for table store

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ContinuousFileStoreITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/FileStoreTableFactory.java
When `log.scan.timestamp-millis` is configured and `log.scan` isn't configured, the `log.scan` should be setting to `from-timestamp` by default.
- `FileStoreTableFactory#validateOptions` should validate the case that `log.scan.timestamp-millis` is configured.
> [FLINK-30110] Enable from-timestamp log scan when timestamp-millis is configured

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/FlinkCatalog.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/CatalogTableITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/AbstractCatalog.java
Currently user can create tables `tablename` and `tablename$snapshots`, but can't insert into values into `tablename$snapshots` and execute query on it.
At the same time, user can create table `tablename$aaa$bbb`, but cannot execute query on it and event cannot drop it.
This PR aims to validate the table name and user cannot create the table whose name contains `$`
> [FLINK-30269] Validate table name for metadata table

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/MetadataCatalogTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/SchemaManager.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/AbstractFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/AppendOnlyFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogValueCountFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/FileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/FileStoreTableFactory.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/Table.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/metadata/OptionsTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/metadata/SnapshotsTable.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/AppendOnlyFileDataTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/AppendOnlyFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/AppendOnlyTableFileMetaFilterTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogValueCountFileDataTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogValueCountFileMetaFilterTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogValueCountFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogWithKeyFileDataTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogWithKeyFileMetaFilterTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/FileStoreTableTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/WritePreemptMemoryTest.java
At present, our processing of dynamic options is relatively independent. In FileStoreTableFactory, this is not conducive to other engines configuring dynamic options.
We should propose an interface on the Table, and dynamic options can be configured at any time.
> [FLINK-30271] Introduce Table.copy from dynamic options

- docs/content/docs/development/streaming-query.md
- docs/layouts/shortcodes/generated/core_configuration.html
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FlinkSourceBuilder.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ComputedColumnAndWatermarkTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ReadWriteTableTestBase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/TableStreamingReader.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/snapshot/DataFileSnapshotEnumerator.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/snapshot/DeltaSnapshotEnumerator.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/snapshot/FullCompactionChangelogSnapshotEnumerator.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/snapshot/InputChangelogSnapshotEnumerator.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/CoreOptionsTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTableTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/source/snapshot/DeltaSnapshotEnumeratorTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/source/snapshot/FullCompactionChangelogSnapshotEnumeratorTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/source/snapshot/InputChangelogSnapshotEnumeratorTest.java
- flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogSourceProvider.java
- flink-table-store-kafka/src/main/java/org/apache/flink/table/store/kafka/KafkaLogStoreFactory.java
We're introducing time-travel reading of Table Store for batch jobs. However this reading mode is quite similar to the "from-timestamp" startup mode for streaming jobs, just that "from-timestamp" streaming jobs only consume incremental data but not history data.
We can support startup mode for both batch and streaming jobs. For batch jobs, "from-timestamp" startup mode will produce all records from the last snapshot before the specified timestamp. For streaming jobs the behavior doesn't change.
Previously, in order to use "from-timestamp" startup mode, users will have to specify "log.scan" and also "log.scan.timestamp-millis", which is a little inconvenient. We can introduce a "default" startup mode and its behavior will base on the execution environment and other configurations. In this …
> [FLINK-30294] Change table property key 'log.scan' to 'scan.mode' and add a default startup mode in Table Store

- flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/KeyValue.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/TableSchema.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogValueCountFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/ChangelogWithKeyFileStoreTable.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/SchemaEvolutionTest.java
There're some system field names such as column with prefix `_KEY_`, column names `_VALUE_COUNT`, `_SEQUENCE_NUMBER` and `_VALUE_KIND`. User can use them to create table in table store, but it will throw exception when user try to `insert values ...` to the table as followed:
Caused by: org.apache.flink.table.api.ValidationException: Field names must be unique. Found duplicates: [_KEY_word]
at org.apache.flink.table.types.logical.RowType.validateFields(RowType.java:273)
at org.apache.flink.table.types.logical.RowType.<init>(RowType.java:158)
at org.apache.flink.table.types.logical.RowType.<init>(RowType.java:162)
at org.apache.flink.table.store.file.KeyValue.schema(KeyValue.java:106)
at org.apache.flink.table.store.file.io.KeyValueFileWriterFactory$Builder.build(KeyValueFileWriterFactory.j …
> [FLINK-30319] Validate column name in ddl

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/lookup/FileStoreLookupFunction.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FlinkSourceBuilder.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/LookupJoinITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/TableStreamingReader.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/snapshot/ContinuousDataFileSnapshotEnumerator.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/snapshot/SnapshotEnumerator.java
The lookup uses streaming read for reading table. (In TableStreamingReader)
- We should support lookup a partial-update table with full compaction.
- But partial-update table without full compaction, we should throw exception.
> [FLINK-30333] Supports lookup a partial-update table

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/FlinkCatalogFactory.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FlinkCatalogTest.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/CatalogFactory.java
Main Change:
- Allow passing ClassLoader parameter when creating catalog;
- Pass ClassLoader from context when creating `FlinkCatalog`.
> [FLINK-30453] Fix 'can't find CatalogFactory' error when using FLINK sql-client to add table store bundle jar

- docs/content/docs/filesystems/oss.md
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/DataTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/Table.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/system/OptionsTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/system/SchemasTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/system/SnapshotsTable.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkCatalog.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkReaderFactory.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkScan.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkScanBuilder.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkSource.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkTable.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkWrite.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkWriteBuilder.java
Currently when writing Table Store tables on OSS with other engines (for example Spark), the following exception will occur.
```
22/12/23 17:54:12 WARN TaskSetManager: Lost task 0.0 in stage 3.0 (TID 3) (core-1-1.c-c9f1b761c8946269.cn-huhehaote.emr.aliyuncs.com executor 2): java.lang.RuntimeException: Failed to find latest snapshot id
at org.apache.flink.table.store.file.utils.SnapshotManager.latestSnapshotId(SnapshotManager.java:81)
at org.apache.flink.table.store.file.operation.AbstractFileStoreWrite.scanExistingFileMetas(AbstractFileStoreWrite.java:87)
at org.apache.flink.table.store.file.operation.KeyValueFileStoreWrite.createWriter(KeyValueFileStoreWrite.java:113)
at org.apache.flink.table.store.file.operation.AbstractFileStoreWrite.createWriter(AbstractFileStoreWrite.java:227)
at …
```
> [FLINK-30504] Fix UnsupportedFileSystemSchemeException when writing Table Store on OSS with Spark

- docs/content/docs/engines/overview.md
- docs/content/docs/engines/spark2.md
- docs/content/docs/engines/spark3.md
- docs/content/docs/how-to/writing-tables.md
Table Store 0.3 supports writing with Spark3. We need to add documentation.
> [FLINK-30506] Add documentation for writing Table Store with Spark3

- pom.xml
With this patch the maven build takes around 1 minute instead of 20 on my laptop. 
There are 2 changes - pinning a dependency in 1b6f8012328522b945dc5e36eda7ee946159c6c9 and updating 2 plugins to their thread-safe versions in 60f661a60f2d1ac2b09b8448bee91f7f4b18c98b.
Without these changes `mvn clean install -DskipTests` takes 15-20 minutes on my laptop. After pinning `json-smart` the build time went to around 2-2.5 minutes. After switching to the latest plugin versions and using -`-T 4` the build runs in 1-1.5 minutes.
> Speed up FTS  build

- pom.xml
This is a follow-up PR for https://github.com/apache/flink-table-store/pull/447. 
The original PR was reverted because it broke builds with maven 3.2.5. Build failures were due to `directory-maven-plugin` upgrade to version 1.0.
This PR reverts the `directory-maven-plugin` version change, but still upgrades rat and pins json-smart. As a result, we still get the build speedup from 20 minutes to ca. ~2 minutes without the multithreaded build.
I tested this PR by building the project with this patch using maven 3.2.5.
> Speedup build

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/SnapshotManager.java
Add retry to read hints in SnapshotManager
- *Introduce the retry logic in SnapshotManager*
- Dependencies (does it add or upgrade a dependency): (no)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
- The serializers: (no)
- The runtime per-record code paths (performance sensitive): (no)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no )
- The S3 file system connector: (no)
- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (JavaDocs)
> [FLINK-30389] Add retry to read hints

- docs/content/docs/filesystems/oss.md
- docs/content/docs/filesystems/s3.md
- flink-table-store-hive/flink-table-store-hive-connector/src/main/java/org/apache/flink/table/store/TableStoreJobConf.java
- flink-table-store-hive/flink-table-store-hive-connector/src/main/java/org/apache/flink/table/store/hive/HiveSchema.java
- flink-table-store-hive/flink-table-store-hive-connector/src/main/java/org/apache/flink/table/store/hive/TableStoreHiveStorageHandler.java
- flink-table-store-hive/flink-table-store-hive-connector/src/main/java/org/apache/flink/table/store/mapred/TableStoreInputFormat.java
- flink-table-store-hive/flink-table-store-hive-connector/src/test/java/org/apache/flink/table/store/hive/TableStoreHiveStorageHandlerITCase.java
[FLINK-29964](https://issues.apache.org/jira/browse/FLINK-29964) add oss support for Hive, but only valid in the case of standalone Hive, the distributed Hive compute engine cannot access.
We should add more FileSystems.initialize to Hive connector.
Manually tests cover, there is no way to test distributed Hive compute engine.
> [FLINK-30555] Hive cluster can not read oss/s3 tables

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/CatalogITCaseBase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileStoreTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/PartialUpdateITCase.java
We recommend users to use Catalog tables instead managed tables.
Managed tables should be deprecated. Now we already did not expose managed in documentation. We can remove it.
Before removing, tests should be refactored.
FileStoreTableITCase with managed tables should be changed to CatalogITCaseBase.
> [FLINK-30581] Deprecate FileStoreTableITCase and use CatalogITCaseBase

- docs/content/docs/maintenance/write-performance.md
- docs/layouts/shortcodes/generated/core_configuration.html
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/action/CompactAction.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/FlinkSink.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/StoreCompactOperator.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ChangelogWithKeyFileStoreTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/action/CompactActionITCase.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/CoreOptions.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/compact/NoopCompactManager.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AppendOnlyFileStoreWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/AbstractFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/TableCommit.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/FileStoreTableTestBase.java
- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/FlinkActionsE2eTest.java
Currently Table Store dedicated writer jobs will also expire snapshots. This may cause conflicts when multiple writer jobs are running.
We should expire snapshots only in dedicated compact job.
> [FLINK-30589] Snapshot expiration should be skipped in Table Store dedicated writer jobs

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestFile.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreExpireImpl.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/CleanedFileStoreExpireTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreExpireTestBase.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/UncleanedFileStoreExpireTest.java
If user kills the job when expiration is in progress, the files for some snapshots will become incomplete. We should support expiration with missing files so that when the job restarts, the expiration process can work normally.
> [FLINK-30611] Expiration can be performed with missing files

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ReadWriteTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ReadWriteTableTestBase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/StreamingReadWriteTableWithKafkaLogITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/util/AbstractTestBase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/util/ReadWriteTableTestUtil.java
1. Split Kafka log related cases into a new test class.
2. `testQueryContainsDefaultFieldName` & `testSuccessiveWriteAndRead` in `ReadWriteTableITCase` seems trivial so I remove them.
3. Introduce new `AbstractTestBase` using Junit5.
> [FLINK-30615] Refactor ReadWriteTableITCase to get rid of Managed Table and introduce new AbstractTestBase

- flink-table-store-hive/flink-table-store-hive-catalog/pom.xml
For Hive 2.3.9, if a custom `hive-site.xml` is presented in `$HIVE_HOME/conf`, when creating Table Store Hive catalog in Flink, the following exception will be thrown.
```
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.hive.metastore.DefaultMetaStoreFilterHookImpl not found
at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2273) ~[flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:2.8.3-10.0]
at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2367) ~[flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:2.8.3-10.0]
at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2393) ~[flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:2.8.3-10.0]
at org.apache.flink.table.store.shaded.org.apache.hadoop.hive.metastore.HiveMetaStoreClient.loadFilterHooks …
```
> [FLINK-30646] Table Store Hive catalog throws ClassNotFoundException when custom hive-site.xml is presented

- docs/content/docs/how-to/creating-catalogs.md
- flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/HiveCatalog.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/HiveCatalogFactory.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/HiveCatalogLock.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/test/java/org/apache/flink/table/store/hive/CustomHiveMetastoreClientITCase.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/test/java/org/apache/flink/table/store/hive/TestHiveMetaStoreClient.java
- flink-table-store-spark/src/main/java/org/apache/flink/table/store/spark/SparkCaseSensitiveConverter.java
- flink-table-store-spark2/src/main/java/org/apache/flink/table/store/spark/SparkCaseSensitiveConverter.java
Currently Hive metastore client class is hard coded in HiveCatalog, however users may want to specify custom Hive metastore client to read and write Hive compliant storage.
This PR is tested by hand.
> [FLINK-30620] Table Store Hive catalog supports specifying custom Hive metastore client

- docs/content/docs/engines/flink.md
The embedded mode has been the default mode of SQL CLI since Flink v1.13. Therefore, users don't need to type the "embedded" parameter when launching SQL CLI. 
```bash
./bin/sql-client.sh
```
> [docs] Remove "embedded" SQL CLI parameter in the Flink quickstart documentation

- flink-table-store-e2e-tests/src/test/java/org/apache/flink/table/store/tests/E2eTestBase.java
The hive e2e always fails according to followed error information:
`Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.Starting HiveServer2.'
at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:49)`
The main reason is the `metastore` finishes to start too late which cause the test case monitor the log of `hive-server` timeout. 
This PR aims to increase timeout from 60s(default value) to 180s for `hive-server`. I have executed `ci` five times and the `hive-server` timeout does not appear again.
> [FLINK-30038] Fix hive e2e fail

- flink-table-store-hive/flink-table-store-hive-catalog/pom.xml
Table Store Hive catalog throws `java.lang.ClassNotFoundException: org.apache.hadoop.hive.common.ValidWriteIdList` under certain environment. We need to package `hive-storage-api` dependency.
> [FLINK-30861] Fix java.lang.ClassNotFoundException: org.apache.hadoop.hive.common.ValidWriteIdList in Table Store Hive catalog

- flink-table-store-hive/flink-table-store-hive-connector/src/main/2/org/apache/flink/table/store/hive/objectinspector/TableStoreTimestampObjectInspector.java
Currently if we run `mvn clean install` against the master branch, it will report checkstyle error like below:
> [INFO] --- maven-checkstyle-plugin:2.17:check (validate) @ flink-table-store-hive-connector ---
> [INFO] There is 1 error reported by Checkstyle 8.14 with /tools/maven/checkstyle.xml ruleset.
> [ERROR] src/main/2/org/apache/flink/table/store/hive/objectinspector/TableStoreTimestampObjectInspector.java:[26] (imports) ImportOrder: Import org.apache.flink.table.store.data.Timestamp appears after other imports that it should precede
And this PR supplies a straight-forward hotfix.
> [hotfix] Fix checkstyle error in flink-table-store-hive module

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/CompositePkAndMultiPartitionedTableITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/CompositePkAndMultiPartitionedTableWIthKafkaLogITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ReadWriteTableTestBase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ShowCreateUtil.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/StreamingReadWriteTableWithKafkaLogITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/action/CompactActionITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/util/ReadWriteTableTestUtil.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/kafka/KafkaTableTestBase.java
Main changes:
1. Split old `CompositePkAndMultiPartitionedTableITCase` to two parts: new `CompositePkAndMultiPartitionedTableITCase` and `CompositePkAndMultiPartitionedTableWIthKafkaLogITCase`.
2. Move some methods from `StreamingReadWriteTableWithKafkaLogITCase` to `ReadWriteTableTestUtil`.
3. Clean some test util classes (`ReadWriteTableTestBase`,  `ShowCreateUtil`).
> [FLINK-30918] Refactor CompositePkAndMultiPartitionedTableITCase to get rid of managed table

- flink-table-store-filesystems/flink-table-store-s3-impl/src/main/java/org/apache/flink/table/store/s3/S3FileIO.java
s3.signer-type mirrored to s3a.signing-algorithm.
> [FLINK-30980] Support s3.signer-type for S3.

- flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/HiveCatalog.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/test/java/org/apache/flink/table/store/hive/HiveCatalogITCase.java
In HiveCatalog.listTables, in the current implementation, getTable will be called for each TableName. However, the environment here may not be able to access non-TableStore tables.
We can avoid access non-TableStore tables by judging whether it is a TableStore table in advance.
> [FLINK-31038] Avoid accessing non-TableStore tables in HiveCatalog.listTables

- docs/content/docs/how-to/writing-tables.md
- docs/layouts/shortcodes/generated/flink_connector_configuration.html
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/FlinkConnectorOptions.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/BucketStreamPartitioner.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/FlinkSink.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/sink/FlinkSinkBuilder.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/sink/FileStoreShuffleBucketTest.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/PartitionComputer.java
Currently sink operator in flink will shuffle data by bucket id, which cause data skew when there is only 1 bucket with multiple partitions in the table. This PR aims to support shuffling data by bucket id and partition when `sink.shuffle-by-partition.enable` is set.
The main changes are
1. Added config `sink.shuffle-by-partition.enable` to support shuffling data by partition
2. Added `PartitionComputer` to get partition from row data
3. Added shuffling data by partition in `BucketStreamPartitioner`
The main tests are
1. Added `FileStoreShuffleBucketTest` to shuffle data by bucket and partition
> [FLINK-30979] Support shuffling data by partition

- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/orc/filter/OrcFilters.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/orc/filter/OrcPredicateFunctionVisitor.java
- flink-table-store-format/src/test/java/org/apache/flink/table/store/format/orc/OrcFilterConverterTest.java
This PR aims to supports `AND` push down in orc format.
> [FLINK-31032] Supports AND push down for orc format

- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/ContinuousFileSplitEnumerator.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/ContinuousFileSplitEnumeratorTest.java
Allocate the splits belonging to the specified task from all buckets to prevent some buckets from being consumed during backpressure.
When performing split allocation, if a task requires a split, a split is taken from each bucket belonging to the task and added to the allocation list.
Added `ContinuousFileSplitEnumeratorTest#testSplitAllocationIsFair` to verify that the allocation is fair.
- Dependencies (does it add or upgrade a dependency): (yes / **no**)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
- The serializers: (yes / **no** / don't know)
- The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, …
> [FLINK-30985] Allocate the splits belonging to the specified task from all buckets.

- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FileSystemCatalogITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/FlinkCatalogTest.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/AbstractCatalog.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/Catalog.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/catalog/FileSystemCatalog.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/system/SystemTableLoader.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/HiveCatalog.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/test/java/org/apache/flink/table/store/hive/HiveCatalogITCase.java
Do some refactor to make system table related methods better.
- Remove `Catalog.getTableSchema`. Useless. Not work for system tables.
- Remove `Catalog.getTableLocation`. Useless. Not work for system tables.
- Correct `Catalog.tableExists`, now work for system tables.
> [hotfix] Remove Catalog.getTableSchema

- docs/layouts/shortcodes/generated/catalog_configuration.html
- flink-table-store-common/src/main/java/org/apache/flink/table/store/table/TableType.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/HiveCatalog.java
True value is `managed` and `external`, but previous is `MANAGED_TABLE` and `EXTERNAL_TABLE` in documentation.
> [hotfix] Improve documentation for table.type

- docs/layouts/shortcodes/generated/flink_connector_configuration.html
- flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/Reference.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/FlinkConnectorOptions.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/ContinuousFileStoreSource.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSourceReader.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitReader.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/FlinkSource.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/RecordsFunction.java
- flink-table-store-connector/src/main/java/org/apache/flink/table/store/connector/source/SingleIteratorRecords.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/ContinuousFileStoreITCase.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/FileStoreSourceReaderTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitReaderTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/RecordsFunctionTest.java
- flink-table-store-connector/src/test/java/org/apache/flink/table/store/connector/source/SingleIteratorRecordsTest.java
Currently, streaming source will be checkpoint in any time, this means UPDATE_BEFORE and UPDATE_AFTER can be split into two checkpoint.
Downstream can see intermediate state. This is weird in some cases.
So in this ticket, add streaming-read-atomic:
The option to enable return per iterator instead of per record in streaming read. This can ensure that there will be no checkpoint segmentation in iterator consumption.
> [FLINK-31072] Introduce streaming-read-atomic to ensure UB and UA cannot be split

- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/parquet/ParquetSchemaConverter.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/parquet/reader/ParquetSplitReaderUtil.java
- flink-table-store-format/src/main/java/org/apache/flink/table/store/format/parquet/writer/ParquetRowDataWriter.java
- flink-table-store-format/src/test/java/org/apache/flink/table/store/format/parquet/ParquetReadWriteTest.java
Parquet format should support MULTISET type for Table Store. Meanwhile, the FileStats couldn't support the MULTISET type because the null count of ColumnStatistics for ARRAY, MAP and MULTISET type in Parquet isn't right.
- The reader, writer and converter of Parquet format supports MULTISET type.
> [FLINK-31232] Parquet format supports MULTISET type for Table Store

- docs/content/docs/how-to/querying-tables.md
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/Snapshot.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AbstractFileStoreScan.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreExpireImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/system/SnapshotsTable.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/FileStoreCommitTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreScanTest.java
- flink-table-store-flink/flink-table-store-flink-common/src/main/java/org/apache/flink/table/store/connector/source/LogHybridSourceFactory.java
- flink-table-store-flink/flink-table-store-flink-common/src/test/java/org/apache/flink/table/store/connector/CatalogTableITCase.java
- flink-table-store-spark/src/test/java/org/apache/flink/table/store/spark/SparkReadITCase.java
Record count represents the total number of data records. `Snapshot` could add `baseRecordCount`, `deltaRecordCount` and `changelogRecordCount` recording the record count of all changes occurred in the snapshot.
- Supports `baseRecordCount`, `deltaRecordCount` and `changelogRecordCount` recording the record count of all changes occurred in `Snapshot` and `SnapshotsTable`.
> [FLINK-31009] Add recordCount to snapshot meta

- flink-table-store-flink/flink-table-store-flink-common/pom.xml
Current FRocksDB version in flink-table-store is still 6.20.3-ververica-1.0, which cannot run with Apple's silicon chips.
Newly released 6.20.3-ververica-2.0 FRocksDB could run well with Apple's silicon chips and is compatible with the previous version.
> [FLINK-31226] Bump FRocksDB version to 6.20.3-ververica-2.0

- docs/content/docs/concepts/primary-key-table.md
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/aggregate/FieldAggregator.java
- flink-table-store-flink/flink-table-store-flink-common/src/test/java/org/apache/flink/table/store/connector/PreAggregationITCase.java
If the field has no aggregate function for aggregation merge-engine, use last_non_null_value aggregation as default.
> [FLINK-31289] Default aggregate-function for field can be last_non_null_value

- docs/content/docs/concepts/primary-key-table.md
Document set `table.exec.sink.upsert-materialize` to `NONE` always to avoid strange behavior brought by FLINK SQL default sink materialize.
> [FLINK-31291] Document "table.exec.sink.upsert-materialize" to "none" to avoid strange behavior

- flink-table-store-flink/flink-table-store-flink-common/src/main/java/org/apache/flink/table/store/connector/source/StaticFileStoreSplitEnumerator.java
- flink-table-store-flink/flink-table-store-flink-common/src/test/java/org/apache/flink/table/store/connector/source/ContinuousFileSplitEnumeratorTest.java
- flink-table-store-flink/flink-table-store-flink-common/src/test/java/org/apache/flink/table/store/connector/source/StaticFileStoreSplitEnumeratorTest.java
The following batch assignment operation is for two things:
1. It can be evenly distributed during batch reading to avoid scheduling problems (for example, the current resource can only schedule part of the tasks) that cause some tasks to fail to read data.
2. Read with limit, if split is assigned one by one, it may cause the task to repeatedly create SplitFetchers. After the task is created, it is found that it is idle and then closed. Then, new split coming, it will create a new SplitFetcher and repeatedly read the data of the limit number (because the limit status is in the SplitFetcher).
> [FLINK-31252] Improve StaticFileStoreSplitEnumerator to assign batch splits

- flink-table-store-flink/flink-table-store-flink-common/src/main/java/org/apache/flink/table/store/connector/sink/CommitterOperator.java
Close the Committer when the CommitterOperator closes.
> [FLINK-31294] Close the Committer when the CommitterOperator closes.

- flink-table-store-common/src/main/java/org/apache/flink/table/store/fs/FileIO.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/HiveCatalog.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/test/java/org/apache/flink/table/store/hive/FailHiveMetaStoreClient.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/test/java/org/apache/flink/table/store/hive/HiveCatalogITCase.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/test/java/org/apache/flink/table/store/hive/TestHiveMetaStoreClient.java
Delete DFS schema when create table failed in HiveCatalog
> [FLINK-31309] Delete DFS schema when create table failed in HiveCatalog

- docs/content/docs/engines/spark2.md
- docs/content/docs/engines/spark3.md
Fix spark jar name in docs for table store
> [FLINK-31389] Fix spark jar name in docs for table store

- flink-table-store-common/src/main/java/org/apache/flink/table/store/catalog/CatalogContext.java
- flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/HadoopConfUtils.java
- flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/HadoopUtils.java
- flink-table-store-common/src/test/java/org/apache/flink/table/store/fs/HadoopConfigLoadingTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/catalog/CatalogFactoryTest.java
At present, if HadoopConf is not passed in the CatalogContext, a new HadoopConf will be directly generated, which may not have the required parameters. we should correct it.
> [FLINK-31292] Introduce HadoopUtils to get Configuration in CatalogContext

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/schema/SchemaManager.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/schema/SchemaManagerTest.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/main/java/org/apache/flink/table/store/hive/HiveCatalog.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/test/java/org/apache/flink/table/store/hive/AlterFailHiveMetaStoreClient.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/test/java/org/apache/flink/table/store/hive/CreateFailHiveMetaStoreClient.java
- flink-table-store-hive/flink-table-store-hive-catalog/src/test/java/org/apache/flink/table/store/hive/HiveCatalogITCase.java
This PR amis to delete updated schema in dfs when `HiveCatalog` updates table failed in `metastore`
> [FLINK-31412] HiveCatalog rollbacks schema in dfs if it alters table failed

- flink-table-store-common/src/main/java/org/apache/flink/table/store/lookup/LookupStoreFactory.java
- flink-table-store-common/src/main/java/org/apache/flink/table/store/lookup/LookupStoreReader.java
- flink-table-store-common/src/main/java/org/apache/flink/table/store/lookup/LookupStoreWriter.java
- flink-table-store-common/src/main/java/org/apache/flink/table/store/lookup/hash/HashLookupStoreFactory.java
- flink-table-store-common/src/main/java/org/apache/flink/table/store/lookup/hash/HashLookupStoreReader.java
- flink-table-store-common/src/main/java/org/apache/flink/table/store/lookup/hash/HashLookupStoreWriter.java
- flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/SimpleReadBuffer.java
- flink-table-store-common/src/main/java/org/apache/flink/table/store/utils/VarLengthIntUtils.java
- flink-table-store-common/src/main/resources/META-INF/NOTICE
- flink-table-store-common/src/test/java/org/apache/flink/table/store/lookup/hash/HashLookupStoreFactoryTest.java
Introduce interface for lookup changelog producer:
```
/**
* A key-value store for lookup, key-value store should be single binary file written once and ready
* to be used. This factory provide two interfaces:
*
* <ul>
*   <li>Writer: written once to prepare binary file.
*   <li>Reader: lookup value by key bytes.
* </ul>
*/
public interface LookupStoreFactory {
LookupStoreWriter createWriter(File file) throws IOException;
LookupStoreReader createReader(File file) throws IOException;
}
```
We can convert remote columnar data to local lookup store, and ready to be used to lookup.
> [FLINK-31397] Introduce write-once hash lookup store

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/ForceUpLevel0Compaction.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/LookupChangelogMergeFunctionWrapper.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/LookupMergeFunction.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/MergeTreeCompactManager.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/UniversalCompaction.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/aggregate/AggregateMergeFunction.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/ForceUpLevel0CompactionTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/LookupChangelogMergeFunctionWrapperTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/MergeTreeCompactManagerTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/compact/UniversalCompactionTest.java
When Lookup Changelog producer is enabled, each merge will query the old merged record, so the latest high level record should be the final merged value.
Because changelog is generated when level 0 is merged to a higher level, we need a compaction policy to ensure that changelog is generated each time.
Changelog records are generated in the process of the level-0 file participating in the compaction, if during the compaction processing:
- Without level-0 records, no changelog.
- With level-0 record, with level-x (x > 0) record, level-x record should be BEFORE, level-0 should be AFTER.
- With level-0 record, without level-x record, need to lookup the history value of the upper level as BEFORE.
> [core] Introduce LookupMergeFunction and ForceUpLevel0Compaction

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/AbstractFileStore.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/manifest/ManifestFile.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/FileStoreCommitImpl.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestFileMetaTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/manifest/ManifestFileTest.java
As schema may change during a CTAS streaming job, the schema ID of snapshots and manifest files may also change. We should remove `schemaId` from their constructor and calculate the real `schemaId` on the fly.
> [FLINK-31436] Remove schemaId from constructor of FileStoreCommitImpl and ManifestFile in Table Store

- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/AbstractFileStoreTable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/FileStoreTable.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/FileStoreTableTestBase.java
To capture schema changes, CDC sinks of Flink Table Store should be able to use the latest schema at any time. This requires us to copy a `FileStoreTable` with latest schema so that we can create `TableWrite` with latest schema.
> [FLINK-31431] Support copying a FileStoreTable with latest schema

- docs/content/docs/concepts/file-layouts.md
Fix typos in doc 'file-layouts':
- 'data file' with link to 'data files'
- 'WIthin' to 'Within'
> [hotfix] Correct typos in document file-layouts

- docs/content/docs/concepts/append-only-table.md
- docs/content/docs/how-to/creating-tables.md
- docs/content/docs/how-to/writing-tables.md
Fix the following shortcode errors in docs:
- append-only-table.md
- creating-tables.md
- writing-tables.md
> [FLINK-31465] Fix shortcode errors in docs.

- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/append/AppendOnlyCompactManager.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/append/AppendOnlyWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/compact/CompactManager.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/compact/NoopCompactManager.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/MergeTreeWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/mergetree/compact/MergeTreeCompactManager.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AbstractFileStoreWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/AppendOnlyFileStoreWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/KeyValueFileStoreWrite.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/operation/Recoverable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/CommitIncrement.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/RecordWriter.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/file/utils/Restorable.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/sink/TableWriteImpl.java
- flink-table-store-core/src/main/java/org/apache/flink/table/store/table/source/StreamTableScan.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/TestFileStore.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/append/AppendOnlyWriterTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/format/FileFormatSuffixTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/mergetree/MergeTreeTest.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/file/operation/TestCommitThread.java
- flink-table-store-core/src/test/java/org/apache/flink/table/store/table/sink/TableWriteTest.java
- flink-table-store-flink/flink-table-store-flink-common/src/test/java/org/apache/flink/table/store/connector/source/FileStoreSourceReaderTest.java
- flink-table-store-flink/flink-table-store-flink-common/src/test/java/org/apache/flink/table/store/connector/source/FileStoreSourceSplitReaderTest.java
- flink-table-store-flink/flink-table-store-flink-common/src/test/java/org/apache/flink/table/store/connector/source/TestChangelogDataReadWrite.java
Currently `Table` and `TableWrite` in Flink Table Store have a fixed schema. However to consume schema changes, Flink Table Store CDC sinks should have the ability to change its schema during a streaming job.
This require us to pause and store the states of a `TableWrite`, then create a `TableWrite` with newer schema and recover the states in the new `TableWrite`.
> [FLINK-31430] Support migrating states between different instances of TableWriteImpl and AbstractFileStoreWrite

- docs/content/concepts/overview.md
Decoupling `Overview` documentation from Flink
No need.
N/A
N/A
> [docs] Decoupling `Overview` documentation from Flink

- paimon-core/src/main/java/org/apache/paimon/cdc/CdcRecord.java
- paimon-core/src/main/java/org/apache/paimon/cdc/Record.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AbstractStoreWriteOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FileStoreSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FullChangelogStoreSinkWrite.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/PrepareCommitOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowDataStoreWriteOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCompactOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWrite.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWriteImpl.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/SchemaAwareStoreWriteOperator.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/FileStoreShuffleBucketTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/SchemaAwareStoreWriteOperatorTest.java
Currently `StoreWriteOperator` is not able to deal with schema changes. We need to introduce a special `StoreWriteOperator` to deal with schema changes.
* SchemaAwareStoreWriteOperatorTest
N/A
N/A
> [FLINK-31432] Introduce a special StoreWriteOperator to deal with schema changes

- paimon-spark/paimon-spark-2/src/main/java/org/apache/paimon/spark/SparkInputPartition.java
- paimon-spark/paimon-spark-2/src/main/java/org/apache/paimon/spark/SparkInputPartitionReader.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkInputPartitionReader.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkReaderFactory.java
Extract SparkInputPartitionReader from paimon spark connector
Optimize code structure
> [spark] Extract SparkInputPartitionReader from paimon spark connector

- paimon-core/src/main/java/org/apache/paimon/schema/SchemaChange.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeSerializationTest.java
To avoid concurrent changes to table schema, CDC sinks for Paimon should send all `SchemaChange` to a special process function. This process function only has 1 parallelism and it is dedicated for schema changes.
To pass `SchemaChange` through network, `SchemaChange` must be serializable.
N/A
N/A
N/A
> [FLINK-31433] Make SchemaChange serializable

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FileStoreSourceReader.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FileStoreSourceSplitReader.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/RecordLimiter.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/StaticFileStoreSplitEnumerator.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FileStoreSourceSplitReaderTest.java
Limit should not rely on assign all splits in StaticFileStoreSplitEnumerator.
Assign all splits in one time will produce exceed `akka.framesize` to exceptions.
We can add a global limiter in `FileStoreSourceReader`, limiter is created in SourceReader, it can be shared in all split readers.
Test Exists.
> [flink] Limit should not rely on assign all splits in StaticFileStoreSplitEnumerator

- paimon-common/src/main/java/org/apache/paimon/utils/TypeUtils.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/SchemaAwareStoreWriteOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/SchemaChangeProcessFunction.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSinkITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/SchemaAwareStoreWriteOperatorTest.java
It is common for database users to update column types to a wider type, such as changing `INT` types to `BIGINT`s, and `CHAR`s to `VARCHAR`s. We should support these common usages.
* SchemaAwareStoreWriteOperatorTest
* FlinkCdcSinkITCase
N/A
N/A
> [FLINK-31558] Support updating schema type with restrictions in CDC sink

- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/TableWriterBenchmark.java
- paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
- paimon-core/src/main/java/org/apache/paimon/utils/FileStorePathFactory.java
- paimon-core/src/test/java/org/apache/paimon/FileFormatTest.java
- paimon-core/src/test/java/org/apache/paimon/TestFileStore.java
- paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java
- paimon-core/src/test/java/org/apache/paimon/io/DataFilePathFactoryTest.java
- paimon-core/src/test/java/org/apache/paimon/io/RollingFileWriterTest.java
- paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileMetaTest.java
- paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileTest.java
- paimon-core/src/test/java/org/apache/paimon/manifest/ManifestListTest.java
- paimon-core/src/test/java/org/apache/paimon/schema/SchemaManagerTest.java
- paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java
- paimon-core/src/test/java/org/apache/paimon/utils/FileStorePathFactoryTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FileStoreITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ForceCompactionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/TestChangelogDataReadWrite.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/PaimonStorageHandlerITCase.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/mapred/PaimonRecordReaderTest.java
Use enum instead of string for file.format and validate the format value in ddl
1. Added the test `SchemaManagerTest.testInvalidFormatType` to validate the format value
*(Does this change affect API or storage format)* no
*(Does this change introduce a new feature)* no
> [core] Use enum instead of string for file.format

- docs/content/how-to/writing-tables.md
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MergeIntoAction.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/MergeIntoActionITCase.java
Fix bug.
1. Register alias as table  is not correct because the registerTable API doesn't handle qualified path. Replace it with #createTemporaryView. 
2. Refactor source table and sql: now source name is required. Source alias should be defined in sql now.
3. Refactor test.
`MergeIntoActionITCase`
Delete `--source-as` argument in merge-into action
Improve writing-tables#Merging into table
> [flink][bug] Table alias cannot work in merge-into action

- paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
The system snapshots table return unordered snapshot rows by default, it's better to return sorted rows by default.
_**Before**_
_**Enhance**_
> [core] Return sorted snapshot rows by default

- paimon-spark/paimon-spark-2/src/test/java/org/apache/paimon/spark/SimpleTableTestHelper.java
- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadITCase.java
- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadTestBase.java
Use new ReadBuilder and WriteBuilder API in tests of paimon-spark module
sub-task of #639
> [spark] Use new ReadBuilder and WriteBuilder API in tests of paimon-spark module

- paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
- paimon-core/src/test/java/org/apache/paimon/schema/SchemaManagerTest.java
- paimon-core/src/test/java/org/apache/paimon/table/SchemaEvolutionTest.java
Q1:
when the changelog producer is `lookup` , the table has no primary key, The exception information is: `Changelog table with full-compaction must have primary keys`
Improve:
`Changelog table with lookup must have primary keys`
Q2:
When the system field ["_VALUE_COUNT", "_SEQUENCE_NUMBER", "_VALUE_KIND"] is included in the schema, the exception information is: `Field name["_VALUE_COUNT"] in schema cannot be exist in [["_VALUE_COUNT", "_SEQUENCE_NUMBER", "_VALUE_KIND"]]`
Improve:
`Field name["_VALUE_COUNT"] in schema cannot be exist in ["_VALUE_COUNT", "_SEQUENCE_NUMBER", "_VALUE_KIND"]`
*(Does this …
> [core] Improve the exception information when the changelog producer is `lookup` , the table has no primary key

- .github/workflows/e2e-tests-1.14.yml
- .github/workflows/e2e-tests-1.15.yml
- .github/workflows/e2e-tests-1.16.yml
- .github/workflows/utitcase-flink.yml
- .github/workflows/utitcase.yml
Due to the instability of GitHub action resources, some tasks may remain in a dormant state indefinitely, resulting in false positives.
For example of #718 as the following shown:
It may be helpful to add a timeout delay parameter to mitigate this issue
> [ci] add timeout option for all test steps

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcBucketStreamPartitioner.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/SchemaAwareStoreWriteOperator.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSinkITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestCdcSourceFunction.java
Current logic in `CdcBucketStreamPartitioner#selectChannel` is incorrect. This may lead to records from the same bucket being sent to different parallelism in downstream, and will cause the same bucket to be modified by multiple writers.
FlinkCdcSinkITCase
N/A
N/A
> [flink][bug] Fix incorrect partitioning result from CdcBucketStreamPartitioner#selectChannel

- paimon-flink/pom.xml
flink1.16-connector-kafka dependencies on kafka-clients 3.x, but paimon-flink-common dependencies on kafka-client version is 2.x, which may leads to classloader conflicts or class not found.so we can provided the Kafka-client dependency. When the user needs to use the external log systems or the kafka connector, user needs to add the flink-connetor-kafka connector dependency in the lib directory
LogSystemITCase
> [flink][bug] Provided kafka-client to avoid classloader conflicts(#705)

- paimon-core/pom.xml
- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommit.java
- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
- paimon-core/src/main/java/org/apache/paimon/operation/PartitionExpire.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/BatchWriteBuilder.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/BatchWriteBuilderImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/InnerTableCommit.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/TableCommitImpl.java
- paimon-core/src/test/java/org/apache/paimon/TestFileStore.java
- paimon-core/src/test/java/org/apache/paimon/operation/FileStoreCommitTest.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DropPartitionAction.java
`BatchWriteBuilder` is API for table, and currently there is no need to modify multiple partitions from table layer.
This PR removes the `BatchWriteBuilder#withOverwrite(List<Map<String, String>>)` method.
The abilities to drop multiple partitions is taken by `FileStoreCommit#dropPartitions(List<Map<String, String>>)`.
`DropPartitionActionITCase`
`PartitionExpireTest`
Added:
`FileStoreCommitTest#testDropPartitions`
Remove public API `BatchWriteBuilder#withOverwrite(List<Map<String, String>>)`.
No.
> [core] BatchWriteBuilder#withOverwrite should not accept multiple partitions list

- docs/content/filesystems/s3.md
Add path style config doc  for some  S3 compliant  object stores which  might not have virtual host style addressing enabled by default.
> [doc] Path style config for S3

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileStoreSource.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumeratorTest.java
This PR solves #722  .
introduces an option scan.split-enumerator.batch-size for assigning splits at one time to avoid exceed akka.framesize limit in StaticFileStoreSplitEnumerator. ContinuousFileSplitEnumerator should support this mechanism too.
`ContinuousFileSplitEnumeratorTest.testSplitWithBatch`
> [flink] Assign batch splits for ContinuousFileSplitEnumerator

- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/FileStoreTestUtils.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/PaimonStorageHandlerITCase.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/mapred/PaimonRecordReaderTest.java
Use new ReadBuilder and WriteBuilder API in tests of paimon-hive module
sub-task of #639
> [hive] Use new ReadBuilder and WriteBuilder API in tests of paimon-hive module

- .github/workflows/e2e-tests-1.14-jdk11.yml
- .github/workflows/e2e-tests-1.14.yml
- .github/workflows/e2e-tests-1.15-jdk11.yml
- .github/workflows/e2e-tests-1.16-jdk11.yml
- .github/workflows/e2e-tests-1.16.yml
- .github/workflows/publish_snapshot.yml
- .github/workflows/unitcase-flink-jdk11.yml
- .github/workflows/unitcase-jdk11.yml
- .github/workflows/utitcase-flink.yml
- .github/workflows/utitcase.yml
- README.md
- paimon-benchmark/paimon-micro-benchmarks/pom.xml
- paimon-common/pom.xml
- paimon-common/src/main/java/org/apache/paimon/io/cache/CachedRandomInputView.java
- paimon-common/src/test/java/org/apache/paimon/io/cache/CachedRandomInputViewTest.java
- paimon-core/pom.xml
- paimon-core/src/main/java/org/apache/paimon/io/DataFileMeta.java
- paimon-filesystems/paimon-s3-impl/pom.xml
- paimon-flink/paimon-flink-1.14/pom.xml
- paimon-flink/paimon-flink-1.15/pom.xml
- paimon-flink/paimon-flink-common/pom.xml
- paimon-format/pom.xml
- paimon-hive/paimon-hive-catalog/pom.xml
- paimon-hive/paimon-hive-common/pom.xml
- paimon-hive/paimon-hive-connector-3.1/pom.xml
- paimon-hive/paimon-hive-connector-common/pom.xml
- paimon-spark/paimon-spark-2/pom.xml
Support JDK11
issue ref: https://github.com/apache/incubator-paimon/issues/693
regression it/e2e case
no
ye
all the java code change is because different behavior between jdk8 and jdk11:
1. `LocalDateTime.now()` return micro seconds in jdk11 (only return millisecond in jdk8), and the DataFileMeta serialize and deserialize both specify the TimeStamp(3). In jdk11, all the related cases will be broken.
2. Changes in `CachedRandomInputView.java` is to fix concurrency issues.
> [core] support JDK 11

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/util/MiniClusterWithClientExtension.java
`org.apache.paimon.annotation.VisibleForTesting` and `org.apache.paimon.annotation.Experimental` not exsit in flink 1.17,which cause compile fail.
> [flink] modify VisibleForTesting/Experimental annotation package 

- paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyCompactManager.java
- paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java
- paimon-core/src/main/java/org/apache/paimon/compact/CompactManager.java
- paimon-core/src/main/java/org/apache/paimon/compact/CompactTask.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeWriter.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactTask.java
- paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/table/source/AppendOnlySplitGenerator.java
- paimon-core/src/main/java/org/apache/paimon/utils/RecordWriter.java
- paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyCompactManagerTest.java
- paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java
- paimon-core/src/test/java/org/apache/paimon/append/IterativeCompactTaskTest.java
- paimon-core/src/test/java/org/apache/paimon/format/FileFormatSuffixTest.java
- paimon-core/src/test/java/org/apache/paimon/table/AppendOnlyFileStoreTableTest.java
- paimon-core/src/test/java/org/apache/paimon/table/source/SplitGeneratorTest.java
When latest-full streaming reading.
The records order of full reading is wrong. This is because:
New files may be created during the compaction process, then the results of the compaction may be put after the new files, and this order will be disrupted.
We need to ensure this order, so we force the order of files by sequence.
`AppendOnlyFileStoreTableTest.testBatchOrderWithCompaction`
> [core] AppendOnly table full reading order is wrong

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
fix: #794 
module: flink
Show more detailed msg which include the table name when the table doesn't support the lookup join ability.
*(List UT and IT cases to verify this change)* no
*(Does this change affect API or storage format)* no
*(Does this change introduce a new feature)* no
> [Paimon-794][Improvement] Display the specific table name in the error message when the table doesn't support lookup join

- paimon-common/src/main/java/org/apache/paimon/utils/TypeUtils.java
- paimon-common/src/test/java/org/apache/paimon/data/DataFormatTestUtil.java
- paimon-core/src/main/java/org/apache/paimon/casting/CastExecutors.java
- paimon-flink/paimon-flink-common/pom.xml
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlCtasAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTypeUtils.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcBucketStreamPartitioner.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcParsingProcessFunction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecord.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/EventParser.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSinkBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/SchemaAwareStoreWriteOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/SchemaChangeProcessFunction.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FileStoreITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ActionITCaseBase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlContainer.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlCtasActionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlVersion.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSinkITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/SchemaAwareStoreWriteOperatorTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestCdcEventParser.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestCdcSourceFunction.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/util/AbstractTestBase.java
- paimon-flink/paimon-flink-common/src/test/resources/mysql/my.cnf
- paimon-flink/paimon-flink-common/src/test/resources/mysql/setup.sql
This PR introduce `MySqlCtasAction` to consume CDC events from MySQL. Currently this action can only be bundled into user's datastream job. `flink run` support and e2e tests will be added in the next PR.
* MySqlCtasActionITCase
N/A
N/A
> [FLINK-31435] Introduce MySqlCtasAction to consume CDC events from MySQL

- paimon-common/src/main/java/org/apache/paimon/types/DataTypes.java
- paimon-common/src/test/java/org/apache/paimon/format/FileStatsExtractorTestBase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/AppendOnlyTableITCase.java
- paimon-format/src/main/java/org/apache/paimon/format/orc/filter/OrcPredicateFunctionVisitor.java
- paimon-format/src/main/java/org/apache/paimon/format/orc/reader/OrcSplitReaderUtil.java
- paimon-format/src/test/java/org/apache/paimon/format/orc/OrcFileFormatTest.java
- paimon-format/src/test/java/org/apache/paimon/format/orc/OrcFileStatsExtractorTest.java
Fix Timestamp LTZ support for orc and flink.
NOTE: hive spark trino, parquet still not support Timestamp LTZ.
> [Bug] Timestamp LTZ is unsupported for orc

- paimon-benchmark/paimon-micro-benchmarks/pom.xml
- paimon-bundle/pom.xml
- paimon-flink/paimon-flink-common/pom.xml
- paimon-flink/pom.xml
- paimon-hive/paimon-hive-connector-2.3/pom.xml
- paimon-hive/paimon-hive-connector-3.1/pom.xml
- paimon-hive/paimon-hive-connector-common/pom.xml
- paimon-spark/paimon-spark-common/pom.xml
- paimon-spark/pom.xml
- pom.xml
https://github.com/apache/incubator-paimon-shade contains a number of shaded dependencies.
But paimon-shade is in main repo. We should rename it to avoid conflicts with incubator-paimon-shade.
> [pom] Rename paimon-shade to paimon-bundle

- paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/FileStoreTableFactory.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogTest.java
[core][bug] fix the issue of failing to get table with timeTravel semantics from catalog (#731)
The existing `FlinkCatalogTest` can already cover this change. I added the `scan.mode` configuration to `FlinkCatalogTest`.
No changes.
No.
> [core][bug] fix the issue of failing to get table with timeTravel semantics from catalog (#731)

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/DataTableSource.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ReadWriteTableITCase.java
Calculate splits with predicate in DataTableSource for #820 
Test case `testInferParallelism` in `ReadWriteTableITCase`
*(Does this change affect API or storage format)* no
*(Does this change introduce a new feature)* no
> [Bug][Flink] Calculate splits with predicate in DataTableSource

- .github/workflows/e2e-tests-1.14-jdk11.yml
- .github/workflows/e2e-tests-1.14.yml
- .github/workflows/e2e-tests-1.15-jdk11.yml
- .github/workflows/e2e-tests-1.15.yml
- docs/content/engines/hive.md
- paimon-e2e-tests/pom.xml
- paimon-e2e-tests/src/test/java/org/apache/paimon/tests/E2eTestBase.java
- paimon-e2e-tests/src/test/java/org/apache/paimon/tests/cdc/MySql57E2eTest.java
- paimon-e2e-tests/src/test/java/org/apache/paimon/tests/cdc/MySql80E2eTest.java
- paimon-e2e-tests/src/test/java/org/apache/paimon/tests/cdc/MySqlCdcE2eTestBase.java
- paimon-e2e-tests/src/test/resources-filtered/docker-compose.yaml
- paimon-e2e-tests/src/test/resources/mysql/my.cnf
- paimon-e2e-tests/src/test/resources/mysql/setup.sql
- paimon-flink/paimon-flink-1.14/src/main/java/org/apache/paimon/flink/utils/SingleOutputStreamOperatorUtils.java
- paimon-flink/paimon-flink-1.15/src/main/java/org/apache/paimon/flink/utils/SingleOutputStreamOperatorUtils.java
- paimon-flink/paimon-flink-common/pom.xml
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/Action.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSinkBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/SingleOutputStreamOperatorUtils.java
`MySqlSyncTableAction` now supports being used from `bin/flink run`. Users can use `MySqlSyncTableAction` without writing and compiling their own data stream jobs.
* MySql57E2eTest
* MySql80E2eTest
N/A
Document will be introduced in the next PR.
> [flink] MySqlSyncTableAction now supports flink run

- docs/content/filesystems/hdfs.md
- paimon-common/src/main/java/org/apache/paimon/security/HadoopModule.java
- paimon-common/src/main/java/org/apache/paimon/security/HadoopSecurityContext.java
- paimon-common/src/main/java/org/apache/paimon/security/KerberosLoginProvider.java
- paimon-common/src/main/java/org/apache/paimon/security/SecurityConfiguration.java
- paimon-common/src/main/java/org/apache/paimon/security/SecurityContext.java
- paimon-common/src/main/java/org/apache/paimon/utils/StringUtils.java
- paimon-common/src/test/java/org/apache/paimon/security/KerberosLoginProviderITCase.java
Introduce a SecurityContext, this can be used by trino, java api and etc...
KerberosLoginProviderTest
introduce `SecurityContext`.
hdfs.html
> [core] Introduce SecurityContext

- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
`HiveCatalog#dropTable` interface should delete table directory to avoid schema in filesystem exists, especially for external table which doesn't delete directory in filesystem so that recreating the same table cause exception that schema in filesystem exists.
Fix #694.
`HiveCatalog#dropTable` forces to delete table directory to avoid schema in filesystem exists.
> [hive] Dropping table deletes table directory to avoid schema in filesystem exists

- docs/content/api/_index.md
- docs/content/api/java-api.md
- paimon-core/src/main/java/org/apache/paimon/table/sink/BatchWriteBuilder.java
> [doc] Document Java API

- docs/content/how-to/writing-tables.md
- paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/FileStoreTable.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ActionBase.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DeleteAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MergeIntoAction.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/DeleteActionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/MergeIntoActionITCase.java
Currently, the partial update merge engine cannot accept -U/-D records, thus actions that may produce -U/-D records will produce error results. This PR try to solve it.
`DeleteActionITCase`
`MergeIntoActionITCase`
No.
Add hint to how-to#writing tables
> [flink][bug] MergeIntoAction and DeleteAction work abnormally with partial update merge engine

- paimon-benchmark/paimon-cluster-benchmark/src/main/java/org/apache/paimon/benchmark/QueryRunner.java
- paimon-benchmark/paimon-cluster-benchmark/src/main/java/org/apache/paimon/benchmark/metric/FlinkRestClient.java
- paimon-benchmark/paimon-cluster-benchmark/src/main/java/org/apache/paimon/benchmark/metric/MetricReporter.java
- paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
resolve the problem which Sonar reported that InterruptedException need to re-throw or re-interrupt
> [test] resolve the problem which Sonar reported that InterruptedException need to re-throw or re-interrupt

- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/StreamingReadWriteTableWithKafkaLogITCase.java
Enable a flink test since it works in Flink 1.17
> [hotfix] Enable StreamingReadWriteTableWithKafkaLogITCase.testReadInsertOnlyChangelogFromEnormousTimestamp

- paimon-filesystems/paimon-s3-impl/pom.xml
- paimon-filesystems/paimon-s3/pom.xml
- paimon-filesystems/paimon-s3/src/test/java/org/apache/paimon/s3/MinioTestContainer.java
- paimon-filesystems/pom.xml
- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkS3ITCase.java
- paimon-spark/pom.xml
Imgrate MinioTestContainer from the module of spark to paimon-s3 ,in order that orther module such as flink,hive,presto can test the s3 FileSystem.
> Imgrate MinioTestContainer from the module of spark to paimon-s3 

- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/CompactedStartingScanner.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/FullCompactedStartingScanner.java
- paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
- paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/FullCompactedStartingScannerTest.java
- paimon-flink/paimon-flink-1.14/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
- paimon-flink/paimon-flink-1.15/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
> [core] Compacted StartingScanner is incorrect

- docs/content/how-to/creating-catalogs.md
- paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
- paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java
- paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalogFactory.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FileSystemCatalogITCase.java
- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalogFactory.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
issue ref: https://github.com/apache/incubator-paimon/issues/754
Add test cases in ITCase.
Now we lack the UT for the catalog, but there's already an issue https://github.com/apache/incubator-paimon/issues/751 to track this.  So I add the test cases in ITCase temporarily.
no
no
> [flink] support tables inherit not built-in configurations from catalog

- paimon-common/src/main/java/org/apache/paimon/utils/Triple.java
- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreExpireImpl.java
- paimon-core/src/main/java/org/apache/paimon/utils/FileStorePathFactory.java
- paimon-core/src/main/java/org/apache/paimon/utils/PartitionPathUtils.java
- paimon-core/src/test/java/org/apache/paimon/TestFileStore.java
- paimon-core/src/test/java/org/apache/paimon/TestKeyValueGenerator.java
- paimon-core/src/test/java/org/apache/paimon/operation/CleanedFileStoreExpireTest.java
- paimon-core/src/test/java/org/apache/paimon/operation/FileStoreExpireDeleteDirTest.java
- paimon-core/src/test/java/org/apache/paimon/operation/FileStoreTestUtils.java
Currently, after calling `FileStoreExpire#expire()`, unused data files in partition directories will be deleted. But if a directory is empty, it will not be delete. This PR fix it.
`FileStoreExpireDeleteDirTest`
No
No
> [core][bug] The empty data file directories are not deleted after expiring file store

- paimon-core/src/main/java/org/apache/paimon/table/source/DataFilePlan.java
- paimon-core/src/main/java/org/apache/paimon/table/source/InnerStreamTableScanImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/CompactedStartingScanner.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousCompactorStartingScanner.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousFromSnapshotStartingScanner.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousFromTimestampStartingScanner.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousLatestStartingScanner.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/FullStartingScanner.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StartingScanner.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StaticFromSnapshotStartingScanner.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StaticFromTimestampStartingScanner.java
- paimon-core/src/test/java/org/apache/paimon/table/source/StreamTableScanTest.java
- paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/CompactedStartingScannerTest.java
- paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ContinuousCompactorStartingScannerTest.java
- paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ContinuousFromTimestampStartingScannerTest.java
- paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ContinuousLatestStartingScannerTest.java
- paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/FullCompactedStartingScannerTest.java
- paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/FullStartingScannerTest.java
At fully read phase of streaming scan,  the snapshot may not existed in some start up modes. BoundedChecker should not check the snapshot.
`StreamTableScanTest#testStartingFromNonExistingSnapshot`
No
No
> [core][bug] BoundedChecker may check non-existing snapshot at fully read phase

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordKeyAndBucketExtractor.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordKeyAndBucketExtractorTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSinkITCase.java
In `CdcRecordKeyAndBucketExtractor#setRecord` I forget to set `partition`, `bucketKey` and `bucket` to null. Thus a `CdcRecordKeyAndBucketExtractor` instance will only produce 1 constant type of `partition` and `bucket`, which is obviously incorrect.
* CdcRecordKeyAndBucketExtractorTest
* FlinkCdcSinkITCase
N/A
N/A
> [flink][bug] Partition and bucket should be reset when a new record is set in CdcRecordKeyAndBucketExtractor

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/AbstractFlinkTableFactory.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/AbstractFlinkTableFactoryTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/kafka/KafkaLogTestUtils.java
Add the compatibility check between `StartupMode` and `LOG_SYSTEM`.  #846
Added `org.apache.paimon.flink.AbstractFlinkTableFactoryTest#testCreateKafkaLogStoreFactory` to verify compatibility between `StartupMode` and `LOG_SYSTEM`.
No.
No.
> [flink] Add the compatibility check between StartupMode and LOG_SYSTEM

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcMultiTableParsingProcessFunction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/EventParser.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncTableSinkBuilder.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncTableSinkITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestCdcEvent.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestCdcEventParser.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestCdcSourceFunction.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestTable.java
This PR introduces `CdcMultiTableParsingProcessFunction` and `FlinkCdcSyncDatabaseSinkBuilder` which creates a separate Paimon sink for each table in the source database. With the new sink, we can support CDC database syncing.
The current implementation is not very efficient in resource saving. We may refine this implementation by merging all sinks into one instance in the future.
* FlinkCdcSyncDatabaseSinkITCase
N/A
N/A
> [flink] Introduce process functions and sinks for CDC database syncing

- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
Fix the typo in the description of orc.bloom.filter.columns
> [core]Fix the typo in the description of orc.bloom.filter.columns

- docs/content/how-to/cdc-ingestion.md
- paimon-e2e-tests/src/test/java/org/apache/paimon/tests/cdc/MySqlCdcE2eTestBase.java
- paimon-e2e-tests/src/test/resources/mysql/setup.sql
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/Action.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSchema.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionITCaseBase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
- paimon-flink/paimon-flink-common/src/test/resources/mysql/setup.sql
This PR introduces `MySqlSyncDatabaseAction` based on `FlinkCdcSyncDatabaseSinkBuilder`. Users can now synchronize the whole database in MySQL into a Paimon database.
* MySqlSyncDatabaseActionITCase
* MySqlCdcE2eTestBase
Yes. Added help information in `MySqlSyncDatabaseAction`.
Yes. Added documentation in `how-to/cdc-ingestion.md`.
> [flink] Introduce MySqlSyncDatabaseAction

- docs/content/api/java-api.md
`TableCommit#abort` is introduced at present to abort unsuccessful commit like Hive write etc. `TableCommit#abort` should document the java api.
No tests.
No affect.
Document `TableCommit#abort`.
> [doc] document TableCommit#abort java api

- paimon-e2e-tests/src/test/java/org/apache/paimon/tests/E2eTestBase.java
fix #874 
I'll give the conclusion at first: the version of docker compose on Mac(v2.17.2) is higher than github actions environment(v1.29.2). 
Docker Compose is introduced by Docker Desktop in the local MacOS environment. While in the CI container of github actions,  Docker Compose is not pre-installed, which is introduced by testcontainers in ContainerisedDockerCompose. The version of Docker Compose is hard coded as "docker/compose:1.29.2"
In Docker Compose v1.29.2, it'll call NetworkInspect API of the docker engine for external network searching. Within the backend implementation, it'll search the external networks with filter 'idOrName'，that's why the e2e tests can always be passed whether the $NETWORK_ID  is set with netword.id or netword.name.
**Docker compose: call inspect() by …
> [test] Set docker environment with network name instead of netword id

- paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
- paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
- paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
- paimon-core/src/test/java/org/apache/paimon/table/SchemaEvolutionTest.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/SchemaChangeProcessFunction.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncTableSinkITCase.java
This pr closes #900 
At present, the columns `already exists` and `does not exist` abnormal printing information are as follows:
Modified:
> [hotfix] add column 'already exists' and 'does not exist' exception type

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSchema.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTypeUtils.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcMultiTableParsingProcessFunction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcParsingProcessFunction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/EventParser.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncTableSinkBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/NewDataFieldListProcessFunction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunction.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestCdcEvent.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestCdcEventParser.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestTable.java
- paimon-flink/paimon-flink-common/src/test/resources/mysql/setup.sql
Currently `MySqlDebeziumJsonEventParser` parses `ALTER TABLE` statement with a regular expression. This regular expression can only deal with a single change in the statement.
This PR further utilizes the information in debizum json format to support multiple changes in one ALTER TABLE statement.
* MySqlSyncTableActionITCase#testMultipleSchemaEvolutions
N/A
N/A
> [flink] MySql CDC can now deal with multiple changes in one ALTER TABLE statement

- README.md
- pom.xml
After #884, project building time increases from 5 minutes to 15 minutes in a github action. This is because downloading dependencies from apache repositories is very slow.
This PR comments the repositories tag in pom.xml to speed up maven build. This PR also adds a notice in the README file for users who do not have a snapshot repositories in their maven settings.
N/A
N/A
N/A
> [pom] Comment the repositories tag in pom.xml to speed up maven build

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FileStoreSourceReader.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FileStoreSourceReaderTest.java
This PR fixes #657.
We now explain this bug by analyzing the following log.
```
org.apache.flink.runtime.source.coordinator.SourceCoordinator [] - Source Source: paimon-adbedf45-0cf5-43df-b62a-1dae79a5dc62.default.ts_table received split request from parallel task 0
org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Source: paimon-adbedf45-0cf5-43df-b62a-1dae79a5dc62.default.ts_table -> Calc(select=[dt, k, v], where=[(dt < _UTF-16LE'2023-01-17')]) -> NotNullEnforcer(fields=[dt, k]) -> TableToDataSteam(type=ROW<`dt` STRING NOT NULL, `k` INT NOT NULL, `v` INT> NOT NULL, rowtime=false) -> Map (1/1) (85791e7e8233fe32e987a2ed56087f0b) switched from INITIALIZING to RUNNING.
org.apache.flink.connector.base.source.reader.SourceReaderBase [] - Adding split(s) to reader: …
```
> [flink][bug] FileStoreSourceReader in Flink connector should only send split request after all given splits are consumed

- paimon-common/src/main/java/org/apache/paimon/plugin/PluginLoader.java
PluginLoader should use yarn tmp directory for yarn cluste
> [hotfix]PluginLoader should use yarn tmp directory for yarn cluster 

- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactActionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/DeleteActionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/DropPartitionActionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionITCaseBase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTestBase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CompactorSinkITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncTableSinkITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/CompactorSourceITCase.java
Use new ReadBuilder and WriteBuilder API in tests of paimon-flink module
sub-task of #639
> [flink] Use new ReadBuilder and WriteBuilder API in tests of paimon-flink module

- pom.xml
the NOTICE years of the META-INFO/NOTICE file nested in the generated jars are not correct(This problem exists in all modules that automatically generate NOTICE files.)
The cause of the problem is that the parent class `apache-23` has a maven attribute `<project.build.outputTimestamp>2020-01-22T15:10:15Z</project.build.outputTimestamp>`
https://github.com/apache/maven-apache-parent/blob/99592e229c20f079c1998875e5c24556d217b491/pom.xml#L95
Modified:
> [release] Fix the NOTICE years of the META-INFO/NOTICE file nested in the generated jars are not correct

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunction.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
- paimon-flink/paimon-flink-common/src/test/resources/mysql/setup.sql
This PR fixes #943.
Currently, running MySQL actions on existing tables may throw schema unmatch exception, even if Paimon schema and MySQL schema actually match. This is because we use `UpdatedDataFieldsProcessFunction.canConvert` to check if the schema matches, but `UpdatedDataFieldsProcessFunction.canConvert` does not deal with the case when `oldType` and `newType` are equal.
* MySqlSyncTableActionITCase#testAllTypes
N/A
N/A
> [flink][bug] Fix bug that running MySQL actions on existing tables throws schema unmatch exception

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTypeUtils.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
- paimon-flink/paimon-flink-common/src/test/resources/mysql/setup.sql
fix https://github.com/apache/incubator-paimon/issues/943
* check compatibility for some data type : decimal , date ，timestamp, longtext, longblob *
> [flink] check compatibility for some data type

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionITCaseBase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
- paimon-flink/paimon-flink-common/src/test/resources/mysql/my.cnf
This PR fixes #945.
According to [MySQL standard](https://dev.mysql.com/doc/refman/8.0/en/datetime.html), display value of datetime is not affected by server time zone. So current implementation of `MySqlDebeziumJsonEventParser` is not correct when parsing datetime.
* MySqlSyncTableActionITCase#testAllTypes
N/A
N/A
> [flink][bug] Datetime parsing should not be affected by server time zone in MySqlDebeziumJsonEventParser

- paimon-core/src/test/java/org/apache/paimon/table/AppendOnlyFileStoreTableTest.java
- paimon-core/src/test/java/org/apache/paimon/table/ChangelogValueCountFileStoreTableTest.java
- paimon-core/src/test/java/org/apache/paimon/table/ChangelogWithKeyFileStoreTableTest.java
- paimon-core/src/test/java/org/apache/paimon/table/WritePreemptMemoryTest.java
TraceableFileIO is for testing connection leak
> [test] FileStoreTableTestBases should use TraceableFileIO

- .gitignore
- .idea/vcs.xml
Add IssueNavigationLink for IDEA, so we would click the link to jira and PR from IDEA
None
None
None
> [hotfix] Add IssueNavigationLink for IDEA git log

- docs/content/engines/overview.md
- docs/content/engines/spark3.md
- docs/content/project/download.md
- paimon-spark/paimon-spark-3.4/pom.xml
- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadITCase.java
- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkSchemaEvolutionITCase.java
- paimon-spark/pom.xml
Apache Spark 3.4.0 is the fifth release of the 3.x line. Paimon could support the integration with Spark 3.4. The release note of Spark 3.4.0 is [Spark Release 3.4.0](https://spark.apache.org/releases/spark-release-3-4-0.html).
Fix #920.
Document adds Spark 3.4 into the supported version of Spark.
> [spark] Support Spark 3.4

- docs/content/project/contributing.md
fix doc, spell error.
Paimpn --> Paimon
no change
yes
Only to fix paimon spell.
> [doc] Paimon is misspelled

- docs/content/how-to/cdc-ingestion.md
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSchema.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/TableNameConverter.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
- paimon-flink/paimon-flink-common/src/test/resources/mysql/setup.sql
Fix #1017 
`MySqlSyncDatabaseActionITCase#testTableAffix`
New args for mysql-sync-database:
--table-prefix
--table-suffix
both are optional
CDC Ingestion # Synchronizing Databases
> [flink] Support specifying table affix in MySQL CDC action

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTypeUtils.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionITCaseBase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
This PR fixes #1020.
In MySQL, `datetime` and `timestamp` default precision is 0 (see https://dev.mysql.com/doc/refman/8.0/en/date-and-time-type-syntax.html). However in Paimon, `timestamp` default precision is 6.
This PR fixes the conversion between MySQL `datetime` / `timestamp` types with default precision and Paimon `timestamp` type.
* `MySqlSyncTableActionITCase#testAllTypes`
N/A
N/A
> [flink][bug] MySQL datetime and timestamp default precision should be 0

- docs/content/how-to/cdc-ingestion.md
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
- paimon-flink/paimon-flink-common/src/test/resources/mysql/setup.sql
As title.
`MySqlSyncDatabaseActionITCase#testIncludingTable`
`MySqlSyncDatabaseActionITCase#testExcludingTable`
New args of mysql-sync-database:
`--including-table`
`--excluding-table`
CDC Ingestion # Synchronizing Databases
> [flink] Support specifying including or excluding source tables in MySQL CDC action

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/FlinkCatalogPropertiesUtil.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogPropertiesUtilTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ReadWriteTableITCase.java
Flink table can define non-physical columns. If do, the Paimon table put the descriptions of non-physical columns to TableSchema. Current implementation will put unnecessary informations (physical columns, pks) into options. We can clean them.
`FlinkCatalogPropertiesUtilTest`
`ReadWriteTableITCase#testCleanedSchemaOptions`
`ReadWriteTableITCase#testReadFromOldStyleSchemaOptions`
No
No
> [flink] Don't serialize physical column and primary keys to TableSchema options when table has non-physical columns and watermark

- docs/content/how-to/cdc-ingestion.md
Currently links for `MySqlSyncTableAction` and `MySqlSyncDatabaseAction` in https://paimon.apache.org/docs/master/how-to/cdc-ingestion/ is broken.
N/A
N/A
N/A
> [docs][bug] Fix Java API link for MySqlSyncTableAction and MySqlSyncDatabaseAction in cdc-ingestion docs

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecord.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordKeyAndBucketExtractor.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestTable.java
Currently `CdcRecord#toGenericRow` ignores `CdcRecord.kind`. This is incorrect because by ignoring `CdcRecord.kind` we'll never delete records from Paimon sink.
#1032 fixes this issue. This PR mainly adds tests for the fix.
* `FlinkCdcSyncTableSinkITCase#testRandomCdcEvents`
* `MySqlSyncTableActionITCase#testSchemaEvolution`
N/A
N/A
> [flink][bug] CdcRecord#toGenericRow should respect CdcRecord.kind

- paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeReaders.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ChangelogMergeTreeRewriter.java
- paimon-format/src/main/java/org/apache/paimon/format/orc/OrcReaderFactory.java
readers don't close while io exception happening, the readers cached in the list will lose control (#1036)
> [core][bug] readers don't close while io exception happening

- paimon-core/src/main/java/org/apache/paimon/table/source/InnerStreamTableScanImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/source/OutOfRangeException.java
- paimon-core/src/test/java/org/apache/paimon/table/source/StreamTableScanTest.java
[core] add range check of snapshot id during scan to prevent endless waiting.  This will fix #807 .
No.
No.
No.
> [core] add range check of snapshot id during scan to prevent endless waiting

- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeReaders.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ChangelogMergeTreeRewriter.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FullChangelogMergeTreeCompactRewriter.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeTreeCompactRewriter.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LoserTree.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactRewriter.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/SortMergeReader.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/SortMergeReaderWithLoserTree.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/SortMergeReaderWithMinHeap.java
- paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreRead.java
- paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTest.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTestBase.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/compact/CombiningRecordReaderTestBase.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/compact/ConcatRecordReaderTest.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LoserTreeTest.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/compact/SortMergeReaderTestBase.java
[Feature] Optimize SortMergeReader: use loser tree to reduce comparisons (#741)
- Unit Tests: `SortMergeReaderTestBase` already exists to verify the correctness of `SortMergeReader`.
- Benchmark：I created a jmh benchmark to compare the performance of different implementations，Here is the [benchmark code](https://github.com/liming30/paimon-benchmark/blob/master/src/main/java/com/bytedance/MergeReaderBenchmark.java).
From the benchmark results, there is almost no difference between `loser-tree` and `min-heap` when `RecordReader`/`data volume` is small. With the increase of `RecordReader`/`data volume`, there can be about 10% performance improvement.
```
Benchmark                               (readersNum)  (recordNum)  Mode  Cnt     Score    Error  Units
MergeReaderBenchmark.group:min-heap …
```
>  [Feature] Optimize SortMergeReader: use loser tree to reduce comparisons

- docs/content/how-to/querying-tables.md
- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-core/src/main/java/org/apache/paimon/consumer/Consumer.java
- paimon-core/src/main/java/org/apache/paimon/consumer/ConsumerManager.java
- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreExpireImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/source/AbstractInnerTableScan.java
- paimon-core/src/main/java/org/apache/paimon/table/source/InnerStreamTableScanImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/source/StreamTableScan.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotSplitReader.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotSplitReaderImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
- paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
- paimon-core/src/test/java/org/apache/paimon/consumer/ConsumerManagerTest.java
- paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkRowData.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/DataTableSource.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkSourceBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/MonitorFunction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/ReadOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/JavaSerializer.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/JavaTypeInfo.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FileStoreITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumeratorTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/operator/OperatorSourceTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/utils/JavaSerializerTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/utils/JavaTypeInfoTest.java
fix #881
This PR is intended to introduce a consume mode, when a `consume-id` is specified, scan will writes the progress of the consume to the file system, which has several advantages:
1. When the job is killed, the newly started job can continue to consume from the previous progress without resuming from the state.
2. When deleting expired snapshots, it ensures that the snapshot being consumed will not be deleted, so that the consumer will not read the expired snapshot and get hung.
This PR also introduces a new Source implementation:
- MonitorFunction
- ReadOperator
This is to avoid Flink's Source interface forcing a checkpoint on Splits, which may only read part of the snapshot data when consuming, the progress of consuming cannot be recorded.
Added.
> [core] Introduce consume-id for retore consuming and reserve snapshot

- docs/content/engines/hive.md
- docs/content/how-to/creating-tables.md
- paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/HiveSchema.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/PaimonMetaHook.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/CreateTableITCase.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
- Recommend creating table without location in hive
- Creating external table without existing paimon  table is not recommended
`HiveCatalogITCaseBase.testHiveCreateAndFlinkRead`
Hive related
> [hive] Recommend creating table without location in hive

- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-core/src/main/java/org/apache/paimon/AppendOnlyFileStore.java
- paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java
- paimon-core/src/main/java/org/apache/paimon/manifest/AbstractManifestEntry.java
- paimon-core/src/main/java/org/apache/paimon/manifest/ManifestEntry.java
- paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java
- paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreScan.java
- paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreScan.java
- paimon-core/src/main/java/org/apache/paimon/utils/ParallellyExecuteUtils.java
- paimon-core/src/test/java/org/apache/paimon/utils/ParallellyExecuteUtilsTest.java
[core] limit parallelly read file memory usage, extract some methods(#1061)
> [core] limit parallelly read file memory usage, extract some methods

- paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/operation/MemoryFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/TableWrite.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/TableWriteImpl.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWriteImpl.java
Add withMemoryPool for TableWrite and different engines can create memory pool for paimon writer buffer
Fix #1070 
Existing tests can cover this feature
1. Add withMemoryPool in TableWrite
> [core] Add withMemoryPool for TableWrite

- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
At present, the default value for `continuous.discovery-interval` is 1 second, which is too short and can cause frequent access to the file system, causing significant pressure.
We can modify its default value to 10 seconds, as our current recommended stream read delay is 30 seconds to 1 minute, which does not have a significant impact.
No
No
Yes
> [core] The default value of continuous.discovery-interval can be 10 s

- docs/content/how-to/altering-tables.md
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java
fix #1111 
Flink is able to modify nullable column to not null column by setting `table.exec.sink.not-null-enforcer` to `DROP` to dropping those null-value records with not-null column silently.
> [flink] Support nullability change when altering table on flink 1.17

- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java
This commit (31ce2f87a8d9c1ae15584b606007a52b243b34f8) changed default value of `continuous.discovery-interval` from 1s to 10s. So the `testForeignKeyJoin` maybe failed because the data of dim table are not discovered.
Add `continuous.discovery-interval=1s` for table properties in `PartialUpdateITCase `
`PartialUpdateITCase#testForeignKeyJoin`
> [hotfix] Fix failed test PartialUpdateITCase#testForeignKeyJoin

- docs/content/how-to/cdc-ingestion.md
- paimon-common/src/main/java/org/apache/paimon/utils/DateTimeUtils.java
- paimon-e2e-tests/src/test/java/org/apache/paimon/tests/cdc/MySqlCdcE2eTestBase.java
- paimon-e2e-tests/src/test/java/org/apache/paimon/tests/cdc/MySqlComputedColumnE2ETest.java
- paimon-e2e-tests/src/test/resources/mysql/setup.sql
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/ColumnValueComputer.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/ComputedColumn.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/Expression.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSchema.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionITCaseBase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
- paimon-flink/paimon-flink-common/src/test/resources/mysql/setup.sql
Base of #1077 and #1038 
`MySqlComputedColumnE2ETest`
`MySqlSyncTableActionITCase#testComputedColumn`
New argument in mysql-sync-table:
--computed-column
CDC Ingestion
> [flink] Add base support of computed column for CDC

- docs/content/how-to/cdc-ingestion.md
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/Expression.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
Support `substring(column, begin, end)'.
`MySqlSyncTableActionITCase#testComputedColumn`
Add new expression for cdc action:
mysql-sync-table
Synchronizing Tables
> [flink] Support 'substring' for cdc computed column

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FileStoreSourceSplitReader.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/RecordsFunction.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FileStoreSourceSplitReaderTest.java
Implements SourceReader.pauseOrResumeSplit for flink-1.17.  close #788 
Add `org.apache.paimon.flink.source.FileStoreSourceSplitReaderTest#testPauseOrResumeSplits` to verify correctness.
No.
No.
> [flink] implements SourceReader.pauseOrResumeSplit for flink-1.17

- docs/content/maintenance/write-performance.md
> Introduce how the read.batch-size option can impact memory consumption when compaction in write-performance page

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CompactorSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FileStoreSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSink.java
Replace `org.apache.flink.util.function.SerializableFunction` by paimon's implementation.
Should be covered by existing tests already.
No changes.
No need.
> [flink] Replace org.apache.flink.util.function.SerializableFunction by paimon's implementation.

- docs/content/how-to/writing-tables.md
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkTableSink.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ReadWriteTableITCase.java
Support `RowLevelDelete` for `ChangelogValueCountFileStoreTable`.  close #1215 
Modified `org.apache.paimon.flink.ReadWriteTableITCase#testDeleteWithoutPrimaryKey` to verify correctness.
No.
No.
> [flink] support RowLevelDelete for ChangelogValueCountFileStoreTable.

- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/HiveSchema.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/PaimonStorageHandlerITCase.java
When reading from Hive, the  current `HiveSchema` maybe constructed from Hive schema infomation even Paimon schema is available. This PR fix it.
This PR can fix #1198 because now the `TIMESTAMP` precision can be set correctly.
`PaimonStorageHandlerITCase#testDateAndTimestamp`
no
no
> [hive] Hive read paimon table should always build schema from existing Paimon table schema first

- paimon-codegen/src/main/java/org/apache/paimon/codegen/CodeGeneratorImpl.java
- paimon-codegen/src/main/scala/org/apache/paimon/codegen/CodeGeneratorContext.scala
- paimon-codegen/src/main/scala/org/apache/paimon/codegen/EqualiserCodeGenerator.scala
- paimon-codegen/src/main/scala/org/apache/paimon/codegen/GenerateUtils.scala
- paimon-codegen/src/main/scala/org/apache/paimon/codegen/ScalarOperatorGens.scala
- paimon-codegen/src/test/java/org/apache/paimon/codegen/EqualiserCodeGeneratorTest.java
- paimon-common/src/main/java/org/apache/paimon/codegen/CodeGenerator.java
- paimon-common/src/main/java/org/apache/paimon/codegen/RecordEqualiser.java
- paimon-common/src/main/java/org/apache/paimon/utils/InternalRowUtils.java
- paimon-common/src/main/java/org/apache/paimon/utils/TypeCheckUtils.java
- paimon-core/src/main/java/org/apache/paimon/codegen/CodeGenUtils.java
Introduce RecordEqualiser for InternalRow to speed up the judgment of equality. close #1102 
Almost all the codes come from `Flink`, and I removed the related codes for unsupported types in `Paimon` (such as `INTERVAL_YEAR_MONTH`, `RAW`, etc.). At the same time, since the two types currently involved in the comparison in `Paimon` are the same, I removed the relevant code for casting the type.
Add unit test to verify the correctness of `EqualiserCodeGenerator`.
- org.apache.paimon.codegen.EqualiserCodeGeneratorTest#testSingleField
- org.apache.paimon.codegen.EqualiserCodeGeneratorTest#ttestManyFields
No.
No.
> [codegen] Introduce RecordEqualiser for InternalRow to speed up the judgment of equality

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
the[ paimon doc](https://paimon.apache.org/docs/master/how-to/cdc-ingestion/#synchronizing-tables) desc that we can use DataStream to use `MySqlSyncTableAction`,  but when we use the action in DataStream, it throw an exception 
`MySqlSyncTableAction(java.util.Map<java.lang.String,java.lang.String>, java.lang.String, java.lang.String, java.lang.String, java.util.List<java.lang.String>, java.util.List<java.lang.String>, java.util.Map<java.lang.String,java.lang.String>, ...)' is not public in 'org.apache.paimon.flink.action.cdc.mysql.MySqlSyncTableAction'. Cannot be accessed from outside package`
so I think we may need to make the construct method to public.
> [flink] make sync action construct method to public

- paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ChangelogMergeTreeRewriter.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FullChangelogMergeFunctionWrapper.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FullChangelogMergeTreeCompactRewriter.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapper.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeTreeCompactRewriter.java
- paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/utils/ValueEqualiserSupplier.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/compact/FullChangelogMergeFunctionWrapperTestBase.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapperTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/TestChangelogDataReadWrite.java
Replace ValueComparatorSupplier with ValueEqualiserSupplier.  fix #1100 
Modify the existing unit tests to verify correctness:
- `org.apache.paimon.mergetree.compact.FullChangelogMergeFunctionWrapperTestBase`
- `org.apache.paimon.mergetree.compact.LookupChangelogMergeFunctionWrapperTest`
No.
No.
> [core] replace ValueComparatorSupplier with ValueEqualiserSupplier.

- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/mapred/PaimonOutputCommitter.java
Fix hive writer memory leak #1191 
every map task  are not close writer ,it causes more memory required.
no
no
no
> [hive] Fix hive writer memory leak

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
When we use flink api to develop some program, we need the `org.apache.paimon.table.Table` object, and we can use the follow code to get the `Table`  directly， it is very convenient，so I think we may remove the `VisibleForTesting` annotation from `FlinkCatalog#catalog` method
```
FlinkCatalog catalog = (FlinkCatalog) tenv.getCatalog(catalogName).get();
Table table = catalog.catalog().getTable(new Identifier(databaseName, tableName));
```
> [flink] rm VisibleForTesting annotation from FlinkCatalog#catalog method

- docs/content/how-to/writing-tables.md
With issue: how to insert into a non-null column with nullable column. One work around method.
see: https://github.com/apache/incubator-paimon/issues/1048
> [docs] add docs: how to insert into a non-null column with nullable column

- docs/content/api/flink-api.md
- docs/content/how-to/cdc-ingestion.md
- paimon-common/src/main/java/org/apache/paimon/utils/ObjectUtils.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/canal/CanalJsonEventParser.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcMultiTableParsingProcessFunction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcMultiplexRecord.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcParsingProcessFunction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecord.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordKeyAndBucketExtractor.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreWriteOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordUtils.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcSinkBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/EventParser.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaEventParserTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncTableSinkITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestCdcEventParser.java
Paimon supports a variety of ways to ingest data into Paimon tables with schema evolution. This means that the added
columns are synchronized to the Paimon table in real time and the synchronization job is not restarted for this purpose.
We currently support the following sync ways:
1. MySQL Synchronizing Table: synchronize one or multiple tables from MySQL into one Paimon table.
2. MySQL Synchronizing Database: synchronize the whole MySQL database into one Paimon database.
3. [API Synchronizing Table]({{< ref "/api/flink-api#cdc-ingestion-table" >}}): synchronize your custom DataStream input into one Paimon table.
This PR aims to introduce API for Synchronizing Table, Many users have various customization needs, and we provide APIs for them to meet their specific business needs
No
Yes …
> [flink] Introduce API to Synchronizing Table

- docs/content/concepts/primary-key-table.md
- paimon-common/src/main/java/org/apache/paimon/types/RowKind.java
- paimon-core/src/main/java/org/apache/paimon/KeyValue.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeFunctionFactory.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java
- paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreRead.java
- paimon-core/src/main/java/org/apache/paimon/table/ChangelogWithKeyFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/SequenceGenerator.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunctionTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java
A sequence-field may not solve the disorder problem of partial-update tables with multiple stream updates, because the sequence-field may be overwritten by the latest data of another stream during multi-stream update.
So we introduce sequence group mechanism for partial-update tables. It can solve:
1. Disorder during multi-stream update. Each stream defines its own sequence-groups.
2. A true partial-update, not just a non-null update.
Both UT & IT
```
CREATE TABLE T (
k INT,
a INT,
b INT,
g_1 INT,
c INT,
d INT,
g_2 INT,
PRIMARY KEY (k) NOT ENFORCED
) WITH (
'merge-engine'='partial-update',
'fields.g_1.sequence-group'='a,b',
'fields.g_2.sequence-group'='c,d'
);
```
Yes
> [core] Introduce sequence group to partial update

- paimon-core/src/main/java/org/apache/paimon/manifest/WrappedManifestCommittable.java
- paimon-core/src/test/java/org/apache/paimon/manifest/WrappedManifestCommittableTest.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RestoreAndFailCommittableStateManager.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreMultiCommitter.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/WrappedManifestCommittableSerializer.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/StoreMultiCommitterTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/WrappedManifestCommittableSerializerTest.java
This PR implements a committer that commits changes to multiple tables during MySQL CDC ingestion. Second part of #1181 .
Yes.
No.
No.
> [feature] Add multi-table committer

- docs/layouts/shortcodes/generated/flink_connector_configuration.html
- paimon-common/src/main/java/org/apache/paimon/memory/AbstractMemorySegmentPool.java
- paimon-common/src/main/java/org/apache/paimon/memory/MemorySegment.java
- paimon-common/src/main/java/org/apache/paimon/utils/ReflectionUtils.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/memory/FlinkMemorySegmentPool.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/memory/MemorySegmentAllocator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/GlobalFullCompactionSinkWrite.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/PrepareCommitOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowDataStoreWriteOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCompactOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWrite.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWriteImpl.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreWriteOperator.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperatorTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreWriteOperatorTest.java
Fix #1071 Use flink managed memory for writer buffer in paimon
1. Add options `sink.use-managed-memory-allocator` and `sink.managed.writer-buffer-memory` for flink managed memory
2. Calculate managed memory weight in FlinkSink
3. Create memory pool for paimon writer in RowDataStoreWriteOperator
1. Added test case ContinuousFileStoreITCase.testFlinkMemoryPool
no
no
> [flink] Support flink managed memory for writer buffer

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/LogHybridSourceFactory.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/kafka/KafkaLogTestUtils.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/LogHybridSourceFactoryTest.java
Restore kafka source should not throw NPE exception.
> [flink] Fix kafka hybrid restore enumerator

- paimon-core/src/main/java/org/apache/paimon/manifest/ManifestEntry.java
- paimon-core/src/main/java/org/apache/paimon/manifest/ManifestFileMeta.java
- paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileMetaTest.java
- paimon-core/src/test/java/org/apache/paimon/manifest/NoPartitionManifestFileMetaTest.java
We can check the deleteEntries to skip base file which has not deletion.
This is useful for non-partition tables.
This is related to #1245
> [core] Skip more unwanted merges for Manifest full compaction

- docs/content/how-to/querying-tables.md
- docs/content/maintenance/write-performance.md
Fix the ref link with secondary titles and typo, which couldn't find the exact resource.
1. 'compactions' -> 'compaction'
2. Remove the h1 headings in the ref link.
> [docs] Fix ref link with secondary titles

- docs/content/how-to/querying-tables.md
Document how to travel to snapshot with 'scan.mode'='from-snapshot-full', to describe clear the traveling will be with the mode of 'from-snapshot' by default if use specify the 'scan.snapshot-id'.
> [docs] Document how to travel to snapshot with mode 'from-snapshot-full'

- paimon-common/src/main/java/org/apache/paimon/utils/BinPacking.java
- paimon-common/src/test/java/org/apache/paimon/utils/BinPackingTest.java
The packing method will return one empty list while binItems is empty and the next file weight is bigger than targetWeight.
e.g The first item weight is 500, the target is 400, then this method will pack a redundant empty list.
We need to check binItems' size
> [bug] bugfix: packing return one empty list

- paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/BatchWriteBuilderImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/InnerTableWrite.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/TableWriteImpl.java
- paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java
- paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ContinuousCompactorFollowUpScannerTest.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWriteImpl.java
In writers, the overwrite flag does not overwrite actually. It just don't scan restored files, so empty writer is a more suitable name maybe. 
This pull request shift name withOverWrite to fromEmptyWriter.
> [core] rename withOverwrite to fromEmptyWriter

- docs/content/maintenance/read-performance.md
- paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
- paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/GlobalFullCompactionSinkWrite.java
Linked issue: close #1302
After modifying this to safely loop, we can remove limitation in documentation, users can set a free full compaction commits delta.
`SnapshotManagerTest.testTraversalSnapshotsFromLatestSafely`.
> [flink] Avoid FileNotFoundException in snapshot loop

- docs/layouts/shortcodes/generated/flink_connector_configuration.html
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/CompactorSourceBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkSourceBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/LogHybridSourceFactory.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/StaticFileStoreSource.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/StaticFileStoreSplitEnumerator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/SystemTableSource.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/assigners/FairSplitAssigner.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/assigners/PreemptiveSplitAssigner.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/assigners/SplitAssigner.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FairAssignModeTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/PreemptiveAssignModeTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/StaticFileStoreSplitEnumeratorTestBase.java
Provide a mode to fall back to the previous preemptive mode in `StaticFileStoreSplitEnumerator`. closes #851 
Added `org.apache.paimon.flink.source.PreemptiveAssignModeTest` to verify the correctness of preemptive mode.
No.
No.
> [flink] Provide a preemptive mode in StaticFileStoreSplitEnumerator

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
In `MySqlSyncDatabaseAction`, if user has specified `ignoreIncompatible = true`, and the table is not compatible, we should ignore it. However, current implementation still add the ignored table to `fileStoreTables`, then in `FlinkCdcSyncDatabaseSinkBuilder` a `DataStream<Void> schemaChangeProcessFunction` will be created, which is unnecessary.
So this PR remove the ignored table.
no
no
> [flink][bug] MySqlSyncDatabaseActionITCase doesn't need to handle incompatible table

- paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-core/src/main/java/org/apache/paimon/table/source/AbstractInnerTableScan.java
- paimon-core/src/main/java/org/apache/paimon/table/source/InnerStreamTableScanImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousAppendAndCompactFollowUpScanner.java
- paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ContinuousAppendAndCompactFollowUpScannerTest.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/CompactorSourceBuilder.java
Add Scan Type "non-bucket" which is used for non-bucket compaction.
When we assigned "non-bucket", we will use 'FullStartingUpScanner' and 'ContinuousAppendAndCompactScanner' to invoke streaming scan.
> [core] add scan type for non-bucket compaction

- paimon-common/pom.xml
- paimon-common/src/main/java/org/apache/paimon/utils/Int2ShortHashMap.java
- paimon-common/src/main/java/org/apache/paimon/utils/IntHashSet.java
- paimon-common/src/main/resources/META-INF/NOTICE
- paimon-common/src/test/java/org/apache/paimon/utils/Int2ShortHashMapTest.java
- paimon-common/src/test/java/org/apache/paimon/utils/IntHashSetTest.java
They are used for dynamic bucket tables.
> [core] Introduce IntHashSet and Int2ShortHashMap

- paimon-common/src/main/java/org/apache/paimon/utils/IntFileUtils.java
- paimon-common/src/main/java/org/apache/paimon/utils/IntIterator.java
- paimon-common/src/test/java/org/apache/paimon/utils/IntHashSetTest.java
- paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
- paimon-core/src/main/java/org/apache/paimon/FileStore.java
- paimon-core/src/main/java/org/apache/paimon/Snapshot.java
- paimon-core/src/main/java/org/apache/paimon/index/HashIndexFile.java
- paimon-core/src/main/java/org/apache/paimon/index/IndexFileHandler.java
- paimon-core/src/main/java/org/apache/paimon/index/IndexFileMeta.java
- paimon-core/src/main/java/org/apache/paimon/index/IndexFileMetaSerializer.java
- paimon-core/src/main/java/org/apache/paimon/io/IndexIncrement.java
- paimon-core/src/main/java/org/apache/paimon/manifest/IndexManifestEntry.java
- paimon-core/src/main/java/org/apache/paimon/manifest/IndexManifestEntrySerializer.java
- paimon-core/src/main/java/org/apache/paimon/manifest/IndexManifestFile.java
- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/CommitMessageImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/CommitMessageSerializer.java
- paimon-core/src/main/java/org/apache/paimon/utils/FileStorePathFactory.java
- paimon-core/src/test/java/org/apache/paimon/TestFileStore.java
- paimon-core/src/test/java/org/apache/paimon/index/HashIndexFileTest.java
- paimon-core/src/test/java/org/apache/paimon/index/IndexFileMetaSerializerTest.java
- paimon-core/src/test/java/org/apache/paimon/manifest/IndexManifestEntrySerializerTest.java
- paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java
- paimon-core/src/test/java/org/apache/paimon/operation/FileStoreCommitTest.java
- paimon-core/src/test/java/org/apache/paimon/table/sink/CommitMessageSerializerTest.java
- paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java
The index file is partition + bucket granularity.
This is the pre work of dynamic buckets, which allows for saving which keys are contained in a bucket in dynamic bucket mode, in order to locate the bucket of the key.
> [core] Introduce index metadata

- paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java
- paimon-core/src/main/java/org/apache/paimon/index/HashBucketAssigner.java
- paimon-core/src/main/java/org/apache/paimon/index/HashIndexMaintainer.java
- paimon-core/src/main/java/org/apache/paimon/index/IndexMaintainer.java
- paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/operation/MemoryFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/DynamicBucketRow.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/DynamicBucketRowKeyExtractor.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/TableWriteImpl.java
- paimon-core/src/test/java/org/apache/paimon/catalog/PrimaryKeyTableTestBase.java
- paimon-core/src/test/java/org/apache/paimon/index/HashBucketAssignerTest.java
- paimon-core/src/test/java/org/apache/paimon/index/HashIndexMaintainerTest.java
- paimon-core/src/test/java/org/apache/paimon/table/sink/TableWriteTest.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWriteImpl.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/TestChangelogDataReadWrite.java
Prepare classes for dynamic bucket for paimon-core
> [core] Introduce IndexMaintainer to FileStoreWrite and HashBucketAssigner

- docs/content/concepts/primary-key-table.md
- docs/content/how-to/cdc-ingestion.md
- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/DynamicBucketRowWriteOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/DynamicBucketSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/HashBucketAssignerOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowDynamicBucketSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/TableWriteOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcDynamicBucketSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcDynamicBucketWriteOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcHashKeyChannelComputer.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordKeyAndBucketExtractor.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcSinkBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcWithBucketChannelComputer.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/DynamicBucketTableITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncTableSinkITCase.java
A bucket is the smallest storage unit for reads and writes, each bucket directory contains an [LSM tree].
Primary Key Table supports two bucket mode:
1. Fixed Bucket mode: configure a bucket greater than 0, rescaling buckets can only be done through offline processes, 
see [Rescale Bucket]. A too large number of buckets leads to too many
small files, and a too small number of buckets leads to poor write performance.
2. Dynamic Bucket mode: configure `'bucket' = '-1'`, Paimon dynamically maintains the index, keeping the data volume
in the bucket below `'dynamic-bucket.target-row-num'`. (This is an experimental feature)
> [flink] Introduce Dynamic bucket sink to Flink

- paimon-core/pom.xml
Use Maven 3.2.5 to build paimon-core will throw error: cannot find org.apache.hadoop.hive.ql.exec.vector.
> [hotfix] Fix that Maven 3.2.5 cannot build paimon-core

- paimon-core/src/main/java/org/apache/paimon/compact/CompactFutureManager.java
Silent `CancellationException` for `CompactFutureManager`
Linked issue: close #1374
> Silent CancellationException for CompactFutureManager

- paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/BatchWriteBuilderImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/InnerTableWrite.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/TableWriteImpl.java
- paimon-core/src/test/java/org/apache/paimon/TestFileStore.java
- paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java
- paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ContinuousCompactorFollowUpScannerTest.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/GlobalFullCompactionSinkWrite.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWriteImpl.java
For the name emptyWriter and fromEmptyWriter are confusing in writers, ignorePreviousFiles and withIgnorePreviousFiles are more suitable names.
This pull request renames emptyWriter to ignorePreviousFiles, fromEmptyWriter to withIgnorePreviousFiles
> [core] rename emptyWriter to ignorePreviousFiles

- paimon-core/src/main/java/org/apache/paimon/io/RollingFileWriter.java
- paimon-core/src/main/java/org/apache/paimon/io/SingleFileWriter.java
RollingFileWriter should not refer all writers, or we should set writer and maxKey to null in SingleFileWriters.
part of #1375
> [core] RollingFileWriter should not refer all writers

- docs/content/concepts/primary-key-table.md
- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-core/src/main/java/org/apache/paimon/table/ChangelogWithKeyFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/SequenceGenerator.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/TableWriteImpl.java
- paimon-core/src/test/java/org/apache/paimon/table/ChangelogWithKeyFileStoreTableTest.java
- paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java
- paimon-core/src/test/java/org/apache/paimon/table/sink/SequenceGeneratorTest.java
fix #1050 
Taking `System.nanotime()` as the time source with high precision, make up to the provided `sequence.field` to nanosecond if it's in`Timestamp` data type and with the precision of second or millisecond.
ChangelogWithKeyFileStoreTableTest#testNanosSequenceNumberOnTimestampSecond
ChangelogWithKeyFileStoreTableTest#testNanosSequenceNumberOnTimestampMilliSecond
ChangelogWithKeyFileStoreTableTest#testNanosSequenceNumberOnTimestampMicroSecond
ChangelogWithKeyFileStoreTableTest#testNanosSequenceNumberOnNonTimestampField
> [core] Support to make up the sequence number to nanosecond precision

- docs/content/concepts/primary-key-table.md
- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/DynamicBucketSink.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/DynamicBucketTableITCase.java
Introduce dynamic-bucket.assigner-parallelism.
Parallelism of assigner operator for dynamic bucket mode, it is related to the number of initialized bucket, too small will lead to insufficient processing speed of assigner.
> [core] Introduce dynamic-bucket.assigner-parallelism

- LICENSE
- NOTICE
- docs/content/engines/spark3.md
- paimon-spark/paimon-spark-3.1/pom.xml
- paimon-spark/paimon-spark-3.1/src/test/java/org/apache/paimon/spark/SparkGenericCatalogTest.java
- paimon-spark/paimon-spark-3.1/src/test/resources/log4j2-test.properties
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalogBase.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java
- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkGenericCatalogTest.java
- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadTestBase.java
When starting `spark-sql`, use the following command to register Paimon’s Spark Generic catalog to replace Spark
default catalog `spark_catalog`. (default warehouse is Spark `spark.sql.warehouse.dir`)
```bash
spark-sql ... \
--conf spark.sql.catalog.spark_catalog=org.apache.paimon.spark.SparkGenericCatalog
```
Using `SparkGenericCatalog`, you can use Paimon tables in this Catalog or non-Paimon tables such as Spark's csv,
parquet, Hive tables, etc.
part of #739
`SparkGenericCatalogTest`
`SparkGenericCatalog`
yes
> [spark] Introduce SparkGenericCatalog

- docs/content/engines/hive.md
To avoid users don't set hdfs scheme.
> [doc] Minor improve Hive doc

- .github/workflows/check-licensing.yml
the jdk distrbution "Temurin" seem to fail setting up, we can change the  distribution to adopt to work around it.
> fix workflow fail

- paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-core/src/main/java/org/apache/paimon/format/FileFormatDiscover.java
- paimon-core/src/test/java/org/apache/paimon/FileFormatTest.java
The format options ,such as 'orc.xx','parquet.xx' currently don't work for reading. 
It work for writing
> [core]Fix inconsistent format option between read and write

- paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/InnerTableWrite.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/TableWriteImpl.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CompactorSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FileStoreSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/GlobalFullCompactionSinkWrite.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowDynamicBucketSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCompactOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWrite.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWriteImpl.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/TableWriteOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/UnawareBucketCompactionSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcDynamicBucketSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSink.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/FlinkSinkTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperatorTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreWriteOperatorTest.java
KeyValueFileStoreWrite could enable spillable in batch mode by default.
We add optimizeForBatch interface to invoke this.
close https://github.com/apache/incubator-paimon/issues/1369
> [flink] set spillable default on for batch mode

- docs/content/filesystems/hdfs.md
- paimon-common/src/main/java/org/apache/paimon/utils/HadoopUtils.java
- paimon-common/src/test/java/org/apache/paimon/fs/HadoopConfigLoadingTest.java
Introduce `hadoop-conf-loader`:
Specifies the way of loading hadoop config.
> [hdfs] Introduce hadoop-conf-loader

- docs/content/api/flink-api.md
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecord.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcParserFactory.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcRecord.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcSinkBuilder.java
The previous CDC API, which required the user to implement an EventParser.Factory, was a bit too complicated for the user.
This PR introduces a RichCdcSinkBuilder, the user only needs to provide a DataStream<RichCdcRecord>, which can extract Schema changes from the data.
> [cdc] Introduce RichCdcSinkBuilder API

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/UnawareBucketWriteSink.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogITCaseBase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/UnawareBucketAppendOnlyTableITCase.java
Unaware-bucket table inserting in batch mode does not need compaction.
Add Tests for this.
> [fix] disable compaction when unaware-bucket table writes in batch mode

- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
We've heard from some users that they experience some issues when using loser tree as the sort engine. This PR changes the default sort engine back to `min-heap`, which is more stable.
N/A
No.
Document for `sort-engine` option is also changed.
> [core] Change default sort engine back to min heap

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AdaptiveParallelism.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StateUtils.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
Paimon Sink does not support Flink's Adaptive Parallelism mode. Please manually turn it off or set Paimon `sink.parallelism` manually.
> [flink] Prohibit adaptive parallelism

- paimon-common/src/main/java/org/apache/paimon/predicate/DeletePushDownFunctionVisitor.java
- paimon-common/src/main/java/org/apache/paimon/predicate/DeletePushDownPartitionKeyVisitor.java
- paimon-common/src/main/java/org/apache/paimon/predicate/DeletePushDownPrimaryKeyVisitor.java
- paimon-common/src/test/java/org/apache/paimon/predicate/DeletePushDownVisitorTest.java
- paimon-core/src/main/java/org/apache/paimon/table/TableUtils.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkTableSink.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ReadWriteTableITCase.java
Linked issue: close https://github.com/apache/incubator-paimon/issues/989
Supported filters:
1. where primary key = x
2. where primary key = x or key = y
3. where primary key in (x, y, z)
4. where partition key = x
Note: primary key between filter now is not supported in Paimon, ignore it now and let's start a new ticket for it later.
UT:
* ReadWriteTableITCase#testDeletePushDownWithPrimaryKey
* ReadWriteTableITCase#testDeletePushDownWithPartitionKey
> [flink] integrate DELETE filter pushdown for flink-1.17

- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
- paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java
We heard from some users that they're experiencing commit conflicts although they're sure that there is only one job writing into the Paimon table. To better diagnose the problem, this PR adds base commit user and cause to commit conflict messages.
Update: after testing, we found that back pressuring is also a cause for commit conflicts. Conflicts will be automatically resolved and the exception won't be repeated, so it is harmless. This PR also adds back pressure as a possible cause for commit conflicts in the exception message.
No.
No.
> [core] Add base commit user and cause to commit conflict messages, also add back pressure as a possible cause for commit conflicts

- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/CommitCallback.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/TableCommitImpl.java
- paimon-core/src/test/java/org/apache/paimon/table/sink/TableCommitTest.java
As discussed in #1445, in this PR we will first introduce `CommitCallback` for tables. Users can also create their own `CommitCallback` and use it through `commit.callback` option.
* `TableCommitTest`.
No.
Yes. This PR comes with changes in document.
> [core] Introduce commit callback for tables

- paimon-core/src/main/java/org/apache/paimon/io/DataFileMeta.java
now，for the `creation_time` of `FilesTable` ，when writing, it is local time ,but we read it as UTC time, we should read it as local time.
the snapshots create time is correct.
> [core]the creation_time of FilesTable should be local date time

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java
Method should be synchronized because {@link #handleSplitRequest} and {@link #processDiscoveredSplits} have thread conflicts.
> [flink] ContinuousFileSplitEnumerator.assignSplits should be thread safe

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumeratorTest.java
Raised ConcurrentModificationException in SplitEnumeratorContext if registered reader has been removed.
> [fix] fix bug: raised ConcurrentModificationException while readers removed in SplitEnumeratorContext

- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/CompactedStartingScanner.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/FullCompactedStartingScanner.java
- paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
- paimon-core/src/test/java/org/apache/paimon/table/ChangelogWithKeyFileStoreTableTest.java
Scan mode should just try its best to find a snapshot, and if it cannot be found, it should return the closest snapshot
> [core] compacted_full should never return null

- docs/content/api/flink-api.md
- paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
- paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java
- paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
- paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
- paimon-core/src/test/java/org/apache/paimon/table/SchemaEvolutionTableTestBase.java
- paimon-core/src/test/java/org/apache/paimon/table/SchemaEvolutionTest.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ActionBase.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcSinkBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/MultiTableUpdatedDataFieldsProcessFunction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcSinkBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunction.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/TestAlterTableCatalogFactory.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/TestCaseInsensitiveCatalogFactory.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncTableSinkITCase.java
- paimon-flink/paimon-flink-common/src/test/resources/META-INF/services/org.apache.paimon.catalog.CatalogFactory
- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkSchemaEvolutionITCase.java
For example, if user use Hive catalog in CDC, currently the schema change information is only recorded into file system, but 
cannot be seen in Hive meta store. This PR fix it.
`TestAlterTableCatalogFactory`
> [bug][flink] CDC schema evolution should pass catalog information

- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkTable.java
- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadITCase.java
Spark dose not have primary key syntax, we should add primary key option for its SHOW CREATE TABLE.
> [spark] Spark Show create table should show primary key

- docs/content/how-to/querying-tables.md
- paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreRead.java
- paimon-core/src/main/java/org/apache/paimon/operation/DiffReader.java
- paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreRead.java
- paimon-core/src/main/java/org/apache/paimon/table/source/AbstractInnerTableScan.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalTagStartingScanner.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReader.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
- paimon-core/src/test/java/org/apache/paimon/table/IncrementalTableTest.java
Process:
- First get the differences in the files and delete the same files directly
- Then compare the before and after files to get the incremental data.
Table types:
- Primary Key table: Compare diff with two tags, perfect.
- Append table: Ignore before files, this may cause some more data to be read due to compaction
> [core] Support incremental read on tags

- docs/content/how-to/creating-catalogs.md
- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-common/src/main/java/org/apache/paimon/utils/IOUtils.java
- paimon-core/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
- paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
- paimon-core/src/main/java/org/apache/paimon/metastore/AddPartitionCommitCallback.java
- paimon-core/src/main/java/org/apache/paimon/metastore/MetastoreClient.java
- paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/ChangelogValueCountFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/ChangelogWithKeyFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/FileStoreTableFactory.java
- paimon-core/src/test/java/org/apache/paimon/table/sink/TableCommitTest.java
- paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ContinuousAppendAndCompactFollowUpScannerTest.java
- paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/ScannerTestBase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/FlinkSinkTest.java
- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveMetastoreClient.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/HiveSchema.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/SearchArgumentToPredicateConverter.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/mapred/PaimonInputFormat.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/mapred/PaimonRecordReader.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/utils/HiveUtils.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveTableSchemaTest.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/PaimonStorageHandlerITCase.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/SearchArgumentToPredicateConverterTest.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/mapred/PaimonRecordReaderTest.java
Currently we cannot create partitioned Paimon table in Hive catalog. In Hive, all fields are considered as normal fields and there is no partition key. It brings us at least two downsides:
1. Users cannot list all partitions through the SHOW PARTITIONS command.
2. Hive's native partition pushdown cannot be performed. Although currently we approach partition pushdown through Hive's filter pushdown, some Hive compatible system may only support partition pushdown and not filter pushdown, making Paimon nearly unusable in those systems.
This PR introduces a feature to synchronize partitions into Hive metastore when using Hive catalog. In this PR, users can create partitioned Hive table through Flink and Spark using Hive catalog. Creating partitioned table directly in Hive is currently not …
> [core][hive] Support syncing partition into Hive metastore when using Hive catalog

- docs/content/how-to/querying-tables.md
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkTable.java
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonAnalysis.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonSparkSessionExtension.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonSparkSessionExtensions.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonTableValuedFunctions.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalog/Catalogs.scala
- paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonSparkTestBase.scala
- paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/TableValuedFunctionsTest.scala
- Builds Paimon SparkSession Extensions Arch;
- Supports paimon_incremental_query TVF to query the incr data between the two versions provided.
> [spark] Supports paimon_incremental_query Table Valued Function

- docs/content/how-to/cdc-ingestion.md
- docs/layouts/shortcodes/generated/mysql_sync_database.html
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/DatabaseSyncMode.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSchema.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseActionFactory.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/canal/CanalRecordParser.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSchema.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionFactory.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTableSchemaBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcDynamicTableParsingProcessFunction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/EventParser.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/NewTableSchemaBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcMultiplexRecord.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcMultiplexRecordEventParser.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcMultiplexRecordSchemaBuilder.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionITCaseBase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncDatabaseActionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
Currently, when Kafka cdc start, the action will read some canal json and try to build schema from them.
In this PR, the action will dynamically find new table and create them.
Remove two Kafka cdc arguments:
schema-init-max-read
ignore-incompatible
Modify doc.
> [flink][kafka-cdc] Kafka cdc should dynamically create table

- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/objectinspector/PaimonDateObjectInspector.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/objectinspector/PaimonDecimalObjectInspector.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/objectinspector/PaimonMapObjectInspector.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/objectinspector/PaimonTimestampObjectInspector.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/PaimonStorageHandlerITCase.java
Linked issue: close #1552 
Currently, Hive external table cannot handle map type. It is because the `PaimonMapObjectInspector` haven't convert paimon map key and hive map key to the same comparble type. This PR fix it.
`PaimonStorageHandlerITCase#testMapKey`
> [hive] Map object inspector should normalize map key properly before search value

- docs/content/maintenance/manage-tags.md
- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
- paimon-core/src/main/java/org/apache/paimon/FileStore.java
- paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/TableCommitImpl.java
- paimon-core/src/main/java/org/apache/paimon/tag/TagAutoCreation.java
- paimon-core/src/test/java/org/apache/paimon/tag/TagAutoCreationTest.java
Paimon supports automatic creation of tags in writing job.
**Step 1: Choose Creation Mode**
You can set `'tag.automatic-creation'` to `process-time` or `watermark`:
- `process-time`: Create TAG based on the time of the machine.
- `watermark`: Create TAG based on the watermark of the Sink input.
If you choose Watermark, you may need to specify the time zone of watermark, if watermark is not in the
UTC time zone, please configure `'sink.watermark-time-zone'`.
**Step 2: Choose Creation Period**
What frequency is used to generate tags. You can choose `'daily'`, `'hourly'` and `'two-hours'` for `'tag.creation-period'`.
If you need to wait for late data, you can configure a delay time: `'tag.creation-delay'`.
**Step 3: Automatic deletion of tags**
You can configure `'tag.num-retained-max'` to …
> [core] Automatic Creation for tags

- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeFunction.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/SortBufferWriteBufferTestBase.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/compact/MergeFunctionTestUtils.java
- paimon-core/src/test/java/org/apache/paimon/utils/ReusingTestData.java
- When delete Ignore is enabled
- and the last data of the key is delete
- which occurs in Sink's WriteBuffer
There will be a bug in object reuse.
We should update key reference even the incoming record is a delete record.
Introduce classes in `SortBufferWriteBufferTestBase`:
1. WithPartialUpdateMergeFunctionTest
2. WithAggMergeFunctionTest
3. WithLookupFunctionTest
> [core] Fix Object reusing bug in PartialUpdateMergeFunction

- paimon-common/src/main/java/org/apache/paimon/data/GenericArray.java
- paimon-common/src/main/java/org/apache/paimon/data/columnar/ColumnarArray.java
- paimon-common/src/main/java/org/apache/paimon/types/RowType.java
- paimon-common/src/main/java/org/apache/paimon/utils/ArrayUtils.java
- paimon-common/src/test/java/org/apache/paimon/format/FormatReadWriteTest.java
- paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ArrayColumnReader.java
- paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ParquetDataColumnReader.java
- paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ParquetDataColumnReaderFactory.java
- paimon-format/src/test/java/org/apache/paimon/format/orc/OrcFormatReadWriteTest.java
- paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetFormatReadWriteTest.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/PaimonStorageHandlerITCase.java
Currently, the default implementation of `ParquetDataColumnReader` doesn't support reading timestamp.
This PR make it possible to read timestamp if precision is less than or equal to 6.
Parquet format
> [format] ParquetDataColumnReader supports reading timestamp with precision <= 6

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTableSchemaBuilder.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
Linked issue: close https://github.com/apache/incubator-paimon/issues/1613
> [flink] parse primary key and schema by historyRecord

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/FileStoreLookupFunctionTest.java
When the main table occasionally has no data, while the dimension table always has data, there is no data to drive the loading of the dimension table, which may result in the snapshot of the dimension table being expired when waiting for a long time to load.
We should avoid making mistakes in this situation.
> [flink] FileStoreLookupFunction should not throw OutOfRangeException

- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
Multiple-writers doc url path is error in Exception messages，Might not be updated to latest url，cause misunderstanding
Earlier： https://paimon.apache.org/docs/master/maintenance/write-performance/#dedicated-compaction-job
Newest：https://paimon.apache.org/docs/master/maintenance/multiple-writers/#dedicated-compaction-job
> [hotfix][core] Multiple-writers doc url path is error in Exception messages

- paimon-e2e-tests/src/test/java/org/apache/paimon/tests/E2eReaderTestBase.java
- paimon-e2e-tests/src/test/java/org/apache/paimon/tests/HiveE2eTest.java
- paimon-hive/paimon-hive-common/src/main/java/org/apache/paimon/hive/LocationKeyExtractor.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/mapred/PaimonInputFormat.java
For a partitioned table, the location of its input split must point to a partition, not the root directory of that table. This PR fixes the issue.
* `HiveE2eTest#testMetastorePartitionedTable`.
No.
No.
> [hive] PaimonInputFormat#getSplits should deal with multiple partitions in INPUT_DIR

- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestCdcSourceFunction.java
[flink][test] fix unstable testRandomCdcEventsDynamicBucket. 
Linked issue: close #1645 
Current `FlinkCdcSyncDatabaseSinkITCase. testRandomCdcEventsDynamicBucket` can cover this.
No.
No.
> [flink][test] fix unstable testRandomCdcEventsDynamicBucket.

- docs/content/how-to/cdc-ingestion.md
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseActionFactory.java
fix doc, When the flink configuration class obtains list parameters, follow the `;` split
org.apache.flink.configuration.ConfigurationUtils#convertToList
```
StructuredOptionsSplitter.splitEscaped(rawValue.toString(), ';').stream()
.map(s -> convertValue(s, atomicClass))
.collect(Collectors.toList());
```
> [doc] KAFKA-Paimon Database Sync, Fix multiple topic parameter delimiter

- paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTestBase.java
[core][test] fix SORT_ENGIN#MIN_HEAP is not tested issue.
Linked issue: close #1655 
`MergeTreeTestWithMinHeap` can work correctly.
No.
No.
> [core][test] fix SORT_ENGIN#MIN_HEAP is not tested issue.

- docs/content/concepts/primary-key-table.md
- paimon-common/src/main/java/org/apache/paimon/io/cache/CacheManager.java
- paimon-common/src/main/java/org/apache/paimon/utils/BiFunctionWithIOE.java
- paimon-core/src/main/java/org/apache/paimon/io/KeyValueFileReaderFactory.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/ContainsLevels.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/LookupLevels.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/LookupUtils.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/ChangelogMergeTreeRewriter.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FirstRowMergeTreeCompactRewriter.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FullChangelogMergeFunctionWrapper.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapper.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeFunction.java
- paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/ContainsLevelsTest.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/compact/FullChangelogMergeFunctionWrapperTestBase.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapperTest.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/compact/SortMergeReaderTestBase.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/compact/UniversalCompactionTest.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/RocksDBListState.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/RocksDBState.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FirstRowITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ReadWriteTableITCase.java
Introduce `ContainsLevels` to optimize first row.
And first row only works with lookup changelog-producer.
Benifit:
1. One is to generate a changelog through contains, which should be highly efficient. It only reads keys and does not read the entire row of data.
2. The second one is that there is data at the upper level, and the output of data at the lower level is directly null. After merging, it is directly deleted
> [core] Optimize First row merge engine with lookup

- paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTestBase.java
[core][test] fix the issue that testPrepareCommitRecycleReference runs unstable.
Linked issue: close #1653 
Currently `testPrepareCommitRecycleReference` can work stable.
No.
No.
> [core][test] fix the issue that testPrepareCommitRecycleReference runs unstable.

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ActionFactory.java
when the mysql conf contain `=` (for example `password=VdwrHwd3=9bxN@#fySW`) , it can not be parsed correctly.
> [flink] parse mysql-conf error when it contain `=`

- docs/content/how-to/system-tables.md
- paimon-core/src/main/java/org/apache/paimon/table/system/ManifestsTable.java
- paimon-core/src/test/java/org/apache/paimon/table/system/ManifestsTableTest.java
Linked issue: close #1666 
[core] support querying the manifest of the specified snapshot.
Added `org.apache.paimon.table.system.ManifestsTableTest` to verify correctness.
No.
No.
> [core] support querying the manifest of the specified snapshot.

- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
> [hive] HiveCatalog should throw TableNotExists Exception when table is not a paimon table

- paimon-common/src/main/java/org/apache/paimon/utils/TypeUtils.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkArrayData.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkInternalRow.java
Clean up the redundant code of the method of obtaining timestamp type precision.
> [hotfix] Clean up the redundant code of the method of obtaining timestamp type precision.

- docs/layouts/shortcodes/generated/flink_connector_configuration.html
- paimon-core/src/main/java/org/apache/paimon/table/source/InnerStreamTableScanImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/source/SnapshotNotExistPlan.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileStoreSource.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FileStoreSourceReader.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkSourceBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedContinuousFileSplitEnumerator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedContinuousFileStoreSource.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedSourceReader.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/CheckpointEvent.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/PlaceholderSplit.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/assigners/AlignedSplitAssigner.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumeratorTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FileStoreSourceReaderTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/align/AlignedContinuousFileSplitEnumeratorTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/align/AlignedSourceReaderTest.java
[flink] align snapshot and checkpoint in split enumerator and source.
Linked issue: close #1486 
- Added `org.apache.paimon.flink.source.align.AlignedSourceReaderTest` to verify `AlignedSourceReader`.
- Added `org.apache.paimon.flink.source.align.AlignedContinuousFileSplitEnumeratorTest` to verify `AlignedContinuousFileSplitEnumerator`
No.
https://cwiki.apache.org/confluence/x/jRE0Dw
> [flink] align snapshot and checkpoint in split enumerator and source.

- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/UnawareBucketAppendOnlyTableITCase.java
This test is unstable, guess the rows generate too fast, and job start too slow to generate 4 file of 4 rows. So make more rows by datagen.
> [test] Fix unstable test: UnawareBucketAppendOnlyTableITCase.testCompactionInStreamingMode

- paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkWriteITCase.java
> [core] Sort spill threhold can not be 1

- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
fix unstable hive catalog test.
See https://github.com/apache/incubator-paimon/blob/c617beb74eb94b627de05809333dbceaf1b81ad5/paimon-hive/paimon-hive-common/src/main/java/org/apache/paimon/hive/HiveTypeUtils.java#L216-L218
> [test] fix unstable hive catalog test

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DropPartitionAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MergeIntoAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableAction.java
when use flink api to start a flink kafka sync action job  ,  it will throw an `Cannot be accessed from outside package` exception , because it is not public.
> [filnk] make kafka sync action to public

- docs/content/how-to/system-tables.md
- paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
- paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
- paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java
- paimon-core/src/main/java/org/apache/paimon/table/system/AllTableOptionsTable.java
- paimon-core/src/main/java/org/apache/paimon/table/system/SystemTableLoader.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
add system table system$all_table_options to enable config search
sql:
```
SELECT * FROM sys.all_table_options
```
add built-in system "sys"
sql:
```
USE sys;
SHOW TABLES;
```
will result in:
all_table_options
We will add more system table in the future
> [improve] add system table to show all table configs in `sys.all_table_options`

- docs/content/how-to/cdc-ingestion.md
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcMultiplexRecordChannelComputer.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/MultiTableUpdatedDataFieldsProcessFunction.java
Linked issue: close https://github.com/apache/incubator-paimon/issues/1659
I fixed it ,the result is : 
During the data synchronization,  we rename a table,  the old table will stop data synchronization , the new table will not be synchronized either.
> [flink] fix rename table error in sync action

- docs/content/concepts/primary-key-table.md
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunctionTest.java
By default, Partial update can not accept delete records, you can choose one of the following solutions:
1. Configure 'partial-update.ignore-delete' to ignore delete records.
2. Configure 'sequence-group' to retract partial columns.
Sequence group delete corresponding fields.
> [core] Partial update supports retraction with sequence group

- docs/content/engines/presto.md
- docs/content/engines/trino.md
file.format is defined here
https://github.com/apache/incubator-paimon/blob/41997b2170dcfa32aa867bbc4573989911f05f61/paimon-common/src/main/java/org/apache/paimon/CoreOptions.java#L91
bucket-key
https://github.com/apache/incubator-paimon/blob/41997b2170dcfa32aa867bbc4573989911f05f61/paimon-common/src/main/java/org/apache/paimon/CoreOptions.java#L67
changelog-producer
https://github.com/apache/incubator-paimon/blob/41997b2170dcfa32aa867bbc4573989911f05f61/paimon-common/src/main/java/org/apache/paimon/CoreOptions.java#L373
primary_key & partitioned_by shouldn't be changed 
https://github.com/apache/incubator-paimon-trino/blob/75360d8e0b11cf5026f5219d0c9af02afee2b984/paimon-trino-common/src/main/java/org/apache/paimon/trino/TrinoTableOptions.java#L36
> [doc] Use correct parameters for Presto & Trino

- paimon-common/src/test/java/org/apache/paimon/utils/CommonTestUtils.java
- paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/TableWriteImpl.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWriteImpl.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperator.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperatorTest.java
`CdcRecordStoreMultiWriteOperatorTest#testUsingTheSameCompactExecutor`
> [flink][mysql-cdc] All FileStoreWrites generated in database synchronization job should use the same compaction executor service

- docs/content/how-to/creating-tables.md
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/PaimonMetaHook.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/CreateTableITCase.java
Support use `partitioned by` to create hive partition table.
> [hive] Support use partitioned by to create hive partition table.

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedContinuousFileSplitEnumerator.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumeratorTest.java
Stream read too slow, tasks will wait time interval to trigger snapshot scan. 
Every request will trigger a snapshot scan immediately (on if the last scan hasn't reach the latest one).
> [bug]  fix bug: Stream read snapshot slow while reading from history, waiting for time interval to trigger stream scan

- docs/content/concepts/primary-key-table.md
- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-core/src/main/java/org/apache/paimon/table/ChangelogWithKeyFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/SequenceGenerator.java
- paimon-core/src/test/java/org/apache/paimon/table/ChangelogWithKeyFileStoreTableTest.java
- paimon-core/src/test/java/org/apache/paimon/table/sink/SequenceGeneratorTest.java
This PR adds `'sequence.auto-padding' = 'row-kind-flag'`, full documentation for **Sequence Auto Padding** is:
When the record is updated or deleted, the `sequence.field` must become larger and cannot remain unchanged.
For -U and +U, their sequence-fields must be different. If you cannot meet this requirement, Paimon provides
option to automatically pad the sequence field for you.
1. `'sequence.auto-padding' = 'row-kind-flag'`: If you are using same value for -U and +U, just like "`op_ts`"
(the time that the change was made in the database) in Mysql Binlog. It is recommended to use the automatic
padding for row kind flag, which will automatically distinguish between -U (-D) and +U (+I).
2. Insufficient precision: If the provided `sequence.field` doesn't meet the precision, like a rough …
> [core] Introduce row time flag sequence.auto-padding

- paimon-common/src/main/java/org/apache/paimon/fs/FileIO.java
- paimon-common/src/main/java/org/apache/paimon/fs/FileIOLoader.java
- paimon-common/src/test/java/org/apache/paimon/fs/FileIOTest.java
- paimon-common/src/test/java/org/apache/paimon/fs/RequireOptionsFileIOLoader.java
- paimon-common/src/test/resources/META-INF/services/org.apache.paimon.fs.FileIOLoader
- paimon-filesystems/paimon-oss/src/main/java/org/apache/paimon/oss/OSSLoader.java
- paimon-filesystems/paimon-s3/src/main/java/org/apache/paimon/s3/S3Loader.java
At present, when we put Paimon-s3.jar into the production environment, we must configure s3 related configurations, and fallback FileIO will not be useful.
We can actually make them coexist and introduce the requiredOptions mechanism to use fallback FileIO.
It is not recommended to use `FileIOUtils.checkAccess` here. Accessing real S3FileIO may cause decompression of temporary files and may also cause blockages.
> [fs] Introduce requiredOptions to FileIOLoader

- docs/content/engines/hive.md
- docs/content/how-to/altering-tables.md
- docs/content/how-to/creating-tables.md
- docs/content/how-to/querying-tables.md
- docs/content/how-to/writing-tables.md
- docs/content/maintenance/rescale-bucket.md
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/PredicateConverter.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/kafka/KafkaLogDeserializationSchema.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowDataStoreWriteOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCommitter.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/MultiTableUpdatedDataFieldsProcessFunction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FileStoreSourceSplitReader.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedContinuousFileSplitEnumerator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/CheckpointEvent.java
1. Ensure uniformity of semicolon termination for SQL statements within the document.
2. Refactor the logic inside `getSchemaChanges` into a separate method to eliminate redundancy.
3. some method invocations may result in 'NullPointerException'. It would be more appropriate to perform null checks beforehand instead of waiting for the invocation to trigger it.
4. Be cautious about unboxing 'nextSnapshotId', as it may lead to 'java.lang.NullPointerException'.
5. Note that '@Nonnull' annotation cannot be used on members of primitive types.
6. Improve the performance of `list.containsAll(collection)` by wrapping 'fieldNames' in a `HashSet` constructor.
> [Improve][Doc][Flink]Improve some small content

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSchema.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java
The current configuration for retry attempts and retry intervals seems inappropriate: the number of retry attempts is set at 100, and the retry interval is set at 100 milliseconds. It is suggested to adjust these values to a more reasonable setting, such as 5 retry attempts and a retry interval of 1000 milliseconds. Additionally, implementing an exponential backoff strategy would be beneficial, which progressively increases the retry waiting time with each attempt.
> [flink]Improve get kafka schema

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/Committer.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCommitter.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreMultiCommitter.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java
Linked issue: close #1737 
Update counter when commit with committables, the value is the size of data files. The counter metric is already registered by flink.
> [Flink] Support numBytesSend metrics for paimon sink

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSchema.java
…chema otherwise perhaps can NOT fetch records in little traffic case
[flink]
Linked issue: when run kafka sync table action it throws can NOT get metadata of topic error
Seek to beginningOffsets and enlarge poll duration when fetch kafka schema otherwise perhaps can NOT fetch records in little traffic case
NO
> [flink] Fetching schema in Kafka table synchronization should first seek to beginningOffsets

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/BucketUnawareCompactSource.java
Ambiguous operator name, we can make it more clearer.
use : instead of -> for operator name
> [flink] Fix to  use : instead of -> for operator name

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkSourceBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedContinuousFileSplitEnumerator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/assigners/AlignedSplitAssigner.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/align/AlignedContinuousFileSplitEnumeratorTest.java
Linked issue: close #1793 
support `consumer-id` for `AlignedContinuousFileSplitEnumerator`.
Added `org.apache.paimon.flink.source.align.AlignedContinuousFileSplitEnumeratorTest#testScanWithConsumerId` to verify that the `consumer-id` can be updated correctly.
No
No
> [flink] support consumer-id for AlignedContinuousFileSplitEnumerator

- paimon-core/src/main/java/org/apache/paimon/tag/TagAutoCreation.java
- paimon-core/src/test/java/org/apache/paimon/tag/TagAutoCreationTest.java
After restarting job, the `TagAutoCreation` may be initialized to expired snapshot. 
`TagAutoCreationTest#testTag`
> [core] Fix that tag auto creation cannot work after restarting job

- paimon-hive/paimon-hive-common/src/main/java/org/apache/paimon/hive/HiveTypeUtils.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/objectinspector/PaimonObjectInspectorFactory.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/objectinspector/PaimonTimeObjectInspector.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/PaimonStorageHandlerITCase.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/RandomGenericRowDataGenerator.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/objectinspector/PaimonInternalRowObjectInspectorTest.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/objectinspector/PaimonTimeObjectInspectorTest.java
`PaimonStorageHandlerITCase#testTime`
> [hive] HiveCatalog supports TIME type by converting time to string

- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/PaimonMetaHook.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/PaimonStorageHandler.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/CreateTableITCase.java
When attempting to create a  hive extern table  for an existing Paimon, if the table creation fails, the Paimon table will be deleted, which is not expected.
The pr is for reproduce the problem,and then fix it
CreateTableITCase#createExternTableFailing
> [hive] extern table remove file by mistake when create table failed

- paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
Currently when creating `AddPartitionCommitCallback`, we forget to check whether the table is a partitioned table. This PR fixes the issue.
* `HiveCatalogITCaseBase#testAddPartitionsToMetastoreForUnpartitionedTable`.
No.
No.
> [core] AddPartitionCommitCallback should only be created for partitioned table

- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
…
Linked issue: close #1831
HiveCatalogITCaseBase#testRenameTable
> [hive] After Flink changed the table name when using hive metastore, the modified table could not be found.

- docs/content/maintenance/write-performance.md
- docs/layouts/shortcodes/generated/core_configuration.html
- docs/layouts/shortcodes/generated/flink_connector_configuration.html
- paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-core/src/main/java/org/apache/paimon/schema/TableSchema.java
- paimon-core/src/main/java/org/apache/paimon/table/ChangelogWithKeyFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/ChangelogWithKeyTableUtils.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/SequenceGenerator.java
- paimon-core/src/test/java/org/apache/paimon/table/sink/SequenceGeneratorTest.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/LocalMergeOperator.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ChangelogWithKeyFileStoreTableITCase.java
Local merge aims to resolve data skew on primary keys. If your job suffers from primary key data skew (for example, you want to count the number of views for each pages in a website, and some particular pages are very popular among the users), you can use local merge so that input records will be buffered and merged before they're shuffled by bucket and written into sink. This is particularly useful when the same primary key is updated frequently between snapshots.
This PR implements local merge operator for Flink.
* `ChangelogWithKeyFileStoreTableITCase` now randomly runs with local merge.
No.
Yes. Document is also updated.
> [flink] Add local merge operator for Flink

- paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyCompactManager.java
- paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/table/source/AppendOnlySplitGenerator.java
- paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyCompactManagerTest.java
- paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java
- paimon-core/src/test/java/org/apache/paimon/format/FileFormatSuffixTest.java
There could overlap in append files, if the users have multiple write jobs.
So we can not check by default.
> [core] Remove append-only.assert-disorder

- paimon-common/pom.xml
Now, paimon-common.jar is too big, about 26 MB.
We should minimize it, actually, the root reason is `fastutil`, it is very big.
I am trying to add minimizeJar to shade plugin. After, the jar is 3 MB.
> [build] Try to minimize paimon-common jar

- docs/content/maintenance/multiple-writers.md
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactDatabaseAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactDatabaseActionFactory.java
- paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactActionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactActionITCaseBase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactDatabaseActionITCase.java
Linked issue: close https://github.com/apache/incubator-paimon/issues/1448
- support one or multiple database compaction.
- support including-tables
- support excluding-tables
org.apache.paimon.flink.action.CompactDatabaseActionITCase
> [flink] support one or multiple database in dedicated compaction job

- docs/content/engines/flink.md
- docs/content/engines/spark3.md
- docs/content/how-to/creating-catalogs.md
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkGenericCatalog.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkGenericCatalogFactory.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkGenericTableFactory.java
- paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogTest.java
- paimon-hive/paimon-hive-connector-common/pom.xml
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/FlinkGenericCatalogITCase.java
Using FlinkGenericCatalog, you need to use Hive metastore. Then, you can use all the tables from Paimon, Hive, and
Flink Generic Tables (Kafka and other tables)!
In this mode, you should use 'connector' option for creating tables.
```sql
CREATE CATALOG my_catalog WITH (
'type'='paimon-generic',
'hive-conf-dir'='...',
'hadoop-conf-dir'='...'
);
USE CATALOG my_catalog;
-- create a word count table
CREATE TABLE word_count (
word STRING PRIMARY KEY NOT ENFORCED,
cnt BIGINT
) WITH (
'connector'='paimon'
);
```
> [flink] Introduce FlinkGenericCatalog

- docs/content/maintenance/manage-tags.md
- docs/layouts/shortcodes/generated/flink_connector_configuration.html
- paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/DataTable.java
- paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
- paimon-core/src/main/java/org/apache/paimon/table/system/BucketsTable.java
- paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AutoTagForSavepointCommitterOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/AutoTagForSavepointCommitterOperatorTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java
Linked issue: close #1635 
Auto create new tag for flink savepoint.
Add `org.apache.paimon.flink.sink.AutoTagForSavepointCommitterOperatorTest` to verify correctness.
- `org.apache.paimon.flink.sink.AutoTagForSavepointCommitterOperatorTest#testAutoTagForSavepoint`
- `org.apache.paimon.flink.sink.AutoTagForSavepointCommitterOperatorTest#testRestore`
No
No
> [flink] auto create new tag for flink savepoint.

- docs/content/how-to/creating-catalogs.md
Add configuration instructions for Apache Atlas
no
no
no
> [doc] Add configuration instructions for Apache Atlas

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/Committer.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterMetrics.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CompactorSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkWriteSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCommitter.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreMultiCommitter.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/UnawareBucketCompactionSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSink.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/StoreMultiCommitterTest.java
This PR refactors Flink sink metrics by introducing the `CommitterMetrics` class. All Flink related metrics are now managed by this class.
This PR also introduces a `sink` metric group for users to quickly find out number of bytes and records written by sink.
Existing tests should cover the changes.
No.
No.
> [flink] Refactor Flink sink metrics by introducing CommitterMetrics

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionFactory.java
> [hotfix] Fix that MySQL sync-database action parses table prefix incorrectly

- docs/content/how-to/cdc-ingestion.md
- paimon-common/src/main/java/org/apache/paimon/utils/StringUtils.java
- paimon-common/src/main/java/org/apache/paimon/utils/TypeUtils.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTypeUtils.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecord.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordUtils.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlCdcTypeMappingITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
- paimon-flink/paimon-flink-common/src/test/resources/mysql/type_mapping_test_setup.sql
1. Binary value is passed as bytes, so we should map the MySQL Binary to byte type. I choose VARBINARY because it can retain the length information.
2. Current parse of BIT(N) is incorrect. The value is of little endian form, and shouldn't be stored by Java String.
Fix:
1. convert bytes to normal form;
2. encode the value to String using Base64 
`MySqlCdcDataTypeModeITCase#testReadAllTypes`
`MySqlSyncTableActionITCase#testAllTypes`
> [flink][mysql-cdc] Map MySQL BINARY to Paimon VARBINARY and fix parse of MySQL BIT(N) value

- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/AppendOnlyTableCompactionWorkerOperatorTest.java
Fix test, reduce the time usage
> [test] fix `AppendOnlyTableCompactionWorkerOperatorTest` spends too much time

- LICENSE
- paimon-spark/paimon-spark-common/pom.xml
- paimon-spark/paimon-spark-common/src/main/antlr4/org.apache.spark.sql.catalyst.parser.extensions/PaimonSqlExtensions.g4
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/analysis/NoSuchProcedureException.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/catalog/ProcedureCatalog.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/Procedure.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ProcedureBuilder.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ProcedureParameter.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ProcedureParameterImpl.java
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/extensions/PaimonSparkSessionExtensions.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/analysis/CoerceArguments.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/analysis/PaimonAnalysis.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveProcedures.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/PaimonSparkSqlExtensionsParser.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/PaimonSqlExtensionsAstBuilder.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/CallCommand.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/CallStatement.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/PaimonDynamicPartitionOverwriteCommand.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/PaimonTableValuedFunctions.scala
- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/extensions/CallStatementParserTest.java
- paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala
- paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/TableValuedFunctionsTest.scala
- pom.xml
Linked issue: close #1155 
Supports parser of Spark call procedure command. Introduces `PaimonSparkSessionExtensions` to extends the syntax and adds the rules of `SparkSessionExtensions`, including the CALL statement.
- Adds tests in `CallStatementParserTest` to verify the parser of `CallStatement` for `PaimonSparkSessionExtensions`.
- Introduces the `Procedure` and `ProcedureCatalog`.
None.
> [spark] Supports parser of Spark call procedure command

- pom.xml
[build] Support storing the commit ID and branch name inside the JAR, when building a JAR package with Paimon
Linked issue: close #1820
> [build] Support storing the commit ID and branch name inside the JAR, when building a JAR package with Paimon

- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/extensions/CallStatementParserTest.java
Fix `CallStatementParserTest` stop and clear spark active session to avoid loading previous non-stopped session, which causes that the Paimon extension could not load from the active session.
Linked issue: close #1155 
- `CallStatementParserTest`
None.
None.
> [hotfix] Fix CallStatementParserTest stop and clear spark active session

- docs/content/maintenance/manage-snapshots.md
- docs/content/maintenance/manage-tags.md
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkUtils.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/BaseProcedure.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CreateTagProcedure.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/DeleteTagProcedure.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RollbackProcedure.java
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/extensions/PaimonSparkSessionExtensions.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CallExec.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala
- paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/CreateAndDeleteTagProcedureTest.scala
- paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/RollbackProcedureTest.scala
implement for this https://github.com/apache/incubator-paimon/issues/1896 Feature request after this https://github.com/apache/incubator-paimon/pull/1785 pr.
As it may be the first implementation, Hope to get some guidance😊.
Will try to add more implementations later.
@JingsongLi  @SteNicholas looking forward to your opinion.
add some new test classes like 
[RollbackProcedureTest.scala](https://github.com/apache/incubator-paimon/pull/1897/files#diff-996f2c6f25319cd2ff34984e540b749449b8250ebcbc05ff9b482c672d83d8b6)
[CreateAndDeleteTagProcedureTest.scala](https://github.com/apache/incubator-paimon/pull/1897/files#diff-8ef36496ed0a33b9f1944112bba5301387fabd94c361d67877a1d42bf1961c6a)
include test cases for both success and failure.
Add new spark procedures: rollback to tag/snapshot、create …
> [spark] implement of `rollback` action using Spark Procedure

- pom.xml
This PR aim to resolve below exception in CI:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project paimon-flink-common: There are test failures.
Error:  
Error:  Please refer to /home/runner/work/incubator-paimon/incubator-paimon/paimon-flink/paimon-flink-common/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  ExecutionException Error occurred in starting fork, check output in log
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException Error occurred in starting fork, check output in log
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResult …
```
> [ci] Try to fix "ExecutionException Error occurred in starting fork"

- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/RocksDBListStateTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/index/GlobalIndexAssignerTest.java
Test always fails because some error called: pure virtual function called.
Track it, found the root cause is: "Java: Finalizer" Thread collapse while gc the rocksdb object.
crash stack:
rocksdb related issue:
https://github.com/facebook/rocksdb/issues/649
> [test] fix test problem: libc++abi: pure virtual function called

- docs/layouts/shortcodes/generated/catalog_configuration.html
- paimon-common/src/main/java/org/apache/paimon/options/CatalogOptions.java
- paimon-core/src/main/java/org/apache/paimon/catalog/CatalogFactory.java
- paimon-core/src/main/java/org/apache/paimon/catalog/CatalogOptionsManager.java
- paimon-core/src/test/java/org/apache/paimon/catalog/CatalogOptionsManagerTest.java
Linked issue: subtask of #1481 
As PIP-5 said, to support `table-lineage` and `data-lineage` catalog options which are immutable, paimon should persist the immutable catalog options when creating catalog. This pr support to read / write the immutable catalog options and support validation on the IMMUTABLE catalog options.
> [core] Paimon catalog support immutable options

- paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java
- paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java
Linked issue: close #1947 
[core] clean up files generated by `compactManager` when `AppendOnlyWriter` is closed.
Added unit test `org.apache.paimon.append.AppendOnlyWriterTest#testCloseUnexpectedly` to verify that files are properly cleaned.
No
No
> [core] clean up files generated by compactManager when AppendOnlyWriter is closed.

- paimon-core/src/test/java/org/apache/paimon/mergetree/compact/SortMergeReaderTestBase.java
Fix typo in the SortMergeReaderTestBase unit test:
WithValueRecordMergeFunctionTest -> WithValueCountMergeFunctionTest
> [test] Fix typo in the SortMergeReaderTestBase unit test

- docs/content/engines/hive.md
Fix Hive data type error in hive type conversion document.
See https://github.com/apache/hive/blob/a4f895ac2eb772ff211c6f98418c7c12387a3a13/serde/src/java/org/apache/hadoop/hive/serde2/typeinfo/TypeInfoFactory.java#L46-L61
> [doc] Fix Hive data type error in hive type conversion document.

- paimon-hive/paimon-hive-common/src/main/java/org/apache/paimon/hive/LocationKeyExtractor.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
… 
Linked issue: close #1865 
When using Hive Cli to read the hive external partition table created by Flink, the location obtained by the PaimonSerDe class is the partition location, so the schema of the external table cannot be found.
HiveCatalogITCaseBase#testFlinkWriteAndHiveReadToCompare
> [hive] After flink creates hive external partition table, using hive to read data cannot find the table schema.

- docs/content/concepts/primary-key-table.md
- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/RocksDBStateFactory.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalIndexAssigner.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/IndexBootstrap.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/LookupTableTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/RocksDBListStateTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/index/GlobalIndexAssignerTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/index/IndexBootstrapTest.java
Cross-partition-upsert Performance: For tables with a large amount of data, there will be a significant loss in performance. Moreover,
initialization takes a long time.
If your upsert does not rely on too old data, you can consider configuring index TTL and bootstrap-min-partition to
reduce Index and initialization time:
- `'cross-partition-upsert.index-ttl'`: The TTL in rocksdb index, this can avoid maintaining too many indexes and lead
to worse and worse performance.
- `'cross-partition-upsert.bootstrap-min-partition'`: The min partition bootstrap of rocksdb index, bootstrap will only
read the partitions above it, and the smaller partitions will not be read into the index. This can reduce job startup
time and excessive initialization of index.
But please note that this may also cause …
> [core] Introduce index-ttl and bootstrap-min-partition for cross-partition-upsert

- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
- paimon-core/src/test/java/org/apache/paimon/operation/FileStoreCommitTest.java
Linked issue: close #1976 
[core] fix the issue that partitionExpire will fail when logOffsets is not empty.
Enhanced `org.apache.paimon.operation. FileStoreCommitTest#testDropPartitions` to verify the correctness when `logOffsets` is not empty.
No
No
> [core] fix the issue that partitionExpire will fail when logOffsets is not empty.

- paimon-common/src/main/java/org/apache/paimon/options/OptionsUtils.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/DataTableSource.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/DataTableSourceTest.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/utils/HiveUtils.java
Linked issue: close #1943
Support using dynamic option in flink job to disable infer scan parallelism for paimon
Added DataTableSourceTest for infer scan parallelism in flink jobs
no
no
> [flink][source] Supports disable infer scan parallelism by flink job dynamic option

- docs/content/maintenance/write-performance.md
- docs/layouts/shortcodes/generated/flink_connector_configuration.html
- docs/layouts/shortcodes/generated/spark_connector_configuration.html
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncDatabaseAction.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncDatabaseAction.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkITCase.java
Committer node may use a large memory if the amount of data written to the table is particularly large, OOM may occur
if the memory is too small. In this case, you need to increase the Committer heap memory, but you may not want to
increase the memory of Flink's TaskManager uniformly, which may lead to a waste of memory.
You can use fine-grained-resource-management of Flink to increase committer heap memory only:
1. Configure Flink Configuration `cluster.fine-grained-resource-management.enabled: true`. (This is default after Flink 1.18)
2. Configure Paimon Table Options: `sink.committer-cpu` (for example 1.0) and `sink.committer-memory` (for example 300 MB, depends on your `TaskManager`).
> [flink] Introduce fine-grained options to increase Committer heap memory only

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/DynamicBucketRowWriteOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FileStoreSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/LocalMergeOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MapToInternalRow.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowDataChannelComputer.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowDataStoreWriteOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowDynamicBucketSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowHashKeyChannelComputer.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowWithBucketChannelComputer.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/UnawareBucketWriteSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalDynamicBucketSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalIndexAssignerOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/KeyPartPartitionKeyExtractor.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/KeyPartRowChannelComputer.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/OrderSorter.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/SortUtils.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/InternalRowTypeSerializer.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/InternalTypeInfo.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/ProjectToRowDataFunction.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/GlobalDynamicBucketTableITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/FlinkSinkTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/RowDataChannelComputerTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/index/GlobalIndexAssignerTest.java
This can avoid many conversion cost between InternalRow and RowData.
> [flink] Use InternalRow instead of RowData in sink sub topo

- paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java
- paimon-core/src/main/java/org/apache/paimon/partition/PartitionPredicate.java
- paimon-core/src/test/java/org/apache/paimon/partition/PartitionPredicateTest.java
When considering tens of thousands of partitions, in Committer node:
- `FileStoreCommitImpl.readAllEntriesFromChangedPartitions` will read all partitions, the predicate will be tens of thousands of `OR`, this will be very low performance.
- We can optimize this by using specific `PartitionPredicate`.
- `PartitionPredicateTest`.
> [core] Introduce PartitionPredicate to improve performance for multiple partitions

- paimon-core/src/main/java/org/apache/paimon/Snapshot.java
- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
- paimon-core/src/test/java/org/apache/paimon/table/IncrementalTimeStampTableTest.java
Linked issue: close #1998 
fix totalRecordCount incorrect when compact in primary key table
IncrementalTimeStampTableTest
no
no
> [core] fix totalRecordCount incorrect when compact in primary key table

- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/Expression.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
> [cdc] Compute column function should be case-insensitive

- paimon-codegen-loader/pom.xml
- paimon-codegen-loader/src/main/java/org/apache/paimon/codegen/CodeGenLoader.java
- paimon-common/src/main/java/org/apache/paimon/plugin/PluginLoader.java
- paimon-filesystems/paimon-oss/pom.xml
- paimon-filesystems/paimon-oss/src/main/java/org/apache/paimon/oss/OSSLoader.java
- paimon-filesystems/paimon-s3/pom.xml
- paimon-filesystems/paimon-s3/src/main/java/org/apache/paimon/s3/S3Loader.java
- pom.xml
Currently to load classes from plugins, `PluginLoader` have to decompress a jar file out of Paimon distribution jar and load that jar file. It is hard for a long existing client (for example a SQL gateway service) to clean up these jar files.
This PR fixes the issue by loading plugin classes directly from distribution jar without decompression.
Existing tests should cover the change.
No.
No.
> [common] Load plugin classes directly from jar without decompression

- docs/content/api/java-api.md
`AlterTable` throws `NullPointerException`, which needs to add code to create database `my_db` at first.
> Update java-api.md as of the official doc has issue.

- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StaticFromTagStartingScanner.java
- paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/StaticFromTagStartingScannerTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkTimeTravelITCase.java
`StaticFromTagStartingScanner` should read a tag instead of a snapshot id.
> [core] Fix that time travel to tag with expired snapshot throws FileNotFoundException

- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/UniversalCompaction.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/compact/ForceUpLevel0CompactionTest.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/compact/UniversalCompactionTest.java
Fix outputlevel is still 0 in extreme scenarios.
This may not be a common case, but it is indeed possible.
For a newly created paimon pk table, with default parameters for num-levels and
others, without adjusting the max-size-amp, size-ratio, and other
configurations, assuming all configurations are using default values.
For a specific bucket:
file1 (1kb) is written,
file2 (1kb) is written,
file3 (1kb) is written,
file4 (1mb) is written,
file5 (10mb) is written
The srS of level0 will be sorted according to
https://github.com/apache/incubator-paimon/blob/master/paimon-core/src/main/java/org/apache/paimon/mergetree/Levels.java#L58 
In this situation, these five level0 files may not go through the pickForSizeAmp
function, outputlevel is 0. This may cause a larger file to appear in level0. I …
> [core] Fix outputlevel is still 0 in extreme scenarios

- docs/content/concepts/primary-key-table.md
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/TableScanUtils.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java
We can support input changelog-producer for Partial-update streaming reading, but only returns input records.
This is also a requirement for scenarios where the downstream only wants to read incremental data.
> [core] Partial-update streaming read supports input changelog-producer

- paimon-core/src/main/java/org/apache/paimon/index/HashBucketAssigner.java
- paimon-core/src/main/java/org/apache/paimon/index/PartitionIndex.java
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/WriteIntoPaimonTable.scala
Linked issue: close #2075 
[core] reduce unnecessary traversals to optimize the assign logic of PartitionIndex.
I made a simple benchmark and continuously used random keys to call the `assign` of `PartitionIndex`. The results showed that removing unnecessary traversals can improve performance by 50% to 200%.
|   | benchmark 1s |  benchmark 5s |  benchmark 10s |  benchmark 30s |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| before | 4247.443 ops/ms  | 2342.67 ops/ms  | 1766.141 ops/ms  | 1287.669 ops/ms  |
| after | 6324.565 ops/ms  | 5738.319 ops/ms  | 5200.766 ops/ms  | 4563.41 ops/ms  |
The existing `org.apache.paimon.index.HashBucketAssignerTest` can verify this change.
No
No
> [core] reduce unnecessary traversals to optimize the assign logic of PartitionIndex.

- docs/content/maintenance/manage-tags.md
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AutoTagForSavepointCommitterOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/AutoTagForSavepointCommitterOperatorTest.java
Linked issue: close #2057 
Currently flink will not send a complete message to the task after the savepoint is successful (unless use `stop-with-savepoint`).  Therefore, we need to create tags for the previous savepoint after the next checkpoint is successful.
- `org.apache.paimon.flink.sink.AutoTagForSavepointCommitterOperatorTest#testAbortSavepointAndCleanTag` to verify that the tag can be cleaned after the savepoint abort.
- `org.apache.paimon.flink.sink.AutoTagForSavepointCommitterOperatorTest#testAutoTagForSavepoint` to verify that the tag can be automatically created for the savepoint after the checkpoint is successful.
No
No
> [flink] create tags for the previous savepoint after a successful checkpoint.

- docs/content/how-to/cdc-ingestion.md
- paimon-core/src/main/java/org/apache/paimon/utils/JsonSerdeUtil.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBActionUtils.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/strategy/MongoVersionStrategy.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableActionITCase.java
- paimon-flink/paimon-flink-cdc/src/test/resources/mongodb/table/defaultid/defaultId-1.js
The `mongodb-conf` introduces the `default.id.generation` parameter as an enhancement to the MongoDB CDC source configuration. The `default.id.generation` setting offers two distinct behaviors: when set to true and when set to false.
When `default.id.generation` is set to true, the MongoDB CDC source adheres to the default `_id` generation strategy, which involves stripping the outer $oid nesting to provide a more straightforward identifier. This mode simplifies the `_id` representation, making it more direct and user-friendly.
On the contrary, when `default.id.generation` is set to false, the MongoDB CDC source retains the original `_id` structure, without any additional processing. This mode offers users the flexibility to work with the raw `_id` format as provided by MongoDB, …
> [flink] Support default.id.generation parameter

- docs/content/concepts/append-only-table.md
- docs/content/concepts/file-operations.md
- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactActionFactory.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/SortCompactAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CompactProcedure.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactActionITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/SortCompactActionITCase.java
Add dynamic option to specify the dynamic table conf when execute CompactAction or SortCompactAction.
For example, we can add --table-conf sink.parallelism=xxx to specify the compaction sink parallelism without change the meta data of the table.
flink run  ./action.jar 
--table-conf sink.parallelism=9
--table-conf xxx=xxx
Add Tests for CompactAction and SortCompactAction about dynamic table conf
No influence to other user behavior.
Added documentations.
> [flink] add dynamic table option for CompactAction and SortCompactAction.

- paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java
- paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreScan.java
- paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreScan.java
- paimon-core/src/main/java/org/apache/paimon/table/ChangelogWithKeyFileStoreTable.java
- paimon-core/src/test/java/org/apache/paimon/TestKeyValueGenerator.java
- paimon-core/src/test/java/org/apache/paimon/operation/KeyValueFileStoreScanTest.java
- paimon-core/src/test/java/org/apache/paimon/table/ChangelogWithKeyColumnTypeFileDataTest.java
- paimon-core/src/test/java/org/apache/paimon/table/ChangelogWithKeyFileDataTableTest.java
- paimon-core/src/test/java/org/apache/paimon/table/ChangelogWithKeyFileMetaFilterTest.java
- paimon-core/src/test/java/org/apache/paimon/table/ChangelogWithKeyTableColumnTypeFileMetaTest.java
- paimon-core/src/test/java/org/apache/paimon/table/SchemaEvolutionTableTestBase.java
Introduce bucket level value filter in primary key.
Current:  primary key does not support value filter.
Improve: if the bucket range min/max doesn't contains the filter target, we don't need to search the bucket any more.
Add test.
The may speed up select in some conditions. No other influence to user.
> [core] Introduce bucket level value filter (filter push down) in primary key table

- docs/content/how-to/cdc-ingestion.md
- docs/layouts/shortcodes/generated/mysql_sync_database.html
- docs/layouts/shortcodes/generated/mysql_sync_table.html
- paimon-core/src/main/java/org/apache/paimon/utils/JsonSerdeUtil.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/CdcActionCommonUtils.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/CdcMetadataConverter.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaSyncTableAction.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableAction.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlDebeziumJsonEventParser.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlMetadataProcessor.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionFactory.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionFactory.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/format/DebeziumEvent.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/CdcActionITCaseBase.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionITCaseBase.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseActionITCase.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
- paimon-flink/paimon-flink-cdc/src/test/resources/mysql/sync_database_setup.sql
- paimon-flink/paimon-flink-cdc/src/test/resources/mysql/sync_table_setup.sql
close #1985
MySqlSyncDatabaseActionITCase#testMetadataColumns()
MySqlSyncTableActionITCase#testMetadataColumns()
> [flink] CDC Ingestion supported metadata columns

- paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyTableCompactionCoordinator.java
- paimon-core/src/main/java/org/apache/paimon/table/source/AbstractInnerTableScan.java
- paimon-core/src/main/java/org/apache/paimon/table/source/InnerStreamTableScanImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/AllDeltaFollowUpScanner.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReader.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
- paimon-core/src/main/java/org/apache/paimon/table/system/FileMonitorTable.java
- paimon-core/src/test/java/org/apache/paimon/table/ChangelogWithKeyFileStoreTableTest.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/CompactorSourceBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/MultiTablesCompactorUtil.java
We have many cases to monitor file changes of a table. Including:
1. Fetch paimon files to new a service to lookup.
2. Monitor files to refresh materialize view.
> [core] Introduce FileMonitorTable to stream read file changes

- paimon-core/src/main/java/org/apache/paimon/operation/FileDeletionBase.java
- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreExpireImpl.java
- paimon-core/src/main/java/org/apache/paimon/operation/SnapshotDeletion.java
- paimon-core/src/main/java/org/apache/paimon/operation/TagDeletion.java
- paimon-core/src/main/java/org/apache/paimon/table/RollbackHelper.java
- paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
- paimon-core/src/test/java/org/apache/paimon/operation/CleanedFileStoreExpireTest.java
- paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java
For example, if a data file is upgraded, it has an ADD entry and a DELETE entry. If it only reads the DELETE entry successfull, the upgraded data file will be deleted.
> [core] FileDeletionBase should cancel reading manifest files when any file is failed to read

- docs/content/how-to/writing-tables.md
add a note about spark insert overwrite
> [doc] Adding Considerations for Spark's Insert Overwrite

- paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
- paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java
- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
Currently, `FileSystemCatalog` and `HiveCatalog` contains a lot of common code. For example, both catalog needs to check if the table to be deleted is a system table, and if that table exists.
This PR extracts common code into `AbstractCatalog`, which makes introducing new catalog easier.
No.
No.
> [core] Move common code from FileSystemCatalog and HiveCatalog into AbstractCatalog

- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcMultiplexRecordChannelComputer.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSink.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/MultiTableCommittableChannelComputer.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSinkTest.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
Currently， the parallelism is set to 1 but actually the cdc records can be shuffled by table name. This PR fix it.
> [flink] Correct the partitioning for multi-table CDC between write to commit

- paimon-flink/paimon-flink-1.14/src/main/java/org/apache/paimon/flink/utils/TableEnvironmentUtils.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/DeleteAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MergeIntoAction.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/TableActionBase.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/MergeIntoProcedure.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ProcedureBase.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/TableEnvironmentUtils.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/MergeIntoActionITCase.java
Without named argument, it is not easy to provide a simple merge_into procedure to users.
So we should simplify the API.
This PR only provide matched-upsert, matched-delete and not-matched-insert to users.
> [flink] Refactor MergeIntoProcedure to make the api easier to use

- docs/content/concepts/primary-key-table.md
- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/IndexBootstrap.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/index/IndexBootstrapTest.java
- `cross-partition-upsert.bootstrap-min-partition` is hard to be configured, actually we need a TTL instead of startup partition, a long running job should not rely on a static startup partition.
- now, use `cross-partition-upsert.index-ttl` to filter scan splits, this can just replace old `bootstrap-min-partition` feature.
> [flink] Remove cross-partition-upsert.bootstrap-min-partition

- paimon-core/src/main/java/org/apache/paimon/sort/BinaryInMemorySortBuffer.java
- paimon-core/src/test/java/org/apache/paimon/table/TableTestBase.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/RocksDBState.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/RocksDBStateFactory.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/RocksDBValueState.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalIndexAssigner.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalIndexAssignerOperator.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/GlobalDynamicBucketTableITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/index/GlobalIndexAssignerTest.java
RocksDB put is too slow, we can use RocksDB bulkload.
> [core] Introduce Index BulkLoading for cross partition update

- paimon-common/src/test/java/org/apache/paimon/data/serializer/ByteSerializerTest.java
- paimon-common/src/test/java/org/apache/paimon/data/serializer/LongSerializerTest.java
- paimon-common/src/test/java/org/apache/paimon/data/serializer/NullableSerializerTest.java
This pr is aims to modify some wrong comments in java doc of serializer tests module.
> [common] Fix class java doc errors in serializer tests

- paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java
- paimon-core/src/main/java/org/apache/paimon/table/FileStoreTableFactory.java
- paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyTableUtils.java
- paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyColumnTypeFileDataTest.java
- paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileDataTableTest.java
- paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileMetaFilterTest.java
- paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
- paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyTableColumnTypeFileMetaTest.java
- paimon-core/src/test/java/org/apache/paimon/table/WritePreemptMemoryTest.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkTableSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkTableSinkBase.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/LocalMergeOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/OrderSorter.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/DataTableSource.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PrimaryKeyFileStoreTableITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/SortCompactActionForDynamicBucketITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/statistics/PrimaryKeyTableStatisticsTest.java
Now, there is no ChangelogWithValueCount, only PrimaryKey Table.
> [core] Rename ChangelogWithKey to PrimaryKey

- paimon-core/src/main/java/org/apache/paimon/disk/InMemoryBuffer.java
- paimon-core/src/test/java/org/apache/paimon/disk/InMemoryBufferTest.java
Lack `this.numBytesInLastBuffer = 0;` in reset.
After reset for InMemoryBuffer, iterator may produce strange records or exception:
```
Caused by: java.io.IOException: Read unexpected bytes in source of positionInSegment[4] and limitInSegment[12344]
at org.apache.paimon.data.serializer.BinaryRowSerializer.pointTo(BinaryRowSerializer.java:200)
at org.apache.paimon.data.serializer.BinaryRowSerializer.mapFromPages(BinaryRowSerializer.java:165)
at org.apache.paimon.data.serializer.InternalRowSerializer.mapFromPages(InternalRowSerializer.java:188)
at org.apache.paimon.data.serializer.InternalRowSerializer.mapFromPages(InternalRowSerializer.java:39)
at org.apache.paimon.disk.InMemoryBuffer$InMemoryBufferIterator.next(InMemoryBuffer.java:163)
at …
```
> [core] Fix iterator bug after reset for InMemoryBuffer

- docs/content/migration/_index.md
- docs/content/migration/upsert-to-partitioned.md
- docs/layouts/shortcodes/generated/core_configuration.html
- docs/layouts/shortcodes/generated/spark_connector_configuration.html
- paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-common/src/main/java/org/apache/paimon/data/JoinedRow.java
- paimon-core/src/main/java/org/apache/paimon/metastore/AddPartitionTagCallback.java
- paimon-core/src/main/java/org/apache/paimon/metastore/TagPreviewCommitCallback.java
- paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/TagCallback.java
- paimon-core/src/main/java/org/apache/paimon/tag/TagAutoCreation.java
- paimon-core/src/main/java/org/apache/paimon/tag/TagPeriodHandler.java
- paimon-core/src/main/java/org/apache/paimon/tag/TagPreview.java
- paimon-core/src/main/java/org/apache/paimon/tag/TagTimeExtractor.java
- paimon-core/src/main/java/org/apache/paimon/utils/PartitionPathUtils.java
- paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
- paimon-core/src/test/java/org/apache/paimon/catalog/PrimaryKeyTableTestBase.java
- paimon-core/src/test/java/org/apache/paimon/tag/TagAutoCreationTest.java
- paimon-core/src/test/java/org/apache/paimon/tag/TagPreviewTest.java
- paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java
- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveMetastoreClient.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/HiveSchema.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/mapred/PaimonInputFormat.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/mapred/PaimonRecordReader.java
- paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/utils/HiveUtils.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/mapred/PaimonRecordReaderTest.java
Linked issue: close #2125
The Tag will maintain the manifests and data files of the snapshot.
A typical usage is creating tags daily, then you can maintain the historical data of each day for batch reading.
When using primary key tables, a non-partitioned approach is often used to maintain updates, in order to mirror and
synchronize tables from upstream database tables. This allows users to query the latest data. The tradition of Hive
data warehouses is not like this. Offline data warehouses require an immutable view every day to ensure the idempotence
of calculations. So we created a Tag mechanism to output these views.
However, the traditional use of Hive data warehouses is more accustomed to using partitions to specify the query's Tag,
and is more accustomed to using Hive computing …
> [hive] Introduce metastore.tag-to-partition for Hive metastore

- paimon-common/src/main/java/org/apache/paimon/fs/FileIO.java
- paimon-common/src/main/java/org/apache/paimon/fs/Path.java
- paimon-common/src/main/java/org/apache/paimon/fs/hadoop/HadoopFileIO.java
- paimon-common/src/main/java/org/apache/paimon/utils/ReflectionUtils.java
- paimon-common/src/test/java/org/apache/paimon/fs/FileIOBehaviorTestBase.java
- paimon-common/src/test/java/org/apache/paimon/fs/FileIOTest.java
- paimon-common/src/test/java/org/apache/paimon/fs/HdfsBehaviorTest.java
- paimon-core/src/main/java/org/apache/paimon/consumer/Consumer.java
- paimon-core/src/main/java/org/apache/paimon/consumer/ConsumerManager.java
- paimon-spark/paimon-spark-common/pom.xml
- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkS3ITCase.java
This fixes #2144
The `fileIO.newOutputStream(path, overwrite))` is not atomic for HDFS, it may results to empty file.
We should use rename with overwrite for HDFS.
> [core] ConsumerManager should use atomic overwrite for HDFS

- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/metrics/FlinkCounter.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/metrics/FlinkGauge.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/metrics/FlinkHistogram.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/metrics/FlinkMetricGroup.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/metrics/FlinkMetricRegistry.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/Committer.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CompactorSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkWriteSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTablesCompactorSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCommitter.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreMultiCommitter.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/UnawareBucketCompactionSink.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/StoreMultiCommitterTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/utils/MetricUtils.java
This PR connects Paimon's metric system with Flink's metric system. The life cycle of Paimon's metrics is now handled by Flink's metric group in Flink connector.
* `CommitterOperatorTest#testCommitMetrics`
* `StoreMultiCommitterTest#testCommitMetrics`
No.
No.
> [flink] Bridge Flink's metrics system with Paimon's metrics

- paimon-core/src/main/java/org/apache/paimon/disk/IOManager.java
- paimon-core/src/main/java/org/apache/paimon/disk/IOManagerImpl.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalIndexAssigner.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalIndexAssignerOperator.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/index/GlobalIndexAssignerTest.java
When there is no index, and it is a batch job, we don't need to use rocksdb, we can just use sort to bulk load records.
> [core] Bulk load records for GlobalIndexAssigner when index is empty

- paimon-common/src/main/java/org/apache/paimon/lineage/LineageMeta.java
- paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
- paimon-core/src/main/java/org/apache/paimon/table/CatalogEnvironment.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/AbstractFlinkTableFactory.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkLineageITCase.java
Linked issue: close #2189 
Use `LineageMetaFactory` in `CatalogEnvironment` instead of `LineageMeta` because `LineageMeta` may has some non-serialized fields such as connection for jdbc lineage meta.
This change can be covered by `FlinkLineageITCase`
no
no
> [lineage] Use lineage meta factory in CatalogEnvironment

- docs/layouts/shortcodes/generated/kafka_sync_table.html
- docs/layouts/shortcodes/generated/mongodb_sync_table.html
- docs/layouts/shortcodes/generated/mysql_sync_table.html
fix the hyperlink in the description of cdc module "--computed-column" cannot be jumped
Linked issue: open #2191
> [doc] fix the hyperlink in the description of cdc module "--computed-column" cannot be jumped

- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
This is because `full-compaction` and `lookup` changelog producers will output the changes in later compact snapshot. If we read the changes of the overwrite snapshot, the output is duplicated.
> [core] Add validation to forbid setting stream-read-overwrite with 'full-compaction' or 'lookup' changelog producer

- paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
- paimon-core/src/main/java/org/apache/paimon/table/system/SystemTableLoader.java
Linked issue: close #2195 
This PR aims to load all table paths lazily for system database
This issue is covered by existing test `CatalogTableITCase`
no
no
> [core] Lazy load all table paths for system database

- docs/content/engines/presto.md
- docs/content/engines/trino.md
Fixed an error with the Hadoop configuration in presto and trino
> [doc] Fixed an error with the Hadoop configuration in presto and trino

- paimon-flink/paimon-flink-cdc/pom.xml
To run test in idea, we need to exclude the low version of protobuf. Otherwise, idea will will the low version protobuf (it can't recognize shade)
> [flink] exclude dependency of protobuf

- paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java
- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreScan.java
- paimon-core/src/main/java/org/apache/paimon/operation/metrics/ScanMetrics.java
- paimon-core/src/main/java/org/apache/paimon/operation/metrics/ScanStats.java
- paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReader.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
- paimon-core/src/test/java/org/apache/paimon/operation/metrics/ScanMetricsTest.java
> [Core] support scan metrics

- docs/content/how-to/querying-tables.md
- docs/layouts/shortcodes/generated/flink_connector_configuration.html
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/DataTableSource.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ReadWriteTableITCase.java
> [flink] Support setting upper limit for inferring scan parallelism for source

- docs/content/how-to/writing-tables.md
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkRow.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkTable.java
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/WriteIntoPaimonTable.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/extensions/PaimonSparkSessionExtensions.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/schema/SparkSystemColumns.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/util/SparkRowUtils.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteRowLeverCommands.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/DeleteFromPaimonTableCommand.scala
- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkWriteITCase.java
- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkWriteWithKyroITCase.java
- paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DeleteFromTableTest.scala
1. add delete check: pk table && 'merge-engine' = 'deduplicate'
2. support distributed delete by spark
3. optimization for delete is drop partition
4. optimization for truncate table (using commit.purgeTable)
> [spark] Enhance spark DELETE

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendOnlyTableCompactionWorkerOperator.java
Wait thread pool shutdown.
Aim to fix test `AppendOnlyTableCompactionWorkerOperatorTest.testAsyncCompactionFileDeletedWhenShutdown`
> [flink] wait executors shutdown to avoid test break

- docs/content/concepts/basic-concepts.md
- docs/content/how-to/creating-tables.md
Linked issue: close #2237
Partition keys not have to be a subset of primary keys when primary keys are defined if the table is configured with dynamic bucket.
We need to fix this description about partition keys.
> [doc] Fix the documentation about partition keys

- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
Driver should be registered before get JDBC connection when using streampark to submit jobs.
> [flink][cdc] Register MySQL JDBC driver when constructing cdc action

- paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
- paimon-core/src/main/java/org/apache/paimon/table/system/SystemTableLoader.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
Fix 'list tables' to view all tables in the sys database.
> [hotfix] Fix 'list tables' to view all tables in the sys database.

- paimon-flink/paimon-flink-1.14/pom.xml
- paimon-flink/paimon-flink-1.15/pom.xml
This is because shade doesn't works in IDEA.
> [hotfix] Exclude conflict jar for paimon-flink tests

- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionUtils.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionITCaseBase.java
Older versions of the Kafka clients api may return null value for the partition info, thus throws a NPE.
This PR improve the error message.
> [flink][kafka-cdc] Improve KafkaActionUtils#getKafkaEarliestConsumer exception message and fix test timeout excption

- paimon-core/src/main/java/org/apache/paimon/table/sink/TableCommitImpl.java
- paimon-core/src/main/java/org/apache/paimon/tag/TagAutoCreation.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/StoreMultiCommitterTest.java
https://github.com/apache/incubator-paimon/pull/2188/files
I conducted relevant tests locally using MySQL, and here are the screenshots:
There is an issue that arises, for instance, when I set the tag creation to once a day and checkpoints to occur every 2 minutes. This results in a large number of snapshot and manifest files being generated. I believe there is room for optimization. Each time a snapshot is forcefully created, it should be checked whether it coincides with the next scheduled tag creation time. If it does, proceed with the snapshot creation; otherwise, skip it.
The following image is a screenshot taken after conducting tests with the logical corrections applied:
> [core] Fix auto process time create snapshot for tag

- paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadITCase.java
When there are hundreds of tables in the database,  and the results of the `show tables` command are not sorted, we need to search one by one to look up if a table exists.
If the results are sorted, we can quickly locate it based on the dictionary order.
> [core] Sort the results of the `show tables` command

- docs/content/maintenance/dedicated-compaction.md
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CompactorSinkBuilder.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CompactorSinkITCase.java
Enable table-conf sink.parallelism for ordinary dedicated compact job. We can use --table-conf sink.parallelism=xxx to modify the parallelism of dedicated compaction job.
Example: 
```sql
flink run ./paimon-flink-action-0.6-SNAPSHOT.jar compact \
--warehouse \
/Users/paimontest/GlobalBatchReadWrite \
--database \
my_db \
--table \
Orders1 \
--table-conf sink.parallelism=4
```
Added documentation for dedicated compaction job.
> [flink] Add config "table-conf sink.parallelism" for ordinary compact

- paimon-flink/paimon-flink-1.17/pom.xml
paimon-flink-common use flink-1.18, so paimon-flink-1.17 should exculdes denpendencies of paimon-flink-common
> [flink] Correct pom of paimon-flink-1.17

- docs/content/how-to/querying-tables.md
- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ConsumerProgressCalculator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FileStoreSourceReader.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkSourceBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ReaderConsumeProgressEvent.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedContinuousFileSplitEnumerator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/assigners/AlignedSplitAssigner.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/assigners/DynamicPartitionPruningAssigner.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/assigners/FIFOSplitAssigner.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/assigners/PreAssignSplitAssigner.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/assigners/SplitAssigner.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/TableScanUtils.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumeratorTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FileStoreSourceReaderTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/align/AlignedSourceReaderTest.java
Linked issue: close #2157 
[flink] support the feature of ContinuousFileStoreSource using consumer-id.
`Enumerator` will assign split to the `reader` in the order of snapshots, and the `reader` will also consume in the order of snapshots. Therefore, the consumption progress of a single reader is:
1. If the reader is in the `enumerator's` waiting list, then the consumption progress of the `reader` is equal to the snapshot assigned by `splitAssigner` next time. If there is no split in `splitAssigner`, it is equal to the snapshot of the next scan by enumerator.
2. If the reader is not in the `enumerator's` waiting list, the `reader's` consumption progress is equal to the greater of the snapshot consumed by the consumer and the snapshot recently assigned to it by `splitAssigner`.
The minimum …
> [flink] support the feature of ContinuousFileStoreSource using consumer-id.

- paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBOptions.java
Now, RocksDB log file will output to flink/log, for session cluster, this will outputs more and more log files...
We should keep RocksDB default configuration, log file should be along to data files.
> [core] Remove RocksDB log relocation to flink log

- docs/content/cdc-ingestion/kafka-cdc.md
- paimon-core/src/main/java/org/apache/paimon/utils/JsonSerdeUtil.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/CdcActionCommonUtils.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/MessageQueueSyncTableActionBase.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/RecordParser.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/canal/CanalFieldParser.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/canal/CanalRecordParser.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/debezium/DebeziumRecordParser.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/maxwell/MaxwellRecordParser.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/ogg/OggRecordParser.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableAction.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcMultiplexRecord.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcMultiplexRecordEventParser.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncDatabaseActionITCase.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java
- paimon-flink/paimon-flink-cdc/src/test/resources/kafka/canal/database/incomplete/canal-data-1.txt
- paimon-flink/paimon-flink-cdc/src/test/resources/kafka/canal/table/incomplete/canal-data-1.txt
- paimon-flink/paimon-flink-cdc/src/test/resources/kafka/canal/table/nonpk/canal-data-1.txt
Currently the RecordParser has strong validation of the Json format. But in some cases, the desired data is not present (data type, table name, etc). We should make sure we can try best to synchronize data. This PR has done:
1. Remove the strong validation before handle data. Now the RecordParser will check specific field when really need it.
2. If the json is invalid, log it before throwing exception (for trouble shooting).
3. Make database, table and primary keys optional.
4. Handle case sensitivity at last.
> [flink][kafka-cdc] Refactor Kafka CDC RecordParser

- paimon-core/src/main/java/org/apache/paimon/io/DataFileMeta.java
- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommit.java
- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/TableCommitImpl.java
- paimon-core/src/test/java/org/apache/paimon/table/sink/TableCommitTest.java
If a user restores a Flink job from an old savepoint and the table has been written by another job for a long time, it means that the files in the savepoint may have been deleted.
At present, the commit will still succeed, which results in the table containing deleted files, which is a serious problem.
This PR aims to check the recovered file, and if it does not exist, report an error to the user.
Fix #2273
> [core] Check existence for commit files of savepoint recovering

- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/LocationHelper.java
- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/StorageLocationHelper.java
- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/TBPropertiesLocationHelper.java
- paimon-hive/paimon-hive-connector-2.3/src/test/java/org/apache/paimon/hive/Hive23CatalogITCase.java
- paimon-hive/paimon-hive-connector-3.1/src/test/java/org/apache/paimon/hive/Hive31CatalogITCase.java
- paimon-hive/paimon-hive-connector-3.1/src/test/java/org/apache/paimon/hive/HiveWriteITCase.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/FileStoreTestUtils.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveWriteITCase.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/PaimonStorageHandlerITCase.java
We want to query Paimon tables with Presto, but our Paimon tables are scattered across different warehouse directories(such as `/user1/warehouse`, `/user2/warehouse`).
Therefore, we use Hive catalog to discover the addresses of different Paimon warehouses. However, in the current implementation of the Hive catalog, it does not use the Hive table's location as the location for Paimon tables.
In this pull request, we have re-implemented the `org.apache.paimon.hive.HiveCatalog#getDataTableLocation` method, which achieves the desired effect.
> [Hive] Using hive table location when catalog is HiveCatalog

- paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyCompactManager.java
- paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyCompactionTask.java
- paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactManager.java
- paimon-core/src/main/java/org/apache/paimon/metrics/MetricGroup.java
- paimon-core/src/main/java/org/apache/paimon/metrics/MetricGroupImpl.java
- paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/operation/metrics/CommitMetrics.java
- paimon-core/src/main/java/org/apache/paimon/operation/metrics/CompactionMetrics.java
- paimon-core/src/main/java/org/apache/paimon/operation/metrics/ScanMetrics.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/metrics/FlinkMetricGroup.java
Currently we don't have a `close` method in `MetricGroup`. When using bucket-wise metric groups (for example `CompactMetrics`), because more and more buckets will be written as the job runs, we need to clean up the resources (for example, their corresponding Flink metric group) in time.
This PR closes `CompactMetrics` after its corresponding writer is closed.
As `CompactMetrics` is not bridged into Flink's metrics system at this time, we can't come up with unit tests. This should be tested in the PR when bridging `CompactMetrics` with Flink's metrics system.
No.
No.
> [core] Close CompactMetrics after closing its corresponding writer

- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTypeUtils.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java
- paimon-flink/paimon-flink-cdc/src/test/resources/kafka/canal/table/incomplete/canal-data-2.txt
The decimal type will validate that precision is between 1-38.
`KafkaCanalSyncTableActionITCase#testMissingDecimalPrecision`
> [cdc] Fix that initializing decimal type that missing precision will throw exception

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogTest.java
Linked issue: close #2283 
Add UT `FlinkCatalogTest#testCreateTableFromTableDescriptor`
> [flink] Fix the bug that Flink will throw UnsupportedOperationException when using TableDescriptor in Flink jobs

- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
If users use `BEGIN STATEMENT SET` and `END STATEMENT SET` to execute multiple `INSERT` statements into the same Paimon table, commit conflicts will also occur. This PR adds this possible cause into the exception message.
No need for tests.
No.
No.
> [core] Add one more possible cause in commit conflict exception message

- paimon-common/src/main/java/org/apache/paimon/predicate/And.java
- paimon-common/src/main/java/org/apache/paimon/predicate/CompoundPredicate.java
- paimon-common/src/main/java/org/apache/paimon/predicate/LeafPredicate.java
- paimon-common/src/main/java/org/apache/paimon/predicate/Or.java
- paimon-common/src/main/java/org/apache/paimon/predicate/Predicate.java
- paimon-common/src/main/java/org/apache/paimon/predicate/PredicateProjectionConverter.java
- paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/source/AbstractDataTableRead.java
- paimon-core/src/main/java/org/apache/paimon/table/source/InnerTableRead.java
- paimon-core/src/main/java/org/apache/paimon/table/source/KeyValueTableRead.java
- paimon-core/src/main/java/org/apache/paimon/table/source/TableRead.java
- paimon-core/src/test/java/org/apache/paimon/table/AppendOnlyFileStoreTableTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/TestChangelogDataReadWrite.java
Computing engines such as Trino need to convert a row into Trino's own data structure after reading it, which is costly. We can actually perform filtering before returning to Trino to reduce the amount of data that needs to be converted.
Trino Connector can just use `TableRead.executeFilter()` to enable this feature.
> [core] Introduce executeFilter to TableRead

- paimon-core/src/main/java/org/apache/paimon/partition/PartitionPredicate.java
- paimon-core/src/test/java/org/apache/paimon/partition/PartitionPredicateTest.java
Linked issue: close #2350 
[common] MultiplePartitionPredicate returns true only after all partition fields have been checked.
- `org.apache.paimon.partition.PartitionPredicateTest#testPartitionWithMultiFields`
No
No
> [common] MultiplePartitionPredicate returns true only after all partition fields have been checked.

- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/RetryingMetaStoreClientFactory.java
Add 1.x HiveMetastore support. It may be useful for presto and trino due to presto/trino using 1.2.2 for hive connector.
Support Method:
`org.apache.hadoop.hive.metastore.RetryingMetaStoreClient#getProxy(org.apache.hadoop.hive.conf.HiveConf, org.apache.hadoop.hive.metastore.HiveMetaHookLoader, java.util.Map<java.lang.String,java.lang.Long>, java.lang.String)`
> [Hive] HiveCatalog support hive 1.x

- paimon-common/src/main/java/org/apache/paimon/data/columnar/ColumnarRow.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FullCompactionFileStoreITCase.java
- paimon-format/src/main/java/org/apache/paimon/format/orc/reader/OrcRowColumnVector.java
> [core] fix after compactioned the array elements are duplicated

- paimon-core/src/main/java/org/apache/paimon/table/source/AbstractInnerTableScan.java
- paimon-core/src/main/java/org/apache/paimon/table/source/DataSplit.java
- paimon-core/src/main/java/org/apache/paimon/table/source/RawFile.java
- paimon-core/src/main/java/org/apache/paimon/table/source/Split.java
- paimon-core/src/main/java/org/apache/paimon/table/source/TableScan.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReader.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
- paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/SnapshotReaderTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FileStoreSourceSplitGeneratorTest.java
It would be more natural to check if a split can be read without merging directly from that split, not from other sources.
This PR moves `convertToRawFiles` method from `TableScan` to `Split`.
This PR is a refactor. Existing tests should cover the correctness.
No.
No.
> [core] Move convertToRawFiles method from TableScan to Split

- docs/content/how-to/system-tables.md
- docs/content/maintenance/read-performance.md
- paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/system/ReadOptimizedTable.java
- paimon-core/src/main/java/org/apache/paimon/table/system/SystemTableLoader.java
- paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
OLAP systems have high demands on reading efficiency. This PR introduces a new system table called the "read-optimized table". This table is optimized for reading by avoiding merging files.
For primary key tables, this system table only scans files on top level. For append only tables, as all files can be read without merging, this system table does nothing special.
* `PrimaryKeyFileStoreTableTest#testReadOptimizedTable`.
* `CatalogTableITCase#testReadOptimizedTable`.
No.
Yes. Document is also updated.
> [core] Introduce read-optimized system table

- paimon-core/src/main/java/org/apache/paimon/crosspartition/BucketAssigner.java
- paimon-core/src/main/java/org/apache/paimon/crosspartition/DeleteExistingProcessor.java
- paimon-core/src/main/java/org/apache/paimon/crosspartition/ExistingProcessor.java
- paimon-core/src/main/java/org/apache/paimon/crosspartition/GlobalIndexAssigner.java
- paimon-core/src/main/java/org/apache/paimon/crosspartition/SkipNewExistingProcessor.java
- paimon-core/src/main/java/org/apache/paimon/crosspartition/UseOldExistingProcessor.java
- paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
- paimon-core/src/main/java/org/apache/paimon/utils/RowIterator.java
- paimon-core/src/test/java/org/apache/paimon/schema/TableSchemaTest.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/GlobalDynamicBucketTableITCase.java
Now only default mode supports bulk load mode for cross partition update.
This PR:
1. Throws exception for sequence-field definition for cross partition update, this is hard to support, we cannot know old sequence number for the record in previous partition.
2. Extract `ExistingProcessor` to support bulk load mode for partial-update and others merge-engine.
> [core] Support bulk load mode for partial-update merge-engine

- docs/layouts/shortcodes/generated/flink_connector_configuration.html
- paimon-core/src/main/java/org/apache/paimon/crosspartition/GlobalIndexAssigner.java
- paimon-core/src/test/java/org/apache/paimon/crosspartition/GlobalIndexAssignerTest.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTablesCompactorSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/PrepareCommitOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalDynamicBucketSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalIndexAssignerOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/ManagedMemoryUtils.java
Default block cache of RocksDB is 8MB. It is too small to performance.
We can use Flink managed memory for RocksDB.
> [core] Use Flink Managed Memory for RocksDB in cross partition update

- paimon-format/src/main/resources/META-INF/NOTICE
- pom.xml
- tools/ci/paimon-ci-tools/pom.xml
- tools/ci/paimon-ci-tools/src/main/java/org/apache/paimon/tools/ci/licensecheck/JarFileChecker.java
- tools/ci/paimon-ci-tools/src/main/java/org/apache/paimon/tools/ci/licensecheck/LicenseChecker.java
- tools/ci/paimon-ci-tools/src/main/java/org/apache/paimon/tools/ci/licensecheck/NoticeFileChecker.java
- tools/ci/paimon-ci-tools/src/main/java/org/apache/paimon/tools/ci/suffixcheck/ScalaSuffixChecker.java
- tools/ci/paimon-ci-tools/src/main/java/org/apache/paimon/tools/ci/utils/dependency/DependencyParser.java
- tools/ci/paimon-ci-tools/src/main/java/org/apache/paimon/tools/ci/utils/deploy/DeployParser.java
- tools/ci/paimon-ci-tools/src/main/java/org/apache/paimon/tools/ci/utils/notice/NoticeContents.java
- tools/ci/paimon-ci-tools/src/main/java/org/apache/paimon/tools/ci/utils/notice/NoticeParser.java
- tools/ci/paimon-ci-tools/src/main/java/org/apache/paimon/tools/ci/utils/shade/ShadeParser.java
- tools/ci/paimon-ci-tools/src/main/java/org/apache/paimon/tools/ci/utils/shared/Dependency.java
- tools/ci/paimon-ci-tools/src/main/java/org/apache/paimon/tools/ci/utils/shared/DependencyTree.java
- tools/ci/paimon-ci-tools/src/main/java/org/apache/paimon/tools/ci/utils/shared/ParserUtils.java
- tools/ci/paimon-ci-tools/src/main/resources/log4j2.properties
- tools/ci/paimon-ci-tools/src/main/resources/modules-defining-excess-dependencies.modulelist
- tools/ci/paimon-ci-tools/src/test/java/org/apache/paimon/tools/ci/licensecheck/JarFileCheckerTest.java
- tools/ci/paimon-ci-tools/src/test/java/org/apache/paimon/tools/ci/licensecheck/NoticeFileCheckerTest.java
- tools/ci/paimon-ci-tools/src/test/java/org/apache/paimon/tools/ci/utils/dependency/DependencyParserCopyTest.java
- tools/ci/paimon-ci-tools/src/test/java/org/apache/paimon/tools/ci/utils/dependency/DependencyParserTreeTest.java
- tools/ci/paimon-ci-tools/src/test/java/org/apache/paimon/tools/ci/utils/deploy/DeployParserTest.java
- tools/ci/paimon-ci-tools/src/test/java/org/apache/paimon/tools/ci/utils/notice/NoticeParserTest.java
- tools/ci/paimon-ci-tools/src/test/java/org/apache/paimon/tools/ci/utils/shade/ShadeParserTest.java
- tools/ci/paimon-ci-tools/src/test/java/org/apache/paimon/tools/ci/utils/shared/DependencyTreeTest.java
This can avoid the releasing of paimon-shade.
> [ci] Migrate ci-tools from shade to this repo

- paimon-e2e-tests/src/test/java/org/apache/paimon/tests/cdc/MySqlCdcE2eTestBase.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java
- tools/maven/checkstyle.xml
Linked issue: close #2382
It is more reasonable import class ImmutableMap from package:org.apache.paimon.shade.guava30.com.google.common.collect which is from jar: org.apache.paimon:paimon-shade-guava-30
, instead of org.apache.hadoop.shaded.com.google.common.collect.ImmutableMap
> [spark] It is more reasonable import class ImmutableMap from package:org.apache.paimon.shade.guava30.com.google.common.collect

- paimon-core/src/main/java/org/apache/paimon/io/DataFileMeta.java
- paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
- paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/SnapshotReaderTest.java
Currently `SnapshotReaderImpl#makeRawTableFile` determines file format of `DataFileMeta` through `CoreOptions#formatType`. However in primary key table, different file levels may have different formats.
This PR determines file format from filename suffix.
* `SnapshotReaderTest#testGetPrimaryKeyRawFiles`
No.
No.
> [core] Extract file format of DataFileMeta through suffix of filename

- paimon-spark/paimon-spark-3.3/pom.xml
- paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/spark/sql/execution/shim/PaimonCreateTableAsSelectStrategy.scala
- paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/DataFrameWriteTest.scala
- paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/DDLTest.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/extensions/PaimonSparkSessionExtensions.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/execution/CallExec.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/execution/PaimonStrategy.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/execution/StrategyHelper.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/execution/shim/PaimonCreateTableAsSelectStrategy.scala
- paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLTest.scala
- paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DataFrameWriteTest.scala
to support `create table as select` or `saveAsTable` api
Linked issue: https://github.com/apache/incubator-paimon/issues/2372
> [Spark] Supports CTAS

- paimon-core/src/main/java/org/apache/paimon/manifest/ManifestEntry.java
- paimon-core/src/main/java/org/apache/paimon/manifest/ManifestFileMeta.java
If there are many manifest files for tables, synchronous merging can be slow.
> [Core]Supports asynchronous manifest merge

- paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyCompactManager.java
- paimon-core/src/main/java/org/apache/paimon/table/source/AppendOnlySplitGenerator.java
Linked issue: close #2397 
[core] AppendOnlySplitGenerator skips the check of sequence number overlap in UNAWARE mode to reduce invalid logs.
No
No
No
> [core] AppendOnlySplitGenerator skips the check of sequence number overlap in UNAWARE mode to reduce invalid logs.

- paimon-core/src/main/java/org/apache/paimon/operation/FileDeletionBase.java
- paimon-core/src/main/java/org/apache/paimon/operation/TagDeletion.java
- paimon-core/src/main/java/org/apache/paimon/utils/ObjectsFile.java
- paimon-core/src/test/java/org/apache/paimon/operation/FileStoreExpireTestBase.java
- paimon-core/src/test/java/org/apache/paimon/operation/UncleanedFileStoreExpireTest.java
Currently, when we delete a tag, the data manifest entries are not merged, so the result may contains data files that should not be deleted. For example, a tag base is (+A, -A, +B), if we don't merge it, we will get candidate deleted file set (A, B).
`UncleanedFileStoreExpireTest#testMixedSnapshotAndTagDeletion`
> [core] Fix that tag deletion might delete used data files

- paimon-filesystems/paimon-oss-impl/src/main/java/org/apache/paimon/oss/HadoopCompliantFileIO.java
Maybe there are oss and oss-hdfs at the same time.
> [oss] FileSystem should be cached by authority

- docs/content/maintenance/manage-snapshots.md
- docs/content/maintenance/manage-tags.md
[doc] correct version typo in rollback related documents.
The rollback action uses version as a parameter, but it is spelled incorrectly in the documentation. https://github.com/apache/incubator-paimon/blob/master/paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RollbackToActionFactory.java#L41
No
No
No
> [doc] correct version typo in rollback related documents.

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkGenericCatalog.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/FlinkGenericCatalogITCase.java
Fix Table Doesn't Exist Exception when Reading System Tables with Flink Generic Catalog
> [Flink] Fix Table Doesn't Exist Exception when Reading System Tables with Flink Generic Catalog

- paimon-filesystems/paimon-oss/pom.xml
- paimon-filesystems/paimon-s3/pom.xml
Release 0.6 RC1 is canceled because META-INF directory of oss and s3 does not appear in the root of jar. This PR fixes the issue.
Tested by hand.
No.
No.
> [filesystem] Copy META-INF directory of oss and s3 to the root of jar

- docs/content/engines/hive.md
- docs/content/how-to/creating-catalogs.md
- docs/content/migration/upsert-to-partitioned.md
- paimon-common/src/main/java/org/apache/paimon/fs/FileIO.java
- paimon-core/src/main/java/org/apache/paimon/catalog/CatalogFactory.java
- paimon-flink/paimon-flink-common/pom.xml
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkGenericCatalogFactory.java
- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalogFactory.java
- paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/HiveCatalogTest.java
- paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveLocationTest.java
1. Warehouse can be empty in HiveCatalog, it can infer warehouse from hadoop Conf
2. If the scheme of warehouse is empty, get Default Uri from conf to create FileIO
> [hive] HiveCatalog infer warehouse from hadoop Conf

- paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/operation/FileStoreWrite.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/BatchWriteBuilderImpl.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/InnerTableWrite.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/TableWriteImpl.java
- paimon-core/src/test/java/org/apache/paimon/table/DynamicBucketTableTest.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperatorTest.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWriteImpl.java
The interface should be `FileStoreWrite`. All invokers should be only rely on `FileStoreWrite` instead of `AbstractFileStoreWrite`.
> [core] AbstractFileStoreWrite should not be the interface

- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SaveMode.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/SchemaHelper.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/extensions/PaimonSparkSessionExtensions.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/sources/StreamHelper.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/analysis/PaimonCoerceArguments.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/analysis/PaimonProcedureResolver.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/PaimonSqlExtensionsAstBuilder.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/PaimonCallCommand.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/PaimonCallStatement.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/execution/PaimonCallExec.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/execution/PaimonStrategy.scala
- paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/extensions/CallStatementParserTest.java
Linked issue: https://github.com/apache/incubator-paimon/issues/2449
> [spark] Add 'Paimon' prefix for Call Procedure

- docs/content/cdc-ingestion/overview.md
- docs/layouts/shortcodes/generated/kafka_sync_database.html
- docs/layouts/shortcodes/generated/kafka_sync_table.html
- docs/layouts/shortcodes/generated/mysql_sync_database.html
- docs/layouts/shortcodes/generated/mysql_sync_table.html
- docs/layouts/shortcodes/generated/pulsar_sync_database.html
- docs/layouts/shortcodes/generated/pulsar_sync_table.html
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/TypeMapping.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlTypeUtils.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlCdcTypeMappingITCase.java
- paimon-flink/paimon-flink-cdc/src/test/resources/mysql/type_mapping_test_setup.sql
`MySqlCdcTypeMappingITCase#testBigintUnsignedToBigint`
New mapping option:
`bigint-unsigned-to-bigint`
> [cdc] Support type mapping option bigint-unsigned-to-bigint to map MySQL BIGINT UNSIGNED related types to BIGINT

- paimon-core/src/main/java/org/apache/paimon/table/sink/TableWriteImpl.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/kafka/KafkaLogSerializationSchema.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/kafka/KafkaLogSerializationTest.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/kafka/LogSystemITCase.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWriteImpl.java
Linked issue: close #2458 
[flink] supports writing to multiple partitions of kafka in unaware bucket mode.
- org.apache.paimon.flink.kafka.KafkaLogSerializationTest#testUnawareBucket
- org.apache.paimon.flink.kafka.LogSystemITCase#testAppendOnlyWithUnawareBucket
No
No
> [flink] supports writing to multiple partitions of kafka in unaware bucket mode.

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkTableSinkBase.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/UnawareBucketWriteSink.java
Disable compaction topology while insert unaware bucket table with bounded input stream.
> [flink] Disable compaction topology for unaware bucket mode insert when streaming with bounded input stream

- docs/content/maintenance/metrics.md
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/ReadOperator.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/operator/OperatorSourceTest.java
Linked issue: close #2466 
OperatorSourceTest#testReadOperatorMetricsRegisterAndUpdate
> [flink] Support source reader metrics when consumer-id is set

- docs/content/concepts/primary-key-table.md
- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-common/src/main/java/org/apache/paimon/types/RowKind.java
- paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
- paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/RowKindGenerator.java
- paimon-core/src/main/java/org/apache/paimon/table/sink/SequenceGenerator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/LocalMergeOperator.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
By default, the primary key table determines the row kind according to the input row. You can also define the 
`'rowkind.field'` to use a field to extract row kind.
The valid row kind string should be `'+I'`, `'-U'`, `'+U'` or `'-D'`.
> [core] Introduce 'rowkind.field' to define rowkind from data

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
Create database directly may throwing Permission exception from Hive Metastore.
> [flink][spark] Check Exists before create database to avoid Permission issue

- docs/content/engines/spark.md
> [spark] doc for spark merge into

- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionUtils.java
…btains messages and generates schema.
kafka adds sasl and other parameters to create consumers when kafka obtains messages and generates schema.
Caused by: org.apache.flink.kafka.shaded.org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata
> [Flink] kafka adds sasl and other parameters to create consumers when kafka obtains messages and generates schema.

- paimon-common/src/main/java/org/apache/paimon/predicate/CompoundPredicate.java
- paimon-core/src/main/java/org/apache/paimon/table/source/RawFile.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkInputPartition.java
- paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkReaderFactory.java
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBatch.scala
In `AdaptiveSparkPlanExec`  spark will use TrieMap to cache sparkplan, we need to add hashcode and equals for `PaimonBatch` for plan reuse
> [spark] Add hashcode for PaimonBatch

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCompactOperator.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/StoreCompactOperatorTest.java
Now, compact times depend on the split size. If one partition bucket has multiple split, then Compact Operator will trigger
multiple compactions. This is not correct, and may cause bugs in the future.
> [flink] Fix compaction multiple times in compact action.

- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/CdcActionCommonUtils.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/ComputedColumnUtils.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/MessageQueueSyncTableActionBase.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncTableActionBase.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/RecordParser.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableAction.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongodbSchemaUtils.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/strategy/Mongo4VersionStrategy.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/strategy/MongoVersionStrategy.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/schema/MySqlSchemaUtils.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/CdcActionITCaseBase.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionITCaseBase.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBActionITCaseBase.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableActionITCase.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongodbSchemaITCase.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionITCaseBase.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableActionITCase.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarActionITCaseBase.java
- paimon-flink/paimon-flink-cdc/src/test/resources/kafka/canal/table/computedcolumn/canal-data-2.txt
- paimon-flink/paimon-flink-cdc/src/test/resources/mongodb/table/computedcolumn/test-table-2.js
- paimon-flink/paimon-flink-cdc/src/test/resources/mysql/sync_table_setup.sql
We cannot retrieve schema with case sensitive because the computed columns rely on the original schema. 
I refactor the flow: 
1. case-sensitive is not involved in the validation, schema retrieving and computed columns building phases; 
2. building Paimon schema uses case-sensitive;
3. when parsing records, first we parse all field and evaluate all computed columns, and then we apply case-sensitive conversion.
`KafkaCanalSyncTableActionITCase#testComputedColumnWithCaseInsensitive`
`MongoDBSyncTableActionITCase#testComputedColumnWithCaseInsensitive`
`MySqlSyncTableActionITCase#testComputedColumnWithCaseInsensitive`
`MySqlSyncTableActionITCase#testSpecifyKeysWithCaseInsensitive`
> [cdc] Fix bug that computed columns work abnormally with case-insensitive

- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
- paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/HiveCatalogTest.java
Add `table_type` parameter to hive database to distinguish `paimon` and `iceberg` tables.
`HiveCatalogTest::testAddHiveTableParameters`
None.
None.
> [hive] add table_type parameter for hive db

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogTest.java
Linked issue: close #2499 
If `disable-create-table-in-default-db` is true, flink catalog should not create default database
1. Added test case in `FlinkCatalogTest`
no
no
> [flink] Do not create default database if ddl in it is disable

- docs/content/api/flink-api.md
Doc code is confusing, there is no need to create catalog in two different methods in two different ways.
> [docs] Fix docs confusing point about catalog create

- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/Committer.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCommitter.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreMultiCommitter.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java
Stop call end input if streaming checkpoint enabled. Because prepareCheckpointBarrier will handle the last checkpoint method.
Do as `CommitterOperator`
> [flink] Resolve bounded stream input finished in multiple checkpoint interval then cause commit failed

- paimon-common/src/main/java/org/apache/paimon/fs/hadoop/HadoopFileIO.java
- paimon-common/src/test/java/org/apache/paimon/fs/HadoopLocalFileIOBehaviorTest.java
- paimon-common/src/test/java/org/apache/paimon/fs/HdfsBehaviorTest.java
- paimon-filesystems/paimon-oss-impl/src/main/java/org/apache/paimon/oss/HadoopCompliantFileIO.java
- paimon-filesystems/paimon-s3-impl/src/main/java/org/apache/paimon/s3/HadoopCompliantFileIO.java
for example, hdfs and viewfs should have different FileSystem classes.
> [fs] HadoopFileIO should cache FileSystem by scheme and authority

- paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/SerializableHiveConf.java
- paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/SerializableHiveConfTest.java
As distributed open read API, `ReadBuilder` supports serialization to each task, and `Table` inside it also support serialization.
During tpcds test, we found that the `hiveConf`'s serialization in `Table/CatalogEnvironment/metastoreClientFactory` was very time-consuming. 
`CatalogEnvironment` is only used by table commit (driver side), in theory it does not need to be serialized, but flink relies it now.
Since there is currently no good way to separate it from the `Table`,  this PR proposes a lazy serialization solution, with it, the spark tpcds result increased by 15%+
> [core] Lazy deserialize hive conf in metastoreClientFactory

- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlActionUtils.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mysql/MySqlCdcTypeMappingITCase.java
If we don't handle jdbc driver, the connection might throw exceptions. For example, not handling `useSSL=false` will cause connection refused.
> [cdc] In schema building phase of mysql cdc, the connection should handle jdbc properties

- paimon-filesystems/paimon-hadoop-shaded/pom.xml
- paimon-filesystems/paimon-oss-impl/src/main/resources/META-INF/NOTICE
When rolling back oss sdk from jindo sdk to the old one through #2435 we missed to roll back the gson related dependency, and this PR aims to fix this up. More details refer to #2290 
Manually test and make sure the `META-INF/NOTICE` file correctly reflect the dependencies of the `paimon-filesystems/paimon-oss-impl` and `paimon-filesystems/paimon-hadoop-shaded` modules.
No API or storage format change involved.
No documentation required.
> [filesystem] Correct the gson dependency after rolling back from jindo sdk to oss sdk

- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/ScanHelper.scala
- paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/ScanHelperTest.scala
- paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonPushDownTest.scala
Linked issue: https://github.com/apache/incubator-paimon/issues/2404
> [spark] Dynamically adjust the parallelism of scan

- paimon-filesystems/paimon-hadoop-shaded/src/main/resources/META-INF/NOTICE
- paimon-filesystems/paimon-hadoop-shaded/src/main/resources/META-INF/licenses/LICENSE.jakarta
- paimon-filesystems/paimon-oss/pom.xml
- paimon-filesystems/paimon-s3/pom.xml
This PR fixes #2468 by the following:
* Add missing dependencies in the NOTICE file of paimon-hadoop-shaded module. (paimon-hadoop-shaded is merely an intermediate build artifact and it is not be deployed to maven central)
* Remove license related files from the nested META-INF directory of paimon-oss and paimon-s3 modules.
Tested by hand.
No.
No.
> [license] Fix license in paimon-hadoop-shaded, paimon-oss and paimon-s3 modules

- paimon-core/src/main/java/org/apache/paimon/tag/TagAutoCreation.java
- paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
- paimon-core/src/test/java/org/apache/paimon/tag/TagAutoCreationTest.java
Fix creation failure caused by savepoint tag
> [core] Fix creation failure caused by savepoint tag

- paimon-common/src/main/java/org/apache/paimon/predicate/CompoundPredicate.java
- paimon-common/src/main/java/org/apache/paimon/predicate/LeafFunction.java
- paimon-common/src/main/java/org/apache/paimon/predicate/LeafPredicate.java
- paimon-common/src/test/java/org/apache/paimon/predicate/PredicateTest.java
- paimon-spark/paimon-spark-3.1/src/main/scala/org/apache/paimon/spark/PaimonScan.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScanBuilder.scala
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala
Implementing `Predicate`'s `toString` can provide convenience for debugging and output
e.g.
```text
Equal(f0, 5)
GreaterThan(f0, 5)
And([Equal(f0, 3), Equal(f1, 5)])
IsNotNull(f0)
```
PredicateTest.testPredicateToString()
> [core] Add toString for Predicate

- paimon-core/src/main/java/org/apache/paimon/mergetree/LookupUtils.java
- paimon-core/src/test/java/org/apache/paimon/mergetree/LookupLevelsTest.java
> [Bug] Fix the IndexOutOfBoundsException when  lookup empty sortedRun

- paimon-common/src/main/java/org/apache/paimon/utils/DateTimeUtils.java
- paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
- paimon-core/src/main/java/org/apache/paimon/table/FileStoreTable.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/AbstractFlinkTableFactory.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java
`BatchFileStoreITCase#testScanFromOldSchema`
`testScanFromOldSchema#testScanFromOldSchema`
> [flink] Fix that schema validation fails when using 'scan.x' options to do time travel on schema changed tables

- paimon-common/src/main/java/org/apache/paimon/utils/TypeUtils.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/RecordParser.java
- paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaDebeziumSyncTableActionITCase.java
- paimon-flink/paimon-flink-cdc/src/test/resources/kafka/debezium/table/nestedtype/debezium-data-1.txt
records：
{
"before": {},
"after": {
"_id": 1004,
"first_name": "Anne Marie",
"last_name": "Kretchmar",
"email": "annek@noanswer.org",
"bool_field": true,
"row":{"row_key":"value"}
},
"source": {
"version": "1.3.1.Final",
"connector": "mysql",
"name": "mysql-server-1",
"ts_sec": 1465581,
"snapshot": false,
"db": "",
"table": "paimon_cdc_test",
"server_id": 223344,
"gtid": null,
"file": "mysql-bin.000003",
"pos": 805,
"row": 0,
"thread": 7,
"query": "DELETE FROM customers WHERE id=1004"
},
"op": "c",
"ts_ms": 1465581902461
}
2023-12-18 18:21:26
java.io.IOException: Failed to deserialize consumer record due to
at org.apache.flink.connector.kafka.source.reader.KafkaRecordEmitter.emitRecord(KafkaRecordEmitter.java:56)
at org.apache.flink.connector.kafka.source.reader.KafkaRecordEmitter.emitReco …
> [flink] Fixed deserialization failure when kafka cdc records contain nested structures

- docs/content/concepts/primary-key-table.md
- docs/layouts/shortcodes/generated/core_configuration.html
- paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
- paimon-common/src/main/java/org/apache/paimon/utils/MathUtils.java
- paimon-core/src/main/java/org/apache/paimon/index/BucketAssigner.java
- paimon-core/src/main/java/org/apache/paimon/index/HashBucketAssigner.java
- paimon-core/src/test/java/org/apache/paimon/index/BucketAssignerTest.java
- paimon-core/src/test/java/org/apache/paimon/index/HashBucketAssignerTest.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcAssignerChannelComputer.java
- paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcDynamicBucketSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/DynamicBucketCompactSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/DynamicBucketSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/HashBucketAssignerOperator.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowAssignerChannelComputer.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowDynamicBucketSink.java
- paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalDynamicBucketSink.java
- paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/DynamicBucketTableITCase.java
- paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/WriteIntoPaimonTable.scala
Assuming we need to write multiple partitions simultaneously:
- At present, setting the dynamic bucket assignment parallelism option too large can result in a large number of buckets.
- Setting it too small will pose a risk to memory and make it prone to OOM
This PR aims to decouple initialized buckets and total parallelism of assigners to avoid the aforementioned issues
> [core] Optimize HashBucketAssigner to more parallilism with less initialized bucket
