docs/content/maintenance/metrics.md
paimon-core/src/main/java/org/apache/paimon/compact/CompactTask.java
paimon-core/src/main/java/org/apache/paimon/operation/metrics/CommitMetrics.java
paimon-core/src/main/java/org/apache/paimon/operation/metrics/CommitStats.java
paimon-core/src/main/java/org/apache/paimon/operation/metrics/CompactionMetrics.java

Some bucket level IO size metrics are removed in https://github.com/apache/paimon/pull/2930/files 
This PR add the avg/max/total compaction input & output io size metrics back.

[core] Add avg/max/total compaction io size metric

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-codegen/src/main/java/org/apache/paimon/codegen/CodeGeneratorImpl.java
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-common/src/main/java/org/apache/paimon/codegen/CodeGenerator.java
paimon-core/src/main/java/org/apache/paimon/codegen/CodeGenUtils.java
paimon-core/src/main/java/org/apache/paimon/crosspartition/GlobalIndexAssigner.java
paimon-core/src/main/java/org/apache/paimon/lookup/RocksDBState.java
paimon-core/src/main/java/org/apache/paimon/mergetree/SortBufferWriteBuffer.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/operation/MergeFileSplitRead.java
paimon-core/src/main/java/org/apache/paimon/sort/BinaryExternalSortBuffer.java
paimon-core/src/main/java/org/apache/paimon/utils/KeyComparatorSupplier.java
paimon-core/src/main/java/org/apache/paimon/utils/UserDefinedSeqComparator.java
paimon-core/src/test/java/org/apache/paimon/codegen/CodeGenUtilsTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FullCacheLookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/SortOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/SortUtils.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sorter/SortOperatorTest.java

In production such as compute ealist login time zipper table，user want to get the small record to query when set sequence.field, currently paimon can only get the largest record, user need (Long.max - timestamp) which is not very convenient. This pr is aimed to support user set sequence.field order to get largest or small record with a option sequence.field.sort.is.ascending， default true keep the largest one，with false keep the small one.
eg like ut case.

[core] Support sequence.field sort order for pk table

---

paimon-common/src/main/java/org/apache/paimon/lookup/hash/HashLookupStoreReader.java
paimon-common/src/main/java/org/apache/paimon/lookup/sort/SortLookupStoreFactory.java
paimon-common/src/main/java/org/apache/paimon/lookup/sort/SortLookupStoreReader.java
paimon-common/src/main/java/org/apache/paimon/utils/FileBasedBloomFilter.java
paimon-common/src/test/java/org/apache/paimon/utils/FileBasedBloomFilterTest.java

The BloomFilter in `SortLookupStoreReader` is not managed by the CacheManager, which will lead to the excessive buffer usage. This PR do these two things:
- Manage the BloomFilter's buffer with the CacheManager
- Release the BloomFilter's buffer when the Reader is closed.

[core] Manage the bloomfilter buffer in cache manager

---

docs/content/flink/procedures.md
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/CompactProcedure.java
paimon-flink/paimon-flink-1.18/src/test/java/org/apache/paimon/flink/procedure/ProcedurePositionalArgumentsITCase.java

Support :  `CALL [catalog.]sys.compact('table', 'order_strategy', 'order_by') `

[flink] Procedure sorting compact a table without partitions filter.

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/test/java/org/apache/paimon/table/SchemaEvolutionTest.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkSchemaEvolutionITCase.java

Support renaming primary keys and bucket keys that are not partition keys.
Added schema evolution tests and Spark e2e tests
Not affected

[core]: support rename primary key columns and bucket key columns

---

paimon-core/src/main/java/org/apache/paimon/io/RecordLevelExpire.java

Using the same name for two variables can easily lead to confusion, change them.

[core] Change variable name in RecordLevelExpire

---

paimon-core/src/main/java/org/apache/paimon/table/Table.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CreateAndDeleteTagProcedureTest.scala

If there are spaces between multiple deleted tags, will throw tag not found exception.

[core] Space allowed between multiple deleted tags

---

docs/content/flink/procedures.md
docs/content/spark/procedures.md
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/DelegatedFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/FormatTable.java
paimon-core/src/main/java/org/apache/paimon/table/ReadonlyTable.java
paimon-core/src/main/java/org/apache/paimon/table/Table.java
paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/CreateOrReplaceTagBaseProcedure.java
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/CreateTagProcedure.java
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/ReplaceTagProcedure.java
paimon-flink/paimon-flink-1.18/src/test/java/org/apache/paimon/flink/procedure/ProcedurePositionalArgumentsITCase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CreateOrReplaceTagActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ReplaceTagAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ReplaceTagActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CreateOrReplaceTagBaseProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CreateTagProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ReplaceTagProcedure.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ReplaceTagActionTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/ProcedureTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/ReplaceTagProcedureITCase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CreateOrReplaceTagBaseProcedure.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ReplaceTagProcedure.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ReplaceTagTagProcedure.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/CreateAndDeleteTagProcedureTest.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/ReplaceTagProcedureTest.scala

In default way, the create_tag procedure for an existing tag means to update it or fail,  it's semantic is not very accurate, replace it with repalce_tag procedure.
before semantic
```sql
CALL paimon.sys.create_tag(table => 'test.T', tag => 'test_tag', snapshot => 1)")
-- success. update it
CALL paimon.sys.create_tag(table => 'test.T', tag => 'test_tag', snapshot => 1, time_retained => '1 d')")
-- failed
CALL paimon.sys.create_tag(table => 'test.T', tag => 'test_tag', snapshot => 2)")
```
after semantic
```sql
CALL paimon.sys.create_tag(table => 'test.T', tag => 'test_tag', snapshot => 1)")
-- failed
CALL paimon.sys.create_tag(table => 'test.T', tag => 'test_tag', snapshot => 1, time_retained => '1 d')")
-- success. use replace to update
CALL paimon.sys.replace_tag(table => 'test.T', tag …
```

[spark] Replace create existing tag semantic with replace_tag

---

docs/content/flink/procedures.md
docs/content/spark/procedures.md
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/RollbackToTimestampProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RollbackToTimestampAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RollbackToTimestampActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RollbackToTimestampProcedure.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RollbackToActionITCase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RollbackToTimestampProcedure.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/RollbackProcedureTest.scala

Currently Rollback cannot rollback according timestamp which can make user more easy to rollback, as https://github.com/apache/paimon/pull/4333 suggest introduce RollbackToTimestamp to support for procedure and action.

[core] Introduce RollbackToTimestamp Procedure and Action

---

paimon-flink/paimon-flink-1.15/src/main/java/org/apache/flink/api/connector/source/SupportsHandleExecutionAttemptSourceEvent.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/StaticFileStoreSplitEnumerator.java

In my company's production job, when batch read a paimon table, I receive the exception.
After read flink and paimon code, I know it means paimon use custom SourceEvent ReaderConsumeProgressEvent.
I have come up with two solutions:
1、Implement the interface SupportsHandleExecutionAttemptSourceEvent according to the exception suggestion;
2、Delete ReaderConsumeProgressEvent in StaticFileStoreSplitEnumerator.
Due to the possibility of new other SourceEvent being added in the future, so I chose the solutions-1.

[Flink] Support speculative execution when batch read paimon table.

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java
paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalog.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java

If some table options are set incorrectly, such as `ignore-delete = max`, it may cause an exception when dropping the table. This is because it tries to getTable before dropping.
The implementation of getting table in different catalog is different too. For example:
`CachingCatalog` will `putTableCache` and this may call `PrimaryKeyFileStoreTable#store()` method, which will create `MergeFunction` through some table options. When trying to read these options, exception occurs, causing getTable failed and leads to dropping table failed.
So, When creating table, we will try to get table store for checking if the relevant table options are set correctly. If not, the table created will be deleted and throw an exception.
CatalogTestBase#testCreateTable

[core] try to get table store for checking table options when creating table

---

docs/content/concepts/spec/manifest.md

When I read source code of `DataFileMeta`, I find `fileSource` and `valueStatsCols` properties didn't update to document, so commit this pr.
Linked issue: `valueStatsCols` in close #4322 and `fileSource` in close #3178
No
No
Update `docs/content/concepts/spec/manifest.md`.

[doc]Update fileSource and valueStatsCols in manifest.md

---

docs/layouts/shortcodes/generated/flink_connector_configuration.html
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/DynamicBucketSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkSourceBuilder.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkJobRecoveryITCase.java

Linked issue: close #4424 
[flink] support setting uid suffix for source/sink to improve state compatibility when jobGraph changes.
1. `org.apache.paimon.flink.FlinkJobRecoveryITCase`
No

 [flink] support setting uid suffix for source/sink to improve state compatibility when jobGraph changes.

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java
paimon-core/src/main/java/org/apache/paimon/io/DataFilePathFactory.java
paimon-core/src/main/java/org/apache/paimon/utils/FileStorePathFactory.java
paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java
paimon-core/src/test/java/org/apache/paimon/format/FileFormatSuffixTest.java
paimon-core/src/test/java/org/apache/paimon/io/DataFilePathFactoryTest.java
paimon-core/src/test/java/org/apache/paimon/io/KeyValueFileReadWriteTest.java
paimon-core/src/test/java/org/apache/paimon/io/RollingFileWriterTest.java
paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileMetaTestBase.java
paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileTest.java
paimon-core/src/test/java/org/apache/paimon/manifest/ManifestListTest.java
paimon-core/src/test/java/org/apache/paimon/utils/FileStorePathFactoryTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/TestChangelogDataReadWrite.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkFileIndexITCase.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkWriteITCase.java

Default, the file name written by paimon only has the file format, it can also include the file compression like spark.

[core] Add file compression type in file names

---

docs/layouts/shortcodes/generated/catalog_configuration.html
paimon-common/src/main/java/org/apache/paimon/options/CatalogOptions.java
paimon-core/src/main/java/org/apache/paimon/catalog/CachingCatalog.java
paimon-core/src/test/java/org/apache/paimon/catalog/CachingCatalogTest.java
paimon-core/src/test/java/org/apache/paimon/catalog/TestableCachingCatalog.java

Linked issue: close #4205
testPartitionCache
CachingCatalog.getPartitions
CachingCatalog.refreshPartitions
Allow cache and refresh partitions for CachingCatalog.

[core] Allow cache and refresh partitions for CachingCatalog

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecord.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcRecord.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/CdcMultiplexRecordChannelComputerTest.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordChannelComputerTest.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordKeyAndBucketExtractorTest.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperatorTest.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreWriteOperatorTest.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/TestTable.java

Currently, the field named `fields` in `CdcRecord` look like `schema` info, but actually represent `data` info, which is ambiguous. And there is also some ambiguity with `RichCdcRecord` field naming. So I rename the the field named `fields` in `CdcRecord` to `data`.
Existing
No
No

[cdc] Fix ambiguous naming in CdcRecord

---

paimon-core/src/main/java/org/apache/paimon/table/system/FilesTable.java
paimon-core/src/test/java/org/apache/paimon/table/system/FilesTableTest.java

This could let user know where is the file come from: Append or Compact.

[core] Show fileSource in the FilesTable

---

paimon-core/src/main/java/org/apache/paimon/utils/BranchManager.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BranchSqlITCase.java

Linked issue: close #4407 
[core] fix the issue where the historical schemaId could not be found when reading the branch table.
- `org.apache.paimon.flink.BranchSqlITCase#testReadBranchTableWithMultiSchemaIds`
No
No

[core] fix the issue where the historical schemaId could not be found when reading the branch table.

---

docs/content/flink/quick-start.md
docs/content/spark/auxiliary.md
paimon-common/src/main/java/org/apache/paimon/options/OptionsUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/AbstractFlinkTableFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/AbstractFlinkTableFactoryTest.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkSource.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/util/OptionUtils.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonOptionTest.scala

Linked issue: close #4371 
In some cases, users may want to use spark time travel by setting properties like set `spark.paimon.scan.tag-name=tag_3`. However, this property will take effect globally if the spark job read multiple tables at the same time.
It would be better if we can support table options via sql conf for Spark Engine. So user can specify different time travel options for different table, like this:
- PaimonOptionsTest.scala

[spark] Support table options via SQL conf for Spark Engine

---

docs/layouts/shortcodes/generated/catalog_configuration.html
paimon-common/src/main/java/org/apache/paimon/options/CatalogOptions.java

The default value of database/table/partition cache for a catalog is 1 minute, leading to a low hit rate. We would like to increase it to 10 minutes.
no.
no.
added.

[core] Increase the default value of cache.expiration-interval to 10m

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/io/RecordLevelExpire.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireWithTimestampBaseTest.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireWithTimestampLTZTest.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireWithTimestampTest.java

Record level expiration supports timestamp type and timestamp_ltz type.

[core] Support timestamp field type in record level expire

---

paimon-core/src/main/java/org/apache/paimon/catalog/CachingCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/test/java/org/apache/paimon/catalog/CachingCatalogTest.java

Among OLAP scenario, we need an interface to refresh cached partition info to assure that if it is necessary to renew a materialized view's partition.
added.
Catalog.refreshPartitions
no

[core] Introduce refreshPartitions interface to CachingCatalog

---

docs/layouts/shortcodes/generated/flink_connector_configuration.html
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/FileStoreLookupFunctionTest.java

In the specified periods, lookup table cache refreshing is forbidden. This is aimed at avoiding server busy time.

[flink] Lookup join supports time periods black list

---

docs/layouts/shortcodes/generated/catalog_configuration.html
docs/layouts/shortcodes/generated/core_configuration.html
docs/layouts/shortcodes/generated/flink_connector_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexPredicate.java
paimon-core/src/main/java/org/apache/paimon/io/RecordLevelExpire.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireWithMillisecondTest.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireWithTimestampBaseTest.java

The record level expired time field type is automatically recognized.
The user is not required to enter the field type `record-level.time-field-type`, and the input may be incorrect.

[core] The record level expired time field type is automatically recognized.

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/CachingCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Database.java
paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java
paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalog.java
paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedCatalog.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/MigrateFileProcedure.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncTableActionBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/log/LogStoreRegister.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/MigrateFileProcedure.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/migrate/HiveMigrator.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/MigrateFileProcedure.java

Delete follow methods in Catalog because of useless, We recommend using methods such as `getTable` directly to avoid errors in implementation.
```
/**
* Get lock factory from catalog. Lock is used to support multiple concurrent writes on the
* object store.
*/
Optional<CatalogLockFactory> lockFactory();
/** Get lock context for lock factory to create a lock. */
default Optional<CatalogLockContext> lockContext() {
return Optional.empty();
}
/** Get metastore client factory for the table specified by {@code identifier}. */
default Optional<MetastoreClient.Factory> metastoreClientFactory(Identifier identifier)
throws TableNotExistException {
return Optional.empty();
}
```
Delete follow methods in Catalog because of repetitive:
```
/**
* Check if a database exists in this catalog.
*
* @param …
```

[core] Delete useless methods in Catalog

---

paimon-core/src/main/java/org/apache/paimon/utils/NextSnapshotFetcher.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PrimaryKeyFileStoreTableITCase.java

A table which is read in streaming read, will not throw exception even if the table is recreated currently. For example, the expected snapshot id is 10001, but the latest snapshot of the recreated table might be null or much less than 10001.
This is because when try to get the next snapshot, if the next snapshot is not exists in filesystem and its id is greater than earliest snapshot id, it will be treat as the next snapshot is still in generating progress.
This feature adds a check in `NextSnapshotFetcher#getNextSnapshot`. If next expected snapshot id is greater than the latest snapshot id plus one, it will throw an exception.
`PrimaryKeyFileStoreTableITCase#testRecreateTableWithException`

[core] throw exception if table is recreated when it still being read

---

docs/content/engines/doris.md
docs/content/engines/trino.md
docs/content/flink/action-jars.md
docs/content/flink/clone-tables.md
docs/content/flink/expire-partition.md
docs/content/flink/savepoint.md

Linked issue: close #4449
Inspired by issue 4449 and `CloneActionITCase`, I update `clone-tables.md` style. Does anyone have any better suggestions?
**no**
**no**
Update `docs/content/flink/clone-tables.md` and `docs/content/flink/expire-partition.md`.

[doc] Update doc style

---

docs/layouts/shortcodes/generated/catalog_configuration.html
docs/layouts/shortcodes/generated/hive_catalog_configuration.html
paimon-common/src/main/java/org/apache/paimon/options/CatalogOptions.java
paimon-core/src/main/java/org/apache/paimon/table/FormatTableOptions.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkGenericCatalogFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FormatCatalogTable.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalogOptions.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveTableUtils.java
paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/HiveCatalogTest.java
paimon-hive/paimon-hive-connector-2.3/src/test/java/org/apache/paimon/hive/Hive23CatalogITCase.java
paimon-hive/paimon-hive-connector-3.1/src/test/java/org/apache/paimon/hive/Hive31CatalogITCase.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogFormatTableITCaseBase.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkCatalogWithHiveTest.java

By default, we should enable PaimonCatalog to have default access to Hive tables

[hive] Enable Format Table by default

---

paimon-core/src/main/java/org/apache/paimon/metastore/AddPartitionCommitCallback.java
paimon-core/src/main/java/org/apache/paimon/metastore/MetastoreClient.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveMetastoreClient.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLTestBase.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTestBase.scala

hiveClient support `client.add_partitions` to add partitions at once, we can use it in AddPartitionCommitCallback
this speeds up the load table a lot when have many partitions to sync.

[core] Add batch add partitions in MetastoreClient

---

paimon-common/src/test/java/org/apache/paimon/format/FormatReadWriteTest.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ColumnConfigParser.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/writer/RowDataParquetBuilder.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetFormatReadWriteTest.java

This pr is meant to support to enable parquet bloomfilter.
```
// Enable the bloom filter for all columns
conf.set("parquet.bloom.filter.enabled", true);
// Disable the bloom filter for the column 'column.path'
conf.set("parquet.bloom.filter.enabled#column.path", false);
// The bloom filter will be enabled for all columns except 'column.path'
```

[parquet] Support to enable parquet bloomfilter

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/HmsReporter.java

This is due to the `List<DeletionFile>` may contain `null`. I think the hms metadata should only contains the datafile. So, 
remove the DeletionFile related code.

[Bug] Fix the NPE when report the statistic with DeletionFile

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaChange.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaEvolutionUtil.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-core/src/test/java/org/apache/paimon/schema/SchemaManagerTest.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadITCase.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkSchemaEvolutionITCase.java

Spark SQL supports adding and dropping nested columns, but Paimon currently does not support it. This PR adds support for adding and dropping nested columns.
This feature does not need a document.

[core][spark] Support adding and dropping nested columns in Spark

---

paimon-core/src/main/java/org/apache/paimon/table/source/DataTableBatchScan.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonPushDownTest.scala

Exception stack ：
```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.util.TimSort.mergeLo(TimSort.java:777)
at java.util.TimSort.mergeAt(TimSort.java:514)
at java.util.TimSort.mergeCollapse(TimSort.java:441)
at java.util.TimSort.sort(TimSort.java:245)
at java.util.Arrays.sort(Arrays.java:1512)
at java.util.ArrayList.sort(ArrayList.java:1462)
at org.apache.paimon.table.source.DataTableBatchScan.applyPushDownLimit(DataTableBatchScan.java:105)
at org.apache.paimon.table.source.DataTableBatchScan.plan(DataTableBatchScan.java:79)
at org.apache.paimon.spark.PaimonBaseScan.getOriginSplits(PaimonBaseScan.scala:73)
at org.apache.paimon.spark.PaimonBaseScan.lazyInputPartitions(PaimonBaseScan.scala:82)
at …
```

[core] Fix Limit push down sort splits violates its general contract.

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaChange.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-core/src/test/java/org/apache/paimon/schema/SchemaManagerTest.java
paimon-core/src/test/java/org/apache/paimon/table/SchemaEvolutionTest.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkSchemaEvolutionITCase.java

Currently Paimon only supports renaming not nested columns. This PR supports renaming nested columns in Paimon, and also add support to Spark.
Document will be added in a dedicated PR.

[core][spark] Support renaming nested columns in Spark

---

paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/HiveCatalogTest.java

Linked issue: close #4366
To test if hive client pool deadlock problem has been solved by #4468.
This test case will fail on release-0.9, however passes in master branch.
org.apache.paimon.hive.HiveCatalogTest#testListTablesLock
no.
no.

[test] Add ut case to check hive clients pool deadlock

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaChange.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-core/src/test/java/org/apache/paimon/schema/SchemaManagerTest.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunctionBase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkSchemaEvolutionITCase.java

Currently Paimon only supports updating not nested column types. This PR supports updating nested column types, and also adds support to Spark.

[core][spark] Support updating nested column types in Spark

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-benchmark/paimon-cluster-benchmark/src/main/java/org/apache/paimon/benchmark/metric/cpu/SysInfoLinux.java
paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/cache/CacheManagerBenchmark.java
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-common/src/main/java/org/apache/paimon/io/cache/CacheKey.java
paimon-common/src/main/java/org/apache/paimon/io/cache/CacheManager.java
paimon-common/src/main/java/org/apache/paimon/lookup/sort/BlockCache.java
paimon-common/src/main/java/org/apache/paimon/lookup/sort/SortLookupStoreReader.java
paimon-common/src/main/java/org/apache/paimon/utils/FileBasedBloomFilter.java
paimon-common/src/test/java/org/apache/paimon/io/cache/CacheManagerTest.java
paimon-common/src/test/java/org/apache/paimon/io/cache/FileBasedRandomInputViewTest.java
paimon-common/src/test/java/org/apache/paimon/lookup/sort/SortLookupStoreFactoryTest.java
paimon-common/src/test/java/org/apache/paimon/utils/FileBasedBloomFilterTest.java
paimon-core/src/main/java/org/apache/paimon/operation/MemoryFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/table/query/LocalTableQuery.java

[core] Separate index cache and data cache

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java

Try to avoid create Paimon table in HiveCatalog.listTables, this can accelerate list tables and avoid potential problems (just show tables here, we don't need to access tables).

[hive] Make HiveCatalog.listTables Lighter weight

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaChange.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/test/java/org/apache/paimon/schema/SchemaManagerTest.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunctionBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java

Unlike Spark, Flink does not support directly updating a nested column. So we support updating a whole row type to another row type in Flink to implement this feature.

[flink] Support updating row type to another row type in Flink

---

paimon-core/src/main/java/org/apache/paimon/table/system/FilesTable.java
paimon-core/src/test/java/org/apache/paimon/table/system/FilesTableTest.java

Now search FilesTable System table, the file_path column only shows file_name, not file_path.

[core] small fix of FilesTable system table

---

docs/content/primary-key-table/compaction.md

In https://github.com/apache/paimon/pull/4458 removed the config `record-level.time-field-type`, update doc.

[doc]  Remove unused config in record-level expire

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java

When we use flink write data and spark compact, we find expiring only 10 snapshots each time in compact, and the snapshot backlog is quite serious. Increase the default value to 50 to avoid this situation.

[core] Adjust default value of 'snapshot.expire.limit'

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/CatalogEnvironment.java
paimon-core/src/main/java/org/apache/paimon/table/DelegatedFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/Table.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/HiveCatalogTest.java

Add Table.uuid method for table uniq id, this can be used like some RBAC support.
- for filesystem catalog, uuid is db + tableName + schema-createTime.
- for hive catalog, uuid is db + tableName + createTime.

[core] Add Table.uuid method

---

paimon-common/src/main/java/org/apache/paimon/fileindex/bitmap/ApplyBitmapIndexFileRecordIterator.java
paimon-common/src/main/java/org/apache/paimon/fileindex/bitmap/ApplyBitmapIndexRecordReader.java
paimon-common/src/main/java/org/apache/paimon/utils/RoaringBitmap32.java
paimon-core/src/main/java/org/apache/paimon/io/FileIndexEvaluator.java
paimon-core/src/main/java/org/apache/paimon/operation/RawFileSplitRead.java
paimon-core/src/test/java/org/apache/paimon/table/AppendOnlyFileStoreTableTest.java
paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java

Introduction of bitmap index record reader to filter data in advance with bitmap index result.
org.apache.paimon.table.AppendOnlyFileStoreTableTest#testBSIAndBitmapIndexInMemory
org.apache.paimon.table.AppendOnlyFileStoreTableTest#testBSIAndBitmapIndexInDisk
org.apache.paimon.table.PrimaryKeyFileStoreTableTest#testDeletionVectorsWithFileIndexInMeta
org.apache.paimon.table.PrimaryKeyFileStoreTableTest#testDeletionVectorsWithBitmapFileIndexInFile
No.
No.

[core] Introduce bitmap index record reader

---

paimon-common/src/main/java/org/apache/paimon/fileindex/bitmap/ApplyBitmapIndexRecordReader.java
paimon-common/src/main/java/org/apache/paimon/reader/EmptyFileRecordReader.java
paimon-common/src/main/java/org/apache/paimon/reader/FileRecordIterator.java
paimon-common/src/main/java/org/apache/paimon/reader/FileRecordReader.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/ApplyDeletionVectorReader.java
paimon-core/src/main/java/org/apache/paimon/io/DataFileRecordReader.java
paimon-core/src/main/java/org/apache/paimon/io/KeyValueDataFileRecordReader.java
paimon-core/src/main/java/org/apache/paimon/io/KeyValueFileReaderFactory.java
paimon-core/src/main/java/org/apache/paimon/operation/RawFileSplitRead.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/changelog/format/CompactedChangelogFormatReaderFactory.java
paimon-format/src/main/java/org/apache/paimon/format/avro/AvroBulkFormat.java
paimon-format/src/main/java/org/apache/paimon/format/orc/OrcReaderFactory.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetReaderFactory.java

In `ApplyBitmapIndexRecordReader` and `ApplyBitmapIndexRecordReader`, they will check the type of iterator which should be `FileRecordIterator`, it is always `FileRecordIterator`, and we should garrantee it by interface.
So we let FormatReaderFactory return FileRecordReader, and all related readers should be `FileRecordReader`s.

[core] Make FormatReaderFactory return FileRecordReader to reduce cast

---

paimon-common/src/main/java/org/apache/paimon/table/SpecialFields.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetReaderFactory.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetSchemaConverter.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetReadWriteTest.java

In #4362 we write field ids into parquet files. However that PR fails to add id for nested array/map type (for example `ARRAY(MAP(INT, ARRAY(INT)))` type. This PR fixes the bug.
Unit tests.
Field id of array element, map keys and values are changed.
No document is needed.

[parquet] Fix nested array/map has no id in parquet files

---

paimon-common/src/main/java/org/apache/paimon/casting/NumericToBooleanCastRule.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java

[common] Fix overflow problem of NumericToBooleanCastRule

---

paimon-core/src/main/java/org/apache/paimon/manifest/ManifestCommittable.java
paimon-core/src/test/java/org/apache/paimon/TestFileStore.java
paimon-core/src/test/java/org/apache/paimon/manifest/ManifestCommittableSerializerTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCommitter.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreMultiCommitter.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/WrappedManifestCommittableSerializerTest.java

Linked issue: close #4515 
[flink] support multiple writers writing to the same partition when using kafka as logSystem in unaware bucket mode.

[flink] support multiple writers writing to the same partition when using kafka as logSystem in unaware bucket mode.

---

paimon-common/src/main/java/org/apache/paimon/casting/CastElementGetter.java
paimon-common/src/main/java/org/apache/paimon/casting/CastedArray.java
paimon-common/src/main/java/org/apache/paimon/casting/CastedMap.java
paimon-common/src/main/java/org/apache/paimon/casting/CastedRow.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaEvolutionUtil.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/test/java/org/apache/paimon/schema/SchemaManagerTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java

This PR supports updating row type nested in array/map in Flink. For example, we can update a field of type `ARRAY<MAP<INT, ROW<f1 INT, f2 DOUBLE>>>` to type `ARRAY<MAP<INT, ROW<f3 STRING, f1 INT>>>` with the `ALTER TABLE` SQL.

[flink] Support updating row type nested in array/map in Flink

---

docs/content/maintenance/system-tables.md
paimon-common/src/main/java/org/apache/paimon/reader/PackChangelogReader.java
paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/BinlogTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/SystemTableLoader.java
paimon-flink/paimon-flink-common/pom.xml
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SystemTableITCase.java

[core] Introduce binlog system table to pack the UB and UA

---

paimon-core/src/main/java/org/apache/paimon/append/UnawareAppendTableCompactionCoordinator.java
paimon-core/src/test/java/org/apache/paimon/append/UnawareAppendTableCompactionCoordinatorTest.java

[core] Fix that batch unaware bucket compact cannot stop when there is no snapshot

---

paimon-core/src/main/java/org/apache/paimon/io/DataFileMeta.java
paimon-core/src/main/java/org/apache/paimon/manifest/ManifestEntry.java
paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/AbstractDataTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/InnerTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/ReadBuilder.java
paimon-core/src/main/java/org/apache/paimon/table/source/ReadBuilderImpl.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReader.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
paimon-core/src/test/java/org/apache/paimon/operation/KeyValueFileStoreScanTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileStoreSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkTableSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/StaticFileStoreSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/MonitorFunction.java

In my company's production environment, when use Flink session cluster for OLAP scan Paimon, we found the JobManager's memory is always heavy.
So, we will optimize this by two ways:
(1) Delete stats in DataSplit.
(2) When dataSkipping, cut unused stats in ManifestEntry.
This pr is for (1)

[core] Support delete stats in result of scan plan.

---

paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/RewritePaimonViewCommands.scala
paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/sql/PaimonViewTest.scala
paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/RewritePaimonViewCommands.scala
paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/PaimonViewTest.scala
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/PaimonViewTest.scala
paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/sql/PaimonViewTest.scala
paimon-spark/paimon-spark-4.0/src/test/scala/org/apache/paimon/spark/sql/PaimonViewTest.scala
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkTypeUtils.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/catalog/SupportView.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/utils/CatalogUtils.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonViewResolver.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/plans/logical/PaimonViewCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/execution/PaimonStrategy.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/execution/PaimonViewExec.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/extensions/PaimonSparkSessionExtensions.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/PaimonSparkSqlExtensionsParser.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/PaimonSqlExtensionsAstBuilder.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/RewritePaimonViewCommands.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTestBase.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/PaimonViewTestBase.scala

To #4496, implement the following basic view usages for SparkCatalog:
```sql
CREATE VIEW v xxx;
CREATE OR REPLACE VIEW v xxx; -- non-atomic, just drop then create
SHOW VIEWS;
SHOW VIEWS LIKE '';
SELECT FROM view;
```

[spark] Introduce View Support to SparkCatalog

---

paimon-format/src/main/java/org/apache/paimon/format/orc/OrcFileFormat.java
paimon-format/src/main/java/org/apache/paimon/format/orc/OrcReaderFactory.java
paimon-format/src/main/java/org/apache/paimon/format/orc/OrcTypeUtil.java
paimon-format/src/main/java/org/apache/paimon/format/orc/reader/OrcSplitReaderUtil.java
paimon-format/src/main/java/org/apache/paimon/format/orc/writer/RowDataVectorizer.java
paimon-format/src/main/java/org/apache/paimon/format/orc/writer/Vectorizer.java
paimon-format/src/test/java/org/apache/paimon/format/orc/OrcSplitReaderUtilTest.java
paimon-format/src/test/java/org/apache/paimon/format/orc/OrcTypeUtilTest.java
paimon-format/src/test/java/org/apache/paimon/format/orc/OrcWriterFactoryTest.java

[orc] Add type id to orc files

---

paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreScan.java
paimon-core/src/main/java/org/apache/paimon/operation/SnapshotDeletion.java
paimon-core/src/test/java/org/apache/paimon/TestFileStore.java
paimon-core/src/test/java/org/apache/paimon/operation/ExpireSnapshotsTest.java
paimon-core/src/test/java/org/apache/paimon/operation/KeyValueFileStoreScanTest.java
paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java

- FileStoreScan.withManifestList is only used by test code, we should remove it.
- Fix unstable test ExpireSnapshotsTest.testChangelogOutLivedSnapshot

[core] Remove FileStoreScan.withManifestList and fix unstable test

---

paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalogOptions.java
paimon-core/src/test/java/org/apache/paimon/catalog/FileSystemCatalogTest.java

FileSystemCatalog now use 'case-sensitive' to control case-sensitive, which is not compatible with other catalog. Make FileSystemCatalog can control case-sensitive with 'allow-upper-case' too.
`FileSystemCatalogTest#testCreateTableAllowUpperCase`

[core] all catalogs use 'allow-upper-case' to control case-sensitive

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/schema/Schema.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/PickFilesForCloneOperator.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/HiveCatalogTest.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkTable.scala
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkReadITCase.java
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/PaimonHiveTestBase.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLTestBase.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTestBase.scala

~~This relocates the 'path' property in the table options to 'location' for better presentation.~~
- Adapt 'path' to Spark's 'location' in table props ( the 'path' is still preserved in table props)
- Support the customization of the table location when creating a table(only allowed for creating external table using hive catalog)
Spark uses the reserved property `location` to indicate the location of the table, and in the output of `DESC EXTENDED`, the location information will be displayed under the "# Detailed Table Information" section for better visibility.
```text
+----------------------------+-----------------------------------------------------------------------------------------------------+-------+
|col_name                    |data_type …
```

[hive][spark] Support create table with specified location using hive catalog

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/aliyun/AliyunDataFormat.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/aliyun/AliyunDataFormatFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/aliyun/AliyunFieldParser.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/aliyun/AliyunRecordParser.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/watermark/MessageQueueCdcTimestampExtractor.java
paimon-flink/paimon-flink-cdc/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/format/aliyun/AliyunJsonRecordParserTest.java
paimon-flink/paimon-flink-cdc/src/test/resources/kafka/aliyun/table/event/event-delete.txt
paimon-flink/paimon-flink-cdc/src/test/resources/kafka/aliyun/table/event/event-insert.txt
paimon-flink/paimon-flink-cdc/src/test/resources/kafka/aliyun/table/event/event-update-in-one.txt

[flink]
Linked issue: close #4529 
To support the json format of aliyun Data Integration, DI in short.
The data in kafka collected by DI from mysql or oracle, are not in standard format. Not canal-json or debezium json. I would like call it aliyun-json.
We want to sink the data to paimon from kafka directly, with the kafka_sync_database/table action. So the aliyun-json must be supported, and parsed into cdc record.
Supplied with the commit.
No.
When used to process the data collected by ID, with paimon-flink-action, it just need to specify the json format as the following:
```shell
... paimon-flink-action-<version>.jar
kafka_sync_database 
...
--kafka_conf value.format=aliyun-json 
...
```

support aliyun-json when sinking data from kafka with paimon-flink-action

---

paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/HiveSchema.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveTableSchemaTest.java

Linked issue: [issue-4556](https://github.com/apache/paimon/issues/4556)
HiveCatalog add column is divided into two stages: first modify the paimon schema, then modify HMS. There will be a time difference between the two stages. If there is a task read (based on hivecatalog) during this time, the paimon schema and hive schema check will fail in the getDataFieldsJsonStr link.
Solution: Actually, you only need to ensure that the Hive DDL is a subset of the paimon schema.
org.apache.paimon.hive.HiveTableSchemaTest#testSupersetColumnNameAndType
org.apache.paimon.hive.HiveTableSchemaTest#testSubsetColumnNameAndType
org.apache.paimon.hive.HiveSchema#checkPartitionMatched
only need to ensure that the Hive DDL is a subset of the paimon schema.

[Hive] Fix Hive DDL and paimon schema mismatched bug

---

paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java
paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeWriter.java

RecordWriter.isCompacting: Check if a compaction is in progress, or if a compaction result remains to be fetched.
It is better to try to trigger compact before check if a compaction is in progress. Otherwise, there may be residual potential incomplete compacts.

[core] Ensure triggerCompaction in RecordWriter.isCompacting

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedCatalog.java
paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedObjectTable.java
paimon-core/src/main/java/org/apache/paimon/table/FileStoreTableFactory.java
paimon-core/src/main/java/org/apache/paimon/table/object/ObjectRefresh.java
paimon-core/src/main/java/org/apache/paimon/table/object/ObjectTable.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ObjectTableITCase.java

Improve object table:
1. FileIO can be customized in AbstractCatalog.
2. Privileged should handle ObjectTable.
3. Add parent_path in Object table schema.

[core] Improve object table for fileIO, Privileged and parent_path

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-spark/paimon-spark-common/src/test/java/org/apache/paimon/spark/SparkCatalogWithHiveTest.java

Support spark to create external table sql statements.
```sql
CREATE EXTERNAL TABLE t1 (a INT, bb INT, c STRING)
```

[spark] Support spark to create external table sql statements.

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BranchSqlITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ContinuousFileStoreITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ConsumerActionITCase.java

Linked issue: #4442 
This PR fixes the bug that Consumers might not have been reset yet when the streaming job is closed in test cases. This is because the resetting logic happens in `MonitorFunction#notifyCheckpointComplete`, and Flink does not guarantee the invocation of this method when the job is canceled or stopped.
This bug happens rarely in the current test cases because Flink's legacy source function runs independently in a separated thread. When we use FLIP-27 source for MonitorFunction and checkpoint events may pile up in Flink's Mailbox, this bug will be triggered more frequently.

[flink][hotfix] Wait for consumer reset before job close

---

paimon-flink/paimon-flink-1.15/src/main/java/org/apache/flink/api/common/functions/OpenContext.java
paimon-flink/paimon-flink-1.16/src/main/java/org/apache/flink/api/common/functions/OpenContext.java
paimon-flink/paimon-flink-1.17/src/main/java/org/apache/flink/api/common/functions/OpenContext.java
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/flink/api/common/functions/OpenContext.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/kafka/KafkaSinkFunction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcDynamicTableParsingProcessFunction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcMultiTableParsingProcessFunction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcParsingProcessFunction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunctionBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/service/QueryAddressRegister.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/service/QueryFileMonitor.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/shuffle/RangeShuffle.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowDataStoreWriteOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/SortUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/BucketUnawareCompactSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedAwareBatchSourceFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedAwareStreamingSourceFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedCompactorSourceFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedUnawareBatchSourceFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedUnawareStreamingSourceFunction.java

Linked issue: #4442 
This PR avoids deprecated usage on `RichFunction#open(Configuration)`, and turn to `RichFunction#open(OpenContext)`.

[flink] Adopt open(OpenContext) in RichFunction

---

paimon-flink/paimon-flink-1.15/src/main/java/org/apache/paimon/flink/utils/RuntimeContextUtils.java
paimon-flink/paimon-flink-1.16/src/main/java/org/apache/paimon/flink/utils/RuntimeContextUtils.java
paimon-flink/paimon-flink-1.17/src/main/java/org/apache/paimon/flink/utils/RuntimeContextUtils.java
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/utils/RuntimeContextUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/service/QueryExecutorOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/HashBucketAssignerOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTablesStoreCompactOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCompactOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/TableWriteOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalIndexAssignerOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/IndexBootstrapOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/SortOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/AppendBypassCoordinateOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/BucketUnawareCompactSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/RuntimeContextUtils.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/UnawareBucketAppendOnlyTableITCase.java

Linked issue: #4442 
This pull request adopts RuntimeContext#getTaskInfo when acquiring parallelism information.

[flink] Adopt getTaskInfo() when acquiring parallelism info

---

paimon-core/src/main/java/org/apache/paimon/operation/CleanOrphanFilesResult.java
paimon-core/src/main/java/org/apache/paimon/operation/LocalOrphanFilesClean.java
paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java
paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
paimon-core/src/test/java/org/apache/paimon/operation/LocalOrphanFilesCleanTest.java
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/RemoveOrphanFilesProcedure.java
paimon-flink/paimon-flink-1.18/src/test/java/org/apache/paimon/flink/RemoveOrphanFilesActionITCase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/orphan/FlinkOrphanFilesClean.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RemoveOrphanFilesProcedure.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionITCaseBase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedure.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/orphan/SparkOrphanFilesClean.scala
paimon-spark/paimon-spark-common/src/test/scala/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedureTest.scala

In my company, after we run a RemoveOrphanFilesAction, we not only want to know the number of orphan files that have been cleared, but also want to know how much capacity has been cleared.
This pr add deletedFileTotalLenInBytes in result of OrphanFilesClean.

[Core][Flink][Spark] Add deletedFileTotalLenInBytes in result of OrphanFilesClean

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java

When store the catalog in s3 object store, as the number of tables increases, the performance of the `show tables` deteriorates.
Because the `FileUtils#listVersionedFileStatus` method will send many `list` request to the s3 server.
**List 100 tables** 
Before patch
```
test_table98
test_table99
Time taken: 68.043 seconds, Fetched 100 row(s)
```
After patch
```
test_table98
test_table99
Time taken: 2.298 seconds, Fetched 100 row(s)
```

[core] Improve the performance of show tables

---

.github/workflows/publish_snapshot.yml

Explicitly set spark3 profile in publish snapshot, because explicit profile will override the default profile

[spark] Explicitly set spark3 profile in publish snapshot

---

paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java

Overwrite commit will read all entries, and generate DELETE entries.
We should drop stats for these DELETE entries, otherwise memory will be too big.

[core] Drop stats for overwrite commit

---

paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
paimon-core/src/test/java/org/apache/paimon/operation/FileStoreCommitTest.java

Overwrite commit will read all entries, and generate DELETE entries.
We should drop stats for these DELETE entries, otherwise memory will be too big.
`FileStoreCommitTest#testDropStatsForOverwrite`

[core] Add tests for drop stats for overwrite commit

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkFileIO.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FileStoreSourceReader.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedSourceReader.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/IteratorSourcesITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/util/MiniClusterWithClientExtension.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/util/ReadWriteTableTestUtil.java

Linked issue: #4442
This pull request fixes several usages about deprecated APIs that will be removed in Flink 2.0. Each of these fixes are so small so they are placed together into this PR.

[flink] Avoids miscellaneous deprecated APIs for 2.0 Preview

---

docs/content/flink/procedures.md
docs/content/maintenance/dedicated-compaction.md
docs/content/spark/procedures.md
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/CompactDatabaseProcedure.java
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/CompactProcedure.java
paimon-flink/paimon-flink-1.18/src/test/java/org/apache/paimon/flink/procedure/ProcedurePositionalArgumentsITCase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactDatabaseActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CompactDatabaseProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CompactProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CombinedTableCompactorSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CompactorSinkBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTablesStoreCompactOperator.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactActionITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/MinorCompactActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/CompactProcedureITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CompactorSinkITCase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/CompactProcedureTestBase.scala

Linked issue: (https://github.com/apache/paimon/issues/4566)
```
- `--compact_strategy` Determines how to pick files to be merged, the default is determined by the runtime execution mode, streaming-mode use minor strategy and batch-mode use full strategy.
- `full `: Only supports batch mode. All files will be selected for merging.
- `minor `: Pick the set of files that need to be merged based on specified conditions.
```

[flink] Support minor compact strategy for dedicated compaction action.

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java

When store the catalog in s3 object store, as the number of tables increases, the performance of the `show tables` deteriorates.
`HiveCatalog#listTablesImpl` will check each table in filesystem, will send many `list` request to the s3 server.
reason as https://github.com/apache/paimon/pull/4592
**List 102 tables** 
Before patch
```
abc098
abc099
Time taken: 25.643 seconds, Fetched 102 row(s)
```
After patch
```
abc098
abc099
Time taken: 1.711 seconds, Fetched 102 row(s)
```

[core] Improve the performance of show tables with hive metastore

---

paimon-core/src/main/java/org/apache/paimon/io/StatsCollectingSingleFileWriter.java

This could save one remote IO operation when stats mode is none

[core] Avoid extract from file footer when stats mode is none

---

paimon-common/src/main/java/org/apache/paimon/types/FieldIdentifier.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunction.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/SchemaEvolutionTest.java

Linked issue: [Issue-4521](https://github.com/apache/paimon/issues/4521)
In scenarios where the number of Paimon table fields is large and the Write concurrency is high, reduce the Latest-Schema access frequency to improve the throughput of job cold start
Case-1: Observe whether the checkpoint time of schema evolution changes
Conclusion: After optimization, Schema Evolution is basically completed in seconds, or even milliseconds.
Case-2: Observe the log to see if there are still a large number of read schema behaviors
Conclusion: From hundreds of thousands to 115 times
org.apache.paimon.flink.sink.cdc.UpdatedDataFieldsProcessFunction#processElement
Before the Schema Evolution operator calls org.apache.paimon.flink.sink.cdc.UpdatedDataFieldsProcessFunctionBase#extractSchemaChanges, add a …

[paimon-flink-cdc] Add the latest_schema state at schema evolution operator ，Reduce the latest schema access frequency

---

paimon-core/src/main/java/org/apache/paimon/rest/responses/ConfigResponse.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/ErrorResponse.java
paimon-core/src/test/java/org/apache/paimon/rest/MockRESTData.java

change JsonProperty path, test error in idea.
程序包org.apache.paimon.shade.com.fasterxml.jackson.annotation不存在
org.apache.paimon.shade.com.fasterxml.jackson.annotation.JsonProperty

[Core]Fix JsonProperty import path in rest package

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/test/java/org/apache/paimon/schema/SchemaManagerTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-spark/paimon-spark-ut/src/test/java/org/apache/paimon/spark/SparkSchemaEvolutionITCase.java

We have supported changing nested column types in array/map in Flink. This PR supports this feature in Spark.
IT cases.

[spark] Support changing column types in array<struct> or map<?,struct>

---

docs/content/migration/iceberg-compatibility.md
paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergOptions.java
paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestFile.java
paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestList.java
paimon-core/src/test/java/org/apache/paimon/iceberg/IcebergCompatibilityTest.java

Some Iceberg reader cannot support zstd for manifest files, for example DuckDB.
It is better to use gzip by default.

[iceberg] Use gzip by default to iceberg avro writer

---

docs/content/migration/iceberg-compatibility.md
paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergOptions.java
paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestFileMeta.java
paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestFileMetaSerializer.java
paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergManifestList.java
paimon-core/src/test/java/org/apache/paimon/iceberg/IcebergCompatibilityTest.java

AWS Athena may use old manifest reader to read Iceberg manifest by names, we should let Paimon producing legacy Iceberg manifest list file, so we introduce: `'metadata.iceberg.manifest-legacy-version'`.
Depends on https://github.com/apache/paimon/pull/4620

[iceberg] Introduce metadata.iceberg.manifest-legacy-version

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/DataCatalogTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkGenericCatalog.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/SystemCatalogTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/FlinkCatalogPropertiesUtil.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/FlinkDescriptorProperties.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogPropertiesUtilTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogTest.java

Linked issue: #4442
This PR removes deprecated usages about Flink Table API, mainly including TableSchema and DescriptorProperties.

[flink] Avoid deprecated usage on TableSchema, DataType and DescriptorProperties

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/lookup/AbstractLookupBenchmark.java
paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/lookup/LookupReaderBenchmark.java
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-common/src/main/java/org/apache/paimon/io/cache/CacheBuilder.java

more test after: https://github.com/apache/paimon/pull/4500/files
The sort format have the advantange as below
1. The compression rate of sort format is higher. 
2. Saved one file merge process.
Benchmarks also show that sort format has better write performance. However, hash format is optimized for values with the same value, so when values are the same, sort format may be slightly worse.
```
writer-100000:                                                                                       Best/Avg Time(ms)    Row Rate(K/s)      Per Row(ns)   Relative
-------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

[core] Make default of 'lookup.local-file-type' to sort

---

paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeyFileStoreTableTest.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetReaderFactory.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/AbstractColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/BooleanColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ByteColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/BytesColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/DoubleColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/FixedLenBytesColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/FloatColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/IntColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/LongColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/NestedColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/NestedPrimitiveColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ParquetReadState.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ParquetSplitReaderUtil.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/RunLengthDecoder.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ShortColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/TimestampColumnReader.java

Linked issue: #4586 
优化了基于 Parquet 文件过滤读取时的谓词下推能力，将原先的Parquet 谓词下推由RowGroup级别增强到了 Column page 级别，查询性能提升明显。
Optimized the predicate pushdown capability for filtering and reading Parquet files, enhancing the original predicate pushdown from the RowGroup level to the Column Page level, resulting in a significant improvement in query performance.

[core] Optimization of Parquet Predicate Pushdown Capability

---

docs/layouts/shortcodes/generated/hive_catalog_configuration.html
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalogFactory.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalogOptions.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/iceberg/IcebergHiveMetadataCommitter.java

…
[doc] Add metastore.client.class option to hive catalog configuration document.

[doc] Add metastore.client.class option to hive catalog configuration document.

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PrimaryKeyFileStoreTableITCase.java

`@Timeout` annotation currently does not work in `PrimaryKeyFileStoreTableITCase`, because Flink's `collect` method will ignore `InterruptedException` triggered by junit timeout.
This PR creates another timeout thread to cancel the job, so that we can work-around this issue.

[tests] Fix @Timeout annotation not working in PrimaryKeyFileStoreTableITCase

---

docs/content/migration/iceberg-compatibility.md
paimon-core/src/main/java/org/apache/paimon/iceberg/AbstractIcebergCommitCallback.java
paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergDataFileMeta.java
paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergDataField.java
paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergListType.java
paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergMapType.java
paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergStructType.java
paimon-core/src/test/java/org/apache/paimon/iceberg/IcebergCompatibilityTest.java
paimon-flink/paimon-flink-1.16/src/test/java/org/apache/paimon/flink/iceberg/Flink116IcebergITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/iceberg/FlinkIcebergITCaseBase.java

Currently, Iceberg compatible metadata has supported all primitive types in Iceberg. This PR adds support for nested types.

[core] Support nested types in Iceberg compatible metadata

---

paimon-core/src/main/java/org/apache/paimon/append/UnawareAppendTableCompactionCoordinator.java
paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/stats/SimpleStatsEvolution.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupDataTableScan.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PrimaryKeyPartialLookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/service/QueryFileMonitor.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala

Statistic is only useful for ADD files.

[core] Drop stats for deleted data files to reduce memory

---

paimon-e2e-tests/src/test/java/org/apache/paimon/tests/E2eTestBase.java
paimon-e2e-tests/src/test/resources-filtered/docker-compose.yaml

Currently e2e tests constantly suffers from initialization timeout, due to zookeeper not running. This PR tries to fix this issue by updating kafka image version.
Reference: https://github.com/confluentinc/cp-docker-images/issues/925

[e2e] Try to fix e2e tests timeout by updating kafka image version

---

docs/content/concepts/spec/fileindex.md
paimon-common/src/main/java/org/apache/paimon/utils/BitSliceIndexRoaringBitmap.java
paimon-common/src/test/java/org/apache/paimon/utils/BitSliceIndexRoaringBitmapTest.java

Firstly, When users turn off to collect the column stats, bsi compare would return a wrong result. Because the predicate can not out of the bsi min/max range in oneil compare.
Secondly, using min/max compare can fast return. e.g. in the GT case, if the predicate is less than the min value, we just need to return the existence bitmap.
At last, because of the v1.0 in paimon is not yet released, I didn't do the compatibility work about the bsi index.
org.apache.paimon.utils.BitSliceIndexRoaringBitmapTest

[core] Use min/max to fast skip the bsi index comparison

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/append/UnawareAppendTableCompactionCoordinator.java
paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
paimon-core/src/main/java/org/apache/paimon/operation/MemoryFileStoreWrite.java
paimon-core/src/test/java/org/apache/paimon/operation/FileStoreCommitTest.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala

It is better to be compatible to old readers. So this PR introduces an option manifest.delete-file-drop-stats to disable this by default.

[core] Introduce manifest.delete-file-drop-stats

---

paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java

`commit.max-retries` represents retry times. If we configure it to 10, it means a maximum of 11 commits. If we configure it to 0, it means no retries are allowed.

[core] Make commit.max-retries behave as it means

---

paimon-format/src/main/java/org/apache/paimon/format/parquet/writer/RowDataParquetBuilder.java

Linked issue: close #4586 
Added the `parquet.page.row.count.limit` parameter for Parquet file writing. The writing of Parquet files is influenced by both `parquet.page.size` and `parquet.page.row.count.limit`. If only `parquet.page.size` is set, it may not have an effect or could lead to misalignment of pages, impacting performance.
新增parquet 文件写入 `parquet.page.row.count.limit` 参数传递，parquet 文件写入时是通过 `parquet.page.size` 与 `parquet.page.row.count.limit` 共同影响的， 如果单一设置 `parquet.page.size` 可能没有产生作用，或者导致 page 不对齐影响性能
```
// org.apache.parquet.column.impl.ColumnWriteStoreBase
private void sizeCheck() {
...
int pageRowCountLimit = props.getPageRowCountLimit();
...
for (ColumnWriterBase writer : columns.values()) {
long usedMem = writer.getCurrentPageBufferedSize();
long rows = rowCount - …
```

[core] Add parquet write page limit parameter

---

docs/content/spark/auxiliary.md
docs/content/spark/sql-ddl.md
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonViewResolver.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/execution/PaimonStrategy.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/execution/PaimonViewExec.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonViewTestBase.scala

Support show create and describe view
```sql
SHOW CREATE TABLE v;
DESC TABLE EXTENDED v;
```

[spark] Support show create and describe view

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/operation/PartitionExpire.java
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/ExpirePartitionsProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpirePartitionsAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ExpirePartitionsProcedure.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/ExpirePartitionsProcedureITCase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ExpirePartitionsProcedure.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/ExpirePartitionsProcedureTest.scala

When expiring too many partitions using a dedicated expire_partitions job, it will have an impact on manifest merge and flink task stability. So adding a conf to control the expired number of partitions at a time.

[core] Expire partiitons add default delete num

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/metrics/FileStoreSourceReaderMetrics.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/ReadOperator.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/metrics/FileStoreSourceReaderMetricsTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/operator/OperatorSourceTest.java

Support Flink sourceIdleTime metric in ReadOperator
Linked issue: close #4249

[flink] support flink sourceIdleTime metric in ReadOperator

---

paimon-core/src/main/java/org/apache/paimon/manifest/ExpireFileEntry.java
paimon-core/src/main/java/org/apache/paimon/manifest/FileEntry.java
paimon-core/src/main/java/org/apache/paimon/manifest/ManifestEntry.java
paimon-core/src/main/java/org/apache/paimon/manifest/ManifestFile.java
paimon-core/src/main/java/org/apache/paimon/manifest/SimpleFileEntry.java
paimon-core/src/main/java/org/apache/paimon/operation/ChangelogDeletion.java
paimon-core/src/main/java/org/apache/paimon/operation/FileDeletionBase.java
paimon-core/src/main/java/org/apache/paimon/operation/SnapshotDeletion.java
paimon-core/src/main/java/org/apache/paimon/operation/TagDeletion.java
paimon-core/src/main/java/org/apache/paimon/table/ExpireChangelogImpl.java
paimon-core/src/main/java/org/apache/paimon/table/ExpireSnapshotsImpl.java
paimon-core/src/main/java/org/apache/paimon/table/RollbackHelper.java
paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
paimon-core/src/test/java/org/apache/paimon/operation/ExpireSnapshotsTest.java

For expiring snapshots and tags, we don't need to keep whole `ManifestEntry`, we can have a dedicated class to maintain file entry structure to reduce memory usage.

[core] Optimize memory usage for expiring snapshots and tags

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/AbstractPaimonSparkSqlExtensionsParser.scala
paimon-spark/paimon-spark-ut/src/test/java/org/apache/paimon/spark/extensions/CallStatementParserTest.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/ProcedureTestBase.scala

Spark allows users to configure multiple extensions and each extension is allowed to inject its own SQL parser, conflicts maybe occur if multiple extensions support the`call` command. We know that the `SYSTEM_DATABASE_NAME` of  all paimon procedures are `sys`, so only parsing supported procedures in paimon.
Also, support ``call catalog.`sys`.`rollback` procedure`` with backticks.
like iceberg https://github.com/apache/iceberg/pull/11480

[spark] Paimon parser only resolve own supported procedures

---

paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java

Overwrite commit should use `tryCommit` to use CommitResult to retry, in this way, retry cost will be reduced.

[core] Optimize overwrite commit to use CommitResult to retry

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
tools/maven/checkstyle.xml

1. When execute drop partition or expire partition with large numbers partitions(eg: table with large number of files and stream job with 1 min ckp), would block batch job for overwrite in a long time loop,  so add a timeout option for commit retry, user can quick get job result in a specific timeout to handle their batch job(which can adjust ckp time interval or stop stream job to finish their batch job). 
2. FileLength change to 4000 for CoreOption lines was near 3000 which would block code compile.

[core] Introduce timeout for commit retry avoid long time loop

---

docs/content/migration/iceberg-compatibility.md
docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java
paimon-core/src/main/java/org/apache/paimon/utils/FileStorePathFactory.java
paimon-core/src/test/java/org/apache/paimon/io/KeyValueFileReadWriteTest.java
paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileMetaTestBase.java
paimon-core/src/test/java/org/apache/paimon/manifest/ManifestFileTest.java
paimon-core/src/test/java/org/apache/paimon/manifest/ManifestListTest.java
paimon-core/src/test/java/org/apache/paimon/table/AppendOnlyFileStoreTableTest.java
paimon-core/src/test/java/org/apache/paimon/utils/FileStorePathFactoryTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/TestChangelogDataReadWrite.java
paimon-spark/paimon-spark-ut/src/test/java/org/apache/paimon/spark/SparkFileIndexITCase.java
tools/maven/checkstyle.xml

Specify the path directory of data files.
Duckdb Iceberg connector may rely on files placed in the `root/data` directory, while Paimon is usually placed directly in the `root` directory, so you can configure this parameter for the table to achieve compatibility: `'data-file.path-directory' = 'data'`.

[core] Introduce data-file.path-directory

---

docs/content/spark/sql-ddl.md
docs/content/spark/sql-write.md
paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkSource.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DDLTestBase.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTestBase.scala

- When the table already exists, we do not need to specify the schema when creating an external table (since it must be consistent with the old schema and can easily be written incorrectly).  
- TBLPROPERTIES can be a subset of the existing props, and for cross-engine compatibility, we have omitted the comparison of `owner`.
`CREATE TABLE t USING paimon LOCATION 'xxxx'`
extra updates:
- not save `provider` to props when create table with spark
Deprecated modification ~- Support add new props when creating external tables, for example, when a table written in Flink is used to create an external table in Spark, in this case, new props such as {provider: paimon} need be added~

[hive][spark] Support creating external table without schema when the table already exists

---

paimon-arrow/src/test/java/org/apache/paimon/arrow/converter/ArrowBatchConverterTest.java

The orc char reader will trim the string which make the tests assumption wrong.

[hotfix] Fix flaky test of orc tests in ArrowBatchConverterTest

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/CloneSourceBuilder.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CloneActionITCase.java

env.fromCollection will throw `Collection must not be null` which is confusing.

[hotfix] CloneAction throw more clear exception when no table in source catalog

---

docs/content/flink/procedures.md
docs/content/spark/procedures.md
paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/RollbackToWatermarkProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RollbackToWatermarkProcedure.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/RollbackToWatermarkProcedureITCase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RollbackToWatermarkProcedure.java

Currently paimon cannot rollback to watermark value for flink job, introduce RollbackToWatermarkProcedure to support it.
RollbackToWatermarkProcedureITCase

[core] Introduce RollbackToWatermarkProcedure for rollback

---

paimon-core/src/main/java/org/apache/paimon/table/system/BinlogTable.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonSystemTableTest.scala

[spark] Fix the build of read type in binlog table

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/CachingCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Identifier.java
paimon-core/src/test/java/org/apache/paimon/catalog/CachingCatalogTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/DeleteBranchProcedure.java
paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/DataFrameWriteTest.scala
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/PaimonSinkTest.scala
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/DeleteBranchProcedure.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/PaimonSinkTest.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DataFrameWriteTest.scala

- Clean up invalid branch cache when table or brach id dropped
- Caching catalog not cache system table
Other:
Remove "spark.sql.catalog.paimon.cache-enabled" -> "false" in `PaimonSparkTestBase`. Note: there are still some cases that cannot enable it because it is incompatible with `write.merge-schema` currently.

[core] Clean up invalid branch cache and not cache system table in caching catalog

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/plans/logical/PaimonTableValuedFunctions.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/TableValuedFunctionsTest.scala

Avoid explicitly creating catalog in PaimonTableValuedFunctions,  which will miss some automatic fill configurations
```
Caused by: java.lang.NullPointerException: Paimon 'warehouse' path must be set
at org.apache.paimon.utils.Preconditions.checkNotNull(Preconditions.java:65)
at org.apache.paimon.catalog.CatalogFactory.warehouse(CatalogFactory.java:55)
at org.apache.paimon.catalog.CatalogFactory.createCatalog(CatalogFactory.java:83)
at org.apache.paimon.catalog.CatalogFactory.createCatalog(CatalogFactory.java:66)
at org.apache.paimon.spark.SparkCatalog.initialize(SparkCatalog.java:76)
at org.apache.paimon.spark.catalyst.plans.logical.PaimonTableValuedFunctions$.resolvePaimonTableValuedFunction(PaimonTableValuedFunctions.scala:67)
```

[spark] Avoid explicitly creating catalog in PaimonTableValuedFunctions

---

paimon-common/src/main/java/org/apache/paimon/fs/FileIOUtils.java
paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java

Maybe over-writer file will fail, so it's better to add some retries.

[core] Retry if snapshot commit hint failed.

---

docs/content/cdc-ingestion/kafka-cdc.md
docs/layouts/shortcodes/generated/kafka_sync_database.html
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/CdcActionCommonUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncDatabaseActionBase.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncDatabaseActionFactoryBase.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/TableNameConverter.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncDatabaseAction.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/TableNameConverterTest.java
pom.xml

Linked issue: close #4703 
With kafka_sync_database, user can specify different prefix and suffix for different db.
org.apache.paimon.flink.action.cdc.TableNameConverterTest#testConvertTableNameByDBPrefix_Suffix
No
Yes and provided.

[flink] kafka_sync_database supports different prefix and suffix for different db

---

paimon-core/src/main/java/org/apache/paimon/table/source/DataSplit.java
paimon-core/src/main/java/org/apache/paimon/table/source/DataTableBatchScan.java
paimon-core/src/test/java/org/apache/paimon/table/source/SplitGeneratorTest.java
paimon-core/src/test/java/org/apache/paimon/table/source/SplitTest.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScanBuilder.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/aggregate/LocalAggregator.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonPushDownTest.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PushDownAggregatesTest.scala

Since we introduce dv cardinality in #4699, we can enable limit pushdown and count optimization for dv table now

[core][spark] Enable limit pushdown and count optimization for dv table

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/changelog/ChangelogCompactTaskSerializer.java

`newHashMapWithExpectedSize` is internally used in flink, we should avoid using it.

[flink] avoid using 'newHashMapWithExpectedSize' which is internal in flink

---

paimon-flink/paimon-flink-1.15/src/main/java/org/apache/paimon/flink/source/DataTableSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/BaseDataTableSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/DataTableSource.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/statistics/FileStoreTableStatisticsTestBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/statistics/PrimaryKeyTableStatisticsTest.java

[flink] Enable limit pushdown and count optimization for dv table

---

paimon-core/src/main/java/org/apache/paimon/utils/FileStorePathFactory.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/SparkDataFileMeta.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/SparkDeletionVectors.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DeletionVectorTest.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTestBase.scala

Fix relativeBucketPath with data-file.path-directory

[spark] Fix relativeBucketPath with data-file.path-directory

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/CopyFileOperator.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkCatalogTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/PartitionMarkDoneTest.java

`Catalog` should not provide some interfaces to expose location, the location is an internal concept for Paimon table.
1. `CopyFileOperator` use `getTable` to get table path.
2. Like https://github.com/apache/paimon/pull/4638 , Flink also support external table to avoid using `getTableLocation`.
3. Remove `Catalog.getTableLocation` interface.

[core] Remove Catalog.getTableLocation interface

---

paimon-common/src/main/java/org/apache/paimon/types/ArrayType.java
paimon-common/src/main/java/org/apache/paimon/types/DataField.java
paimon-common/src/main/java/org/apache/paimon/types/DataType.java
paimon-common/src/main/java/org/apache/paimon/types/MapType.java
paimon-common/src/main/java/org/apache/paimon/types/RowType.java
paimon-core/src/main/java/org/apache/paimon/schema/Schema.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/main/java/org/apache/paimon/schema/TableSchema.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTestBase.scala

Fix create external table with schema evolution, e.g.
```sql
CREATE TABLE t1 (a INT, b INT, c INT) USING paimon;
ALTER TABLE t1 DROP COLUMN b;
ALTER TABLE t1 ADD COLUMN b INT;
-- ok
CREATE TABLE t2 (a INT, c INT, b INT) USING paimon LOCATION '/path/to/t1';
-- error
CREATE TABLE t2 (a INT, b INT, c INT) USING paimon LOCATION '/path/to/t1';
```

[core][spark] Fix create external table with schema evolution

---

pom.xml

- Avoid trying to download release artifacts from Apache snapshot repo.
- Add `central` repo to ensure it's preferred to `repository.apache.org` when downloading release artifacts.
Uncommented the `<repositories>` section, and built locally.
```
$ mvn -DskipTests clean package
...
[INFO] ------------------< org.apache.paimon:paimon-parent >-------------------
[INFO] Building Paimon : 1.0-SNAPSHOT                                    [1/52]
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/com/diffplug/spotless/spotless-maven-plugin/2.13.0/spotless-maven-plugin-2.13.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/com/diffplug/spotless/spotless-maven-plugin/2.1 …
```

[pom] prefer central repo for releases; limit apache-snapshots to snapshots

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/metastore/AddPartitionCommitCallback.java
paimon-core/src/main/java/org/apache/paimon/metastore/AddPartitionTagCallback.java
paimon-core/src/main/java/org/apache/paimon/metastore/MetastoreClient.java
paimon-core/src/main/java/org/apache/paimon/metastore/PartitionStats.java
paimon-core/src/main/java/org/apache/paimon/operation/PartitionExpire.java
paimon-core/src/main/java/org/apache/paimon/partition/actions/MarkPartitionDoneEventAction.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/test/java/org/apache/paimon/operation/PartitionExpireTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionStatisticsReporter.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/AddDonePartitionActionTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/PartitionStatisticsReporterTest.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveMetastoreClient.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonPartitionManagement.scala

New MetastoreClient API:
```java
/**
* A metastore client related to a table. All methods of this interface operate on the same specific
* table.
*/
public interface MetastoreClient extends AutoCloseable {
void addPartition(LinkedHashMap<String, String> partition) throws Exception;
void addPartitions(List<LinkedHashMap<String, String>> partitions) throws Exception;
void dropPartition(LinkedHashMap<String, String> partition) throws Exception;
void dropPartitions(List<LinkedHashMap<String, String>> partitions) throws Exception;
void markPartitionDone(LinkedHashMap<String, String> partition) throws Exception;
default void alterPartition(
LinkedHashMap<String, String> partition, PartitionStats partitionStats)
throws Exception {
throw new UnsupportedOperationException();
}
/** Factory to …
```

[core] Refactor MetastoreClient methods to simplify catalog

---

LICENSE
paimon-common/src/main/java/org/apache/paimon/data/variant/GenericVariant.java
paimon-common/src/main/java/org/apache/paimon/data/variant/GenericVariantBuilder.java
paimon-common/src/main/java/org/apache/paimon/data/variant/GenericVariantUtil.java
paimon-common/src/main/java/org/apache/paimon/data/variant/PathSegment.java
paimon-common/src/main/java/org/apache/paimon/data/variant/Variant.java
paimon-common/src/test/java/org/apache/paimon/data/variant/GenericVariantTest.java

Subtask of #4471
Variant was born from Apache Spark, and the encoding rules have been incorporated into Parquet https://github.com/apache/parquet-format/blob/master/VariantEncoding.md
This PR add the basic interface of Variant and ported the latest implementation of Spark.
```java
public interface Variant {
/** Returns the variant metadata. */
byte[] metadata();
/** Returns the variant value. */
byte[] value();
/** Parses the variant to json. */
String toJson();
/**
* Extracts a sub-variant value according to a path which start with a `$`. 
*/
Object variantGet(String path);
}
```
Usage
```java
String json = "{\"age\":35,\"city\":\"Hangzhou\"}";
Variant v = GenericVariant.fromJson(json);
assertThat(v.variantGet("$.age")).isEqualTo(35L); …
```

[core] Introduce Variant data

---

docs/content/cdc-ingestion/kafka-cdc.md
docs/layouts/shortcodes/generated/kafka_sync_database.html
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/CdcActionCommonUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncDatabaseActionBase.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncDatabaseActionFactoryBase.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/RichCdcMultiplexRecordEventParser.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/SyncDatabaseActionBaseTest.java

Linked issue: close #4722 
org.apache.paimon.flink.action.cdc.SyncDatabaseActionBaseTest
No.
Yes and docs provided

[flink] kafka_sync_database supports db whitelist and blacklist

---

docs/layouts/shortcodes/generated/catalog_configuration.html
paimon-common/src/main/java/org/apache/paimon/options/CatalogOptions.java
paimon-core/src/main/java/org/apache/paimon/catalog/CachingCatalog.java
paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java
paimon-core/src/main/java/org/apache/paimon/operation/metrics/CacheMetrics.java
paimon-core/src/main/java/org/apache/paimon/operation/metrics/ScanMetrics.java
paimon-core/src/main/java/org/apache/paimon/utils/ObjectsCache.java
paimon-core/src/main/java/org/apache/paimon/utils/ObjectsFile.java
paimon-core/src/main/java/org/apache/paimon/utils/SegmentsCache.java
paimon-core/src/test/java/org/apache/paimon/metrics/MetricGroupTest.java
paimon-core/src/test/java/org/apache/paimon/metrics/TestMetricRegistry.java
paimon-core/src/test/java/org/apache/paimon/operation/metrics/CommitMetricsTest.java
paimon-core/src/test/java/org/apache/paimon/operation/metrics/CompactionMetricsTest.java
paimon-core/src/test/java/org/apache/paimon/operation/metrics/ScanMetricsTest.java
paimon-core/src/test/java/org/apache/paimon/utils/ObjectsCacheTest.java

Add CacheSizes for CachingCatalog and CacheMetrics for ObjectCache so that engine can get cache stats at query level.
added
CachingCatalog.estimatedCacheSizes
ScanMetrics.getLatestScan
ScanMetrics.getCacheMetrics
added

[core] Introduce CacheStats and expose ScanStats

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperator.java

add more detailed exception message for CdcRecordStoreMultiWriteOperator.

[cdc] add exception message for CdcRecordStoreMultiWriteOperator

---

paimon-common/src/main/java/org/apache/paimon/casting/CastExecutors.java
paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFileStoreScan.java
paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreScan.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaEvolutionUtil.java
paimon-core/src/main/java/org/apache/paimon/stats/SimpleStatsEvolutions.java
paimon-core/src/main/java/org/apache/paimon/utils/FormatReaderMapping.java
paimon-core/src/test/java/org/apache/paimon/schema/SchemaEvolutionUtilTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FilterPushdownWithSchemaChangeITCase.java

Reproduce case:
```
CREATE TABLE T (
id INT,
f DECIMAL(5,2),
);
INSERT INTO T VALUES (1, 111.32);
ALTER TABLE T MODIFY (f DECIMAL(6, 3));
SELECT * FROM T WHERE f < 111.321;
```
The result is empty but expected 111.320
There are also same problem for other field cast Scenario.

[core] Fix predicate literals cast in filter pushdown after schema evolution

---

paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveMetastoreClient.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTestBase.scala

1. Fix sync hms partition with `data-file.path-directory`
2. make `data-file.path-directory` Immutable
3. sync `data-file.path-directory` to hms anyway

[hive] Fix sync hms partition with data-file.path-directory

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/CatalogUtils.java
paimon-core/src/test/java/org/apache/paimon/catalog/FileSystemCatalogTest.java
paimon-core/src/test/java/org/apache/paimon/jdbc/JdbcCatalogTest.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncDatabaseActionBase.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncTableActionBase.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SynchronizationActionBase.java
paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/HiveCatalogTest.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkGenericCatalog.java
paimon-spark/paimon-spark-ut/src/test/java/org/apache/paimon/spark/SparkGenericCatalogWithHiveTest.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTestBase.scala

Checked with iceberg and delta, they don't check the case of tables or fields with hive in catalog.
So skip case checking in paimon too, and let the catalog implementation do case checking itself.
For example, table names are always lowercase in hive, so when creating a table with the same lowercase with hive catalog, hive will throw an exception:
```sql
create table t;
-- table exists exception
create table T;
```

[core] Skip case checking in catalog

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java

For a database containing thousands of tables on OSS, show tables may take several minutes.
It is enough to compare prop to determine whether it is a paimon table when show tables,  we can skip checking table exists in filesystem. And  the batch list api can reduce the metastore call overhead.
cost: 3min -> 4s

[hive] Batch list tables and skip checking table exists in filesystem with hive catalog

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaEvolutionUtil.java
paimon-core/src/test/java/org/apache/paimon/schema/SchemaEvolutionUtilTest.java

[hotfix] Remove unused SchemaEvolutionUtil methods

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/catalog/SupportFunction.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonFunctionTest.scala

`loadFunction` in `SparkGenericCatalog` should throw `NoSuchFunctionException` instead of `RuntimeException`, fix this
```
Function test_hive.myIntSum is not a paimon function
java.lang.RuntimeException: Function test_hive.myIntSum is not a paimon function
at org.apache.paimon.spark.catalog.SupportFunction.loadFunction(SupportFunction.java:67)
at org.apache.paimon.spark.SparkGenericCatalog.loadFunction(SparkGenericCatalog.java:379)
at org.apache.spark.sql.connector.catalog.FunctionCatalog.functionExists(FunctionCatalog.java:60)
at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$20.applyOrElse(Analyzer.scala:2075)
at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$20.applyOrElse(Analyzer.scala:2066)
at …
```

[spark] Fix load function with SparkGenericCatalog

---

paimon-core/src/main/java/org/apache/paimon/table/source/ReadBuilder.java
paimon-core/src/main/java/org/apache/paimon/utils/FormatReaderMapping.java
paimon-core/src/test/java/org/apache/paimon/table/IncrementalTableTest.java
paimon-core/src/test/java/org/apache/paimon/table/TableTestBase.java
paimon-core/src/test/java/org/apache/paimon/table/system/BucketsTableTest.java
paimon-core/src/test/java/org/apache/paimon/table/system/PartitionsTableTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/NestedProjectedRowData.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/Projection.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/ProjectionRowData.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileStoreSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FileStoreSourceReader.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkRecordsWithSplitIds.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkSourceBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkTableSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/LogHybridSourceFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/StaticFileStoreSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/SystemTableSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedContinuousFileStoreSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedSourceReader.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/MonitorSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/ReadOperator.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ProjectionTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FileStoreSourceMetricsTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FileStoreSourceReaderTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FlinkRecordsWithSplitIdsTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ProjectionPushDownITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/align/AlignedSourceReaderTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/operator/OperatorSourceTest.java

Linked issue: close #4370
This PR supports nested projection pushdown in Flink Paimon source.
The following new test cases are added for nested projection abilities.
* ProjectionTest
* ProjectionPushDownITCase
Existing test cases will also assist in testing that exisiting source functions are not harmed by this PR.
This change does not introduce a new feature.

[flink] Support nested projection pushdown

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkFilterConverter.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/expressions/ExpressionHelper.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala
paimon-spark/paimon-spark-ut/src/test/java/org/apache/paimon/spark/SparkFilterConverterTest.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DeleteFromTableTestBase.scala

Currently paimon `delete where` supports directly dropping partitions when all filters are partition filter. Therefore we can not allow partial success for this filter conversion.
```sql
CREATE TABLE T (id INT, p STRING) PARTITIONED BY (p);
INSERT INTO T VALUES (2, '2024-12-16'), (3, '2024-12-17'), (4, '2024-12-18');
DELETE FROM T WHERE p >= date_sub('2024-12-17', 0) AND p < '2024-12-18';
SELECT * FROM T ORDER BY id;
```
before
```
+---+----------+
| id|         p|
+---+----------+
|  4|2024-12-18|
+---+----------+
```
after
```
+---+----------+
| id|         p|
+---+----------+
|  2|2024-12-16|
|  4|2024-12-18|
+---+----------+
```

[spark] Fix delete with partial non-convertible partition filter

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTestBase.scala

Ignore path comparison when creating external table, because the original table may not have the 'path' attribute

[hive] Ignore path comparison when creating external table

---

paimon-common/src/main/java/org/apache/paimon/data/columnar/ColumnarRowIterator.java
paimon-common/src/main/java/org/apache/paimon/data/columnar/VectorizedColumnBatch.java
paimon-common/src/main/java/org/apache/paimon/data/columnar/VectorizedRowIterator.java
paimon-format/src/main/java/org/apache/paimon/format/orc/OrcReaderFactory.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetReaderFactory.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetColumnVectorTest.java

Another solution for https://github.com/apache/paimon/pull/4748

[parquet] parquet reader should not retrun VectorizedRowIterator for nested schema

---

paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/NestedColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/NestedPrimitiveColumnReader.java

[hotfix] Fix typo in NestedColumnReader and NestedPrimitiveColumnReader

---

paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/NestedPositionUtil.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetReadWriteTest.java

Linked issue: close #4753 
covered
Format

[core] fix parquet can not read row with last column is array.

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreWriteOperator.java

[hotfix] Rename cdc schema change options in CdcRecordStoreWriteOperator

---

paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/FixedLenBytesBinaryColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/FixedLenBytesColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/FixedLenBytesDecimalColumnReader.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ParquetSplitReaderUtil.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetReadWriteTest.java

Currently, paimon parquet reader cannot read parquet files with 'FIXED_LEN_BYTE_ARRAY' type. 
This pr support parquet reader reading field with 'FIXED_LEN_BYTE_ARRAY' type
org.apache.paimon.format.parquet.ParquetReadWriteTest#testReadBinaryWrittenByParquet

[format] support parquet reader reading field with 'FIXED_LEN_BYTE_ARRAY' type

---

paimon-spark/paimon-spark-4.0/src/test/scala/org/apache/paimon/spark/sql/VariantTest.scala
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkRow.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkTypeUtils.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/paimon/shims/SparkShim.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/VariantTestBase.scala
paimon-spark/paimon-spark3-common/src/main/scala/org/apache/spark/sql/paimon/shims/Spark3Shim.scala
paimon-spark/paimon-spark4-common/src/main/scala/org/apache/paimon/spark/data/Spark4ArrayData.scala
paimon-spark/paimon-spark4-common/src/main/scala/org/apache/spark/sql/paimon/shims/Spark4Shim.scala

Subtask of #4471
- Integrate Variant with Spark4
```sql
CREATE TABLE t (v VARIANT) USING paimon;
INSERT INTO t VALUES parse_json('{"age":26,"city":"Beijing"}');
SELECT variant_get(v, '$.age', 'int') FROM t;
```

[spark] Integrate Variant with Spark4

---

paimon-core/src/main/java/org/apache/paimon/io/DataFileMeta.java
paimon-core/src/main/java/org/apache/paimon/io/DataFileMetaSerializer.java
paimon-core/src/main/java/org/apache/paimon/io/DataFilePathFactory.java
paimon-core/src/main/java/org/apache/paimon/io/FileIndexEvaluator.java
paimon-core/src/main/java/org/apache/paimon/io/KeyValueFileReaderFactory.java
paimon-core/src/main/java/org/apache/paimon/io/KeyValueFileWriterFactory.java
paimon-core/src/main/java/org/apache/paimon/manifest/FileEntry.java
paimon-core/src/main/java/org/apache/paimon/manifest/ManifestEntry.java
paimon-core/src/main/java/org/apache/paimon/manifest/SimpleFileEntry.java
paimon-core/src/main/java/org/apache/paimon/mergetree/MergeTreeWriter.java
paimon-core/src/main/java/org/apache/paimon/table/source/DataSplit.java
paimon-core/src/main/java/org/apache/paimon/table/system/FilesTable.java
paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java
paimon-core/src/test/java/org/apache/paimon/io/DataFilePathFactoryTest.java
paimon-core/src/test/java/org/apache/paimon/io/KeyValueFileReadWriteTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/ContainsLevelsTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/LookupLevelsTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTestBase.java
paimon-core/src/test/java/org/apache/paimon/utils/FileStorePathFactoryTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/CloneFileInfo.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/CopyFileOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/PickFilesForCloneOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/PickFilesUtil.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/changelog/ChangelogCompactTask.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RewriteFileIndexSink.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RewriteFileIndexActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/RewriteFileIndexProcedureITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/AppendOnlySingleTableCompactionWorkerOperatorTest.java
paimon-spark/paimon-spark-ut/src/test/java/org/apache/paimon/spark/SparkFileIndexITCase.java

Fix after https://github.com/apache/paimon/pull/4761
- External Path in DataFileMeta should be the file path instead of directory.
- And clean interface methods.

[core] External Path in DataFileMeta should be the file path

---

paimon-core/src/main/java/org/apache/paimon/table/system/BinlogTable.java

Avoid to construct the rowType for each record.

[core] optimize the binlog table read performance

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/DynamicPartitionLoader.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java

There is a scenario: the Join job is calculating the T day data, and the dim table is writing the (T + 1) day data, we can load two partitions data, so the Join job won't lose result when day is converting from T to T + 1.

[flink] Introduce max_two_pt for Flink lookup join

---

docs/content/append-table/bucketed.md
docs/content/append-table/query-performance.md
docs/content/primary-key-table/compaction.md
docs/content/primary-key-table/overview.md
docs/content/primary-key-table/query-performance.md

[docs] Fix typo in docs/content/pk-table&append-table

---

paimon-common/src/main/java/org/apache/paimon/lookup/sort/BlockWriter.java
paimon-common/src/test/java/org/apache/paimon/lookup/sort/SortLookupStoreFactoryTest.java

In some cases, for example, all records in remote file has been marked deleted. It is possible to build an empty local file to lookup. `BlockWriter.finish` will throw a `IllegalStateException`.
We can fix it by supporting empty record in `SortLookupStoreWriter`.

[core] SortLookupStoreWriter should support empty record

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonAnalysis.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/InsertOverwriteTableTestBase.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/WithTableOptions.scala

```sql
CREATE TABLE t (i INT, s STRUCT<f1: INT, f2: INT>);
INSERT INTO t VALUES ((1, null), (2, STRUCT(null, null));
SELECT s FROM t;
```
before
```
[null,null], [null,null]
```
after
```
-- orc and avro
null, [null,null]
```
There is still bug with reading parquet, which fix involves core changes, add an issue to track it https://github.com/apache/paimon/issues/4785

[spark] Fix writing null struct col

---

docs/content/cdc-ingestion/mysql-cdc.md
docs/content/flink/quick-start.md
docs/content/maintenance/write-performance.md

Starting with Flink 1.19, Flink has officially introduced full support for the standard YAML 1.2 syntax ([FLIP-366](https://cwiki.apache.org/confluence/display/FLINK/FLIP-366%3A+Support+standard+YAML+for+FLINK+configuration?src=contextnavpagetreemode)). The default configuration file has been changed to `config.yaml` and placed in the `conf/` directory.
No need
No
No

[docs] Use `config.yaml` for flink version >= 1.19

---

paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java
paimon-core/src/test/java/org/apache/paimon/operation/OrphanFilesCleanTest.java
paimon-flink/paimon-flink-1.18/src/test/java/org/apache/paimon/flink/RemoveOrphanFilesActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionITCaseBase.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedureTest.scala

Now when clean OrphanFiles by call RemoveOrphanFilesProcedure or RemoveOrphanFilesAction, If the argument older_than is large then now, dataFiles that are currently being written and not referenced by snapshots will be mistakenly cleaned up.
So add a check of the argument older_than.

Add check of older_than when RemoveOrphanFiles

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/BatchWriteGeneratorTagOperator.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/BatchWriteGeneratorTagOperatorTest.java

Linked issue: close #4774
Introduce a new option to set customized tag name for Batch TagCreationMode 
- BatchWriteGeneratorTagOperatorTest.testBatchWriteGeneratorCustomizedTag
No
No

[core] Support customized tag name in Batch TagCreationMode

---

docs/content/concepts/system-tables.md
paimon-core/src/main/java/org/apache/paimon/table/system/IndexesTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/SystemTableLoader.java
paimon-core/src/main/java/org/apache/paimon/table/system/TableIndexesTable.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SystemTableITCase.java

Provide a convienient way to query index files

[core] Support to query indexes

---

paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/bitmap/RoaringBitmapBenchmark.java
paimon-common/src/main/java/org/apache/paimon/utils/RoaringBitmap32.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/BitmapDeletionVector.java
paimon-core/src/main/java/org/apache/paimon/deletionvectors/DeletionVector.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldRoaringBitmap32Agg.java

In `RoaringBitmap`, the `deserialize(java.io.DataInput, byte[])` function has a better performance to deserialize the `BitmapContainer`.
No.
No.
No.

[common] Using a faster deserialization method in RoaringBitmap32

---

paimon-common/src/main/java/org/apache/paimon/utils/RoaringBitmap32.java
paimon-core/src/test/java/org/apache/paimon/table/AppendOnlyFileStoreTableTest.java
paimon-format/src/main/java/org/apache/parquet/hadoop/ParquetFileReader.java
paimon-format/src/main/java/org/apache/parquet/internal/filter2/columnindex/ColumnIndexFilter.java
paimon-format/src/main/java/org/apache/parquet/internal/filter2/columnindex/RowRanges.java

Support using file index result to filter row ranges.
org.apache.paimon.table.AppendOnlyFileStoreTableTest#testBitmapIndexResultFilterParquetRowRanges
No.
No.

[parquet] Support using file index result to filter row ranges

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
paimon-core/src/test/java/org/apache/paimon/schema/SchemaValidationTest.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireTest.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireWithMillisecondTest.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireWithTimestampLTZTest.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireWithTimestampTest.java

Add schema validation for record-level.time-field
Linked issue: close #4724

[core]Add schema validation for record-level.time-field

---

paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaActionITCaseBase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaDebeziumAvroSyncTableActionITCase.java

Remove the loggingTimer, it has the thread-safe problem and will cause the build to fail. It just prints some logs periodically and doesn't do anything else.
See https://github.com/apache/paimon/actions/runs/12517312341/job/34917869427
```text
Error: Exception in thread "Debug Logging Timer" java.lang.RuntimeException: Failed to execute logging action
at org.apache.paimon.flink.action.cdc.kafka.KafkaActionITCaseBase$2.run(KafkaActionITCaseBase.java:206)
at java.util.TimerThread.mainLoop(Timer.java:555)
at java.util.TimerThread.run(Timer.java:505)
Caused by: java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2491)
at …
```

[test] Remove the loggingTimer to fix the CDC build error

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/HiveCatalogTest.java

[hive] Fix listTablesImpl possible timeout issue

---

docs/content/maintenance/manage-branches.md

[doc] Add a comment to the delete branch operation to explain its behavior

---

paimon-core/src/test/java/org/apache/paimon/table/AppendOnlyFileStoreTableTest.java
paimon-format/src/main/java/org/apache/parquet/hadoop/ParquetFileReader.java
paimon-format/src/main/java/org/apache/parquet/internal/filter2/columnindex/ColumnIndexFilter.java
paimon-format/src/main/java/org/apache/parquet/internal/filter2/columnindex/RowRanges.java

Fix #4780 filter row ranges missing rowgroup offset.

[parquet] Fix file index result filter the row ranges missing rowgroup offset problem

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/PurgeFilesProcedure.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/PurgeFilesProcedureTest.scala

PurgeFileProcedure in spark not refresh catalog and this would lead to FileNotFound because of catalog cache, user need start a new spark job or session to avoid it, this pr is aim to fix it.
error as:
```
java.io.FileNotFoundException: File '/spark-6341d25d-5b46-414e-983f-0c606a3a8866/test.db/T/bucket-0/data-00564938-11af-44dd-8337-85787c7e3e14-0.parquet' not found, Possible causes: 1.snapshot expires too fast, you can configure 'snapshot.time-retained' option with a larger value. 2.consumption is too slow, you can improve the performance of consumption (For example, increasing parallelism).
at org.apache.paimon.utils.FileUtils.checkExists(FileUtils.java:113)
at org.apache.paimon.io.DataFileRecordReader.<init>(DataFileRecordReader.java:55)
at …
```

[spark] Purge file need refresh table avoid FileNotFound

---

paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergOptions.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/iceberg/IcebergHiveMetadataCommitter.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/iceberg/IcebergHiveMetadataCommitterITCaseBase.java

Linked issue: close #4810
Add Iceberg database / table options as alias when generating Iceberg metadata.
1. IcebergHiveMetadataCommitterITCaseBase
This change does not affect API or storage format

[Iceberg]Add Iceberg database / table options as alias when generating Iceberg metadata

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionITCaseBase.java

https://github.com/apache/paimon/actions/runs/12586476279/job/35094352733?pr=4820
Sometimes the test will delete less files.

[hotfix] Fix flaky test testCleanWithBranch

---

docs/content/flink/procedures.md

Fix typo of create_tag procedure doc

[hotfix] Fix typo of create_tag procedure doc

---

paimon-common/pom.xml
paimon-common/src/main/resources/META-INF/NOTICE

Upgrade the RoaringBitmap version from 1.0.5 to 1.2.1, in order to fix some bug.
For example: 
* https://github.com/RoaringBitmap/RoaringBitmap/pull/722
* https://github.com/RoaringBitmap/RoaringBitmap/pull/724
* https://github.com/RoaringBitmap/RoaringBitmap/pull/736
* https://github.com/RoaringBitmap/RoaringBitmap/pull/739

[common] Upgrade the RoaringBitmap version from 1.0.5 to 1.2.1

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/execution/PaimonStrategy.scala

```sql
--conf spark.sql.catalog.spark_catalog=org.apache.paimon.spark.SparkGenericCatalog \
--conf spark.sql.extensions=org.apache.paimon.spark.extensions.PaimonSparkSessionExtensions \
```
```sql
ALTER TABLE test_paimon_v1 CREATE TAG `TAG-1`
```
```
java.lang.AssertionError: assertion failed: No plan for Create tag: TAG-1 for table: ArrayBuffer(test_paimon_v1)
```

[spark] SparkGenericCatalog support tag DDL

---

paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java

when commit change log set overwrite file as true

[Bug] overwrite is true when commit change log

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
paimon-core/src/test/java/org/apache/paimon/catalog/PrimaryKeyTableTestBase.java
paimon-core/src/test/java/org/apache/paimon/schema/SchemaValidationTest.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireTest.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireWithMillisecondTest.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireWithTimestampBaseTest.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireWithTimestampLTZTest.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireWithTimestampTest.java

Linked issue: close #4821 
We should not enforce not nullable check for record-level.time-field for two reasons:
1, When creating paimon tables using  Spark SQL or Hive SQL, users cannot specify certain fields are not nullable;
2, In certain cases like #4821, Paimon writer will inevitably write null time field into data files. Not nullable datatype will cause parquet reader fail with following msgs:

[core] remove nullable check for record-level.time-field

---

docs/content/flink/sql-write.md
docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/partition/actions/PartitionMarkDoneAction.java
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/MarkPartitionDoneProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MarkPartitionDoneAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/MarkPartitionDoneProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionListeners.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionMarkDone.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/MarkPartitionDoneActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/CustomPartitionMarkDoneActionTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/MockCustomPartitionMarkDoneAction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/PartitionMarkDoneTest.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/MarkPartitionDoneProcedure.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/WriteIntoPaimonTable.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/MarkPartitionDoneProcedureTest.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/MockCustomPartitionMarkDoneAction.scala

[core] Support customize action for partition mark done.

---

docs/content/cdc-ingestion/mysql-cdc.md

When I used the mysql-cdc-connector to form my data pipeline, I found that some dependencies is different,so I want to upplement the documentation for mysql-cdc.
**docs/content/cdc-ingestion/mysql-cdc.md**
cc @JingsongLi .Please take a look,Thanks!

[hotfix] [docs] Improving the mysql-cdc.md usage Documentation

---

paimon-core/src/main/java/org/apache/paimon/io/RecordLevelExpire.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireWithAggregationTest.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireWithMillisecondTest.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireWithTimestampBaseTest.java

Return true for RecordLevelExpire reader filter when time field is null.
Linked issue: close #4821 
RecordLevelExpireWithNullFieldTest

[core] support null value for record-level.time-field

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MergeIntoAction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/MergeIntoActionITCase.java

Linked issue: close #4845 
[flink][action] add '`' to the fields of merge into action to avoid exceptions when the field name is an SQL keyword.
- `org.apache.paimon.flink.action.MergeIntoActionITCase#testSqlWithKeywordCase`
No.
No.

 [flink][action] add '`' to the fields of merge into action to avoid exceptions when the field name is an SQL keyword.

---

paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java

Fix `incremental-between` when then snapshot id reference snapshot file has deleted bug

[Bug] use snapshot when SnapshotReaderImpl.toChangesPlan

---

paimon-common/src/main/java/org/apache/paimon/casting/ArrayToStringCastRule.java
paimon-common/src/main/java/org/apache/paimon/casting/CastExecutors.java
paimon-common/src/main/java/org/apache/paimon/casting/MapToStringCastRule.java
paimon-common/src/main/java/org/apache/paimon/casting/RowToStringCastRule.java
paimon-common/src/test/java/org/apache/paimon/casting/CastExecutorTest.java

Introduce nested type cast to string. For example, it can be used for partition cast in system table

[core] Introduce nested type cast to string

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FullCacheLookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/NoPrimaryKeyLookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PrimaryKeyLookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/SecondaryIndexLookupTable.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/LookupTableTest.java

If we use dynamic partition loader, it may reopen the LookupTable after partition changed. After reopen, the refresh executor is shutdown, we should recreate the executor in the open phase.

[flink] Fix the refresh executor not work after reopen

---

docs/content/cdc-ingestion/mysql-cdc.md

Fix some typo and add a three-level catalogue.

[hotfix] [doc] Fix some typo and add a three-level catalogue

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/tag/TagPeriodHandler.java
paimon-core/src/test/java/org/apache/paimon/table/system/CustomDurationTagsTableTest.java
paimon-core/src/test/java/org/apache/paimon/table/system/PeriodDurationTagsTableTest.java

Currently auto create tag only can be set with fixed hour or day and can not specify a custom duration，such as user want to create tag every 30min，this pr is aim to support it.
CustomDurationTagsTableTest

[core] Support auto create tag with custom duration

---

paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/SupportsRowLevelOperationFlinkTableSink.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java

[flink] Flink batch delete supports partial-update.remove-record-on-sequence-group option

---

paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/CachingCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/CatalogUtils.java
paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java
paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreScan.java
paimon-core/src/main/java/org/apache/paimon/operation/ManifestsReader.java
paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/table/FallbackReadFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/source/AbstractDataTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/InnerTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReader.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/HiveCatalogTest.java

At present, we have scattered many methods in `MetastoreClient`, and we should provide unified support for all of them on the Catalog interface.
1. Only introduce batch methods to reduce complex.
2. Tag to partition table should be handled too.
This is the first PR for removing `MetastoreClient`. This PR just introduce methods in Catalog.

[core] Introduce batch partition methods in catalog

---

paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java
paimon-core/src/main/java/org/apache/paimon/utils/FileStorePathFactory.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedureTest.scala

Fix remove orphan files with data file path directory

[core] Fix remove orphan files with data file path directory

---

paimon-core/src/main/java/org/apache/paimon/privilege/FileBasedPrivilegeManagerLoader.java
paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegeManagerLoader.java
paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedCatalog.java
paimon-core/src/test/java/org/apache/paimon/privilege/PrivilegedCatalogTest.java

[core] Introduce PrivilegeManagerLoader to avoid hardcode FileBasedPrivilegeManager

---

paimon-common/src/main/java/org/apache/paimon/types/DataTypeJsonParser.java
paimon-common/src/main/java/org/apache/paimon/types/RowType.java
paimon-core/src/test/java/org/apache/paimon/schema/DataTypeJsonParserTest.java

As part of #4471, in order to support variant shredding, we need a way to indicate which fields require shredding. To reuse the code, we utilize the existing RowType JSON parser. 
E.g. If we want to shred field v with age int and city string, we can create table like this:
```sql
CREATE TABLE T (v VARIANT)
TBLPROPERTIES (
'fields.v.shredding-schema' = '{"type":"ROW","fields":[{"name":"age","type":"INT"},{"name":"city","type":"STRING"}]}'
)
```
To reduce user conf, support parsing row type json without field id

[core] Support parsing row type json without field id

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
paimon-flink/paimon-flink-common/src/test/resources/log4j2-test.properties

Add logs about join keys and join results when performing lookup join in `DEBUG` mode.

[log] logging specific join keys and results  for lookup join

---

paimon-flink/paimon-flink-cdc/pom.xml
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/debezium/DebeziumBsonDataFormat.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/debezium/DebeziumBsonDataFormatFactory.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/debezium/DebeziumBsonRecordParser.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/debezium/DebeziumJsonRecordParser.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/BsonValueConvertor.java
paimon-flink/paimon-flink-cdc/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory

Linked issue: open [#4615](https://github.com/apache/paimon/issues/4615)

[flink] Supports debezium-bson format of kafka which collected from mongodb via debezium

---

paimon-core/src/main/java/org/apache/paimon/metrics/MetricGroupImpl.java
paimon-core/src/main/java/org/apache/paimon/schema/TableSchema.java
paimon-core/src/test/java/org/apache/paimon/schema/TableSchemaTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/metrics/FlinkMetricGroup.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java

Exception:
```
java.lang.StackOverflowError: null
at java.util.Collections$UnmodifiableMap.get(Collections.java:1456) ~[?:1.8.0_372]
at java.util.Collections$UnmodifiableMap.get(Collections.java:1456) ~[?:1.8.0_372]
at java.util.Collections$UnmodifiableMap.get(Collections.java:1456) ~[?:1.8.0_372]
at java.util.Collections$UnmodifiableMap.get(Collections.java:1456) ~[?:1.8.0_372]
at java.util.Collections$UnmodifiableMap.get(Collections.java:1456) ~[?:1.8.0_372]
at java.util.Collections$UnmodifiableMap.get(Collections.java:1456) ~[?:1.8.0_372]
at java.util.Collections$UnmodifiableMap.get(Collections.java:1456) ~[?:1.8.0_372]
at java.util.Collections$UnmodifiableMap.get(Collections.java:1456) ~[?:1.8.0_372]
at java.util.Coll
```
`AbstractFileStoreTable.copyWithLatestSchema` may introduce too …

[core] Do not use Collections.unmodifiableMap to avoid stack overflow

---

paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/InsertOverwriteTableTestBase.scala

Now , [this bug ](https://github.com/apache/paimon/issues/4785)is fixed ,Maybe we should consider removing the useless comment.

[hotfix] remove the useless comment

---

paimon-core/src/main/java/org/apache/paimon/catalog/CachingCatalog.java

Fix invalidate tables with same tableNames in other db issue when dropTable in CachingCatalog

[core] Fix invalidate tables with same tableNames in other db issue

---

docs/content/flink/sql-write.md
docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/partition/actions/HttpReportMarkDoneAction.java
paimon-core/src/main/java/org/apache/paimon/partition/actions/HttpReportMarkDoneException.java
paimon-core/src/main/java/org/apache/paimon/partition/actions/PartitionMarkDoneAction.java
paimon-core/src/main/java/org/apache/paimon/rest/HttpClient.java
paimon-core/src/test/java/org/apache/paimon/rest/HttpClientTest.java
paimon-core/src/test/java/org/apache/paimon/rest/TestHttpWebServer.java
paimon-flink/paimon-flink-common/pom.xml
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/MarkPartitionDoneActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/CustomPartitionMarkDoneActionTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/HttpReportMarkDoneActionTest.java

In order to coordinate the scheduling of real-time data and offline data, we provide an online web service to receive table partition completion information from the real-time application (flink).
When the real-time program completes writing to a partition, `http-report` action will report the partition to the remote service, when the online service receives the partition done request, it immediately calls the downstream associated offline job.
Compared with other actions, `http-report` action is more time-sensitive and does not require polling or blocking to wait for partitioning to complete. It is passive.

[core] Add a http-report action to reporting partition done to remote servers.

---

paimon-core/src/main/java/org/apache/paimon/rest/HttpClient.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTObjectMapper.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/GetDatabaseResponse.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/GetTableResponse.java
paimon-core/src/test/java/org/apache/paimon/rest/HttpClientTest.java
paimon-core/src/test/java/org/apache/paimon/rest/MockRESTMessage.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTest.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTObjectMapperTest.java
paimon-core/src/test/java/org/apache/paimon/rest/TestHttpWebServer.java
paimon-open-api/rest-catalog-open-api.yaml
paimon-open-api/src/main/java/org/apache/paimon/open/api/RESTCatalogController.java

1. Table name should be added in `GetTableResponse`, for example, get bundle tables should return `List<GetTableResponse>`.
2. path should be removed, because it should be in options.
3. Add id to table and database.

[rest] Add name to GetTableResponse and remove path

---

paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetFileFormat.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetReaderFactory.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetSchemaConverter.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ParquetSplitReaderUtil.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/writer/ParquetRowDataBuilder.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetReadWriteTest.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetSchemaConverterTest.java

Subtask of #4471, to support shredding, we need a way to convert from Parquet type to Paimon type.

[core] Introduce conversion from parquet type to paimon type

---

paimon-core/src/main/java/org/apache/paimon/operation/LocalOrphanFilesClean.java
paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/RemoveOrphanFilesProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RemoveOrphanFilesProcedure.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedure.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/orphan/SparkOrphanFilesClean.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedureTest.scala

Empty directories can not be cleaned after executing `remove_orphan_files`.

[spark] Clean empty directory after removing orphan files

---

docs/content/engines/doris.md

The Doris website has been upgraded so the link to Doris Paimon Catalog is missing. Update to the new link.

[docs] update link about Apache Doris

---

docs/content/flink/procedures.md
docs/content/spark/procedures.md
paimon-core/src/main/java/org/apache/paimon/operation/ListUnexistingFiles.java
paimon-core/src/test/java/org/apache/paimon/operation/ListUnexistingFilesTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RemoveUnexistingFilesAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RemoveUnexistingFilesActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RemoveUnexistingFilesProcedure.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RemoveUnexistingFilesActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/RemoveUnexistingFilesProcedureITCase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkProcedures.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedure.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RemoveUnexistingFilesProcedure.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/procedure/SparkOrphanFilesClean.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/procedure/SparkRemoveUnexistingFiles.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/RemoveUnexistingFilesProcedureTest.scala
paimon-spark/pom.xml

This PR adds an action/procedure to remove unexisting files from manifests. It has the following use cases:
* There is currently a known case when unexisting data file might be written into manifest. Consider a write-only job (W) plus a dedicated compaction job (C):
1. W commits a snapshot with file F. Then W constantly fails and restarts, each time before we can retry the commit (or W is stopped, creating Flink savepoint S).
2. C compacts F into a larger file, so F is now deleted from the manifest.
3. Before the compact snapshot expires, but after all snapshots created by W expires, W comes back to normal (or restarted from savepoint S). As W cannot find its previous snapshot, it assumes that this snapshot has not been committed, so file F is committed to the manifest once again.
4. When …

[flink] Add a action/procedure to remove unexisting files from manifests

---

paimon-common/src/main/java/org/apache/paimon/options/Options.java
paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/CatalogUtils.java
paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/TableMetadata.java
paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/table/object/ObjectTable.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-core/src/test/java/org/apache/paimon/rest/TestRESTCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveTableUtils.java
paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/HiveCatalogTest.java

Loading table logicals were in `RESTCatalog` and `AbstractCatalog` and `HiveCatalog`, we can unify them to one class util.

[core] Extract loadTable in CatalogUtils

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java

We forbid to set agg function for sequence group fields, but default agg won't be detected, so the sequence group fields might be aggregated by default agg.

[core] Fix that sequence group fields are mistakenly aggregated by default aggregator in partial update

---

paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/CatalogUtils.java
paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Identifier.java
paimon-core/src/main/java/org/apache/paimon/catalog/RenamingSnapshotCommit.java
paimon-core/src/main/java/org/apache/paimon/catalog/SnapshotCommit.java
paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalog.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommit.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
paimon-core/src/main/java/org/apache/paimon/operation/PartitionExpire.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTSnapshotCommitFactory.java
paimon-core/src/main/java/org/apache/paimon/rest/ResourcePaths.java
paimon-core/src/main/java/org/apache/paimon/rest/requests/CommitTableRequest.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/CommitTableResponse.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/CatalogEnvironment.java
paimon-core/src/main/java/org/apache/paimon/table/sink/TableCommitImpl.java
paimon-core/src/test/java/org/apache/paimon/operation/PartitionExpireTest.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java
paimon-open-api/rest-catalog-open-api.yaml
paimon-open-api/src/main/java/org/apache/paimon/open/api/RESTCatalogController.java

For `RESTCatalog`, it has no lock implementation, so for multiple jobs committing, we should abstract `SnapshotCommit` interface:
```java
/** Interface to commit snapshot atomically. */
public interface SnapshotCommit extends AutoCloseable {
boolean commit(Snapshot snapshot, String branch) throws Exception;
/** Factory to create {@link SnapshotCommit}. */
interface Factory extends Serializable {
SnapshotCommit create(Identifier identifier, SnapshotManager snapshotManager);
}
}
```
- For non-RESTCatalog, just be `RenamingSnapshotCommit` to be compatible to history implementation.
- And for RESTCatalog, it submits `CommitTableRequest` to REST server to do single thread committing.
And for Schema changing, we don't really the lock, all schema changes happened in Catalog, we can lock them in …

[core] Introduce SnapshotCommit to abstract atomically commit

---

docs/content/maintenance/rescale-bucket.md

[hotfix] [doc] fix the url link in document

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/postgres/PostgresRecordParser.java

Fixed the type conversion method.

[hotfix] Minor fix the int parsing in PostgresRecordParser

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PrimaryKeyFileStoreTableITCase.java

In this PR, we fix the unstable random tests in `PrimaryKeyFileStoreTableITCase` by using a large number of rows to mimic unbounded streams because there is a known consistency issue in bounded streams.
For bounded streams, if COMPACT snapshot fails to commit when the stream ends (due to conflict or whatever reasons), we have no chance to modify the compaction result, so the changelogs produced by compaction will not be committed.
If it happens in production, users can run another job to compact the table, or run another job to write more data into the table. These remaining changelogs will be produced again.

[test] Fix the unstable random tests in PrimaryKeyFileStoreTableITCase

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/PickFilesForCloneOperator.java

`testCloneWithSchemaEvolution` is an unstable test, because the target table is created in `PickFilesForCloneOperator`, but its latest schema file might be overwritten concurrently in `CopyFileOperator`, and at that time target table can't be retrieved from the catalog.
This PR fixes the issue by copying the latest schema file in `PickFilesForCloneOperator`, so it will never be overwritten.
IT cases.

[test] Fix the unstable testCloneWithSchemaEvolution

---

docs/content/spark/auxiliary.md

[hotfix] [doc] Add quotes to the partition

---

paimon-core/src/main/java/org/apache/paimon/rest/ExponentialHttpRetryInterceptor.java
paimon-core/src/main/java/org/apache/paimon/rest/HttpClient.java
paimon-core/src/main/java/org/apache/paimon/rest/HttpClientOptions.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalogOptions.java
paimon-core/src/test/java/org/apache/paimon/rest/ExponentialHttpRetryInterceptorTest.java
paimon-core/src/test/java/org/apache/paimon/rest/HttpClientTest.java

Support define max connections and retry when failing for RESTCatalog client
Linked issue: #4540
- ExponentialHttpRetryInterceptorTest
- HttpClientTest.testRetry

Add http conf and ExponentialHttpRetryInterceptor to handle retry In RESTCatalog

---

paimon-common/src/main/java/org/apache/paimon/fs/FileIO.java
paimon-common/src/main/java/org/apache/paimon/fs/FileStatusIterator.java
paimon-common/src/main/java/org/apache/paimon/fs/RemoteIterator.java
paimon-common/src/test/java/org/apache/paimon/fs/FileIOTest.java

Linked issue: close #4791
Proposing `FileIO#listFilesPaged` and its non-iterative sibling `FileIO#listFiles` .
* `FileIOTest#testListFiles`
* ~`FileIOTest#testListFilesPaged`~
Adding `listFilesPaged` method to `FileIO` interface.
As described in the methods' JavaDocs.

[common] A FileIO API to list files iteratively

---

paimon-core/src/main/java/org/apache/paimon/iceberg/AbstractIcebergCommitCallback.java
paimon-core/src/main/java/org/apache/paimon/io/DataFilePathFactory.java
paimon-core/src/main/java/org/apache/paimon/operation/FileDeletionBase.java
paimon-core/src/main/java/org/apache/paimon/operation/LocalOrphanFilesClean.java
paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java
paimon-core/src/main/java/org/apache/paimon/operation/TagDeletion.java
paimon-core/src/test/java/org/apache/paimon/TestFileStore.java
paimon-core/src/test/java/org/apache/paimon/operation/ExpireSnapshotsTest.java
paimon-core/src/test/java/org/apache/paimon/operation/LocalOrphanFilesCleanTest.java
paimon-flink/paimon-flink-common/pom.xml
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/ExpireTagsActionTest.java

Due to the introduction of an external path[1], the data file may not exist in the warehouse path,
so the expire function needs to be refactored.
This job is a part of this job[2]
[1] https://github.com/apache/paimon/pull/4751
[2] https://cwiki.apache.org/confluence/display/PAIMON/PIP-29%3A+Introduce+Table+Multi-Location++Management
Refactor the LocalOrphanFilesCleanTest

[Core]Refactor the orphan clean and expire function

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PrimaryKeyFileStoreTableITCase.java

In #4933 we fix unstable IT cases in `PrimaryKeyFileStoreTableITCase` by mimicing unbounded streams with lots of records. However `testNoChangelogProducerStreamingRandom` will wait for the job to finish and then start checking result, so it is now prone to time out.
This PR fixes the unstable test by checking the result as soon as enough record is written into Paimon.

[test] Fix the unstable testNoChangelogProducerStreamingRandom

---

docs/layouts/shortcodes/generated/flink_connector_configuration.html
paimon-flink/paimon-flink-1.15/src/main/java/org/apache/paimon/flink/source/DataTableSource.java
paimon-flink/paimon-flink-common/pom.xml
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/AbstractFlinkTableFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/BaseDataTableSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/DataTableSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkTableSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/SystemTableSource.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java

We need to introduce the pattern of running bounded reads in stream jobs, which is useful in certain application scenarios, such as broadcasting a Paimon table to the stream operator.
`BatchFileStoreITCase.testScanBounded`

[flink] Introduce scan bounded to force bounded in streaming job

---

docs/content/concepts/spec/fileindex.md
docs/content/concepts/spec/tableindex.md

Fix the typo of `BIT_ENDIAN` to `BIG_ENDIAN`
N/A
N/A
N/A

[docs] Fix typo of BIG_ENDIAN

---

paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/RenamingSnapshotCommit.java
paimon-core/src/main/java/org/apache/paimon/operation/Lock.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java

After #4911 , the `LockFactory` is not used any more.

[refactor] Clean unused codes in Lock

---

paimon-core/src/main/java/org/apache/paimon/io/CompactIncrement.java
paimon-core/src/main/java/org/apache/paimon/io/DataIncrement.java
paimon-core/src/main/java/org/apache/paimon/io/IndexIncrement.java

Linked issue: close #4938
* Include `deletedFiles` in `DataIncrement#toString`
* Unifying `toString` format of `DataIncrement`, `CompactIncrement` and `IndexIncrement` to formatting `List`s of file names, inlined and spaces around equal sign
N/A
N/A
N/A

refine CommitMessage toString

---

paimon-core/src/main/java/org/apache/paimon/table/ExpireSnapshotsImpl.java
paimon-core/src/main/java/org/apache/paimon/table/RollbackHelper.java
paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/SnapshotHintOperator.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/RollbackProcedureTest.scala

Clear cache when deleting the snapshot
```sql
CREATE TABLE T (id INT);
NSERT INTO T VALUES (1), (2), (3), (4);
DELETE FROM T WHERE id = 1;
CALL sys.rollback(table => 'T', version => '1');
DELETE FROM T WHERE id = 1;
SELECT * FROM T ORDER BY id;
```
```
Job aborted due to stage failure: Task 1 in stage 9.0 failed 1 times, most recent failure: Lost task 1.0 in stage 9.0 (TID 9) (30.221.116.223 executor driver): java.io.FileNotFoundException: File '/private/var/folders/px/y3gybll50ggctcjp2t4r2b500000gp/T/spark-5b259941-137d-4736-968a-5b61e456898a/test.db/T/bucket-0/data-e9507592-0884-457f-86d1-fbfc996225b2-0.parquet' not found, Possible causes: 1.snapshot expires too fast, you can configure 'snapshot.time-retained' option with a larger value. 2.consumption is too slow, you can improve the …
```

[core] Clear cache when deleting the snapshot

---

docs/content/migration/iceberg-compatibility.md
docs/layouts/shortcodes/generated/iceberg_configuration.html
paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergOptions.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/iceberg/IcebergHiveMetadataCommitter.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/iceberg/IcebergHiveMetadataCommitterITCaseBase.java

Paimon's Iceberg compatibility layer [suggests](https://paimon.apache.org/docs/1.0/migration/iceberg-compatibility/#:~:text=Note%3A%20You%20can%20use%20this%20repo%20to%20build%20the%20required%20jar%2C%20include%20it%20in%20your%20path%20and%20configure%20the%20AWSCatalogMetastoreClient.) using https://github.com/promotedai/aws-glue-data-catalog-client-for-apache-hive-metastore to connect to AWS Glue catalog. This AWS Glue client package supports skipping Glue archive, however, Paimon is never skipping archive when using that client.
Linked issue: close #4967
Added the new option in the test for table options.
The default behavior has not changed in this PR. By default, skip-archive is false.
It is worth noting that in Iceberg the default is true …

[iceberg] Support skipping AWS Glue archive

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionFactory.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/RemoveOrphanFilesActionITCaseBase.java

[hotfix] remove_orphan_files action shouldn't check table argument (table=null means clean whole database)

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldCollectAgg.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/FieldMergeMapAgg.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java

[core] Fix NPE when retracting collect and merge-map

---

README.md

[hotfix] [doc] Update the maven version requirements in the readme

---

docs/content/spark/sql-query.md
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonQueryTest.scala

[doc][spark] Add read metadata columns

---

paimon-common/src/main/java/org/apache/paimon/fs/hadoop/HadoopFileIO.java
paimon-common/src/test/java/org/apache/paimon/fs/FileIOBehaviorTestBase.java
paimon-filesystems/paimon-oss-impl/src/main/java/org/apache/paimon/oss/HadoopCompliantFileIO.java
paimon-filesystems/paimon-s3-impl/src/main/java/org/apache/paimon/s3/HadoopCompliantFileIO.java

Linked issue: close #4951 
Take advantage of OSS's native batched list API to provide an optimized implementation of listFilesIterative for OSS.
None.
(I can't seem to find any existing tests for various `FileIO`s.)
N/A
N/A

Optimized iterative list implementations

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java
paimon-core/src/main/java/org/apache/paimon/iceberg/migrate/IcebergMigrateHadoopMetadata.java
paimon-core/src/main/java/org/apache/paimon/iceberg/migrate/IcebergMigrateHadoopMetadataFactory.java
paimon-core/src/main/java/org/apache/paimon/iceberg/migrate/IcebergMigrateMetadataFactory.java
paimon-core/src/main/java/org/apache/paimon/iceberg/migrate/IcebergMigrator.java
paimon-core/src/main/java/org/apache/paimon/operation/LocalOrphanFilesClean.java
paimon-core/src/main/java/org/apache/paimon/operation/OrphanFilesClean.java
paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/RemoveOrphanFilesProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RemoveOrphanFilesAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/CopyFileOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/orphan/FlinkOrphanFilesClean.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RemoveOrphanFilesProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/privilege/InitFileBasedPrivilegeProcedure.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedure.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/procedure/SparkOrphanFilesClean.scala

RESTCatalog does not have FileIO for catalog. We should remove this.
The side effect of this PR is that PrivilegedCatalog only supports AbstractCatalog, which is acceptable because REST Catalog has its own permission system.

[core] Remove Catalog.fileio method

---

paimon-core/src/main/java/org/apache/paimon/catalog/CatalogUtils.java
paimon-core/src/test/java/org/apache/paimon/table/FallbackReadFileStoreTableTest.java

When calling listPartitions interface, it may occurs ArrayIndexOutOfBoundsException.
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at org.apache.paimon.utils.InternalRowPartitionComputer.<init>(InternalRowPartitionComputer.java:64)
at org.apache.paimon.catalog.CatalogUtils.listPartitionsFromFileSystem(CatalogUtils.java:80)
at org.apache.paimon.catalog.AbstractCatalog.listPartitions(AbstractCatalog.java:198)
```
This PR fixs the problem.
added
no.
no.

[core] Fix listPartitions ArrayIndexOutOfBoundsException for release-1.0

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/AggregateMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/factory/FieldAggregatorFactory.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/aggregate/FieldAggregatorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PreAggregationITCase.java

[core] Fix that sequence fields are mistakenly aggregated by default aggregator in AggregateMergeFunction

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonRelation.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/UpdateTableTestBase.scala

```sql
CREATE TABLE T (id INT, s STRING, c CHAR(1));
INSERT INTO T VALUES (1, 's', 'a');
UPDATE T SET c = 'b' WHERE id = 1;
```
```
UPDATE TABLE is not supported temporarily.
org.apache.spark.SparkUnsupportedOperationException: UPDATE TABLE is not supported temporarily.
at org.apache.spark.sql.errors.QueryExecutionErrors$.ddlUnsupportedTemporarilyError(QueryExecutionErrors.scala:1089)
at org.apache.spark.sql.execution.SparkStrategies$BasicOperators$.apply(SparkStrategies.scala:935)
at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$1(QueryPlanner.scala:63)
```
Note that this PR actually ignores the `read side padding` in the `Project`, so if the char type is used and `spark.sql.legacy.charVarcharAsString` is set to true (default is false), and the char type is written in …

[spark] Fix update table with char type

---

docs/content/spark/procedures.md
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/RollbackProcedureTest.scala
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/RollbackProcedure.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/RollbackProcedureTest.scala

Rollback in spark currently cannot  correctly identify tag or snapshot, such as tag named with 20250122 would be handle as snapshot like:
Rollback snapshot '20250122' doesn't exist.
java.lang.IllegalArgumentException: Rollback snapshot '20250122' doesn't exist.
at org.apache.paimon.utils.Preconditions.checkArgument(Preconditions.java:149)
at org.apache.paimon.table.AbstractFileStoreTable.rollbackTo(AbstractFileStoreTable.java:572)
at org.apache.paimon.spark.procedure.RollbackProcedure.lambda$call$0(RollbackProcedure.java:74)
at org.apache.paimon.spark.procedure.BaseProcedure.execute(BaseProcedure.java:88)
at org.apache.paimon.spark.procedure.BaseProcedure.modifyPaimonTable(BaseProcedure.java:78)
at org.apache.paimon.spark.procedure.RollbackProcedure.call(RollbackPr …

[spark] Fix rollback not correctly identify tag or snapshot

---

paimon-core/src/main/java/org/apache/paimon/rest/DefaultErrorHandler.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/exceptions/NotImplementedException.java
paimon-core/src/test/java/org/apache/paimon/rest/DefaultErrorHandlerTest.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java

At present, our partition interface will be called twice, once to retrieve the table and once for the actual partition operation. In fact, we don't need to retrieve the table, we just need to let the server determine whether it is a partition table by itself.
This PR has also changed the exception name, `NotImplementedException` is less likely to conflict and better.

[rest] Optimize partition methods to let rest return table not partitioned

---

paimon-core/src/main/java/org/apache/paimon/table/object/ObjectRefresh.java

Linked issue: close #4971 
* Take advantage of iterative list to lower memory requirement.
* Commit object refresh entries in batches to improve performance.
Use existing tests `ObjectTableITCase` and `ObjectTableTest`.
N/A
N/A

[core] ObjectRefresh with iterative list and batched commit

---

docs/content/flink/procedures.md
docs/content/maintenance/manage-snapshots.md

[doc] Add sys prefix to procedure

---

paimon-common/src/main/java/org/apache/paimon/fs/FileStatus.java
paimon-core/src/main/java/org/apache/paimon/table/object/ObjectRefresh.java

Linked issue: close #4986
Populate all fields of object table.
Use existing `ObjectTableITCase` and `ObjectTableTest`.
Adding several getters for metadata to `FileStatus`. The new getters all defaults to null.
N/A

[common][core] Populate more metadata to object table

---

docs/content/cdc-ingestion/kafka-cdc.md
docs/content/cdc-ingestion/mongo-cdc.md
docs/content/cdc-ingestion/postgres-cdc.md
docs/content/cdc-ingestion/pulsar-cdc.md
docs/layouts/shortcodes/generated/kafka_sync_database.html
docs/layouts/shortcodes/generated/kafka_sync_table.html
docs/layouts/shortcodes/generated/mongodb_sync_database.html
docs/layouts/shortcodes/generated/mysql_sync_database.html
docs/layouts/shortcodes/generated/mysql_sync_table.html
docs/layouts/shortcodes/generated/postgres_sync_table.html
docs/layouts/shortcodes/generated/pulsar_sync_database.html
docs/layouts/shortcodes/generated/pulsar_sync_table.html
paimon-format/src/main/java/org/apache/orc/OrcConf.java

Fix cdc doc url and some typos.

[hotfix] [docs] Fix cdc doc url and some typos

---

paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalTagStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/TimeTravelUtil.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/plans/logical/PaimonTableValuedFunctions.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/TableValuedFunctionsTest.scala

[spark] Fallback to spark except query if increment query with rescale bucket

---

paimon-common/src/main/java/org/apache/paimon/data/columnar/ColumnarRowIterator.java
paimon-common/src/main/java/org/apache/paimon/data/columnar/VectorizedRowIterator.java
paimon-common/src/main/java/org/apache/paimon/utils/LongIterator.java
paimon-common/src/test/java/org/apache/paimon/utils/LongIteratorTest.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/newreader/ColumnarBatch.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/newreader/RowIndexGenerator.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/newreader/VectorizedParquetRecordReader.java

Improve performance, we should let rowIndexes to lazied.

[parquet] Introduce LongIterator to Parquet RowIndexGenerator

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/AppendOnlySingleTableCompactionWorkerOperatorTest.java

[test] [flink] Fix unstable test: AppendOnlySingleTableCompactionWorkerOperator should be closed

---

paimon-common/src/main/java/org/apache/paimon/fileindex/bitmap/BitmapFileIndexMeta.java
paimon-common/src/test/java/org/apache/paimon/fileindex/bitmapindex/TestBitmapFileIndex.java

Fix type bug when using Boolean in bitmap for file index. Current use byte will cause: 
`java.lang.ClassCastException：class java.lang.Boolean cannot be cast to class java.lang.Byte`
TestBitmapFileIndex.testBitmapIndexForBooleanType
NO
NO

[bug] Fix type bug when using Boolean in bitmap for file index

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/MigrateDatabaseProcedure.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/MigrateDatabaseProcedureTest.scala

```sql
CALL sys.migrate_database(source_type => 'hive', database => '$hiveDbName', options => 'file.format=$format')
```
```
java.lang.String cannot be cast to org.apache.spark.unsafe.types.UTF8String
java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.spark.unsafe.types.UTF8String
at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.getUTF8String(rows.scala:45)
at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.getUTF8String$(rows.scala:45)
at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.getUTF8String(rows.scala:165)
at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
at org.apache.spark.sql.execution.CommandResultExec.$anonfun$unsafeRows$1(CommandResultExec.scala …
```

[spark] Fix the result of migrate database procedure

---

docs/content/maintenance/filesystems.md

Simply fixes a small typo in the filesystem docs.

[filesystem] Fix typo in docs

---

docs/content/flink/clone-tables.md

Fix sys.clone doc demo: as the key must use `` not ''

[bug] Fix sys.clone doc demo

---

paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/utils/CatalogUtils.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DDLTestBase.scala

```sql
ALTER TABLE paimon.default.t1 RENAME TO paimon.default.t2;
```
```
Paimon only support single namespace, but got [paimon, default]
java.lang.IllegalArgumentException: Paimon only support single namespace, but got [paimon, default]
at org.apache.paimon.utils.Preconditions.checkArgument(Preconditions.java:149)
at org.apache.paimon.spark.utils.CatalogUtils.checkNamespace(CatalogUtils.java:31)
at org.apache.paimon.spark.utils.CatalogUtils.toIdentifier(CatalogUtils.java:38)
at org.apache.paimon.spark.SparkCatalog.renameTable(SparkCatalog.java:433)
```

[spark] Fix rename table with catalog name

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedAwareStreamingSource.java

[flink] change the name of MultiTablesReadOperator to avoid using same name with source

---

paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/PaimonScan.scala
paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/PaimonScanBuilder.scala
paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/PaimonSplitScanBuilder.scala
paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/catalyst/analysis/expressions/ExpressionHelper.scala
paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/sql/PaimonPushDownTest.scala
paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/paimon/spark/PaimonScan.scala
paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/spark/sql/internal/connector/PredicateUtils.scala
paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/PaimonPushDownTest.scala
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/PaimonPushDownTest.scala
paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/sql/PaimonPushDownTest.scala
paimon-spark/paimon-spark-4.0/src/test/scala/org/apache/paimon/spark/sql/PaimonPushDownTest.scala
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkFilterConverter.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScanBuilder.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScanBuilder.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonSplitScan.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkV2FilterConverter.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/expressions/ExpressionHelper.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/PaimonUtils.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonPushDownTestBase.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/SparkV2FilterConverterTestBase.scala

Support push down v2 filter
```scala
class PaimonScanBuilder extends SupportsPushDownV2Filters
class PaimonScan extends SupportsRuntimeV2Filtering
```

[spark] Support push down v2 filter

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SynchronizationActionBase.java

[bug] Avoid obtaining the wrong checkpoint configuration in the `SynchronizationAction`

---

paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java

Linked issue: close #5040 
```java
assertThat(meta.fileName().substring(meta.fileName().lastIndexOf(".") + 1))
.isEqualTo(CoreOptions.FILE_FORMAT_AVRO);
```
No change
No change

[test] Fix AppendOnlyWriterTest file format is error

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunctionTest.java

For example,
```
CREATE TABLE SG
(
pk   INT,
f0   INT,
g0   INT,
f1   INT,
g1   INT,
PRIMARY KEY (pk) NOT ENFORCED
) WITH (
'merge-engine' = 'partial-update',
'fields.g0.sequence-group' = 'f0',
'fields.f0.aggregate-function' = 'listagg',
'fields.f1.aggregate-function' = 'listagg'
);
```
The `f1` lack sequence-group but there's no exception.

[core] Check that all fields with aggregate functions in partial-update should be protected by sequence-group

---

paimon-core/pom.xml
paimon-core/src/main/java/org/apache/paimon/jdbc/DistributedLockDialectFactory.java
paimon-core/src/main/java/org/apache/paimon/jdbc/PostgresqlDistributedLockDialect.java
paimon-core/src/test/java/org/apache/paimon/jdbc/PostgresqlCatalogTest.java

Linked issue: close #4836
Currently lock.enabled is only supported my SQLLite and MySQL.  Adding support for Postgres.
The only difference between MySQL and Postgres is the `TIMESTAMPDIFF` function
In MySQL
`DELETE FROM paimon_distributed_locks WHERE TIMESTAMPDIFF(SECOND, acquired_at, NOW()) > expire_time_seconds and lock_id = ? `
In Postgres
`DELETE FROM paimon_distributed_locks WHERE EXTRACT(EPOCH FROM AGE(NOW(), acquired_at)) > expire_time_seconds and lock_id = ? `
`PostgresqlCatalogTest.java`. This uses TestContainers with `postgres:13-alpine` to run postgres inside docker.
No
Yes ,The doc at https://paimon.apache.org/docs/master/flink/sql-ddl/#creating-jdbc-catalog says
> Currently, lock configuration is only supported for MySQL and SQLite. If you are using a different type of …

[core] Support lock for postgres catalog (#4836)

---

paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergConversions.java
paimon-core/src/test/java/org/apache/paimon/iceberg/IcebergCompatibilityTest.java
paimon-core/src/test/java/org/apache/paimon/iceberg/manifest/IcebergConversionsVarcharTest.java

Paimon's Iceberg compatibility tables partitioned by a `string` field doesn't return any results when queried by an equality predicate on the partition field. 
- The snapshot file's partition summary lower and upper bounds have a null character suffix.
- The column stats in the manifest files also contain null character suffix.
The effect of these is clients skip all the data files for the Iceberg table during scan planning. See the linked issue for examples.
Linked issue: https://github.com/apache/paimon/issues/5007
- Added a new test case in `IcebergCompatibilityTest` to verify the snapshot metadata files no longer contain the `\u000` padding.
- Added extensive test cases for the `IcebergConversions` CHAR/VARCHAR case.
N/A
N/A

[iceberg] Improved ByteBuffer string conversion for Iceberg manifests

---

paimon-common/src/main/java/org/apache/paimon/utils/TypeUtils.java

Fix https://github.com/apache/paimon/issues/4920
Sinking cdc with map type, value surrouned with double quotes.
To prevent generating quotes, 
first check if value is text.
https://github.com/apache/paimon/issues/4920#issuecomment-2630112634

[core] TypeUtils: remove quotes of map value

---

paimon-core/src/main/java/org/apache/paimon/partition/actions/HttpReportMarkDoneAction.java
paimon-core/src/main/java/org/apache/paimon/partition/actions/PartitionMarkDoneAction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/MarkPartitionDoneActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/CustomPartitionMarkDoneActionTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/HttpReportMarkDoneActionTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/MockCustomPartitionMarkDoneAction.java

[core] Add open method to PartitionMarkDone for CustomPartitionMarkDone.

---

paimon-format/src/main/java/org/apache/paimon/format/parquet/newreader/ParquetVectorUpdaterFactory.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/newreader/VectorizedColumnReader.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetReadWriteTest.java

Fix lenth bytes to decimal type should be convert according to paimon decimal type scale.

[Parquet] Fix parquet decimal type match.

---

paimon-core/src/main/java/org/apache/paimon/KeyValue.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapper.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeFunction.java

We don't need two merge functions in one `LookupChangelogMergeFunctionWrapper `

[core] Slightly refatory code in LookupChangelogMergeFunctionWrapper

---

paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-common/src/main/java/org/apache/paimon/sort/zorder/ZIndexer.java
paimon-common/src/main/java/org/apache/paimon/sort/zorder/ZOrderByteUtils.java
paimon-common/src/test/java/org/apache/paimon/sort/zorder/TestZOrderByteUtil.java
paimon-core/src/test/java/org/apache/paimon/sort/zorder/ZIndexerTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/SortCompactAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/TableSortInfo.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sorter/TableSorter.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sorter/TableSortInfoTest.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/sort/SparkZOrderUDF.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/sort/TableSorter.java

Linked issue: close #5017 
Move order type enum class from spark/flink module to paimon which will be used for primary key table.
no
no
no

[Core] Add order type in paimon

---

paimon-core/src/main/java/org/apache/paimon/rest/RESTToken.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTTokenFileIO.java

C++ native engines can use this token to use C++ reader/writer to use data token from REST Server.

[core] Public RESTTokenFileIO.validToken for native engines to get the token

---

paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
paimon-core/src/test/java/org/apache/paimon/table/FileStoreTableTestBase.java

We encountered an exception in our production job.
After investigate this issue, the reason of this exception is :
We open `Changelog` decouple, the `Changelog` has records the `indexManifest`. But the `Snapshot` of the `Changelog` has been expired. So when read this `Changelog` will read the non-existed `indexManifest`.
We have think two functions to solve this problem.
1、 Don't read the `indexManifest` when streaming read the `Changelog`.
2、Override the `indexManifest` method in `Changelog`, which return null forever.
Due to the design of `Changelog` and `Tag` is extends `Snapshot`, they should not modify the field of `Snapshot`. So after discuss we choose the function 1.

[Core][Bug] Fix bug when read changelog's IndexManifest.

---

paimon-core/src/main/java/org/apache/paimon/iceberg/migrate/IcebergMigrateHadoopMetadata.java
paimon-core/src/test/java/org/apache/paimon/iceberg/migrate/IcebergMigrateHadoopMetadataTest.java
paimon-core/src/test/resources/META-INF/services/org.apache.paimon.fs.FileIOLoader

```
Path path =
new Path(
String.format(
"%s/%s/metadata",
icebergIdentifier.getDatabaseName(),
icebergIdentifier.getTableName()));
try {
fileIO = FileIO.get(path, CatalogContext.create(icebergOptions));
} catch (IOException e) {
throw new RuntimeException(e);
}
```
If obtain FileIO with the code below, it'll always get LocalFileIO because `path.toUri().getScheme() == null` will always be true. So we should use absolute warehouse path to get FileIO.
IcebergMigrateHadoopMetadataTest#testGetIcebergMetadataWithCustomFileIO

[iceberg][fix] obtain FileIO from the absolute warehouse path instead of relative table path

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/LocationHelper.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/StorageLocationHelper.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/TBPropertiesLocationHelper.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

Fix hive catalog create partitions using table location.

[hive]Fix hive catalog create partitions using table location.

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/AggregateMergeFunction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java

For example, for sequence fields 's0,s1', if input (null, 1), (1, null), the result will be (1, 1) currently which is wrong.

[core] Fix that AggregateMergeFunction handles multiple sequence fields mistakenly

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/WriteIntoPaimonTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/PaimonUtils.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DataFrameWriteTest.scala

[Spark] Allows data with missing columns to be written when enable 'merge-schema'

---

paimon-core/src/main/java/org/apache/paimon/Changelog.java
paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java

Linked issue: close #3479
This PR fixes a racing bug about earliest snapshot. When thread A is trying to get the earliest snapshot of a table, while the snapshot is being expired by thread B, thread A might throw exception that it cannot get the snapshot information from the earliest snapshot id.
This PR fixes the bug by adding retrying logic to seek the second earliest snapshot if the first one cannot be found.
Note that, theoretically speaking, any snapshot (including the latest one) could encounter this issue, but the probability is quite small, so this PR only fixes the bug for invocations on the earliest snapshot.
Tests in SnapshotManagerTest are used to verify against the changes.
This change does not introduce a new feature.

[core] Fix race condition for earliest snapshot

---

paimon-common/src/main/java/org/apache/paimon/utils/TypeUtils.java
paimon-common/src/test/java/org/apache/paimon/utils/TypeUtilsTest.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/postgres/PostgresSyncTableActionITCase.java

Linked issue: relates to #4920
Fix JSON text deserialization in ARRAYs and ROWs.
Added test cases for deserialization of JSON strings with different types of elements.
Before the change:
```
$ mvn -pl paimon-common -Dtest=org.apache.paimon.utils.TypeUtilsTest test
[...]
[ERROR] Failures:
[ERROR]   TypeUtilsTest.testArrayStringCastFromString:101
expected: org.apache.paimon.data.GenericArray@93cd27db
but was: org.apache.paimon.data.GenericArray@18d8f46e
[ERROR]   TypeUtilsTest.testCastFromString:71
expected: org.apache.paimon.data.GenericArray@6820ecbf
but was: org.apache.paimon.data.GenericArray@9f40b0f7
[ERROR]   TypeUtilsTest.testRowCastFromString:268
expected: +I(org.apache.paimon.data.GenericMap@9fb34a0d,value)
but was: +I(org.apache.paimon.data.GenericMap@9fb34a0d,"value")
[...]
``` …

[core] Fix JSON text deserialization in ARRAYs and ROWs

---

paimon-core/pom.xml
paimon-core/src/main/resources/META-INF/NOTICE

Relation pr : https://github.com/apache/paimon/pull/5044  (this pr can't be reopen because force push.)
When I used the partition mark done action of `http-report` : 
`java. lang.NoClassDefFoundError: okio/Options`
`java. lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics`
So we need to shade `okio-jvm` and `kotlin-stdlib`  too.

[core] Fix missing kotlin and okio dependencies when using okhttp3. 

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScanBuilder.scala

In follow two PRs, we introduce dropStats to optimize memory usage.
https://github.com/apache/paimon/pull/4506
https://github.com/apache/paimon/pull/4534
But in follow PR, it not call dropStats.
https://github.com/apache/paimon/pull/4709
So, this pr add call dropStats.

Add call dropStats when use spark read paimon

---

docs/content/spark/sql-functions.md
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/catalog/SupportFunction.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/catalog/functions/PaimonFunctions.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonPartitionManagement.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/ReplacePaimonFunctions.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/extensions/PaimonSparkSessionExtensions.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonFunctionTest.scala

Adds a new Spark function `max_pt`. It accpets a string type literal and return a max-valid-toplevel partition value.
- `valid` means the partition contains data files
- `toplevel` means only return the first partition value if the table has multi-partition columns
`max_pt` will throw exception when:
- the table is not a partitioned table
- the partitioned table does not have partition
- all of the partitions do not contains data files
This pr adds `max_pt` through spark v2 function catalog using a fake scalar function and then adds a rule to replace `max_pt` to a literal value during analysis.
Example:
```sql
SELECT max_pt('t')
=>
20250101
```
no
add `sql-functions` docs

[spark] Add max_pt function

---

paimon-flink/paimon-flink-1.15/src/main/java/org/apache/paimon/flink/utils/ParallelismUtils.java
paimon-flink/paimon-flink-1.16/src/main/java/org/apache/paimon/flink/utils/ParallelismUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcSinkBuilder.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSink.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/shuffle/RangeShuffle.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CombinedTableCompactorSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/DynamicBucketCompactSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/DynamicBucketSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkStreamPartitioner.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/UnawareBucketSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/index/GlobalDynamicBucketSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkSourceBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/ParallelismUtils.java

In Flink 1.17+, the parameter `parallelismConfigurable` is introduced to support specifying operator's initial parallelism while dynamically changing parallelism in some situations (like in AQE). This PR adds this parameter to Paimon Flink operators where parallelism does not affect correctness, and can be changed by Flink infra according to detailed needs.
Related PR: #4975
Flink batch execution mode enables AQE by default, so existing batch tests like BatchFileStoreITCase can verify the correctness of these changes.
This change does not introduce a new feature that needs documentation.

[flink] Support parallelismConfigurable

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSchemaUtils.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSyncTableAction.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongoDBSchemaITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/mongodb/MongodbSchemaITCase.java

Rename MongdbSchemaUtils to MongDBSchemaUtils, MongodbSchemaITCase to MongoDBSchemaITCase ,and make its naming standardised.

[hotfix] Rename MongdbSchemaUtils to MongDBSchemaUtils

---

docs/layouts/shortcodes/generated/orc_configuration.html
paimon-format/src/main/java/org/apache/paimon/format/OrcOptions.java
paimon-format/src/main/java/org/apache/paimon/format/orc/OrcFileFormat.java
paimon-format/src/main/java/org/apache/paimon/format/orc/OrcReaderFactory.java
paimon-format/src/main/java/org/apache/paimon/format/orc/filter/OrcSimpleStatsExtractor.java
paimon-format/src/main/java/org/apache/paimon/format/orc/reader/AbstractOrcColumnVector.java
paimon-format/src/main/java/org/apache/paimon/format/orc/reader/OrcTimestampColumnVector.java
paimon-format/src/main/java/org/apache/paimon/format/orc/writer/FieldWriterFactory.java
paimon-format/src/main/java/org/apache/paimon/format/orc/writer/RowDataVectorizer.java
paimon-format/src/test/java/org/apache/paimon/format/orc/OrcFormatReadWriteTest.java
paimon-format/src/test/java/org/apache/paimon/format/orc/OrcReaderFactoryTest.java

Linked issue: close #5066
OrcFormatReadWriteTest#testTimestampLTZWithLegacyWriteAndRead
OrcFormatReadWriteTest#testTimestampLTZWithNewWriteAndRead
OrcFormatReadWriteTest#testTimestampLTZWithNewWriteAndLegacyRead
OrcFormatReadWriteTest#testTimestampLTZWithLegacyWriteAndNewRead
orc-format

[core]  fix the timezone conversion for timestamp_ltz data_type in OrcFileFormat

---

paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java

This PR fixes earliestSnapshot test case failures.
* Improve earliestSnapshot retry number according to latest snapshot id
* Fix SnapshotManager#earlierThanTimeMills return value when earliest snapshot cannot be found
* Fix test case expected result according to invocation time.
SnapshotManagerTest

[hotfix] Fix earliestSnapshot stability

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkTableSource.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/DataTableSourceTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/SourceMetricsITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/util/ReadWriteTableTestUtil.java

default.parallelism is not working because scan.infer-parallelism is default true

[flink] Infer parallelism only in situation of parallelism is not set.

---

paimon-benchmark/paimon-micro-benchmarks/pom.xml
paimon-common/pom.xml
pom.xml

See https://github.com/apache/paimon/pull/4859

[pom] Fix RoaringBitmap dependency problem in partial building

---

docs/content/flink/sql-lookup.md
docs/layouts/shortcodes/generated/flink_connector_configuration.html
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/DynamicPartitionLoader.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PartitionLoader.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/StaticPartitionLoader.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/BaseDataTableSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkTableSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/SystemTableSource.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/FileStoreLookupFunctionTest.java

Lookup joins in streaming SQL is the same as normal joins in batch SQL. However, when specifying what partitions to scan in lookup joins, currently user can specify `max_pt()` through SQL hints to read the latest partition, without specifying a fixed partition. Such SQL hint is not supported in batch joins.
Paimon is a streaming-batch unified lake format. To also support streaming-batch unification in SQL, this PR introduces a new option `scan.partitions`, which accepts both `max_pt()` (in lookup joins) and fixed partitions (in all joins). Users only need to change the value of this option to specify different partitions for streaming and batch jobs, and they don't need to change SQL itself.

[flink] Support specifying what partitions to scan in Flink

---

docs/content/cdc-ingestion/kafka-cdc.md
docs/layouts/shortcodes/generated/kafka_sync_database.html

Just to refine the document for kafka_sync_database. Make it clearer on how to specify the relevant options.
No need.
No.

[cdc] Refine the document for kafka_sync_database.

---

paimon-core/src/main/java/org/apache/paimon/catalog/CatalogUtils.java
paimon-core/src/main/java/org/apache/paimon/table/DataTable.java
paimon-core/src/main/java/org/apache/paimon/table/FormatTable.java
paimon-core/src/main/java/org/apache/paimon/table/KnownSplitsTable.java
paimon-core/src/main/java/org/apache/paimon/table/Table.java
paimon-core/src/main/java/org/apache/paimon/table/system/AggregationFieldsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/AllTableOptionsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/BranchesTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/BucketsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/CatalogOptionsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/ConsumersTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/FilesTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/ManifestsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/OptionsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/PartitionsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/SchemasTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/SnapshotsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/StatisticTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/TableIndexesTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/TagsTable.java
paimon-core/src/test/java/org/apache/paimon/rest/TestRESTCatalog.java

In some cases, the computing engine needs to obtain FileIO to operate some files on its own, including metadata files and data files. Previously, the engine obtained FileIO by converting the table into a DataTable.
We can directly expose the Table FileIO interface.

[core] Introduce Table.fileIO interface to public fileIO to file operation

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/MigrateIcebergTableProcedure.java

Make `iceberg_options` argument required in MigrateIcebergTableProcedure(paimon-flink-common)

[iceberg][fix] make 'iceberg_options' required in procedure

---

docs/content/primary-key-table/data-distribution.md
docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/index/HashBucketAssigner.java
paimon-core/src/main/java/org/apache/paimon/index/PartitionIndex.java
paimon-core/src/main/java/org/apache/paimon/index/SimpleHashBucketAssigner.java
paimon-core/src/main/java/org/apache/paimon/table/sink/KeyAndBucketExtractor.java
paimon-core/src/test/java/org/apache/paimon/index/HashBucketAssignerTest.java
paimon-core/src/test/java/org/apache/paimon/index/SimpleHashBucketAssignerTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/HashBucketAssignerOperator.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/BucketProcessor.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala

In dynamic bucket mode, unlimited buckets lead to an unpredicable number of small files, which lead to stability problems. so we should support upper bound in dynamic bucket mode.
Linked issue: close #4942 
HashBucketAssignerTest
SimpleHashBucketAssignerTest
- Use new feature, Produce 3 buckets after inserting 12 rows
- Not use new feature, Produce 6 buckets after inserting 12 rows
docs/layouts/shortcodes/generated/core_configuration.html

[core] Support upper bound in dynamic bucket mode

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java

Pr https://github.com/apache/paimon/pull/5090 changed the type of `table` defined in constructor to `FileStoreTable`, so this pr specialized the type of `table` defined in `FileStoreLookupFunction` to `FileStoreTable`.

[refactor] specialize the type of table to FileStoreTable in FileStoreLookupFunction

---

paimon-core/src/main/java/org/apache/paimon/table/ReadonlyTable.java

Engines may call latestSnapshotId interface at table level, however when it comes to system table, it will throw an exception. I suppose it better to return empty now that the return value is an Optional.
no
no need

[core] Return empty instead of throwing exception when getting system table's latestSnapshotId

---

paimon-core/src/main/java/org/apache/paimon/table/source/splitread/IncrementalDiffSplitRead.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/TableValuedFunctionsTest.scala

Due to the possibility that the before files and after files may offset each other during incremental read, while there are also new deletes in after files, we cannot drop deletes when reading after files.
```
//            tag1                          tag2
// l0         f(+I 10001),f(+I 10002)       f(-D 999)
// l1
// l2
// l3
// l4                                       f(+I 10001,10002)
// l5         f(+I 1-10000)                 f(+I 1-10000)
// before files: f(+I 10001), f(+I 10002)
// after files:  f(-D 999),   f(+I 10001,10002)
```

[core] Fix incremental query with delete after minor compact

---

paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/TableWriterBenchmark.java
paimon-core/src/main/java/org/apache/paimon/KeyValueSerializer.java
paimon-core/src/main/java/org/apache/paimon/mergetree/SortBufferWriteBuffer.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/DeduplicateMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/FirstRowMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapper.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/AggregateMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyTableUtils.java
paimon-core/src/main/java/org/apache/paimon/utils/OffsetRow.java
paimon-core/src/test/java/org/apache/paimon/mergetree/SortBufferWriteBufferTestBase.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapperTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/SortMergeReaderTestBase.java
paimon-core/src/test/java/org/apache/paimon/operation/MergeFileSplitReadTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupChangelogWithAggITCase.java

Linked issue: close #5103
1. skip the copy process during the compaction, because the KeyValue of the same key are from the different reader, and will not read the next key, before the same key are all processed
2. copy the underlying BinaryRow directly for the sort write buffer
```
Apple M3 Pro
parquet:                                                                                             Best/Avg Time(ms)    Row Rate(K/s)      Per Row(ns)   Relative
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
OPERATORTEST_parquet_write                                                                              39571 / 39979             75.8          13190.3       1.0X
OpenJDK …
```

[core] Avoid the unnecessary key value copy

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/CatalogUtils.java
paimon-core/src/main/java/org/apache/paimon/catalog/TableMetadata.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/GetTableResponse.java
paimon-core/src/test/java/org/apache/paimon/rest/MockRESTMessage.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/TestRESTCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-open-api/rest-catalog-open-api.yaml
paimon-open-api/src/main/java/org/apache/paimon/open/api/RESTCatalogController.java

Add isExternal to REST GetTableResponse, isExternal can be used to distinguish data file io and more things. So it is neccessary to add an isExternal to table response.

[rest] Add isExternal to GetTableResponse

---

docs/content/migration/migration-from-hive.md
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ClearConsumerActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MigrateIcebergTableActionFactory.java

Adding line breaks to `migrate_iceberg_table` and `clear_consumers` action. Related PR [4878](https://github.com/apache/paimon/pull/4878), [4893](https://github.com/apache/paimon/pull/4893).

[hotfix] [doc] [action] Adding line breaks to action and fix document for migration

---

paimon-core/src/main/java/org/apache/paimon/table/FallbackReadFileStoreTable.java
paimon-core/src/test/java/org/apache/paimon/catalog/CachingCatalogTest.java

[core] Add manifest cache to the FallbackReadFileStoreTable

---

docs/content/maintenance/write-performance.md

When we use Flink job to run dedicated compaction with config of `cluster.fine-grained-resource-management.enabled: true` and `sink.committer-memory: 32G`, we receive the follow exception. This PR is add the solution of this question.
At the moment, fine-grained resource management requires batch workloads to be executed with types of all edges being BLOCKING. To do that, you need to configure 'fine-grained.shuffle-mode.all-blocking' to 'true'. Notice that this may affect the performance. See FLINK-20865 for more details.

[Doc] Modify ths doc of commit memory.

---

paimon-common/src/main/java/org/apache/paimon/data/GenericMap.java
paimon-common/src/main/java/org/apache/paimon/utils/InternalRowUtils.java
paimon-common/src/test/java/org/apache/paimon/utils/InternalRowUtilsTest.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/AbstractSparkInternalRow.java

The `AbstractSparkInternalRow` would be passed to Spark, so it is dangerous if it would throw exception when call equals or hashcode. This pr make it fallback to suport if there is an exception.
Pass CI
no
no

[spark] AbstractSparkInternalRow supports fallback equals and hashCode

---

paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/view/View.java
paimon-core/src/main/java/org/apache/paimon/view/ViewImpl.java
paimon-core/src/main/java/org/apache/paimon/view/ViewSchema.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-core/src/test/java/org/apache/paimon/rest/MockRESTMessage.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/HiveCatalogTest.java
paimon-open-api/rest-catalog-open-api.yaml
paimon-open-api/src/main/java/org/apache/paimon/open/api/RESTCatalogController.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/catalog/SupportView.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonViewResolver.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/execution/PaimonViewExec.scala

In many scenarios, the dialects of each engine are different. We can provide View with dialect fields to provide space for future extensions.
However, there is currently no operation to control dialects, and multiple dialects can only be written directly through the API when creating a View.
Perhaps in the future, we can consider adding some procedures to add, modify, or delete dialects.
Some information in Iceberg community: https://lists.apache.org/thread/k6szpr5smyrh37sy563xpgjor4g6pr81
They seem more inclined to use `Substrait` to only save intermediate states, but that solution appears to be very complex and difficult to control.
BTW, this PR also change `RowType rowType` to `List<DataField> fields` in `ViewSchema`, this is good to be consistent with Table `Schema`.

[core] Add dialects to View

---

docs/layouts/shortcodes/generated/kafka_sync_database.html
docs/layouts/shortcodes/generated/kafka_sync_table.html
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncDatabaseActionBase.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncTableActionBase.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/TypeMapping.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcSinkBuilder.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/MultiTableUpdatedDataFieldsProcessFunction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunction.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/UpdatedDataFieldsProcessFunctionBase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/SchemaEvolutionTest.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaCanalSyncTableActionITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkITCase.java
paimon-flink/paimon-flink-cdc/src/test/resources/kafka/canal/table/typenochange/canal-data-3.txt
paimon-flink/paimon-flink-cdc/src/test/resources/kafka/canal/table/typenochange/canal-data-4.txt

Linked issue: close #4783 
We use ticdc to collect data from tidb to kafka, but it does not provide specific parameters for types. No length for varcahr, and no precision and scale for decimal. The current schema evoluation would improve them to string and decimal(38, 18), which is not expected.
So we want to keep the type specified manually unchanged. This could be controlled by the new type_mapping options. NO_CHNAGE, DECIMAL_NO_CHANGE.
Observe the varchar and decimal field definition after new value ingested.
No.
Yes and provided

[cdc] Ignore decimal length and precision change by type-mapping

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/CompactorSourceBuilder.java

There are some failures related to delicated compaction
```
1. FlinkActionsWithKafkaE2eTest
Result is still unexpected after 60 retries.
Expected: {20221206, 1, 100=1, 20221205, 1, 100=1}
Actual: {}
at org.apache.paimon.tests.E2eTestBase.checkResult(E2eTestBase.java:333)
at org.apache.paimon.tests.FlinkActionsWithKafkaE2eTest.testCompact(FlinkActionsWithKafkaE2eTest.java:112)
2. CompactProcedureITCase
java.util.concurrent.TimeoutException: Cannot collect 2 records in 3 MINUTES
at org.apache.paimon.utils.BlockingIterator.collect(BlockingIterator.java:84)
at org.apache.paimon.utils.BlockingIterator.collect(BlockingIterator.java:72)
at org.apache.paimon.flink.procedure.CompactProcedureITCase.testStreamingCompact(CompactProcedureITCase.java:138)
``` 
FlinkActionsWithKafkaE2eTest …

[hotfix] Fix dedicated compaction

---

paimon-core/src/main/java/org/apache/paimon/catalog/CatalogUtils.java
paimon-core/src/main/java/org/apache/paimon/catalog/RenamingSnapshotCommit.java
paimon-core/src/main/java/org/apache/paimon/catalog/SnapshotCommit.java
paimon-core/src/main/java/org/apache/paimon/manifest/PartitionEntry.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
paimon-core/src/main/java/org/apache/paimon/partition/Partition.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTSnapshotCommitFactory.java
paimon-core/src/main/java/org/apache/paimon/rest/requests/CommitTableRequest.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-open-api/rest-catalog-open-api.yaml

When we commit a table, we can obtain the statistical information of this change. We can aggregate this statistical information by partition and provide it to the REST service. This way, the server can maintain tables and partitions based on this information to provide better services.

[rest] Add commit statistics when commit to REST Server

---

paimon-core/src/main/java/org/apache/paimon/utils/JsonSerdeUtil.java

[cdc] Fix canal cdc data field value is null judgment condition.

---

paimon-core/src/main/java/org/apache/paimon/append/BucketedAppendCompactManager.java

TreeMap will remove record if comparator return 0. But we don't want this happen in BucktedAppendTableWrite.

[core] Use PriorityQueue intead of TreeSet. TreeSet will deduplicate record if comparator return 0

---

paimon-e2e-tests/src/test/java/org/apache/paimon/tests/E2eTestBase.java
paimon-e2e-tests/src/test/resources-filtered/docker-compose.yaml

Reduce the complexity of E2E container and improve the stability. 
many projects such as Iceberg have removed relying on zk

[build] Optimize Kafka container to use KRaft instead of relying on ZooKeeper

---

docs/content/flink/procedures.md

[doc] Add catalog prefix to Flink procedure

---

paimon-core/src/main/java/org/apache/paimon/catalog/SupportsBranches.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/ResourcePaths.java
paimon-core/src/main/java/org/apache/paimon/rest/requests/CreateBranchRequest.java
paimon-core/src/main/java/org/apache/paimon/rest/requests/ForwardBranchRequest.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/ErrorResponseResourceType.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/ListBranchesResponse.java
paimon-core/src/main/java/org/apache/paimon/utils/FileSystemBranchManager.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTest.java
paimon-open-api/rest-catalog-open-api.yaml
paimon-open-api/src/main/java/org/apache/paimon/open/api/RESTCatalogController.java

Next PR for https://github.com/apache/paimon/pull/5157

[rest] Implement SupportsBranches in REST Catalog

---

paimon-core/src/main/java/org/apache/paimon/table/FallbackReadFileStoreTable.java

In my company, the batch dedicated compaction throw a exception.
After read the code, we found in CompactorSourceBuilder#batchCompactOptions we will do `put(CoreOptions.SCAN_SNAPSHOT_ID.key(), null);`, so the exception throw.
Now fix it.

[Bug] Fix NumberFoematException of Dedicated Compaction

---

docs/content/maintenance/metrics.md
paimon-core/src/main/java/org/apache/paimon/mergetree/Levels.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactManager.java
paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/operation/metrics/CompactionMetrics.java
paimon-core/src/test/java/org/apache/paimon/operation/metrics/CompactionMetricsTest.java

This PR adds total file size metrics of active buckets for primary key tables, so that when users experience a slow compaction,  they can quickly check if some buckets are too large.
* `CompactionMetricsTest`.
Document is also updated.

[metrics] Add total file size metrics of active buckets for primary key tables

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/FileSystemCatalog.java
paimon-core/src/main/java/org/apache/paimon/jdbc/JdbcCatalog.java
paimon-core/src/main/java/org/apache/paimon/utils/FileStorePathFactory.java
paimon-core/src/test/java/org/apache/paimon/rest/MetadataInMemoryFileSystemCatalog.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PrimaryKeyFileStoreTableITCase.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java

In my company, we open the external paths feature. 
But we found after drop table, the external paths still exist. 
This is a bug, now fix it.

[Bug] Delete external paths when drop table

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DataFrameWriteTest.scala

[spark] Fix the column projection when writing by DataFrameWriter

---

paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalogOptions.java
paimon-core/src/main/java/org/apache/paimon/rest/auth/DLFAuthProviderFactory.java
paimon-core/src/test/java/org/apache/paimon/rest/auth/AuthSessionTest.java
paimon-core/src/test/java/org/apache/paimon/rest/auth/DLFAuthProviderFactoryTest.java

RESTCatalog: update parse region from DLF uri
Linked issue: #4540 
DLFAuthProviderFactoryTest.getRegion

[core] RESTCatalog: update parse region from dlf uri

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/Committer.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTableCommittableChannelComputer.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreMultiCommitter.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java

[flink] Fix StoreMultiCommitter with eager init mode

---

paimon-core/src/main/java/org/apache/paimon/tag/TagBatchCreation.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/BatchWriteGeneratorTagOperator.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/WriteIntoPaimonTable.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonTagDdlTestBase.scala

[spark] Enable TagCreationMode#batch for spark writer

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ReadWriteTableITCase.java

This PR fixes the bug that AdaptiveBatchScheduler can still adjust the parallelism of a writer operator when `sink.parallelism` is configured.
ReadWriteTableITCase#testSinkParallelism

[flink] fix parallelismConfigured in cases when sink parallelism is set

---

paimon-spark/paimon-spark-3.2/pom.xml
paimon-spark/paimon-spark-3.3/pom.xml
paimon-spark/paimon-spark-3.4/pom.xml

When I execute a spark 3.4- UT in idea, such as `DDLTest`, get `NoClassDefFoundError`
```
Caused by: java.lang.NoClassDefFoundError: org/apache/parquet/hadoop/ParquetEmptyBlockException
at org.apache.paimon.format.parquet.ParquetUtil.getParquetReader(ParquetUtil.java:81)
at org.apache.paimon.format.parquet.ParquetUtil.extractColumnStats(ParquetUtil.java:51)
at org.apache.paimon.format.parquet.ParquetSimpleStatsExtractor.extractWithFileInfo(ParquetSimpleStatsExtractor.java:78)
at org.apache.paimon.format.parquet.ParquetSimpleStatsExtractor.extract(ParquetSimpleStatsExtractor.java:71)
at org.apache.paimon.io.StatsCollectingSingleFileWriter.fieldStats(StatsCollectingSingleFileWriter.java:105)
at org.apache.paimon.io.RowDataFileWriter.result(RowDataFileWriter.java:112)
```
There is a parquet …

[spark][test] Fix spark parquet dependency conflict when executing tests locally.

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java

getNumberOfParallelSubtasks From getRuntimeContext() may be not found in separated flink version. SO replace it by RuntimeContextUtils.

[flink] Use RuntimeContextUtils to keep compatible

---

docs/content/flink/procedures.md
docs/content/migration/migration-from-iceberg.md

add the documents about iceberg migration

[iceberg][doc] add docs about iceberg migration

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/tag/TagPeriodHandler.java
paimon-core/src/test/java/org/apache/paimon/tag/TagAutoManagerTest.java

Hourly tag format only supports yyyy-MM-dd HH and yyyyMMdd HH now, user also need format without space.
Linked issue: close #5161
Support enums without spaces in TagPeriodFormatter.
Add testTagHourlyPeriodFormatterWithoutDashesAndSpaces in TagAutoManagerTest.java

[core]Support enums without spaces in TagPeriodFormatter

---

paimon-core/src/main/java/org/apache/paimon/rest/auth/DLFAuthProvider.java
paimon-core/src/test/java/org/apache/paimon/rest/auth/AuthSessionTest.java

Fix unstable test case: testRefreshDLFAuthTokenFileAuthProvider

[hotfix] Fix unstable test case: testRefreshDLFAuthTokenFileAuthProvider

---

paimon-core/src/main/java/org/apache/paimon/crosspartition/IndexBootstrap.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BranchSqlITCase.java

Support cross-partition for fallback branch feature.
Currently, once writing into a cross-partition table which fallback branch feature enabled, 
```
Flink SQL> create table part1(id int primary key not enforced, name string, dt string) partitioned by (dt);
Flink SQL> call sys.create_branch('branch.part1', 'stream');
Flink SQL> alter table part1 set ('scan.fallback-branch'='stream');
Flink SQL> insert into part1 values (1,'anew','20250301'),(20, 'from stream', '20250303');
```
throws exception as follow, it is caused by FallbackReadFileStoreTable#newScan return a DataTableScan instance, we should use `DataTableScan` instead of `AbstractDataTableScan` in IndexBootstrap#bootstrap.
```
Caused by: java.lang.ClassCastException: org.apache.paimon.table.FallbackReadFileStoreTable$Scan cannot be …
```

[core] Support cross-partition for fallback branch feature

---

paimon-arrow/src/main/java/org/apache/paimon/arrow/vector/ArrowFormatCWriter.java
paimon-arrow/src/main/java/org/apache/paimon/arrow/vector/ArrowFormatWriter.java

The`ArrayWriter` and `MapWriter` need to be reset before writing again, so the `ArrowFormatWriter` should expose the reset method.

[hotfix] ArrowFormatWriter should reset ArrowFieldWriters after flushing

---

paimon-common/src/main/java/org/apache/paimon/PagedList.java
paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/HttpClient.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalogOptions.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTClient.java
paimon-core/src/main/java/org/apache/paimon/rest/ResourcePaths.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/ListPartitionsResponse.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/ListTableDetailsResponse.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/ListViewDetailsResponse.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/ListViewsResponse.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-core/src/test/java/org/apache/paimon/rest/HttpClientTest.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTest.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-open-api/rest-catalog-open-api.yaml
paimon-open-api/src/main/java/org/apache/paimon/open/api/RESTCatalogController.java

[core] RestCatalog: set up paged list tables/views/partitions
Check Iceberg & Unity Catalog,  they support paged list for tables & views both, so suggest adding paged list method into paimon

[core] RestCatalog: set up paged list tables/views/partitions

---

paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/AppendOnlyFileStore.java
paimon-core/src/main/java/org/apache/paimon/FileStore.java
paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java
paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedFileStore.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java
paimon-core/src/test/java/org/apache/paimon/iceberg/IcebergCompatibilityTest.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/iceberg/IcebergHiveMetadataCommitterITCaseBase.java

Paimon synchronizes metadata to iceberg by invoking IcebergCommitCallback method when committing. DropPartition operation create `commit` by `AbstractFileStore#newCommit(commitUser)` which will pass an empty list of CommitCallback to `commit` and thus metadata cannot be synchronized to iceberg.
This can be fixed by creating corresponding IcebergCommitCallback when invoking `AbstractFileStore#newCommit(commitUser)`.

[iceberg] fix that dropPartition cannot sychronize the metadata to iceberg

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordUtils.java

When a cdc record conversion exception occurs, the user does not know which field it is.

[cdc] Improve cdc record conversion to row Failure logs add field name

---

paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetReaderFactory.java

In my company, a job throw the follow exception. 
When debug this problem, we found that some log is absent in Paimon, now add it.

[Log] Add log to help debug

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java

Fixed bucket append table should not apply precommit-compact.

[flink] Fix Add table type judgment for precommit-compact.

---

paimon-common/src/main/java/org/apache/paimon/format/SimpleStatsExtractor.java
paimon-common/src/main/java/org/apache/paimon/fs/local/LocalFileIO.java
paimon-common/src/test/java/org/apache/paimon/format/SimpleColStatsExtractorTest.java
paimon-core/src/main/java/org/apache/paimon/io/KeyValueDataFileWriter.java
paimon-core/src/main/java/org/apache/paimon/io/RowDataFileWriter.java
paimon-core/src/main/java/org/apache/paimon/io/StatsCollectingSingleFileWriter.java
paimon-core/src/main/java/org/apache/paimon/migrate/FileMetaUtils.java
paimon-core/src/test/java/org/apache/paimon/SnapshotTest.java
paimon-core/src/test/java/org/apache/paimon/stats/TestSimpleStatsExtractor.java
paimon-format/src/main/java/org/apache/paimon/format/avro/AvroSimpleStatsExtractor.java
paimon-format/src/main/java/org/apache/paimon/format/orc/filter/OrcSimpleStatsExtractor.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetInputFile.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetReaderFactory.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetSimpleStatsExtractor.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetUtil.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetFormatReadWriteTest.java

Minor optimization for parquet reader.

[core] Reduce useless getFileStatus for Parquet Reader

---

paimon-hive/paimon-hive-connector-2.3/pom.xml
paimon-hive/paimon-hive-connector-3.1/pom.xml
paimon-hive/paimon-hive-connector-common/pom.xml
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveLocationTest.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/runner/PaimonEmbeddedHiveRunner.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/runner/PaimonEmbeddedHiveServerContext.java
paimon-hive/pom.xml

Currently, hive tests on jdk11 always failed.
After digging into the problem, I found that old hiverunner usage was outdated and can be replaced as `io.github.hiverunner:hiverunner` refer to https://github.com/HiveRunner/HiveRunner/blob/main/README.md.
In addition, The dependency tez 0.9.1 in hiverunner has bugs for jdk0.9+ and have been fixed in 0.10.0 refer to https://issues.apache.org/jira/browse/TEZ-3860.
CI on jdk11: https://github.com/liyubin117/paimon/actions/runs/13676925840

[test][hive] Upgrade hiverunner usage to support tests in jdk11

---

paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java

[core] Remove useless branch arguement in FileStoreCommitImpl

---

paimon-core/src/main/java/org/apache/paimon/rest/HttpClient.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTUtil.java
paimon-core/src/main/java/org/apache/paimon/rest/ResourcePaths.java
paimon-core/src/main/java/org/apache/paimon/rest/auth/RESTAuthParameter.java
paimon-core/src/main/java/org/apache/paimon/rest/responses/ErrorResponse.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-core/src/test/java/org/apache/paimon/rest/DefaultErrorHandlerTest.java
paimon-core/src/test/java/org/apache/paimon/rest/HttpClientTest.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTObjectMapperTest.java
paimon-core/src/test/java/org/apache/paimon/rest/ResourcePathsTest.java
paimon-open-api/src/main/java/org/apache/paimon/open/api/RESTCatalogController.java

RESTCatalog:  encode resource name in URL
Linked issue: https://github.com/apache/paimon/issues/4540
- HttpClientTest. testUrl
- ResourcePathsTest. testUrlEncode

[core] RESTCatalog:  encode resource name and query value in url

---

docs/content/concepts/rest-catalog.md
docs/content/spark/sql-ddl.md
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalogOptions.java

In Paimon's configuration items, it seems that lowercase letters and - are usually used to define configuration key names.
Another reason is that when options are passed from SparkCatalog, all keys are converted to lowercase.

[core] refine the dlf config key

---

paimon-core/src/main/java/org/apache/paimon/operation/FileDeletionBase.java
paimon-core/src/main/java/org/apache/paimon/operation/TagDeletion.java

Another solution for #5229
This PR tries to maintain the original logic of Tag deleting files as much as possible to avoid residual files.

[core] Fix that snapshot expire might delete files used by tag mistakenly

---

paimon-common/src/main/java/org/apache/paimon/data/columnar/heap/HeapRowVector.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/newreader/VectorizedParquetRecordReader.java

** Remove redundant reset in `HeapRowVector`
** Throws file location if next batch errors

[core] Remove redundant reset by HeapRowVector

---

paimon-common/src/test/java/org/apache/paimon/data/DataFormatTestUtil.java
paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergDataField.java
paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergDataTypeDeserializer.java
paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergListType.java
paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergMapType.java
paimon-core/src/test/java/org/apache/paimon/iceberg/migrate/IcebergMigrateTest.java

This pr supports migrating an iceberg table with nested type to paimon. The nested types are list, map and struct. 
IcebergMigrateTest#testNestedDataTypes

[iceberg] support migrating iceberg table with nested types

---

docs/content/flink/procedures.md
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RescaleAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RescaleActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/RescaleProcedure.java

Currently user has no way to configure source and sink parallelism in rescale procedure. This PR adds default parallelism and make it configurable.

[flink] Add default parallelism for source and sink in rescale procedure, also make them configurable

---

paimon-core/src/main/java/org/apache/paimon/rest/RESTTokenFileIO.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTUtil.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTUtilTest.java

When merging option and token in RESTTokenFileIO, the value in options should not be overwritten. DLF server will pass a default value, such as fs.oss.endpoint=oss-cn-hangzhou-internal.aliyuncs.com, which is not available in some client environment, and the value passed in options needs to be used.
RESTUtilTest

[core] do not overwrite options when merging options and token

---

paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java

Purpose
When merging option in test format table, the value in options should not be written by default value. DLF server cannot handle format table without external path, so the format table test options should be able to be overridden .
Tests
CatalogTestBase.testFormatTable

[test] do not overwrite options when test format table

---

paimon-core/src/main/java/org/apache/paimon/rest/HttpClient.java
paimon-core/src/main/java/org/apache/paimon/rest/auth/DLFAuthProvider.java
paimon-core/src/main/java/org/apache/paimon/rest/auth/DLFAuthSignature.java
paimon-core/src/main/java/org/apache/paimon/rest/auth/RESTAuthParameter.java
paimon-core/src/test/java/org/apache/paimon/rest/HttpClientTest.java
paimon-core/src/test/java/org/apache/paimon/rest/MockRESTCatalogTest.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/auth/AuthSessionTest.java
paimon-core/src/test/java/org/apache/paimon/rest/auth/DLFAuthSignatureTest.java

Because the host header is easily overwritten after several forwarding, so remove it from add additional signed headers.
DLFAuthSignatureTest

[core] remove additional signed headers

---

docs/content/flink/sql-query.md
docs/content/spark/sql-query.md
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/table/source/AbstractDataTableScan.java
paimon-core/src/test/java/org/apache/paimon/table/IncrementalTimeStampTableTest.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/TableValuedFunctionsTest.scala

[core] incremental-between-timestamp supports timestamp string

---

paimon-common/src/main/java/org/apache/paimon/data/columnar/heap/HeapBytesVector.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/newreader/DeltaByteArrayEncodingTest.java

Linked issue: close #5271
DeltaByteArrayEncodingTest#testNegativeSize

[hotfix] Catch NegativeArraySizeException when reserveBytes in HeapBytesVector

---

paimon-arrow/src/main/java/org/apache/paimon/arrow/vector/ArrowFormatCWriter.java
paimon-arrow/src/main/java/org/apache/paimon/arrow/vector/ArrowFormatWriter.java
paimon-arrow/src/test/java/org/apache/paimon/arrow/vector/ArrowFormatWriterTest.java

Linked issue: close #5278 
[arrow] support ArrowFormatWriter to use an external BufferAllocator to provide finer-grained memory control and monitor allocation events.
- org.apache.paimon.arrow.vector.ArrowFormatWriterTest#testWriteWithExternalAllocator
No.
No.

[arrow] support ArrowFormatWriter to use an external BufferAllocator to provide finer-grained memory control and monitor allocation events.

---

paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java

Submitting a commit to record the deletion of all files is a heavy operation that should be completed by the client.

[rest] Drop partition using filesystem in RESTCatalog

---

paimon-core/src/main/java/org/apache/paimon/io/RecordLevelExpire.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/CompactStrategy.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactManager.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactTask.java
paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java
paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTestBase.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/MergeTreeCompactManagerTest.java
paimon-core/src/test/java/org/apache/paimon/table/RecordLevelExpireTest.java

Record-Level expiration happens in compaction, but some specific data files will not be rewritten even in full compaction which may leading some expired records can't be expired for a long time. This pr aims to ensure that record-expire takes effect when full compaction. 
When full compaction, the files with the following kinds will not be rewritten:
- large file, file level is maxLevel and no overlap with other file: do nothing for the file
- large file, outputLevel is not maxLevel or has no deleted records: directly upgrade file level to outputLevel without rewriting
For these files,  rewrite them if they contain expired records.
And full compaction will pick no files for compaction in the following cases:
- lsm tree is empty
- only one maxLevel sorted run in …

[core] ensure that record-expire takes effect when full compaction

---

paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalTimeStampStartingScanner.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java

[hotfix] incremental-between-timestamp should return empty data instead of throwing exception

---

paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTestBase.java

Linked issue: close 
since #5299 removed partition modification in RESTCatalog, we should support partition upsert&delete in RESTCatalogServer.commitSnapshot and fix relative ut

[test] refactor commitSpanshot in RestCatalog and fix ut

---

docs/content/concepts/table-types.md
paimon-core/src/main/java/org/apache/paimon/table/FormatTable.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveTableUtils.java
paimon-hive/paimon-hive-connector-2.3/pom.xml
paimon-hive/paimon-hive-connector-3.1/pom.xml
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogFormatTableITCaseBase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkSource.scala
paimon-spark/paimon-spark-ut/pom.xml
paimon-spark/paimon-spark-ut/src/test/java/org/apache/paimon/spark/SparkCatalogWithHiveTest.java

Currently paimon format table only support CSV, Parquet, ORC formats, this pr adds support for json format.

[core] support format table for json

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactDatabaseAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/MultiAwareBucketTableScan.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/MultiTableScanBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/MultiUnawareBucketTableScan.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendOnlyMultiTableCompactionWorkerOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTablesStoreCompactOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/PrepareCommitOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/CombinedTableCompactorSourceBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedAwareBatchSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedAwareStreamingSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedUnawareBatchSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/CombinedUnawareStreamingSource.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactDatabaseActionITCase.java

Currently, tables are dynamically loaded when performing dedicated database compaction, and table conf set by user will not be passed to these tables in some stages, e.g., source stage and write stage will not pass the user table conf. This pr aims to fix it.

[flink] make tableConf valid for database compaction job

---

paimon-core/src/main/java/org/apache/paimon/utils/ChangelogManager.java

OrphanFilesClean: add log change log path when change log is empty

[core] OrphanFilesClean: add log change log path when change log is empty

---

docs/content/concepts/rest-catalog.md
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalogOptions.java
paimon-core/src/main/java/org/apache/paimon/rest/auth/DLFECSTokenLoader.java
paimon-core/src/main/java/org/apache/paimon/rest/auth/DLFECSTokenLoaderFactory.java
paimon-core/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-core/src/test/java/org/apache/paimon/rest/auth/AuthSessionTest.java
paimon-core/src/test/java/org/apache/paimon/rest/auth/MockECSMetadataService.java

support DLFECSTokenLoader
org.apache.paimon.rest.auth.AuthSessionTest#testCreateDlfAuthProviderByECSTokenProvider
org.apache.paimon.rest.auth.AuthSessionTest#testCreateDlfAuthProviderByECSTokenProviderWithDefineRole
org.apache.paimon.rest.auth.AuthSessionTest#testCreateDlfAuthProviderByECSTokenProviderWithInvalidRole

[core] RESTCatalog: support DLFECSTokenLoader

---

paimon-common/src/main/java/org/apache/paimon/fs/FileIO.java
paimon-core/src/main/java/org/apache/paimon/utils/HintFileUtils.java

```
/**
* Overwrite hint file by content atomically, the characteristic of Hint file is that it can not
* exist for a period of time, which allows some file systems to perform overwrite writing by
* deleting and renaming.
*/
```

[fileio] Introduce FileIO.overwriteHintFile

---

docs/content/flink/procedures.md
paimon-core/src/main/java/org/apache/paimon/table/ExpireChangelogImpl.java
paimon-core/src/main/java/org/apache/paimon/utils/ChangelogManager.java
paimon-core/src/main/java/org/apache/paimon/utils/HintFileUtils.java
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/ExpireChangelogsProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpireChangelogsAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpireChangelogsActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ExpireChangelogsProcedure.java
paimon-flink/paimon-flink-common/src/main/resources/META-INF/services/org.apache.paimon.factories.Factory
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/ExpireChangelogsProcedureITCase.java

Feature https://github.com/apache/paimon/issues/2899 enables to decouple the lifecycle of snapshot and changelog. The reasons of introducing changelog expire procedure are as follows:
1. `ExpireSnapshotsProcedure` will only expire snapshots. If their lifecycle is decoupled, the previous changelog can not be expired with `ExpireSnapshotsProcedure`.
2. If  a table decoupled the lifecycle at initially, but later changed to not decoupled, there would be some changelogs  which can not be expired anymore. Here is a simple example:
```
First:
snapshot.num-retained.min = 4, changelog.num-retained.min = 10 (lifecycle decoupled)
Snapshot: [7, 8, 9, 10]
Changelog: [1, 2, 3, 4, 5, 6]
Later:
snapshot.num-retained.min = 4, changelog.num-retained.min = 4 (lifecycle not …
```

[core][flink] introduce changelog expire procedure and action

---

paimon-common/src/main/java/org/apache/paimon/fileindex/bitmap/BitmapIndexResult.java
paimon-common/src/test/java/org/apache/paimon/fileindex/bitmapindex/BitmapFileIndexTest.java

Fixed the incorrect logic of BitmapIndexResult and other IndexResult operations
org.apache.paimon.fileindex.bitmapindex.BitmapFileIndexTest::testCompoundIndexResult

[common] Fix bug in BitmapIndexResult 'or' operation.

---

docs/content/primary-key-table/compaction.md

There is no compaction section in primary-key-table/overview page.

[doc] fix typo link in compaction doc

---

paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTestBase.java

refactor testListPartitionsWhenMetastorePartitionedIsTrue due to changes of branch logic in #5325

[test] refactor test in RESTCatalogTestBase#testListPartitionsWhenMetastorePartitionedIsTrue

---

docs/content/flink/procedures.md
docs/content/spark/procedures.md

Fix line layout to enhance readability.
There are some layout errors such as
```
-- for Flink 1.18
CALL sys.rollback_to_timestamp('default.T', 10) -- for Flink 1.19 and later
CALL sys.rollback_to_timestamp(`table` => 'default.T', timestamp => 1730292023000)
```

[doc] Fix line layout to enhance readability

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CloneActionITCase.java

Fixes the bug that targetFileIO is used to read sourceTable's content in CloneActionITCase.

[test] Fixed incorrect use of FileIO in CloneActionITCase

---

docs/README.md
docs/content/concepts/rest/overview.md
docs/layouts/shortcodes/generated/rest_catalog.html

Currently, it is difficult to understand the RestCatalog API in text form (https://raw.githubusercontent.com/apache/paimon/master/paimon-open-api/rest-catalog-open-api.yaml).
We can introduce Redoc (refer to https://nordicapis.com/using-redoc-to-auto-generate-openapi-documentation/) to visualize how the API can be used as shown below. And it will automatically change with the changes of the YAML definition, without additional maintenance.

[rest] Introduce `Redoc` to visualize Rest API

---

paimon-core/src/main/java/org/apache/paimon/table/source/AbstractDataTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalDeltaStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalDiffStartingScanner.java
paimon-core/src/test/java/org/apache/paimon/table/IncrementalTableTest.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/IncrementalDeltaStartingScannerTest.java

It is necessary for automatically run paimon batch job of incremental query if we return empty result.
Throwing exceptions will break the workflow.

[core] Incremental query should return empty result for some corner cases

---

paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogITCaseBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/BranchActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CloneActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/SortCompactActionForUnawareBucketITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/ExpirePartitionsProcedureITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/ExpireSnapshotsProcedureITCase.java

- Changed the access modifiers of certain methods in Action and Procedure from private to protected:
- This change enables subclasses to inherit and reuse logic for ITCase scenarios.
- It also supports future extensibility and customization.
-  Updated the following classes to public access:
- BranchActionITCase
- This change allows the classes to be accessed across different packages, improving code reusability and modularity.

[test] Enhance inheritance and visibility for ITCase support

---

docs/content/concepts/rest/rest-api.md
docs/layouts/partials/docs/inject/head.html

For pages using `Redoc`
1. Custom content-security-policy to allow visit `https://raw.githubusercontent.com/apache/paimon/master/paimon-open-api/`
2. use `redoc.standalone.js`, others not, speed up pages loading.

[rest] Introduce `redocPage` variable to support customizable parameters on pages using `Redoc`

---

paimon-common/src/main/java/org/apache/paimon/utils/ParallelExecution.java
paimon-core/src/test/java/org/apache/paimon/utils/ParallelExecutionTest.java

Now, if a record is too big, in `ParallelExecution`, there will be a busy loop.
We should throw exception to alert user to increase `page-size` table option.

[core] Fix one record cannot fit into a single page in ParallelExecution

---

docs/content/flink/procedures.md
paimon-core/src/main/java/org/apache/paimon/rest/RESTObjectMapper.java
paimon-core/src/main/java/org/apache/paimon/utils/JsonSerdeUtil.java

RESTCatalog: use object mapper from JsonSerdeUtil  in RESTObjectMapper
Linked issue:  #4540

[core]: RESTCatalog: use object mapper from JsonSerdeUtil in RESTObjectMapper

---

paimon-filesystems/paimon-gs-impl/pom.xml
paimon-filesystems/paimon-gs-impl/src/main/java/org/apache/paimon/gs/GSFileIO.java
paimon-filesystems/paimon-gs-impl/src/main/java/org/apache/paimon/gs/HadoopCompliantFileIO.java
paimon-filesystems/paimon-gs-impl/src/main/resources/META-INF/NOTICE
paimon-filesystems/paimon-gs-impl/src/main/resources/META-INF/licenses/LICENSE.animal-sniffer
paimon-filesystems/paimon-gs-impl/src/main/resources/META-INF/licenses/LICENSE.checker-framework-qualifiers
paimon-filesystems/paimon-gs-impl/src/main/resources/META-INF/licenses/LICENSE.dnsjava
paimon-filesystems/paimon-gs-impl/src/main/resources/META-INF/licenses/LICENSE.jakarta
paimon-filesystems/paimon-gs-impl/src/main/resources/META-INF/licenses/LICENSE.jaxb
paimon-filesystems/paimon-gs-impl/src/main/resources/META-INF/licenses/LICENSE.re2j
paimon-filesystems/paimon-gs-impl/src/main/resources/META-INF/licenses/LICENSE.stax2api
paimon-filesystems/paimon-gs/pom.xml
paimon-filesystems/paimon-gs/src/main/java/org/apache/paimon/gs/GSLoader.java
paimon-filesystems/paimon-gs/src/main/resources/META-INF/services/org.apache.paimon.fs.FileIOLoader
paimon-filesystems/pom.xml

Linked issue: https://github.com/apache/paimon/issues/5235
Adding support for Google Cloud Storage
The same format is applied.
Configurations are derived from Google Cloud's Hadoop connector
https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/CONFIGURATION.md
This is a new feature.
A catalog is created in a similar way the S3 catalog is being created
```
CREATE CATALOG my_gcs_catalog WITH (
'type' = 'paimon',
'warehouse' = 'gs://paimon-tables/catalog',
'fs.gs.auth.type' = 'SERVICE_ACCOUNT_JSON_KEYFILE',
'fs.gs.auth.service.account.json.keyfile' = '/path/to/service-account-.json'
);
```

[Feature] Add filesystem support for Google Cloud Storage

---

docs/content/spark/quick-start.md

Add spark dataframe read and write

[doc] Add spark dataframe read and write

---

docs/content/spark/sql-write.md
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/InsertOverwriteTableTestBase.scala

Add more examples of insert overwrite partition

[doc] Add more examples of insert overwrite partition

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/AggregateMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/factory/FieldAggregatorFactory.java
paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeySimpleTableTest.java

We use aggregation in special case which needs  removing the record when receiving a DELETE operation.
1. We use `--computed_column 'etl_create_time=now()'` and `field.etl_create_time.aggregate-function = first_non_null_value` to
record the first time when the record ingestd.
2. It also needs removing the record when ingesting DELETE operation instead of just value retraction.

[core] Support remove-record-on-delete for aggregation merge-engine

---

paimon-open-api/src/main/java/org/apache/paimon/open/api/RESTCatalogController.java

Caused by: java.lang.IllegalStateException: Ambiguous mapping. Cannot map 'RESTCatalogController' method 
org.apache.paimon.open.api.RESTCatalogController#listViewDetails(String, String, Integer, String)
to {GET [/v1/{prefix}/databases/{database}/views]}: There is already 'RESTCatalogController' bean method
org.apache.paimon.open.api.RESTCatalogController#listViews(String, String, Integer, String) mapped.
just as rest-catalog-open-api.yaml described,listViewDetails method should be mappinged into '/v1/{prefix}/databases/{database}/view-details' 

[rest] Fix RESTCatalogController ambiguous mapping between listViewDetails and listViews method

---

docs/content/flink/sql-ddl.md
docs/content/maintenance/manage-partitions.md

Introduce manage partitions doc page

[doc] Add manage partitions page

---

paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/IncrementalDeltaStartingScanner.java
paimon-core/src/test/java/org/apache/paimon/table/IncrementalTableTest.java
paimon-core/src/test/java/org/apache/paimon/table/IncrementalTimeStampTableTest.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/IncrementalDeltaStartingScannerTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java

When quering audit_log with scaning delta or changelog, we want to get each operation without merging. 
For example, one record was INSERT-ed then DELETE-ed, we need both operations. This is useful for multi micro-batch processing. 
Firstly, a new record is detected. If the record wast removed, we need detected the DELETE operation in the following batch query instead of nothing. This could cause users to mistakenly think nothing happened which actually did.

[core] Incremental delta scan should be in stream mode, not mergeing

---

paimon-spark/paimon-spark-3.2/pom.xml
paimon-spark/paimon-spark-3.3/pom.xml

Change paimon-spark-common to provided in paimon-spark-3.2 and paimon-spark-3.3.
In the current pom.xml files for paimon-spark-3.2 and paimon-spark-3.3, the dependency on paimon-spark-common is included in a way that introduces a problem: these modules contain classes with the same names. For example, paimon-spark-3.2 includes a class named org.apache.paimon.spark.PaimonScan, and paimon-spark-common has a class with the same name. 
When packaging with the mvn command, the maven-shade-plugin resolves the conflict. However, when an external project includes the paimon-spark-3.2 dependency, the classpath will contain two org.apache.paimon.spark.PaimonScan classes, leading to a conflict if the external project code references PaimonScan, causing an exception. I believe changing the scope to …

[spark] In Spark 3.2 and 3.3, change paimon-spark-common to provided.

---

docs/layouts/shortcodes/generated/catalog_configuration.html
paimon-common/src/main/java/org/apache/paimon/options/CatalogOptions.java
paimon-filesystems/paimon-oss-impl/src/main/java/org/apache/paimon/oss/HadoopCompliantFileIO.java
paimon-filesystems/paimon-oss-impl/src/main/java/org/apache/paimon/oss/OSSFileIO.java

Linked issue: close #4990 
Expose OSS objects' metadata, so more fields of object tables built on OSS can be filled.
N/A
N/A
N/A

[filesystems] Listing OSS objects with metadata

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/util/OptionUtils.scala

As the title, just correct the warnning message.

[spark] Correct the warning message when missing paimon extension

---

paimon-core/src/main/java/org/apache/paimon/Snapshot.java

Optimize equals and hashCode implementation in Snapshot

[core] Optimize equals and hashCode implementation in Snapshot

---

docs/content/maintenance/filesystems.md
paimon-filesystems/paimon-azure-impl/pom.xml
paimon-filesystems/paimon-azure-impl/src/main/java/org/apache/paimon/azure/AzureFileIO.java
paimon-filesystems/paimon-azure-impl/src/main/java/org/apache/paimon/azure/HadoopCompliantFileIO.java
paimon-filesystems/paimon-azure-impl/src/main/resources/META-INF/NOTICE
paimon-filesystems/paimon-azure-impl/src/main/resources/META-INF/licenses/LICENSE.animal-sniffer
paimon-filesystems/paimon-azure-impl/src/main/resources/META-INF/licenses/LICENSE.checker-framework-qualifiers
paimon-filesystems/paimon-azure-impl/src/main/resources/META-INF/licenses/LICENSE.dnsjava
paimon-filesystems/paimon-azure-impl/src/main/resources/META-INF/licenses/LICENSE.jakarta
paimon-filesystems/paimon-azure-impl/src/main/resources/META-INF/licenses/LICENSE.jaxb
paimon-filesystems/paimon-azure-impl/src/main/resources/META-INF/licenses/LICENSE.re2j
paimon-filesystems/paimon-azure-impl/src/main/resources/META-INF/licenses/LICENSE.stax2api
paimon-filesystems/paimon-azure/pom.xml
paimon-filesystems/paimon-azure/src/main/java/org/apache/paimon/azure/AzureLoader.java
paimon-filesystems/paimon-azure/src/main/resources/META-INF.services/org.apache.paimon.fs.FileIOLoader
paimon-filesystems/pom.xml

Adding support for Microsoft Azure Storage
https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-java?tabs=powershell%2Cmanaged-identity%2Croles-azure-portal%2Csign-in-azure-cli&pivots=blob-storage-quickstart-scratch
This is a new feature.
A catalog is created in a similar way the S3 catalog is being created
CREATE CATALOG my_azure_catalog WITH (
'type' = 'paimon',
'fs.azure.account.key.ACCOUNT.blob.core.windows.net' = 'secret key',
'warehouse' = 'wasb://[test@ACCOUNT.blob.core.windows.net](mailto:test@ACCOUNT.blob.core.windows.net)/',
);

[Feature] Add filesystem support for Microsoft Azure Storage

---

paimon-core/src/main/java/org/apache/paimon/table/FallbackReadFileStoreTable.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BranchSqlITCase.java

There is no need to force an exception if fallback-branch has no files to be readed.
BranchSqlITCase#testCrossPartitionFallbackBranchBatchRead

[core] Not throw exception for fallback reading

---

paimon-common/src/main/java/org/apache/paimon/fs/FileIO.java
paimon-common/src/main/java/org/apache/paimon/fs/local/LocalFileIO.java
paimon-core/src/test/java/org/apache/paimon/table/SimpleTableTestBase.java

[core] Fix listFilesIterative bug and avoid using Files.walk in SimpleTableTestBase

---

docs/layouts/shortcodes/generated/flink_connector_configuration.html
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PostponeBucketTableITCase.java

Postpone bucket writing job should not expire snapshots. Snapshot expiration should be done in the compaction job.
* `PostponeBucketTableITCase#testPostponeWriteNotExpireSnapshots`.

[core] Postpone bucket writing job should not expire snapshots

---

paimon-core/src/main/java/org/apache/paimon/KeyValue.java
paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java

rowType in KeyValue and AppendOnlyFileStore is used for read and write, make it not null.

[core] make rowType not null for KeyValue and AppendOnlyFileStore

---

paimon-core/src/test/java/org/apache/paimon/rest/RESTSimpleTableTest.java

[test] RestCatalog: fix unit case annotation typo

[test] RestCatalog: fix unit case annotation typo

---

paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/ContinuousFromTimestampStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/TimeTravelUtil.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/TimeTravelUtilsTest.java
paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java

Return null if time travel meet earlier timestamp than the earliest snapshot timestamp when set flag.

[improve] As for `TimeTravel`, if the expected timestamp is earlier than the earliest snapshot, add one parameter to decide to return null or not

---

docs/layouts/shortcodes/generated/flink_connector_configuration.html
paimon-common/src/main/java/org/apache/paimon/utils/ThreadPoolUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/changelog/ChangelogCompactCoordinateOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/changelog/ChangelogCompactTask.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/changelog/ChangelogCompactWorkerOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PrimaryKeyFileStoreTableITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/compact/changelog/ChangelogCompactCoordinateOperatorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/compact/changelog/ChangelogCompactTaskSerializerTest.java

In #4380 we introduce pre-commit compact for changelog files. Multiple changelog files from the same partition will be merged into one big file in one worker parallelism to decrease the number of small files.
However, when the number of changelog files to merge is large (while each file itself is small enough), the copying process will be slow, because opening these many files from the filesystem takes a lot of time.
In this PR, we add a thread pool to the worker operator, so that when performing pre-commit compact for changelogs, we can copy the bytes with multiple threads, thus speeding up the process.
Existing IT cases should cover this change. This PR also adds a unit test for the coordinator operator.
Document is also updated.

[flink] Copy bytes with multiple threads when preforming precommit compact for changelogs

---

docs/content/concepts/spec/fileindex.md
paimon-common/src/main/java/org/apache/paimon/fileindex/bitmap/BitmapFileIndex.java

Production environment validation shows that version 2 has significant advantages.

[core] Make the default version of bitmap index to 2

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeFunction.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/aggregate/AggregateMergeFunction.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapperTest.java
paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeySimpleTableTest.java

like #5077, aggregate merge function should not return empty row with non-null column type exist

[core] Aggregate merge function should not return empty row with non-null column type exist

---

paimon-common/src/main/java/org/apache/paimon/utils/ProcedureUtils.java
paimon-core/src/main/java/org/apache/paimon/operation/PartitionExpire.java
paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/ExpirePartitionsProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpireSnapshotsAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/ExpireSnapshotsActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CompactManifestProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ExpirePartitionsProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ExpireSnapshotsProcedure.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/compact/UnawareBucketNewFilesCompactionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/ExpirePartitionsProcedureITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/ExpireSnapshotsProcedureITCase.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactManifestProcedure.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/CompactProcedure.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ExpirePartitionsProcedure.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/procedure/ExpireSnapshotsProcedure.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/CreateTagFromTimestampProcedureTest.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/ExpirePartitionsProcedureTest.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/ExpireSnapshotsProcedureTest.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/RemoveOrphanFilesProcedureTest.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/AnalyzeTableTestBase.scala

If the table property have related properties, we do not need to configure them separately in procedure, unify them for expire_partitions and expire_snapshots.
1. Properties loading priority: procedure param > options param > table properties.
2. Add 'options' parameter for some procedures, we can control some behaviors, such as manifest merge.

[core] Unify the order of procedure loading properties

---

paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreScan.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreScan.java
paimon-core/src/main/java/org/apache/paimon/operation/ManifestsReader.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReader.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/ReadOptimizedTable.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/CompactionChangelogFollowUpScannerTest.java

This PR adds `withLevel` method in `SnapshotReader` to optimize `$ro` system table scanning and `FULL_COMPACTION` scan mode. This method uses the newly added stats about levels in `ManifestFileMeta`.

[core] Add withLevel method in SnapshotReader to optimize RO/compacted table scanning

---

pom.xml

Since the current version contains vulnerability, we shoule consider upgrading json-smart version to resolve [CVE-2024-57699](https://github.com/advisories/GHSA-pq2g-wx69-c263).

[core] Upgrade json-smart and resolve CVE-2024-57699

---

paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/benchmark/BucketFunctionBenchmark.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/benchmark/PaimonSqlBasedBenchmark.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/benchmark/WriteBenchmark.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/spark/sql/paimon/PaimonBenchmark.scala

```
OpenJDK 64-Bit Server VM 1.8.0_332-b09 on Mac OS X 14.4.1
Apple M1
Bucket function:                          Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
Single int column                                  1965           2718        1260         10.2          98.3       1.0X
Single string column                               8529           8654         108          2.3         426.4       0.2X
Multiple columns                                  13629          14425        1238          1.5         681.4       0.1X
```
```
OpenJDK 64-Bit Server VM 1.8.0_332-b09 on Mac OS X 14.4.1
Apple M1
Write paimon table: …
```

[spark] Add bucket function and write benchmark

---

paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StaticFromSnapshotStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StaticFromTimestampStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
paimon-core/src/test/java/org/apache/paimon/utils/SnapshotManagerTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/TimeTravelITCase.java
paimon-spark/paimon-spark-ut/src/test/java/org/apache/paimon/spark/SparkTimeTravelITCase.java
paimon-spark/paimon-spark-ut/src/test/java/org/apache/paimon/spark/SparkTimeTravelWithDataFrameITCase.java

[core] Throw exception when travel to timestamp before the earliest snapshot

---

docs/layouts/shortcodes/generated/catalog_configuration.html
paimon-common/src/main/java/org/apache/paimon/options/CatalogOptions.java
paimon-hive/paimon-hive-catalog/src/test/java/org/apache/paimon/hive/HiveCatalogTest.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveCatalogITCaseBase.java

Set SYNC_ALL_PROPERTIES default to true, this change has been approved in paimon dev email.

[common] Set SYNC_ALL_PROPERTIES default to true, be kind to user.

---

paimon-core/src/main/java/org/apache/paimon/rest/DefaultErrorHandler.java
paimon-core/src/main/java/org/apache/paimon/rest/ErrorHandler.java
paimon-core/src/main/java/org/apache/paimon/rest/HttpClient.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-core/src/test/java/org/apache/paimon/rest/DefaultErrorHandlerTest.java

In the restCatalog, we need to include the requestId in the client's error message to better troubleshoot issues, especially when logs are absent.
Additionally, if the server does not provide a requestId (unknown), the error message should remain unchanged.

[rest] add requestId into errorMsg

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java
paimon-core/src/test/java/org/apache/paimon/operation/KeyValueFileStoreWriteTest.java

When using async compaction, users may want to monitor the process of compaction by checking the number of level 0 files. This PR adds an option to always select level 0 files when compacting, so user can make sure that, if no level 0 file exists, the compaction has finished.
* `KeyValueFileStoreWriteTest`
Document is also updated.

[core] Add option to always select level 0 files when compacting

---

paimon-core/src/main/java/org/apache/paimon/table/source/KeyValueTableRead.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FileStoreSourceReader.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/FileStoreSourceReaderTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/TestChangelogDataReadWrite.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/align/AlignedSourceReaderTest.java

Currently `sort-spill-threshold` does not affect Paimon Flink sources, because `IOManager` is not set to `TableRead` in Flink sources. This PR fixes the issue.
* `FileStoreSourceReaderTest`

[flink] Set IOManager to TableRead in Flink source

---

paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java

In Catalog.listXXXPaged methods' Javadocs, there is a description as follows.
> NOTE: Currently only RestCatalog will return pagedList data, other catalog will return all
> databases names like listDatabases.
So In order to get the correct paged results, invokers have to identify whether a catalog is a RESTCatalog, which breaks the isolation between the Catalog interface and its implementations. This PR proposes to add a supportsListObjectsPaged method to solve this problem. A similar design could be referenced from Catalog#supportsVersionManagement.
This PR adds a public Catalog#supportsListObjectsPaged method.

[core] Add supportsListObjectsPaged to Catalog

---

paimon-core/src/main/java/org/apache/paimon/table/ExpireSnapshotsImpl.java
paimon-core/src/test/java/org/apache/paimon/TestFileStore.java
paimon-core/src/test/java/org/apache/paimon/operation/ExpireSnapshotsTest.java
paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java
paimon-core/src/test/java/org/apache/paimon/operation/FileStoreTestUtils.java

[core][test] Test that snapshot deletion stops when throwing exception for skipping set

---

docs/content/maintenance/filesystems.md
paimon-filesystems/paimon-obs-impl/pom.xml
paimon-filesystems/paimon-obs-impl/src/main/java/org/apache/paimon/obs/HadoopCompliantFileIO.java
paimon-filesystems/paimon-obs-impl/src/main/java/org/apache/paimon/obs/OBSFileIO.java
paimon-filesystems/paimon-obs-impl/src/main/resources/META-INF/NOTICE
paimon-filesystems/paimon-obs-impl/src/main/resources/META-INF/licenses/LICENSE.animal-sniffer
paimon-filesystems/paimon-obs-impl/src/main/resources/META-INF/licenses/LICENSE.checker-framework-qualifiers
paimon-filesystems/paimon-obs-impl/src/main/resources/META-INF/licenses/LICENSE.dnsjava
paimon-filesystems/paimon-obs-impl/src/main/resources/META-INF/licenses/LICENSE.jakarta
paimon-filesystems/paimon-obs-impl/src/main/resources/META-INF/licenses/LICENSE.jaxb
paimon-filesystems/paimon-obs-impl/src/main/resources/META-INF/licenses/LICENSE.re2j
paimon-filesystems/paimon-obs-impl/src/main/resources/META-INF/licenses/LICENSE.stax2api
paimon-filesystems/paimon-obs/pom.xml
paimon-filesystems/paimon-obs/src/main/java/org/apache/paimon/obs/OBSLoader.java
paimon-filesystems/paimon-obs/src/main/resources/META-INF/services/org.apache.paimon.fs.FileIOLoader
paimon-filesystems/pom.xml

Huawei's OBS storage system is divided into object storage and parallel file system, both of which support the S3 protocol by default. However, in production testing, the object storage fully supports the S3 protocol, while the parallel file system encounters errors when using the S3 protocol. The error is as follows:
Caused by: java.lang.IllegalArgumentException: The path 's3://bucketname/warehouse/xxx' should be a directory. Upon investigation, it was found to be caused by the underlying S3 code. Therefore, support was provided based on Huawei OBS SDK and hadoop-huaweicloud, and it has been running stably in production for half a year.
https://support.huaweicloud.com/usermanual-obs/obs_13_0007.html

[Feature] Add filesystem support for Huawei OBS Storage

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/append/UnawareAppendTableCompactionCoordinator.java
paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyTableCompactionTest.java
paimon-core/src/test/java/org/apache/paimon/append/UnawareAppendTableCompactionCoordinatorTest.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/CompactProcedureTestBase.scala

Unaware bucket table compaction generates too many tasks.

[core] Unaware bucket table compaction generates too many tasks

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCompactOperator.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/StoreCompactOperatorTest.java

Currently `StoreCompactOperatorTest` is not a correct test. We should use `SerializationUtils.serializeBinaryRow` to serialize partition, just like the compaction source.

[test] Fix incorrect test in StoreCompactOperatorTest

---

docs/content/append-table/bucketed.md
docs/content/program-api/catalog-api.md
docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/append/BucketedAppendCompactManager.java
paimon-core/src/main/java/org/apache/paimon/operation/AppendOnlyFixedBucketFileStoreWrite.java
paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyTableCompactionTest.java
paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java
paimon-core/src/test/java/org/apache/paimon/append/BucketedAppendCompactManagerTest.java
paimon-core/src/test/java/org/apache/paimon/append/UnawareAppendTableCompactionCoordinatorTest.java
paimon-core/src/test/java/org/apache/paimon/format/FileFormatSuffixTest.java
paimon-core/src/test/java/org/apache/paimon/rest/MockRESTMessage.java
paimon-core/src/test/java/org/apache/paimon/table/SimpleTableTestBase.java
paimon-flink/paimon-flink-1.18/src/test/java/org/apache/paimon/flink/UnawareBucketAppendOnlyTableITCase.java
paimon-flink/paimon-flink-1.19/src/test/java/org/apache/paimon/flink/UnawareBucketAppendOnlyTableITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/AppendOnlyTableITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/UnawareBucketAppendOnlyTableITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactDatabaseActionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/compact/UnawareBucketNewFilesCompactionITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/AppendOnlySingleTableCompactionWorkerOperatorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/StoreMultiCommitterTest.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/HiveWriteITCase.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/DeleteFromPaimonTableCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/MergeIntoPaimonTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/UpdatePaimonTableCommand.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/CompactManifestProcedureTest.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/CompactProcedureTestBase.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DeletionVectorTest.scala

The 'compaction.max.file-num' is uesless:
- For append bucketed table, this option is equal to `min.file-num`, it is useless.
- For append unaware table, this option has been removed in https://github.com/apache/incubator-paimon/pull/5442

[core] Remove useless 'compaction.max.file-num'

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/NoopStoreSinkWriteState.java

As the class name suggests, `NoopStoreSinkWriteState` should do nothing when `get` and `put` is called, instead of throwing `UnsupportedOperationException`.
This is a simple change without tests.

[flink] NoopStoreSinkWriteState should do nothing instead of throwing UnsupportedOperationException

---

.github/workflows/e2e-tests-flink-1.x-jdk11.yml
.github/workflows/e2e-tests-flink-1.x.yml
.github/workflows/e2e-tests-flink-2.x-jdk11.yml
.github/workflows/publish_snapshot.yml
.github/workflows/utitcase-flink-1.x-jdk11.yml
.github/workflows/utitcase-flink-1.x.yml
.github/workflows/utitcase-flink-2.x-jdk11.yml
.github/workflows/utitcase-spark-4.x.yml
paimon-e2e-tests/README.md
tools/releasing/deploy_staging_jars.sh

This PR adds flink1 profile to deploy and publish process.
See also: #4595, #4768

[hotfix] Add flink1 profile to deploy and publish process

---

docs/content/maintenance/manage-snapshots.md

[doc] not recommended to use asynchronous expiration in batch mode

---

paimon-core/src/main/java/org/apache/paimon/sort/BinaryExternalSortBuffer.java
paimon-core/src/main/java/org/apache/paimon/sort/SpillChannelManager.java
paimon-core/src/test/java/org/apache/paimon/sort/BinaryExternalSortBufferTest.java

In `BinaryExternalSortBuffer`, should not close `channelManager`, because `channelManager` will be used in `BinaryExternalMerger`.
This bug can be produced in the scenario when spill files exceed `maxNumFileHandles`, this kind of scenario is very rare.
`BinaryExternalSortBufferTest.testSpillingAndClearWithMaxFanIn`

[core] Should not close channelManager in BinaryExternalSortBuffer

---

paimon-core/src/main/java/org/apache/paimon/table/sink/KeyAndBucketExtractor.java
paimon-core/src/test/java/org/apache/paimon/table/sink/FixedBucketRowKeyExtractorTest.java

`static int bucket(int hashcode, int numBuckets)` will be called at the row level, remove the checker in it

[core] Remove the checker in bucket function

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java

As discussed in https://github.com/apache/paimon/pull/5430, update docs.

[doc] Exclude deprecated `branch` option

---

docs/content/migration/iceberg-compatibility.md
docs/layouts/shortcodes/generated/iceberg_configuration.html
paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergCommitCallback.java
paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergOptions.java
paimon-core/src/test/java/org/apache/paimon/iceberg/IcebergCommitCallbackTest.java

[core] Support configurable Iceberg metadata path independent of storage type
Linked issue [Feature]: close #5470
This PR introduces a new table option `metadata.iceberg.storage-location` to allow users to configure where Iceberg metadata is stored, independently of the selected metadata.iceberg.storage type.
By default, when using `metadata.iceberg.storage = table-location`, Paimon does not register the table or database in Hive or AWS Glue catalogs. This is expected behavior, but it limits integration with catalog-based systems such as Lake Formation or Iceberg readers that rely on Hive/Glue.
This feature adds support for catalog registration even when using table-location, by decoupling the metadata storage path from the catalog integration logic.
This enables users to:
- Store Iceberg …

[core] Support configurable Iceberg metadata path independent of storage type

---

docs/content/concepts/spec/datafile.md

Fix  `datafile.md` file format, maybe `Table with Primary key Data File` and `Table w/o Primary key Data File` are H3 level, which is easier to understand.

[hotfix] fix markdown heading level

---

.github/workflows/e2e-tests-flink-2.x-jdk11.yml
.github/workflows/utitcase-flink-1.x-jdk11.yml
.github/workflows/utitcase-flink-2.x-jdk11.yml

1. End to End Tests Flink 2.x on JDK 11: 13min -> 9min https://github.com/liyubin117/paimon/actions/runs/14464290242
- should not compile for `-Pflink1,spark3`
2. UTCase and ITCase Flink 2.x on JDK 11: 46min -> 40min https://github.com/liyubin117/paimon/actions/runs/14464290191
- should not compile for `-Pflink1,spark3`
- should use `timeout-minutes`, https://github.com/apache/paimon/actions/runs/14462435680/job/40557390576 takes 360min and waste a lot of resources.
- test phase only be responsible to `test verify` instead of `install` again

[build] Speed up tests execution

---

paimon-common/src/main/java/org/apache/paimon/data/serializer/InternalRowSerializer.java
paimon-core/src/test/java/org/apache/paimon/table/sink/FixedBucketRowKeyExtractorTest.java

This PR extracts some modifications from https://github.com/apache/paimon/pull/5242 to the PR, thanks to [zhongyujiang](https://github.com/zhongyujiang)
The `InternalRowSerializer` needs to maintain the handling of null value for uncompact Decimal and timestamp types in `org.apache.paimon.codegen.GenerateUtils.binaryWriterWriteNull` to avoid inconsistencies in hashcode, which could lead to the inconsistencies in bucket calculation.
```java
def binaryWriterWriteNull(indexTerm: String, writerTerm: String, t: DataType): String =
t.getTypeRoot match {
// ordered by type root definition
case DECIMAL if !Decimal.isCompact(getPrecision(t)) =>
s"$writerTerm.writeDecimal($indexTerm, null, ${getPrecision(t)})"
case TIMESTAMP_WITHOUT_TIME_ZONE | TIMESTAMP_WITH_LOCAL_TIME_ZONE
if …
```

[core] Use write null for uncompact decimal and timestamp in InternalRowSerialize

---

paimon-flink/paimon-flink-1.17/pom.xml
paimon-flink/paimon-flink-1.17/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkTableSource.java

In older Flink versions (for example Flink 1.17), when setting `scan.partitions` to `max_pt()` on a lookup table source, `IllegalArgumentException` will be thrown. This PR fixes the issue.
* `LookupTableITCase`.

[flink] Fix IllegalArgumentException when setting scan.partitions to max_pt() in older Flink versions

---

paimon-core/src/main/java/org/apache/paimon/append/UnawareAppendTableCompactionCoordinator.java
paimon-core/src/test/java/org/apache/paimon/append/UnawareAppendTableCompactionCoordinatorTest.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/CompactProcedureTestBase.scala

TargetFileSize * 50 is too greater for append only table compaction. If 1000 small files, open cost is 4M, then one task will contain 256 * 50 / 4 = 3200 files to compact. It is a great burden for compaction task.

[core] Reduce the file size per append table compaction task

---

paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/compact/PartialUpdateMergeFunctionBenchmark.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java

Improve the performance of PartialUpdateMergeFunction with sequence group.  
We made the following changes:
* Use a List, instead of a Map, to store the `FieldsComparator` and `FieldAggregator` to improve the performance for accessing the `FieldsComparator` and `FieldAggregator`.
* Get the field from the value row when it is needed to avoid the unnecessary heavy call of `FieldGetter#getFieldOrNull`.
* Use an array of booleans to record if the sequence group is empty to avoid duplicate checks for the same sequence group.
The optimization gives about 51% performance boost by the benchmark `PartialUpdateMergeFunctionBenchmark` with empty sequence groups, and 28% without empty sequence groups. According to our experience, the `PartialUpdateMergeFunction#updateWithSequenceGroup` method is …

[core] Improve performance of PartialUpdateMergeFunction with sequence group

---

paimon-core/src/main/java/org/apache/paimon/rest/RESTTokenFileIO.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTest.java

fix refresh token: add log and expire token when in 1 hour.

[core] fix refresh token to earlier refresh and log refresh

---

docs/content/spark/sql-write.md

Reverts apache/paimon#5499 because paimon spark currently does not support this syntax

Revert "[doc] alter streaming write to paimon table grammar"

---

docs/content/flink/procedures.md
docs/content/spark/procedures.md

`options` is a very useful feature, introduced by https://github.com/apache/paimon/pull/4657, we should expose it for users.

[doc] Add missing `options` for related procedures

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/hive/CopyProcessFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/hive/ListHiveFilesFunction.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/procedure/CloneHiveActionITCase.java

When clone hive table to paimon, if target paimon table already exists, check its compatibility with hive table.

[hive][clone] check compatibility if paimon table already exists

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala

Since the introduction of stats reporting to batch jobs, the stability of many online tasks has been affected, and the batch task reporting time is unavailable, seriously affecting stability. We should default to disabling reporting.

[core] Disable PARTITION_IDLE_TIME_TO_REPORT_STATISTIC by default

---

docs/content/concepts/spec/fileindex.md

`column name` and `index name` should be varchar type.

[hotfix] Update fileindex.md

---

paimon-arrow/src/main/java/org/apache/paimon/arrow/ArrowUtils.java
paimon-arrow/src/main/java/org/apache/paimon/arrow/vector/ArrowFormatWriter.java
paimon-arrow/src/main/java/org/apache/paimon/arrow/vector/OneElementFieldVectorGenerator.java
paimon-arrow/src/main/java/org/apache/paimon/arrow/writer/ArrowFieldWriter.java
paimon-arrow/src/main/java/org/apache/paimon/arrow/writer/ArrowFieldWriterFactory.java
paimon-arrow/src/main/java/org/apache/paimon/arrow/writer/ArrowFieldWriterFactoryVisitor.java
paimon-arrow/src/main/java/org/apache/paimon/arrow/writer/ArrowFieldWriters.java

ArrowFieldWriter does not check whether it could write null yet, if the record is null and the field is not nullable, it will meet problem. 
For example, if the target field is `VarChar(length=Integer.MAX_VALUE, nullable=false)`, then
we should throw an exception when we call writer.write(null). Because it could not be null.

[WIP] [Arrow] Adjust ArrowFieldWriterFactory to support nullable with correct parameters

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/DynamicPartitionLoader.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java

If Flink lookup source table is updated by `INSERT OVERWRITE` and `max_pt()` is used to specify partition, lookup join operator might fail to join keys. This PR fixes the issue.
* `LookupJoinITCase`

[flink] Fix lookup failed to join keys when using max_pt() and lookup table is updated by insert overwrite

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/migrate/HiveCloneUtils.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/migrate/HiveMigrator.java

CloneHiveTable would fail when hive table format is unsupported, better to print the table name if the format is unsupported.
N/A
N/A
N/A

[hive][clone] Output the table name if the format is unsupported.

---

paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StaticFromSnapshotStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StaticFromTagStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StaticFromTimestampStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/StaticFromWatermarkStartingScanner.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/TimeTravelUtil.java
paimon-core/src/main/java/org/apache/paimon/table/system/ManifestsTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/TableIndexesTable.java
paimon-core/src/test/java/org/apache/paimon/table/source/snapshot/TimeTravelUtilsTest.java
paimon-core/src/test/java/org/apache/paimon/table/system/ManifestsTableTest.java
paimon-flink/paimon-flink-1.15/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java

[core] Unify timetravel processing to starting scanners

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalog/functions/PaimonFunctions.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/PaimonSparkTestBase.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/SparkWriteITCase.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/TableValuedFunctionsTest.scala

The reason of this is that Spark's timestamp precision is fixed to 6, and in [[BucketFunction.bind]], we use `InternalRowSerializer(bucketKeyRowType)` to convert paimon rows, but the `bucketKeyRowType` is derived from Spark's StructType which will lose the true precision of timestamp, leading to anomalies in bucket calculations.

[spark] Avoid using bucket function for timestamp with spark unsupported precision

---

paimon-core/src/main/java/org/apache/paimon/table/Table.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/execution/CreateOrReplaceTagExec.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonTagDdlTestBase.scala

```
java.util.NoSuchElementException: None.get
at scala.None$.get(Option.scala:529)
at scala.None$.get(Option.scala:527)
at org.apache.paimon.spark.execution.CreateOrReplaceTagExec.run(CreateOrReplaceTagExec.scala:56)
at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
at …
```

[spark] Fix NPE when replace tag if tag exists

---

paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/catalyst/analysis/expressions/ExpressionHelper.scala
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkConnectorOptions.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/expressions/ExpressionHelper.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/util/OptionUtils.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/write/BaseWriteBuilder.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/write/SparkV2Write.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/write/SparkV2WriteBuilder.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/write/SparkWrite.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/write/SparkWriteBuilder.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/write/SparkWriteRequirement.scala
paimon-spark/paimon-spark-ut/src/test/java/org/apache/paimon/spark/catalog/functions/BucketFunctionTest.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/SparkWriteITCase.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/V2WriteRequireDistributionTest.scala

Linked issue: part of https://github.com/apache/paimon/issues/4816
Support spark datasource v2 write path, reduce write serialization overhead and accelerate the process of writing to primary key tables in Spark. Currently only added support for fixed-bucket and bucket unware table, unsupported table types would fallback to v1 write.
V2WriteRequireDistributionTest
SparkV2WriteITCase
No
Added a Spark SQL propertie  `spark.sql.paimon.use-v2-write`

[spark] add spark v2 write

---

paimon-core/src/main/java/org/apache/paimon/table/system/BinlogTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/SystemCatalogTable.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BatchFileStoreITCase.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonSystemTableTest.scala

This PR fixes two problems. 
1. Projection was not be handled.
2. Computed column is not supported.
For example, if you create a able like 
```
CREATE TABLE test_table (a int, b int, c AS a + b)
```
You will get an exception while querying binlog:
`Cannot apply '+' to arguments of type '<INTEGER ARRAY> + <INTEGER ARRAY>'.`. It is complicated to support it because we should handle flink computed column expressions in this occasion.

[core] Fix computed column and projection of BinlogTable

---

docs/layouts/shortcodes/generated/catalog_configuration.html
paimon-common/src/main/java/org/apache/paimon/options/CatalogOptions.java
paimon-core/src/main/java/org/apache/paimon/catalog/CachingCatalog.java
paimon-core/src/test/java/org/apache/paimon/catalog/CachingCatalogTest.java
paimon-core/src/test/java/org/apache/paimon/catalog/TestableCachingCatalog.java

Our previous cache expiration never expired under frequent access, which can cause some problems, such as schema updates that prevent users from seeing the new schema of the table.
So in this PR:
1. Introduce 'cache.expire-after-write'.
2. Rename 'cache.expiration-interval' to 'cache.expire-after-access'.

[core] Introduce 'cache.expire-after-write' to expire a max interval

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/ListCloneFilesFunction.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/migrate/HiveCloneUtils.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/procedure/CloneActionITCase.java

support clone file format including options
Currently, the file format and related configurations of the source hive table are not cloned. The cloned target paimon table uses the default option 'file.format' =  'parquet', which will affect the subsequent writing of the paimon table. For example, after a hive table using orc is cloned to the paimon table and written again, the new file will be in parquet format, which is unexpected. This PR is to fix this problem.

[hive][clone] support clone file format including options

---

paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/HiveSchema.java

To fix issue #5450
This PR addresses three issues related to Hive3 compatibility with Paimon tables:
1. Type Validation Failure for Timestamp LTZ
Hive3 stores the timestamp with local time zone type as timestamp in its metastore, while Paimon explicitly uses the type name timestamp with local time zone during type conversion. Although Hive3 natively supports this type, the metastore's type name mismatch causes validation failures. We resolve this by allowing type compatibility validation to bypass the naming inconsistency.
2. -8-Hour Timezone Offset in Query Results
After fixing the first issue, Hive3 successfully executes DDL operations but returns timestamp values with an incorrect -8-hour offset for the Beijing timezone. The root cause lies in the …

[Bug] throw Hive DDL and paimon schema mismatched excetion when show the table's schema with the timestamp type

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/postpone/PostponeBucketCompactSplitSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/postpone/RewritePostponeBucketCommittableOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/MonitorSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/ReadOperator.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PostponeBucketTableITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/operator/OperatorSourceTest.java

Currently, deletion vectors are not working in postpone bucket tables, because compaction job does not handle index files correctly. This PR fixes the problem.
* `PostponeBucketTableITCase#testDeletionVector`

[flink] Fix deletion vector support for postpone bucket tables

---

paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ParquetSplitReaderUtil.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/ParquetVectorUpdaterFactory.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/VectorizedColumnReader.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/reader/FileTypeNotMatchReadTypeTest.java

If the timestamp field, in paimon, precision is 3. But in file, it is Binary. We will get an exception.
Fix this issue, do the converter for timestamp type and decimal type.

[parquet] Fix timestamp type and decimal type, if the file schema is not correctly match the schema in metadata

---

docs/layouts/shortcodes/generated/core_configuration.html
docs/static/rest-catalog-open-api.yaml
paimon-common/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/ResourcePaths.java
paimon-core/src/main/java/org/apache/paimon/rest/requests/AuthTableQueryRequest.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/CatalogEnvironment.java
paimon-core/src/main/java/org/apache/paimon/table/source/AbstractDataTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/DataTableBatchScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/DataTableStreamScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/InnerTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/ReadBuilderImpl.java
paimon-core/src/main/java/org/apache/paimon/table/source/TableQueryAuth.java
paimon-core/src/main/java/org/apache/paimon/table/system/ReadOptimizedTable.java
paimon-core/src/test/java/org/apache/paimon/rest/MockRESTCatalogTest.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupDataTableScan.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupFileStoreTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/BaseDataTableSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkTableSource.java
paimon-open-api/rest-catalog-open-api.yaml
paimon-open-api/src/main/java/org/apache/paimon/open/api/RESTCatalogController.java

This PR introduces an interface to give Catalog the opportunity to perform column level and row level permission validation on queries.
Introduce Catalog method:
```
/**
* Auth table query select and filter.
*
* @param identifier path of the table to alter partitions
* @param select projection fields
* @param filter query filter
* @throws TableNotExistException if the table does not exist
*/
void authTableQuery(Identifier identifier, List<String> select, List<String> filter)
throws TableNotExistException;
```
Introduce rest api:
```
/v1/{prefix}/databases/{database}/tables/{table}/auth:
post:
tags:
- table
summary: Auth table query
operationId: authTableQuery
parameters:
- name: prefix
in: path
required: true
schema:
type: string
- name: database
in: path
required: true
schema:
type: …
```

[core] Introduce Catalog.authTableQuery to auth query select and filter

---

paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/procedure/CloneActionITCase.java

random tested ddl sql lacks the close quotation mark
https://github.com/apache/paimon/actions/runs/14924626967/job/41926595406
```
Error:  org.apache.paimon.hive.procedure.CloneActionITCase.testCloneWithExistedTable  Time elapsed: 20.755 s  <<< ERROR!
org.apache.flink.table.api.SqlParserException: 
SQL parse failed. Encountered "\'" at line 1, column 166.
Was expecting one of:
<BINARY_STRING_LITERAL> ...
<QUOTED_STRING> ...
<PREFIXED_STRING_LITERAL> ...
<UNICODE_STRING_LITERAL> ...
<BIG_QUERY_DOUBLE_QUOTED_STRING> ...
<BIG_QUERY_QUOTED_STRING> ...
```

[hive][clone] Fix unstable CloneActionITCase#testCloneWithExistedTable

---

paimon-core/src/main/java/org/apache/paimon/crosspartition/GlobalIndexAssigner.java
paimon-core/src/main/java/org/apache/paimon/crosspartition/IndexBootstrap.java
paimon-core/src/main/java/org/apache/paimon/table/sink/RowPartitionAllPrimaryKeyExtractor.java
paimon-core/src/test/java/org/apache/paimon/crosspartition/IndexBootstrapTest.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/InsertOverwriteTableTestBase.scala

If the partition columns contain primary key, cross partition insertion would fail.
```sql
create table pk_pt (c1 int) partitioned by(p1 string, p2 string) tblproperties('primary-key'='c1, p1')
insert into table pk_pt partition(p1, p2) values(1, 'a', 'b'), (1, 'b', 'b')
```
```
RootCause:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 1.0 (TID 701)failed with no retrying exception: Lost task 1.0 in stage 1.0 (TID 701) (33.212.14.188 executor ): java.lang.IllegalArgumentException: Field names must be unique. Found duplicates: [category]
Caused by: java.lang.IllegalArgumentException: Field names must be unique. Found duplicates: [category]
TraceStack:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 1.0 (TID 701)failed …
```

[CORE] Fix dynamic insert into table with partition columns contain primary key error

---

paimon-common/src/main/java/org/apache/paimon/table/BucketMode.java
paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PrimaryKeyPartialLookupTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CompactorSinkBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/BaseDataTableSource.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FlinkJobRecoveryITCase.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/write/PaimonWriteRequirement.scala

The previous `HASH_FIXED` pattern already assumed that the `bucket` was a positive value, which is already assumed in many engines. We need to introduce a new mode to Postpone Bucket to avoid bugs.
For example, Spark bucketed Join.
We should add tests for Spark postpone bucket reading, but currently, we lack the Table API for compact postpone bucket table. We should add these table api later.

[core] Postpone bucket should introduce a new BucketMode

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/Committer.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RestoreAndFailCommittableStateManager.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCommitter.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreMultiCommitter.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionListener.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionListeners.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionMarkDone.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/ReportPartStatsListener.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/PartitionMarkDoneTest.java

In our production environment, we use Flink bounded stream job write data to Paimon table. We use the 'partition mark done' feature to make downstream knows that our Flink bounded stream job has finished. But we found multi partition mark down will be trigger when :
1、Some writer task has finished.
2、Enable checkpoint.
3、Failover.
After troubleshooting, we found the reason is when some wirte task finish, follow code will be called:
Then when failover, the committer operator will mark partition done:
Finally, Our downstream started consuming before the Flink bounded stream job was completely finished, resulting in data loss online.
So, after discuss offline, we think when failover, no need to call PartitionListeners#notifyCommittable.

[Bug] Fix bug of redundant mark partition done

---

paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetReaderFactory.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/ParquetSchemaConverter.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/reader/FileTypeNotMatchReadTypeTest.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/reader/SimpleGroupWriteSupport.java

Parquet list may have two level representation protos.
For example, this is a standard two level list type protobuf schema in parquet:
```
ParquetSchemaExampleB {
required group list_of_ints (LIST) {
repeated int32 list_of_ints_tuple;
}
}
```
While this is the three level representation:
```
ParquetSchemaExampleA {
optional group list_of_ints (LIST) {
repeated group list {
required int32 element;
}
}
}
```
see link: https://impala.apache.org/docs/build/html/topics/impala_parquet_array_resolution.html

[parquet] Support parquet two level list type protobuf representation

---

docs/content/concepts/rest/overview.md
docs/content/program-api/catalog-api.md
docs/content/program-api/flink-api.md
docs/content/program-api/java-api.md
docs/content/program-api/python-api.md
docs/content/program-api/rest-api.md
paimon-api/README.md
paimon-api/src/main/java/org/apache/paimon/PagedList.java
paimon-api/src/main/java/org/apache/paimon/rest/HttpClient.java
paimon-api/src/main/java/org/apache/paimon/rest/RESTApi.java
paimon-api/src/main/java/org/apache/paimon/rest/RESTObjectMapper.java
paimon-api/src/main/java/org/apache/paimon/rest/auth/DLFAuthProvider.java
paimon-api/src/main/java/org/apache/paimon/rest/auth/DLFECSTokenLoader.java
paimon-api/src/main/java/org/apache/paimon/rest/auth/DLFLocalFileTokenLoader.java
paimon-api/src/main/java/org/apache/paimon/utils/StringUtils.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTTokenFileIO.java
paimon-core/src/test/java/org/apache/paimon/rest/MockRESTCatalogTest.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTApiJsonTest.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTest.java
paimon-core/src/test/java/org/apache/paimon/rest/TestHttpWebServer.java
paimon-core/src/test/java/org/apache/paimon/rest/auth/AuthProviderTest.java
paimon-core/src/test/java/org/apache/paimon/rest/auth/DLFAuthSignatureTest.java

Nest step after https://github.com/apache/paimon/pull/5607
```java
import org.apache.paimon.options.Options;
import org.apache.paimon.rest.RESTApi;
import java.util.List;
import static org.apache.paimon.options.CatalogOptions.WAREHOUSE;
import static org.apache.paimon.rest.RESTCatalogOptions.DLF_ACCESS_KEY_ID;
import static org.apache.paimon.rest.RESTCatalogOptions.DLF_ACCESS_KEY_SECRET;
import static org.apache.paimon.rest.RESTCatalogOptions.TOKEN_PROVIDER;
import static org.apache.paimon.rest.RESTCatalogOptions.URI;
public class RESTApiExample {
public static void main(String[] args) {
Options options = new Options();
options.set(URI, "<catalog server url>");
options.set(WAREHOUSE, "my_instance_name");
options.set(TOKEN_PROVIDER, "dlf");
options.set(DLF_ACCESS_KEY_ID, …
```

[core] Introduce paimon-api module for light rest api, part 3

---

docs/static/rest-catalog-open-api.yaml
paimon-api/src/main/java/org/apache/paimon/function/Function.java
paimon-api/src/main/java/org/apache/paimon/function/FunctionImpl.java
paimon-api/src/main/java/org/apache/paimon/rest/RESTApi.java
paimon-api/src/main/java/org/apache/paimon/rest/ResourcePaths.java
paimon-api/src/main/java/org/apache/paimon/rest/requests/CreateFunctionRequest.java
paimon-api/src/main/java/org/apache/paimon/rest/responses/GetFunctionResponse.java
paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/test/java/org/apache/paimon/rest/MockRESTMessage.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTest.java

Linked issue: #5420
update function api
- function belong to database
- inputParams and returnParams is optional

[core] fix: function need belong to database

---

paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/FlinkGenericCatalogITCase.java

…te hive catalog exception: no wirte permissions for root directory /
"Improved local testing in flink generic catalog IT case class. Create hive catalog exception: no wirte permissions for root directory `/`.
exception:
```
java.io.UncheckedIOException: org.apache.hadoop.security.AccessControlException: Permission denied: user=zhuangchong, access=WRITE, inode="/":omm:supergroup:drwxr-xr-x
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:410)
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:258)
...
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1761)
at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2911)
at …
```

[test] Local tests exceptionally no write permission when creating Hive catalog

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkGenericCatalog.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/FlinkGenericCatalogITCase.java

Linked issue: close #5489
By default, use the Paimon catalog to create the view. Create views with options is not supported.

[flink] by default, use paimon catalog to create views in flink generic catalog.

---

paimon-core/src/main/java/org/apache/paimon/table/sink/ChannelComputer.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/postpone/PostponeBucketCompactSplitSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/PostponeBucketChannelComputer.java

Currently in `ChannelComputer`, if `partition.hashCode()` equals to `Integer.MIN_VALUE`, the resulting channel will also be negative. This PR fixes the issue.
None.

[core] Start channel should not be negative when partition.hashCode() equals to Integer.MIN_VALUE

---

paimon-core/src/main/java/org/apache/paimon/tag/TagBatchCreation.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonTagDdlTestBase.scala

Table set `tag.num-retained-max=1`, batch write twice, the total tag is empty after the sencond write.
```sql
set spark.paimon.tag.batch.customized-name=tag-1;
insert into tb (1, 'a');  // generate tag-1
set spark.paimon.tag.batch.customized-name=tag-2;
insert into tb (2, 'b');   // both tag-1 and tag-2 expired
```

[hotfix] Fix tag expiration is unexpect for batch write

---

docs/content/primary-key-table/merge-engine/partial-update.md
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/PartialUpdateMergeFunction.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PartialUpdateITCase.java

1. check ignore-delete and remove-record-on-sequence-group cannot be enabled at the same time
2. optimize sequenceFields from storage field names to field indexes to reduce duplicate operations

[core]Improve partial update merge engine configuration ignore-delete and remove-record-on-sequence-group cannot be enabled at the same time.

---

docs/static/rest-catalog-open-api.yaml
paimon-api/src/main/java/org/apache/paimon/rest/RESTApi.java
paimon-api/src/main/java/org/apache/paimon/rest/responses/AuthTableQueryResponse.java
paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/table/CatalogEnvironment.java
paimon-core/src/main/java/org/apache/paimon/table/source/AbstractDataTableScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/TableQueryAuth.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java

For row level access control, the general design is to add additional filtering conditions to make users see less data, so we need to return additional filtering instead of passing the filtering conditions to the server.

[rest] Adjust auth table for row level access control

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/CompactStrategy.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactManager.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactTask.java
paimon-core/src/test/java/org/apache/paimon/iceberg/IcebergCompatibilityTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/DeletionVectorITCase.java

In deletion-vector mode, all deletion vector index should be removed and the corresponding data files should be rewrite after full compaction. But for the following case below:
Only one file in maxLevel, and using `DELETE` sql to delete some records, it'll generate a dv for the file in maxLevel. When performing full compaction, it' possible that the file won't be picked for compaction, causing that the dv index can't be totally removed after full compaction which is unexpected.
DeletionVectorITCase#testRemoveDvsAfterFullCompaction: test whether we can select the correct data after disabling dv.

[core] pick large files which have dv index for full compaction

---

paimon-core/src/main/java/org/apache/paimon/AppendOnlyFileStore.java
paimon-core/src/main/java/org/apache/paimon/FileStore.java
paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java
paimon-core/src/main/java/org/apache/paimon/postpone/PostponeBucketFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/postpone/PostponeBucketWriter.java
paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedFileStore.java
paimon-core/src/main/java/org/apache/paimon/privilege/PrivilegedFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/AppendOnlyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/DelegatedFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/FileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/object/ObjectTable.java
paimon-flink/paimon-flink-cdc/pom.xml
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcPostponeBucketChannelComputer.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperator.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcSinkBuilder.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkITCase.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncTableSinkITCase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTablesStoreCompactOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/NoopStoreSinkWriteState.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RowAppendTableSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCompactOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWriteImpl.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWriteState.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWriteStateImpl.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/TableWriteOperator.java

This PR supports postpone bucket tables in Paimon CDC, both for syncing tables and syncing databases.
* `FlinkCdcSyncTableSinkITCase#testRandomCdcEventsPostponeBucket`
* `FlinkCdcSyncDatabaseSinkITCase#testRandomCdcEventsPostponeBucket`

[cdc] Support postpone bucket tables in Paimon CDC

---

docs/content/maintenance/dedicated-compaction.md

In the CALL sys.compact example, partition_idle_time as a key name is incorrectly written with single quotes:
`  CALL sys.compact(`table` => 'default.T', 'partition_idle_time' => '1 d')`
It should be:
`  CALL sys.compact(`table` => 'default.T', partition_idle_time => '1 d')`
This PR fixes the syntax to avoid confusion.
Before fix:
```
Flink SQL> CALL sys.compact(`table` => 'default.word_count', 'partition_idle_time' => '1 d');
[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.sql.parser.impl.ParseException: Encountered "=>" at line 1, column 73.
```
After fix:
```
Flink SQL> CALL sys.compact(`table` => 'default.word_count', partition_idle_time => '1 d');
+----------------------------------------+
|                                 result | …
```

[hotfix] [doc] Fix invalid syntax for partition_idle_time in sys.compact example

---

paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapper.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeFunction.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapperTest.java

Linked issue: close #5631
`org.apache.paimon.mergetree.compact.LookupChangelogMergeFunctionWrapperTest#testKeepLowestHighLevel`

[core] keep lowest high-level kv for lookup compaction.

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncJobHandler.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarActionUtils.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/pulsar/PulsarActionITCaseBase.java

flink-connector-pulsar 4.1.0+ remove PulsarOptions#PULSAR_ADMIN_URL option, pulsar cdc compatible with flink-connector-pulsar version 4.1.0
https://github.com/apache/flink-connector-pulsar/blob/v4.1.0/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/PulsarSourceBuilder.java#L154-L158
https://github.com/apache/flink-connector-pulsar/blob/v4.1.0/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/config/PulsarOptions.java

[cdc] pulsar cdc compatible with flink-connector-pulsar version 4.1.0

---

docs/layouts/shortcodes/generated/flink_connector_configuration.html
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CombinedTableCompactorSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/Committer.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/CommitterOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkWriteSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RestoreAndFailCommittableStateManager.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCommitter.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreMultiCommitter.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionListener.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionListeners.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionMarkDone.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/ReportPartStatsListener.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/PartitionMarkDoneTest.java

After https://github.com/apache/paimon/pull/5581, we found a potential bug:
When a checkpoint finished, it should notify PartitionMarkDone in ComminterOperator#notifyCheckpointComplete. But failover before call ComminterOperator#notifyCheckpointComplete. 
Then after restarted, RestoreAndFailedCommittableStateManager#recover will be called, the PartitionMarkDone will not notify, which miss the PartitionMarkDone.
So we add an option here which means whether trigger partition mark done when recover from state, the default value is true.

[Flink] Hot fix of partition mark down bug.

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/clone/HiveCloneExtractor.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/clone/HiveCloneUtils.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/clone/HiveTableCloneExtractor.java
paimon-hudi/src/main/java/org/apache/paimon/hudi/HudiFileIndex.java
paimon-hudi/src/main/java/org/apache/paimon/hudi/HudiHiveCloneExtractor.java

CloneHive tool meets problem when clone Hudi table to paimon, which is caused by some necessary FileSystem configuration not passed to Hudi connector.

[hudi][clone] Fix Hudi clone to pass configuration for Hudi extractFiles

---

paimon-common/src/main/java/org/apache/paimon/fileindex/bitmap/BitmapFileIndexMetaV2.java
paimon-common/src/test/java/org/apache/paimon/fileindex/bitmapindex/BitmapFileIndexTest.java

When all values ​​are empty, a null pointer exception will be generated during the serialization of bitmap index v2.
org.apache.paimon.fileindex.bitmapindex.BitmapFileIndexTest::testAllNull

[core] Fix npe problem in bitmap file index v2

---

paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
paimon-core/src/main/java/org/apache/paimon/table/ExpireSnapshotsImpl.java

```
INFO  org.apache.paimon.operation.FileStoreCommitImpl [] - Ready to commit to table T, number of commit messages: 2
INFO  org.apache.paimon.operation.FileStoreCommitImpl [] - Finished collecting changes, including: 2 append table files
INFO  org.apache.paimon.operation.FileStoreCommitImpl [] - Successfully commit snapshot 1 to table T by user 9565778e-6649-429b-9ca9-f0cca34bc44b with identifier 9223372036854775807 and kind APPEND.
INFO  org.apache.paimon.operation.FileStoreCommitImpl [] - Finished commit to table T, duration 77 ms
```

[core] Add more commit info logs

---

docs/static/rest-catalog-open-api.yaml
paimon-api/src/main/java/org/apache/paimon/rest/RESTApi.java
paimon-api/src/main/java/org/apache/paimon/rest/ResourcePaths.java
paimon-api/src/main/java/org/apache/paimon/rest/responses/GetVersionSnapshotResponse.java
paimon-api/src/main/java/org/apache/paimon/rest/responses/ListSnapshotsResponse.java
paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTest.java

Make the display of snapshots simpler, without having to read files, but relying on catalog service to query.
This PR adds:
```java
/**
* Return the snapshot of table for given version. Version parsing order is:
*
* <ul>
*   <li>1. If it is 'EARLIEST', get the earliest snapshot.
*   <li>2. If it is 'LATEST', get the latest snapshot.
*   <li>3. If it is a number, get snapshot by snapshot id.
*   <li>4. Else try to get snapshot from Tag name.
* </ul>
*
* @param identifier Path of the table
* @param version version to snapshot
* @return The requested snapshot
* @throws Catalog.TableNotExistException if the target does not exist
* @throws UnsupportedOperationException if the catalog does not {@link
*     #supportsVersionManagement()}
*/
Optional<Snapshot> loadSnapshot(Identifier identifier, …
```

[core] Add load version snapshot and list snapshots to Catalog

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala

like https://github.com/apache/paimon/pull/5623

[spark] Avoid partition to be negative when partition.hashCode() equals to Integer.MIN_VALUE

---

paimon-core/src/main/java/org/apache/paimon/table/FallbackReadFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/source/DataSplit.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BranchSqlITCase.java

Currently in `FallbackReadFileStoreTable#Read`, if data split has no primary key, it will be regarded as data from main branch. However, this is not true if both main branch and fallback branch have no primary key.
* `BranchSqlITCase#testMainAndFallbackNoPrimaryKeys`.

[core] Fix bug when both main branch and fallback branch have no primary key

---

docs/static/rest-catalog-open-api.yaml
paimon-api/src/main/java/org/apache/paimon/rest/RESTApi.java
paimon-api/src/main/java/org/apache/paimon/rest/requests/CommitTableRequest.java
paimon-core/src/main/java/org/apache/paimon/catalog/AbstractCatalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/CatalogSnapshotCommit.java
paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/main/java/org/apache/paimon/table/CatalogEnvironment.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTest.java

Consider situation:
1. Create a table named "a".
2. Run streaming job to write "a".
3. Drop table.
4. Create a new table named "a".
The streaming job may write wrong snapshot to new table, causing abnormal table status that cannot be restored.
We can add tableId to commit snapshot method, server can check the id should be the correct id.

[core][rest] Add tableId to commit snapshot to avoid wrong commit

---

paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/spark/sql/execution/shim/PaimonCreateTableAsSelectStrategy.scala
paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/spark/sql/execution/shim/PaimonCreateTableAsSelectStrategy.scala
paimon-spark/paimon-spark-3.4/src/main/scala/org/apache/spark/sql/execution/shim/PaimonCreateTableAsSelectStrategy.scala
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/SparkCatalog.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/catalog/FormatTableCatalog.java
paimon-spark/paimon-spark-common/src/main/java/org/apache/paimon/spark/catalog/SparkBaseCatalog.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkSource.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/execution/shim/PaimonCreateTableAsSelectStrategy.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DDLTestBase.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTestBase.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/FormatTableTestBase.scala

Currently, because Spark DSv2 does not support writing partitioned tables, the partitioned format table created by ctas is not written to the partition normally, so throw exception for now

[spark] Throw exception when creating partitioned table via CTAS

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/SchemaChangeITCase.java

This PR adds support for map value type and array element type evolution. For ex: ARRAY<INT> -> ARRAY<BIGINT>
As of today there is no support for evolution map value type and array element type. This change adds support for the same. Consider the case as follows:
```
- CREATE CATALOG paimon WITH ('type' = 'paimon', 'warehouse' = 'file:/Users/ashish/Documents/flink-1.20.1/paimon_warehouse');
- USE CATALOG paimon;
- CREATE TABLE evolution_test(field1 INT, field2 ARRAY<INT>, PRIMARY KEY (field1) NOT ENFORCED);
- ALTER TABLE evolution_test MODIFY field2 ARRAY<BIGINT>;
- CREATE TABLE evolution_test1(field1 INT, field2 ARRAY<ROW(f1 INT, f2 INT) NOT NULL>);
- ALTER TABLE evolution_test1 MODIFY field2 ARRAY<ROW(f1 INT, f2 INT)>;
With the added support both the above …
```

[paimon-core] Add support for map value type and array element type evolution

---

paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
paimon-flink/paimon-flink-1.16/src/test/java/org/apache/paimon/flink/iceberg/Flink116IcebergITCase.java
paimon-flink/paimon-flink-1.17/src/test/java/org/apache/paimon/flink/iceberg/Flink117IcebergITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/iceberg/FlinkIcebergITCaseBase.java

Issue:  https://github.com/apache/paimon/pull/5570
Relates to https://github.com/apache/paimon/pull/5570
I will use Iceberg tags in production soon and want replace_tag to update Iceberg metadata. Otherwise the Iceberg tags can become inconsistent with Paimon tags.
In https://github.com/apache/paimon/pull/4346#discussion_r1807119066 there was discussion of not adding callbacks on tag replace. For Iceberg it makes sense. The other callbacks - success file and add partition - may not be idempotent so I only added the Iceberg callback.

[core] Call Iceberg callback on replace_tag procedure

---

paimon-hive/paimon-hive-connector-3.1/src/main/java/org/apache/paimon/hive/objectinspector/PaimonTimestampLocalTZObjectInspector.java
paimon-hive/paimon-hive-connector-3.1/src/test/java/org/apache/paimon/hive/objectinspector/PaimonTimestampLocalTZObjectInspectorTest.java

Linked issue: open #5568
This PR fixes time zone offset issues in the Hive connector when handling the `timestamp with local time zone` data type. To explain the problem, we first introduce two semantic interpretations of timestamps: **Instant semantics** and **Local semantics**.
Instant semantics corresponds to timestamp with local time zone (equivalent to Flink's TIMESTAMP_LTZ type). It stores a fixed UTC timestamp, which is displayed according to the user's current process or session time zone. Users in different time zones see different local times, but they all represent the same absolute moment. The following Java code demonstrates Instant semantics:
```java
// Instant semantics
long nowMs = System.currentTimeMillis();
System.out.println(Instant.ofEpochMilli(nowMs).atZone(TimeZone.ge …
```

[Bug] The Hive connector encounters time offset issues when reading and writing data of the timestamp with local time zone field type.

---

paimon-api/src/main/java/org/apache/paimon/function/FunctionNameValidator.java
paimon-api/src/main/java/org/apache/paimon/rest/RESTApi.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTest.java

Function name is allowed to contain characters such as letters (a-zA-Z), numbers (0-9), dots (.), hyphens (-), underscores (_), and must contain letters.
- RESTCatalogTest.testValidateFunctionName
- RESTCatalogTest.testFunction

[core] fix: add function name validate

---

paimon-core/src/main/java/org/apache/paimon/iceberg/IcebergCommitCallback.java

Linked issue: close https://github.com/apache/paimon/issues/5700
It seems there was a regression in how CDC ingestion syncs Paimon and Iceberg metadata in `IcebergCommitCallback`. The `FileStoreTable` object passed to the committer may not be refreshed.
This PR resolves the problem discussed in the attached issue.
```
cat ~/.paimon-data/warehouse/default.db/test_table/metadata/v2.metadata.json | jq '.schemas[]'
{
"type": "struct",
"schema-id": 0,
"fields": [
{
"id": 0,
"name": "field1",
"required": false,
"type": "int",
"doc": null
},
{
"id": 1,
"name": "field2",
"required": false,
"type": "float",
"doc": null
}
]
}
{
"type": "struct",
"schema-id": 1,
"fields": [
{
"id": 0,
"name": "field1",
"required": false,
"type": "int",
"doc": null
},
{
"id": 1,
"name": "field2",
"required": false, …
```

[core] Refactored schema ID retrieval to use latest schema

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileStoreSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/FlinkSourceBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/SystemTableSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedContinuousFileSplitEnumerator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/align/AlignedContinuousFileStoreSource.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/operator/MonitorSource.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumeratorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/align/AlignedContinuousFileSplitEnumeratorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/source/align/AlignedSourceReaderTest.java

FlinkSourceBuilder use `BucketMode.HASH_FIXED` as default argument. I think it's confusing.

[refactor] Refactor flink source to get rid of confusing BucketMode argument

---

paimon-core/src/main/java/org/apache/paimon/index/HashBucketAssigner.java
paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java

Just like #5680, this PR creates a `latestSnapshotOfUserFromFileSystem` method in `SnapshotManager` and use it in writers Because `latestSnapshotOfUser` will query from REST catalog (if the table is created from REST catalog) and we don't want to flood the catalog with high concurrency.

[core] Don't use snapshotManager.latestSnapshotOfUser in writers to prevent flooding catalog

---

docs/layouts/shortcodes/generated/flink_connector_configuration.html
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSink.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcSyncDatabaseSinkBuilder.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSinkTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java

This is a convenient way for users to set writer cpu and memory.

[flink] Writer operator support SlotSharingGroup settings

---

paimon-core/src/main/java/org/apache/paimon/operation/ChangelogDeletion.java
paimon-core/src/main/java/org/apache/paimon/operation/TagDeletion.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/RollbackHelper.java
paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java
paimon-core/src/test/java/org/apache/paimon/table/IndexFileExpireTableTest.java
paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeySimpleTableTest.java
paimon-core/src/test/java/org/apache/paimon/table/SimpleTableTestBase.java

At present, rollback is a relatively dangerous operation. It not only deletes unnecessary snapshots, but also cleans up all unnecessary data files, which makes it very prone to problems. Once there is a bug, it will cause the table to malfunction.
Actually, rollback is a very low-frequency operation, and we don't need to clean up all the unnecessary data files. Just leave it to orphan file clean.

[core] Simplify rollback to only clean snapshots

---

paimon-core/src/main/java/org/apache/paimon/stats/SimpleStats.java

Reduce 300 bytes in memory per `DataFileMeta`.

[core] Optimize DataFileMeta.keyStats to EMPTY_STATS to reduce memory usage

---

pom.xml

When using Mac OS and JAVA_HOME is not set.
exec : mvn clean deploy -DskipTests -Drat.skip=true -Pdocs-and-source 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project paimon-api: MavenReportException: Error while creating archive: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. 
```
This is `maven-javadoc-plugin:2.9.1` 's bug  and  I compared the versions of `maven-javadoc-plugin` of other open source components. At least 3.x or above. I think it's time to upgrade the plugin.
Relation issue : 
https://stackoverflow.com/questions/20313453/java-home-on-osx-with-eclipse-and-maven
https://github.com/apache/flink/pull/25265

[fix] Update maven javadoc plugin.

---

paimon-core/src/main/java/org/apache/paimon/tag/TagPreview.java

AuditLogTable (DataTable) also supports reading tags.

[hotfix] TagPreview utils support DataTable

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-api/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
paimon-core/src/test/java/org/apache/paimon/table/sink/TableCommitTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RescaleAction.java

Consider the following scenario: For a postpone bucket table, when a rescale job is running, another compact job commits. However, as the rescale job is started without knowing the COMMIT snapshot, the resulting snapshot will not include its changes and the data is lost.
This PR adds a "strict mode" for commit, where commit is aborted if committer found another user's COMPACT / OVERWRITE snapshot.
* `TableCommitTest#testStrictMode`.
Document is updated.

[core] Introduce commit strict mode to avoid data loss in rescale job

---

paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommit.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
paimon-core/src/main/java/org/apache/paimon/table/sink/TableCommitImpl.java
paimon-core/src/test/java/org/apache/paimon/TestAppendFileStore.java
paimon-core/src/test/java/org/apache/paimon/TestFileStore.java
paimon-core/src/test/java/org/apache/paimon/operation/FileStoreCommitTest.java
paimon-core/src/test/java/org/apache/paimon/operation/FileStoreTestUtils.java
paimon-core/src/test/java/org/apache/paimon/operation/TestCommitThread.java

In https://github.com/apache/incubator-paimon/pull/5703 , there is properties in `ManifestCommittable`.
We don't need properties field in FileStoreCommit.commit.

[core] Remove properties field in FileStoreCommit.commit

---

pom.xml

Bump the Scala version to the latest one

chore: bump Scala version to 2.13.16 & 2.12.20

---

paimon-spark/paimon-spark-ut/src/test/java/org/apache/paimon/spark/SparkCatalogWithHiveTest.java
paimon-spark/paimon-spark-ut/src/test/java/org/apache/paimon/spark/SparkGenericCatalogWithHiveTest.java
paimon-spark/paimon-spark-ut/src/test/java/org/apache/paimon/spark/catalog/functions/BucketFunctionTest.java

drop database created in testBuildWithHive
```
Error:  org.apache.paimon.spark.SparkGenericCatalogWithHiveTest.testBuildWithHive(Path)  Time elapsed: 0.058 s  <<< ERROR!
org.apache.spark.sql.catalyst.analysis.NamespaceAlreadyExistsException: 
[SCHEMA_ALREADY_EXISTS] Cannot create schema `my_db` because it already exists.
Choose a different name, drop the existing schema, or add the IF NOT EXISTS clause to tolerate pre-existing schema.
```

[test][spark] Fix the unstable testHiveCatalogOptions  

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/format/debezium/DebeziumSchemaUtils.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/format/debezium/DebeziumSchemaUtilsTest.java

Linked issue: https://github.com/apache/paimon/issues/4912
Currently debezium schema format does not have any support to convert avro type ENUM. Without this change paimon fails with error:
```
Caused by: java.lang.UnsupportedOperationException: Don't support avro type 'ENUM' yet.
at org.apache.paimon.flink.action.cdc.format.debezium.DebeziumSchemaUtils.fromDebeziumAvroType(DebeziumSchemaUtils.java:514)
at org.apache.paimon.flink.action.cdc.format.debezium.DebeziumSchemaUtils.avroToPaimonDataType(DebeziumSchemaUtils.java:435)
at org.apache.paimon.flink.action.cdc.format.debezium.DebeziumAvroRecordParser.extractRowData(DebeziumAvroRecordParser.java:158)
at org.apache.paimon.flink.action.cdc.format.debezium.DebeziumAvroRecordParser.processRecord(DebeziumAvroRecordParser.java:117)
at …
```

[flink] Add support for AvroType enum for debezium format

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-api/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/append/BucketedAppendCompactManager.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/CompactStrategy.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactManager.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/MergeTreeCompactTask.java
paimon-core/src/main/java/org/apache/paimon/operation/BucketedAppendFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java
paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java
paimon-core/src/test/java/org/apache/paimon/append/BucketedAppendCompactManagerTest.java
paimon-core/src/test/java/org/apache/paimon/append/FullCompactTaskTest.java
paimon-core/src/test/java/org/apache/paimon/format/FileFormatSuffixTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/MergeTreeTestBase.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/MergeTreeCompactManagerTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/procedure/CompactProcedureITCase.java

Linked issue:  #3627
Make a full compaction to the chosen external paths.
Usage: 
```
CALL sys.compact(table => 'xxxx', partition_idle_time =>'7d', options => 'compaction.force-compact-all-files=true,data-file.external-paths.strategy=specific-fs,data-file.external-paths.specific-fs=oss');
```
note that table `xxxx` should have at least one external path whose scheme is prefixed with 'oss'.
org.apache.paimon.flink.procedure.CompactProcedureITCase#testExternalCompact
Add a new table option `compaction.force-compact-all-files`, which should usually be dynamically configured in a compaction procedure.
added

[core] Support dedicated full compact to external paths

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcAppendTableSink.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcAppendTableWriteOperator.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendTableSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSinkBuilder.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkWriteSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/PostponeBucketSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RestoreAndFailCommittableStateManager.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/RestoreCommittableStateManager.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/BatchWriteGeneratorTagOperatorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/StoreMultiCommitterTest.java

PostponeBucketSink and AppendTableSink do not need to have state and intended failure, Because its writing does not read snapshots

[flink] Make PostponeBucketSink no state and no intended failure

---

paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java
paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java
paimon-core/src/main/java/org/apache/paimon/operation/AbstractFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/postpone/PostponeBucketFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/postpone/PostponeBucketWriter.java
paimon-core/src/main/java/org/apache/paimon/utils/SinkWriter.java
paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeySimpleTableTest.java

To prevent the situation of OOM caused by users writing too many partitions.

[core] Introduce auto-buffer-spill for postpone bucket write

---

paimon-flink/paimon-flink-1.15/pom.xml
paimon-flink/paimon-flink-1.16/pom.xml
paimon-flink/paimon-flink-1.17/pom.xml
paimon-flink/paimon-flink-1.18/pom.xml
paimon-flink/paimon-flink-1.19/pom.xml
paimon-flink/paimon-flink-1.20/pom.xml
paimon-flink/paimon-flink-2.0/pom.xml
paimon-flink/paimon-flink-cdc/pom.xml
paimon-flink/paimon-flink-common/pom.xml
paimon-flink/pom.xml
pom.xml

This PR fixes the bug that `update_branch_version.sh` does not work for paimon-flink1-common and paimon-flink2-common.
* Extracts paimon-flinkx-common from paimon-flink-common's jar
Manually verified that `update_branch_version.sh` could now work on all pom.xml.

[flink] Fix paimon-flink-2.0 releasing process

---

paimon-flink/paimon-flink-1.18/src/main/java/org/apache/paimon/flink/procedure/MarkPartitionDoneProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/MarkPartitionDoneAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/MarkPartitionDoneProcedure.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCommitter.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/CommitListener.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/CommitListeners.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/PartitionMarkDoneListener.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/partition/ReportPartStatsListener.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/CustomPartitionMarkDoneActionTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/partition/PartitionMarkDoneTest.java

1. It should be CommitListener
2. Do not add `partitionMarkDoneRecoverFromState` to CommitListener

[core] Rename PartitionListener to CommitListener

---

docs/static/rest-catalog-open-api.yaml
paimon-api/src/main/java/org/apache/paimon/rest/RESTApi.java
paimon-api/src/main/java/org/apache/paimon/rest/responses/ListTablesGloballyResponse.java
paimon-api/src/main/java/org/apache/paimon/rest/responses/ListViewsGloballyResponse.java
paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java
paimon-core/src/main/java/org/apache/paimon/catalog/DelegateCatalog.java
paimon-core/src/main/java/org/apache/paimon/rest/RESTCatalog.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTest.java

optimize return type of ListTablesGlobally & ListViewsGlobally
RestCatalogTest.testListTablesPagedGlobally
RestCatalogTest.testListViewsPagedGlobally
rest-catalog-open-api.yaml: listTablesGlobally & listViewsGlobally

[hotfix] Rest: optimize return type of ListTablesGlobally & ListViewsGlobally

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-api/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/utils/StatsCollectorFactories.java
paimon-core/src/test/java/org/apache/paimon/utils/StatsCollectorFactoriesTest.java

Users may not want to config the stats column by column, so I add a config to support keeping a fixed number columns' stats in metadata. The rest columns' stats will be set to none.
org.apache.paimon.utils.StatsCollectorFactoriesTest#testPrefixStats
no
added

[core] Add a config to support keeping first N columns' stats in metadata.

---

docs/content/flink/consumer-id.md
docs/content/learn-paimon/understand-files.md
docs/content/maintenance/dedicated-compaction.md
docs/content/maintenance/filesystems.md
docs/content/maintenance/manage-branches.md
docs/content/maintenance/manage-snapshots.md
docs/content/maintenance/manage-tags.md

The space after \ will cause failure when executing command.

[doc] remove spaces after backslash which will cause bash command execution fail

---

paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
paimon-core/src/test/java/org/apache/paimon/operation/FileStoreCommitTest.java
paimon-core/src/test/java/org/apache/paimon/rest/MockRESTCatalogTest.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogServer.java

We can retry commit in `FileStoreCommitImpl` when exception. This can significantly improve the robustness of the code.
1. Remove file reusing in `RetryResult`.
2. Add retry when commit exception.
In `MockRESTCatalogTest`.

[core] Optimize commit retry on exception

---

paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexFormat.java

When I study the code of FileIndexFormat. I found that there are some details in the code comments and the top "image" of the class that do not match. 
In order to reduce misunderstandings among other students, now I have fixed these typos.

[Typo] Fix typo in FileIndexFormat.

---

paimon-core/src/main/java/org/apache/paimon/KeyValueFileStore.java
paimon-core/src/main/java/org/apache/paimon/table/source/DataTableBatchScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/DataTableStreamScan.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReader.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
paimon-core/src/main/java/org/apache/paimon/table/system/AuditLogTable.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CompactAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/RescaleAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/LookupDataTableScan.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/postpone/PostponeBucketCompactSplitSource.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PostponeBucketTableITCase.java

Currently, streaming read can't be performed on postpone bucket tables with `none` changelog producer. This PR fixes the bug.
* `PostponeBucketTableITCase#testNoneChangelogProducer`.

[core] Fix streaming read bug in postpone bucket tables when changelog producer is none

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/ScanHelper.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/procedure/BranchProcedureTest.scala

fix
```
Caused by: java.lang.ClassCastException: org.apache.paimon.table.source.DataSplit cannot be cast to org.apache.paimon.table.FallbackReadFileStoreTable$FallbackDataSplit
at org.apache.paimon.table.FallbackReadFileStoreTable$Read.createReader(FallbackReadFileStoreTable.java:459)
at org.apache.paimon.spark.PaimonPartitionReader.readSplit(PaimonPartitionReader.scala:104)
at org.apache.paimon.spark.PaimonPartitionReader.<init>(PaimonPartitionReader.scala:46)
at org.apache.paimon.spark.PaimonPartitionReaderFactory.createReader(PaimonPartitionReaderFactory.scala:37)
at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.advanceToNextIter(DataSourceRDD.scala:84)
```

[spark] Fix read with scan.fallback-branch

---

paimon-hudi/src/main/java/org/apache/paimon/hudi/HudiFileIndex.java
paimon-hudi/src/main/java/org/apache/paimon/hudi/HudiHiveCloneExtractor.java

For Hudi version < 0.9, there is no spark-sql support, which may cause some different behavior of the Hudi table. 
1. There is no spark.sql.sources.provider in table parameter
2. Partition path may not be form of pt=xxx

Fix clone Hudi for table writen by old Hudi version

---

paimon-api/src/main/java/org/apache/paimon/CoreOptions.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkSink.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/LookupSinkWrite.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTablesStoreCompactOperator.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/PrimaryKeyFileStoreTableITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/WriterOperatorTest.java

This PR fixes the same bug in #3512, but in the scenario when `lookup-wait` is `true`. Consider the following case:
A lookup writer has produced both new files and compacted changelogs during one checkpoint, however only the APPEND snapshot is committed and the COMPACT snapshot fails to commit due to exception.
When the job restarts, the COMPACT snapshot will not be committed again to avoid potential manifest conflicts. If records of this bucket never comes after restart, the changelogs will be lost.
* `WriterOperatorTest#testLookupWithFailure`.

[flink] All lookup writers should store active buckets in state to make sure changelog can be produced

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/execution/PaimonFormatTable.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/FormatTableTestBase.scala

Support show partitions for Format table
```sql
SHOW PARTITIONS format_tbl
SHOW PARTITIONS format_tbl PARTITION (p1=1)
```

[spark] Format table support show partitions

---

paimon-e2e-tests/src/test/java/org/apache/paimon/tests/FileStoreBatchE2eTest.java
paimon-e2e-tests/src/test/java/org/apache/paimon/tests/cdc/MySqlCdcE2eTestBase.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/coordinator/CoordinatedWriteRestore.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/coordinator/CoordinationResponseUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/coordinator/WriteOperatorCoordinator.java

Currently, Flink's RPC gateway can only deserialize classes accessible from Flink's class loader (see [apache/flink](https://github.com/apache/flink/blob/ce03ea11d10df28affa040847dbaf02680eb785d/flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/pekko/PekkoRpcService.java#L543), so we have to wrap our own response with a class (`CollectCoordinationResponse`) in Flink's project.
E2e tests.

[flink] Fix ClassNotFoundException when deserializing writer coordination response

---

docs/content/flink/sql-lookup.md

This PR fixes the document for Fixed Bucket Large Scale Lookup optimization. This optimization takes effect only when the join keys contain all the bucket keys (See BaseDataTableSource#supportBucketShufflePartitioner). The current document missed this point.

[flink] Fix the document of Fixed Bucket Large Scale Lookup optimization

---

paimon-api/src/main/java/org/apache/paimon/rest/RESTApi.java
paimon-core/src/test/java/org/apache/paimon/rest/MockRESTCatalogTest.java

Fixed base header not being set when 'configRequired' is false
org.apache.paimon.rest.MockRESTCatalogTest#testHeaderOptions

[rest] fix base header options in RESTApi

---

paimon-core/src/main/java/org/apache/paimon/catalog/Catalog.java

We cannot judge where or why we have no permission for the table/database, so we need include more detailed descriptions of lacking permissions.
MockRESTCatalogTest.testDatabaseApiWhenNoPermission
MockRESTCatalogTest.testApiWhenTableNoPermission

[hotfix] add detail information for NoPermissionException

---

.gitignore
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/pool/CachedClientPool.java

In Spark executor attempts to connect to HMS, but executor fails without Kerberos authentication information for HMS.
Due to the changes in https://github.com/apache/paimon/pull/4010, `HiveCatalog` will be connected to HMS when initialized.
In this PR, only connect to HMS without SASL enabled in the initialization.
```java
ERROR TSaslTransport: SASL negotiation failure
javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211)
at org.apache.thrift.transport.TSaslClientTransport.handleSaslStartMessage(TSaslClientTransport.java:95)
at …
```

[hive] Only connect to HMS without SASL enabled in the HiveCatalog initialization

---

paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveCatalog.java
paimon-hive/paimon-hive-catalog/src/main/java/org/apache/paimon/hive/HiveTableUtils.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/FormatTableTestBase.scala

Always sync properties to HMS for format table

[hive] Format table: Support field delimiter in HMS 

---

docs/content/flink/sql-lookup.md
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/DynamicPartitionLevelLoader.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/DynamicPartitionLoader.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/DynamicPartitionNumberLoader.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/FileStoreLookupFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/lookup/PartitionLoader.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/LookupJoinITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/lookup/DynamicPartitionLevelLoaderTest.java

Sometimes users want to specify max_pt() for a fixed-level partition and load all subpartitions for lookup. For example,  set 'scan.partitions' = 'ds=max_pt()', then all subpartitions in max 'ds' partition will be loaded.

[flink] support specify max_pt for partition level

---

paimon-api/src/main/java/org/apache/paimon/CoreOptions.java
paimon-core/src/main/java/org/apache/paimon/table/source/DataTableBatchScan.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/CompactorSourceBuilder.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/action/CompactActionITCase.java

If the table is dv enabled or using first-row as merge engine, and its writing job is write-only, compact action in batch mode for this table will generate 0 splits. This is because `DataTableBatchScan` will skip all level-0 files when dv enabled or with first-row merge engine while files written with write-only set to true are all in level-0. 
This pr introduced a new option "batch-scan-mode" which should only be used internally, if `batch-scan-mode = compact`, the `scan` won't apply the level-0 filter.
CompactActionITCase#testCompactWhenSkipLevel0

[core] fix that batch CompactAction makes no sense with all level-0 files

---

paimon-arrow/src/main/java/org/apache/paimon/arrow/reader/ArrowBatchReader.java
paimon-common/src/main/java/org/apache/paimon/data/RowHelper.java
paimon-common/src/main/java/org/apache/paimon/data/serializer/InternalRowSerializer.java
paimon-core/src/main/java/org/apache/paimon/io/KeyValueDataFileWriter.java
paimon-core/src/test/java/org/apache/paimon/mergetree/ChangelogMergeTreeRewriterTest.java
paimon-format/src/main/java/org/apache/paimon/format/parquet/reader/VectorizedParquetRecordReader.java

We should copy the maxKey, otherwise if the reader is closed first, the maxKey inside may be reset, such as the dictionary in Parquet Reader.

[core] Copy max key in KeyValueDataFileWriter

---

docs/content/spark/sql-ddl.md
paimon-core/src/main/java/org/apache/paimon/AbstractFileStore.java
paimon-core/src/main/java/org/apache/paimon/table/AbstractFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/table/system/TagsTable.java
paimon-core/src/main/java/org/apache/paimon/utils/TagManager.java
paimon-core/src/test/java/org/apache/paimon/tag/TagAutoManagerTest.java

Linked issue: close #5800
Prevent different auto-tags created on the same snapshot.
If not, inserting data would incur errors as the issue #5800 shows.
org.apache.paimon.tag.TagAutoManagerTest#testMultiAutoTagsOnOneSnapshot
No

[core]  One snapshot should have only one auto tag

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonSparkWriter.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/write/PaimonWriteRequirement.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/WriteDistributeModeTest.scala

Currently, in v2 write, writing to a partitioned table with bucket = -1 defaults to repartitioning the data by partition columns, which is inconsistent with the default behavior of v1 write. So a new option `spark.paimon.write.distribution-mode` has been added to control this behavior and align it between v1 and v2 writes.
This configuration only applies to bucket-unaware tables, because bucket tables always need repartition now.
Maybe in the furure, repartitioning for bucketed tables may also be optional — for example, when the write mode is set to write-only.

[spark] Apply partition.sink-strategy to spark write

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DeleteFromTableTestBase.scala

link https://github.com/apache/paimon/issues/5801
In https://github.com/apache/paimon/pull/3462, implemented the SupportsMetadataColumns interface. The metadata columns will be added first in spark `AddMetadataColumns` rule. But in paimon, add them again.
```scala
override def metadataColumns: Array[MetadataColumn] = {
val partitionType = SparkTypeUtils.toSparkPartitionType(table)
Array[MetadataColumn](
PaimonMetadataColumn.FILE_PATH,
PaimonMetadataColumn.ROW_INDEX,
PaimonMetadataColumn.PARTITION(partitionType),
PaimonMetadataColumn.BUCKET
)
}
```
As a delete sql with metadata column, metadata will add twice.
```sql
delete from T where __paimon_file_path = 'file_name';
-- default LogicalPlan
RelationV2[id#53L, c1#54, __paimon_file_path#55, __paimon_row_index#56L, __paimon_partition#57, …
```

[spark] delete with metadata columns generates duplicate relation fields

---

.github/workflows/utitcase-flink-2.x-jdk11.yml
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/CatalogTableITCase.java
paimon-flink/paimon-flink1-common/pom.xml
paimon-flink/pom.xml
pom.xml

Linked issue: close #5876
This PR fixes the problems that affect the stability of Flink 2.0 test workflow and add back the workflow script again, which was once removed in https://github.com/apache/paimon/commit/a6d2e8376cfb93accfbb2112048edefeb48bc77e.
I counted the most recent 100 Action executions before the script is removed, and the problems that caused the failures are as follows.
1. (79%) The Action run successfully.
2. (11%) paimon-flink-cdc module download timeout.
4. (7%) CatalogTableITCase#testConsumersTable failed. It is a flaky test with race condition.
5. (3%) Various failures that appeared only once.
So we need to fix the problems mentioned in 2 and 3 before enabling the Action again. The fixing is as follows.
Example failure Action log: …

[flink] Fix stability of Flink 2.0 test workflow

---

paimon-core/src/main/java/org/apache/paimon/tag/TagAutoCreation.java

Just to correct the right information when deleting outdated snapshot.

[bug] Log the right name of the deleting tag.

---

paimon-common/src/main/java/org/apache/paimon/data/variant/GenericVariant.java
paimon-common/src/main/java/org/apache/paimon/data/variant/GenericVariantBuilder.java
paimon-common/src/main/java/org/apache/paimon/data/variant/GenericVariantUtil.java

Port SPARK-51270, SPARK-52181, SPARK-52153

[variant] Port changes of variant from spark

---

pom.xml

Skip the error in https://github.com/apache/paimon/actions/runs/16280610720
```
2025-07-15T00:05:43.1138113Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:jar (attach-javadocs) on project paimon-s3-impl: MavenReportException: Error while generating Javadoc: 
2025-07-15T00:05:43.1139650Z [ERROR] Exit code: 2 - error: No source files for package org.apache.paimon.s3
2025-07-15T00:05:43.1140303Z [ERROR] 1 error
```
Searched for a long time but didn't figure out how to fix it. Hope someone in the future can find the root cause.

[deploy] Suppress doc generation error when using JDK17

---

paimon-arrow/src/main/java/org/apache/paimon/arrow/ArrowUtils.java
paimon-arrow/src/test/java/org/apache/paimon/arrow/ArrowUtilsTest.java

Map value type should be nullable if paimon map type value is nullable.
Do not force non-null for arrow map value type.

[arrow] Fix map type conversion from paimon type to arrow type

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/postpone/PostponeBucketCommittableRewriter.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/postpone/RewritePostponeBucketCommittableOperator.java

This PR extracts logic in `RewritePostponeBucketCommittableOperator` into a separated class, so if we want to support database compaction for postpone bucket tables in the future, we can reuse this class.
This is only a refactor. No test is needed.

[flink] Refactor code in RewritePostponeBucketCommittableOperator

---

pom.xml

New javadoc settings break the website building

[doc] Keep old javadoc plugin for paimon website building

---

docs/content/spark/dataframe.md
paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/sql/DataFrameWriteTest.scala
paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/DataFrameWriteTest.scala
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/DataFrameWriteTest.scala
paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/sql/DataFrameWriteTest.scala
paimon-spark/paimon-spark-4.0/src/test/scala/org/apache/paimon/spark/sql/DataFrameWriteTest.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DataFrameWriteTestBase.scala

There are still many users who use dataframe api, add a document to facilitate users

[doc][spark] Add dataframe page

---

paimon-flink/paimon-flink-1.15/src/main/java/org/apache/paimon/flink/utils/ParallelismUtils.java
paimon-flink/paimon-flink-1.16/src/main/java/org/apache/paimon/flink/utils/ParallelismUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/FlinkStreamPartitioner.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/utils/ParallelismUtils.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/ReadWriteTableITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/ParallelismConfiguredITCase.java

This PR allows configuring the `parallelismConfigured` property of `FlinkStreamPartitioner` to false. 
With this PR and previous commits, Paimon can now have most of its Flink sink operators dynamically changing their parallelism in AdaptiveBatch situations. Exceptional operators are as follows:
* Operators that are forced not to be parallel because of their syntax: Global Committers, Compact Coordinators and discarding sinks
* Operators in dynamic bucket mode and batch execution mode: dynamic bucket assigner and the writer operator.
`ParallelismConfiguredITCase` is added to verify the `parallelismConfigured` property of these operators and the end-to-end correctness.

[flink] Enable adaptive parallelism for FlinkStreamPartitioner

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-api/src/main/java/org/apache/paimon/CoreOptions.java
paimon-api/src/main/java/org/apache/paimon/OffPeakHours.java
paimon-api/src/test/java/org/apache/paimon/offpeak/OffPeakHoursTest.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/UniversalCompaction.java
paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/UniversalCompactionTest.java

Implementing a feature similar to HBase's off-peak:
Allows set a different (by default, more aggressive) percentage ratio for determining whether larger sorted run sizes are included in compactions during off-peak hours. Works in the same way as compaction.size-ratio. Only applies if offpeak.start.hour and offpeak.end.hour are also enabled.
Add UT cases: OffPeakHoursTest、UniversalCompactionTest#testOffPeakRatioThreshold

[core] Support off-peak hours

---

docs/content/spark/dataframe.md
docs/content/spark/sql-upsert.md
docs/layouts/shortcodes/generated/core_configuration.html
paimon-api/src/main/java/org/apache/paimon/CoreOptions.java
paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/spark/sql/paimon/shims/MinorVersionShim.scala
paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/sql/RewriteUpsertTableTest.scala
paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/spark/sql/paimon/shims/MinorVersionShim.scala
paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/RewriteUpsertTableTest.scala
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/RewriteUpsertTableTest.scala
paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/sql/RewriteUpsertTableTest.scala
paimon-spark/paimon-spark-4.0/src/test/scala/org/apache/paimon/spark/sql/RewriteUpsertTableTest.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/RewriteUpsertTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/extensions/PaimonSparkSessionExtensions.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/spark/sql/paimon/shims/SparkShim.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/RewriteUpsertTableTestBase.scala
paimon-spark/paimon-spark3-common/src/main/scala/org/apache/spark/sql/paimon/shims/MinorVersionShim.scala
paimon-spark/paimon-spark3-common/src/main/scala/org/apache/spark/sql/paimon/shims/Spark3Shim.scala
paimon-spark/paimon-spark4-common/src/main/scala/org/apache/spark/sql/paimon/shims/Spark4Shim.scala

```sql
CREATE TABLE T (k INT, ts INT, c STRING)
TBLPROPERTIES ('upsert-key' = 'k', 'sequence.field' = 'ts')
INSERT INTO T values (1, 1, 'c1'), (null, 2, 'c2'), (3, 3, 'c3')
INSERT INTO T values (null, 22, 'c22'), (1, 11, 'c11'), (4, 4, 'c4')
```
select  result
```sql
Row(null, 22, "c22"), Row(1, 11, "c11"), Row(3, 3, "c3"), Row(4, 4, "c4")
```

[spark] Introduce upsert-key for insert into non-pk table 

---

paimon-core/src/main/java/org/apache/paimon/table/FallbackReadFileStoreTable.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BranchSqlITCase.java

```
Caused by: java.lang.ClassCastException: org.apache.paimon.table.source.DataSplit cannot be cast to org.apache.paimon.table.FallbackReadFileStoreTable$FallbackDataSplit
```
An exception would be thrown when attempting to read a branch configured with the `scan.fallback-branch` property. This occurs because the `FallbackReadFileStoreTable` class does not implement the `newStreamScan()` method. As a result, the data splits generated in streaming mode are instances of `DataSplit` rather than `FallbackDataSplit`, leading to a ClassCastException.

[core] fix that branch can't be streamingly read if setting fallback branch

---

paimon-common/src/main/java/org/apache/paimon/fileindex/rangebitmap/RangeBitmap.java
paimon-common/src/main/java/org/apache/paimon/fileindex/rangebitmap/dictionary/chunked/AbstractChunk.java
paimon-common/src/main/java/org/apache/paimon/fileindex/rangebitmap/dictionary/chunked/ChunkedDictionary.java
paimon-common/src/test/java/org/apache/paimon/fileindex/rangebitmap/ChunkedDictionaryTest.java
paimon-common/src/test/java/org/apache/paimon/fileindex/rangebitmap/RangeBitmapFileIndexTest.java

The `Dictionary#find(java.lang.Object)` result is same as the `Collections.binarySearch`. 
Return the code by the search key if it is contained in the dictionary; otherwise, `(-(insertion point) - 1)` instead.

[common] Correct the range-bitmap's dictionary return results

---

paimon-core/src/main/java/org/apache/paimon/iceberg/manifest/IcebergConversions.java
paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergDataField.java
paimon-core/src/test/java/org/apache/paimon/iceberg/IcebergCompatibilityTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/iceberg/FlinkIcebergITCaseBase.java

Support [TINYINT](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/types/#tinyint) and [SMALLINT](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/types/#smallint) in Iceberg
I need these types because I have them in MySQL clusters and want to ingest them to Paimon and read as Iceberg.
UT and IT test cases

[core] Iceberg:  support TINYINT and SMALLINT

---

docs/content/flink/quick-start.md
docs/layouts/shortcodes/generated/flink_connector_configuration.html
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/FlinkConnectorOptions.java

FileIO runtime context should be implemented by user, so if user have implemented it, of course he wants this feature. So adjust the default value for convenience.

[flink] Change filesystem.job-level-settings.enabled default value to true and add doc

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-api/src/main/java/org/apache/paimon/CoreOptions.java
paimon-arrow/src/main/java/org/apache/paimon/arrow/vector/ArrowFormatCWriter.java
paimon-arrow/src/main/java/org/apache/paimon/arrow/vector/ArrowFormatWriter.java
paimon-arrow/src/test/java/org/apache/paimon/arrow/vector/ArrowFormatWriterTest.java
paimon-common/src/main/java/org/apache/paimon/format/FileFormat.java
paimon-common/src/main/java/org/apache/paimon/format/FileFormatFactory.java
paimon-format/src/test/java/org/apache/paimon/format/parquet/ParquetFileFormatTest.java
paimon-lance/src/main/java/org/apache/paimon/format/lance/LanceFileFormat.java

If every record is too big to put into one batch, then write.batch-size may be useless.
Introduce a new config write.batch-memory for this situation.

[format] Introduce 'write.batch-memory' to control memory in arrow

---

paimon-api/src/main/java/org/apache/paimon/table/SpecialFields.java
paimon-core/src/main/java/org/apache/paimon/AppendOnlyFileStore.java
paimon-core/src/main/java/org/apache/paimon/operation/BaseAppendFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
paimon-core/src/main/java/org/apache/paimon/table/system/RowLineageTable.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/AppendTableITCase.java

Row id and Sequence number should be kept their origin value during compaction.

[core] Row-tracking row should keep their row_id and sequence_number in compaction

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/listener/PartitionMarkDoneTrigger.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/listener/PartitionMarkDoneTriggerTest.java

[core] Log a warning for invalid partition values instead of throwing an exception when enable partition mark done. 

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/test/java/org/apache/paimon/table/SchemaEvolutionTest.java

Currently, column renames don't automatically update table properties. For example, if a table has a column `foo` configured with `fields.foo.aggregate-function=collect`, rename `foo`  to `bar` won't update table options synchronously. This can lead to change errors:
```
java.lang.IllegalArgumentException: Field foo can not be found in table schema.
```
This PR apply column rename changes to table options to fix this.
org.apache.paimon.table.SchemaEvolutionTest#testRenameFieldReferencedByOptions
No
No
Hi @JingsongLi @Zouxxyy, can you take a look at this when you have time? Thanks!

[core]: fix column rename when columns referenced by table options.

---

docs/content/spark/sql-query.md
paimon-core/src/main/java/org/apache/paimon/table/source/ReadBuilder.java
paimon-core/src/main/java/org/apache/paimon/table/source/ReadBuilderImpl.java
paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/PaimonScan.scala
paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/PaimonScanBuilder.scala
paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/paimon/spark/PaimonScan.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/ColumnPruningAndPushDown.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScan.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonBaseScanBuilder.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonRecordReaderIterator.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScan.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScanBuilder.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonSplitScan.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkTable.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/aggregate/LocalAggregator.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/commands/PaimonCommand.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/schema/PaimonMetadataColumn.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/RowLineageTest.scala

In this PR:
1. ~~add `metadataRowType()` and `fullRowType()` in `interface InnerTable`~~ remove the schema checker in `withReadType(RowType readType)`
3. make spark scan accpet `InnerTable` instead of `Table`
4. add `_ROW_ID` and `_SEQUENCE_NUMBER` metadata column in spark scan
```sql
SELECT *, _ROW_ID, _SEQUENCE_NUMBER FROM t
```

[core][spark] Support reading row lineage metadata column

---

paimon-python/pypaimon/schema/data_types.py
paimon-python/pypaimon/schema/schema.py
paimon-python/pypaimon/schema/table_schema.py
paimon-python/pypaimon/tests/api_test.py
paimon-python/pypaimon/tests/schema_test.py
paimon-python/pypaimon/write/row_key_extractor.py

- Support partial mutual conversion between nested paimon DataField and pyarrow Field, including list and map.
- Support create Schema from pyarrow Schema
schema_test.SchemaTestCase.test_types()

[python] Support mutual conversion between paimon DataField and pyarrow Field

---

paimon-flink/paimon-flink-common/pom.xml

Fix the failure of FlinkRestCatalogITCase in IDEA, as httpcomponents is relocated in the paimon-api module, and IDEA cannot recognize this scenario. The dependency should be explicitly defined.

[test] Fix FlinkRestCatalogITCase ut failed in idea

---

.github/workflows/check-licensing.yml
.github/workflows/docs-tests.yml
.github/workflows/e2e-tests-flink-1.x-jdk11.yml
.github/workflows/e2e-tests-flink-1.x.yml
.github/workflows/e2e-tests-flink-2.x-jdk11.yml
.github/workflows/publish_snapshot-jdk17.yml
.github/workflows/publish_snapshot.yml
.github/workflows/utitcase-flink-1.x-jdk11.yml
.github/workflows/utitcase-flink-1.x.yml
.github/workflows/utitcase-flink-2.x-jdk11.yml
.github/workflows/utitcase-jdk11.yml
.github/workflows/utitcase-spark-3.x.yml
.github/workflows/utitcase-spark-4.x.yml
.github/workflows/utitcase.yml

I noticed that our current CI pipeline is unreliable, occasionally [failing](https://github.com/apache/paimon/actions/runs/16520230108/job/46720172040)  due to Maven connection resets. 
This PR attempts to resolve this by configuring Maven settings, to retry upon Maven connection reset.
The solution is borrowed from https://github.com/GoogleContainerTools/skaffold/issues/5248.
Hi @JingsongLi @Zouxxyy can you take a look when you have time? Thanks!

[build]: fix maven resolve dependencies error on github workflow.

---

paimon-core/src/test/java/org/apache/paimon/table/source/StartupModeTest.java

The useless cases may cause the workflow runs error.
See https://github.com/apache/paimon/actions/runs/16743242901/job/47395798363?pr=6028
```text
Error:  Failures: 
Error:    StartupModeTest.testStartFromSnapshotWithoutDelayDuration:272 
Expecting actual:
117L
to be less than:
100L 
[INFO] 
Error:  Tests run: 2083, Failures: 1, Errors: 0, Skipped: 2
```

[hotfix] Fix useless cases in StartupModeTest

---

paimon-common/src/main/java/org/apache/paimon/fileindex/rangebitmap/BitSliceIndexBitmap.java
paimon-common/src/main/java/org/apache/paimon/fileindex/rangebitmap/RangeBitmap.java
paimon-common/src/main/java/org/apache/paimon/fileindex/rangebitmap/dictionary/chunked/ChunkedDictionary.java
paimon-common/src/test/java/org/apache/paimon/fileindex/rangebitmap/BitSliceIndexBitmapTest.java
paimon-common/src/test/java/org/apache/paimon/fileindex/rangebitmap/ChunkedDictionaryTest.java
paimon-common/src/test/java/org/apache/paimon/fileindex/rangebitmap/RangeBitmapFileIndexTest.java

Fix the following two issues:
1. An unexpected error will be thrown when building the range-bitmap if all the values are NULL.
2. If the cardinality of a value is 1, an unexpected exception will be thrown when reading the range-bitmap's bsi.

[common] Minor fix for range-bitmap

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/ScanHelper.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/ScanHelperTest.scala

For maxPartitionBytes, paimon has `source.split.target-size`, spark has `spark.sql.files.maxPartitionBytes`
For file openCostInBytes, paimon has `source.split.open-file-cost`, spark has `spark.sql.files.openCostInBytes`
This pr combine them, and make Paimon's conf takes precedence over Spark's if we set them both

[spark] Unify config extraction for maxPartitionBytes and openCostInBytes between paimon and spark

---

paimon-iceberg/src/test/java/org/apache/paimon/flink/CloneActionForIcebergITCase.java

`CloneActionForHudiITCase` and `CloneActionForIcebergITCase` should use different METASTORE ports to avoid port conflicts.

[fix] Fix hive metastore address already in use

---

docs/content/spark/dataframe.md
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkSource.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/util/OptionUtils.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DDLWithHiveCatalogTestBase.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonOptionTest.scala

- If only path conf is provided, the catalog configs should not be read.
- Provides catalog, database, and table options, to allow the user to specify the catalog name.
- Fix other options reading, like time travel

[spark] Optimize the config reading for load table in SparkSource

---

paimon-core/src/main/java/org/apache/paimon/table/sink/TableWriteImpl.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/BranchSqlITCase.java

[core] Fix default value not work for primary key table with bucket -1

---

paimon-filesystems/paimon-jindo/src/main/java/org/apache/paimon/jindo/JindoFileIO.java

Set SimpleCredentialsProvider as default credentials provider for JindoFileIO to use right token to access OSS.

[fs] Set credentials provider in JindoFileIO

---

docs/content/maintenance/filesystems.md
paimon-common/src/main/java/org/apache/paimon/fs/hadoop/HadoopFileIO.java
paimon-common/src/main/java/org/apache/paimon/fs/hadoop/HadoopSecuredFileSystem.java
paimon-common/src/test/java/org/apache/paimon/fs/HadoopSecuredFileSystemTest.java
paimon-common/src/test/java/org/apache/paimon/fs/hadoop/HadoopSecuredFileSystemTest.java

This PR adds support for Kerberos authentication to Hadoop FileSystem.
HadoopSecuredFileSystemTest is added for verification.
Document about filesystems is changed to specify the way to enable Kerberos authentication when Flink engine is used.

[core] Support Kerberos authentication

---

paimon-core/src/main/java/org/apache/paimon/table/query/LocalTableQuery.java

- Fixes a bug where localtablequery throws an error:
```
Caused by: java.lang.IllegalArgumentException: The before file should be empty for the initial phase.
at org.apache.paimon.utils.Preconditions.checkArgument(Preconditions.java:127)
at org.apache.paimon.table.query.LocalTableQuery.refreshFiles(LocalTableQuery.java:118)
```
- Beforefiles may be expected in the FILE_MONITOR mode and not populated for changelog/compact_delta modes. 
- Removed the check, ideally this should be only added to the changelog log/compact_delta modes, but the LocalTableQuery is not aware of the modes, and the check does not add much value. 
- This fix will unblock querying but in the future, the higher level apis can be extended to be more aware of the mode and pass it to LocalTableQuery which can enforce the …

[core] Ignore beforeFiles on initial refresh for LocalTableQuery

---

paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/procedure/CloneActionITCase.java

- testMigrateOneNonPartitionedTable occasionally fails with "Broken pipe" HMS connectivity errors
- Network/timing issues in CI cause transient Thrift connection failures
- Simple retry with backoff gives HMS time to recover from temporary issues
- Fixes: #6002

[test] Fix flaky test for CloneActionITCase

---

paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/bitmap/RangeBitmapIndexPushDownBenchmark.java
paimon-common/src/main/java/org/apache/paimon/fileindex/bitmap/BitmapIndexResult.java
paimon-core/src/main/java/org/apache/paimon/io/FileIndexEvaluator.java
paimon-core/src/main/java/org/apache/paimon/io/KeyValueFileReaderFactory.java
paimon-core/src/main/java/org/apache/paimon/operation/DataEvolutionSplitRead.java
paimon-core/src/main/java/org/apache/paimon/operation/RawFileSplitRead.java
paimon-core/src/main/java/org/apache/paimon/operation/SplitRead.java
paimon-core/src/main/java/org/apache/paimon/table/source/AppendTableRead.java
paimon-core/src/main/java/org/apache/paimon/table/source/InnerTableRead.java
paimon-core/src/main/java/org/apache/paimon/table/source/KeyValueTableRead.java
paimon-core/src/main/java/org/apache/paimon/table/source/ReadBuilderImpl.java
paimon-core/src/main/java/org/apache/paimon/utils/FormatReaderMapping.java
paimon-core/src/test/java/org/apache/paimon/table/AppendOnlySimpleTableTest.java
paimon-core/src/test/java/org/apache/paimon/table/PrimaryKeySimpleTableTest.java
paimon-core/src/test/java/org/apache/paimon/utils/FormatReaderMappingTest.java
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonPushDownTestBase.scala

For now, `selection` can push down to filter the DataFile's rowgroups and pages, and the `limit` can trim the `selection`, then more rowgroups and pages will be filtered out.
1. support append-only table, append-only/primary-key table in deletion-vector mode.
2. limit can not using with `TopN` and `Predicate Filter`.
Benchmarks:
Before
```text
limit:                                                                                               Best/Avg Time(ms)    Row Rate(K/s)      Per Row(ns)   Relative
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
OPERATORTEST_limit_300000-1000                                                                             498 /  498 …
```

[core] Support limit pushdown to the DataFile

---

paimon-python/pypaimon/tests/writer_test.py
paimon-python/pypaimon/write/file_store_commit.py

Fixes #6138
Fix: the total number of rows in the table and the number of rows added in python commit are empty.

[python] Add totalRecordCount and deltaRecordCount in Snapshot

---

paimon-spark/paimon-spark-3.2/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeInto.scala
paimon-spark/paimon-spark-3.3/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeInto.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeInto.scala
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/catalyst/analysis/PaimonMergeIntoBase.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTestBase.scala

Support partial column specification in MERGE INTO's INSERT clause

[spark] Support partial column specification in MERGE INTO's INSERT clause

---

paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/kafka/KafkaDebeziumJsonDeserializationSchema.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/action/cdc/kafka/KafkaDebeziumJsonDeserializationSchemaTest.java

- Fixes #5945 
- KafkaDebeziumJsonDeserializationSchema always parses Kafka keys as JSON, causing deserialization for fail for non JSON
- CDC pipelines only use the JSON value payload, handle this gracefully by ignoring the non json fields. 
- Prevents crashes for topics with raw keys.

[flink] Bug fix for non-JSON deserialization in Flink CDC

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCommitter.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CommitterOperatorTest.java

- Global Committer metrics in Flink UI when committing via filter-and-commit.
- StoreCommitter.filterAndCommit() didn’t update CommitterMetrics, unlike commit().
- Updated the same and added a test.
- Fixes: #5950

[flink] Fix Global Committer metrics missing in UI for filter/commit path

---

paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergDataField.java
paimon-core/src/test/java/org/apache/paimon/iceberg/metadata/IcebergDataFieldTest.java

Fix IcebergDataField nested type nullability handling.
paimon-core/src/test/java/org/apache/paimon/iceberg/metadata/IcebergDataFieldTest.java

[iceberg] Add comprehensive tests for IcebergDataField and fix nested type nullability handling

---

paimon-core/src/main/java/org/apache/paimon/table/format/FormatReadBuilder.java
paimon-core/src/main/java/org/apache/paimon/table/format/FormatTableScan.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-core/src/test/java/org/apache/paimon/table/format/FormatReadBuilderTest.java

- fix FormatReadBuilder serialization fail 
- partition bug when partition filter is null
- FormatReadBuilderTest
- CatalogTestBase#testFormatTableRead

[bug] fix:  FormatReadBuilder serialization fail and partition bug

---

paimon-common/src/main/java/org/apache/paimon/predicate/PredicateBuilder.java
paimon-core/src/main/java/org/apache/paimon/table/format/FormatReadBuilder.java
paimon-core/src/main/java/org/apache/paimon/table/source/snapshot/SnapshotReaderImpl.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java

For the format table: a user may define partition filters in filters, so we need to get partition filters from filters when a user defines filters for reading
- CatalogTestBase#testFormatTableRead

[core]fix: filter contains partition filter

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/compact/changelog/ChangelogCompactTask.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/compact/changelog/ChangelogCompactTaskTest.java

Changelog compact tasks currently does not set the correct external path for fake file metas. This will cause `FileNotFoundException` when reading changelogs. This PR fixes the issue.
* `ChangelogCompactTaskTest`

[flink] Fix file not found when using changelog compact with multiple extra paths

---

docs/content/concepts/spec/fileindex.md
paimon-benchmark/paimon-micro-benchmarks/src/test/java/org/apache/paimon/benchmark/bitmap/RangeBitmapIndexPushDownBenchmark.java
paimon-common/src/main/java/org/apache/paimon/fileindex/FileIndexPredicate.java
paimon-common/src/main/java/org/apache/paimon/fileindex/rangebitmap/BitSliceIndexBitmap.java
paimon-common/src/main/java/org/apache/paimon/fileindex/rangebitmap/RangeBitmapFileIndex.java
paimon-common/src/main/java/org/apache/paimon/predicate/TopN.java
paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/PaimonScanBuilder.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/PaimonPushDownTestBase.scala

Wrap up #6178
Suppose the `id` has created with `range-bitmap`.
position | id | price
--|--|--|
0|10 | 100
1|20 | 100
2|20 | 200
3|20 | 300
4|30 | 100
`SELECT * FROM id DESC LIMIT 2` will return
position | id | price
--|--|--|
3|20 | 300
4|30 | 100
`SELECT * FROM id DESC, price LIMIT 2` will return this. And the compute engine will rerank the result.
position | id | price
--|--|--|
1|20 | 100
2|20 | 200
3|20 | 300
4|30 | 100

[core] The TopN predicate for range-bitmap supports multiple sort keys

---

docs/content/spark/procedures.md

Inconsistent attribute names lead to ambiguity and it is impossible to determine which one to use

fix inconsistent attribute names

---

docs/layouts/shortcodes/generated/core_configuration.html
paimon-api/src/main/java/org/apache/paimon/CoreOptions.java
paimon-api/src/main/java/org/apache/paimon/options/MemorySize.java
paimon-common/src/main/java/org/apache/paimon/memory/UnlimitedSegmentPool.java
paimon-core/src/main/java/org/apache/paimon/crosspartition/GlobalIndexAssigner.java
paimon-core/src/main/java/org/apache/paimon/disk/ExternalBuffer.java
paimon-core/src/main/java/org/apache/paimon/disk/InMemoryBuffer.java
paimon-core/src/main/java/org/apache/paimon/disk/RowBuffer.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/KeyValueBuffer.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapper.java
paimon-core/src/main/java/org/apache/paimon/mergetree/compact/LookupMergeFunction.java
paimon-core/src/main/java/org/apache/paimon/operation/KeyValueFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/operation/MergeFileSplitRead.java
paimon-core/src/main/java/org/apache/paimon/postpone/PostponeBucketFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/table/PrimaryKeyFileStoreTable.java
paimon-core/src/main/java/org/apache/paimon/utils/SinkWriter.java
paimon-core/src/test/java/org/apache/paimon/disk/ExternalBufferTest.java
paimon-core/src/test/java/org/apache/paimon/disk/InMemoryBufferTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/SortBufferWriteBufferTestBase.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/KeyValueBufferInsertIntoTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/KeyValueBufferTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LookupChangelogMergeFunctionWrapperTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LookupMergeFunctionTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/LookupMergeFunctionUnitTest.java
paimon-core/src/test/java/org/apache/paimon/mergetree/compact/SortMergeReaderTestBase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/DeletionVectorITCase.java

- Introduce `lookup.merge-buffer-size` and `lookup.merge-records-threshold`.
- When this threshold is exceeded, a spillable external buffer will be used to avoid OOM exceptions caused by too much records.

[core] Introduce external buffer in lookup merging

---

paimon-core/src/main/java/org/apache/paimon/catalog/CatalogUtils.java
paimon-core/src/test/java/org/apache/paimon/catalog/CatalogTestBase.java
paimon-core/src/test/java/org/apache/paimon/jdbc/JdbcCatalogTest.java
paimon-core/src/test/java/org/apache/paimon/privilege/PrivilegedCatalogTest.java

`CatalogEnvironment` should be tableIdentifier in `CatalogUtils.loadTable`.
`CatalogTestBase.testGetTable`

[core] Fix manifests system table not work in REST Catalog

---

paimon-spark/paimon-spark-common/src/main/scala/org/apache/paimon/spark/SparkV2FilterConverter.scala

Eliminate duplicate convertLiteral invocations
CI

[spark] Eliminate duplicate convertLiteral invocations

---

paimon-common/src/main/java/org/apache/paimon/rest/RESTTokenFileIO.java
paimon-core/src/test/java/org/apache/paimon/rest/RESTCatalogTest.java

Fix REST token handling for system tables

[core] Ensure system tables use the correct identifier for loadTableToken in RESTTokenFileIO

---

paimon-core/src/main/java/org/apache/paimon/operation/FileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/table/sink/TableWrite.java
paimon-core/src/main/java/org/apache/paimon/table/sink/TableWriteImpl.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperator.java
paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/sink/cdc/FlinkCdcMultiTableSink.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreWriteOperatorTest.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/GlobalFullCompactionSinkWrite.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/LookupSinkWrite.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/MultiTablesStoreCompactOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/PrepareCommitOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreCompactOperator.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWrite.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/StoreSinkWriteImpl.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/TableWriteOperator.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/CompactorSinkITCase.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/StoreCompactOperatorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/WriterOperatorTest.java

Currently, `TableWriteImpl` can use either `MemoryPool` or `MemoryPoolFactory` from the outside. However, `MemoryPoolFactory` are always preferrable, because it can share memory even between writers from different `TableWriteImpl` instances. This is useful for multi-table writes such as the database compact action.
This PR removes `withMemoryPool` in `TableWriteImpl`. From now on we should only use `withMemoryPoolFactory`.
This PR is a refactor and has no specific test.

[core][flink] Remove withMemoryPool in TableWriteImpl

---

docs/content/concepts/rest/pvfs.md

- Fix typo: 'ecesystem' -> 'ecosystem'
- Fix Python dictionary syntax errors in code examples

[doc] Fix Python code syntax errors and typo in PVFS documentation

---

paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CloneAction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/CloneActionFactory.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/CloneFileFormatUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/CloneHiveTableUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/ClonePaimonTableUtils.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/schema/CloneHiveSchemaFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/clone/schema/ClonePaimonSchemaFunction.java
paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/CloneProcedure.java
paimon-hive/paimon-hive-connector-common/src/test/java/org/apache/paimon/hive/procedure/CloneActionITCase.java

Support specifying target prefer file format when migrating orc/csv/json tables to parquet tables
org.apache.paimon.hive.procedure.CloneActionITCase#testMigrateWithPreferFileFormat

[clone] support specifying target prefer file format

---

paimon-core/src/main/java/org/apache/paimon/schema/SchemaManager.java
paimon-core/src/test/java/org/apache/paimon/table/SchemaEvolutionTest.java
paimon-flink/paimon-flink-cdc/src/test/java/org/apache/paimon/flink/sink/cdc/CdcRecordStoreMultiWriteOperatorTest.java
paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FilterPushdownWithSchemaChangeITCase.java

Currently when updating column types, `SchemaManager` does not check if the changed field is a primary key. This PR adds the check.
* `SchemaEvolutionTest`

[core] Primary key types should not be changed

---

.github/workflows/publish_snapshot-jdk17.yml
.github/workflows/publish_snapshot.yml
.github/workflows/utitcase-jdk11.yml
.github/workflows/utitcase-spark-3.x.yml
.github/workflows/utitcase-spark-4.x.yml
.github/workflows/utitcase.yml
paimon-spark/paimon-spark-3.2/pom.xml
paimon-spark/paimon-spark-3.3/pom.xml
paimon-spark/paimon-spark-3.4/pom.xml
paimon-spark/paimon-spark-3.5/pom.xml
paimon-spark/paimon-spark-4.0/pom.xml
paimon-spark/paimon-spark-ut/pom.xml
paimon-spark/paimon-spark3-common/pom.xml
paimon-spark/paimon-spark4-common/pom.xml
pom.xml

Support the use of scala 2.13 to compile and package the paimon-spark module, as in other projects, if scala 2.13 is used, the paimon jar package must also be packaged using scala 2.13.
Rerun the UT and IT for the spark module package compiled on scala 2.13

[spark] support using scala 2.13 to build and deploy with paimon-spark

---

docs/content/iceberg/overview.md
paimon-core/src/main/java/org/apache/paimon/iceberg/metadata/IcebergDataField.java
paimon-core/src/test/java/org/apache/paimon/iceberg/metadata/IcebergDataFieldTest.java

Extended timestamp precision support: Updated IcebergDataField.java to support timestamp types with precision from 4 to 9 (previously limited to 4-6)

[iceberg] Enhance Iceberg timestamp type compatibility with extended precision support

---

paimon-api/src/main/java/org/apache/paimon/Snapshot.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommit.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
paimon-core/src/main/java/org/apache/paimon/table/sink/TableCommitImpl.java
paimon-core/src/test/java/org/apache/paimon/TestFileStore.java
paimon-core/src/test/java/org/apache/paimon/operation/FileDeletionTest.java
paimon-core/src/test/java/org/apache/paimon/operation/TestCommitThread.java
paimon-spark/paimon-spark-3.2/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTest.scala
paimon-spark/paimon-spark-3.3/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTest.scala
paimon-spark/paimon-spark-3.4/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTest.scala
paimon-spark/paimon-spark-3.5/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTest.scala
paimon-spark/paimon-spark-4.0/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTest.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/DeleteFromTableTestBase.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/MergeIntoTableTestBase.scala
paimon-spark/paimon-spark-ut/src/test/scala/org/apache/paimon/spark/sql/UpdateTableTestBase.scala

Currently, there are some issues with the commit kind for non-PK tables under row-level commands:
- UPDATE, DELETE, and MERGE operations that remove old files should be classified as OVERWRITE, not APPEND.
- For non-PK DV (Deletion Vector) tables, only a single snapshot commit is needed (no need two), and it should also be of type OVERWRITE.
Here is a brief summary of commit kinds after modifcation:
- APPEND: 
- insert into table
- place data to PK table's level 0 (e.g. the first step of PK tables' DV generation).
- COMPACT:
- Compact non-PK tables (e.g. merge small files)
- Compact PK tables (e.g. triggered by LSM tree compaction)
- Compact PK DV tables (e.g. triggered by DV generation)
- OVERWRITE:
- insert overwrite (partition) table
- drop partition
- delete, update, and merge on …

[core] Fix the commit kind when performing row-level changes on non-pk table

---

paimon-common/src/main/java/org/apache/paimon/fs/FileIO.java
paimon-common/src/main/java/org/apache/paimon/fs/MultiPartUploadStore.java
paimon-common/src/main/java/org/apache/paimon/fs/MultiPartUploadTwoPhaseOutputStream.java
paimon-common/src/main/java/org/apache/paimon/fs/RenamingTwoPhaseOutputStream.java
paimon-common/src/main/java/org/apache/paimon/fs/TwoPhaseOutputStream.java
paimon-common/src/test/java/org/apache/paimon/fs/RenamingTwoPhaseOutputStreamTest.java
paimon-filesystems/paimon-oss-impl/src/main/java/org/apache/paimon/oss/HadoopCompliantFileIO.java
paimon-filesystems/paimon-oss-impl/src/main/java/org/apache/paimon/oss/OSSFileIO.java
paimon-filesystems/paimon-oss-impl/src/main/java/org/apache/paimon/oss/OSSMultiPartUpload.java
paimon-filesystems/paimon-oss-impl/src/main/java/org/apache/paimon/oss/OssTwoPhaseOutputStream.java
paimon-filesystems/paimon-oss-impl/src/test/java/org/apache/paimon/oss/OssTwoPhaseOutputStreamTest.java
paimon-filesystems/paimon-s3-impl/src/main/java/org/apache/paimon/s3/HadoopCompliantFileIO.java
paimon-filesystems/paimon-s3-impl/src/main/java/org/apache/paimon/s3/S3FileIO.java
paimon-filesystems/paimon-s3-impl/src/main/java/org/apache/paimon/s3/S3MultiPartUpload.java
paimon-filesystems/paimon-s3-impl/src/main/java/org/apache/paimon/s3/S3TwoPhaseOutputStream.java
paimon-filesystems/paimon-s3-impl/src/test/java/org/apache/paimon/s3/S3TwoPhaseOutputStreamTest.java

This PR introduces **TwoPhaseOutputStream** functionality to Paimon. This feature provides:
1. **ACID Guarantees**: Implements two-phase commit mechanism using `TwoPhaseOutputStream` abstraction
2. **Multi-Storage Support**: Robust support for cloud storage (S3, OSS) via multi-part uploads and HDFS via atomic rename operations
**Key Components**:
- `TwoPhaseOutputStream` - Core abstraction for two-phase commit writes
- `MultiPartUploadStore` - Interface for cloud storage multi-part uploads  
- Storage-specific implementations for S3, OSS, and HDFS
- `RenamingTwoPhaseOutputStreamTest`
- `S3TwoPhaseOutputStreamTest`
- `OssTwoPhaseOutputStreamTest`

[core]file io support TwoPhaseOutputStream

---

paimon-python/pypaimon/catalog/rest/rest_catalog.py
paimon-python/pypaimon/tests/predicates_test.py
paimon-python/pypaimon/tests/pvfs_test.py
paimon-python/pypaimon/tests/py36/ao_simple_test.py
paimon-python/pypaimon/tests/rest/rest_server.py
paimon-python/pypaimon/tests/rest/rest_simple_test.py
paimon-python/pypaimon/tests/serializable_test.py

Support ignore_if_exists param when create and drop a database and table.
- RESTSimpleTest.test_create_drop_database_table()

[python] Support ignore_if_exists param for database and table

---

paimon-arrow/src/main/java/org/apache/paimon/arrow/converter/ArrowBatchConverter.java
paimon-arrow/src/main/java/org/apache/paimon/arrow/converter/ArrowPerRowBatchConverter.java
paimon-arrow/src/main/java/org/apache/paimon/arrow/converter/ArrowVectorizedBatchConverter.java

Currently, the VectorSchemaRoot in ArrowBatchConverter is reused, but when interacting with compute engines, they might clean the returned VSR (thus the FieldVector inner structure might be cleaned), so we should support recreate a new VSR.

[arrow] ArrowBatchConverter support reset the reused VectorSchemaRoot

---

paimon-api/src/main/java/org/apache/paimon/types/BlobType.java
paimon-common/src/main/java/org/apache/paimon/utils/Either.java
paimon-core/src/main/java/org/apache/paimon/append/AppendOnlyWriter.java
paimon-core/src/main/java/org/apache/paimon/append/MergeAllBatchReader.java
paimon-core/src/main/java/org/apache/paimon/io/DataFileMeta.java
paimon-core/src/main/java/org/apache/paimon/operation/BaseAppendFileStoreWrite.java
paimon-core/src/main/java/org/apache/paimon/operation/DataEvolutionSplitRead.java
paimon-core/src/main/java/org/apache/paimon/operation/FileStoreCommitImpl.java
paimon-core/src/main/java/org/apache/paimon/schema/SchemaValidation.java
paimon-core/src/main/java/org/apache/paimon/table/source/DataEvolutionSplitGenerator.java
paimon-core/src/test/java/org/apache/paimon/append/AppendOnlyWriterTest.java
paimon-core/src/test/java/org/apache/paimon/append/BlobTableTest.java
paimon-core/src/test/java/org/apache/paimon/format/FileFormatSuffixTest.java
paimon-core/src/test/java/org/apache/paimon/operation/DataEvolutionReadTest.java
paimon-core/src/test/java/org/apache/paimon/table/TableTestBase.java
paimon-format/src/main/resources/META-INF/services/org.apache.paimon.format.FileFormatFactory

Support read and write blob file in data evolution table.
Related PIP: https://cwiki.apache.org/confluence/display/PAIMON/PIP-35:+Introduce+Blob+to+store+multimodal+data

[core] Support blob read and write
